const currentCatalogue = variant => ({...variant,catalogueStatus:'current',priceSource:'user_supplied_working_cost_2026_08_31',taxBasis:'ex_vat'});

export const CALCULATOR_LEGACY_CATALOGUE_IDS=Object.freeze([
  'me508_unconfigured','tp600_unconfigured','tp601_unconfigured','me020_pending',
  'bracket_unconfigured','bracket_150_pending','bracket_200_pending','bracket_250_pending',
  'frame_screw_pending','concrete_fixing_pending','masonry_fixing_pending','timber_fixing_pending','icf_fixing_pending','packer_pending',
  'mini_spider_crane','glass_vacuum_lifter','glazing_robot',
]);

export const CALCULATOR_CATALOGUE_DEFAULTS=Object.freeze([
  ['retrofit_survey','service','Retrofit Survey','per_day','400.00'],['installation_support','service','Installation Support','per_day','350.00'],['installer_labour','labour','Installer labour','per_person_day','350.00'],
  ['installer_mileage','travel','Installer mileage','per_mile','0.55'],['supplier_site_mileage','travel','Supplier / site-visit mileage','per_mile','0.55'],
  ['installation_accommodation','accommodation','Installation accommodation','per_person_night','125.00'],['bnb','accommodation','B&B','per_person_night','100.00'],['hotel','accommodation','Hotel','per_person_night','150.00'],['airbnb','accommodation','Airbnb','per_crew_week','750.00'],
  ['food_allowance','accommodation','Food allowance','per_person_day','30.00'],['stay_away_allowance','accommodation','Staying-away allowance','per_person_night','50.00'],
  ['lifting_telehandler','mechanical_lifting','Telehandler — Day Hire','hire','200.00',currentCatalogue({equipmentType:'telehandler',hirePeriod:'day',productName:'Telehandler — Day Hire',purchaseUnit:'hire',deliveryCost:null,collectionCost:null,defaultMarkupPercent:0})],
  ['lifting_telehandler_week','mechanical_lifting','Telehandler — Week Hire','hire','750.00',currentCatalogue({equipmentType:'telehandler',hirePeriod:'week',productName:'Telehandler — Week Hire',purchaseUnit:'hire',deliveryCost:null,collectionCost:null,defaultMarkupPercent:0})],
  ['lifting_robot','mechanical_lifting','Robot','hire','650.00',currentCatalogue({equipmentType:'robot',productName:'Robot',purchaseUnit:'hire',deliveryCost:'150.00',collectionCost:'150.00',defaultMarkupPercent:0})],
  ['lifting_spider_crane','mechanical_lifting','Spider Crane','hire','550.00',currentCatalogue({equipmentType:'spider_crane',productName:'Spider Crane',purchaseUnit:'hire',deliveryCost:'150.00',collectionCost:'150.00',defaultMarkupPercent:0})],
  ['lifting_crane','mechanical_lifting','Crane','hire',null,currentCatalogue({equipmentType:'crane',productName:'Crane',purchaseUnit:'hire',deliveryCost:null,collectionCost:null,defaultMarkupPercent:0,sourceStatus:'Hire and transport costs require Administration configuration'})],
  ...[['1','100.00'],['2','200.00'],['3','300.00'],['4','400.00']].map(([option,price])=>[`lifting_glass_vacuum_${option}`,'mechanical_lifting',`Glass Vacuum Lifter — Option ${option}`,'hire',price,currentCatalogue({equipmentType:'glass_vacuum_lifter',productName:`Glass Vacuum Lifter — Option ${option}`,purchaseUnit:'hire',deliveryCost:'150.00',collectionCost:'150.00',defaultMarkupPercent:0,temporaryCommercialDefault:true})]),
  ...[['6','175.00'],['8','250.00'],['12','350.00']].map(([yards,price])=>[`equipment_skip_${yards}_yard`,'mechanical_lifting',`${yards} Yard Skip`,'hire',price,currentCatalogue({equipmentType:'skip_hire',capacityYards:Number(yards),productName:`${yards} Yard Skip`,purchaseUnit:'hire',deliveryCost:'0.00',collectionCost:'0.00',defaultMarkupPercent:0})]),
  ['skip_4_yard','skip','4-yard skip','each',null],['skip_6_yard','skip','6-yard skip','each',null],['skip_8_yard','skip','8-yard skip','each',null],['skip_12_yard','skip','12-yard skip','each',null],
  ['me508_501392','illbruck_me508','Illbruck ME508 Airtightness Membrane Internal · 70 mm × 75 m','roll','145.69',currentCatalogue({itemNumber:'501392',manufacturer:'Illbruck',productCode:'ME508',productName:'Illbruck ME508 Airtightness Membrane Internal',role:'internal installation membrane',rollLengthM:75,rollWidthCode:'EW-70',rollWidthMm:70,rollsPerBox:1,purchaseUnit:'roll'})],
  ['me508_501393','illbruck_me508','Illbruck ME508 Airtightness Membrane Internal · 100 mm × 75 m','roll','190.61',currentCatalogue({itemNumber:'501393',manufacturer:'Illbruck',productCode:'ME508',productName:'Illbruck ME508 Airtightness Membrane Internal',role:'internal installation membrane',rollLengthM:75,rollWidthCode:'EW-100',rollWidthMm:100,rollsPerBox:1,purchaseUnit:'roll'})],
  ['me508_500252','illbruck_me508','Illbruck ME508 Airtightness Membrane Internal · 140 mm × 25 m','roll','89.20',currentCatalogue({itemNumber:'500252',manufacturer:'Illbruck',productCode:'ME508',productName:'Illbruck ME508 Airtightness Membrane Internal',role:'internal installation membrane',rollLengthM:25,rollWidthCode:'EW-140',rollWidthMm:140,rollsPerBox:1,purchaseUnit:'roll'})],
  ['me508_500290','illbruck_me508','Illbruck ME508 Airtightness Membrane Internal · 200 mm × 25 m','roll','128.62',currentCatalogue({itemNumber:'500290',manufacturer:'Illbruck',productCode:'ME508',productName:'Illbruck ME508 Airtightness Membrane Internal',role:'internal installation membrane',rollLengthM:25,rollWidthCode:'EW-200',rollWidthMm:200,rollsPerBox:1,purchaseUnit:'roll'})],
  ['me508_500540','illbruck_me508','Illbruck ME508 Airtightness Membrane Internal · 250 mm × 25 m','roll','171.33',currentCatalogue({itemNumber:'500540',manufacturer:'Illbruck',productCode:'ME508',productName:'Illbruck ME508 Airtightness Membrane Internal',role:'internal installation membrane',rollLengthM:25,rollWidthCode:'EW-250',rollWidthMm:250,rollsPerBox:1,purchaseUnit:'roll'})],
  ...[[100,'77.23'],[140,'68.07'],[200,'158.57'],[250,'245.30']].map(([width,price])=>[`me501_${width}_25`,'illbruck_me501',`Illbruck ME501 External Membrane · ${width} mm × 25 m`,'roll',price,currentCatalogue({manufacturer:'Illbruck',productCode:'ME501',productName:'Illbruck ME501 External Membrane',role:'external installation membrane',rollLengthM:25,rollWidthMm:width,rollWidthCode:`ME501-${width}`,rollsPerBox:1,purchaseUnit:'roll'})]),
  ['tp600_20_3_7_8','illbruck_tp600','Illbruck TP600 Compriband · 20 mm · 3–7 mm · 8 m','roll','25.00',currentCatalogue({manufacturer:'Illbruck',productCode:'TP600',productName:'Illbruck TP600 Compriband',tapeWidthMm:20,jointGapMinMm:3,jointGapMaxMm:7,rollLengthM:8,purchaseUnit:'roll'})],
  ['tp600_20_5_10_5_6','illbruck_tp600','Illbruck TP600 Compriband · 20 mm · 5–10 mm · 5.6 m','roll','22.62',currentCatalogue({manufacturer:'Illbruck',productCode:'TP600',productName:'Illbruck TP600 Compriband',tapeWidthMm:20,jointGapMinMm:5,jointGapMaxMm:10,rollLengthM:5.6,purchaseUnit:'roll'})],
  ['tp600_ng_20_7_15_3_3','illbruck_tp600','Illbruck TP600 Compriband NG · 20 mm · 7–15 mm · 3.3 m','roll','16.78',currentCatalogue({manufacturer:'Illbruck',productCode:'TP600 NG',productName:'Illbruck TP600 Compriband',tapeWidthMm:20,jointGapMinMm:7,jointGapMaxMm:15,rollLengthM:3.3,purchaseUnit:'roll',replacementOption:true})],
  ['tp600_20_8_15_3_3','illbruck_tp600','Illbruck TP600 Compriband · 20 mm · 8–15 mm · 3.3 m','roll','21.72',currentCatalogue({manufacturer:'Illbruck',productCode:'TP600',productName:'Illbruck TP600 Compriband',tapeWidthMm:20,jointGapMinMm:8,jointGapMaxMm:15,rollLengthM:3.3,purchaseUnit:'roll'})],
  ['tp600_ng_22_9_18_6_5','illbruck_tp600','Illbruck TP600 Compriband NG · 22 mm · 9–18 mm · 6.5 m','roll','59.47',currentCatalogue({manufacturer:'Illbruck',productCode:'TP600 NG',productName:'Illbruck TP600 Compriband',tapeWidthMm:22,jointGapMinMm:9,jointGapMaxMm:18,rollLengthM:6.5,purchaseUnit:'roll',replacementOption:true})],
  ['fm330_750','illbruck_fm330','Illbruck FM330 PU Foam · Box of 12 × 750 ml cans','box','101.64',currentCatalogue({manufacturer:'Illbruck',productCode:'FM330',productName:'Illbruck FM330 PU Foam',canVolumeMl:750,unitsPerPack:12,purchaseUnit:'box',jointDepthMm:92,jointWidthMm:20,foamYieldLitresPerCan:45})],
  ['me902_500','illbruck_me902','Illbruck ME902 Primer (Spray Can) · 500 ml','can','16.16',currentCatalogue({manufacturer:'Illbruck',productCode:'ME902',productName:'Illbruck ME902 Primer (Spray Can)',canVolumeMl:500,unitsPerPack:1,purchaseUnit:'can',coverageMetresPerUnit:50,coverageBasis:'40 mm application strip',appliesTo:'ME508',sourceStatus:'Current manufacturer product/TDS evidence',sourceUrl:'https://www.illbruck.com/en-gb/products-systems/product-finder/me902-butyl-bitumen-spray-primer/'})],
  ['ab005','tool','Illbruck AB005 Cutting Shears','each','20.22',currentCatalogue({manufacturer:'Illbruck',productCode:'AB005',productName:'Illbruck AB005 Cutting Shears',unitsPerPack:1,purchaseUnit:'each'})],
  ['aa270','tool','Illbruck AA270 Foam Gun','each','67.02',currentCatalogue({manufacturer:'Illbruck',productCode:'AA270',productName:'Illbruck AA270 Foam Gun',unitsPerPack:1,purchaseUnit:'each'})],
  ...[[100,'0.55'],[150,'0.65'],[200,'0.75'],[250,'0.87']].map(([length,price])=>[`bracket_${length}`,'bracket',`${length} mm Fixing Bracket`,'each',price,currentCatalogue({category:'Bracket',productCode:`BRACKET-${length}`,bracketLengthMm:length,purchaseUnit:'each',unitsPerPack:1})]),
  ['frame_screw_turbo_tx_5x70','frame_screw','Turbo TX TX Double-Countersunk Multipurpose Screw · 5 mm × 70 mm','box','6.41',currentCatalogue({category:'Frame Screw',manufacturer:'Turbo TX',productCode:'752VV',diameterMm:5,lengthMm:70,purchaseUnit:'box',packQuantity:100,unitsPerPack:100,referenceGrossPriceAmount:'7.69',referenceVatPercent:20,referencePriceSource:'Screwfix',referencePriceSourceUrl:'https://www.screwfix.com/c/screws-nails-fixings/woodscrews/cat840066?brand=turbo_tx&headtype=double_countersunk&sort_by=-brand'})],
]);

export const CALCULATION_RULE_DEFAULTS=Object.freeze({
  new_build_units_per_day_two_person:'7',refurbishment_units_per_day_two_person:'3',waste_percent:'10',
  day_one_installation_output:'0',target_return_home:'18:00',latest_return_home:'23:00',
  ggf_2016_replacement_pvcu_baseline:{name:'GGF 2016 Replacement PVC-U Baseline',version:1,advisory:true,applicability:{projectTypes:['refurbishment'],frameMaterials:['PVC-U'],regions:['England','Wales'],excluded:['new_build','aluminium','timber','steel','curtain_walling','specialist_sliding','bifold','Scotland']},source:{name:'GGF: A Guide to Good Practice — Installation of Replacement Windows and Doors',edition:'April 2016',section:'3.15.1 PVC-U windows and doors',url:'https://www.ggf.org.uk/wp-content/uploads/securepdfs/2018/06/20.3-Window-and-Door-GPG-April-2016.pdf'},rules:{secureAllFourSidesWherePossible:true,cornerOffsetMinMm:150,cornerOffsetMaxMm:250,mullionTransomExclusionMm:150,maxIntermediateSpacingMm:600,minimumFixingsPerJamb:2,headSillWidthBands:[{maxWidthMm:1200,intermediatePerSide:0},{minWidthMm:1201,maxWidthMm:2400,intermediatePerSide:1},{minWidthMm:2401,maxWidthMm:3600,intermediatePerSide:2}],aboveWidthMmRequiresReview:3600}},
  installation_materials_v1:{name:'Installation Materials defaults',version:2,defaultContingencyPercent:15,defaultBracketLengthMm:250,frameScrewsPerBracket:2,substrateFixingsPerBracket:1,packerCalculationMode:'manual',packersPerFixingPosition:null,packersPerFrame:null,buildingTypes:{timber_frame:{label:'Timber Frame',fixingsPerBracket:null,source:'Structural fixing product/rule required'},brick_block:{label:'Brick & Block',fixingsPerBracket:1,source:'QuoteSuite approved bracket assembly rule'},icf:{label:'ICF',fixingsPerBracket:1,source:'QuoteSuite approved bracket assembly rule'},concrete:{label:'Concrete',fixingsPerBracket:1,source:'QuoteSuite approved bracket assembly rule'}},frameFixingRules:{'PVC-U':{key:'ggf_pvcu',source:'GGF/default',cornerOffsetMinMm:150,cornerOffsetMaxMm:250,maxIntermediateSpacingMm:600,minimumFixingsPerJamb:2,allFourSides:true,provenance:{name:'GGF: A Guide to Good Practice — Installation of Replacement Windows and Doors',edition:'April 2016',section:'3.15.1 PVC-U windows and doors'}},Timber:{key:'ggf_timber',source:'GGF/default',cornerOffsetMinMm:150,cornerOffsetMaxMm:250,maxIntermediateSpacingMm:600,minimumFixingsPerJamb:2,allFourSides:false,centralHeadSillAboveWidthMm:1800,provenance:{file:'ggf-installation-guide.pdf',section:'3 — Timber Windows and Doors',printedPage:24}},Aluminium:{key:'ggf_aluminium',source:'GGF/default',cornerOffsetMinMm:100,cornerOffsetMaxMm:150,maxIntermediateSpacingMm:600,minimumFixingsPerJamb:2,allFourSides:true,centralHeadSillAboveWidthMm:1800,provenance:{file:'ggf-installation-guide.pdf',section:'3 — Aluminium Windows and Doors',printedPage:25}},'Steel — hot rolled solid':{key:'ggf_steel_hot_rolled',source:'GGF/default',cornerOffsetMinMm:175,cornerOffsetMaxMm:175,maxIntermediateSpacingMm:750,allFourSides:true,provenance:{file:'ggf-installation-guide.pdf',section:'3 — Steel Windows',printedPage:25}},'Steel — cold formed hollow':{key:'ggf_steel_cold_formed',source:'GGF/default',cornerOffsetMinMm:200,cornerOffsetMaxMm:200,maxIntermediateSpacingMm:900,allFourSides:true,provenance:{file:'ggf-installation-guide.pdf',section:'3 — Steel Windows',printedPage:25}}},precedence:['manufacturer','product','admin_installation_rule','GGF/default','estimate_override'],packerProvenance:{file:'ggf-installation-guide.pdf',section:'3 — Installation Packers',printedPage:27,note:'Legacy evidence only; no active new-costing product is configured.'}},
  installation_programme_v1:{name:'Stage 6 Installation programme and rates',version:2,workingDays:['monday','tuesday','wednesday','thursday','friday'],workingStart:'08:00',workingFinish:'17:00',productiveHoursPerDay:8,breaksIncludedInProductivity:true,installerDayRate:'350.00',fullDayLabourOnly:true,standardUnitsPerDayByCrew:{'2':7,'4':12},installationTypeRules:{new_build:{label:'New Build',standardUnitsPerDayByCrew:{'2':7,'4':12},deliveryOffloadSetOutDays:0,snaggingDays:0,removalRequired:false},refurbishment_rip_out_replace:{label:'Refurbishment — Rip Out & Replace',standardUnitsPerDayByCrew:{'2':3,'4':6},deliveryOffloadSetOutDays:1,snaggingDays:1,removalRequired:true},refurbishment_straight_install:{label:'Refurbishment — Straight Install / No Removal',standardUnitsPerDayByCrew:{'2':7,'4':12},deliveryOffloadSetOutDays:0,snaggingDays:0,removalRequired:false}},fourPersonRecommendationThresholdUnits:28,splitCrewPermitted:true,specialistFamilies:['lift_and_slide','sliding_door','bifold'],specialistWidthThresholdMm:2500,specialistUnderThresholdCrew:3,specialistUnderThresholdHours:3,specialistAtOrAboveThresholdCrew:4,specialistAtOrAboveThresholdHours:4,kitDurationChoicesHours:[4,8,12,16,24],stayAwayThresholdMinutes:90,mileageRate:'0.55',foodPerPersonDay:'30.00',accommodationPerPersonNight:'125.00',genericStayAwayAllowance:'0.00',travelLabourCharge:false,supportDayRate:'350.00',supportAffectsProductivity:false,surveyDayRate:'400.00',cillInstallationRate:'25.00',latestReturnHomeMinutes:1380,mobilisationSetOutHours:null,teamSelectionAuthority:'estimator',skipRetrofitRecommendation:true,liftingStatus:'review_required',provenance:{type:'confirmed_quote_suite_business_rules',confirmedAt:'2026-09-06'}},
});

export const PACKAGE_RULE_DEFAULTS=Object.freeze({
  supply_only:['products','extras','transport'],
  support:['products','extras','transport','survey','installation_support','travel'],
  full_installation:['products','extras','transport','installation','sealing','brackets','travel','accommodation','skip'],
});
