export const CALCULATOR_CATALOGUE_DEFAULTS=Object.freeze([
  ['retrofit_survey','service','Retrofit Survey','per_day','400.00'],['installation_support','service','Installation Support','per_day','350.00'],['installer_labour','labour','Installer labour','per_person_day','350.00'],
  ['installer_mileage','travel','Installer mileage','per_mile','0.55'],['supplier_site_mileage','travel','Supplier / site-visit mileage','per_mile','0.55'],
  ['installation_accommodation','accommodation','Installation accommodation','per_person_night','125.00'],['bnb','accommodation','B&B','per_person_night','100.00'],['hotel','accommodation','Hotel','per_person_night','150.00'],['airbnb','accommodation','Airbnb','per_crew_week','750.00'],
  ['food_allowance','accommodation','Food allowance','per_person_day','30.00'],['stay_away_allowance','accommodation','Staying-away allowance','per_person_night','50.00'],
  ['mini_spider_crane','mechanical_lifting','Mini spider crane','hire',null],['glass_vacuum_lifter','mechanical_lifting','Glass vacuum lifter','hire',null],['glazing_robot','mechanical_lifting','Glazing robot','hire',null],
  ['skip_4_yard','skip','4-yard skip','each',null],['skip_6_yard','skip','6-yard skip','each',null],['skip_8_yard','skip','8-yard skip','each',null],['skip_12_yard','skip','12-yard skip','each',null],
  ['tp600_unconfigured','illbruck_tp600','Illbruck TP600 — variant requires reference data','roll',null],
  ['me508_501392','illbruck_me508','Illbruck ME508 501392 · EW-70 · 75 m · 1 roll/box','box',null,{itemNumber:'501392',productName:'Illbruck ME508',role:'internal window/door membrane',rollLengthM:75,rollWidthCode:'EW-70',rollWidthMm:70,rollsPerBox:1,membraneThicknessMm:0.5,pricingUnit:'box'}],
  ['me508_501393','illbruck_me508','Illbruck ME508 501393 · EW-100 · 75 m · 1 roll/box','box',null,{itemNumber:'501393',productName:'Illbruck ME508',role:'internal window/door membrane',rollLengthM:75,rollWidthCode:'EW-100',rollWidthMm:100,rollsPerBox:1,membraneThicknessMm:0.5,pricingUnit:'box'}],
  ['me508_500252','illbruck_me508','Illbruck ME508 500252 · EW-140 · 25 m · 2 rolls/box','box',null,{itemNumber:'500252',productName:'Illbruck ME508',role:'internal window/door membrane',rollLengthM:25,rollWidthCode:'EW-140',rollWidthMm:140,rollsPerBox:2,membraneThicknessMm:0.5,pricingUnit:'box'}],
  ['me508_500290','illbruck_me508','Illbruck ME508 500290 · EW-200 · 25 m · 1 roll/box','box',null,{itemNumber:'500290',productName:'Illbruck ME508',role:'internal window/door membrane',rollLengthM:25,rollWidthCode:'EW-200',rollWidthMm:200,rollsPerBox:1,membraneThicknessMm:0.5,pricingUnit:'box'}],
  ['me508_500540','illbruck_me508','Illbruck ME508 500540 · EW-250 · 25 m · 1 roll/box','box',null,{itemNumber:'500540',productName:'Illbruck ME508',role:'internal window/door membrane',rollLengthM:25,rollWidthCode:'EW-250',rollWidthMm:250,rollsPerBox:1,membraneThicknessMm:0.5,pricingUnit:'box'}],
  ['tp601_unconfigured','illbruck_tp601','Illbruck TP601 — variant requires reference data','roll',null],
  ['me020_pending','illbruck_me020','Illbruck ME020 — technical variant pending supplied specification','roll',null,{manufacturer:'illbruck',productName:'ME020',sourceStatus:'Pending product specification'}],
  ['fm330_750','illbruck_fm330','Illbruck FM330 Pro Foam Air Seal · 750 ml · 12/carton','carton',null,{manufacturer:'illbruck',productName:'FM330',canVolumeMl:750,unitsPerPack:12,source:{file:'Windows_Facades Product Catalogue Brochure (en-GB).pdf',page:12}}],
  ['me902_500','illbruck_me902','Illbruck ME902 spray primer · 500 ml · 12/carton','carton',null,{manufacturer:'illbruck',productName:'ME902',canVolumeMl:500,unitsPerPack:12,source:{file:'Windows_Facades Product Catalogue Brochure (en-GB).pdf',page:19}}],
  ['ab005','tool','Illbruck AB005 Membrane Shears','unit',null,{manufacturer:'illbruck',productName:'AB005',sourceStatus:'User-corrected product identity; technical sheet pending',source:{type:'user_correction',date:'2026-08-21'}}],
  ['aa270','tool','Illbruck AA270 Foam Gun Ultra','unit',null,{manufacturer:'illbruck',productName:'AA270',unitsPerPack:1,source:{file:'Windows_Facades Product Catalogue Brochure (en-GB).pdf',page:20}}],
  ...[150,200,250].map(length=>[`bracket_${length}_pending`,'bracket',`${length} mm fixing bracket — Pending product specification`,'pack',null,{category:'Bracket',bracketLengthMm:length,packQuantity:null,sourceStatus:'Pending product specification'}]),
  ['frame_screw_pending','frame_screw','Frame/bracket screw — Pending product specification','pack',null,{category:'Frame Screw',packQuantity:null,sourceStatus:'Pending product specification'}],
  ['concrete_fixing_pending','concrete_screw','Concrete fixing — Pending product specification','pack',null,{category:'Concrete Screw',packQuantity:null,sourceStatus:'Pending product specification'}],
  ['masonry_fixing_pending','masonry_fixing','Brick & Block fixing — Pending product specification','pack',null,{category:'Masonry Fixing',packQuantity:null,sourceStatus:'Pending product specification'}],
  ['timber_fixing_pending','timber_fixing','Timber Frame fixing — Pending product specification','pack',null,{category:'Timber Fixing',packQuantity:null,sourceStatus:'Pending product specification'}],
  ['icf_fixing_pending','icf_fixing','ICF fixing system — Pending product specification','pack',null,{category:'ICF Fixing',packQuantity:null,sourceStatus:'Pending product specification'}],
  ['packer_pending','packer','Installation packer — Pending product specification','pack',null,{category:'Packer',packQuantity:null,sourceStatus:'Pending product specification'}],
]);

export const CALCULATION_RULE_DEFAULTS=Object.freeze({
  new_build_units_per_day_two_person:'7',refurbishment_units_per_day_two_person:'3',waste_percent:'10',
  day_one_installation_output:'0',target_return_home:'18:00',latest_return_home:'23:00',
  ggf_2016_replacement_pvcu_baseline:{name:'GGF 2016 Replacement PVC-U Baseline',version:1,advisory:true,applicability:{projectTypes:['refurbishment'],frameMaterials:['PVC-U'],regions:['England','Wales'],excluded:['new_build','aluminium','timber','steel','curtain_walling','specialist_sliding','bifold','Scotland']},source:{name:'GGF: A Guide to Good Practice — Installation of Replacement Windows and Doors',edition:'April 2016',section:'3.15.1 PVC-U windows and doors',url:'https://www.ggf.org.uk/wp-content/uploads/securepdfs/2018/06/20.3-Window-and-Door-GPG-April-2016.pdf'},rules:{secureAllFourSidesWherePossible:true,cornerOffsetMinMm:150,cornerOffsetMaxMm:250,mullionTransomExclusionMm:150,maxIntermediateSpacingMm:600,minimumFixingsPerJamb:2,headSillWidthBands:[{maxWidthMm:1200,intermediatePerSide:0},{minWidthMm:1201,maxWidthMm:2400,intermediatePerSide:1},{minWidthMm:2401,maxWidthMm:3600,intermediatePerSide:2}],aboveWidthMmRequiresReview:3600}},
  installation_materials_v1:{name:'Installation Materials defaults',version:1,defaultContingencyPercent:15,defaultBracketLengthMm:200,frameScrewsPerBracket:3,packerCalculationMode:'per_fixing_position',packersPerFixingPosition:null,packersPerFrame:null,buildingTypes:{timber_frame:{label:'Timber Frame',fixingsPerBracket:null,source:'Admin configuration required'},brick_block:{label:'Brick & Block',fixingsPerBracket:1,source:'QuoteSuite user installation rule'},icf:{label:'ICF',fixingsPerBracket:null,source:'Pending product specification'},concrete:{label:'Concrete',fixingsPerBracket:2,source:'QuoteSuite user installation rule'}},frameFixingRules:{'PVC-U':{key:'ggf_pvcu',source:'GGF/default',cornerOffsetMinMm:150,cornerOffsetMaxMm:250,maxIntermediateSpacingMm:600,minimumFixingsPerJamb:2,allFourSides:true,provenance:{file:'ggf-installation-guide.pdf',section:'3 — PVC-U Windows and Doors',printedPage:23}},Timber:{key:'ggf_timber',source:'GGF/default',cornerOffsetMinMm:150,cornerOffsetMaxMm:250,maxIntermediateSpacingMm:600,minimumFixingsPerJamb:2,allFourSides:false,centralHeadSillAboveWidthMm:1800,provenance:{file:'ggf-installation-guide.pdf',section:'3 — Timber Windows and Doors',printedPage:24}},Aluminium:{key:'ggf_aluminium',source:'GGF/default',cornerOffsetMinMm:100,cornerOffsetMaxMm:150,maxIntermediateSpacingMm:600,minimumFixingsPerJamb:2,allFourSides:true,centralHeadSillAboveWidthMm:1800,provenance:{file:'ggf-installation-guide.pdf',section:'3 — Aluminium Windows and Doors',printedPage:25}},'Steel — hot rolled solid':{key:'ggf_steel_hot_rolled',source:'GGF/default',cornerOffsetMinMm:175,cornerOffsetMaxMm:175,maxIntermediateSpacingMm:750,allFourSides:true,provenance:{file:'ggf-installation-guide.pdf',section:'3 — Steel Windows',printedPage:25}},'Steel — cold formed hollow':{key:'ggf_steel_cold_formed',source:'GGF/default',cornerOffsetMinMm:200,cornerOffsetMaxMm:200,maxIntermediateSpacingMm:900,allFourSides:true,provenance:{file:'ggf-installation-guide.pdf',section:'3 — Steel Windows',printedPage:25}}},precedence:['manufacturer','product','admin_installation_rule','GGF/default','estimate_override'],packerProvenance:{file:'ggf-installation-guide.pdf',section:'3 — Installation Packers',printedPage:27,note:'Packers adjacent to fixing positions; quantity remains configurable.'}},
  installation_programme_v1:{name:'Stage 6 Installation programme and rates',version:1,workingDays:['monday','tuesday','wednesday','thursday','friday'],workingStart:'08:00',workingFinish:'17:00',productiveHoursPerDay:8,breaksIncludedInProductivity:true,installerDayRate:'350.00',fullDayLabourOnly:true,standardUnitsPerDayByCrew:{'2':7,'4':12},fourPersonRecommendationThresholdUnits:28,splitCrewPermitted:true,specialistFamilies:['lift_and_slide','sliding_door','bifold'],specialistWidthThresholdMm:2500,specialistUnderThresholdCrew:3,specialistUnderThresholdHours:3,specialistAtOrAboveThresholdCrew:4,specialistAtOrAboveThresholdHours:4,kitDurationChoicesHours:[4,8,12,16,24],stayAwayThresholdMinutes:90,mileageRate:'0.55',foodPerPersonDay:'30.00',accommodationPerPersonNight:'125.00',genericStayAwayAllowance:'0.00',travelLabourCharge:false,supportDayRate:'350.00',supportAffectsProductivity:false,surveyDayRate:'400.00',cillInstallationRate:'25.00',latestReturnHomeMinutes:1380,mobilisationSetOutHours:null,teamSelectionAuthority:'estimator',skipRetrofitRecommendation:true,liftingStatus:'review_required',provenance:{type:'confirmed_quote_suite_business_rules',confirmedAt:'2026-08-21'}},
});

export const PACKAGE_RULE_DEFAULTS=Object.freeze({
  supply_only:['products','extras','transport'],
  support:['products','extras','transport','survey','installation_support','travel'],
  full_installation:['products','extras','transport','installation','sealing','brackets','mechanical_lifting','travel','accommodation','skip'],
});
