import { randomUUID } from 'node:crypto';
import { INSTALLATION_CAPABILITIES } from './installationProgramme.js';

const parse = value => { try { return JSON.parse(value || '{}'); } catch { return {}; } };
const capabilities = value => [...new Set((Array.isArray(value) ? value : []).filter(item => INSTALLATION_CAPABILITIES.includes(item)))];
const companyMap = row => row && ({ id:row.id,name:row.name,address:parse(row.address_json),postcode:row.postcode,telephone:row.telephone,email:row.email,notes:row.notes,dayRate:row.day_rate,active:!!row.active,version:row.version });
const installerMap = row => row && ({ id:row.id,companyId:row.company_id,name:row.name,mobile:row.mobile,email:row.email,address:parse(row.address_json),postcode:row.postcode,dayRate:row.day_rate,capabilities:parse(row.capabilities_json),active:!!row.active,version:row.version });
const teamMap = row => row && ({ id:row.id,companyId:row.company_id,companyName:row.company_name,name:row.name,normalCrewSize:row.normal_crew_size,baseAddress:parse(row.base_address_json),basePostcode:row.base_postcode,capabilities:parse(row.capabilities_json),active:!!row.active,version:row.version,installerIds:parse(row.installer_ids_json || '[]') });
const required = (value, label) => { const result=String(value??'').trim(); if(!result)throw Object.assign(new Error(`${label} is required.`),{code:'invalid_installation_workforce'}); return result; };
const rate = value => { if(value==null||value==='')return null;if(!/^\d+(?:\.\d{1,2})?$/.test(String(value)))throw Object.assign(new Error('Day rate must be a non-negative amount with no more than two decimal places.'),{code:'invalid_installation_workforce'});return String(value); };

export function createInstallationWorkforceService(db) {
  const list = async () => {
    const [companies,installers,teams] = await Promise.all([
      db.all('SELECT * FROM installation_companies ORDER BY active DESC,name'),
      db.all('SELECT * FROM installation_installers ORDER BY active DESC,name'),
      db.all(`SELECT t.*,c.name company_name,(SELECT json_group_array(installer_id) FROM installation_team_members m WHERE m.team_id=t.id) installer_ids_json FROM installation_teams t JOIN installation_companies c ON c.id=t.company_id ORDER BY t.active DESC,t.name`),
    ]);
    return { companies:companies.map(companyMap),installers:installers.map(installerMap),teams:teams.map(teamMap),capabilities:INSTALLATION_CAPABILITIES };
  };
  return {
    list,
    async saveCompany(input) { const id=input.id||randomUUID(),now=new Date().toISOString(),existing=await db.get('SELECT id FROM installation_companies WHERE id=?',id);await db.run(existing?'UPDATE installation_companies SET name=?,address_json=?,postcode=?,telephone=?,email=?,notes=?,day_rate=?,active=?,version=version+1,updated_at=? WHERE id=?':'INSERT INTO installation_companies(name,address_json,postcode,telephone,email,notes,day_rate,active,version,created_at,updated_at,id) VALUES(?,?,?,?,?,?,?,?,1,?,?,?)',required(input.name,'Company name'),JSON.stringify(input.address||{}),input.postcode||null,input.telephone||null,input.email||null,input.notes||null,rate(input.dayRate),input.active===false?0:1,...(existing?[now,id]:[now,now,id]));return list(); },
    async saveInstaller(input) { const id=input.id||randomUUID(),companyId=required(input.companyId,'Installation Company'),now=new Date().toISOString();if(!await db.get('SELECT id FROM installation_companies WHERE id=?',companyId))throw Object.assign(new Error('Installation Company was not found.'),{code:'invalid_installation_workforce'});const existing=await db.get('SELECT id FROM installation_installers WHERE id=?',id);await db.run(existing?'UPDATE installation_installers SET company_id=?,name=?,mobile=?,email=?,address_json=?,postcode=?,day_rate=?,capabilities_json=?,active=?,version=version+1,updated_at=? WHERE id=?':'INSERT INTO installation_installers(company_id,name,mobile,email,address_json,postcode,day_rate,capabilities_json,active,version,created_at,updated_at,id) VALUES(?,?,?,?,?,?,?,?,?,1,?,?,?)',companyId,required(input.name,'Installer name'),input.mobile||null,input.email||null,JSON.stringify(input.address||{}),input.postcode||null,rate(input.dayRate),JSON.stringify(capabilities(input.capabilities)),input.active===false?0:1,...(existing?[now,id]:[now,now,id]));return list(); },
    async saveTeam(input) { const id=input.id||randomUUID(),companyId=required(input.companyId,'Installation Company'),crew=Number(input.normalCrewSize);if(!Number.isInteger(crew)||crew<1)throw Object.assign(new Error('Normal crew size must be a positive integer.'),{code:'invalid_installation_workforce'});const installerIds=[...new Set(Array.isArray(input.installerIds)?input.installerIds:[])],now=new Date().toISOString();for(const installerId of installerIds)if(!await db.get('SELECT id FROM installation_installers WHERE id=? AND company_id=?',installerId,companyId))throw Object.assign(new Error('Every team member must belong to the selected Installation Company.'),{code:'invalid_installation_workforce'});const existing=await db.get('SELECT id FROM installation_teams WHERE id=?',id);await db.exec('BEGIN IMMEDIATE');try{await db.run(existing?'UPDATE installation_teams SET company_id=?,name=?,normal_crew_size=?,base_address_json=?,base_postcode=?,capabilities_json=?,active=?,version=version+1,updated_at=? WHERE id=?':'INSERT INTO installation_teams(company_id,name,normal_crew_size,base_address_json,base_postcode,capabilities_json,active,version,created_at,updated_at,id) VALUES(?,?,?,?,?,?,?,1,?,?,?)',companyId,required(input.name,'Team name'),crew,JSON.stringify(input.baseAddress||{}),input.basePostcode||null,JSON.stringify(capabilities(input.capabilities)),input.active===false?0:1,...(existing?[now,id]:[now,now,id]));await db.run('DELETE FROM installation_team_members WHERE team_id=?',id);for(const installerId of installerIds)await db.run('INSERT INTO installation_team_members(team_id,installer_id,created_at) VALUES(?,?,?)',id,installerId,now);await db.exec('COMMIT');}catch(error){await db.exec('ROLLBACK');throw error;}return list(); },
  };
}
