import { useEffect, useState } from "react";
import { projectCalculatorLabApi } from "./api/projectCalculatorLabApi";
import type { CalculatorAdminConfiguration } from "./domain/projectCalculatorLab.types";
import InstallationWorkforceAdmin from "./InstallationWorkforceAdmin";

const groups = [
  ["Cost Catalogue", ["service", "labour", "travel", "accommodation", "mechanical_lifting", "skip"]],
  ["Sealing & Airtightness", ["illbruck_tp600", "illbruck_tp601", "illbruck_me508", "illbruck_me020", "illbruck_fm330", "illbruck_me902"]],
  ["Mechanical Fixings", ["bracket", "frame_screw", "concrete_screw", "masonry_fixing", "timber_fixing", "icf_fixing", "packer"]],
  ["Installation Tools", ["tool"]],
] as const;

export default function CalculatorAdminCatalogue() {
  const [config,setConfig]=useState<CalculatorAdminConfiguration|null>(null),[message,setMessage]=useState(""),[loadError,setLoadError]=useState("");
  useEffect(()=>{let active=true;void projectCalculatorLabApi.getAdminConfiguration().then(value=>{if(active)setConfig(value);}).catch(error=>{if(active)setLoadError(error instanceof Error?error.message:"Calculator configuration could not be loaded.");});return()=>{active=false;};},[]);
  if(loadError)return <div className="ui-card calculator-lab__card" role="alert"><h3>Calculator configuration unavailable</h3><p>{loadError}</p></div>;
  if(!config)return <p>Loading calculator configuration…</p>;
  const savePrice=async(id:string,label:string,priceAmount:string)=>{try{setConfig(await projectCalculatorLabApi.updateCatalogueItem(id,{priceAmount}));setMessage(`${label} saved`);}catch(error){setMessage(error instanceof Error?error.message:"Catalogue value could not be saved.");}};
  const installationRule=(config.rules.installation_materials_v1?.value??{}) as Record<string,any>,programmeRule=(config.rules.installation_programme_v1?.value??{}) as Record<string,any>;
  const saveMaterialRule=async(key:string,value:string)=>{setConfig(await projectCalculatorLabApi.updateRule("installation_materials_v1",{...installationRule,[key]:value===""?null:Number(value)}));setMessage("Installation Materials defaults saved. Existing Estimates were not changed.");};
  const saveProgrammeRule=async(key:string,value:string)=>{setConfig(await projectCalculatorLabApi.updateRule("installation_programme_v1",{...programmeRule,[key]:Number(value)}));setMessage("Installation programme defaults saved for future Estimates.");};
  const building=installationRule.buildingTypes??{};
  const saveBuilding=async(key:string,value:string)=>{setConfig(await projectCalculatorLabApi.updateRule("installation_materials_v1",{...installationRule,buildingTypes:{...building,[key]:{...building[key],fixingsPerBracket:value===""?null:Number(value)}}}));setMessage("Building-type rule saved for future Estimates.");};
  return <div className="calculator-admin"><p>Administration prices and rules initialise new Estimate snapshots. Existing Estimates remain unchanged.</p><InstallationWorkforceAdmin />
    <section className="ui-card calculator-lab__card"><h3>Installation Programme &amp; Rates</h3><div className="calculator-lab__form"><label>Installer / full day<input className="ui-input" defaultValue={programmeRule.installerDayRate??350} onBlur={event=>void saveProgrammeRule("installerDayRate",event.currentTarget.value)} /></label><label>2-person standard units/day<input className="ui-input" value={programmeRule.standardUnitsPerDayByCrew?.["2"]??7} readOnly /></label><label>4-person standard units/day<input className="ui-input" defaultValue={programmeRule.standardUnitsPerDayByCrew?.["4"]??12} onBlur={event=>void projectCalculatorLabApi.updateRule("installation_programme_v1",{...programmeRule,standardUnitsPerDayByCrew:{...programmeRule.standardUnitsPerDayByCrew,"4":Number(event.currentTarget.value)}}).then(setConfig)} /></label><label>Mileage / mile<input className="ui-input" defaultValue={programmeRule.mileageRate??0.55} onBlur={event=>void saveProgrammeRule("mileageRate",event.currentTarget.value)} /></label><label>Food / person/day<input className="ui-input" defaultValue={programmeRule.foodPerPersonDay??30} onBlur={event=>void saveProgrammeRule("foodPerPersonDay",event.currentTarget.value)} /></label><label>Accommodation / person/night<input className="ui-input" defaultValue={programmeRule.accommodationPerPersonNight??125} onBlur={event=>void saveProgrammeRule("accommodationPerPersonNight",event.currentTarget.value)} /></label><label>Stay-away threshold minutes<input className="ui-input" defaultValue={programmeRule.stayAwayThresholdMinutes??90} onBlur={event=>void saveProgrammeRule("stayAwayThresholdMinutes",event.currentTarget.value)} /></label></div><small>Monday–Friday · 08:00–17:00 · eight productive hours · full-day labour only. Existing Estimate snapshots remain immutable.</small></section>
    {groups.map(([title,categories])=><section className="ui-card calculator-lab__card" key={title}><h3>{title}</h3>{config.catalogue.filter(item=>(categories as readonly string[]).includes(item.category)).map(item=><label className="calculator-admin__row" key={item.id}><span><strong>{item.label}</strong><small>{item.category.replaceAll("_"," ")} · {item.rateType.replaceAll("_"," ")} · v{item.version}{item.variant.sourceStatus?` · ${String(item.variant.sourceStatus)}`:""}</small></span><input className="ui-input" defaultValue={item.priceAmount??""} placeholder="Price required" onBlur={event=>void savePrice(item.id,item.label,event.currentTarget.value)} /></label>)}</section>)}
    <section className="ui-card calculator-lab__card"><h3>Installation Materials Rules</h3><div className="calculator-lab__form"><label>Default contingency %<input className="ui-input" defaultValue={installationRule.defaultContingencyPercent??15} onBlur={event=>void saveMaterialRule("defaultContingencyPercent",event.currentTarget.value)} /></label><label>Default bracket length mm<select className="ui-input" defaultValue={installationRule.defaultBracketLengthMm??200} onChange={event=>void saveMaterialRule("defaultBracketLengthMm",event.currentTarget.value)}><option>150</option><option>200</option><option>250</option></select></label><label>Frame screws per bracket<input className="ui-input" defaultValue={installationRule.frameScrewsPerBracket??3} onBlur={event=>void saveMaterialRule("frameScrewsPerBracket",event.currentTarget.value)} /></label>{[["brick_block","Brick & Block"],["concrete","Concrete"],["timber_frame","Timber Frame"],["icf","ICF"]].map(([key,label])=><label key={key}>{label} fixings per bracket<input className="ui-input" defaultValue={building[key]?.fixingsPerBracket??""} placeholder="Pending specification" onBlur={event=>void saveBuilding(key,event.currentTarget.value)} /></label>)}<label>Packers per fixing position<input className="ui-input" defaultValue={installationRule.packersPerFixingPosition??""} placeholder="Pending authoritative rule" onBlur={event=>void saveMaterialRule("packersPerFixingPosition",event.currentTarget.value)} /></label></div><small>GGF rules retain page provenance; Estimate overrides remain separately recorded.</small></section>{message?<p role="status">{message}</p>:null}
  </div>;
}
