import { useEffect, useMemo, useRef, useState } from "react";
import { projectCalculatorLabApi } from "./api/projectCalculatorLabApi";
import type { CalculatorAdminConfiguration, CalculatorCatalogueItem } from "./domain/projectCalculatorLab.types";
import InstallationWorkforceAdmin from "./InstallationWorkforceAdmin";

type InstallationTab = "programme" | "materials" | "fixings" | "tools" | "survey" | "lifting" | "rules" | "trail";
type EditorState = { item: CalculatorCatalogueItem; isNew: boolean };

const tabs: Array<{ id: InstallationTab; label: string }> = [
  { id: "programme", label: "Programme & Rates" },
  { id: "materials", label: "Materials" },
  { id: "fixings", label: "Mechanical Fixings" },
  { id: "tools", label: "Tools" },
  { id: "survey", label: "Survey / Site Visit" },
  { id: "lifting", label: "Equipment Hire" },
  { id: "rules", label: "Calculation Rules" },
  { id: "trail", label: "Calculation Trail" },
];
const materialCategories = ["illbruck_me508", "illbruck_me501", "illbruck_tp600", "illbruck_fm330", "illbruck_me902"];
const fixingCategories = ["bracket", "frame_screw"];
const surveyIds = ["retrofit_survey", "installation_support", "supplier_site_mileage"];
const categoryLabels: Record<string, string> = {
  illbruck_me508: "Membrane", illbruck_me501: "Membrane", illbruck_tp600: "Compriband", illbruck_fm330: "PU Foam", illbruck_me902: "Primer",
  bracket: "Mechanical Fixing", frame_screw: "Mechanical Fixing", tool: "Installation Tool", service: "Survey / Site Visit", travel: "Survey / Site Visit", mechanical_lifting: "Equipment Hire",
};
const categoryOptions = [
  ["illbruck_me508", "ME508 membrane"], ["illbruck_me501", "ME501 membrane"], ["illbruck_tp600", "TP600 Compriband"], ["illbruck_fm330", "FM330 foam"], ["illbruck_me902", "ME902 primer"],
  ["bracket", "Fixing bracket"], ["frame_screw", "Frame fixing screw"], ["tool", "Installation tool"], ["service", "Survey / service"], ["travel", "Site-visit travel"], ["mechanical_lifting", "Equipment Hire"],
] as const;

const numberValue = (value: FormDataEntryValue | null) => value === "" || value == null ? null : Number(value);
const productCode = (item: CalculatorCatalogueItem) => String(item.variant.productCode ?? item.variant.itemNumber ?? item.label);
const locationLabel = (item: CalculatorCatalogueItem) => {
  if (item.category === "illbruck_me508") return "Internal";
  if (item.category === "illbruck_me501") return "External";
  if (item.category === "illbruck_me902") return "Internal / External";
  if (["illbruck_tp600", "illbruck_fm330"].includes(item.category)) return "Installation Joint";
  return String(item.variant.location ?? "—");
};
const widthLabel = (item: CalculatorCatalogueItem) => item.variant.rollWidthMm != null ? `${String(item.variant.rollWidthMm)} mm` : item.variant.tapeWidthMm != null ? `${String(item.variant.tapeWidthMm)} mm` : item.variant.bracketLengthMm != null ? `${String(item.variant.bracketLengthMm)} mm` : item.variant.diameterMm != null && item.variant.lengthMm != null ? `${String(item.variant.diameterMm)} × ${String(item.variant.lengthMm)} mm` : "—";
const sizeLabel = (item: CalculatorCatalogueItem) => item.variant.jointGapMinMm != null ? `Joint ${String(item.variant.jointGapMinMm)}–${String(item.variant.jointGapMaxMm)} mm` : String(item.variant.variantSize ?? "—");
const packLabel = (item: CalculatorCatalogueItem) => item.variant.rollLengthM != null ? `${String(item.variant.rollLengthM)} m roll` : item.variant.canVolumeMl != null ? item.variant.unitsPerPack && Number(item.variant.unitsPerPack) > 1 ? `${String(item.variant.unitsPerPack)} × ${String(item.variant.canVolumeMl)} ml ${item.rateType}` : `${String(item.variant.canVolumeMl)} ml ${item.rateType}` : item.variant.packQuantity != null ? `${String(item.variant.packQuantity)} / ${item.rateType}` : item.rateType === "each" ? "Each" : item.rateType.replaceAll("_", " ");
const costLabel = (item: CalculatorCatalogueItem) => item.priceAmount == null ? "Cost required" : new Intl.NumberFormat("en-GB", { style: "currency", currency: item.currency }).format(Number(item.priceAmount));
const blankItem = (category: string): CalculatorCatalogueItem => ({ id: "new", category, label: "", rateType: category === "mechanical_lifting" ? "hire" : category === "tool" || category === "bracket" ? "each" : category.startsWith("illbruck_") ? "roll" : "unit", priceAmount: null, currency: "GBP", variant: { catalogueStatus: "current" }, supplier: category.startsWith("illbruck_") || category === "tool" ? "Illbruck" : null, notes: null, active: true, version: 1 });

function CatalogueTable({ items, area, onEdit, onRemove }: { items: CalculatorCatalogueItem[]; area: "materials" | "fixings" | "tools" | "survey" | "lifting"; onEdit: (item: CalculatorCatalogueItem) => void; onRemove: (item: CalculatorCatalogueItem) => void }) {
  const empty = <tr><td colSpan={area === "materials" ? 10 : 8}><div className="ui-empty-state">No catalogue products match the current filters.</div></td></tr>;
  return <div className="calculator-admin__table-wrap"><table className="ui-table calculator-admin__catalogue-table">
    <thead><tr><th>Product</th><th>Category</th>{area === "materials" ? <><th>Location</th><th>Width</th><th>Size / Joint</th></> : <th>Size / Variant</th>}<th>Purchase Unit</th><th>Pack / Coverage</th><th>Ex-VAT Cost</th><th>Status</th><th>Action</th></tr></thead>
    <tbody>{items.length ? items.map(item => <tr key={item.id}>
      <td><b>{productCode(item)}</b><small>{item.label}</small></td><td>{categoryLabels[item.category] ?? item.category.replaceAll("_", " ")}</td>
      {area === "materials" ? <><td>{locationLabel(item)}</td><td>{widthLabel(item)}</td><td>{sizeLabel(item)}</td></> : <td>{widthLabel(item)}</td>}
      <td>{item.rateType.replaceAll("_", " ")}</td><td>{packLabel(item)}</td><td>{costLabel(item)}</td><td><span className={`ui-status ${item.active ? "ui-status--success" : "ui-status--muted"}`}>{item.active ? "Active" : "Inactive"}</span></td>
      <td><div className="ui-action-row calculator-admin__row-actions"><button type="button" className="ui-button" onClick={() => onEdit(item)}>Edit</button><button type="button" className="ui-button ui-button--danger" onClick={() => onRemove(item)}>Remove</button></div></td>
    </tr>) : empty}</tbody>
  </table></div>;
}

function CatalogueEditor({ state, onClose, onSave }: { state: EditorState; onClose: () => void; onSave: (form: HTMLFormElement) => void }) {
  const { item, isNew } = state, [category, setCategory] = useState(item.category), isMaterial = materialCategories.includes(category), isTape = category === "illbruck_tp600", isRoll = ["illbruck_me508", "illbruck_me501", "illbruck_tp600"].includes(category), isCan = ["illbruck_fm330", "illbruck_me902"].includes(category), isLifting = category === "mechanical_lifting";
  return <div className="ui-modal-backdrop" role="presentation"><form className="ui-modal workforce-admin__modal" role="dialog" aria-modal="true" aria-labelledby="catalogue-editor-title" onSubmit={event => { event.preventDefault(); onSave(event.currentTarget); }}>
    <header><div><h3 id="catalogue-editor-title">{isNew ? "Add Installation Catalogue Item" : "Edit Installation Catalogue Item"}</h3><p>Use the same catalogue fields for materials, fixings, tools and survey costs. Saved Estimate snapshots are not changed.</p></div><button type="button" className="ui-button" aria-label="Close catalogue editor" onClick={onClose}>×</button></header>
    <div className="workforce-admin__editor-grid">
      <label>Product / name<input required name="label" className="ui-input" defaultValue={item.label} /></label>
      <label>Category<select name="category" className="ui-input" value={category} onChange={event => setCategory(event.currentTarget.value)}>{categoryOptions.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label>
      <label>Manufacturer<input name="manufacturer" className="ui-input" defaultValue={item.supplier ?? String(item.variant.manufacturer ?? "")} /></label>
      <label>Product code<input name="productCode" className="ui-input" defaultValue={String(item.variant.productCode ?? "")} placeholder="ME508" /></label>
      <label>Reference / SKU<input name="sku" className="ui-input" defaultValue={String(item.variant.itemNumber ?? "")} /></label>
      <label>Location<input name="location" className="ui-input" defaultValue={locationLabel(item) === "—" ? "" : locationLabel(item)} /></label>
      <label>Variant / size<input name="variantSize" className="ui-input" defaultValue={String(item.variant.variantSize ?? "")} /></label>
      <label>Purchase unit<select name="rateType" className="ui-input" defaultValue={item.rateType}><option value="roll">Roll</option><option value="box">Box</option><option value="can">Can</option><option value="each">Each</option><option value="hire">Hire</option><option value="per_day">Per day</option><option value="per_mile">Per mile</option><option value="unit">Unit</option></select></label>
      {isLifting ? <><label>Equipment type<select name="equipmentType" className="ui-input" defaultValue={String(item.variant.equipmentType ?? "glass_vacuum_lifter")}><option value="telehandler">Telehandler</option><option value="robot">Robot</option><option value="spider_crane">Spider Crane</option><option value="crane">Crane</option><option value="glass_vacuum_lifter">Glass Vacuum Lifter</option><option value="skip_hire">Skip Hire</option></select></label><label>Delivery cost<input name="deliveryCost" inputMode="decimal" className="ui-input" defaultValue={String(item.variant.deliveryCost ?? "")} placeholder="Configure when applicable" /></label><label>Collection cost<input name="collectionCost" inputMode="decimal" className="ui-input" defaultValue={String(item.variant.collectionCost ?? "")} placeholder="Configure when applicable" /></label><label>Default markup %<input name="defaultMarkupPercent" inputMode="decimal" className="ui-input" defaultValue={String(item.variant.defaultMarkupPercent ?? 0)} /></label></> : null}
      {isMaterial || category === "bracket" || category === "frame_screw" ? <label>Width / bracket length (mm)<input name="widthMm" inputMode="decimal" className="ui-input" defaultValue={String(item.variant.rollWidthMm ?? item.variant.tapeWidthMm ?? item.variant.bracketLengthMm ?? "")} /></label> : null}
      {isTape ? <><label>Joint minimum (mm)<input name="jointGapMinMm" inputMode="decimal" className="ui-input" defaultValue={String(item.variant.jointGapMinMm ?? "")} /></label><label>Joint maximum (mm)<input name="jointGapMaxMm" inputMode="decimal" className="ui-input" defaultValue={String(item.variant.jointGapMaxMm ?? "")} /></label></> : null}
      {isRoll ? <label>Roll length (m)<input name="rollLengthM" inputMode="decimal" className="ui-input" defaultValue={String(item.variant.rollLengthM ?? "")} /></label> : null}
      {isCan ? <label>Container size (ml)<input name="canVolumeMl" inputMode="decimal" className="ui-input" defaultValue={String(item.variant.canVolumeMl ?? "")} /></label> : null}
      <label>Pack quantity<input name="packQuantity" inputMode="decimal" className="ui-input" defaultValue={String(item.variant.packQuantity ?? item.variant.unitsPerPack ?? "")} /></label>
      {category === "illbruck_me902" ? <label>Coverage metres / unit<input name="coverageMetresPerUnit" inputMode="decimal" className="ui-input" defaultValue={String(item.variant.coverageMetresPerUnit ?? "")} placeholder="Coverage required" /></label> : null}
      <label>Currency<input name="currency" className="ui-input" defaultValue={item.currency} maxLength={3} /></label>
      <label>Ex-VAT purchase price / unit<input name="priceAmount" inputMode="decimal" className="ui-input" defaultValue={item.priceAmount ?? ""} placeholder="Cost required" /></label>
      <label className="workforce-admin__wide">Notes<textarea name="notes" className="ui-input" rows={3} defaultValue={item.notes ?? ""} /></label>
      <label className="workforce-admin__active"><input type="checkbox" name="active" defaultChecked={item.active} /> Active</label>
    </div>
    <footer><button type="button" className="ui-button" onClick={onClose}>Cancel</button><button type="submit" className="ui-button ui-button--primary">{isNew ? "Add Product" : "Save Changes"}</button></footer>
  </form></div>;
}

export default function CalculatorAdminCatalogue() {
  const [config, setConfig] = useState<CalculatorAdminConfiguration | null>(null), [message, setMessage] = useState(""), [loadError, setLoadError] = useState(""), [editing, setEditing] = useState<EditorState | null>(null);
  const [activeTab, setActiveTab] = useState<InstallationTab>(() => { const saved = globalThis.sessionStorage?.getItem("quotesuite.installationAdminTab"); return tabs.some(tab => tab.id === saved) ? saved as InstallationTab : "programme"; });
  const [materialFilter, setMaterialFilter] = useState("all"), [statusFilter, setStatusFilter] = useState("active");
  const tabRefs = useRef<Array<HTMLButtonElement | null>>([]);
  useEffect(() => { let active = true; void projectCalculatorLabApi.getAdminConfiguration().then(value => { if (active) setConfig(value); }).catch(error => { if (active) setLoadError(error instanceof Error ? error.message : "Calculator configuration could not be loaded."); }); return () => { active = false; }; }, []);
  useEffect(() => { globalThis.sessionStorage?.setItem("quotesuite.installationAdminTab", activeTab); }, [activeTab]);
  const selectTab = (tab: InstallationTab) => { setActiveTab(tab); setStatusFilter("active"); setMessage(""); };
  const onTabKeyDown = (index: number, event: React.KeyboardEvent<HTMLButtonElement>) => { let next = index; if (event.key === "ArrowRight") next = (index + 1) % tabs.length; else if (event.key === "ArrowLeft") next = (index - 1 + tabs.length) % tabs.length; else if (event.key === "Home") next = 0; else if (event.key === "End") next = tabs.length - 1; else return; event.preventDefault(); selectTab(tabs[next].id); tabRefs.current[next]?.focus(); };
  const installationRule = (config?.rules.installation_materials_v1?.value ?? {}) as Record<string, any>, programmeRule = (config?.rules.installation_programme_v1?.value ?? {}) as Record<string, any>;
  const filtered = useMemo(() => { if (!config) return []; let items = config.catalogue.filter(item => statusFilter === "all" || item.active === (statusFilter === "active")); if (activeTab === "materials") items = items.filter(item => materialCategories.includes(item.category) && (materialFilter === "all" || categoryLabels[item.category] === materialFilter)); if (activeTab === "fixings") items = items.filter(item => fixingCategories.includes(item.category)); if (activeTab === "tools") items = items.filter(item => item.category === "tool"); if (activeTab === "survey") items = items.filter(item => surveyIds.includes(item.id)); if (activeTab === "lifting") items = items.filter(item => item.category === "mechanical_lifting"); return items; }, [config, activeTab, materialFilter, statusFilter]);
  if (loadError) return <div className="ui-card calculator-lab__card" role="alert"><h3>Calculator configuration unavailable</h3><p>{loadError}</p></div>;
  if (!config) return <p role="status">Loading Installation Administration…</p>;
  const saveRule = async (key: string, value: string) => { setConfig(await projectCalculatorLabApi.updateRule("installation_materials_v1", { ...installationRule, [key]: value === "" ? null : Number(value) })); setMessage("Calculation default saved for future Estimates. Existing snapshots were not changed."); };
  const saveProgrammeRule = async (key: string, value: string) => { setConfig(await projectCalculatorLabApi.updateRule("installation_programme_v1", { ...programmeRule, [key]: Number(value) })); setMessage("Programme default saved for future Estimates."); };
  const saveCatalogue = async (form: HTMLFormElement) => {
    if (!editing) return;
    const data = new FormData(form), category = String(data.get("category")), width = numberValue(data.get("widthMm"));
    const variant = { ...editing.item.variant, catalogueStatus: "current", manufacturer: data.get("manufacturer") || null, productCode: data.get("productCode") || null, itemNumber: data.get("sku") || null, location: data.get("location") || null, variantSize: data.get("variantSize") || null, rollWidthMm: category === "illbruck_me508" || category === "illbruck_me501" ? width : editing.item.variant.rollWidthMm ?? null, tapeWidthMm: category === "illbruck_tp600" ? width : editing.item.variant.tapeWidthMm ?? null, bracketLengthMm: category === "bracket" ? width : editing.item.variant.bracketLengthMm ?? null, rollLengthM: numberValue(data.get("rollLengthM")), jointGapMinMm: numberValue(data.get("jointGapMinMm")), jointGapMaxMm: numberValue(data.get("jointGapMaxMm")), canVolumeMl: numberValue(data.get("canVolumeMl")), packQuantity: numberValue(data.get("packQuantity")), unitsPerPack: numberValue(data.get("packQuantity")), coverageMetresPerUnit: numberValue(data.get("coverageMetresPerUnit")), purchaseUnit: data.get("rateType"), equipmentType: data.get("equipmentType") || editing.item.variant.equipmentType || null, productName: category === "mechanical_lifting" ? data.get("label") : editing.item.variant.productName ?? null, deliveryCost: numberValue(data.get("deliveryCost")), collectionCost: numberValue(data.get("collectionCost")), defaultMarkupPercent: numberValue(data.get("defaultMarkupPercent")) };
    const input = { category, label: data.get("label"), supplier: data.get("manufacturer"), rateType: data.get("rateType"), currency: data.get("currency"), priceAmount: data.get("priceAmount"), notes: data.get("notes"), active: data.get("active") === "on", variant };
    try { setConfig(editing.isNew ? await projectCalculatorLabApi.createCatalogueItem(input) : await projectCalculatorLabApi.updateCatalogueItem(editing.item.id, input)); setMessage(`${String(data.get("label"))} ${editing.isNew ? "added to" : "updated in"} the current catalogue.`); setEditing(null); } catch (error) { setMessage(error instanceof Error ? error.message : "Catalogue product could not be saved."); }
  };
  const removeCatalogue = async (item: CalculatorCatalogueItem) => { if (!globalThis.confirm(`Remove ${item.label} from the current catalogue? Referenced saved scenarios will be preserved.`)) return; try { const result = await projectCalculatorLabApi.removeCatalogueItem(item.id); setConfig(result.configuration); setMessage(result.disposition === "deleted" ? `${item.label} deleted.` : `${item.label} is now inactive because ${result.dependencies.snapshotReferenceCount} saved snapshot(s) reference it.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Catalogue product could not be removed."); } };
  const addForTab = () => setEditing({ item: blankItem(activeTab === "materials" ? "illbruck_me508" : activeTab === "fixings" ? "bracket" : activeTab === "tools" ? "tool" : activeTab === "lifting" ? "mechanical_lifting" : "service"), isNew: true });
  const panelHeader = (title: string, description: string, addLabel?: string) => <div className="calculator-admin__section-heading"><div><h3>{title}</h3><p>{description}</p></div>{addLabel ? <button type="button" className="ui-button ui-button--primary" onClick={addForTab}>{addLabel}</button> : null}</div>;
  const statusControl = <div className="calculator-admin__filters"><label>Status<select className="ui-input" value={statusFilter} onChange={event => setStatusFilter(event.currentTarget.value)}><option value="active">Active</option><option value="inactive">Inactive</option><option value="all">All</option></select></label></div>;
  return <div className="calculator-admin">
    <div><h2>Installation</h2><p>Configure installation teams, rates, catalogues and governed calculation rules. Changes initialise future calculations; saved scenarios remain immutable snapshots.</p></div>
    <div className="ui-tabs calculator-admin__tabs" role="tablist" aria-label="Installation Administration sections">{tabs.map((tab, index) => <button key={tab.id} ref={node => { tabRefs.current[index] = node; }} type="button" role="tab" id={`installation-tab-${tab.id}`} aria-selected={activeTab === tab.id} aria-controls={`installation-panel-${tab.id}`} tabIndex={activeTab === tab.id ? 0 : -1} className="ui-tab" onClick={() => selectTab(tab.id)} onKeyDown={event => onTabKeyDown(index, event)}>{tab.label}</button>)}</div>
    <section className="calculator-admin__panel" role="tabpanel" id={`installation-panel-${activeTab}`} aria-labelledby={`installation-tab-${activeTab}`}>
      {activeTab === "programme" ? <div className="calculator-admin__panel-stack"><InstallationWorkforceAdmin /><section className="ui-card calculator-lab__card">{panelHeader("Programme & Rates", "Current labour, travel and stay-away defaults for future Estimate snapshots.")}<div className="calculator-lab__form"><label>Installer / full day<input className="ui-input" defaultValue={programmeRule.installerDayRate ?? 350} onBlur={event => void saveProgrammeRule("installerDayRate", event.currentTarget.value)} /></label><label>2-person standard units/day<input className="ui-input" value={programmeRule.standardUnitsPerDayByCrew?.["2"] ?? 7} readOnly /></label><label>4-person standard units/day<input className="ui-input" value={programmeRule.standardUnitsPerDayByCrew?.["4"] ?? 12} readOnly /></label><label>Mileage / mile<input className="ui-input" defaultValue={programmeRule.mileageRate ?? 0.55} onBlur={event => void saveProgrammeRule("mileageRate", event.currentTarget.value)} /></label><label>Food / person/day<input className="ui-input" defaultValue={programmeRule.foodPerPersonDay ?? 30} onBlur={event => void saveProgrammeRule("foodPerPersonDay", event.currentTarget.value)} /></label><label>Accommodation / person/night<input className="ui-input" defaultValue={programmeRule.accommodationPerPersonNight ?? 125} onBlur={event => void saveProgrammeRule("accommodationPerPersonNight", event.currentTarget.value)} /></label></div></section></div> : null}
      {activeTab === "materials" ? <section className="ui-card calculator-lab__card">{panelHeader("Materials", "Approved sealing, airtightness, foam and primer products. Variant costs remain Administration-editable.", "Add Material")}<div className="calculator-admin__filters"><label>Category<select className="ui-input" value={materialFilter} onChange={event => setMaterialFilter(event.currentTarget.value)}><option value="all">All</option><option>Membrane</option><option>Compriband</option><option>PU Foam</option><option>Primer</option></select></label><label>Status<select className="ui-input" value={statusFilter} onChange={event => setStatusFilter(event.currentTarget.value)}><option value="active">Active</option><option value="inactive">Inactive</option><option value="all">All</option></select></label></div><CatalogueTable items={filtered} area="materials" onEdit={item => setEditing({ item, isNew: false })} onRemove={item => void removeCatalogue(item)} /></section> : null}
      {activeTab === "fixings" ? <section className="ui-card calculator-lab__card">{panelHeader("Mechanical Fixings", "Explicit bracket variants and the current frame-fixing screw. Substrate products remain review-required until configured.", "Add Fixing")}{statusControl}<CatalogueTable items={filtered} area="fixings" onEdit={item => setEditing({ item, isNew: false })} onRemove={item => void removeCatalogue(item)} /></section> : null}
      {activeTab === "tools" ? <section className="ui-card calculator-lab__card">{panelHeader("Tools", "Order-fixed installation tools. Required tools contribute one item per order.", "Add Tool")}{statusControl}<CatalogueTable items={filtered} area="tools" onEdit={item => setEditing({ item, isNew: false })} onRemove={item => void removeCatalogue(item)} /></section> : null}
      {activeTab === "survey" ? <section className="ui-card calculator-lab__card">{panelHeader("Survey / Site Visit", "Manual/internal survey and site-visit defaults. Supplier survey evidence remains an explicit Project Costing choice.", "Add Survey Cost")}{statusControl}<CatalogueTable items={filtered} area="survey" onEdit={item => setEditing({ item, isNew: false })} onRemove={item => void removeCatalogue(item)} /></section> : null}
      {activeTab === "lifting" ? <section className="ui-card calculator-lab__card">{panelHeader("Equipment Hire", "Lifting products, Skip Hire and delivery/collection defaults for future Estimate snapshots. Prices remain editable and historical Estimate selections stay fixed.", "Add Equipment")}{statusControl}<CatalogueTable items={filtered} area="lifting" onEdit={item => setEditing({ item, isNew: false })} onRemove={item => void removeCatalogue(item)} /></section> : null}
      {activeTab === "rules" ? <section className="ui-card calculator-lab__card">{panelHeader("Calculation Rules", "A compact view of current commercial assumptions and governed installation rules.")}<div className="calculator-admin__rules-grid"><label>Linear-material contingency<input className="ui-input" defaultValue={installationRule.defaultContingencyPercent ?? 15} onBlur={event => void saveRule("defaultContingencyPercent", event.currentTarget.value)} /><small>ME508, ME501, TP600 and configured ME902 coverage</small></label><label>Default fixing bracket<select className="ui-input" defaultValue={installationRule.defaultBracketLengthMm ?? 250} onChange={event => void saveRule("defaultBracketLengthMm", event.currentTarget.value)}><option value="100">100 mm</option><option value="150">150 mm</option><option value="200">200 mm</option><option value="250">250 mm</option></select><small>Bracket length; not fixing centres</small></label><div><b>FM330 joint</b><span>92 mm deep × 20 mm wide</span></div><div><b>FM330 yield</b><span>45 L per can · boxes of 12 · no 15% uplift</span></div><div><b>GGF fixing rule</b><span>April 2016 PVC-U baseline · governed and versioned</span></div><div><b>Frame screws</b><span>2 per bracket · boxes of 100</span></div><div><b>ME902 coverage</b><span>{installationRule.me902CoverageMetresPerCan ? `${String(installationRule.me902CoverageMetresPerCan)} m / can` : "Not configured"}</span></div><div><b>Substrate fixing products</b><span>Product / cost required</span></div></div></section> : null}
      {activeTab === "trail" ? <section className="ui-card calculator-lab__card">{panelHeader("Calculation Trail", "Read-only verification of the current governed Installation engine. Estimate-specific evidence remains in immutable costing snapshots.")}<div className="calculator-admin__rules-grid"><div><b>Programme capacity</b><span>2 people: {String(programmeRule.standardUnitsPerDayByCrew?.["2"] ?? 7)} units/day · 4 people: {String(programmeRule.standardUnitsPerDayByCrew?.["4"] ?? 12)} units/day</span></div><div><b>Team recommendation</b><span>Suitable Teams are costed independently; the lowest complete estimated total is recommended for user approval.</span></div><div><b>Travel recommendation</b><span>Google route distance/time · stay over above {String(programmeRule.stayAwayThresholdMinutes ?? 90)} minutes</span></div><div><b>Linear materials</b><span>Canonical installation perimeter × {String(100 + Number(installationRule.defaultContingencyPercent ?? 15))}% ÷ purchase-unit coverage, rounded up</span></div><div><b>FM330</b><span>LM × 92 × 20 ÷ (1000 × 45), then whole boxes of 12</span></div><div><b>Fixing brackets</b><span>GGF April 2016 member-by-member calculation, then multiplied by position quantity</span></div><div><b>Frame screws</b><span>2 per bracket, rounded up to boxes of 100</span></div><div><b>Snapshot boundary</b><span>Admin defaults initialise new/amended costings; frozen Estimate evidence is never silently recalculated.</span></div></div></section> : null}
    </section>
    {message ? <p className="ui-status ui-status--muted calculator-admin__status" role="status">{message}</p> : null}
    {editing ? <CatalogueEditor state={editing} onClose={() => setEditing(null)} onSave={form => void saveCatalogue(form)} /> : null}
  </div>;
}
