import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { projectCalculatorLabApi } from "./api/projectCalculatorLabApi";
import type { CalculatorScenario, InstallationTeam, InstallationWorkforce } from "./domain/projectCalculatorLab.types";
import { calculateDirectionalRoute, resolveRouteEndpoint } from "./integrations/routeIntegration";

type RouteResult = { distanceMiles:number;durationMinutes:number;raw:Record<string,unknown> };
const numberValue=(value:FormDataEntryValue|null,fallback=0)=>value==null||value===""?fallback:Number(value);

export default function ConfigureInstallation({scenario}:{scenario:CalculatorScenario}) {
  const [open,setOpen]=useState(false),[workforce,setWorkforce]=useState<InstallationWorkforce|null>(null),[routes,setRoutes]=useState<Record<string,RouteResult>>({}),[status,setStatus]=useState(""),[busy,setBusy]=useState(false);
  const profile=(scenario.options?.installationProfile??{}) as Record<string,any>,programme=scenario.installationProgramme,canonicalSitePostcode=String(profile.sitePostcode??(scenario.options?.sitePostcodeSource==="estimate_project"?scenario.options?.siteVisitTravel?.sitePostcode:"")??"");
  useEffect(()=>{if(open&&!workforce)void projectCalculatorLabApi.getInstallationWorkforce().then(setWorkforce).catch(error=>setStatus(error instanceof Error?error.message:"Installation workforce could not be loaded."));},[open,workforce]);
  const requiredCrew=useMemo(()=>Math.max(2,...(programme?.tasks.map(task=>Number(task.minimumCrew??2))??[2])),[programme]);
  const eligible=(workforce?.teams??[]).filter(team=>team.active&&team.normalCrewSize>=requiredCrew&&(programme?.requiredCapabilities??[]).every(capability=>team.capabilities.includes(capability))).sort((left,right)=>(routes[left.id]?.durationMinutes??Number.MAX_SAFE_INTEGER)-(routes[right.id]?.durationMinutes??Number.MAX_SAFE_INTEGER));
  const rank=async()=>{const sitePostcode=canonicalSitePostcode.trim();if(!sitePostcode){setStatus("Project/site postcode is required before team routes can be ranked.");return;}setBusy(true);setStatus("");try{const destination=await resolveRouteEndpoint(sitePostcode,{googleMapsApiKey:"server-managed",what3wordsApiKey:"server-managed"});if(!destination)throw new Error("Project/site postcode could not be resolved.");const next:Record<string,RouteResult>={};for(const team of workforce?.teams.filter(item=>item.active&&item.basePostcode)??[]){const origin=await resolveRouteEndpoint(team.basePostcode!,{googleMapsApiKey:"server-managed",what3wordsApiKey:"server-managed"});if(!origin)continue;const route=await calculateDirectionalRoute("installer_to_site",origin,destination,{googleMapsApiKey:"server-managed",what3wordsApiKey:"server-managed"});if(route?.distanceKm!=null&&route.durationMinutes!=null)next[team.id]={distanceMiles:Number(route.distanceKm)*0.621371192,durationMinutes:route.durationMinutes,raw:route as unknown as Record<string,unknown>};}setRoutes(next);setStatus("Suitable active teams ranked by capability, crew and road journey. Select the actual team explicitly.");}catch(error){setStatus(error instanceof Error?error.message:"Team routes could not be calculated.");}finally{setBusy(false);}};
  const save=async(form:HTMLFormElement)=>{setBusy(true);setStatus("");try{const data=new FormData(form),selectedTeamId=String(data.get("selectedTeamId")??""),team=(workforce?.teams??[]).find(item=>item.id===selectedTeamId),selectedRoute=routes[selectedTeamId],positionRequirements={...(profile.positionRequirements??{})};for(const item of scenario.products.filter(row=>/lift|slide|bifold/i.test(row.productClass))){const key=item.estimatePositionId??item.id,kitFormat=data.get(`kit:${key}`)==="yes",duration=data.get(`duration:${key}`),customDuration=data.get(`customDuration:${key}`),durationHours=customDuration?Number(customDuration):duration?Number(duration):null;positionRequirements[key]={...(positionRequirements[key]??{}),kitFormat,durationHours:kitFormat?durationHours:null,customDurationHours:customDuration?Number(customDuration):null};}let snapshotId:string|null=null;if(selectedRoute){const withSnapshot=await projectCalculatorLabApi.addRouteSnapshot(scenario.id,selectedRoute.raw);snapshotId=withSnapshot.routeSnapshots[0]?.id??null;}const updated=await projectCalculatorLabApi.updateInstallationProfile(scenario.id,{enabled:true,selectedTeamId:selectedTeamId||null,selectedTeamSnapshot:team?{id:team.id,name:team.name,companyId:team.companyId,companyName:team.companyName,normalCrewSize:team.normalCrewSize,basePostcode:team.basePostcode,capabilities:team.capabilities,version:team.version}:null,crewSize:numberValue(data.get("crewSize"),team?.normalCrewSize??2),sitePostcode:String(data.get("sitePostcode")??""),travelMode:String(data.get("travelMode")??"auto"),vehicleCount:numberValue(data.get("vehicleCount"),1),mileageRate:String(data.get("mileageRate")??"0.55"),installerDayRate:String(data.get("installerDayRate")??"350.00"),foodPerPersonDay:String(data.get("foodPerPersonDay")??"30.00"),accommodationPerPersonNight:String(data.get("accommodationPerPersonNight")??"125.00"),mobilisationSetOutHours:data.get("mobilisationSetOutHours")===""?null:numberValue(data.get("mobilisationSetOutHours")),supportDays:numberValue(data.get("supportDays")),surveyDays:numberValue(data.get("surveyDays")),cillApplicableQuantity:numberValue(data.get("cillApplicableQuantity")),skipDecision:String(data.get("skipDecision")??""),liftingDecision:String(data.get("liftingDecision")??""),positionRequirements,route:selectedRoute?{snapshotId,oneWayMiles:selectedRoute.distanceMiles.toFixed(2),oneWayDurationMinutes:selectedRoute.durationMinutes}:profile.route??null});window.dispatchEvent(new CustomEvent("quotesuite:costing-updated",{detail:updated}));setOpen(false);}catch(error){setStatus(error instanceof Error?error.message:"Installation configuration could not be saved.");}finally{setBusy(false);}};
  return <><button type="button" className="ui-button ui-button--secondary" onClick={()=>setOpen(true)}>Configure Installation</button>{open&&createPortal(<div className="costing-sheet__modal-backdrop" role="presentation"><section className="costing-sheet__modal" role="dialog" aria-modal="true" aria-labelledby="installation-config-title"><div className="costing-sheet__modal-header"><div><h3 id="installation-config-title">Configure Installation</h3><small>Estimate-only snapshot · Administration defaults remain unchanged</small></div><button type="button" className="ui-button ui-button--ghost" onClick={()=>setOpen(false)}>Close</button></div><form onSubmit={event=>{event.preventDefault();void save(event.currentTarget);}}>
    <div className="calculator-lab__form"><label>Project/site postcode<input name="sitePostcode" className="ui-input" defaultValue={canonicalSitePostcode} /></label><label>Selected Team<select name="selectedTeamId" className="ui-input" defaultValue={String(profile.selectedTeamId??"")}><option value="">Select explicitly</option>{eligible.map(team=><option key={team.id} value={team.id}>{team.companyName} · {team.name} · {team.normalCrewSize} people{routes[team.id]?` · ${routes[team.id].distanceMiles.toFixed(1)} mi / ${routes[team.id].durationMinutes} min`:""}</option>)}</select></label><label>Crew size<input name="crewSize" type="number" min="1" className="ui-input" defaultValue={String(profile.crewSize??2)} /></label><label>Travel mode<select name="travelMode" className="ui-input" defaultValue={String(profile.travelMode??"auto")}><option value="auto">Auto / Recommended</option><option value="daily_travel">Daily Travel</option><option value="stay_away">Stay Away</option><option value="manual">Manual</option></select></label><label>Vehicles<input name="vehicleCount" type="number" min="1" className="ui-input" defaultValue={String(profile.vehicleCount??1)} /></label><label>Mileage / mile<input name="mileageRate" className="ui-input" defaultValue={String(profile.mileageRate??"0.55")} /></label><label>Installer / full day<input name="installerDayRate" className="ui-input" defaultValue={String(profile.installerDayRate??"350.00")} /></label><label>Food / person/day<input name="foodPerPersonDay" className="ui-input" defaultValue={String(profile.foodPerPersonDay??"30.00")} /></label><label>Accommodation / person/night<input name="accommodationPerPersonNight" className="ui-input" defaultValue={String(profile.accommodationPerPersonNight??"125.00")} /></label><label>Mobilisation/offload/set-out hours<input name="mobilisationSetOutHours" className="ui-input" placeholder="Review required" defaultValue={profile.mobilisationSetOutHours??""} /></label><label>Support days<input name="supportDays" className="ui-input" defaultValue={String(profile.supportDays??0)} /></label><label>Retrofit survey days<input name="surveyDays" className="ui-input" defaultValue={String(profile.surveyDays??0)} /></label><label>Applicable cill quantity<input name="cillApplicableQuantity" className="ui-input" defaultValue={String(profile.cillApplicableQuantity??0)} /></label><label>Skip Hire<select name="skipDecision" className="ui-input" defaultValue={String(profile.skipDecision??"")}><option value="">Review Required</option><option value="required">Required</option><option value="not_required">Not required</option></select></label><label>Lifting equipment<select name="liftingDecision" className="ui-input" defaultValue={String(profile.liftingDecision??"")}><option value="">Review Required</option><option value="required">Required — product review</option><option value="not_required">Not required</option></select></label></div>
    <div className="costing-sheet__product-actions"><button type="button" className="ui-button ui-button--secondary" disabled={busy||!workforce} onClick={()=>void rank()}>Rank Suitable Teams</button><button type="submit" className="ui-button" disabled={busy}>Save Installation Snapshot</button></div>{programme?.recommendFourPersonTeam?<p role="status">More than 28 standard units: a four-person team is recommended.</p>:null}{status?<p role="status">{status}</p>:null}
    <details><summary>Position installation requirements</summary><p>Specialist kit-format positions require a position-specific duration. Unsupported classifications remain Review Required.</p>{scenario.products.filter(item=>/lift|slide|bifold/i.test(item.productClass)).map(item=>{const key=item.estimatePositionId??item.id,current=profile.positionRequirements?.[key]??{};return <div key={item.id} className="costing-sheet__facts"><span><b>{item.displayReference}</b> · {item.productClass} · {item.widthMm} mm</span><label>Kit format?<select name={`kit:${key}`} className="ui-input" defaultValue={current.kitFormat?"yes":"no"}><option value="no">No</option><option value="yes">Yes</option></select></label><label>Kit duration<select name={`duration:${key}`} className="ui-input" defaultValue={String(current.durationHours??"")}><option value="">Select when kit</option><option value="4">0.5 day</option><option value="8">1 day</option><option value="12">1.5 days</option><option value="16">2 days</option><option value="24">3 days</option></select></label><label>Custom productive hours<input name={`customDuration:${key}`} className="ui-input" inputMode="decimal" placeholder="Optional" defaultValue={current.customDurationHours??""} /></label></div>;})}</details>
  </form></section></div>,document.body)}</>;
}
