import { useEffect, useState } from "react";
import { projectCalculatorLabApi } from "./api/projectCalculatorLabApi";
import type { InstallationWorkforce } from "./domain/projectCalculatorLab.types";

const EMPTY: InstallationWorkforce = { companies: [], installers: [], teams: [], capabilities: [] };

export default function InstallationWorkforceAdmin() {
  const [value, setValue] = useState<InstallationWorkforce>(EMPTY);
  const [message, setMessage] = useState("");
  useEffect(() => { void projectCalculatorLabApi.getInstallationWorkforce().then(setValue).catch(error => setMessage(error instanceof Error ? error.message : "Installation workforce could not be loaded.")); }, []);
  const company = value.companies[0];
  const saveCompany = async (form: FormData) => setValue(await projectCalculatorLabApi.saveInstallationCompany(undefined, { name:form.get("name"),address:{line1:form.get("address")},postcode:form.get("postcode"),telephone:form.get("telephone"),email:form.get("email"),dayRate:form.get("dayRate"),active:true }));
  const saveInstaller = async (form: FormData) => setValue(await projectCalculatorLabApi.saveInstallationInstaller(undefined, { companyId:form.get("companyId"),name:form.get("name"),mobile:form.get("mobile"),email:form.get("email"),address:{line1:form.get("address")},postcode:form.get("postcode"),dayRate:form.get("dayRate"),active:true,capabilities:form.getAll("capabilities") }));
  const saveTeam = async (form: FormData) => setValue(await projectCalculatorLabApi.saveInstallationTeam(undefined, { companyId:form.get("companyId"),name:form.get("name"),normalCrewSize:Number(form.get("crewSize")),basePostcode:form.get("postcode"),active:true,capabilities:form.getAll("capabilities"),installerIds:form.getAll("installerIds") }));
  return <section className="ui-card calculator-lab__card"><h3>Installation Workforce</h3><p>Companies, installers and teams are Administration-owned. Estimates snapshot the selected team and rates.</p>
    <div className="calculator-lab__form">
      <form onSubmit={event=>{event.preventDefault();void saveCompany(new FormData(event.currentTarget)).then(()=>setMessage("Installation Company saved."));}}><h4>Add Installation Company</h4><label>Company name<input required name="name" className="ui-input" /></label><label>Address<input name="address" className="ui-input" /></label><label>Postcode<input required name="postcode" className="ui-input" /></label><label>Telephone<input name="telephone" className="ui-input" /></label><label>Email<input name="email" type="email" className="ui-input" /></label><label>Default installer/full-day cost<input name="dayRate" inputMode="decimal" defaultValue="350.00" className="ui-input" /></label><button className="ui-button" type="submit">Add Company</button></form>
      <form onSubmit={event=>{event.preventDefault();void saveInstaller(new FormData(event.currentTarget)).then(()=>setMessage("Installer saved."));}}><h4>Add Installer</h4><label>Company<select required name="companyId" className="ui-input" defaultValue={company?.id??""}><option value="">Select</option>{value.companies.filter(item=>item.active).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Name<input required name="name" className="ui-input" /></label><label>Mobile<input name="mobile" className="ui-input" /></label><label>Email<input name="email" type="email" className="ui-input" /></label><label>Address<input name="address" className="ui-input" /></label><label>Postcode<input name="postcode" className="ui-input" /></label><label>Labour cost / full day<input name="dayRate" inputMode="decimal" defaultValue="350.00" className="ui-input" /></label><fieldset><legend>Capabilities</legend>{value.capabilities.map(item=><label key={item}><input type="checkbox" name="capabilities" value={item} /> {item.replaceAll("_"," ")}</label>)}</fieldset><button className="ui-button" type="submit">Add Installer</button></form>
      <form onSubmit={event=>{event.preventDefault();void saveTeam(new FormData(event.currentTarget)).then(()=>setMessage("Installation Team saved."));}}><h4>Add Team</h4><label>Company<select required name="companyId" className="ui-input" defaultValue={company?.id??""}><option value="">Select</option>{value.companies.filter(item=>item.active).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Team name<input required name="name" className="ui-input" /></label><label>Normal crew size<input required name="crewSize" type="number" min="1" defaultValue="2" className="ui-input" /></label><label>Base postcode<input required name="postcode" className="ui-input" /></label><fieldset><legend>Members</legend>{value.installers.filter(item=>item.active).map(item=><label key={item.id}><input type="checkbox" name="installerIds" value={item.id} /> {item.name}</label>)}</fieldset><fieldset><legend>Capabilities</legend>{value.capabilities.map(item=><label key={item}><input type="checkbox" name="capabilities" value={item} /> {item.replaceAll("_"," ")}</label>)}</fieldset><button className="ui-button" type="submit">Add Team</button></form>
    </div>
    <div className="costing-sheet__detail-list">{value.companies.map(item=><div key={item.id}><b>{item.name}</b> · {item.postcode||"No postcode"} · {item.active?"Active":"Inactive"}</div>)}{value.teams.map(item=><div key={item.id}><b>{item.name}</b> · {item.companyName} · {item.normalCrewSize} people · {item.basePostcode||"No base"}</div>)}</div>{message?<p role="status">{message}</p>:null}
  </section>;
}
