import React,{useEffect,useMemo,useState} from "react";
import { projectCalculatorLabApi } from "./api/projectCalculatorLabApi";
import type { CalculatorPackageCode,CalculatorScenario,ImportSource,ProductClass } from "./domain/projectCalculatorLab.types";
import { calculateDirectionalRoute,resolveRouteEndpoint } from "./integrations/routeIntegration";
import "./projectCalculatorLab.css";

const packages:[CalculatorPackageCode,string][]=[["supply_only","Supply Only"],["support","Support"],["full_installation","Full Installation"]];
const productClasses:ProductClass[]=["Window","Single door","French/double door","Door with sidelight","Lift-and-slide","Bifold","Sliding/gliding door","Curtain walling","Other","Needs review"];
function sumExact(values:(string|null)[]){let scale=0;for(const value of values){const places=(value?.split('.')[1]||'').length;if(places>scale)scale=places;}let total=0n;for(const value of values){if(!value)continue;const [whole,fraction='']=value.split('.');total+=BigInt(whole+fraction.padEnd(scale,'0'));}const raw=String(total).padStart(scale+1,'0');return scale?`${raw.slice(0,-scale)}.${raw.slice(-scale).replace(/0+$/,'')||'0'}`:raw;}

export default function ProjectCalculatorLabWorkspace(){
 const [sources,setSources]=useState<ImportSource[]>([]),[scenarios,setScenarios]=useState<CalculatorScenario[]>([]),[active,setActive]=useState<CalculatorScenario|null>(null);
 const [sourceId,setSourceId]=useState(""),[name,setName]=useState(""),[packageCode,setPackageCode]=useState<CalculatorPackageCode>("supply_only"),[openings,setOpenings]=useState("0");
 const [office,setOffice]=useState(""),[site,setSite]=useState(""),[manualDirection,setManualDirection]=useState<"office_to_site"|"site_to_office">("office_to_site"),[manualDistance,setManualDistance]=useState(""),[manualDuration,setManualDuration]=useState(""),[overrideReason,setOverrideReason]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const config={googleMapsApiKey:String(import.meta.env.VITE_GOOGLE_MAPS_API_KEY||""),what3wordsApiKey:String(import.meta.env.VITE_WHAT3WORDS_API_KEY||"")};
 const refresh=async()=>{const [nextSources,nextScenarios]=await Promise.all([projectCalculatorLabApi.listImportSources(),projectCalculatorLabApi.listScenarios()]);setSources(nextSources);setScenarios(nextScenarios);};
 useEffect(()=>{void refresh().catch(()=>setMessage("Unable to load calculator lab."));},[]);
 const totals=useMemo(()=>active?{rows:active.products.length,quantity:active.products.reduce((a,r)=>a+r.quantity,0),area:sumExact(active.products.map(r=>r.areaSquareMetres)),perimeter:sumExact(active.products.map(r=>r.framePerimeterMetres))}:null,[active]);
 async function create(){const source=sources.find(s=>s.runId===sourceId);if(!source||!name.trim())return;setBusy(true);try{const created=await projectCalculatorLabApi.createScenario({name:name.trim(),packageCode,importLabSessionId:source.sessionId,extractionRunId:source.runId,sourceAttachmentId:source.attachmentId,installationOpeningCount:Number(openings)||0});setActive(created);await refresh();setMessage("Scenario created from immutable Import Lab evidence.");}catch(error){setMessage(error instanceof Error?error.message:"Scenario creation failed.");}finally{setBusy(false);}}
 async function calculateRoutes(){if(!active)return;setBusy(true);try{const officePoint=await resolveRouteEndpoint(office,config),sitePoint=await resolveRouteEndpoint(site,config);if(!officePoint||!sitePoint)throw new Error("Locations could not be resolved. Check Integration configuration.");const outbound=await calculateDirectionalRoute("office_to_site",officePoint,sitePoint,config);const inbound=await calculateDirectionalRoute("site_to_office",sitePoint,officePoint,config);if(!outbound||!inbound)throw new Error("Google routing is unavailable or Distance Matrix permission is absent.");let updated=await projectCalculatorLabApi.addRouteSnapshot(active.id,outbound as unknown as Record<string,unknown>);updated=await projectCalculatorLabApi.addRouteSnapshot(active.id,inbound as unknown as Record<string,unknown>);setActive(updated);setMessage("Outbound and return route snapshots stored separately.");}catch(error){setMessage(error instanceof Error?error.message:"Route calculation failed.");}finally{setBusy(false);}}
 async function saveManualRoute(){if(!active||!overrideReason.trim())return;const officePoint=await resolveRouteEndpoint(office,config),sitePoint=await resolveRouteEndpoint(site,config);if(!officePoint||!sitePoint){setMessage("Locations could not be resolved for the manual snapshot.");return;}const outbound=manualDirection==='office_to_site';const updated=await projectCalculatorLabApi.addRouteSnapshot(active.id,{direction:manualDirection,origin:outbound?officePoint:sitePoint,destination:outbound?sitePoint:officePoint,distanceKm:manualDistance||null,durationMinutes:manualDuration?Number(manualDuration):null,trafficDurationMinutes:null,calculatedAt:new Date().toISOString(),integration:'manual',manuallyOverridden:true,overrideReason:overrideReason.trim()});setActive(updated);setMessage("Manual route override stored with its reason.");}
 return <div className="calculator-lab">
  <section className="ui-card calculator-lab__card"><h2>Project Calculator (Beta)</h2><p>Estimate-independent allocation lab. Supplier evidence is imported as an immutable snapshot; no selling prices are calculated.</p>
   <div className="calculator-lab__form"><label>Scenario name<input className="ui-input" value={name} onChange={e=>setName(e.target.value)}/></label><label>Completed Import Lab run<select className="ui-input" value={sourceId} onChange={e=>setSourceId(e.target.value)}><option value="">Select extraction run</option>{sources.map(s=><option key={s.runId} value={s.runId}>{s.supplierName} — {s.attachmentFileName} ({s.currency}, {s.selectedRowCount} rows)</option>)}</select></label><label>Package<select className="ui-input" value={packageCode} onChange={e=>setPackageCode(e.target.value as CalculatorPackageCode)}>{packages.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Installation openings<input className="ui-input" type="number" min="0" value={openings} onChange={e=>setOpenings(e.target.value)}/></label><button className="ui-button ui-button--primary" disabled={busy||!sourceId||!name.trim()} onClick={()=>void create()}>Create scenario</button></div>
   <div className="calculator-lab__scenario-list">{scenarios.map(s=><button className="ui-button" key={s.id} onClick={()=>void projectCalculatorLabApi.getScenario(s.id).then(setActive)}>{s.name} · {s.currency}</button>)}</div>{message?<p role="status">{message}</p>:null}
  </section>
  {active?<><section className="ui-card calculator-lab__card"><h3>{active.name}</h3><div className="calculator-lab__metrics"><span>Supply subtotal <strong>{active.supplierSummary?.productSubtotal??"—"} {active.currency}</strong></span><span>Supplier transport <strong>{active.supplierSummary?.deliveryTotal??"—"} {active.currency}</strong></span><span>Supplier final <strong>{active.supplierSummary?.finalSupplierTotal??"—"} {active.currency}</strong></span><span>Commercial rows <strong>{totals?.rows}</strong></span><span>Physical quantity <strong>{totals?.quantity}</strong></span><span>Total m² <strong>{totals?.area}</strong></span><span>Frame perimeter m <strong>{totals?.perimeter}</strong></span></div><label>Installation-opening count <input className="ui-input" type="number" min="0" value={active.installationOpeningCount} onChange={e=>setActive({...active,installationOpeningCount:Number(e.target.value)})} onBlur={()=>void projectCalculatorLabApi.updateScenario(active.id,{installationOpeningCount:active.installationOpeningCount}).then(setActive)}/></label><p className="calculator-lab__provenance">Source session {active.importLabSessionId}; run {active.extractionRunId}; attachment {active.sourceAttachmentId}. Grouped references remain one commercial row.</p></section>
  <section className="ui-card calculator-lab__card"><h3>Imported products</h3><div className="calculator-lab__table-wrap"><table><thead><tr><th>Reference</th><th>Class</th><th>Qty</th><th>W × H</th><th>m²</th><th>Perimeter m</th><th>Supplier total</th></tr></thead><tbody>{active.products.map(row=><tr key={row.id}><td>{row.displayReference}</td><td><select value={row.productClass} onChange={e=>void projectCalculatorLabApi.updateProductClass(active.id,row.id,e.target.value as ProductClass).then(setActive)}>{productClasses.map(value=><option key={value}>{value}</option>)}</select></td><td>{row.quantity}</td><td>{row.widthMm} × {row.heightMm}</td><td>{row.areaSquareMetres}</td><td>{row.framePerimeterMetres}</td><td>{row.totalPrice??"—"} {row.currency}</td></tr>)}</tbody></table></div></section>
  <section className="ui-card calculator-lab__card"><h3>Supplier additional costs</h3>{active.supplierCosts.map(cost=><div key={cost.id}>{cost.category}: {cost.label} — {cost.amount??"—"} {cost.currency}</div>)}<p>Original supplier transport and discounts remain supplier evidence; this lab does not redistribute them.</p></section>
  <section className="ui-card calculator-lab__card"><h3>Scenario package catalogue</h3><div className="calculator-lab__catalogue">{active.packageItems.map(item=><label key={item.id}><input type="checkbox" checked={item.included} onChange={e=>void projectCalculatorLabApi.updatePackageItem(active.id,item.id,{included:e.target.checked,unitCost:item.unitCost??""}).then(setActive)}/><span>{item.label}</span><input className="ui-input" placeholder={`Cost (${item.currency})`} value={item.unitCost??""} onChange={e=>setActive({...active,packageItems:active.packageItems.map(x=>x.id===item.id?{...x,unitCost:e.target.value}:x)})} onBlur={e=>void projectCalculatorLabApi.updatePackageItem(active.id,item.id,{included:item.included,unitCost:e.target.value}).then(setActive)}/></label>)}</div><p>Catalogue values are editable scenario defaults, not supplier evidence. Later-stage labour, materials, accommodation and margin arithmetic is not active.</p></section>
  <section className="ui-card calculator-lab__card"><h3>Directional route snapshots</h3><div className="calculator-lab__form"><label>Office address / coordinates<input className="ui-input" value={office} onChange={e=>setOffice(e.target.value)}/></label><label>Site address / what3words / coordinates<input className="ui-input" value={site} onChange={e=>setSite(e.target.value)}/></label><button className="ui-button" disabled={busy||!office||!site} onClick={()=>void calculateRoutes()}>Calculate both directions</button></div><p>Google provides routable distance and normal duration. Traffic-aware duration is unavailable in the current provider and remains blank.</p><details><summary>Record manual override</summary><div className="calculator-lab__form"><select className="ui-input" value={manualDirection} onChange={e=>setManualDirection(e.target.value as typeof manualDirection)}><option value="office_to_site">Office → site</option><option value="site_to_office">Site → office</option></select><input className="ui-input" placeholder="Distance km" value={manualDistance} onChange={e=>setManualDistance(e.target.value)}/><input className="ui-input" placeholder="Duration minutes" value={manualDuration} onChange={e=>setManualDuration(e.target.value)}/><input className="ui-input" placeholder="Required override reason" value={overrideReason} onChange={e=>setOverrideReason(e.target.value)}/><button className="ui-button" disabled={!overrideReason.trim()||!office||!site} onClick={()=>void saveManualRoute()}>Save manual snapshot</button></div></details>{active.routeSnapshots.map(route=><div key={route.id}><strong>{route.direction==="office_to_site"?"Office → site":"Site → office"}</strong>: {route.distanceKm??"—"} km, {route.durationMinutes??"—"} min; traffic {route.trafficDurationMinutes??"not available"} · {new Date(route.calculatedAt).toLocaleString()}{route.manuallyOverridden?` · manual: ${route.overrideReason}`:""}</div>)}</section></>:null}
 </div>;
}
