import React, { useEffect, useState, type ReactNode } from "react";
import type { CalculatorProductRow, CalculatorScenario, CalculatorSupplierCost } from "./domain/projectCalculatorLab.types";
import { addDecimalAmounts, applyMarkupPercentage, calculateProductSelling, MARKUP_CATEGORIES, percentageRatio, subtractDecimalAmounts, validateMarkupPercentage, type MarkupCategory, type ProjectCostingMarkups } from "./domain/projectCostingMarkup";

type WorksheetScenario=CalculatorScenario&{estimateId?:string|null;estimateRef?:string|null;me508Calculation?:{rollsRequired:number;boxesRequired:number;totalCost:string|null};fixingBreakdown?:Array<Record<string,unknown>>};
type SectionKey="products"|"extras"|"transport"|"equipment"|"installation"|"materials"|"duties";
const number=(value:string|null|undefined)=>Number(value||0);
const money=(value:string|null|undefined,currency="GBP")=>value==null||value===""?"—":new Intl.NumberFormat("en-GB",{style:"currency",currency,minimumFractionDigits:2}).format(number(value));
const gbp=(rows:Array<{gbpAmount:string|null}>)=>addDecimalAmounts(rows.map(row=>row.gbpAmount));
const commercialGbp=(rows:Array<{commercialGbpAmount:string|null}>)=>addDecimalAmounts(rows.map(row=>row.commercialGbpAmount));
const original=(rows:Array<{originalAmount:string|null}>)=>rows.reduce((sum,row)=>sum+number(row.originalAmount),0);
const productOverrides=(products:CalculatorProductRow[])=>Object.fromEntries(products.map(row=>[row.id,row.markupOverridePercent??""]));

function Icon({kind}:{kind:SectionKey}){const glyph={products:"▦",extras:"◫",transport:"◆",equipment:"♜",installation:"♟",materials:"⬡",duties:"◎"}[kind];return <span className={`costing-sheet__icon costing-sheet__icon--${kind}`} aria-hidden="true">{glyph}</span>}
function CommercialRow({description,cost,converted,rate,sale}:{description:string;cost:string;converted:string;rate:string;sale:string}){return <div className="costing-sheet__commercial-row"><span>{description}</span><span>{cost}</span><span>{converted}</span><span>{rate}</span><strong>{sale}</strong></div>}
function ProductRow({row,rate,categoryMarkup,override,onOverrideChange}:{row:CalculatorProductRow;rate:string;categoryMarkup:string;override:string;onOverrideChange:(value:string)=>void}){const pricing=row.commercialGbpAmount?calculateProductSelling(row.commercialGbpAmount,row.quantity,categoryMarkup,override===""?null:override):null,invalid=override!==""&&Boolean(validateMarkupPercentage(override));return <tr className={override!==""?"is-overridden":"is-inherited"}><td>{row.displayReference}</td><td>{row.quantity}</td><td>{money(row.unitSupplyCost,row.currency)}</td><td>{money(row.originalAmount,row.originalCurrency??row.currency)}</td><td>{rate}</td><td>{money(row.gbpAmount)}</td><td><label className={`costing-sheet__row-markup${invalid?" is-invalid":""}`}><input aria-label={`${row.displayReference} markup override`} inputMode="decimal" value={override} placeholder={categoryMarkup} onChange={event=>onOverrideChange(event.currentTarget.value)}/><small>% · {override===""?"Inherited":"Override"}</small></label></td><td>{money(pricing?.unitSellingPrice)}</td><td>{money(pricing?.totalSellingPrice)}</td></tr>}
function Section({index,kind,title,summary,cost,converted,markup,sale,open,onToggle,onMarkupChange,onMarkupKeyDown,invalid,children}:{index:number;kind:SectionKey;title:string;summary:string;cost:string;converted:string;markup:string;sale:string;open:boolean;onToggle:()=>void;onMarkupChange:(value:string)=>void;onMarkupKeyDown:(event:React.KeyboardEvent<HTMLInputElement>)=>void;invalid:boolean;children?:ReactNode}){return <section className={`costing-sheet__section${open?" costing-sheet__section--open":""}`}><div className="costing-sheet__section-row"><button className="costing-sheet__section-label" onClick={onToggle} aria-expanded={open}><Icon kind={kind}/><span><b>{index}. {title}</b><small>{summary}</small></span></button><strong>{cost}</strong><strong>{converted}</strong><label className={`costing-sheet__markup${invalid?" is-invalid":""}`}><span className="sr-only">{title} markup percentage</span><input aria-label={`${title} markup percentage`} inputMode="decimal" value={markup} onChange={event=>onMarkupChange(event.currentTarget.value)} onBlur={event=>onMarkupChange(event.currentTarget.value)} onKeyDown={onMarkupKeyDown}/><small>%</small></label><strong className="costing-sheet__sale">{sale}</strong><button className="costing-sheet__chevron" onClick={onToggle} aria-label={`${open?"Collapse":"Expand"} ${title}`}>{open?"⌃":"⌄"}</button></div>{open?<div className="costing-sheet__section-detail">{children}</div>:null}</section>}

export default function ScenarioCostingWorksheet({scenario,onNew,onSaveMarkups,onCreateRevision,onRefreshRate}:{scenario:WorksheetScenario;onNew?:()=>void;onSaveMarkups:(markups:ProjectCostingMarkups,productOverrides:Array<{rowId:string;markupOverridePercent:string|null}>)=>Promise<void>;onCreateRevision:()=>Promise<void>;onRefreshRate:()=>Promise<void>}){
 const[open,setOpen]=useState<SectionKey|null>("installation"),[markupDraft,setMarkupDraft]=useState<ProjectCostingMarkups>(scenario.markups),[persistedMarkups,setPersistedMarkups]=useState<ProjectCostingMarkups>(scenario.markups),[rowOverrides,setRowOverrides]=useState<Record<string,string>>(()=>productOverrides(scenario.products)),[persistedOverrides,setPersistedOverrides]=useState<Record<string,string>>(()=>productOverrides(scenario.products)),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 useEffect(()=>{const overrides=productOverrides(scenario.products);setMarkupDraft(scenario.markups);setPersistedMarkups(scenario.markups);setRowOverrides(overrides);setPersistedOverrides(overrides)},[scenario.id,scenario.markups,scenario.products]);
 const dirty=MARKUP_CATEGORIES.some(key=>markupDraft[key]!==persistedMarkups[key])||scenario.products.some(row=>(rowOverrides[row.id]??"")!==(persistedOverrides[row.id]??"")),invalidCategories=MARKUP_CATEGORIES.filter(key=>validateMarkupPercentage(markupDraft[key])),invalidOverrides=scenario.products.filter(row=>rowOverrides[row.id]!==""&&validateMarkupPercentage(rowOverrides[row.id]));
 const editMarkup=(category:MarkupCategory,value:string)=>{setMarkupDraft(current=>({...current,[category]:value}));setError("")};
 const markupKeys=(category:MarkupCategory)=>(event:React.KeyboardEvent<HTMLInputElement>)=>{if(event.key==="Escape"){editMarkup(category,persistedMarkups[category]);event.currentTarget.blur()}if(event.key==="Enter")event.currentTarget.blur()};
 async function save(){if(invalidCategories.length||invalidOverrides.length){setError("Correct invalid markup percentages before saving.");return}setSaving(true);setError("");try{await onSaveMarkups(markupDraft,scenario.products.map(row=>({rowId:row.id,markupOverridePercent:rowOverrides[row.id]===""?null:rowOverrides[row.id]})));setPersistedMarkups(markupDraft);setPersistedOverrides(rowOverrides)}catch(reason){setError(reason instanceof Error?reason.message:"Markup save failed. No values were persisted.")}finally{setSaving(false)}}
 const toggle=(key:SectionKey)=>setOpen(current=>current===key?null:key);
 const costs=scenario.supplierCosts,transport=costs.filter(row=>row.category==="delivery"),installation=costs.filter(row=>["labour","travel","accommodation","survey"].includes(row.category)),fees=costs.filter(row=>/import|dut(y|ies)/i.test(`${row.category} ${row.label}`)),extras=costs.filter(row=>!transport.includes(row)&&!installation.includes(row)&&!fees.includes(row));
 const selected=scenario.packageItems.filter(row=>row.included),equipment=selected.filter(row=>/crane|lifter|robot|telehandler|skip/i.test(row.label)),materials=selected.filter(row=>/bracket|fixing|ME508|TP600|TP601|foam|membrane|tape|material/i.test(row.label));
 const productGbp=gbp(scenario.products),extrasGbp=gbp(extras),transportGbp=gbp(transport),installationGbp=gbp(installation),feeGbp=gbp(fees),productCommercialGbp=commercialGbp(scenario.products),extrasCommercialGbp=commercialGbp(extras),transportCommercialGbp=commercialGbp(transport),installationCommercialGbp=commercialGbp(installation),feeCommercialGbp=commercialGbp(fees),equipmentCost=addDecimalAmounts(equipment.map(row=>row.unitCost)),materialsCost=addDecimalAmounts(materials.map(row=>row.unitCost));
 const selling=(amount:string,category:MarkupCategory)=>applyMarkupPercentage(amount,markupDraft[category])?.sellingPrice??"—";
 const productPricing=scenario.products.map(row=>row.commercialGbpAmount?calculateProductSelling(row.commercialGbpAmount,row.quantity,markupDraft.product,(rowOverrides[row.id]??"")===""?null:rowOverrides[row.id]):null),productSale=addDecimalAmounts(productPricing.map(value=>value?.totalSellingPrice)),extrasSale=selling(extrasCommercialGbp,"extras"),transportSale=selling(transportCommercialGbp,"transport"),equipmentSale=selling(equipmentCost,"equipment"),installationSale=selling(installationCommercialGbp,"installation"),materialsSale=selling(materialsCost,"materials"),feeSale=selling(feeCommercialGbp,"duties");
 const projectCost=addDecimalAmounts([productGbp,extrasGbp,transportGbp,equipmentCost,installationGbp,materialsCost,feeGbp]),sale=addDecimalAmounts([productSale,extrasSale,transportSale,equipmentSale,installationSale,materialsSale,feeSale]),profit=subtractDecimalAmounts(sale,projectCost);
 const supplierTotal=scenario.supplierSummary?.finalSupplierTotal??String(original(scenario.products)+original(costs)),supplierPurchaseGbp=addDecimalAmounts([productGbp,extrasGbp,transportGbp,installationGbp,feeGbp]);
 const quote=scenario.sourceRevision?scenario.name.replace(/\s*·\s*revision\s+\d+$/i,""):scenario.name;
 const supplier=scenario.origin==="supplier_import"?(quote.split(/\s+\d{4,}/)[0]||"Supplier quotation"):"Manual costing";
 const liveRate=scenario.exchangeRate?.supplierToGbpLiveRate??"—",commercialRate=scenario.exchangeRate?.supplierToGbpSellingRate??"—",rate=`£1 = ${liveRate}`;
 const installVisible=scenario.packageCode==="full_installation"||installation.length>0;
 const materialsVisible=materials.length>0||Boolean(scenario.options?.useIllbruck||scenario.options?.bracketsRequired);
 const nav=["Quotation","Extraction Review","Project Costing","Documents","History"];
 return <div className="project-costing">
  <header className="project-costing__topbar"><div className="project-costing__brand"><span>▧</span><strong>Ecofenster</strong><small>ARCHITECTURAL WINDOWS &amp; DOORS</small></div><div className="project-costing__breadcrumbs"><span>Supplier Quotations</span><b>›</b><span>{scenario.estimateRef||scenario.estimateId||"Legacy commercial record"}</span><b>›</b><strong>Project Costing</strong></div><div className="project-costing__rate">Rate: {rate} · Selling FX: £1 = {commercialRate}</div><button className="ui-button">View rate history</button><button className="ui-button" disabled={saving} onClick={()=>void onRefreshRate()}>Refresh Rate</button><button className="ui-button" disabled={!dirty||saving||invalidCategories.length>0||invalidOverrides.length>0} onClick={()=>void save()}>{saving?"Saving…":"Save"}</button><button className="ui-button ui-button--primary" disabled={dirty||saving} onClick={()=>void onCreateRevision()}>Create Revision</button><button className="ui-button project-costing__more" aria-label="More actions">⋮</button></header>
  <div className="project-costing__layout"><aside className="project-costing__sidebar"><section className="project-costing__quote-card"><h3>{supplier}</h3><strong>{quote}</strong><span className="project-costing__extracted">✓ Extracted</span><small>Extracted: {new Date(scenario.createdAt).toLocaleString()}</small><nav aria-label="Project workflow">{nav.map((label,index)=><button key={label} className={label==="Project Costing"?"is-active":""}><span>{["▤","◫","▦","□","◷"][index]}</span><span><b>{label}</b><small>{["Document & extraction",`${scenario.products.length} items, ${extras.length} extras`,"Commercial worksheet","Attachments & notes","Revisions & activity"][index]}</small></span>{index<2?<i>✓</i>:null}</button>)}</nav></section><section className="project-costing__session"><h3>Session Summary</h3><div><span>Products ({scenario.products.length})</span><b>{money(scenario.supplierSummary?.productSubtotal??String(original(scenario.products)),scenario.currency)}</b></div><div><span>Extras ({extras.length})</span><b>{money(String(original(extras)),scenario.currency)}</b></div><div><span>Transport</span><b>{money(scenario.supplierSummary?.deliveryTotal??String(original(transport)),scenario.currency)}</b></div><hr/><div><span>Supplier Total</span><b>{money(supplierTotal,scenario.currency)}</b></div>{onNew?<button className="ui-button" onClick={onNew}>View extraction summary</button>:null}</section></aside>
   <main className="costing-sheet"><div className="costing-sheet__title"><div><h1>Project Costing</h1><p>Commercial worksheet for this quotation</p></div><div className={dirty?"costing-sheet__unsaved":"costing-sheet__saved"}>{dirty?"Unsaved markup changes":`Saved · Revision ${scenario.revisionNumber}`}</div></div>{error?<p role="alert" className="calculator-lab__message calculator-lab__message--error">{error}</p>:null}<div className="costing-sheet__columns"><span>Description</span><span>Supplier Cost<small>{scenario.currency}</small></span><span>Purchase Cost<small>GBP · {rate}</small></span><span>Markup %</span><span>Selling Price<small>GBP</small></span><span/></div>
<Section index={1} kind="products" title="Products / Supply Only" summary={`${scenario.products.length} items · ${money(scenario.supplierSummary?.productSubtotal??String(original(scenario.products)),scenario.currency)} supplier subtotal`} cost={money(scenario.supplierSummary?.productSubtotal??String(original(scenario.products)),scenario.currency)} converted={money(productGbp)} markup={markupDraft.product} sale={money(productSale)} open={open==="products"} onToggle={()=>toggle("products")} onMarkupChange={value=>editMarkup("product",value)} onMarkupKeyDown={markupKeys("product")} invalid={Boolean(validateMarkupPercentage(markupDraft.product))}><div className="costing-sheet__detail-table"><table><thead><tr><th>Reference</th><th>Qty</th><th>Supplier unit</th><th>Supplier total</th><th>Rate</th><th>GBP cost</th><th>Markup</th><th>Sale unit</th><th>Sale total</th></tr></thead><tbody>{scenario.products.map(row=><ProductRow key={row.id} row={row} rate={rate} categoryMarkup={markupDraft.product} override={rowOverrides[row.id]??""} onOverrideChange={value=>{setRowOverrides(current=>({...current,[row.id]:value}));setError("")}}/>)}</tbody></table></div></Section>
    {extras.length?<Section index={2} kind="extras" title="Extras" summary={`${extras.length} items`} cost={money(String(original(extras)),scenario.currency)} converted={money(extrasGbp)} markup={markupDraft.extras} sale={money(extrasSale)} open={open==="extras"} onToggle={()=>toggle("extras")} onMarkupChange={value=>editMarkup("extras",value)} onMarkupKeyDown={markupKeys("extras")} invalid={Boolean(validateMarkupPercentage(markupDraft.extras))}><div className="costing-sheet__detail-list">{extras.map(row=><CommercialRow key={row.id} description={row.label} cost={money(row.originalAmount,row.originalCurrency??scenario.currency)} converted={money(row.gbpAmount)} rate={`${row.markupPercent}%`} sale={money(row.markedUpAmount)}/>)}</div></Section>:null}
    {transport.length||scenario.supplierSummary?.deliveryTotal?<Section index={3} kind="transport" title="Transport" summary="Supplier transport (imported)" cost={money(scenario.supplierSummary?.deliveryTotal??String(original(transport)),scenario.currency)} converted={money(transportGbp)} markup={markupDraft.transport} sale={money(transportSale)} open={open==="transport"} onToggle={()=>toggle("transport")} onMarkupChange={value=>editMarkup("transport",value)} onMarkupKeyDown={markupKeys("transport")} invalid={Boolean(validateMarkupPercentage(markupDraft.transport))}><CommercialRow description="Original supplier transport" cost={money(scenario.supplierSummary?.deliveryTotal??String(original(transport)),scenario.currency)} converted={money(String(transportGbp))} rate="—" sale="—"/><CommercialRow description="Customer transport charge" cost="—" converted={scenario.options?.customerTransport?money(scenario.options.customerTransport):"Not set"} rate={`${scenario.markups.transport}%`} sale={money(String(transportSale))}/><div className="costing-sheet__facts"><span>Allocated into products <b>{scenario.options?.allocateTransportDifference?"Yes":"No"}</b></span><span>Allocation method <b>{scenario.options?.transportAllocationMethod?.replaceAll("_"," ")??"None"}</b></span></div></Section>:null}
    {equipment.length?<Section index={4} kind="equipment" title="Equipment Hire" summary={`${equipment.length} selected`} cost={money(String(equipmentCost))} converted={money(equipmentCost)} markup={markupDraft.equipment} sale={money(equipmentSale)} open={open==="equipment"} onToggle={()=>toggle("equipment")} onMarkupChange={value=>editMarkup("equipment",value)} onMarkupKeyDown={markupKeys("equipment")} invalid={Boolean(validateMarkupPercentage(markupDraft.equipment))}><div className="costing-sheet__detail-list">{equipment.map(item=><CommercialRow key={item.id} description={item.label} cost={money(item.unitCost,item.currency)} converted={money(item.unitCost)} rate={`${scenario.markups.installation}%`} sale={money(item.unitCost)}/>)}</div></Section>:null}
    {installVisible?<Section index={5} kind="installation" title="Installation" summary={scenario.packageCode==="full_installation"?"Full installation":"Selected installation costs"} cost={money(String(original(installation)),scenario.currency)} converted={money(installationGbp)} markup={markupDraft.installation} sale={money(installationSale)} open={open==="installation"} onToggle={()=>toggle("installation")} onMarkupChange={value=>editMarkup("installation",value)} onMarkupKeyDown={markupKeys("installation")} invalid={Boolean(validateMarkupPercentage(markupDraft.installation))}><div className="costing-sheet__detail-list">{["labour","travel","accommodation","food allowance","staying-away allowance"].map(label=>{const row=installation.find(item=>item.category===label||item.label.toLowerCase().includes(label.split(" ")[0]));return <CommercialRow key={label} description={label.replace(/^./,c=>c.toUpperCase())} cost={row?money(row.originalAmount,row.originalCurrency??scenario.currency):"Not configured"} converted={row?money(row.gbpAmount):"—"} rate={`${scenario.markups.installation}%`} sale={row?money(row.markedUpAmount):"—"}/>})}</div><div className="costing-sheet__facts"><span>Physical quantity <b>{scenario.products.reduce((sum,row)=>sum+row.quantity,0)}</b></span><span>Installation openings <b>{scenario.installationOpeningCount}</b></span><span>Crew <b>{scenario.options?.crewSize??2}</b></span><span>Programme <b>Day 1 set-out · productive days · completion and return</b></span></div></Section>:null}
    {materialsVisible?<Section index={6} kind="materials" title="Installation Materials" summary={`${materials.length+(scenario.me508Calculation?1:0)} selected`} cost={money(String(materialsCost))} converted={money(materialsCost)} markup={markupDraft.materials} sale={money(materialsSale)} open={open==="materials"} onToggle={()=>toggle("materials")} onMarkupChange={value=>editMarkup("materials",value)} onMarkupKeyDown={markupKeys("materials")} invalid={Boolean(validateMarkupPercentage(markupDraft.materials))}><div className="costing-sheet__detail-list">{materials.map(item=><CommercialRow key={item.id} description={item.label} cost={money(item.unitCost,item.currency)} converted={money(item.unitCost)} rate={`${scenario.markups.installation}%`} sale={money(item.unitCost)}/>)}{scenario.me508Calculation?<CommercialRow description={`ME508 internal membrane · ${scenario.me508Calculation.rollsRequired} rolls / ${scenario.me508Calculation.boxesRequired} boxes`} cost={scenario.me508Calculation.totalCost?money(scenario.me508Calculation.totalCost):"Price required"} converted={scenario.me508Calculation.totalCost?money(scenario.me508Calculation.totalCost):"Price required"} rate={`${scenario.markups.installation}%`} sale={scenario.me508Calculation.totalCost?money(scenario.me508Calculation.totalCost):"Price required"}/>:null}</div></Section>:null}
    {fees.length?<Section index={7} kind="duties" title="Import Fees & Duties" summary={`${fees.length} items`} cost={money(String(original(fees)),scenario.currency)} converted={money(feeGbp)} markup={markupDraft.duties} sale={money(feeSale)} open={open==="duties"} onToggle={()=>toggle("duties")} onMarkupChange={value=>editMarkup("duties",value)} onMarkupKeyDown={markupKeys("duties")} invalid={Boolean(validateMarkupPercentage(markupDraft.duties))}><div className="costing-sheet__detail-list">{fees.map(row=><CommercialRow key={row.id} description={row.label} cost={money(row.originalAmount,row.originalCurrency??scenario.currency)} converted={money(row.gbpAmount)} rate={`${row.markupPercent}%`} sale={money(row.markedUpAmount)}/>)}</div></Section>:null}
<section className="costing-sheet__summary"><h2>Commercial Summary</h2><div className="costing-sheet__summary-categories">{[["Products / Supply Only",productSale],["Extras",extrasSale],["Transport",transportSale],["Equipment Hire",equipmentSale],["Installation",installationSale],["Installation Materials",materialsSale],["Import Fees & Duties",feeSale]].map(([label,value])=><div key={String(label)}><span>{label}</span><b>{money(String(value))}</b></div>)}</div><div className="costing-sheet__summary-cost"><div><strong>Original supplier purchase total</strong><b>{money(supplierTotal,scenario.currency)}</b></div><div><strong>Actual GBP purchase cost at live rate</strong><b>{money(supplierPurchaseGbp)}</b></div><div><strong>Project Cost (Ex VAT)</strong><b>{money(projectCost)}</b></div><div><span>VAT <small>0% · not configured</small></span><b>{money("0")}</b></div><div className="costing-sheet__summary-highlight"><strong>Project Cost (Inc VAT)</strong><b>{money(projectCost)}</b></div></div><div className="costing-sheet__summary-profit"><div className="costing-sheet__summary-sale"><strong>Selling Price</strong><b>{money(sale)}</b></div><div><strong>Gross Profit</strong><b>{money(profit)}</b></div><div><strong>Gross Margin</strong><b>{percentageRatio(profit,sale)}%</b></div><div><strong>Overall Markup</strong><b>{percentageRatio(profit,projectCost)}%</b></div></div></section><p className="costing-sheet__footer">All calculations use the saved {scenario.exchangeRate?.provider??"exchange-rate"} snapshot of {rate}{scenario.exchangeRate?.providerTimestamp?` from ${new Date(scenario.exchangeRate.providerTimestamp).toLocaleDateString()}`:""}. Supplier costs remain immutable and are shown exclusive of VAT.</p>
   </main></div>
 </div>;
}
