import React, { useEffect, useState } from "react";
import { projectCalculatorLabApi } from "./api/projectCalculatorLabApi";
import { subtractDecimalAmounts } from "./domain/projectCostingMarkup";
import { CANONICAL_QUOTATION_PACKAGE_LEVELS, correctQuotationPackageMeaning, type CanonicalQuotationPackageLevel } from "../../../shared/quotationPackageModel.js";

type PackageDefinition = { id: string; label: string; sourceLabel?: string; description?: string; amount: string; amountProvenance?: string; sourceTrace?: unknown[]; isBase?: boolean; selected?: boolean; enabled?: boolean; displayOrder?: number; upliftCategory?: string | null; canonicalPackageLevel?: CanonicalQuotationPackageLevel | null; canonicalPackageLabel?: string; canonicalMeaningProvenance?: string };
export type SupplierCommercialResult = { supplierName: string; revisionId: string; quotationReference?: string; policy: Record<string, any>; pricingMethod?: string; pricingProvenance?: Record<string, any>; standardDiscountStages: Array<Record<string, any>>; effectiveManufacturerDiscountPercentage: string; standardNetBuyingAmount: string; projectDiscountAmount: string; projectDiscountPercentage: string; discountedSupplierPurchaseAmount: string; basePackageAmount: string; selectedPackageAmount: string; packageUplift: string; packageUpliftCategory: string | null; settlementAmount: string | null; settlementAmountEstimated: boolean; actualGbpPurchaseCost: string | null; totalSupplierDirectCost?: string; documentSelectedPackageId?: string | null };
const currency = (value: string | undefined) => String(value || "GBP").toUpperCase();
const money = (value: string | null | undefined, code: string) => value == null ? "—" : new Intl.NumberFormat("en-GB", { style: "currency", currency: code }).format(Number(value));
const methodLabel = (method: string | undefined) => ({ factory_price: "Factory Price", parity_1_to_1: "1 to 1 Pricing", staged_discount: "Staged Discount", legacy_net_buying_price: "Legacy net buying-price policy", legacy_manufacturer_factory_price: "Legacy manufacturer/factory policy", legacy_manufacturer_list: "Legacy manufacturer-list policy" } as Record<string, string>)[method ?? ""] ?? "Legacy policy (preserved)";
const packageMeaningProvenance = (value: string | undefined) => ({ quotation_wording: "Auto-detected from quotation", recognized_marketing_sequence: "Auto-detected from quotation package sequence", manual: "Manually selected", review_required: "Please confirm" } as Record<string, string>)[value ?? ""] ?? "Historical package mapping";

export default function SupplierCommercialReview({ scenarioId, policies, onSaveSupplier }: { scenarioId: string; policies: SupplierCommercialResult[]; onSaveSupplier?: (revisionId: string, policy: Record<string, unknown>) => Promise<void> }) {
  const [drafts, setDrafts] = useState<Record<string, Record<string, any>>>({});
  const [status, setStatus] = useState("");
  const [open, setOpen] = useState(false);
  useEffect(() => setDrafts(Object.fromEntries(policies.map(item => [item.revisionId, item.policy]))), [policies]);
  const saveSupplier = onSaveSupplier ?? (async (revisionId, policy) => { const updated = await projectCalculatorLabApi.updateSupplierCommercialPolicy(scenarioId, revisionId, policy); window.dispatchEvent(new CustomEvent("quotesuite:costing-updated", { detail: updated })); });
  const patch = (id: string, value: Record<string, unknown>) => setDrafts(current => ({ ...current, [id]: { ...current[id], ...value } }));
  const persist = async (result: SupplierCommercialResult, policy: Record<string, any>, message = "Supplier commercial selection saved.") => { setStatus("Saving…"); await saveSupplier(result.revisionId, policy); setStatus(message); };
  if (!policies.length) return null;
  return <><button type="button" className="ui-button supplier-commercial-review__amend" onClick={()=>setOpen(true)}>Amend Commercial Choices</button>{open?<div className="ui-modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setOpen(false)}}><section className="ui-modal supplier-commercial-review" role="dialog" aria-modal="true" aria-label="Amend Commercial Choices"><header className="supplier-commercial-review__heading"><span><strong>Amend Commercial Choices</strong><small>Estimate-only snapshot · Administration defaults are unchanged</small></span><button className="ui-button" onClick={()=>setOpen(false)} aria-label="Close commercial choices">×</button></header>
    {policies.map(result => { const policy = drafts[result.revisionId] ?? result.policy, quoted = currency(policy.quotedCurrency), packages = (Array.isArray(policy.packages) ? policy.packages : []) as PackageDefinition[], base = packages.find(entry => entry.isBase), selected = packages.find(entry => entry.id === policy.selectedPackageId) ?? base, projectDiscount = policy.projectDiscount ?? { mode: "percentage", percentage: "0", amount: "0" }, sourceEvidence = policy.sourceProductCommercialEvidence as Record<string, any> | null, sourceDiscountApplied = sourceEvidence && policy.sourceDiscountDecision?.status === "applied", method = result.pricingMethod ?? policy.pricingMethod;
      return <article className="supplier-commercial-review__supplier" key={result.revisionId}>
        <header><div><strong>{result.supplierName}</strong><small>{result.quotationReference ? `Quote ${result.quotationReference} · ` : ""}{methodLabel(method)}</small></div><div><span>{sourceEvidence ? "Products / Supply list basis" : "Net Supplier Buying Price"}</span><strong>{money(sourceEvidence?.grossListAmount ?? result.standardNetBuyingAmount, quoted)}</strong></div><div><span>{sourceEvidence ? "Current product purchase basis" : "GBP costing basis"}</span><strong>{money(sourceDiscountApplied ? sourceEvidence.netProductSubtotal : sourceEvidence?.grossListAmount ?? result.actualGbpPurchaseCost, sourceEvidence ? quoted : "GBP")}</strong></div></header>
        {method === "parity_1_to_1" ? <p className="supplier-commercial-review__evidence">1 to 1 Pricing deliberately applies numeric parity to the GBP costing basis. It does not state that the saved market exchange rate is 1.0000.</p> : null}
        {result.standardDiscountStages.length ? <div className="supplier-commercial-review__calculation"><strong>Internal supplier calculation</strong><div><span>Manufacturer/List Price</span><b>{money(result.standardDiscountStages[0]?.beforeAmount ?? policy.manufacturerListAmount ?? policy.quotedAmount, quoted)}</b></div>{result.standardDiscountStages.map(stage => <div key={stage.id ?? stage.sequence}><span>{stage.label ?? `Discount ${Number(stage.sequence) + 1}`} — {stage.percentage}%</span><b>−{money(stage.discountAmount, quoted)} · after {money(stage.resultingAmount, quoted)}</b></div>)}<div><span>Net Supplier Buying Price</span><b>{money(result.standardNetBuyingAmount, quoted)}</b></div></div> : null}
        {packages.length ? <><div className="supplier-package-options" role="radiogroup" aria-label={`${result.supplierName} supplier package`}>{packages.filter(entry => entry.enabled !== false).sort((a, b) => Number(a.displayOrder ?? 0) - Number(b.displayOrder ?? 0)).map(entry => { const uplift = base ? subtractDecimalAmounts(entry.amount, base.amount) : "0", active = entry.id === selected?.id; return <button key={entry.id} className={`supplier-package-option${active ? " is-selected" : ""}`} role="radio" aria-checked={active} onClick={() => { const next = { ...policy, selectedPackageId: entry.id }; patch(result.revisionId, { selectedPackageId: entry.id }); void persist(result, next, `${entry.label} selected.`); }}><span><strong>{entry.sourceLabel ?? entry.label}</strong><small>{entry.canonicalPackageLabel ?? (entry.isBase ? "Supply Only" : entry.description || "Please confirm")}</small></span><span><b>{money(entry.amount, quoted)}</b><small>{entry.isBase ? "Base" : `+${money(uplift, quoted)} uplift`}</small></span></button>; })}</div><div className="supplier-package-meaning-review" aria-label="Canonical package meaning review"><p>Supplier labels and quoted amounts remain unchanged. Correct only the canonical service meaning if detection is wrong.</p>{packages.filter(entry => entry.enabled !== false).sort((a, b) => Number(a.displayOrder ?? 0) - Number(b.displayOrder ?? 0)).map(entry => <label key={`meaning-${entry.id}`}><span><strong>{entry.sourceLabel ?? entry.label}</strong><small>{packageMeaningProvenance(entry.canonicalMeaningProvenance)} · price from supplier quotation</small></span><select className="ui-input" aria-label={`Canonical meaning for ${entry.sourceLabel ?? entry.label}`} value={entry.canonicalPackageLevel ?? ""} onChange={event => { const corrected = correctQuotationPackageMeaning(packages as Array<Record<string, unknown>>, entry.id, event.currentTarget.value as CanonicalQuotationPackageLevel) as PackageDefinition[]; const next = { ...policy, packages: corrected }; patch(result.revisionId, { packages: corrected }); void persist(result, next, `${entry.sourceLabel ?? entry.label} mapped to ${event.currentTarget.selectedOptions[0]?.textContent ?? "the selected service level"}.`); }}><option value="" disabled>Please confirm</option>{CANONICAL_QUOTATION_PACKAGE_LEVELS.map(level => <option key={level.id} value={level.id}>{level.label}</option>)}</select></label>)}</div><div className="supplier-package-summary"><span>Total Supplier Direct Cost <strong>{money(result.totalSupplierDirectCost, quoted)}</strong></span></div>{result.documentSelectedPackageId ? <small className="supplier-commercial-review__evidence">Supplier document indicated a package selection. QuoteSuite costing selection remains reviewable.</small> : null}</> : null}
        {sourceEvidence ? <div className="supplier-project-discount supplier-project-discount--source"><span><strong>Supplier discount available</strong><small>{sourceEvidence.discountPercentage}% · {money(sourceEvidence.discountAmount, quoted)} · supplier quoted net products {money(sourceEvidence.netProductSubtotal, quoted)}</small></span><span className="ui-badge">{sourceDiscountApplied ? "Applied by user" : "Available · not applied"}</span><button className="ui-button" onClick={() => { const next = sourceDiscountApplied ? { ...policy, sourceDiscountDecision: { status: "not_applied" }, projectDiscount: { mode: "percentage", percentage: "0", amount: "0" } } : { ...policy, sourceDiscountDecision: { status: "applied", evidenceVersion: sourceEvidence.version, appliedAt: new Date().toISOString() }, projectDiscount: { mode: "fixed", amount: sourceEvidence.discountAmount, percentage: sourceEvidence.discountPercentage, source: "supplier_quotation", scope: "products_supply", evidenceVersion: sourceEvidence.version } }; patch(result.revisionId, next); void persist(result, next, sourceDiscountApplied ? "Supplier discount removed; source list prices remain unchanged." : "Supplier discount applied to the Products / Supply total; source list prices remain unchanged."); }}>{sourceDiscountApplied ? "Remove supplier discount" : "Apply supplier discount"}</button></div> : <div className="supplier-project-discount"><label>Additional project supplier discount<select className="ui-input" value={projectDiscount.mode} onChange={event => patch(result.revisionId, { projectDiscount: { ...projectDiscount, mode: event.currentTarget.value } })}><option value="percentage">Percentage</option><option value="fixed">Fixed monetary amount</option></select></label><label>{projectDiscount.mode === "fixed" ? `Discount (${quoted})` : "Discount %"}<input className="ui-input" inputMode="decimal" value={projectDiscount.mode === "fixed" ? projectDiscount.amount ?? "0" : projectDiscount.percentage ?? "0"} onChange={event => patch(result.revisionId, { projectDiscount: { ...projectDiscount, [projectDiscount.mode === "fixed" ? "amount" : "percentage"]: event.currentTarget.value } })} /></label><span>Calculated reduction <strong>−{money(result.projectDiscountAmount, quoted)}</strong></span><button className="ui-button" onClick={() => void persist(result, policy, "Project supplier discount saved.")}>Save discount</button></div>}
        <details className="supplier-commercial-review__advanced"><summary>Advanced supplier pricing</summary><label>Pricing Method<select className="ui-input" value={method} onChange={event => patch(result.revisionId, { pricingBasis: event.currentTarget.value, pricingMethod: event.currentTarget.value, pricingPolicyVersion: 2 })}><option value="factory_price">Factory Price</option><option value="parity_1_to_1">1 to 1 Pricing</option><option value="staged_discount">Staged Discount</option>{String(method).startsWith("legacy_") ? <option value={method}>Legacy policy (preserved)</option> : null}</select></label><button className="ui-button" disabled={String(method).startsWith("legacy_")} onClick={() => void persist(result, policy)}>Save advanced pricing</button></details>
      </article>; })}
  <footer><small>{status||"Changes create Estimate costing history and preserve prior revisions."}</small><button className="ui-button" onClick={()=>setOpen(false)}>Close</button></footer></section></div>:null}</>;
}
