import {useEffect,useState} from "react";
import Toggle from "../../components/Toggle";
import {projectCalculatorLabApi} from "./api/projectCalculatorLabApi";
import {subtractDecimalAmounts} from "./domain/projectCostingMarkup";

type PackageDefinition={id:string;label:string;description?:string;amount:string;isBase?:boolean;selected?:boolean;enabled?:boolean;displayOrder?:number;upliftCategory?:string|null};
export type SupplierCommercialResult={supplierName:string;revisionId:string;policy:Record<string,any>;standardDiscountStages:Array<Record<string,any>>;effectiveManufacturerDiscountPercentage:string;standardNetBuyingAmount:string;projectDiscountAmount:string;projectDiscountPercentage:string;discountedSupplierPurchaseAmount:string;basePackageAmount:string;selectedPackageAmount:string;packageUplift:string;packageUpliftCategory:string|null;settlementAmount:string|null;settlementAmountEstimated:boolean;actualGbpPurchaseCost:string|null;totalSupplierDirectCost?:string;documentSelectedPackageId?:string|null};
const currency=(value:string|undefined)=>String(value||"GBP").toUpperCase();
const money=(value:string|null|undefined,code:string)=>value==null?"—":new Intl.NumberFormat("en-GB",{style:"currency",currency:code}).format(Number(value));

export default function SupplierCommercialReview({scenarioId,policies,onSaveSupplier}:{scenarioId:string;policies:SupplierCommercialResult[];onSaveSupplier?:(revisionId:string,policy:Record<string,unknown>)=>Promise<void>}){
 const[drafts,setDrafts]=useState<Record<string,Record<string,any>>>({}),[status,setStatus]=useState("");
 useEffect(()=>setDrafts(Object.fromEntries(policies.map(item=>[item.revisionId,item.policy]))),[policies]);
 const saveSupplier=onSaveSupplier??(async(revisionId,policy)=>{const updated=await projectCalculatorLabApi.updateSupplierCommercialPolicy(scenarioId,revisionId,policy);window.dispatchEvent(new CustomEvent("quotesuite:costing-updated",{detail:updated}))});
 const patch=(id:string,value:Record<string,unknown>)=>setDrafts(current=>({...current,[id]:{...current[id],...value}}));
 const persist=async(result:SupplierCommercialResult,policy:Record<string,any>,message="Supplier commercial selection saved.")=>{setStatus("Saving…");await saveSupplier(result.revisionId,policy);setStatus(message)};
 return <section className="ui-card calculator-lab__card supplier-commercial-review">
  <div className="supplier-commercial-review__heading"><div><h2>Supplier commercial selection</h2><p>Review project-specific choices. Standard supplier discount policies remain managed in Administration.</p></div>{status?<span className="ui-status-badge" role="status">{status}</span>:null}</div>
  {policies.map(result=>{const policy=drafts[result.revisionId]??result.policy,quoted=currency(policy.quotedCurrency),settlement=currency(policy.settlementCurrency),packages=(Array.isArray(policy.packages)?policy.packages:[]) as PackageDefinition[],base=packages.find(entry=>entry.isBase),selected=packages.find(entry=>entry.id===policy.selectedPackageId)??base,documentSelected=packages.find(entry=>entry.id===(policy.supplierDocumentPackageId??packages.find(item=>item.selected)?.id)),uplift=base&&selected?subtractDecimalAmounts(selected.amount,base.amount):"0",projectDiscount=policy.projectDiscount??{mode:"percentage",percentage:"0",amount:"0"},discountValue=projectDiscount.mode==="fixed"?money(result.projectDiscountAmount||projectDiscount.amount,quoted):`${projectDiscount.percentage??"0"}% · −${money(result.projectDiscountAmount,quoted)}`;
   return <article className="supplier-commercial-review__supplier" key={result.revisionId}>
    <header><div><strong>{result.supplierName}</strong><small>{packages.length?`Base Supply Only ${money(base?.amount,quoted)}`:`Normal supplier buying price ${money(result.standardNetBuyingAmount||policy.quotedAmount,quoted)}`}</small></div><div><span>Settlement</span><strong>{settlement}</strong></div><div><span>Additional project supplier discount</span><strong>{discountValue}</strong></div></header>
    {packages.length?<><div className="supplier-package-options" role="radiogroup" aria-label={`${result.supplierName} supplier package`}>{packages.filter(entry=>entry.enabled!==false).sort((a,b)=>Number(a.displayOrder??0)-Number(b.displayOrder??0)).map(entry=>{const entryUplift=base?subtractDecimalAmounts(entry.amount,base.amount):"0",active=entry.id===selected?.id;return <button key={entry.id} className={`supplier-package-option${active?" is-selected":""}`} role="radio" aria-checked={active} onClick={()=>{const next={...policy,selectedPackageId:entry.id};patch(result.revisionId,{selectedPackageId:entry.id});void persist(result,next,`${entry.label} selected.`)}}><span><strong>{entry.label}</strong><small>{entry.isBase?"Base Supply Only":entry.description||entry.label}</small></span><span><b>{money(entry.amount,quoted)}</b><small>{entry.isBase?"Base":`+${money(entryUplift,quoted)} uplift`}</small></span></button>})}</div><div className="supplier-package-summary"><span>Products / Supply Only <strong>{money(base?.amount,quoted)}</strong></span><span>{selected?.isBase?"Package uplift":selected?.description||selected?.label} <strong>{money(uplift,quoted)}</strong></span><span>Total Supplier Direct Cost <strong>{money(selected?.amount,quoted)}</strong></span></div>{documentSelected?<small className="supplier-commercial-review__evidence">Supplier document indicated: {documentSelected.label}. QuoteSuite costing selection remains reviewable.</small>:null}</>:null}
    <div className="supplier-project-discount"><label>Additional project supplier discount<select className="ui-input" value={projectDiscount.mode} onChange={event=>patch(result.revisionId,{projectDiscount:{...projectDiscount,mode:event.currentTarget.value}})}><option value="percentage">Percentage</option><option value="fixed">Fixed monetary amount</option></select></label><label>{projectDiscount.mode==="fixed"?`Discount (${quoted})`:"Discount %"}<input className="ui-input" inputMode="decimal" value={projectDiscount.mode==="fixed"?projectDiscount.amount??"0":projectDiscount.percentage??"0"} onChange={event=>patch(result.revisionId,{projectDiscount:{...projectDiscount,[projectDiscount.mode==="fixed"?"amount":"percentage"]:event.currentTarget.value}})}/></label><span>Calculated reduction <strong>−{money(result.projectDiscountAmount,quoted)}</strong>{projectDiscount.mode==="fixed"?<small>{result.projectDiscountPercentage}% equivalent</small>:null}</span><button className="ui-button" onClick={()=>void persist(result,policy,"Project supplier discount saved.")}>Save discount</button></div>
    <details className="supplier-commercial-review__advanced"><summary>Advanced supplier pricing</summary><div className="calculator-lab__form"><label>Pricing basis override<select className="ui-input" value={policy.pricingBasis} onChange={event=>patch(result.revisionId,{pricingBasis:event.currentTarget.value})}><option value="net_buying_price">Net Supplier Buying Price</option><option value="manufacturer_factory_price">Manufacturer / Factory Price</option><option value="manufacturer_list">Manufacturer List Price + Admin Policy</option></select></label><label>Paid in quoted currency?<Toggle value={policy.paidInQuotedCurrency!==false} onChange={value=>patch(result.revisionId,{paidInQuotedCurrency:value,settlementCurrency:value?quoted:settlement})}/></label>{policy.paidInQuotedCurrency===false?<><label>Settlement currency<input className="ui-input" maxLength={3} value={settlement} onChange={event=>patch(result.revisionId,{settlementCurrency:event.currentTarget.value.toUpperCase()})}/></label><label>Settlement amount mode<select className="ui-input" value={policy.settlementAmountMode} onChange={event=>patch(result.revisionId,{settlementAmountMode:event.currentTarget.value})}><option value="estimated">Estimated from FX</option><option value="confirmed">Confirmed Supplier Settlement Amount</option></select></label>{policy.settlementAmountMode==="confirmed"?<label>Confirmed settlement amount<input className="ui-input" inputMode="decimal" value={policy.confirmedSettlementAmount??""} onChange={event=>patch(result.revisionId,{confirmedSettlementAmount:event.currentTarget.value})}/></label>:null}</>:null}{packages.length?<label>Discount application override<select className="ui-input" value={policy.discountApplicationBasis??"selected_complete_package"} onChange={event=>patch(result.revisionId,{discountApplicationBasis:event.currentTarget.value})}><option value="selected_complete_package">Selected complete package</option><option value="base_supply_only">Base Supply Only package</option><option value="package_uplift">Package uplift only</option></select></label>:null}<button className="ui-button" onClick={()=>void persist(result,policy)}>Save advanced pricing</button></div></details>
   </article>})}
 </section>;
}
