import { useEffect, useState } from "react";
import { projectCalculatorLabApi } from "./api/projectCalculatorLabApi";
import { subtractDecimalAmounts } from "./domain/projectCostingMarkup";

type PackageDefinition = { id: string; label: string; description?: string; amount: string; isBase?: boolean; selected?: boolean; enabled?: boolean; displayOrder?: number; upliftCategory?: string | null };
export type SupplierCommercialResult = { supplierName: string; revisionId: string; policy: Record<string, any>; pricingMethod?: string; pricingProvenance?: Record<string, any>; standardDiscountStages: Array<Record<string, any>>; effectiveManufacturerDiscountPercentage: string; standardNetBuyingAmount: string; projectDiscountAmount: string; projectDiscountPercentage: string; discountedSupplierPurchaseAmount: string; basePackageAmount: string; selectedPackageAmount: string; packageUplift: string; packageUpliftCategory: string | null; settlementAmount: string | null; settlementAmountEstimated: boolean; actualGbpPurchaseCost: string | null; totalSupplierDirectCost?: string; documentSelectedPackageId?: string | null };
const currency = (value: string | undefined) => String(value || "GBP").toUpperCase();
const money = (value: string | null | undefined, code: string) => value == null ? "—" : new Intl.NumberFormat("en-GB", { style: "currency", currency: code }).format(Number(value));
const methodLabel = (method: string | undefined) => ({ factory_price: "Factory Price", parity_1_to_1: "1 to 1 Pricing", staged_discount: "Staged Discount", legacy_net_buying_price: "Legacy net buying-price policy", legacy_manufacturer_factory_price: "Legacy manufacturer/factory policy", legacy_manufacturer_list: "Legacy manufacturer-list policy" } as Record<string, string>)[method ?? ""] ?? "Legacy policy (preserved)";

export default function SupplierCommercialReview({ scenarioId, policies, onSaveSupplier }: { scenarioId: string; policies: SupplierCommercialResult[]; onSaveSupplier?: (revisionId: string, policy: Record<string, unknown>) => Promise<void> }) {
  const [drafts, setDrafts] = useState<Record<string, Record<string, any>>>({});
  const [status, setStatus] = useState("");
  useEffect(() => setDrafts(Object.fromEntries(policies.map(item => [item.revisionId, item.policy]))), [policies]);
  const saveSupplier = onSaveSupplier ?? (async (revisionId, policy) => { const updated = await projectCalculatorLabApi.updateSupplierCommercialPolicy(scenarioId, revisionId, policy); window.dispatchEvent(new CustomEvent("quotesuite:costing-updated", { detail: updated })); });
  const patch = (id: string, value: Record<string, unknown>) => setDrafts(current => ({ ...current, [id]: { ...current[id], ...value } }));
  const persist = async (result: SupplierCommercialResult, policy: Record<string, any>, message = "Supplier commercial selection saved.") => { setStatus("Saving…"); await saveSupplier(result.revisionId, policy); setStatus(message); };
  if (!policies.length) return null;
  return <details className="ui-card supplier-commercial-review supplier-commercial-review--compact">
    <summary className="supplier-commercial-review__heading"><span><strong>Supplier commercial choices</strong><small>{policies.map(item => `${item.supplierName} · ${methodLabel(item.pricingMethod ?? item.policy.pricingMethod)} · ${currency(item.policy.settlementCurrency)} settlement`).join(" · ")}</small></span><span>{status || "Edit"}</span></summary>
    {policies.map(result => { const policy = drafts[result.revisionId] ?? result.policy, quoted = currency(policy.quotedCurrency), packages = (Array.isArray(policy.packages) ? policy.packages : []) as PackageDefinition[], base = packages.find(entry => entry.isBase), selected = packages.find(entry => entry.id === policy.selectedPackageId) ?? base, projectDiscount = policy.projectDiscount ?? { mode: "percentage", percentage: "0", amount: "0" }, method = result.pricingMethod ?? policy.pricingMethod;
      return <article className="supplier-commercial-review__supplier" key={result.revisionId}>
        <header><div><strong>{result.supplierName}</strong><small>{methodLabel(method)}</small></div><div><span>Net Supplier Buying Price</span><strong>{money(result.standardNetBuyingAmount, quoted)}</strong></div><div><span>GBP costing basis</span><strong>{money(result.actualGbpPurchaseCost, "GBP")}</strong></div></header>
        {method === "parity_1_to_1" ? <p className="supplier-commercial-review__evidence">1 to 1 Pricing deliberately applies numeric parity to the GBP costing basis. It does not state that the saved market exchange rate is 1.0000.</p> : null}
        {result.standardDiscountStages.length ? <div className="supplier-commercial-review__calculation"><strong>Internal supplier calculation</strong><div><span>Manufacturer/List Price</span><b>{money(result.standardDiscountStages[0]?.beforeAmount ?? policy.manufacturerListAmount ?? policy.quotedAmount, quoted)}</b></div>{result.standardDiscountStages.map(stage => <div key={stage.id ?? stage.sequence}><span>{stage.label ?? `Discount ${Number(stage.sequence) + 1}`} — {stage.percentage}%</span><b>−{money(stage.discountAmount, quoted)} · after {money(stage.resultingAmount, quoted)}</b></div>)}<div><span>Net Supplier Buying Price</span><b>{money(result.standardNetBuyingAmount, quoted)}</b></div></div> : null}
        {packages.length ? <><div className="supplier-package-options" role="radiogroup" aria-label={`${result.supplierName} supplier package`}>{packages.filter(entry => entry.enabled !== false).sort((a, b) => Number(a.displayOrder ?? 0) - Number(b.displayOrder ?? 0)).map(entry => { const uplift = base ? subtractDecimalAmounts(entry.amount, base.amount) : "0", active = entry.id === selected?.id; return <button key={entry.id} className={`supplier-package-option${active ? " is-selected" : ""}`} role="radio" aria-checked={active} onClick={() => { const next = { ...policy, selectedPackageId: entry.id }; patch(result.revisionId, { selectedPackageId: entry.id }); void persist(result, next, `${entry.label} selected.`); }}><span><strong>{entry.label}</strong><small>{entry.isBase ? "Base Supply Only" : entry.description || entry.label}</small></span><span><b>{money(entry.amount, quoted)}</b><small>{entry.isBase ? "Base" : `+${money(uplift, quoted)} uplift`}</small></span></button>; })}</div><div className="supplier-package-summary"><span>Total Supplier Direct Cost <strong>{money(result.totalSupplierDirectCost, quoted)}</strong></span></div>{result.documentSelectedPackageId ? <small className="supplier-commercial-review__evidence">Supplier document indicated a package selection. QuoteSuite costing selection remains reviewable.</small> : null}</> : null}
        <div className="supplier-project-discount"><label>Additional project supplier discount<select className="ui-input" value={projectDiscount.mode} onChange={event => patch(result.revisionId, { projectDiscount: { ...projectDiscount, mode: event.currentTarget.value } })}><option value="percentage">Percentage</option><option value="fixed">Fixed monetary amount</option></select></label><label>{projectDiscount.mode === "fixed" ? `Discount (${quoted})` : "Discount %"}<input className="ui-input" inputMode="decimal" value={projectDiscount.mode === "fixed" ? projectDiscount.amount ?? "0" : projectDiscount.percentage ?? "0"} onChange={event => patch(result.revisionId, { projectDiscount: { ...projectDiscount, [projectDiscount.mode === "fixed" ? "amount" : "percentage"]: event.currentTarget.value } })} /></label><span>Calculated reduction <strong>−{money(result.projectDiscountAmount, quoted)}</strong></span><button className="ui-button" onClick={() => void persist(result, policy, "Project supplier discount saved.")}>Save discount</button></div>
        <details className="supplier-commercial-review__advanced"><summary>Advanced supplier pricing</summary><label>Pricing Method<select className="ui-input" value={method} onChange={event => patch(result.revisionId, { pricingBasis: event.currentTarget.value, pricingMethod: event.currentTarget.value, pricingPolicyVersion: 2 })}><option value="factory_price">Factory Price</option><option value="parity_1_to_1">1 to 1 Pricing</option><option value="staged_discount">Staged Discount</option>{String(method).startsWith("legacy_") ? <option value={method}>Legacy policy (preserved)</option> : null}</select></label><button className="ui-button" disabled={String(method).startsWith("legacy_")} onClick={() => void persist(result, policy)}>Save advanced pricing</button></details>
      </article>; })}
  </details>;
}
