import { useEffect, useMemo, useState } from "react";
import type { Client } from "../../models/types";
import { commercialIdentityApi, type ProjectRecord } from "../../services/commercialIdentity/commercialIdentityApi";
import { serviceApi, type ResponsibilityConfiguration, type ServiceCase, type ServiceTimer } from "./serviceApi";
import "./service.css";

const idempotency=()=>crypto.randomUUID();
const label=(value:string)=>value.replaceAll("_"," ").replace(/^./,letter=>letter.toUpperCase());
const clientLabel=(client:Client)=>client.businessName||client.clientName||client.contactPerson||client.clientRef;
const timerLabel:Record<string,string>={first_response:"First staff response",customer_update:"Next customer update",assessment_plan:"Assessment / plan",resolution:"Resolution target"};
const timerText=(timer:ServiceTimer)=>{if(timer.completedAt)return `Completed ${new Date(timer.completedAt).toLocaleString("en-GB")}`;if(timer.state==="paused")return `Paused · was due ${new Date(timer.dueAt).toLocaleString("en-GB")}`;const ms=new Date(timer.dueAt).getTime()-Date.now(),minutes=Math.round(Math.abs(ms)/60000),hours=Math.floor(minutes/60),remaining=`${hours?`${hours}h `:""}${minutes%60}m`;return ms<0?`${remaining} overdue`:`${remaining} remaining`};
const fileBase64=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error);reader.onload=()=>resolve(String(reader.result||"").split(",")[1]||"");reader.readAsDataURL(file)});

export default function ServiceWorkspace({clients}:{clients:Array<Client & {deletedAt?:string|null}>}){
  const[cases,setCases]=useState<ServiceCase[]>([]),[selectedId,setSelectedId]=useState(""),[selected,setSelected]=useState<ServiceCase|null>(null),[configuration,setConfiguration]=useState<ResponsibilityConfiguration|null>(null),[projects,setProjects]=useState<ProjectRecord[]>([]);
  const[search,setSearch]=useState(""),[statusFilter,setStatusFilter]=useState(""),[priorityFilter,setPriorityFilter]=useState(""),[teamFilter,setTeamFilter]=useState(""),[creating,setCreating]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const[draft,setDraft]=useState({clientId:"",projectId:"",caseType:"service",issueSummary:"",description:"",firstNoticedAt:"",priority:"normal",nextAction:"Review the reported issue",nextActionDueAt:""});
  const[edit,setEdit]=useState({status:"new",priority:"normal",waitingOn:"none",teamId:"",assigneeId:"",nextAction:"",nextActionDueAt:"",warrantyState:"not_assessed",warrantyEvidence:"",warrantyReason:"",resolution:""});
  const[updateBody,setUpdateBody]=useState(""),[updateVisibility,setUpdateVisibility]=useState<"customer"|"internal">("customer"),[reopenReason,setReopenReason]=useState("");
  const filters=useMemo(()=>Object.fromEntries(Object.entries({search,status:statusFilter,priority:priorityFilter,teamId:teamFilter}).filter(([,value])=>value)),[search,statusFilter,priorityFilter,teamFilter]);
  const loadList=async()=>{const rows=await serviceApi.list(filters);setCases(rows);setSelectedId(current=>current&&rows.some(item=>item.id===current)?current:rows[0]?.id||"")};
  const loadConfiguration=async()=>{const value=await serviceApi.configuration();setConfiguration(value.teams)};
  useEffect(()=>{const timer=setTimeout(()=>void loadList().catch(error=>setMessage(error instanceof Error?error.message:"Service cases could not be loaded.")),180);return()=>clearTimeout(timer)},[filters]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{void loadConfiguration().catch(()=>setConfiguration(null))},[]);
  useEffect(()=>{if(!draft.clientId){setProjects([]);return}void commercialIdentityApi.listProjects(draft.clientId).then(setProjects).catch(()=>setProjects([]))},[draft.clientId]);
  useEffect(()=>{const open=(event:Event)=>{const caseId=String((event as CustomEvent<{id?:string}>).detail?.id||"");if(caseId)setSelectedId(caseId)};window.addEventListener("quotesuite:open-service-case",open);return()=>window.removeEventListener("quotesuite:open-service-case",open)},[]);
  useEffect(()=>{if(!selectedId){setSelected(null);return}void serviceApi.get(selectedId).then(value=>{setSelected(value);setEdit({status:value.status,priority:value.priority,waitingOn:value.waitingOn,teamId:value.teamId||"",assigneeId:value.assigneeId||"",nextAction:value.nextAction,nextActionDueAt:String(value.nextActionDueAt||"").slice(0,10),warrantyState:value.warrantyState,warrantyEvidence:String(value.warrantyAssessment.evidence||""),warrantyReason:String(value.warrantyAssessment.reason||""),resolution:value.resolution})}).catch(error=>setMessage(error instanceof Error?error.message:"Service case could not be opened."))},[selectedId]);
  const run=async(action:()=>Promise<ServiceCase>,progress:string,success:(value:ServiceCase)=>string)=>{setBusy(true);setMessage(progress);try{const value=await action();setSelected(value);setSelectedId(value.id);await loadList();setMessage(success(value));return true}catch(error){setMessage(`${error instanceof Error?error.message:"The Service action could not be completed."} Your entries are retained; correct the issue and retry.`);return false}finally{setBusy(false)}};
  const create=async()=>{const saved=await run(()=>serviceApi.create({...draft,idempotencyKey:idempotency()}),"Registering Service case…",value=>`${value.reference} registered${value.teamName?` with ${value.teamName}`:" in Unassigned"}. Next: review the evidence and set the next action.`);if(saved){setCreating(false);setDraft({clientId:"",projectId:"",caseType:"service",issueSummary:"",description:"",firstNoticedAt:"",priority:"normal",nextAction:"Review the reported issue",nextActionDueAt:""})}};
  const eligibleProjects=projects.filter(project=>project.clientId===draft.clientId);
  const selectedTeam=configuration?.teams.find(team=>team.id===edit.teamId),members=selectedTeam?.members.filter(member=>member.active)||[];
  return <section className="service-workspace" aria-labelledby="service-title">
    <header className="ui-card"><div><span className="ui-eyebrow">Customer care</span><h2 id="service-title">Service</h2><p>See the issue, who owns it and what must happen next.</p></div><button className="ui-button ui-button--primary" onClick={()=>setCreating(true)}>Report an issue</button></header>
    {message?<p className="ui-status" role={/could not|unavailable|required|retry/i.test(message)?"alert":"status"}>{message}</p>:null}
    {creating?<section className="ui-card service-case__editor"><h3>Report an issue</h3><p>An Order is helpful but not required. Nothing is sent automatically.</p><div className="service-case__status-grid"><label>Client<select className="ui-select" value={draft.clientId} onChange={event=>setDraft(current=>({...current,clientId:event.currentTarget.value,projectId:""}))}><option value="">Choose Client</option>{clients.filter(client=>!client.deletedAt).map(client=><option key={client.id} value={client.id}>{client.clientRef} · {clientLabel(client)}</option>)}</select></label><label>Project, if known<select className="ui-select" value={draft.projectId} onChange={event=>setDraft(current=>({...current,projectId:event.currentTarget.value}))}><option value="">Not known / link later</option>{eligibleProjects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label>Case type<input className="ui-input" value={draft.caseType} onChange={event=>setDraft(current=>({...current,caseType:event.currentTarget.value}))}/></label><label>Priority<select className="ui-select" value={draft.priority} onChange={event=>setDraft(current=>({...current,priority:event.currentTarget.value}))}>{["low","normal","high","urgent"].map(value=><option key={value}>{value}</option>)}</select></label><label>Issue first noticed<input className="ui-input" type="date" value={draft.firstNoticedAt} onChange={event=>setDraft(current=>({...current,firstNoticedAt:event.currentTarget.value}))}/></label><label>Next action due<input className="ui-input" type="date" value={draft.nextActionDueAt} onChange={event=>setDraft(current=>({...current,nextActionDueAt:event.currentTarget.value}))}/></label></div><label>Issue summary<input className="ui-input" value={draft.issueSummary} onChange={event=>setDraft(current=>({...current,issueSummary:event.currentTarget.value}))}/></label><label>Description<textarea className="ui-textarea" rows={5} value={draft.description} onChange={event=>setDraft(current=>({...current,description:event.currentTarget.value}))}/></label><label>Next action<input className="ui-input" value={draft.nextAction} onChange={event=>setDraft(current=>({...current,nextAction:event.currentTarget.value}))}/></label><div className="service-workspace__actions"><button className="ui-button" disabled={busy} onClick={()=>setCreating(false)}>Cancel</button><button className="ui-button ui-button--primary" disabled={busy||!draft.clientId||!draft.issueSummary.trim()||!draft.description.trim()} onClick={()=>void create()}>{busy?"Registering issue…":"Register Service case"}</button></div></section>:null}
    <div className="service-workspace__filters ui-card"><label>Search<input className="ui-input" value={search} onChange={event=>setSearch(event.currentTarget.value)} placeholder="Reference, customer or issue"/></label><label>Status<select className="ui-select" value={statusFilter} onChange={event=>setStatusFilter(event.currentTarget.value)}><option value="">All statuses</option>{["new","under_review","awaiting","resolved","closed"].map(value=><option value={value} key={value}>{label(value)}</option>)}</select></label><label>Priority<select className="ui-select" value={priorityFilter} onChange={event=>setPriorityFilter(event.currentTarget.value)}><option value="">All priorities</option>{["low","normal","high","urgent"].map(value=><option key={value}>{label(value)}</option>)}</select></label><label>Team<select className="ui-select" value={teamFilter} onChange={event=>setTeamFilter(event.currentTarget.value)}><option value="">All teams</option>{configuration?.teams.map(team=><option key={team.id} value={team.id}>{team.name}</option>)}</select></label></div>
    <div className="service-workspace__layout"><nav className="ui-card service-workspace__list" aria-label="Service cases">{cases.map(item=><button key={item.id} className={item.id===selectedId?"is-selected":""} onClick={()=>setSelectedId(item.id)}><strong>{item.reference} · {item.issueSummary}</strong><span>{item.clientName}{item.projectName?` · ${item.projectName}`:""}</span><small>{label(item.status)} · {item.teamName||"Unassigned"} · {item.nextAction||"Next action not set"}</small></button>)}{!cases.length?<p className="ui-empty-state">No Service cases match these filters.</p>:null}</nav>
      <article className="ui-card service-case">{selected?<><header className="service-case__header"><div><span className="ui-eyebrow">{selected.reference}</span><h3>{selected.issueSummary}</h3><p>{selected.clientName}{selected.projectName?` · ${selected.projectName}`:""}</p></div><span className={`ui-status ${selected.status==="new"||selected.timers.some(timer=>timer.state==="breached")?"ui-status--warning":""}`}>{label(selected.status)}</span></header><section className="service-case__summary"><p>{selected.description}</p><div className="service-case__facts"><div><span>Responsible team</span><strong>{selected.teamName||"Unassigned"}</strong></div><div><span>Responsible person</span><strong>{selected.assigneeName||"Team queue / not assigned"}</strong></div><div><span>Waiting on</span><strong>{label(selected.waitingOn)}</strong></div><div><span>Next action</span><strong>{selected.nextAction||"Not set"}</strong><small>{selected.nextActionDueAt?new Date(selected.nextActionDueAt).toLocaleDateString("en-GB"):"No due date"}</small></div></div>{!selected.teamId?<p className="ui-status ui-status--warning">No valid routing rule applied. Choose a team below; this case remains visible in Unassigned.</p>:null}{selected.customerExpectation?<p className="ui-status">{selected.customerExpectation}</p>:<small>No approved customer-facing SLA is published for this case. Internal targets, if configured, remain staff-only.</small>}</section>
      {selected.timers.length?<section><h4>Service targets</h4><div className="service-case__timers">{selected.timers.map(timer=><article key={timer.id}><strong>{timerLabel[timer.targetKey]}</strong><span className={timer.state==="breached"?"ui-status ui-status--error":""}>{timerText(timer)}</span><small>Due {new Date(timer.dueAt).toLocaleString("en-GB")} · {timer.targetMinutes} business minutes</small></article>)}</div></section>:<p className="ui-empty-state">No configured internal target applies to this case.</p>}
      <section className="service-case__editor"><h4>Ownership, status and next action</h4><div className="service-case__status-grid"><label>Status<select className="ui-select" value={edit.status} onChange={event=>setEdit(current=>({...current,status:event.currentTarget.value}))}>{["new","under_review","awaiting","resolved","closed"].map(value=><option value={value} key={value}>{label(value)}</option>)}</select></label><label>Priority<select className="ui-select" value={edit.priority} onChange={event=>setEdit(current=>({...current,priority:event.currentTarget.value}))}>{["low","normal","high","urgent"].map(value=><option key={value}>{label(value)}</option>)}</select></label><label>Waiting on<select className="ui-select" value={edit.waitingOn} onChange={event=>setEdit(current=>({...current,waitingOn:event.currentTarget.value}))}>{["none","customer","supplier","internal"].map(value=><option key={value}>{label(value)}</option>)}</select></label><label>Team<select className="ui-select" value={edit.teamId} onChange={event=>setEdit(current=>({...current,teamId:event.currentTarget.value,assigneeId:""}))}><option value="">Unassigned</option>{configuration?.teams.filter(team=>team.active).map(team=><option key={team.id} value={team.id}>{team.name}</option>)}</select></label><label>Responsible person<select className="ui-select" value={edit.assigneeId} onChange={event=>setEdit(current=>({...current,assigneeId:event.currentTarget.value}))}><option value="">Team queue</option>{members.map(member=><option key={member.userId} value={member.userId}>{member.userName}</option>)}</select></label><label>Next action due<input className="ui-input" type="date" value={edit.nextActionDueAt} onChange={event=>setEdit(current=>({...current,nextActionDueAt:event.currentTarget.value}))}/></label></div><label>Next action<input className="ui-input" value={edit.nextAction} onChange={event=>setEdit(current=>({...current,nextAction:event.currentTarget.value}))}/></label><label>Resolution<textarea className="ui-textarea" rows={3} value={edit.resolution} onChange={event=>setEdit(current=>({...current,resolution:event.currentTarget.value}))} placeholder="Required before Resolved or Closed"/></label><button className="ui-button ui-button--primary" disabled={busy} onClick={()=>void run(()=>serviceApi.update(selected.id,{...edit,warrantyAssessment:{evidence:edit.warrantyEvidence,reason:edit.warrantyReason},assignmentReason:"Reviewed in Service",idempotencyKey:idempotency()}),"Saving Service case…",value=>`${value.reference} saved. Next: ${value.nextAction||"set the next action"}.`)}>{busy?"Saving case…":"Save case"}</button></section>
      <section className="service-case__editor"><h4>Warranty assessment</h4><p>Supplier warranty guidance is not available until the source documents below are retained and reviewed. Do not promise or reject coverage from this screen.</p><ul><li>Zyle warranty / claims terms — missing</li><li>Zyle installation and maintenance manual — missing</li></ul><div className="service-case__status-grid"><label>Assessment state<select className="ui-select" value={edit.warrantyState} onChange={event=>setEdit(current=>({...current,warrantyState:event.currentTarget.value}))}>{["not_assessed","potentially_covered","evidence_required","outside_supplier_terms","staff_confirmed"].map(value=><option value={value} key={value}>{label(value)}</option>)}</select></label><label>Source document, version, page / clause<textarea className="ui-textarea" rows={2} value={edit.warrantyEvidence} onChange={event=>setEdit(current=>({...current,warrantyEvidence:event.currentTarget.value}))}/></label><label>Reviewed reason and dates/evidence<textarea className="ui-textarea" rows={2} value={edit.warrantyReason} onChange={event=>setEdit(current=>({...current,warrantyReason:event.currentTarget.value}))}/></label></div><small>Missing purchase, delivery, installation and maintenance evidence must remain explicit. Supplier warranty expiry does not determine all customer rights.</small></section>
      <section className="service-case__editor"><h4>Add an update</h4><label>Visibility<select className="ui-select" value={updateVisibility} onChange={event=>setUpdateVisibility(event.currentTarget.value as typeof updateVisibility)}><option value="customer">Customer-visible update</option><option value="internal">Internal note</option></select></label><textarea className="ui-textarea" rows={4} value={updateBody} onChange={event=>setUpdateBody(event.currentTarget.value)} placeholder={updateVisibility==="customer"?"Explain what happens next in plain language":"Internal assessment, supplier discussion or reasoning"}/><button className="ui-button ui-button--primary" disabled={busy||!updateBody.trim()} onClick={()=>void run(()=>serviceApi.addUpdate(selected.id,{body:updateBody,visibility:updateVisibility,idempotencyKey:idempotency()}),"Saving update…",value=>{setUpdateBody("");return `${updateVisibility==="customer"?"Customer update":"Internal note"} saved to ${value.reference}.`})}>{busy?"Saving update…":"Save update"}</button></section>
      <section className="service-case__files"><h4>Photos and documents</h4><input className="ui-input" type="file" multiple onChange={async event=>{const files=[...(event.currentTarget.files||[])];if(!files.length)return;setBusy(true);setMessage(`Uploading ${files.length} Service file${files.length===1?"":"s"}…`);try{for(const file of files)await serviceApi.addAttachment(selected.id,{fileName:file.name,mediaType:file.type,contentBase64:await fileBase64(file),visibility:updateVisibility,idempotencyKey:idempotency()});setSelected(await serviceApi.get(selected.id));setMessage(`${files.length} file${files.length===1?"":"s"} saved to ${selected.reference}. Existing identical evidence was reused.`)}catch(error){setMessage(`${error instanceof Error?error.message:"A Service file could not be saved."} Completed files remain saved; retry only the missing file.`)}finally{setBusy(false);event.currentTarget.value=""}}}/>{selected.attachments.map(file=><article key={file.id}><strong>{file.fileName}</strong><small>{file.visibility} · {Math.ceil(file.sizeBytes/1024)} KB</small><a className="ui-button" href={file.downloadUrl} target="_blank" rel="noreferrer">Open</a></article>)}</section>
      <section className="service-case__history"><h4>History</h4>{selected.events.map(event=><article key={event.id}><strong>{label(event.eventType)}</strong><span>{event.body}</span><small>{event.visibility} · {event.actorType} · {new Date(event.occurredAt).toLocaleString("en-GB")}</small></article>)}</section>
      {(selected.status==="resolved"||selected.status==="closed")?<section className="service-case__editor"><h4>Reopen case</h4><label>Reason<textarea className="ui-textarea" rows={2} value={reopenReason} onChange={event=>setReopenReason(event.currentTarget.value)}/></label><button className="ui-button" disabled={busy||!reopenReason.trim()} onClick={()=>void run(()=>serviceApi.reopen(selected.id,{reason:reopenReason,idempotencyKey:idempotency()}),"Reopening case…",value=>{setReopenReason("");return `${value.reference} reopened with the reason preserved. Next: review the case.`})}>Reopen case</button></section>:null}</>:<p>Select a Service case.</p>}</article>
    </div>
  </section>;
}
