export type MarginStatus = "low" | "caution" | "healthy" | "strong" | "high";
export type CommercialMarginBand = { status: MarginStatus; minimumPercent: string };
export type CommercialMarginPolicy = { targetGrossMarginPercent: string; minimumAcceptableGrossMarginPercent: string; bands: CommercialMarginBand[]; capturedAt: string | null };
export const DEFAULT_COMMERCIAL_MARGIN_POLICY: CommercialMarginPolicy = { targetGrossMarginPercent:"35", minimumAcceptableGrossMarginPercent:"25", bands:[{status:"low",minimumPercent:"0"},{status:"caution",minimumPercent:"25"},{status:"healthy",minimumPercent:"30"},{status:"strong",minimumPercent:"35"},{status:"high",minimumPercent:"40"}], capturedAt:null };
const decimal=/^\d+(?:\.\d+)?$/;
const parts=(value:string)=>{const[whole,fraction=""]=value.split(".");return{value:BigInt(`${whole}${fraction}`),scale:fraction.length}};
const scaled=(value:string,places:number)=>{const parsed=parts(value);return parsed.value*10n**BigInt(places-parsed.scale)};
const formatMoney=(pence:bigint)=>`${pence/100n}.${String(pence%100n).padStart(2,"0")}`;
const ratio=(part:bigint,whole:bigint)=>{if(whole===0n)return"0.00";const hundredths=(part*10000n+(whole>0n?whole/2n:0n))/whole,absolute=hundredths<0n?-hundredths:hundredths;return`${hundredths<0n?"-":""}${absolute/100n}.${String(absolute%100n).padStart(2,"0")}`};
export function validateGrossMarginPercentage(value:string){if(!decimal.test(value))return"Enter a percentage without exponent notation.";const parsed=parts(value),places=Math.max(2,parsed.scale);return scaled(value,places)>=10000n*10n**BigInt(places-2)?"Gross margin must be below 100%.":null}
export function calculateCommercialMargin(directCost:string,sellingPrice:string,targetPercent:string){if(!decimal.test(directCost)||!decimal.test(sellingPrice)||validateGrossMarginPercentage(targetPercent))return null;const cost=scaled(directCost,2),sale=scaled(sellingPrice,2),profit=sale-cost,target=parts(targetPercent),base=100n*10n**BigInt(target.scale),remaining=base-target.value,targetSale=(cost*base+remaining/2n)/remaining,variance=sale-targetSale;return{grossProfit:`${profit<0n?"-":""}${formatMoney(profit<0n?-profit:profit)}`,grossMarginPercent:ratio(profit,sale),overallMarkupPercent:ratio(profit,cost),targetSellingPrice:formatMoney(targetSale),varianceAmount:formatMoney(variance<0n?-variance:variance),varianceDirection:variance<0n?"below" as const:"above" as const,requiredOverallMarkupPercent:ratio(target.value,remaining)}}
export function resolveMarginStatus(marginPercent:string,bands:CommercialMarginBand[]){const value=Number(marginPercent);return[...bands].sort((a,b)=>Number(a.minimumPercent)-Number(b.minimumPercent)).reduce<MarginStatus>((status,band)=>value>=Number(band.minimumPercent)?band.status:status,"low")}
