import express from 'express';
import { createProjectCalculatorLabService } from '../features/projectCalculatorLab/projectCalculatorLabService.js';
import { createCalculatorAdminService } from '../features/projectCalculatorLab/calculatorAdminService.js';

const fail=(res,status,code,message)=>res.status(status).json({code,error:message});

export async function createProjectCalculatorLabRouter({dbPromise, exchangeRateProvider}) {
  const router=express.Router();
  const service=createProjectCalculatorLabService(await dbPromise,{exchangeRateProvider});
  const admin=createCalculatorAdminService(await dbPromise);
  router.get('/admin-configuration',async(_req,res,next)=>{try{res.json(await admin.getConfiguration());}catch(error){next(error);}});
  router.patch('/admin-configuration/catalogue/:itemId',async(req,res,next)=>{try{const value=await admin.updateCatalogueItem(req.params.itemId,req.body||{});return value?res.json(value):fail(res,404,'catalogue_item_not_found','Catalogue item not found.');}catch(error){if(error.code==='invalid_catalogue')return fail(res,400,error.code,error.message);next(error);}});
  router.patch('/admin-configuration/rules/:ruleKey',async(req,res,next)=>{try{const value=await admin.updateRule(req.params.ruleKey,req.body?.value);return value?res.json(value):fail(res,404,'rule_not_found','Calculation rule not found.');}catch(error){next(error);}});
  router.patch('/admin-configuration/packages/:packageCode',async(req,res,next)=>{try{const value=await admin.updatePackage(req.params.packageCode,req.body?.inclusions||[]);return value?res.json(value):fail(res,404,'package_rule_not_found','Package rule not found.');}catch(error){next(error);}});
  router.get('/import-sources',async(req,res,next)=>{try{res.json(await service.listImportSources(req.query.estimate_id||null));}catch(error){next(error);}});
  router.get('/scenarios',async(req,res,next)=>{try{res.json(await service.listScenarios(req.query.estimate_id||null));}catch(error){next(error);}});
  router.post('/scenarios',async(req,res,next)=>{try{const origin=req.body?.origin??(req.body?.extractionRunId?'supplier_import':null);if(!['supplier_import','estimate','manual','mixed'].includes(origin))return fail(res,400,'invalid_scenario','A recognized scenario origin is required.');res.status(201).json(await service.createScenario({...req.body,origin}));}catch(error){if(['source_not_found','source_has_no_selected_items','invalid_scenario','origin_unavailable','feature_unavailable','exchange_rate_unavailable','estimate_not_found'].includes(error.code)){const status=['source_not_found','estimate_not_found'].includes(error.code)?404:['source_has_no_selected_items','origin_unavailable','feature_unavailable'].includes(error.code)?409:error.code==='exchange_rate_unavailable'?503:400;return fail(res,status,error.code,error.message);}next(error);}});
  router.get('/scenarios/:scenarioId',async(req,res,next)=>{try{const value=await service.getScenario(req.params.scenarioId);const estimateId=typeof req.query.estimate_id==='string'?req.query.estimate_id:'';return value&&(!estimateId||value.estimateId===estimateId)?res.json(value):fail(res,404,'scenario_not_found','Project Costing record not found for this estimate.');}catch(error){next(error);}});
  router.patch('/scenarios/:scenarioId',async(req,res,next)=>{try{const value=await service.updateScenario(req.params.scenarioId,req.body||{});return value?res.json(value):fail(res,404,'scenario_not_found','Calculator scenario not found.');}catch(error){if(error.code==='invalid_scenario')return fail(res,400,error.code,error.message);next(error);}});
  router.patch('/scenarios/:scenarioId/products/:rowId',async(req,res,next)=>{try{const value=await service.updateProduct(req.params.scenarioId,req.params.rowId,req.body||{});return value?res.json(value):fail(res,404,'product_not_found','Calculator product row not found.');}catch(error){if(error.code==='invalid_product')return fail(res,400,error.code,error.message);next(error);}});
  router.post('/scenarios/:scenarioId/manual-products',async(req,res,next)=>{try{const value=await service.addManualProduct(req.params.scenarioId,req.body||{});return value?res.status(201).json(value):fail(res,404,'scenario_not_found','Calculator scenario not found.');}catch(error){if(error.code==='invalid_manual_line')return fail(res,400,error.code,error.message);next(error);}});
  router.post('/scenarios/:scenarioId/manual-costs',async(req,res,next)=>{try{const value=await service.addManualCost(req.params.scenarioId,req.body||{});return value?res.status(201).json(value):fail(res,404,'scenario_not_found','Calculator scenario not found.');}catch(error){if(error.code==='invalid_manual_line')return fail(res,400,error.code,error.message);next(error);}});
  router.post('/scenarios/:scenarioId/exchange-rate/refresh',async(req,res,next)=>{try{const value=await service.refreshExchangeRate(req.params.scenarioId);return value?res.json(value):fail(res,404,'scenario_not_found','Calculator scenario not found.');}catch(error){if(error.code==='exchange_rate_unavailable')return fail(res,503,error.code,error.message);next(error);}});
  router.patch('/scenarios/:scenarioId/exchange-rate',async(req,res,next)=>{try{const value=await service.updateExchangeRate(req.params.scenarioId,req.body||{});return value?res.json(value):fail(res,404,'scenario_not_found','Calculator scenario not found.');}catch(error){if(error.code==='invalid_exchange_rate')return fail(res,400,error.code,error.message);next(error);}});
  router.patch('/scenarios/:scenarioId/markups',async(req,res,next)=>{try{const value=await service.updateMarkups(req.params.scenarioId,req.body||{});return value?res.json(value):fail(res,404,'scenario_not_found','Calculator scenario not found.');}catch(error){if(error.code==='invalid_markup')return fail(res,400,error.code,error.message);next(error);}});
  router.post('/scenarios/:scenarioId/revisions',async(req,res,next)=>{try{const value=await service.createRevision(req.params.scenarioId);return value?res.status(201).json(value):fail(res,404,'scenario_not_found','Calculator scenario not found.');}catch(error){next(error);}});
  router.patch('/scenarios/:scenarioId/options',async(req,res,next)=>{try{const value=await service.updateOptions(req.params.scenarioId,req.body||{});return value?res.json(value):fail(res,404,'scenario_not_found','Calculator scenario not found.');}catch(error){if(error.code==='invalid_options')return fail(res,400,error.code,error.message);next(error);}});
  router.patch('/scenarios/:scenarioId/package-items/:itemId',async(req,res,next)=>{try{const value=await service.updatePackageItem(req.params.scenarioId,req.params.itemId,req.body||{});return value?res.json(value):fail(res,404,'package_item_not_found','Package item not found.');}catch(error){if(error.code==='invalid_cost')return fail(res,400,error.code,error.message);next(error);}});
  router.post('/scenarios/:scenarioId/route-snapshots',async(req,res,next)=>{try{const value=await service.appendRouteSnapshot(req.params.scenarioId,req.body||{});return value?res.status(201).json(value):fail(res,404,'scenario_not_found','Calculator scenario not found.');}catch(error){if(error.code==='invalid_route')return fail(res,400,error.code,error.message);next(error);}});
  router.use((error,req,res,_next)=>{console.error('Project Calculator Lab request failed',{method:req.method,code:error?.code||'calculator_lab_failure'});return fail(res,500,'calculator_lab_failure','Project Calculator Lab operation failed.');});
  return router;
}
