import express from 'express';
import { createReadStream } from 'node:fs';
import { rename } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { SUPPLIER_UPLOAD_LIMITS } from '../config/supplierUploadLimits.js';
import { calculateFileSha256, generateLabManagedStorageKey, readFileIntegrity, resolveAttachmentRoot, resolveManagedPath } from '../features/supplierQuotes/managedAttachmentStorage.js';
import { validateSupplierDocumentFile } from '../features/supplierQuotes/fileTypeValidation.js';
import { createSupplierUploadMiddleware, moveTemporaryUpload, removeFileIfPresent } from '../features/supplierQuotes/supplierUploadStorage.js';
import { createSupplierImportLabService } from '../features/supplierImportLab/supplierImportLabService.js';

const allowedRoles = new Set(['original_quote', 'supporting_document', 'supplier_drawing']);
const apiError = (res, status, code, message) => res.status(status).json({ error: message, code });
const safeDownloadName = (value) => String(value || 'supplier-document').replace(/[\r\n"\\/]/g, '_').replace(/[\u0000-\u001f\u007f]/g, '_').slice(0, 255) || 'supplier-document';
function rolesForRequest(body, count) { const raw = typeof body.roles === 'string' ? body.roles : typeof body.role === 'string' ? body.role : 'original_quote'; let roles; try { roles = raw.startsWith('[') ? JSON.parse(raw) : [raw]; } catch { roles = []; } if (roles.length === 1 && count > 1) roles = Array(count).fill(roles[0]); if (roles.length !== count || roles.some((role) => !allowedRoles.has(role))) throw Object.assign(new Error('Invalid attachment role.'), { code: 'unsupported_file_type' }); return roles; }
const middlewarePromise = (middleware) => (req, res, next) => middleware(req, res, (error) => error ? next(error) : next());

export async function createSupplierImportLabRouter({ dbPromise, attachmentRoot = resolveAttachmentRoot() } = {}) {
  if (!dbPromise) throw new Error('Supplier Import Lab router requires a database promise.');
  const router = express.Router(); const upload = await createSupplierUploadMiddleware(attachmentRoot); const service = async () => createSupplierImportLabService(await dbPromise);
  router.get('/sessions', async (req, res, next) => { try { res.json(await (await service()).listSessions({ includeArchived: req.query.include_archived === 'true' })); } catch (error) { next(error); } });
  router.post('/sessions', async (req, res, next) => { try { res.status(201).json(await (await service()).createSession(req.body || {})); } catch (error) { if (error.code === 'invalid_session') return apiError(res, 400, error.code, error.message); next(error); } });
  router.get('/sessions/:sessionId', async (req, res, next) => { try { const value = await (await service()).getSession(req.params.sessionId); return value ? res.json(value) : apiError(res, 404, 'session_not_found', 'Import Lab session not found.'); } catch (error) { next(error); } });
  router.patch('/sessions/:sessionId', async (req, res, next) => { try { if (req.body?.archive === true) { const archived = await (await service()).archiveSession(req.params.sessionId); return archived ? res.json(archived) : apiError(res, 404, 'session_not_found', 'Import Lab session not found.'); } const value = await (await service()).updateSession(req.params.sessionId, req.body || {}); return value ? res.json(value) : apiError(res, 404, 'session_not_found', 'Import Lab session not found.'); } catch (error) { if (['invalid_session','invalid_session_state'].includes(error.code)) return apiError(res, 409, error.code, error.message); next(error); } });
  router.get('/sessions/:sessionId/attachments', async (req, res, next) => { try { const value = await (await service()).listAttachments(req.params.sessionId); return value ? res.json(value) : apiError(res, 404, 'session_not_found', 'Import Lab session not found.'); } catch (error) { next(error); } });
  router.get('/sessions/:sessionId/attachments/:attachmentId', async (req, res, next) => { try { const value = await (await service()).getAttachment(req.params.sessionId, req.params.attachmentId); return value ? res.json(value.metadata) : apiError(res, 404, 'attachment_not_found', 'Attachment not found.'); } catch (error) { next(error); } });
  router.post('/sessions/:sessionId/attachments', (req, res, next) => { const length = Number(req.headers['content-length'] || 0); if (length > SUPPLIER_UPLOAD_LIMITS.maxCombinedFileBytes + 1024 * 1024) return apiError(res, 413, 'request_too_large', 'Upload request is too large.'); return middlewarePromise(upload)(req, res, next); }, async (req, res) => {
    const files = Array.isArray(req.files) ? req.files : []; const temporary = files.map((file) => file.path); const finals = []; let retained = false; const cleanup = async () => Promise.allSettled([...temporary, ...finals].map(removeFileIfPresent)); req.once('aborted', () => { if (!retained) void cleanup(); });
    try { if (!files.length) return apiError(res, 400, 'empty_file', 'At least one PDF or DOCX file is required.'); if (files.reduce((sum, file) => sum + file.size, 0) > SUPPLIER_UPLOAD_LIMITS.maxCombinedFileBytes) throw Object.assign(new Error(), { code: 'request_too_large' }); const roles = rolesForRequest(req.body || {}, files.length); const records = []; for (const [index, file] of files.entries()) { const valid = await validateSupplierDocumentFile({ filename: file.path, originalFileName: file.originalname, declaredMimeType: file.mimetype, sizeBytes: file.size, maxFileNameLength: SUPPLIER_UPLOAD_LIMITS.maxOriginalFileNameLength }); if (!valid.valid) throw Object.assign(new Error(), { code: valid.code }); const id = randomUUID(); const storageKey = generateLabManagedStorageKey({ sessionId: req.params.sessionId, attachmentId: id }); const finalPath = await moveTemporaryUpload(file.path, storageKey, attachmentRoot); finals.push(finalPath); records.push({ id, sessionId: req.params.sessionId, role: roles[index], originalFileName: valid.displayName, mediaType: valid.mediaType, sizeBytes: file.size, sha256: await calculateFileSha256(finalPath), storageKey, parserEligible: valid.parserEligible, createdAt: new Date().toISOString() }); } const stored = await (await service()).insertAttachments(req.params.sessionId, records); retained = true; return res.status(201).json({ attachments: stored }); } catch (error) { await cleanup(); const status = error.code === 'session_not_found' ? 404 : ['request_too_large','LIMIT_FILE_SIZE'].includes(error.code) ? 413 : error.code === 'invalid_session_state' ? 409 : 400; return apiError(res, status, error.code || 'storage_failure', status === 404 ? 'Import Lab session not found.' : 'Upload rejected.'); }
  });
  router.get('/sessions/:sessionId/attachments/:attachmentId/download', async (req, res, next) => { try { const record = await (await service()).getAttachment(req.params.sessionId, req.params.attachmentId); if (!record) return apiError(res, 404, 'attachment_not_found', 'Attachment not found.'); const filename = resolveManagedPath(record.storageKey, attachmentRoot); let integrity; try { integrity = await readFileIntegrity(filename); } catch { return apiError(res, 404, 'attachment_not_found', 'Attachment not found.'); } if (integrity.sizeBytes !== record.metadata.sizeBytes || integrity.sha256 !== record.metadata.sha256) return apiError(res, 409, 'integrity_failure', 'Attachment integrity verification failed.'); res.setHeader('Content-Type', record.metadata.mediaType); res.setHeader('Content-Disposition', `attachment; filename="${safeDownloadName(record.metadata.originalFileName)}"`); res.setHeader('Content-Length', String(integrity.sizeBytes)); res.setHeader('X-Content-Type-Options', 'nosniff'); createReadStream(filename).on('error', next).pipe(res); } catch (error) { next(error); } });
  router.delete('/sessions/:sessionId/attachments/:attachmentId', async (req, res, next) => { let quarantine; try { const record = await (await service()).getAttachment(req.params.sessionId, req.params.attachmentId); if (!record) return apiError(res, 404, 'attachment_not_found', 'Attachment not found.'); const filename = resolveManagedPath(record.storageKey, attachmentRoot); quarantine = `${filename}.delete-${randomUUID()}`; try { await rename(filename, quarantine); } catch (error) { if (error.code !== 'ENOENT') throw error; quarantine = null; } try { await (await service()).deleteAttachmentMetadata(req.params.sessionId, req.params.attachmentId); } catch (error) { if (quarantine) await rename(quarantine, filename); throw error; } if (quarantine) await removeFileIfPresent(quarantine); res.status(204).end(); } catch (error) { if (error.code === 'invalid_session_state') return apiError(res, 409, error.code, error.message); next(error); } });
  router.delete('/sessions/:sessionId', async (req, res, next) => { const quarantined = []; let metadataDeleted = false; try { const attachments = await (await service()).listAttachments(req.params.sessionId); if (attachments === null) return apiError(res, 404, 'session_not_found', 'Import Lab session not found.'); for (const attachment of attachments) { const record = await (await service()).getAttachment(req.params.sessionId, attachment.id); const filename = resolveManagedPath(record.storageKey, attachmentRoot); const quarantine = `${filename}.delete-${randomUUID()}`; try { await rename(filename, quarantine); quarantined.push({ filename, quarantine }); } catch (error) { if (error.code !== 'ENOENT') throw error; } } await (await service()).deleteSessionMetadata(req.params.sessionId); metadataDeleted = true; await Promise.allSettled(quarantined.map((item) => removeFileIfPresent(item.quarantine))); res.status(204).end(); } catch (error) { if (!metadataDeleted) await Promise.allSettled(quarantined.map((item) => rename(item.quarantine, item.filename))); if (error.code === 'invalid_session_state') return apiError(res, 409, error.code, error.message); next(error); } });
  router.use((error, req, res, _next) => { const code = error?.code === 'LIMIT_FILE_COUNT' ? 'too_many_files' : error?.code === 'LIMIT_FILE_SIZE' ? 'file_too_large' : 'storage_failure'; console.error('Supplier Import Lab request failed', { code, method: req.method, sessionId: req.params?.sessionId || null }); return apiError(res, code === 'storage_failure' ? 500 : 413, code, code === 'storage_failure' ? 'Supplier Import Lab operation failed.' : 'Upload limit exceeded.'); });
  return router;
}
