import { apiFetch, apiUrl, extractApiErrorMessage } from "../../../services/api/apiClient";
import type { SupplierQuote, SupplierQuoteAttachment, SupplierQuoteDocumentKind, SupplierQuoteRevision } from "../../supplierQuoteImport/domain/supplierQuote.types";
import { normalizeManufacturerImportReview, type ManufacturerImportReview, type SupplierImportDiagnostics } from "../domain/manufacturerImportReview";

export type { ManufacturerImportReview, SupplierImportDiagnostics } from "../domain/manufacturerImportReview";

const base = (estimateId: string) => `/api/estimates/${encodeURIComponent(estimateId)}/supplier-quotes`;
export type SupplierImportConfirmationCounts=Pick<SupplierImportDiagnostics["counts"],"sourcePositions"|"parsedPositions"|"selectedPositions"|"validCanonicalPositions"|"reviewRequiredPositions"|"persistedPositions"|"productsSupplyRows"|"projectCostingRows"|"includedRows"|"alternativeRows"|"excludedRows">;
export type SupplierImportOperationStatus="confirmed"|"review_required"|"partial_recovery_required"|"failed_recoverable";
export type SupplierImportConfirmationResponse={scenarioId:string;status:SupplierImportOperationStatus;operationStatus:SupplierImportOperationStatus;counts:SupplierImportConfirmationCounts;completion:{status:SupplierImportOperationStatus;confirmed:boolean;failures:string[]};documents:Array<{runId:string;attachmentIds:string[];quoteId:string;revisionId:string;status:SupplierImportOperationStatus;operationId:string;operationStatus:SupplierImportOperationStatus;idempotentReplay:boolean;extractedProducts:number;extractedCosts:number;loadedProducts:number;loadedCosts:number;duplicateProducts:number;duplicateCosts:number;invalidProducts:number;invalidCosts:number;summaryUpdated:boolean;diagnostics:SupplierImportDiagnostics;warnings:string[]}>;costing:unknown;postConfirmationWarnings?:string[]};
const confirmationCountKeys:Array<keyof SupplierImportConfirmationCounts>=["sourcePositions","parsedPositions","selectedPositions","validCanonicalPositions","reviewRequiredPositions","persistedPositions","productsSupplyRows","projectCostingRows","includedRows","alternativeRows","excludedRows"];
export function parseSupplierImportConfirmationResponse(value:unknown):SupplierImportConfirmationResponse{if(!value||typeof value!=="object")throw new Error("Supplier confirmation returned no response. Original quotation retained; refresh Products / Supply before retrying.");const candidate=value as Partial<SupplierImportConfirmationResponse>;if(!candidate.counts||!Array.isArray(candidate.documents)||!candidate.operationStatus||confirmationCountKeys.some(key=>!Number.isFinite(candidate.counts?.[key])))throw new Error("Supplier confirmation response was incomplete. Original quotation retained; recovery review is required before retrying.");return candidate as SupplierImportConfirmationResponse}
function responseList<T>(value:unknown,label:string):T[]{if(value==null)return[];if(!Array.isArray(value))throw new Error(`${label} response was incomplete.`);return value as T[]}
async function listStoredDocuments(estimateId:string) { const quotes=await supplierQuotesApi.listQuotes(estimateId); return (await Promise.all(quotes.map(async quote=>(await Promise.all((await supplierQuotesApi.listRevisions(estimateId,quote.id)).map(async revision=>(await supplierQuotesApi.listAttachments(estimateId,quote.id,revision.id)).map(attachment=>({quote,revision,attachment}))))).flat()))).flat(); }
async function uploadManufacturerQuoteForAnalysis(estimateId:string,file:File){
  const body=new FormData();body.append('files',file);
  const {documents,duplicate}=await apiFetch(`${base(estimateId)}/stage-upload`,{method:'POST',body}) as {duplicate:boolean;documents:Array<{quoteId:string;revisionId:string;attachmentId:string}>};
  try{
    const attachments=await Promise.all(documents.map(document=>apiFetch(`${base(estimateId)}/${document.quoteId}/revisions/${document.revisionId}/attachments/${document.attachmentId}`) as Promise<SupplierQuoteAttachment>));
    const review=await supplierQuotesApi.prepareReview(estimateId,documents);
    return {duplicate,attachments,documents,review};
  }catch(error){throw new Error(`${error instanceof Error?error.message:'Analysis could not finish.'} The original quotation is retained. Retry with this same file to reuse it; nothing has been imported to Project Costing by this analysis attempt.`)}
}
export const supplierQuotesApi = {
  listQuotes: async (estimateId: string) => responseList<SupplierQuote>(await apiFetch(base(estimateId)),"Supplier quotations"),
  createQuote: (estimateId: string, input: { supplierCode: string; supplierName: string }) => apiFetch(base(estimateId), { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }) as Promise<SupplierQuote>,
  listRevisions: async (estimateId: string, quoteId: string) => responseList<SupplierQuoteRevision>(await apiFetch(`${base(estimateId)}/${quoteId}/revisions`),"Supplier quotation revisions"),
  createRevision: (estimateId: string, quoteId: string, input: Record<string, string>) => apiFetch(`${base(estimateId)}/${quoteId}/revisions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }) as Promise<SupplierQuoteRevision>,
  listAttachments: async (estimateId: string, quoteId: string, revisionId: string) => responseList<SupplierQuoteAttachment>(await apiFetch(`${base(estimateId)}/${quoteId}/revisions/${revisionId}/attachments`),"Supplier quotation attachments"),
  listStoredDocuments,
  uploadManufacturerQuoteForAnalysis,
  uploadAttachments: (estimateId: string, quoteId: string, revisionId: string, files: readonly File[], role = "original_quote", documentKind:SupplierQuoteDocumentKind="complete_quotation") => { const body = new FormData(); files.forEach((file) => body.append("files", file)); body.append("role", role); body.append("documentKind",documentKind); return apiFetch(`${base(estimateId)}/${quoteId}/revisions/${revisionId}/attachments`, { method: "POST", body }) as Promise<{ attachments: SupplierQuoteAttachment[] }>; },
  extractSelected: (estimateId:string,documents:Array<{quoteId:string;revisionId:string;attachmentId:string}>)=>apiFetch(`${base(estimateId)}/extract`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({documents})}) as Promise<{runs:Array<{id:string;revisionId:string;attachmentIds:string[];status:string}>}>,
  prepareReview:async(estimateId:string,documents:Array<{quoteId:string;revisionId:string;attachmentId:string}>)=>normalizeManufacturerImportReview(await apiFetch(`${base(estimateId)}/prepare-review`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({documents})})),
  prepareCanonicalDocumentForReview:async(estimateId:string,canonicalDocumentId:string)=>{const response=await apiFetch(`/api/communications/documents/${encodeURIComponent(canonicalDocumentId)}/manufacturer-import-review`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({estimateId})}) as {review:unknown};return normalizeManufacturerImportReview(response.review)},
  extractAndLoad: async (estimateId:string,scenarioId:string,documents:Array<{quoteId:string;revisionId:string;attachmentId:string}>,confirmation?:{selectedRowKeys:string[];commercialSupplierCode:string;manufacturerId?:string;metadata:{quotationNumber:string;revision:string;quotationDate?:string;currency:string;documentType?:string}})=>parseSupplierImportConfirmationResponse(await apiFetch(`${base(estimateId)}/extract-and-load`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({scenarioId,documents,...confirmation})})),
  removeAttachment: (estimateId: string, quoteId: string, revisionId: string, attachmentId: string) => apiFetch(`${base(estimateId)}/${quoteId}/revisions/${revisionId}/attachments/${attachmentId}`, { method: "DELETE" }),
  downloadAttachment: async (estimateId: string, quoteId: string, revisionId: string, attachment: SupplierQuoteAttachment) => { const path = `${base(estimateId)}/${quoteId}/revisions/${revisionId}/attachments/${attachment.id}/download`; const response = await fetch(apiUrl(path)); if (!response.ok) { const body = await response.text().catch(() => ""); throw new Error(extractApiErrorMessage(response.status, body)); } const blob = await response.blob(); const url = URL.createObjectURL(blob); try { const anchor = document.createElement("a"); anchor.href = url; anchor.download = attachment.originalFileName; anchor.click(); } finally { URL.revokeObjectURL(url); } },
};
