// Auto-generated by QuoteSync Phase 4B extraction patch.
// Moved from src/App.tsx (no UI/layout/logic changes).
import React, { useEffect } from "react";
import * as Models from "../../models/types";
import type { EstimateDefaults } from "../../models/types";
import { PRODUCT_TYPES, SUPPLIERS, WOOD_TYPES, FINISHES_BY_TYPE, allProductsForSupplier, firstProductForSupplier, isTimberProductType } from "../catalog/defaultCatalog";
import { HINGE_TYPES, UG_DOUBLE, UG_TRIPLE, HANDLE_TYPES, SUN_PROTECTION, CILL_DEPTHS, FRAME_EXTS } from "./defaultEstimateDefaults";

function H3({ children }: { children: React.ReactNode }) {
  return <h3 style={{ fontSize: 14, margin: 0, fontWeight: 800, color: "#18181b" }}>{children}</h3>;
}
function Small({ children }: { children: React.ReactNode }) {
  return <div style={{ fontSize: 12, color: "#71717a" }}>{children}</div>;
}
function Input({
  value,
  onChange,
  placeholder,
  type = "text",
  list,
  disabled,
  readOnly,
}: {
  value: string;
  onChange: (v: string) => void;
  placeholder?: string;
  type?: string;
  list?: string;
  disabled?: boolean;
  readOnly?: boolean;
}) {
  return (
    <input
      type={type}
      value={value}
      placeholder={placeholder}
      list={list}
      disabled={disabled}
      readOnly={readOnly}
      onChange={(e) => onChange(e.target.value)}
      style={{
        width: "100%",
        borderRadius: 12,
        border: "1px solid #e4e4e7",
        padding: "10px 12px",
        fontSize: 14,
        outline: "none",
      }}
    />
  );
}

const labelStyle: React.CSSProperties = { fontSize: 13, color: "#3f3f46", fontWeight: 700, marginBottom: 6 };
/* =========================
   Defaults Editor (Estimate-level + Position "Use estimate defaults")
========================= */

export default function DefaultsEditor({
  title,
  productType,
  value,
  onChange,
  showDoorOptions,
}: {
  title: string;
  productType: Models.ProductType;
  value: EstimateDefaults;
  onChange: (next: EstimateDefaults) => void;
  showDoorOptions: boolean;
}) {
  const finishes = FINISHES_BY_TYPE[productType];

  // keep G fixed at 0.53 for now (per your instruction)
  useEffect(() => {
    if (value.gValue !== "0.53") onChange({ ...value, gValue: "0.53" });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [value.ugValue, value.glassType]);

  const ugOptions = value.glassType === "Double" ? UG_DOUBLE : UG_TRIPLE;

  return (
    <div style={{ borderRadius: 14, border: "1px solid #e4e4e7", padding: 12 }}>
      <H3>{title}</H3>

      <div style={{ marginTop: 12, display: "grid", gap: 14 }}>
        {/* Supplier & Product */}
        <div style={{ borderRadius: 14, border: "1px solid #e4e4e7", padding: 12 }}>
          <H3>Supplier & Product</H3>

          <div style={{ marginTop: 10, display: "grid", gap: 12 }}>
            <div>
              <div style={labelStyle}>Supplier</div>
              <select
                value={value.supplier}
                onChange={(e) => {
                  const supplier = e.target.value;
                  const nextProd = supplier ? firstProductForSupplier(supplier) : "";
                  onChange({ ...value, supplier, product: nextProd });
                }}
                style={{ width: "100%", borderRadius: 12, border: "1px solid #e4e4e7", padding: "10px 12px", fontSize: 14 }}
              >
                <option value="">Select supplier…</option>
                {SUPPLIERS.map((s) => (
                  <option key={s.name} value={s.name}>
                    {s.name}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <div style={labelStyle}>Product type</div>
              <select
                value={value.productType}
                onChange={(e) => onChange({ ...value, productType: e.target.value as Models.ProductType })}
                style={{ width: "100%", borderRadius: 12, border: "1px solid #e4e4e7", padding: "10px 12px", fontSize: 14 }}
              >
                {PRODUCT_TYPES.map((t) => (
                  <option key={t} value={t}>
                    {t}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <div style={labelStyle}>Product</div>
              <select
                value={value.product}
                onChange={(e) => onChange({ ...value, product: e.target.value })}
                disabled={!value.supplier}
                style={{
                  width: "100%",
                  borderRadius: 12,
                  border: "1px solid #e4e4e7",
                  padding: "10px 12px",
                  fontSize: 14,
                  background: !value.supplier ? "#fafafa" : "#fff",
                  color: !value.supplier ? "#a1a1aa" : "#18181b",
                }}
              >
                <option value="">{value.supplier ? "Select product…" : "Select supplier first…"}</option>
                {allProductsForSupplier(value.supplier).map((p) => (
                  <option key={p} value={p}>
                    {p}
                  </option>
                ))}
              </select>
            </div>
          </div>
        </div>

        {/* Finishes */}
        <div style={{ borderRadius: 14, border: "1px solid #e4e4e7", padding: 12 }}>
          <H3>Finishes</H3>

          <datalist id={"ext-finish-" + title}>
            {finishes.external.map((x) => (
              <option key={x} value={x} />
            ))}
          </datalist>
          <datalist id={"int-finish-" + title}>
            {finishes.internal.map((x) => (
              <option key={x} value={x} />
            ))}
          </datalist>

          <div style={{ marginTop: 10, display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
            <div>
              <div style={labelStyle}>External finish</div>
              <Input value={value.externalFinish} onChange={(v) => onChange({ ...value, externalFinish: v })} list={"ext-finish-" + title} placeholder="Select or type…" />
            </div>
            <div>
              <div style={labelStyle}>Internal finish</div>
              <Input value={value.internalFinish} onChange={(v) => onChange({ ...value, internalFinish: v })} list={"int-finish-" + title} placeholder="Select or type…" />
            </div>
          </div>
        </div>

        {/* Hinges + Wood */}
        <div style={{ borderRadius: 14, border: "1px solid #e4e4e7", padding: 12 }}>
          <H3>Hardware</H3>

          <div style={{ marginTop: 10, display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
            <div>
              <div style={labelStyle}>Hinges</div>
              <select
                value={value.hingeType}
                onChange={(e) => onChange({ ...value, hingeType: e.target.value as any })}
                style={{ width: "100%", borderRadius: 12, border: "1px solid #e4e4e7", padding: "10px 12px", fontSize: 14 }}
              >
                {HINGE_TYPES.map((t) => (
                  <option key={t} value={t}>
                    {t}
                  </option>
                ))}
              </select>
            </div>

            {isTimberProductType(value.productType) ? (
              <div>
                <div style={labelStyle}>Wood type</div>
                <select
                  value={value.woodType}
                  onChange={(e) => onChange({ ...value, woodType: e.target.value })}
                  style={{ width: "100%", borderRadius: 12, border: "1px solid #e4e4e7", padding: "10px 12px", fontSize: 14 }}
                >
                  {WOOD_TYPES.map((w) => (
                    <option key={w} value={w}>
                      {w}
                    </option>
                  ))}
                </select>
              </div>
            ) : (
              <div />
            )}
          </div>
        </div>

        {/* Glazing */}
        <div style={{ borderRadius: 14, border: "1px solid #e4e4e7", padding: 12 }}>
          <H3>Glazing</H3>

          <div style={{ marginTop: 10, display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 12 }}>
            <div>
              <div style={labelStyle}>Glass</div>
              <select
                value={value.glassType}
                onChange={(e) => {
                  const glassType = e.target.value as "Double" | "Triple";
                  const nextUg = glassType === "Double" ? "1.1" : "0.4";
                  onChange({ ...value, glassType, ugValue: nextUg, gValue: "0.53" });
                }}
                style={{ width: "100%", borderRadius: 12, border: "1px solid #e4e4e7", padding: "10px 12px", fontSize: 14 }}
              >
                <option value="Double">Double</option>
                <option value="Triple">Triple</option>
              </select>
            </div>

            <div>
              <div style={labelStyle}>Ug value required</div>
              <select
                value={value.ugValue}
                onChange={(e) => onChange({ ...value, ugValue: e.target.value, gValue: "0.53" })}
                style={{ width: "100%", borderRadius: 12, border: "1px solid #e4e4e7", padding: "10px 12px", fontSize: 14 }}
              >
                {ugOptions.map((u) => (
                  <option key={u} value={u}>
                    {u}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <div style={labelStyle}>G value</div>
              <Input value={value.gValue} onChange={(v) => onChange({ ...value, gValue: v })} />
              <Small>Placeholder: fixed at 0.53 for now</Small>
            </div>
          </div>
        </div>

        {/* Window Handle */}
        <div style={{ borderRadius: 14, border: "1px solid #e4e4e7", padding: 12 }}>
          <H3>Window Handle</H3>

          <div style={{ marginTop: 10, display: "grid", gridTemplateColumns: "1fr 160px", gap: 12, alignItems: "center" }}>
            <div>
              <div style={labelStyle}>Handle type</div>
              <select
                value={value.windowHandleType}
                onChange={(e) => onChange({ ...value, windowHandleType: e.target.value as any })}
                style={{ width: "100%", borderRadius: 12, border: "1px solid #e4e4e7", padding: "10px 12px", fontSize: 14 }}
              >
                {HANDLE_TYPES.map((t) => (
                  <option key={t} value={t}>
                    {t}
                  </option>
                ))}
              </select>
            </div>

            <div
              style={{
                height: 96,
                borderRadius: 12,
                border: "1px solid #e4e4e7",
                background: "#fafafa",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                color: "#71717a",
                fontWeight: 800,
                fontSize: 12,
              }}
            >
              Handle image
            </div>
          </div>

          <div style={{ marginTop: 10 }}>
            <label style={{ display: "flex", gap: 8, alignItems: "center", fontSize: 14, fontWeight: 700 }}>
              <input type="checkbox" checked={value.internalCillRequired} onChange={(e) => onChange({ ...value, internalCillRequired: e.target.checked })} />
              Lockable handle
            </label>
            <Small>This was previously “door multipoint locking” — now aligned to your “lockable handle” wording.</Small>
          </div>
        </div>

        {/* Door options */}
        {showDoorOptions && (
          <div style={{ borderRadius: 14, border: "1px solid #e4e4e7", padding: 12 }}>
            <H3>Door options</H3>

            <div style={{ marginTop: 10, display: "grid", gap: 10 }}>
              <label style={{ display: "flex", gap: 8, alignItems: "center", fontSize: 14, fontWeight: 700 }}>
                <input type="checkbox" checked={value.doorMultipointLocking} onChange={(e) => onChange({ ...value, doorMultipointLocking: e.target.checked })} />
                Multipoint locking
              </label>

              <label style={{ display: "flex", gap: 8, alignItems: "center", fontSize: 14, fontWeight: 700 }}>
                <input type="checkbox" checked={value.electricalOperation} onChange={(e) => onChange({ ...value, electricalOperation: e.target.checked })} />
                Electrical operation
              </label>

              <label style={{ display: "flex", gap: 8, alignItems: "center", fontSize: 14, fontWeight: 700 }}>
                <input type="checkbox" checked={value.dayLatch} onChange={(e) => onChange({ ...value, dayLatch: e.target.checked })} />
                Day latch
              </label>
            </div>
          </div>
        )}

        {/* Accessories */}
        <div style={{ borderRadius: 14, border: "1px solid #e4e4e7", padding: 12 }}>
          <H3>Accessories</H3>

          <div style={{ marginTop: 10, display: "grid", gap: 12 }}>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
              <label style={{ display: "flex", gap: 8, alignItems: "center", fontSize: 14, fontWeight: 700 }}>
                <input type="checkbox" checked={value.internalCillRequired} onChange={(e) => onChange({ ...value, internalCillRequired: e.target.checked })} />
                Window cill internally required
              </label>

              <label style={{ display: "flex", gap: 8, alignItems: "center", fontSize: 14, fontWeight: 700 }}>
                <input type="checkbox" checked={value.externalSillRequired} onChange={(e) => onChange({ ...value, externalSillRequired: e.target.checked })} />
                Window sill externally required
              </label>
            </div>

            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
              <div>
                <div style={labelStyle}>Window cill depth</div>
                <select
                  value={String(value.cillDepthMm)}
                  onChange={(e) => onChange({ ...value, cillDepthMm: Number(e.target.value) })}
                  style={{ width: "100%", borderRadius: 12, border: "1px solid #e4e4e7", padding: "10px 12px", fontSize: 14 }}
                >
                  {CILL_DEPTHS.map((d) => (
                    <option key={d} value={d}>
                      {d} mm
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <div style={labelStyle}>Cill end cap type</div>
                <select
                  value={value.cillEndCapType}
                  onChange={(e) => onChange({ ...value, cillEndCapType: e.target.value as any })}
                  style={{ width: "100%", borderRadius: 12, border: "1px solid #e4e4e7", padding: "10px 12px", fontSize: 14 }}
                >
                  <option value="Cladding/Render End Cap">Cladding/Render End Cap</option>
                  <option value="Brick Type End Cap">Brick Type End Cap</option>
                </select>
              </div>
            </div>

            <div>
              <H3>Frame extensions</H3>
              <Small>Set each side independently.</Small>

              <div style={{ marginTop: 10, display: "grid", gridTemplateColumns: "1fr 1fr 1fr 1fr", gap: 12 }}>
                {[
                  ["Left", "frameExtLeftMm"],
                  ["Right", "frameExtRightMm"],
                  ["Top", "frameExtTopMm"],
                  ["Bottom", "frameExtBottomMm"],
                ].map(([label, key]) => (
                  <div key={key}>
                    <div style={labelStyle}>{label}</div>
                    <select
                      value={String((value as any)[key])}
                      onChange={(e) => onChange({ ...value, [key]: Number(e.target.value) } as any)}
                      style={{ width: "100%", borderRadius: 12, border: "1px solid #e4e4e7", padding: "10px 12px", fontSize: 14 }}
                    >
                      {FRAME_EXTS.map((mm) => (
                        <option key={mm} value={mm}>
                          {mm} mm
                        </option>
                      ))}
                    </select>
                  </div>
                ))}
              </div>
            </div>

            <div>
              <label style={{ display: "flex", gap: 8, alignItems: "center", fontSize: 14, fontWeight: 700 }}>
                <input type="checkbox" checked={value.sunProtectionRequired} onChange={(e) => onChange({ ...value, sunProtectionRequired: e.target.checked })} />
                Sun protection required
              </label>

              {value.sunProtectionRequired && (
                <div style={{ marginTop: 10 }}>
                  <div style={labelStyle}>Type</div>
                  <select
                    value={value.sunProtectionType}
                    onChange={(e) => onChange({ ...value, sunProtectionType: e.target.value as any })}
                    style={{ width: "100%", borderRadius: 12, border: "1px solid #e4e4e7", padding: "10px 12px", fontSize: 14 }}
                  >
                    {SUN_PROTECTION.map((t) => (
                      <option key={t} value={t}>
                        {t}
                      </option>
                    ))}
                  </select>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}


