import React, { useEffect, useState } from "react";
import { apiFetch } from "../../services/api/apiClient";
import { DEFAULT_COMMERCIAL_MARGIN_POLICY, normalizeCommercialMarginPolicy, validateGrossMarginPercentage, type CommercialMarginPolicy } from "../projectCalculatorLab/domain/commercialMargin";

const SETTING_KEY="commercial.marginPolicy";
type Setting={key:string;value:unknown;updated_at:string|null};

export default function AdminCommercialMarginPanel(){
 const[policy,setPolicy]=useState<CommercialMarginPolicy>(DEFAULT_COMMERCIAL_MARGIN_POLICY),[exists,setExists]=useState(false),[status,setStatus]=useState(""),[saving,setSaving]=useState(false);
 useEffect(()=>{let cancelled=false;void apiFetch("/api/settings/projectPreferences").then(value=>{const rows=Array.isArray(value)?value as Setting[]:[],row=rows.find(item=>item?.key===SETTING_KEY);if(!cancelled){setPolicy(normalizeCommercialMarginPolicy(row?.value));setExists(Boolean(row))}}).catch(()=>{if(!cancelled)setStatus("Company commercial-margin defaults could not be loaded.")});return()=>{cancelled=true}},[]);
 const invalid=validateGrossMarginPercentage(policy.targetGrossMarginPercent)||validateGrossMarginPercentage(policy.minimumAcceptableGrossMarginPercent)||policy.bands.some(item=>Boolean(validateGrossMarginPercentage(item.minimumPercent)));
 async function save(){if(invalid){setStatus("Enter valid percentages below 100%.");return}setSaving(true);setStatus("");try{const body=exists?{value:policy,group_name:"projectPreferences"}:{key:SETTING_KEY,value:policy,group_name:"projectPreferences"};await apiFetch(exists?`/api/settings/${SETTING_KEY}`:"/api/settings",{method:exists?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setExists(true);setStatus("Commercial margin defaults saved. Existing costing revisions are unchanged.")}catch{setStatus("Commercial margin defaults could not be saved.")}finally{setSaving(false)}}
 return <section className="admin-card admin-card--section ui-card admin-commercial-margin"><div><div className="admin-group-title">Commercial Margin Defaults</div><div className="admin-body-copy">Defaults for new Project Costings. Each costing stores its own historical policy snapshot.</div></div><div className="admin-dimensions-grid"><label><span className="admin-setting-label">Company Target Gross Margin %</span><input className="admin-input ui-input" inputMode="decimal" value={policy.targetGrossMarginPercent} onChange={event=>{const value=event.currentTarget.value;setPolicy(current=>({...current,targetGrossMarginPercent:value}))}}/></label><label><span className="admin-setting-label">Minimum Acceptable Gross Margin %</span><input className="admin-input ui-input" inputMode="decimal" value={policy.minimumAcceptableGrossMarginPercent} onChange={event=>{const value=event.currentTarget.value;setPolicy(current=>({...current,minimumAcceptableGrossMarginPercent:value}))}}/></label></div><div className="admin-commercial-margin__bands">{policy.bands.map((band,index)=><label key={band.status}><span className="admin-setting-label">{band.status.replace(/^./,value=>value.toUpperCase())} from %</span><input className="admin-input ui-input" inputMode="decimal" value={band.minimumPercent} onChange={event=>{const value=event.currentTarget.value;setPolicy(current=>({...current,bands:current.bands.map((item,itemIndex)=>itemIndex===index?{...item,minimumPercent:value}:item)}))}}/></label>)}</div><div className="admin-flex-row"><button className="ui-button ui-button--primary" disabled={saving||Boolean(invalid)} onClick={()=>void save()}>{saving?"Saving…":"Save Commercial Defaults"}</button>{status?<span role="status" className="admin-body-copy">{status}</span>:null}</div></section>;
}
