import { useEffect, useMemo, useState } from "react";
import { apiFetch } from "../../services/api/apiClient";
import AdminSectionTabs from "./AdminSectionTabs";

type LibraryDocument={id:string;ownerKind:"manufacturer"|"supplier";ownerId:string|null;ownerName:string;productSystemId:string|null;productSystemName:string;category:"certificate"|"system_drawing";subcategory:string;title:string;documentFormat:"PDF"|"DWG"|"RVT"|"IFC"|"OTHER";canonicalDocumentId:string;fileName:string|null;versionLabel:string|null;issueDate:string|null;expiryDate:string|null;jurisdiction:string|null;status:"active"|"superseded"};
type CanonicalSource={canonicalDocumentId:string;fileName:string;mimeType:string;documentType:string;provider:string;folderPath:string};
type IdentityOptions={manufacturers:Array<{id:string;name:string;code:string}>;products:Array<{id:string;manufacturerId:string;name:string;code:string;manufacturerName:string}>;suppliers:Array<{id:string;name:string}>};
type ProjectOption={id:string;name:string;clientId:string;clientReference:string;clientName:string};
type ProjectContext={project:ProjectOption;estimate:{id:string;reference:string;revision:number}|null;positions:Array<{id:string;reference:string;description:string}>;currentLink:{portalVisibility:"internal_only"|"customer_approved";applicabilityEvidence:{projectWide?:boolean;positionIds?:string[];customerSharingReviewed?:boolean;note?:string}}|null};
type LibraryForm={ownerKind:"manufacturer"|"supplier";ownerId:string;productSystemId:string;subcategory:string;title:string;documentFormat:"PDF"|"DWG"|"RVT"|"IFC"|"OTHER";canonicalDocumentId:string;versionLabel:string;issueDate:string;expiryDate:string;jurisdiction:string};
const emptyForm:LibraryForm={ownerKind:"manufacturer",ownerId:"",productSystemId:"",subcategory:"",title:"",documentFormat:"PDF",canonicalDocumentId:"",versionLabel:"",issueDate:"",expiryDate:"",jurisdiction:""};
const emptyIdentities:IdentityOptions={manufacturers:[],products:[],suppliers:[]};

export default function AdminManufacturerDocuments(){
  const [tab,setTab]=useState<"certificate"|"system_drawing">("certificate"),[rows,setRows]=useState<LibraryDocument[]>([]),[sources,setSources]=useState<CanonicalSource[]>([]),[identities,setIdentities]=useState<IdentityOptions>(emptyIdentities),[projects,setProjects]=useState<ProjectOption[]>([]),[form,setForm]=useState<LibraryForm>(emptyForm),[showForm,setShowForm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[selectedDocument,setSelectedDocument]=useState<LibraryDocument|null>(null),[projectId,setProjectId]=useState(""),[projectContext,setProjectContext]=useState<ProjectContext|null>(null),[projectBusy,setProjectBusy]=useState(false),[projectWide,setProjectWide]=useState(false),[positionIds,setPositionIds]=useState<string[]>([]),[visibility,setVisibility]=useState<"internal_only"|"customer_approved">("internal_only"),[sharingReviewed,setSharingReviewed]=useState(false),[applicabilityNote,setApplicabilityNote]=useState("");
  const updateForm=<K extends keyof LibraryForm>(field:K,value:LibraryForm[K])=>setForm((current)=>({...current,[field]:value}));
  async function load(){setError("");try{const [library,canonical,identityOptions,projectOptions]=await Promise.all([apiFetch("/api/admin/manufacturer-documents"),apiFetch("/api/admin/manufacturer-documents/canonical-sources"),apiFetch("/api/admin/manufacturer-documents/identity-options"),apiFetch("/api/admin/manufacturer-documents/project-options")]);setRows(Array.isArray(library)?library as LibraryDocument[]:[]);setSources(Array.isArray(canonical)?canonical as CanonicalSource[]:[]);setIdentities(identityOptions as IdentityOptions);setProjects(Array.isArray(projectOptions)?projectOptions as ProjectOption[]:[]);}catch(reason){setError(reason instanceof Error?reason.message:"Manufacturer documents could not be loaded.")}}
  useEffect(()=>{void load()},[]);
  const filtered=useMemo(()=>rows.filter((row)=>row.category===tab),[rows,tab]);
  const owners=form.ownerKind==="manufacturer"?identities.manufacturers:identities.suppliers;
  const products=useMemo(()=>form.ownerKind==="manufacturer"&&form.ownerId?identities.products.filter((product)=>product.manufacturerId===form.ownerId):identities.products,[form.ownerKind,form.ownerId,identities.products]);
  async function save(){setBusy(true);setError("");setNotice("");try{const saved=await apiFetch("/api/admin/manufacturer-documents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,category:tab,applicability:{reviewStatus:"metadata_registered"},sourceProvenance:{entryMethod:"administration"}})}) as LibraryDocument;setForm(emptyForm);setShowForm(false);setSelectedDocument(saved);setNotice(`${saved.fileName||saved.title} was registered under ${saved.ownerName} → ${saved.productSystemName}. Next: review where it applies.`);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Document metadata could not be saved. Your selections have been kept.")}finally{setBusy(false)}}
  function beginProjectReview(document:LibraryDocument){setSelectedDocument(document);setProjectId("");setProjectContext(null);setProjectWide(false);setPositionIds([]);setVisibility("internal_only");setSharingReviewed(false);setApplicabilityNote("");setError("");setNotice("")}
  async function chooseProject(nextProjectId:string){setProjectId(nextProjectId);setProjectContext(null);setError("");if(!selectedDocument||!nextProjectId)return;setProjectBusy(true);try{const context=await apiFetch(`/api/admin/manufacturer-documents/${selectedDocument.id}/projects/${nextProjectId}`) as ProjectContext;setProjectContext(context);const evidence=context.currentLink?.applicabilityEvidence;setProjectWide(Boolean(evidence?.projectWide));setPositionIds(Array.isArray(evidence?.positionIds)?evidence.positionIds:[]);setVisibility(context.currentLink?.portalVisibility||"internal_only");setSharingReviewed(Boolean(evidence?.customerSharingReviewed));setApplicabilityNote(evidence?.note||"");}catch(reason){setError(reason instanceof Error?reason.message:"Project applicability could not be loaded.")}finally{setProjectBusy(false)}}
  async function saveProjectUse(){if(!selectedDocument||!projectContext)return;setProjectBusy(true);setError("");setNotice("");try{const result=await apiFetch(`/api/admin/manufacturer-documents/${selectedDocument.id}/projects/${projectContext.project.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({portalVisibility:visibility,applicabilityEvidence:{projectWide,positionIds,customerSharingReviewed:sharingReviewed,note:applicabilityNote}})}) as {fileName:string;projectName:string;clientName:string;portalVisibility:string};setNotice(`${result.fileName||selectedDocument.title} is linked to ${result.clientName} → ${result.projectName} for the reviewed ${projectWide?"whole Project":`${positionIds.length} Position${positionIds.length===1?"":"s"}`}. ${result.portalVisibility==="customer_approved"?"It is approved for the customer Portal.":"It remains internal only."} Next: open the Project or review another document.`);await chooseProject(projectContext.project.id);}catch(reason){setError(reason instanceof Error?reason.message:"Project use could not be saved. Your review has been kept and is safe to retry.")}finally{setProjectBusy(false)}}
  return <div className="admin-page-stack admin-manufacturer-documents">
    <header className="admin-card admin-card--content ui-card"><div><span className="ui-eyebrow">Administration → Technical Documents</span><div className="admin-page-title">Manufacturer / System Documents</div><p className="admin-body-copy admin-copy-width">Register one retained source, then review the exact Projects and Positions where it applies. Nothing is shared with a customer automatically.</p></div><button type="button" className="ui-button ui-button--primary" onClick={()=>setShowForm((value)=>!value)}>{showForm?"Cancel":"Register document"}</button></header>
    {notice?<div className="ui-status ui-status--success" role="status">{notice}</div>:null}{error?<div className="ui-status ui-status--error" role="alert">{error}</div>:null}
    <AdminSectionTabs tabs={[{id:"certificate",label:"Certificates"},{id:"system_drawing",label:"System Drawings"}]} activeTab={tab} onChange={setTab} label="Manufacturer document categories"/>
    {showForm?<section className="admin-card admin-card--section ui-card admin-manufacturer-documents__form"><h3>Register canonical {tab==="certificate"?"certificate":"system drawing"}</h3><p>Choose existing Administration identities and one active provider-backed source file. QuoteSuite stores the relationship, not another binary copy.</p><div className="admin-manufacturer-documents__fields">
      <label>Owned by<select className="ui-input" value={form.ownerKind} onChange={(event)=>setForm((current)=>({...current,ownerKind:event.currentTarget.value as LibraryForm["ownerKind"],ownerId:"",productSystemId:""}))}><option value="manufacturer">Manufacturer</option><option value="supplier">Supplier</option></select></label>
      <label>{form.ownerKind==="manufacturer"?"Manufacturer":"Supplier"}<select className="ui-input" data-testid="manufacturer-document-owner" value={form.ownerId} onChange={(event)=>setForm({...form,ownerId:event.currentTarget.value,productSystemId:form.ownerKind==="manufacturer"?"":form.productSystemId})}><option value="">Choose current {form.ownerKind}</option>{owners.map((owner)=><option key={owner.id} value={owner.id}>{owner.name}{"code" in owner&&owner.code?` · ${owner.code}`:""}</option>)}</select></label>
      <label>Product / system<select className="ui-input" value={form.productSystemId} onChange={(event)=>updateForm("productSystemId",event.currentTarget.value)}><option value="">Choose current product / system</option>{products.map((product)=><option key={product.id} value={product.id}>{form.ownerKind==="supplier"?`${product.manufacturerName} · `:""}{product.name}{product.code?` · ${product.code}`:""}</option>)}</select></label>
      <label>Subcategory<input className="ui-input" value={form.subcategory} onChange={(event)=>updateForm("subcategory",event.currentTarget.value)} placeholder={tab==="certificate"?"Thermal / Security / Acoustic":"Head / Jamb / Threshold / Interface"}/></label><label>Document title<input className="ui-input" value={form.title} onChange={(event)=>updateForm("title",event.currentTarget.value)}/></label><label>Canonical source file<select className="ui-input" value={form.canonicalDocumentId} onChange={(event)=>updateForm("canonicalDocumentId",event.currentTarget.value)}><option value="">Select a canonical file</option>{sources.map((source)=><option key={source.canonicalDocumentId} value={source.canonicalDocumentId}>{source.fileName} · {source.folderPath||source.provider}</option>)}</select></label><label>File format<select className="ui-input" value={form.documentFormat} onChange={(event)=>updateForm("documentFormat",event.currentTarget.value as LibraryForm["documentFormat"])}>{["PDF","DWG","RVT","IFC","OTHER"].map((format)=><option key={format}>{format}</option>)}</select></label><label>Issue / version<input className="ui-input" value={form.versionLabel} onChange={(event)=>updateForm("versionLabel",event.currentTarget.value)}/></label><label>Issue date<input className="ui-input" type="date" value={form.issueDate} onChange={(event)=>updateForm("issueDate",event.currentTarget.value)}/></label><label>Expiry date<input className="ui-input" type="date" value={form.expiryDate} onChange={(event)=>updateForm("expiryDate",event.currentTarget.value)}/></label><label>Jurisdiction / applicability<input className="ui-input" value={form.jurisdiction} onChange={(event)=>updateForm("jurisdiction",event.currentTarget.value)} placeholder="Scotland / England / Wales / UK"/></label>
    </div><div className="ui-action-row"><button type="button" className="ui-button ui-button--primary" disabled={busy||!form.ownerId||!form.productSystemId||!form.subcategory||!form.title||!form.canonicalDocumentId} onClick={()=>void save()}>{busy?"Registering document…":"Register canonical document"}</button></div></section>:null}
    <section className="admin-card admin-card--section ui-card"><header className="admin-manufacturer-documents__section-header"><div><h3>{tab==="certificate"?"Certificates":"System Drawings"}</h3><p>{tab==="certificate"?"Thermal, security, acoustic, fire, declarations and other reviewed compliance evidence.":"PDF, DWG, RVT and IFC source drawings with manufacturer-specific categories."}</p></div><span className="ui-status ui-status--muted">{filtered.length} record{filtered.length===1?"":"s"}</span></header>{filtered.length?<div className="admin-manufacturer-documents__table-wrap"><table><thead><tr><th>Manufacturer / Supplier</th><th>Product / System</th><th>Category</th><th>Document</th><th>Issue / applicability</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map((row)=><tr key={row.id}><td><strong>{row.ownerName}</strong><small>{row.ownerKind}{row.ownerId?" · canonical":" · legacy identity"}</small></td><td>{row.productSystemName}</td><td>{row.subcategory}</td><td><strong>{row.title}</strong><small>{row.fileName||"Canonical file retained"} · {row.documentFormat}</small></td><td>{row.versionLabel||"—"}<small>{row.issueDate||"Date not supplied"}{row.expiryDate?` · Expires ${row.expiryDate}`:""}{row.jurisdiction?` · ${row.jurisdiction}`:""}</small></td><td><span className={`ui-status ui-status--${row.status==="active"?"success":"muted"}`}>{row.status}</span></td><td><button type="button" className="ui-button" disabled={row.status!=="active"} onClick={()=>beginProjectReview(row)}>Review Project use</button></td></tr>)}</tbody></table></div>:<div className="ui-empty-state">No {tab==="certificate"?"certificates":"system drawings"} registered yet.</div>}</section>
    {selectedDocument?<section className="admin-card admin-card--section ui-card"><header className="admin-manufacturer-documents__section-header"><div><span className="ui-eyebrow">Project applicability review</span><h3>{selectedDocument.title}</h3><p>{selectedDocument.fileName} · {selectedDocument.ownerName} → {selectedDocument.productSystemName}</p></div><button type="button" className="ui-button" onClick={()=>setSelectedDocument(null)}>Close</button></header><label>Client / Project<select className="ui-input" value={projectId} onChange={(event)=>void chooseProject(event.currentTarget.value)}><option value="">Choose a Project</option>{projects.map((project)=><option key={project.id} value={project.id}>{project.clientReference} · {project.clientName} → {project.name}</option>)}</select></label>{projectBusy&&!projectContext?<p className="ui-status">Loading Project Positions…</p>:null}{projectContext?<><p>{projectContext.estimate?`${projectContext.estimate.reference} · revision ${projectContext.estimate.revision}`:"No active Estimate Positions are available. Choose whole Project only when that is genuinely correct."}</p><label><input type="checkbox" checked={projectWide} onChange={(event)=>setProjectWide(event.currentTarget.checked)}/> Applies to the whole Project</label>{projectContext.positions.length?<fieldset><legend>Applicable Positions</legend>{projectContext.positions.map((position)=><label key={position.id}><input type="checkbox" checked={positionIds.includes(position.id)} disabled={projectWide} onChange={(event)=>{const checked=event.currentTarget.checked;setPositionIds((current)=>checked?[...current,position.id]:current.filter((id)=>id!==position.id))}}/>{position.reference} · {position.description}</label>)}</fieldset>:null}<label>Customer visibility<select className="ui-input" value={visibility} onChange={(event)=>{const next=event.currentTarget.value as typeof visibility;setVisibility(next);if(next==="internal_only")setSharingReviewed(false)}}><option value="internal_only">Internal only</option><option value="customer_approved">Approved for this customer's Portal</option></select></label>{visibility==="customer_approved"?<label><input type="checkbox" checked={sharingReviewed} onChange={(event)=>setSharingReviewed(event.currentTarget.checked)}/> I reviewed this exact document and its applicability for this customer.</label>:null}<label>Review note (optional)<textarea className="ui-textarea" rows={3} value={applicabilityNote} onChange={(event)=>setApplicabilityNote(event.currentTarget.value)}/></label><button type="button" className="ui-button ui-button--primary" disabled={projectBusy||(!projectWide&&!positionIds.length)||(visibility==="customer_approved"&&!sharingReviewed)} onClick={()=>void saveProjectUse()}>{projectBusy?"Saving Project use…":"Save Project use"}</button></>:null}</section>:null}
  </div>;
}
