import { useCallback, useEffect, useState } from "react";
import { clearIntegrationKey, getIntegrationStatuses, saveIntegration, testIntegration, type IntegrationProvider, type IntegrationStatus } from "../../services/integrations/integrationService";
import { googleWorkspaceIntegrationService } from "../../services/integrations/googleWorkspaceIntegrationService";
import type { GoogleWorkspaceStatus } from "../../services/communications/communicationsApi";
import { COMMUNICATION_PROVIDER_CONTRACTS } from "../communications/domain/communications";
import { ESTIMATE_TO_ORDER_DOCUMENT_STRATEGY, PROJECT_FOLDER_PROVISIONING_TRIGGER } from "../documents/domain/projectDocumentArchitecture";

const PROVIDERS: Array<{ id: IntegrationProvider; title: string; description: string }> = [
  { id: "googleMaps", title: "Google Maps", description: "Server credential for geocoding, routes, distance, and travel time. Browser map display uses its separately deployed website-restricted key." },
  { id: "what3words", title: "what3words", description: "Resolve three-word addresses and coordinates for project locations." },
];
const DEFAULT_TEMPLATE:Record<string,string>={drawingsClient:"Drawings (Client)",drawingsEcofenster:"Drawings (Ecofenster)",supplierEstimates:"Estimates",invoices:"Invoices",orders:"Orders"};
const TEMPLATE_LABELS:Record<string,string>={drawingsClient:"Customer drawings",drawingsEcofenster:"Ecofenster drawings",supplierEstimates:"Supplier estimates",invoices:"Invoices",orders:"Project orders"};

function sourceLabel(status?: IntegrationStatus) { if (!status?.configured) return "Not configured"; return status.source === "quotesync" ? "QuoteSuite managed" : "Environment fallback"; }
function googleStateLabel(status:GoogleWorkspaceStatus|null,loadFailed=false) {
  if (!status) return loadFailed?"Unavailable":"Loading";
  if (status.state==="connected") return `Connected${status.account?.email?` · ${status.account.email}`:""}`;
  if (status.state==="configured_encryption_unavailable") return "Configured · encryption unavailable";
  if (status.state==="reconnect_required") return "Reconnect required";
  if (status.state==="configured_disconnected") return "Configured · disconnected";
  return "Not configured";
}

export default function AdminIntegrationsPanel() {
  const [statuses,setStatuses]=useState<IntegrationStatus[]>([]),[keys,setKeys]=useState<Record<IntegrationProvider,string>>({googleMaps:"",what3words:""}),[busy,setBusy]=useState<IntegrationProvider|null>(null),[message,setMessage]=useState<Record<string,string>>({});
  const [google,setGoogle]=useState<GoogleWorkspaceStatus|null>(null),[googleBusy,setGoogleBusy]=useState(false),[googleMessage,setGoogleMessage]=useState(""),[googleLoadFailed,setGoogleLoadFailed]=useState(false);
  const [googleForm,setGoogleForm]=useState({clientId:"",clientSecret:"",redirectUri:"http://localhost:3001/api/integrations/googleWorkspace/oauth/callback",estimatesRootFolderId:"",ordersRootFolderId:"",folderTemplate:{...DEFAULT_TEMPLATE}});
  const applyGoogle=useCallback((status:GoogleWorkspaceStatus)=>{const configuredTemplate=Object.fromEntries(Object.entries(status.folderTemplate).filter(([key])=>key in DEFAULT_TEMPLATE));setGoogle(status);setGoogleForm(current=>({...current,clientId:status.clientId||"",redirectUri:status.redirectUri||current.redirectUri,estimatesRootFolderId:status.estimatesRootFolderId||"",ordersRootFolderId:status.ordersRootFolderId||"",folderTemplate:{...DEFAULT_TEMPLATE,...configuredTemplate}}))},[]);
  const refresh=useCallback(async()=>{const [regular,workspace]=await Promise.allSettled([getIntegrationStatuses(),googleWorkspaceIntegrationService.status()]);if(regular.status==="fulfilled")setStatuses(regular.value);else setMessage(current=>({...current,general:"Integration status could not be loaded."}));if(workspace.status==="fulfilled"){applyGoogle(workspace.value);setGoogleLoadFailed(false)}else{setGoogleLoadFailed(true);setGoogleMessage(workspace.reason instanceof Error?workspace.reason.message:"Google Workspace status could not be loaded.")}},[applyGoogle]);
  useEffect(()=>{void refresh()},[refresh]);
  useEffect(()=>{const receive=(event:MessageEvent)=>{if(event.data?.type==="quotesuite:google-workspace-connected"){void googleWorkspaceIntegrationService.status().then(status=>{applyGoogle(status);setGoogleLoadFailed(false)}).catch(error=>{setGoogleLoadFailed(true);setGoogleMessage(error instanceof Error?error.message:"Google Workspace status could not be loaded.")});setGoogleMessage("Google Workspace connected.")}};window.addEventListener("message",receive);return()=>window.removeEventListener("message",receive)},[applyGoogle]);
  const run=async(provider:IntegrationProvider,action:()=>Promise<IntegrationStatus|void>)=>{setBusy(provider);setMessage(current=>({...current,[provider]:""}));try{const next=await action();if(next)setStatuses(current=>current.map(item=>item.provider===provider?next:item))}catch(error){setMessage(current=>({...current,[provider]:error instanceof Error?error.message:"Integration request failed."}))}finally{setBusy(null)}};
  const runGoogle=async(action:()=>Promise<void>)=>{setGoogleBusy(true);setGoogleMessage("");try{await action()}catch(error){setGoogleMessage(error instanceof Error?error.message:"Google Workspace request failed.")}finally{setGoogleBusy(false)}};
  const setGoogleField=(field:"clientId"|"clientSecret"|"redirectUri"|"estimatesRootFolderId"|"ordersRootFolderId",value:string)=>setGoogleForm(current=>({...current,[field]:value}));
  const setGoogleTemplateField=(field:string,value:string)=>setGoogleForm(current=>({...current,folderTemplate:{...current.folderTemplate,[field]:value}}));
  const saveGoogleConfiguration=async()=>{const input:{clientId?:string;clientSecret?:string;redirectUri:string;estimatesRootFolderId:string|null;ordersRootFolderId:string|null;folderTemplate:Record<string,string>}={redirectUri:googleForm.redirectUri.trim(),estimatesRootFolderId:googleForm.estimatesRootFolderId.trim()||null,ordersRootFolderId:googleForm.ordersRootFolderId.trim()||null,folderTemplate:googleForm.folderTemplate};if(googleForm.clientId.trim())input.clientId=googleForm.clientId.trim();if(googleForm.clientSecret.trim())input.clientSecret=googleForm.clientSecret.trim();applyGoogle(await googleWorkspaceIntegrationService.configure(input as Parameters<typeof googleWorkspaceIntegrationService.configure>[0]));setGoogleForm(current=>({...current,clientSecret:""}));setGoogleMessage("Google Workspace configuration saved.")};

  return <div className="admin-integrations">
    <div className="admin-card admin-card--content ui-card"><div className="admin-section-title">Integrations</div><p>Company-managed credentials and encrypted OAuth tokens are stored by the QuoteSuite server. Secrets and tokens are never returned to this screen.</p>{message.general?<div className="ui-status ui-status--error">{message.general}</div>:null}</div>
    <form className="admin-card admin-card--content ui-card admin-integration-card" onSubmit={event=>{event.preventDefault();void runGoogle(saveGoogleConfiguration)}}>
      <div className="admin-integration-card__header"><div><h3>Google Workspace</h3><p>One OAuth connection powers the provider-neutral Email workspace and Google Drive project documents.</p></div><span className={`ui-status ${google?.connected?"ui-status--success":googleLoadFailed||google?.state==="configured_encryption_unavailable"||google?.state==="reconnect_required"?"ui-status--warning":"ui-status--muted"}`}>{googleStateLabel(google,googleLoadFailed)}</span></div>
      {google?.infrastructureMessage?<div className="ui-status ui-status--warning" role="alert">{google.infrastructureMessage} Saved provider settings and connection records have been retained; a server administrator must restore the encryption service.</div>:null}
      <div className="admin-integration-card__capabilities">
        <span className={`ui-status ${google?.capabilities.gmail.available?"ui-status--success":"ui-status--muted"}`}>Gmail · {google?.capabilities.gmail.available?"Available":google?.state==="configured_encryption_unavailable"?"Encryption unavailable":google?.connected?"Scope required":"Disconnected"}</span>
        <span className={`ui-status ${google?.capabilities.drive.available?"ui-status--success":"ui-status--muted"}`}>Drive · {google?.capabilities.drive.available?(google.capabilities.drive.rootConfigured?"Available · Estimates root configured":"Available · root required"):google?.state==="configured_encryption_unavailable"?"Encryption unavailable":google?.connected?"Scope required":"Disconnected"}</span>
      </div>
      <div className="admin-integrations__grid">
        <label className="ui-field"><span>OAuth client ID</span><input className="ui-input" value={googleForm.clientId} placeholder={google?.clientIdHint||"Google OAuth web client ID"} onChange={event=>{const value=event.currentTarget.value;setGoogleField("clientId",value)}}/></label>
        <label className="ui-field"><span>OAuth client secret</span><input className="ui-input" type="password" autoComplete="new-password" value={googleForm.clientSecret} placeholder={google?.configured?"Stored securely •••••••• · leave blank to retain":"Google OAuth client secret"} onChange={event=>{const value=event.currentTarget.value;setGoogleField("clientSecret",value)}}/></label>
        <label className="ui-field"><span>Authorised redirect URI</span><input className="ui-input" value={googleForm.redirectUri} onChange={event=>{const value=event.currentTarget.value;setGoogleField("redirectUri",value)}}/></label>
        <label className="ui-field"><span>Estimates root folder ID</span><input className="ui-input" value={googleForm.estimatesRootFolderId} placeholder="Required for provisioning" onChange={event=>{const value=event.currentTarget.value;setGoogleField("estimatesRootFolderId",value)}}/></label>
        <label className="ui-field"><span>Orders root folder ID</span><input className="ui-input" value={googleForm.ordersRootFolderId} placeholder="Reserved for Estimate → Order" onChange={event=>{const value=event.currentTarget.value;setGoogleField("ordersRootFolderId",value)}}/></label>
      </div>
      <div className="admin-integration-card__capabilities">{["Inbox / Sent / Drafts","Search / compose / reply / forward","Email attachments","Drive API project folders","Dynamic supplier folders","Canonical Drive IDs"].map(item=><span className="ui-chip" key={item}>{item}</span>)}</div>
      <details><summary>Project folder template</summary><div className="admin-integrations__grid">{Object.entries(googleForm.folderTemplate).map(([key,value])=><label className="ui-field" key={key}><span>{TEMPLATE_LABELS[key]||key}</span><input className="ui-input" value={value} onChange={event=>{const nextValue=event.currentTarget.value;setGoogleTemplateField(key,nextValue)}}/></label>)}</div></details>
      {googleMessage?<div className="ui-status ui-status--warning" role="status">{googleMessage}</div>:null}
      <div className="ui-action-row">
        <button type="submit" className="ui-button ui-button--primary" disabled={googleBusy||!google?.encryptionConfigured||!googleForm.redirectUri.trim()}>Save configuration</button>
        <button type="button" className="ui-button" disabled={googleBusy||!google?.configured||!google.encryptionConfigured} onClick={()=>void runGoogle(async()=>{const oauth=await googleWorkspaceIntegrationService.beginOAuth();window.open(oauth.authorizationUrl,"quotesuite-google-oauth","popup=yes,width=640,height=760");setGoogleMessage("Complete consent in the Google window.")})}>{google?.connected?"Reconnect Google Workspace":"Connect Google Workspace"}</button>
        <button type="button" className="ui-button ui-button--danger" disabled={googleBusy||!google?.connected} onClick={()=>void runGoogle(async()=>{applyGoogle(await googleWorkspaceIntegrationService.disconnect());setGoogleMessage("Google Workspace disconnected; saved OAuth configuration was retained.")})}>Disconnect</button>
      </div>
      <small>Requested delegated scopes: {google?.scopes.join(" · ")}. Provisioning trigger: {PROJECT_FOLDER_PROVISIONING_TRIGGER.replaceAll("_"," ")} · future Order document strategy: {ESTIMATE_TO_ORDER_DOCUMENT_STRATEGY.mode.replaceAll("_"," ")}.</small>
    </form>
    <div className="admin-integrations__grid">{PROVIDERS.map(provider=>{const status=statuses.find(item=>item.provider===provider.id),disabled=busy===provider.id;return <form className="admin-card admin-card--content ui-card admin-integration-card" key={provider.id} onSubmit={event=>{event.preventDefault();void run(provider.id,async()=>{const next=await saveIntegration(provider.id,{enabled:status?.enabled??true,apiKey:keys[provider.id]});setKeys(current=>({...current,[provider.id]:""}));return next})}}><div className="admin-integration-card__header"><div><h3>{provider.title}</h3><p>{provider.description}</p></div><span className={`ui-status ${status?.configured?"ui-status--success":"ui-status--muted"}`}>{sourceLabel(status)}</span></div><label className="admin-integration-card__toggle"><input type="checkbox" checked={status?.enabled??true} disabled={!status||disabled} onChange={event=>{const enabled=event.currentTarget.checked;void run(provider.id,()=>saveIntegration(provider.id,{enabled}))}}/> Enabled</label>{status?.capabilities?.length?<div className="admin-integration-card__capabilities">{status.capabilities.map(capability=><span className="ui-chip" key={capability}>{capability.replaceAll("_"," ")}</span>)}</div>:null}<label className="ui-field"><span>{provider.id==="googleMaps"?"Server API Key":"API Key"}</span><input className="ui-input" type="password" autoComplete="new-password" placeholder={status?.maskedKey||"Enter API key"} value={keys[provider.id]} onChange={event=>{const value=event.currentTarget.value;setKeys(current=>({...current,[provider.id]:value}))}}/></label>{message[provider.id]?<div className="ui-status ui-status--warning">{message[provider.id]}</div>:null}<div className="ui-action-row"><button type="submit" className="ui-button ui-button--primary" disabled={disabled||!keys[provider.id].trim()}>Save / Update</button><button type="button" className="ui-button" disabled={disabled||!status?.configured||!status.enabled} onClick={()=>void run(provider.id,async()=>{const result=await testIntegration(provider.id);setMessage(current=>({...current,[provider.id]:result.message}));await refresh()})}>Test Connection</button><button type="button" className="ui-button ui-button--danger" disabled={disabled||status?.source!=="quotesync"} onClick={()=>void run(provider.id,()=>clearIntegrationKey(provider.id))}>Remove key</button></div></form>})}</div>
    <div className="admin-card admin-card--content ui-card"><div className="admin-section-title">Additional communication providers</div><p>The domain remains provider-neutral. Microsoft 365 stays a planned provider; no Gmail-specific records leak into Client, Estimate, Order, supplier quotation or project links.</p></div>
    <div className="admin-integrations__grid">{COMMUNICATION_PROVIDER_CONTRACTS.filter(provider=>provider.id!=="google_workspace").map(provider=><section className="admin-card admin-card--content ui-card admin-integration-card" key={provider.id}><div className="admin-integration-card__header"><div><h3>{provider.label}</h3></div><span className="ui-status ui-status--muted">Planned · OAuth required</span></div><div className="admin-integration-card__capabilities">{provider.capabilities.map(capability=><span className="ui-chip" key={capability}>{capability}</span>)}</div></section>)}</div>
  </div>;
}
