import { useEffect, useMemo, useState } from "react";
import {
  BUILT_IN_THEME_ID,
  DEFAULT_QUOTESYNC_THEME_CONFIGURATION,
  QUOTESYNC_FONT_OPTIONS,
  QUOTESYNC_THEMES,
  getSelectedTheme,
  listThemes,
  loadCompanyThemeStore,
  normaliseThemeConfiguration,
  saveCompanyThemeStore,
  type QuoteSyncNamedTheme,
  type QuoteSyncThemeConfiguration,
  type QuoteSyncThemeStore,
} from "../../theme/themes";

type Tab = "themes" | "colours" | "typography" | "appearance" | "identity" | "preview";
type ColourGroup = "semantic" | "operational";
const tabs: Array<[Tab, string]> = [["themes","Themes"],["colours","Colours"],["typography","Typography"],["appearance","Components / Appearance"],["identity","Identity & Logos"],["preview","Preview"]];
const paletteFields = [["background","Page Background"],["surface","Surface"],["elevatedSurface","Elevated Surface"],["card","Card"],["control","Control"],["border","Border"],["primaryText","Primary Text"],["secondaryText","Secondary Text"]] as const;
const semanticFields = [["success","Success"],["warning","Warning"],["error","Error / Attention"],["information","Information"],["sellingPrice","Selling Price / Commercial Positive"]] as const;
const operationalFields = [["quotes","Quotes / Follow-up"],["installations","Installation"],["ordersAttention","Orders Needing Attention"],["invoices","Invoice / Finance"],["pipelineNewLeads","Pipeline Leads"],["pipelineQuoted","Pipeline Quoted"],["pipelineNegotiation","Pipeline Negotiation"],["pipelineWon","Pipeline Won"]] as const;

function ColourControl({ label, value, disabled, onChange, onReset }: { label:string; value:string; disabled?:boolean; onChange:(value:string)=>void; onReset:()=>void }) {
  const valid = /^#[0-9a-f]{6}$/i.test(value);
  return <label className="admin-theme-colour"><span>{label}</span><span className="admin-theme-colour__control"><input type="color" value={valid?value:"#000000"} disabled={disabled} onChange={(event)=>onChange(event.target.value)} aria-label={`${label} colour`}/><input className={valid?"ui-input":"ui-input is-invalid"} value={value} disabled={disabled} onChange={(event)=>onChange(event.target.value)} aria-label={`${label} hex value`}/><button type="button" className="ui-button admin-theme-reset-colour" disabled={disabled} onClick={onReset}>Reset</button></span></label>;
}

function makeId(name:string) { return `${name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"custom-theme"}-${Date.now()}`; }

export default function AdminThemeColoursPanel() {
  const [tab,setTab]=useState<Tab>("themes");
  const [store,setStore]=useState<QuoteSyncThemeStore>({schemaVersion:2,activeThemeId:BUILT_IN_THEME_ID,themes:[]});
  const [selectedId,setSelectedId]=useState(BUILT_IN_THEME_ID);
  const [draft,setDraft]=useState<QuoteSyncThemeConfiguration>(()=>structuredClone(DEFAULT_QUOTESYNC_THEME_CONFIGURATION));
  const [status,setStatus]=useState("Loading company themes…");
  const [saving,setSaving]=useState(false);
  const themes=useMemo(()=>listThemes(store),[store]);
  const selected=themes.find((theme)=>theme.id===selectedId)??themes[0];
  const locked=selected.builtIn;

  useEffect(()=>{let current=true;void loadCompanyThemeStore().then((loaded)=>{if(!current)return;setStore(loaded);setSelectedId(loaded.activeThemeId);setDraft(getSelectedTheme(loaded).configuration);setStatus("Company themes loaded.");});return()=>{current=false};},[]);
  const choose=(theme:QuoteSyncNamedTheme)=>{setSelectedId(theme.id);setDraft(structuredClone(theme.configuration));};
  const duplicate=(theme=selected)=>{const name=`${theme.name} Copy`;const copy={id:makeId(name),name,builtIn:false,baseThemeId:theme.id,configuration:structuredClone(theme.configuration)};setStore((current)=>({...current,themes:[...current.themes,copy]}));setSelectedId(copy.id);setDraft(copy.configuration);setStatus("Theme duplicated. Save to persist it.");};
  const create=()=>{const name="New QuoteSuite Theme";const copy={id:makeId(name),name,builtIn:false,baseThemeId:BUILT_IN_THEME_ID,configuration:structuredClone(DEFAULT_QUOTESYNC_THEME_CONFIGURATION)};setStore((current)=>({...current,themes:[...current.themes,copy]}));setSelectedId(copy.id);setDraft(copy.configuration);};
  const save=async(activate=false)=>{if(locked){setStatus("Ecofenster Default is locked. Duplicate it to create an editable theme.");return;}setSaving(true);try{const next={...store,activeThemeId:activate?selectedId:store.activeThemeId,themes:store.themes.map((theme)=>theme.id===selectedId?{...theme,configuration:normaliseThemeConfiguration(draft)}:theme)};const saved=await saveCompanyThemeStore(next);setStore(saved);setStatus(activate?"Theme saved and activated.":"Theme saved.");}catch(error){setStatus(error instanceof Error?error.message:"Theme could not be saved.");}finally{setSaving(false)}};
  const rename=()=>{if(locked)return;const name=window.prompt("Theme name",selected.name)?.trim();if(name)setStore((current)=>({...current,themes:current.themes.map((theme)=>theme.id===selectedId?{...theme,name}:theme)}));};
  const activate=async()=>{setSaving(true);try{const saved=await saveCompanyThemeStore({...store,activeThemeId:selectedId,themes:store.themes.map((theme)=>theme.id===selectedId?{...theme,configuration:normaliseThemeConfiguration(draft)}:theme)});setStore(saved);setStatus("Company theme activated.");}catch(error){setStatus(error instanceof Error?error.message:"Theme could not be activated.");}finally{setSaving(false)}};
  const remove=async()=>{if(locked||!window.confirm(`Delete custom theme “${selected.name}”?`))return;const next={...store,themes:store.themes.filter((theme)=>theme.id!==selectedId),activeThemeId:store.activeThemeId===selectedId?BUILT_IN_THEME_ID:store.activeThemeId};setSaving(true);try{const saved=await saveCompanyThemeStore(next);setStore(saved);setSelectedId(BUILT_IN_THEME_ID);setDraft(structuredClone(DEFAULT_QUOTESYNC_THEME_CONFIGURATION));setStatus("Custom theme deleted.");}catch(error){setStatus(error instanceof Error?error.message:"Theme could not be deleted.");}finally{setSaving(false)}};
  const resetAll=()=>{if(locked)return;const base=themes.find((theme)=>theme.id===selected.baseThemeId)??themes[0];setDraft(structuredClone(base.configuration));setStatus(`Custom theme restored to its ${base.name} base values. Save to persist.`);};
  const setPalette=(mode:"light"|"dark",key:keyof QuoteSyncThemeConfiguration["light"],value:string)=>setDraft((current)=>({...current,[mode]:{...current[mode],[key]:value}}));
  const setGroup=(group:ColourGroup,key:string,value:string)=>setDraft((current)=>({...current,[group]:{...current[group],[key]:value}}));
  const previewAttributes={"data-preview-primary":draft.primary,"data-preview-bg":draft.dark.background,"data-preview-card":draft.dark.card,"data-preview-border":draft.dark.border,"data-preview-text":draft.dark.primaryText,"data-preview-muted":draft.dark.secondaryText,"data-preview-selling":draft.semantic.sellingPrice,"data-preview-attention":draft.operational.ordersAttention};

  return <div className="admin-theme-panel">
    <header className="admin-card ui-card admin-theme-panel__header"><div><div className="admin-page-title">Branding</div><div className="admin-section-title">QuoteSuite Look &amp; Feel</div><p className="admin-body-copy">Manage named company themes without altering the locked Ecofenster default.</p></div><div className="admin-theme-panel__actions"><button className="ui-button" type="button" onClick={()=>duplicate()}>Duplicate</button><button className="ui-button" type="button" disabled={locked} onClick={resetAll}>Restore Theme</button><button className="ui-button ui-button--primary" type="button" disabled={saving||locked} onClick={()=>void save(false)}>Save</button><button className="ui-button ui-button--primary" type="button" disabled={saving||locked} onClick={()=>void save(true)}>Save &amp; Activate</button></div><div className="admin-theme-panel__status" role="status">{status}</div></header>
    <nav className="admin-theme-tabs" aria-label="Branding configuration">{tabs.map(([id,label])=><button key={id} type="button" className={tab===id?"ui-button ui-button--primary":"ui-button"} onClick={()=>setTab(id)}>{label}</button>)}</nav>
    {tab==="themes"&&<section className="admin-theme-layout"><div className="ui-card admin-theme-list"><div className="admin-theme-list__actions"><button className="ui-button" type="button" onClick={create}>Create Theme</button><button className="ui-button" type="button" onClick={()=>duplicate()}>Duplicate Default / Selected</button></div>{themes.map((theme)=><button type="button" key={theme.id} className={`admin-theme-item ${selectedId===theme.id?"is-selected":""}`} onClick={()=>choose(theme)}><span><strong>{theme.name}</strong><small>{theme.builtIn?"Built-in / Locked":"Custom"}</small></span>{store.activeThemeId===theme.id&&<span className="ui-chip">Active</span>}</button>)}</div><div className="ui-card admin-theme-section"><h3>{selected.name}</h3><p>{locked?"This built-in theme is immutable and always recoverable.":"Custom company theme."}</p><div className="admin-theme-panel__actions"><button className="ui-button ui-button--primary" disabled={saving} type="button" onClick={()=>void activate()}>Activate</button><button className="ui-button" disabled={locked} type="button" onClick={rename}>Rename</button><button className="ui-button" type="button" onClick={()=>duplicate()}>Save As / Duplicate</button><button className="ui-button" disabled={locked} type="button" onClick={()=>void remove()}>Delete</button></div><h4>Default Theme</h4><div className="admin-theme-modes">{QUOTESYNC_THEMES.map((mode)=><button key={mode.id} type="button" disabled={locked} className={draft.defaultMode===mode.id?"ui-button ui-button--primary":"ui-button"} onClick={()=>setDraft((current)=>({...current,defaultMode:mode.id}))}>{mode.name}</button>)}</div></div></section>}
    {tab==="colours"&&<>{locked&&<div className="ui-empty-state">Duplicate the built-in theme to edit colours.</div>}<section className="ui-card admin-theme-section"><h3>Brand</h3><div className="admin-theme-grid"><ColourControl label="Primary" value={draft.primary} disabled={locked} onChange={(value)=>setDraft((current)=>({...current,primary:value}))} onReset={()=>setDraft((current)=>({...current,primary:DEFAULT_QUOTESYNC_THEME_CONFIGURATION.primary}))}/><ColourControl label="Accent" value={draft.accent} disabled={locked} onChange={(value)=>setDraft((current)=>({...current,accent:value}))} onReset={()=>setDraft((current)=>({...current,accent:DEFAULT_QUOTESYNC_THEME_CONFIGURATION.accent}))}/></div></section>{(["light","dark"] as const).map((mode)=><section className="ui-card admin-theme-section" key={mode}><div className="admin-theme-section__heading"><h3>Base — {mode[0].toUpperCase()+mode.slice(1)}</h3><button className="ui-button" disabled={locked} type="button" onClick={()=>setDraft((current)=>({...current,[mode]:structuredClone(DEFAULT_QUOTESYNC_THEME_CONFIGURATION[mode])}))}>Restore Section</button></div><div className="admin-theme-grid">{paletteFields.map(([key,label])=><ColourControl key={key} label={label} value={draft[mode][key]} disabled={locked} onChange={(value)=>setPalette(mode,key,value)} onReset={()=>setPalette(mode,key,DEFAULT_QUOTESYNC_THEME_CONFIGURATION[mode][key])}/>)}</div></section>)}<section className="ui-card admin-theme-section"><h3>Semantic</h3><div className="admin-theme-grid">{semanticFields.map(([key,label])=><ColourControl key={key} label={label} value={draft.semantic[key]} disabled={locked} onChange={(value)=>setGroup("semantic",key,value)} onReset={()=>setGroup("semantic",key,DEFAULT_QUOTESYNC_THEME_CONFIGURATION.semantic[key])}/>)}</div></section><section className="ui-card admin-theme-section"><h3>Operational</h3><div className="admin-theme-grid">{operationalFields.map(([key,label])=><ColourControl key={key} label={label} value={draft.operational[key]} disabled={locked} onChange={(value)=>setGroup("operational",key,value)} onReset={()=>setGroup("operational",key,DEFAULT_QUOTESYNC_THEME_CONFIGURATION.operational[key])}/>)}</div></section></>}
    {tab==="typography"&&<section className="ui-card admin-theme-section"><h3>Typography</h3><label className="admin-theme-font-control"><span>Font family</span><select className="ui-select" disabled={locked} value={draft.fontFamily} onChange={(event)=>setDraft((current)=>({...current,fontFamily:event.target.value as QuoteSyncThemeConfiguration["fontFamily"]}))}>{QUOTESYNC_FONT_OPTIONS.map((font)=><option key={font.id} value={font.id}>{font.name}</option>)}</select></label><div className="admin-theme-font-preview" data-font={draft.fontFamily}><strong>QuoteSuite commercial workspace</strong><span>Clear operational and commercial information using the selected company typeface.</span></div></section>}
    {tab==="appearance"&&<section className="ui-card admin-theme-section"><h3>Components / Appearance</h3>{([["density","Density",["compact","standard","comfortable"]],["corners","Corner style",["square-ish","standard","rounded"]],["elevation","Elevation",["minimal","standard","enhanced"]],["motion","Motion",["reduced","standard"]]] as const).map(([key,label,options])=><label className="admin-theme-font-control" key={key}><span>{label}</span><select className="ui-select" disabled={locked} value={draft.appearance[key]} onChange={(event)=>setDraft((current)=>({...current,appearance:{...current.appearance,[key]:event.target.value}}))}>{options.map((option)=><option key={option}>{option}</option>)}</select></label>)}</section>}
    {tab==="identity"&&<section className="ui-card admin-theme-section"><h3>Identity &amp; Logos</h3><div className="ui-empty-state"><strong>Company identity remains managed by the existing document and logo settings.</strong><span>Unified logo asset management will be added when its backend storage boundary is available.</span></div></section>}
    {tab==="preview"&&<section className="admin-theme-preview" {...previewAttributes}><header><strong>QuoteSuite Preview</strong><button type="button">Primary action</button></header><div className="admin-theme-preview__tabs"><span className="is-active">Overview</span><span>Commercial</span><span>Documents</span></div><div className="admin-theme-preview__grid"><article><small>Project value</small><strong>£48,250.00</strong><span>Commercial summary</span></article><article className="is-attention"><small>Needs attention</small><strong>3 orders</strong><span>Review required</span></article></div><label>Client reference<input value="EF-EST-2026-001" readOnly/></label><table><thead><tr><th>Description</th><th>Status</th><th>Value</th></tr></thead><tbody><tr><td>Supplier products</td><td><span className="admin-theme-preview__success">Complete</span></td><td className="admin-theme-preview__selling">£32,400</td></tr></tbody></table></section>}
  </div>;
}
