import { useEffect, useState } from "react";
import Toggle from "../../components/Toggle";
import { apiFetch } from "../../services/api/apiClient";

const displayPolicy = { positionPrices: "show", discountPresentation: "project_total", showOriginalTotal: true, showDiscountPercentage: true, showDiscountAmount: true, showNetTotal: true, showCategoryTotals: true, showOverallTotal: true };
const newStages = () => [1, 2, 3, 4].map((number, sequence) => ({ id: `discount-${number}`, sequence, label: `Discount ${number}`, percentage: "0", enabled: true }));
const empty = () => ({ supplierCode: "", supplierName: "", active: true, policy: { pricingBasis: "factory_price", pricingMethod: "factory_price", pricingPolicyVersion: 2, paidInQuotedCurrency: true, settlementCurrency: "GBP", discountPolicy: { type: "net", thresholdBasis: "manufacturer_list_gbp_before_discounts", stages: newStages(), bands: [] as any[] }, packagePricingAvailable: false, packages: [] as any[], discountApplicationBasis: "selected_complete_package" }, pricingDisplayPolicy: { ...displayPolicy } });
const legacyMethod = (value: string) => value.startsWith("legacy_");

export default function AdminSupplierCommercialDefaults() {
  const [records, setRecords] = useState<any[]>([]);
  const [draft, setDraft] = useState<any>(empty());
  const [status, setStatus] = useState("");
  const load = () => apiFetch("/api/admin/project-calculator-lab/supplier-commercial-defaults").then(value => setRecords(value as any[]));
  useEffect(() => { void load(); }, []);
  const policy = (value: Record<string, unknown>) => setDraft((current: any) => ({ ...current, policy: { ...current.policy, ...value } }));
  const discount = (value: Record<string, unknown>) => policy({ discountPolicy: { ...draft.policy.discountPolicy, ...value } });
  const stage = (index: number, value: Record<string, unknown>) => discount({ stages: draft.policy.discountPolicy.stages.map((item: any, position: number) => position === index ? { ...item, ...value } : item) });
  const band = (index: number, value: Record<string, unknown>) => discount({ bands: draft.policy.discountPolicy.bands.map((item: any, position: number) => position === index ? { ...item, ...value } : item) });
  const packagePatch = (index: number, value: Record<string, unknown>) => policy({ packages: draft.policy.packages.map((item: any, position: number) => ({ ...item, ...(position === index ? value : {}), ...(value.isBase ? { isBase: position === index } : {}) })) });
  const chooseMethod = (pricingBasis: string) => policy({ pricingBasis, pricingMethod: pricingBasis, pricingPolicyVersion: 2, discountPolicy: { ...draft.policy.discountPolicy, type: pricingBasis === "staged_discount" ? "staged" : "net" } });
  const save = async () => { setStatus("Saving…"); try { await apiFetch(`/api/admin/project-calculator-lab/supplier-commercial-defaults/${encodeURIComponent(draft.supplierCode)}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draft) }); await load(); setStatus("Supplier pricing saved. Existing Project Costing snapshots are unchanged."); } catch (error) { setStatus(error instanceof Error ? error.message : "Supplier pricing could not be saved."); } };
  const setActive = async (item: any, active: boolean) => { setStatus(active ? "Reactivating supplier…" : "Archiving supplier…"); try { await apiFetch(`/api/admin/project-calculator-lab/supplier-commercial-defaults/${encodeURIComponent(item.supplierCode)}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...item, active }) }); await load(); if (draft.supplierCode === item.supplierCode) setDraft((current: any) => ({ ...current, active })); setStatus(active ? "Supplier reactivated." : "Supplier archived. Historical quotation and Estimate snapshots are unchanged."); } catch (error) { setStatus(error instanceof Error ? error.message : "Supplier status could not be changed."); } };
  const stages = draft.policy.discountPolicy.stages ?? [];
  const bands = draft.policy.discountPolicy.bands ?? [];
  const method = draft.policy.pricingMethod ?? draft.policy.pricingBasis;
  return <div className="admin-content">
    <section className="ui-card admin-theme-section">
      <h2>Supplier pricing</h2><p>Supplier-specific defaults are copied into new quotation revisions. Historical Project Costing snapshots do not change.</p>
      <div className="admin-theme-grid">
        <label>Supplier code<input className="ui-input" value={draft.supplierCode} onChange={event => setDraft({ ...draft, supplierCode: event.currentTarget.value })} /></label>
        <label>Supplier / manufacturer<input className="ui-input" value={draft.supplierName} onChange={event => setDraft({ ...draft, supplierName: event.currentTarget.value })} /></label>
        <label>Pricing Method<select className="ui-input" value={method} onChange={event => chooseMethod(event.currentTarget.value)}>
          <option value="factory_price">Factory Price</option><option value="parity_1_to_1">1 to 1 Pricing</option><option value="staged_discount">Staged Discount</option>
          {legacyMethod(method) ? <option value={method}>Legacy policy (preserved)</option> : null}
        </select></label>
        <label>Quoted currency normally used for settlement?<Toggle value={draft.policy.paidInQuotedCurrency} onChange={value => policy({ paidInQuotedCurrency: value })} /></label>
        {!draft.policy.paidInQuotedCurrency ? <label>Default settlement currency<input className="ui-input" maxLength={3} value={draft.policy.settlementCurrency} onChange={event => policy({ settlementCurrency: event.currentTarget.value.toUpperCase() })} /></label> : null}
      </div>
      {method === "parity_1_to_1" ? <p className="ui-status-badge">Commercial parity policy: the quoted numeric supplier amount becomes the same numeric GBP costing basis. Saved FX evidence remains unchanged.</p> : null}
      {method === "staged_discount" ? <>
        <section><h3>Discount stages</h3><p>Stages apply sequentially. Discount 1 is the primary discount.</p>{stages.map((item: any, index: number) => <div className="calculator-lab__form" key={item.id}>
          <label>Stage label<input className="ui-input" value={item.label} onChange={event => stage(index, { label: event.currentTarget.value })} /></label>
          <label>Discount %<input className="ui-input" inputMode="decimal" value={item.percentage} onChange={event => stage(index, { percentage: event.currentTarget.value })} /></label>
          <label>Enabled<Toggle value={item.enabled !== false} onChange={value => stage(index, { enabled: value })} /></label>
          {index >= 4 ? <button className="ui-button" onClick={() => discount({ stages: stages.filter((_: any, position: number) => position !== index) })}>Remove</button> : null}
        </div>)}<button className="ui-button" onClick={() => discount({ stages: [...stages, { id: crypto.randomUUID(), sequence: stages.length, label: `Discount ${stages.length + 1}`, percentage: "0", enabled: true }] })}>Add discount stage</button></section>
        <section><h3>Optional order-value bands</h3><p>Basis: manufacturer/list value converted to GBP before discounts. Lower bound is inclusive; upper bound is exclusive. With no bands, every enabled stage applies.</p>{bands.map((item: any, index: number) => <div className="calculator-lab__form" key={item.id}>
          <label>Band label<input className="ui-input" value={item.label} onChange={event => band(index, { label: event.currentTarget.value })} /></label>
          <label>Lower bound GBP<input className="ui-input" inputMode="decimal" value={item.lowerBoundGbp} onChange={event => band(index, { lowerBoundGbp: event.currentTarget.value })} /></label>
          <label>Upper bound GBP (blank = no maximum)<input className="ui-input" inputMode="decimal" value={item.upperBoundGbp ?? ""} onChange={event => band(index, { upperBoundGbp: event.currentTarget.value || null })} /></label>
          <fieldset><legend>Applied stages</legend>{stages.map((entry: any) => <label key={entry.id}><input type="checkbox" checked={(item.stageIds ?? []).includes(entry.id)} onChange={event => band(index, { stageIds: event.currentTarget.checked ? [...(item.stageIds ?? []), entry.id] : (item.stageIds ?? []).filter((id: string) => id !== entry.id) })} />{entry.label}</label>)}</fieldset>
          <button className="ui-button" onClick={() => discount({ bands: bands.filter((_: any, position: number) => position !== index) })}>Remove band</button>
        </div>)}<button className="ui-button" onClick={() => discount({ bands: [...bands, { id: crypto.randomUUID(), label: `Band ${bands.length + 1}`, lowerBoundGbp: "0", upperBoundGbp: null, stageIds: stages.filter((item: any) => item.enabled !== false).map((item: any) => item.id), enabled: true }] })}>Add order-value band</button></section>
      </> : null}
      <details><summary><strong>Supplier package pricing</strong></summary><label>Package pricing available?<Toggle value={draft.policy.packagePricingAvailable} onChange={value => policy({ packagePricingAvailable: value })} /></label>{draft.policy.packagePricingAvailable ? <>{(draft.policy.packages ?? []).map((item: any, index: number) => <div className="calculator-lab__form" key={item.id}><label>Package label<input className="ui-input" value={item.label} onChange={event => packagePatch(index, { label: event.currentTarget.value })} /></label><label>Description<input className="ui-input" value={item.description ?? ""} onChange={event => packagePatch(index, { description: event.currentTarget.value })} /></label><label>Amount<input className="ui-input" inputMode="decimal" value={item.amount ?? ""} onChange={event => packagePatch(index, { amount: event.currentTarget.value })} /></label><label>Base Supply Only?<Toggle value={Boolean(item.isBase)} onChange={value => packagePatch(index, { isBase: value })} /></label>{!item.isBase ? <label>Uplift category<input className="ui-input" value={item.upliftCategory ?? "installation"} onChange={event => packagePatch(index, { upliftCategory: event.currentTarget.value })} /></label> : null}<label>Source matching text<input className="ui-input" value={item.sourceMatch ?? ""} onChange={event => packagePatch(index, { sourceMatch: event.currentTarget.value })} /></label><label>Enabled<Toggle value={item.enabled !== false} onChange={value => packagePatch(index, { enabled: value })} /></label><button className="ui-button" onClick={() => policy({ packages: draft.policy.packages.filter((_: any, position: number) => position !== index) })}>Remove package</button></div>)}<button className="ui-button" onClick={() => policy({ packages: [...(draft.policy.packages ?? []), { id: crypto.randomUUID(), label: "New package", description: "", amount: "0", isBase: !(draft.policy.packages ?? []).length, upliftCategory: "installation", sourceMatch: "", enabled: true }] })}>Add package</button><label>Supplier discount applies to<select className="ui-input" value={draft.policy.discountApplicationBasis} onChange={event => policy({ discountApplicationBasis: event.currentTarget.value })}><option value="selected_complete_package">Selected complete package</option><option value="base_supply_only">Base Supply Only package</option><option value="package_uplift">Package uplift only</option></select></label></> : null}</details>
      <details><summary><strong>Customer pricing presentation policy</strong></summary><div className="admin-theme-grid"><label>Position pricing<select className="ui-input" value={draft.pricingDisplayPolicy.positionPrices} onChange={event => setDraft({ ...draft, pricingDisplayPolicy: { ...draft.pricingDisplayPolicy, positionPrices: event.currentTarget.value } })}><option value="show">Show individual position prices</option><option value="hide">Hide individual position prices</option></select></label><label>Discount presentation<select className="ui-input" value={draft.pricingDisplayPolicy.discountPresentation} onChange={event => setDraft({ ...draft, pricingDisplayPolicy: { ...draft.pricingDisplayPolicy, discountPresentation: event.currentTarget.value } })}><option value="position">Show against individual positions</option><option value="project_total">Show at Products/project total</option><option value="net_only">Net prices only</option></select></label>{Object.entries({ showOriginalTotal: "Show original total", showDiscountPercentage: "Show discount percentage", showDiscountAmount: "Show discount monetary value", showNetTotal: "Show discounted/net total", showCategoryTotals: "Show category totals", showOverallTotal: "Show overall project total" }).map(([key, label]) => <label key={key}>{label}<Toggle value={Boolean(draft.pricingDisplayPolicy[key])} onChange={value => setDraft({ ...draft, pricingDisplayPolicy: { ...draft.pricingDisplayPolicy, [key]: value } })} /></label>)}</div></details>
      <button className="ui-button ui-button--primary" disabled={!draft.supplierCode || !draft.supplierName || legacyMethod(method)} onClick={() => void save()}>Save supplier pricing</button>{status ? <p role="status">{status}</p> : null}
    </section>
    <section className="ui-card admin-supplier-list"><h3>Configured suppliers</h3><p>Choose Edit to amend defaults. Referenced suppliers are archived rather than deleted so historical quotation and Estimate snapshots remain intact.</p><table><thead><tr><th>Supplier</th><th>Pricing method</th><th>Status</th><th>Actions</th></tr></thead><tbody>{records.map(item => { const selected=draft.supplierCode===item.supplierCode; const methodLabel=({ factory_price: "Factory Price", parity_1_to_1: "1 to 1 Pricing", staged_discount: "Staged Discount" } as Record<string,string>)[item.policy.pricingMethod ?? item.policy.pricingBasis] ?? "Legacy policy (preserved)"; return <tr key={item.supplierCode} className={selected?"is-selected":""} onClick={()=>setDraft(item)}><td><strong>{item.supplierName}</strong><small>{item.supplierCode}</small></td><td>{methodLabel}</td><td>{item.active!==false?"Active":"Archived"}</td><td><div className="admin-supplier-list__actions"><button type="button" className="ui-button" aria-label={`Edit ${item.supplierName}`} onClick={(event)=>{event.stopPropagation();setDraft(item)}}>Edit</button><button type="button" className="ui-button" aria-label={`${item.active!==false?"Archive":"Reactivate"} ${item.supplierName}`} onClick={(event)=>{event.stopPropagation();void setActive(item,item.active===false)}}>{item.active!==false?"Archive":"Reactivate"}</button></div></td></tr>})}</tbody></table></section>
  </div>;
}
