// Auto-generated by QuoteSync Phase 4C extraction patch.
// Seed/demo clients moved out of src/App.tsx (no logic changes).
import * as Models from "../../models/types";
import type { Client, Estimate, Position } from "../../models/types";
import { makeDefaultEstimateDefaults } from "../estimateDefaults/defaultEstimateDefaults";

export const DEFAULT_CUSTOMER_ADDRESS = ["4 Glebe Road", "Cowdenbeath", "Fife", "KY4 9FA"].join("\n");

function makeDemoPositions(opts: { uid: () => string }): Position[] {
  const mk = (n: number, w: number, h: number): Position => ({
    id: Models.asPositionId(opts.uid()),
    positionRef: `W-${String(n).padStart(3, "0")}`,
    qty: 1,
    roomName: "",
    widthMm: w,
    heightMm: h,
    fieldsX: 1,
    fieldsY: 1,
    insertion: "Fixed",
    cellInsertions: { "0,0": "Fixed" },
    positionType: "Window",
    useEstimateDefaults: true,
    overrides: {},
  });

  return [
    mk(1, 1000, 1200),
    mk(2, 900, 900),
    mk(3, 1200, 1050),
    mk(4, 800, 2100),
    mk(5, 1500, 1200),
  ];
}

function makeDemoEstimate(opts: { uid: () => string }, n: number): Estimate {
  const year = new Date().getFullYear();
  const base = `${year}-90${String(n).padStart(2, "0")}`;

  return {
    id: Models.asEstimateId(opts.uid()),
    estimateRef: base,
    baseEstimateRef: base,
    revisionNo: 0,
    status: "Draft",
    defaults: makeDefaultEstimateDefaults(),
    positions: makeDemoPositions(opts),
  };
}

export function makeDefaultClients(opts: { uid: () => string; nextClientRef: (n: number) => string }): Client[] {
  return [
    {
      id: Models.asClientId(opts.uid()),
      type: "Business",
      clientRef: opts.nextClientRef(1),
      clientName: "Ecofenster Ltd",
      businessName: "Ecofenster Ltd",
      contactPerson: "",
      email: "",
      mobile: "07882 809 453",
      home: "",
      projectName: "",
      projectAddress: DEFAULT_CUSTOMER_ADDRESS,
      invoiceAddress: DEFAULT_CUSTOMER_ADDRESS,
      estimates: [makeDemoEstimate(opts, 1)],
    },
    {
      id: Models.asClientId(opts.uid()),
      type: "Individual",
      clientRef: opts.nextClientRef(2),
      clientName: "Craig Ferguson",
      businessName: "",
      contactPerson: "",
      email: "",
      mobile: "07882 809 453",
      home: "",
      projectName: "",
      projectAddress: DEFAULT_CUSTOMER_ADDRESS,
      invoiceAddress: DEFAULT_CUSTOMER_ADDRESS,
      estimates: [makeDemoEstimate(opts, 2)],
    },
  ];
}

