// Auto-generated by QuoteSync Phase 4C extraction patch.
// Seed/demo clients moved out of src/App.tsx (no logic changes).
import * as Models from "../../models/types";
import type { Address, Client, Estimate, Position } from "../../models/types";
import { makeDefaultEstimateDefaults } from "../estimateDefaults/defaultEstimateDefaults";

export const DEFAULT_CUSTOMER_ADDRESS_STRUCTURED: Address = {
  line1: "4 Glebe Road",
  line2: "",
  line3: "",
  town: "Cowdenbeath",
  city: "",
  county: "Fife",
  postcode: "KY4 9FA",
};

export const DEFAULT_CUSTOMER_ADDRESS = [
  DEFAULT_CUSTOMER_ADDRESS_STRUCTURED.line1,
  DEFAULT_CUSTOMER_ADDRESS_STRUCTURED.line2,
  DEFAULT_CUSTOMER_ADDRESS_STRUCTURED.line3,
  DEFAULT_CUSTOMER_ADDRESS_STRUCTURED.town,
  DEFAULT_CUSTOMER_ADDRESS_STRUCTURED.city,
  DEFAULT_CUSTOMER_ADDRESS_STRUCTURED.county,
  DEFAULT_CUSTOMER_ADDRESS_STRUCTURED.postcode,
].join("\n");

const ORDER_MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
] as const;

function makeDemoPositions(opts: { uid: () => string }): Position[] {
  const mk = (n: number, w: number, h: number): Position => ({
    id: Models.asPositionId(opts.uid()),
    positionRef: `W-${String(n).padStart(3, "0")}`,
    qty: 1,
    itemPrice: 1250 + n * 175,
    roomName: "",
    widthMm: w,
    heightMm: h,
    fieldsX: 1,
    fieldsY: 1,
    insertion: "Fixed",
    cellInsertions: { "0,0": "Fixed" },
    positionType: "Window",
    useEstimateDefaults: true,
    overrides: {},
  });

  return [
    mk(1, 1000, 1200),
    mk(2, 900, 900),
    mk(3, 1200, 1050),
    mk(4, 800, 2100),
    mk(5, 1500, 1200),
  ];
}

function makeDemoEstimate(opts: { uid: () => string }, n: number): Estimate {
  const year = new Date().getFullYear();
  const base = `${year}-90${String(n).padStart(2, "0")}`;

  return {
    id: Models.asEstimateId(opts.uid()),
    estimateRef: base,
    baseEstimateRef: base,
    revisionNo: 0,
        status: "Draft" as const,
    estimatedOrderMonth: ORDER_MONTHS[(n - 1) % ORDER_MONTHS.length],
    estimatedOrderYear: year + Math.floor((n - 1) / ORDER_MONTHS.length),
    defaults: makeDefaultEstimateDefaults(),
    positions: makeDemoPositions(opts),
  };
}

export function makeDefaultClients(opts: {
  uid: () => string;
  nextClientRef: (n: number) => string;
  loadDemoClients: boolean;
  loadDemoEstimates: boolean;
}): Client[] {
  if (!opts.loadDemoClients) return [];
  const firstNames = [
    "Oliver", "George", "Harry", "Jack", "Noah", "Leo", "Arthur", "Charlie", "Oscar", "Henry",
    "Freddie", "Theo", "Alfie", "Archie", "Thomas", "William", "James", "Lucas", "Logan", "Isaac",
  ];

  const lastNames = [
    "Smith", "Jones", "Taylor", "Brown", "Williams", "Wilson", "Davies", "Evans", "Thomas", "Roberts",
    "Johnson", "Walker", "Wright", "Thompson", "White", "Hughes", "Edwards", "Green", "Hall", "Turner",
  ];

  const businessNames = [
    "Northfield Developments Ltd",
    "Oak & Stone Construction",
    "Greenframe Projects Ltd",
    "Essex Build Group",
    "Primeview Homes Ltd",
    "Urbanline Construction",
    "Crown Property Services",
    "Westgate Developments",
    "Blueoak Installations Ltd",
    "Maplebridge Contractors",
    "Harbour View Developments",
    "Apex Glazing Solutions",
    "Redbrick Homes Ltd",
    "Eastbrook Property Group",
    "Silverfern Construction",
  ];

  const streets = [
    "High Street",
    "Church Road",
    "Station Road",
    "London Road",
    "Victoria Avenue",
    "Kings Road",
    "Park Lane",
    "Mill Lane",
    "School Lane",
    "South View Road",
    "Oak Drive",
    "Meadow Close",
    "Willow Way",
    "Chestnut Avenue",
    "The Green",
  ];

  const towns = [
    "Basildon",
    "Billericay",
    "Brentwood",
    "Chelmsford",
    "Rayleigh",
    "Wickford",
    "Romford",
    "Southend-on-Sea",
    "Colchester",
    "Harlow",
    "Grays",
    "Maldon",
    "Witham",
    "Benfleet",
    "Leigh-on-Sea",
  ];

const counties = [
  "Fife",
  "Essex",
  "Kent",
  "Surrey",
  "Yorkshire",
  "Lancashire",
  "Devon",
  "Cornwall",
  "Hertfordshire",
  "Norfolk",
  "Suffolk",
  "Cambridgeshire",
  "Leicestershire",
  "Nottinghamshire",
  "Derbyshire",
  "Warwickshire",
  "Oxfordshire",
  "Berkshire",
];

  const projectNames = [
    "Rear Extension",
    "Whole House Replacement",
    "New Build Plot 3",
    "Showroom Upgrade",
    "Garden Room Package",
    "Aluminium Door Upgrade",
    "Passive House Package",
    "Refurbishment Phase 1",
    "Timber Window Renewal",
    "Trade Supply Package",
  ];

  const estimateCountPattern = [1, 2, 5, 10];

  function randFrom<T>(arr: T[]): T {
    return arr[Math.floor(Math.random() * arr.length)];
  }

  function randInt(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
  }

  function randomPostcode() {
    const area = randFrom(["SS", "CM", "RM", "CO", "IG"]);
    return `${area}${randInt(1, 9)} ${randInt(1, 9)}${randFrom(["A", "B", "C", "D", "E", "F", "G", "H", "J", "K"])}${randFrom(["A", "B", "C", "D", "E", "F", "G", "H", "J", "K"])}`;
  }

  function buildAddressString(address: Address) {
    return [
      address.line1,
      address.line2,
      address.line3,
      address.town,
      address.city,
      address.county,
      address.postcode,
    ].join("\n");
  }

  function randomAddressStructured(): Address {
    return {
      line1: `${randInt(1, 180)} ${randFrom(streets)}`,
      line2: "",
      line3: "",
      town: randFrom(towns),
      city: "",
      county: randFrom(counties),
      postcode: randomPostcode(),
    };
  }

  function randomAddress() {
    return buildAddressString(randomAddressStructured());
  }

  function extractPostcode(projectAddress: string) {
    const match = (projectAddress || "").match(/[A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2}/i);
    return match ? match[0].toUpperCase().replace(/\s+/, " ") : "";
  }

  let demoEstimateSequence = 0;

  function randomIsoDateFromToday(minDays: number, maxDays: number) {
    const start = new Date();
    const daysToAdd = randInt(minDays, maxDays);
    start.setDate(start.getDate() + daysToAdd);
    return start.toISOString().slice(0, 10);
  }

  function buildDemoOrderMeta(kind: "order" | "installation") {
    const productionStartDate = randomIsoDateFromToday(7, 70);
    const productionWeeks = randFrom([2, 4, 6, 8, 10, 12, 14, 16]);
    const start = new Date(`${productionStartDate}T00:00:00`);
    const productionEnd = new Date(start);
    productionEnd.setDate(productionEnd.getDate() + productionWeeks * 7);

    const balanceInvoiceDue = new Date(productionEnd);
    balanceInvoiceDue.setDate(balanceInvoiceDue.getDate() - 14);

    const deliveryDate = new Date(productionEnd);
    deliveryDate.setDate(deliveryDate.getDate() + randInt(1, 10));

    const installationDate = new Date(deliveryDate);
    installationDate.setDate(installationDate.getDate() + randInt(1, 14));

    return {
      timeline: [],
      installerId: kind === "installation" ? `demo-installer-${((demoEstimateSequence - 1) % 5) + 1}` : undefined,
      clientSignoffSentDate: randomIsoDateFromToday(-30, 10),
      clientSignoffReceivedDate: randomIsoDateFromToday(-20, 20),
      factoryOrderSignedOffDate: randomIsoDateFromToday(-10, 25),
      factoryInvoicePaidDate: randomIsoDateFromToday(-10, 30),
      productionWeeks,
      productionStartDate,
      productionEndDate: productionEnd.toISOString().slice(0, 10),
      balanceInvoiceDueDate: balanceInvoiceDue.toISOString().slice(0, 10),
      productionCompletedDate: productionEnd.toISOString().slice(0, 10),
      factoryDispatchDate: deliveryDate.toISOString().slice(0, 10),
      deliveryDate: deliveryDate.toISOString().slice(0, 10),
      installationDate: kind === "installation" ? installationDate.toISOString().slice(0, 10) : "",
    };
  }

  function makeEstimate(seed: number, estimateIndex: number) {
    demoEstimateSequence += 1;
    const base = makeDemoEstimate(opts, seed);

    const positionCount = randInt(1, 100);
    const basePosition = base.positions[0];

    const positions = Array.from({ length: positionCount }, (_, posIndex) => ({
      ...basePosition,
      id: Models.asPositionId(opts.uid()),
      positionRef: `W-${String(posIndex + 1).padStart(3, "0")}`,
      qty: randInt(1, 6),
      itemPrice: randInt(850, 4200),
      roomName: randFrom([
        "Kitchen",
        "Living Room",
        "Bedroom 1",
        "Bedroom 2",
        "Bathroom",
        "Hall",
        "Landing",
        "Office",
        "Dining Room",
        "Extension",
      ]),
      widthMm: randInt(600, 3200),
      heightMm: randInt(600, 2800),
      fieldsX: 1,
      fieldsY: 1,
      insertion: randFrom(["Fixed", "Turn", "Tilt", "Tilt & Turn", "Top Hung", "Side Hung"]),
      cellInsertions: { "0,0": randFrom(["Fixed", "Turn", "Tilt", "Tilt & Turn", "Top Hung", "Side Hung"]) },
      colWidthsMm: undefined,
      rowHeightsMm: undefined,
      positionType: randFrom(["Window", "Door"] as const),
      useEstimateDefaults: true,
      overrides: {},
    }));

    const isInstallationSeed = demoEstimateSequence > 35 && demoEstimateSequence <= 52;
    const isOrderSeed = demoEstimateSequence > 10 && demoEstimateSequence <= 35;

    return {
      ...base,
      id: Models.asEstimateId(opts.uid()),
      estimateRef: `${base.estimateRef}-${String(estimateIndex + 1).padStart(2, "0")}`,
      baseEstimateRef: `${base.baseEstimateRef}-${String(estimateIndex + 1).padStart(2, "0")}`,
      revisionNo: 0,
      status: "Draft" as const,
      estimatedOrderMonth: randFrom([...ORDER_MONTHS]),
      estimatedOrderYear: new Date().getFullYear() + randInt(0, 1),
      orderMeta: isOrderSeed || isInstallationSeed ? buildDemoOrderMeta(isInstallationSeed ? "installation" : "order") : undefined,
      positions,
    };
  }

  const extraClients: Client[] = Array.from({ length: 30 }, (_, idx) => {
    const isBusiness = Math.random() < 0.45;
    const firstName = randFrom(firstNames);
    const lastName = randFrom(lastNames);
    const personName = `${firstName} ${lastName}`;
    const businessName = randFrom(businessNames);
    const estimateCount = estimateCountPattern[idx % estimateCountPattern.length];
    const customerAddressStructured = randomAddressStructured();
    const customerAddress = buildAddressString(customerAddressStructured);
    const projectAddressStructured = randomAddressStructured();
    const projectAddress = buildAddressString(projectAddressStructured);
    const invoiceDifferent = Math.random() < 0.25;
    const invoiceAddressStructured = invoiceDifferent ? randomAddressStructured() : { ...projectAddressStructured };
    const invoiceAddress = buildAddressString(invoiceAddressStructured);

    const estimates = opts.loadDemoEstimates
      ? Array.from({ length: estimateCount }, (_, estimateIndex) =>
          makeEstimate(1000 + idx * 20 + estimateIndex, estimateIndex)
        )
      : [];

    return {
      id: Models.asClientId(opts.uid()),
      type: isBusiness ? "Business" : "Individual",
      clientRef: opts.nextClientRef(idx + 3),
      clientName: isBusiness ? businessName : personName,
      businessName: isBusiness ? businessName : "",
      contactPerson: isBusiness ? personName : "",
      email: `${firstName}.${lastName}${idx + 1}@example.com`.toLowerCase(),
      mobile: `07${randInt(100000000, 999999999)}`,
      home: Math.random() < 0.5 ? `01${randInt(100000000, 999999999)}` : "",
      projectName: randFrom(projectNames),
      customerAddress,
      projectAddress,
      invoiceAddress,
      customerAddressStructured,
      projectAddressStructured,
      invoiceAddressStructured,
      postcode: extractPostcode(projectAddress),
      estimates,
    };
  });

  return [
    {
      id: Models.asClientId(opts.uid()),
      type: "Business",
      clientRef: opts.nextClientRef(1),
      clientName: "Ecofenster Ltd",
      businessName: "Ecofenster Ltd",
      contactPerson: "",
      email: "",
      mobile: "07882 809 453",
      home: "",
      projectName: "",
      customerAddress: DEFAULT_CUSTOMER_ADDRESS,
      projectAddress: DEFAULT_CUSTOMER_ADDRESS,
      invoiceAddress: DEFAULT_CUSTOMER_ADDRESS,
      customerAddressStructured: { ...DEFAULT_CUSTOMER_ADDRESS_STRUCTURED },
      projectAddressStructured: { ...DEFAULT_CUSTOMER_ADDRESS_STRUCTURED },
      invoiceAddressStructured: { ...DEFAULT_CUSTOMER_ADDRESS_STRUCTURED },
      postcode: extractPostcode(DEFAULT_CUSTOMER_ADDRESS),
      estimates: opts.loadDemoEstimates ? [makeDemoEstimate(opts, 1)] : [],
    },
    {
      id: Models.asClientId(opts.uid()),
      type: "Individual",
      clientRef: opts.nextClientRef(2),
      clientName: "Craig Ferguson",
      businessName: "",
      contactPerson: "",
      email: "",
      mobile: "07882 809 453",
      home: "",
      projectName: "",
      customerAddress: DEFAULT_CUSTOMER_ADDRESS,
      projectAddress: DEFAULT_CUSTOMER_ADDRESS,
      invoiceAddress: DEFAULT_CUSTOMER_ADDRESS,
      customerAddressStructured: { ...DEFAULT_CUSTOMER_ADDRESS_STRUCTURED },
      projectAddressStructured: { ...DEFAULT_CUSTOMER_ADDRESS_STRUCTURED },
      invoiceAddressStructured: { ...DEFAULT_CUSTOMER_ADDRESS_STRUCTURED },
      postcode: extractPostcode(DEFAULT_CUSTOMER_ADDRESS),
      estimates: opts.loadDemoEstimates ? [makeDemoEstimate(opts, 2)] : [],
    },
    ...extraClients,
  ];
}

