// Auto-generated by QuoteSync Phase 4C extraction patch.
// Seed/demo clients moved out of src/App.tsx (no logic changes).
import * as Models from "../../models/types";
import type { Client } from "../../models/types";
export const DEFAULT_CUSTOMER_ADDRESS = ["4 Glebe Road", "Cowdenbeath", "Fife", "KY4 9FA"].join("\n");

export function makeDefaultClients(opts: { uid: () => string; nextClientRef: (n: number) => string }): Client[]  {
  return [
    {
      id: Models.asClientId(opts.uid()),
      type: "Business",
      clientRef: opts.nextClientRef(1),
      clientName: "Ecofenster Ltd",
      businessName: "Ecofenster Ltd",
      contactPerson: "",
      email: "",
      mobile: "07882 809 453",
      home: "",
      projectName: "",
      projectAddress: DEFAULT_CUSTOMER_ADDRESS,
      invoiceAddress: DEFAULT_CUSTOMER_ADDRESS,
      estimates: [],
    },
    {
      id: Models.asClientId(opts.uid()),
      type: "Individual",
      clientRef: opts.nextClientRef(2),
      clientName: "Craig Ferguson",
      businessName: "",
      contactPerson: "",
      email: "",
      mobile: "07882 809 453",
      home: "",
      projectName: "",
      projectAddress: DEFAULT_CUSTOMER_ADDRESS,
      invoiceAddress: DEFAULT_CUSTOMER_ADDRESS,
      estimates: [],
    },
  ];
}


