import type {
  B92ConfiguratorLayoutOrientation,
  B92ConfiguratorLayoutPreset,
} from "./b92Configurator.types";

export type B92StructurePresetDefinition = {
  id: B92ConfiguratorLayoutPreset;
  label: string;
  fieldCount: number;
  orientation: B92ConfiguratorLayoutOrientation;
  rows: number;
  columns: number;
  disabled?: boolean;
  mappedProofFamilyId: string | null;
  unsupportedReason: string | null;
};

export const B92_FIELD_COUNT_OPTIONS = [1, 2, 3, 4, 5, 6] as const;

export const B92_GRID_PRESET_OPTIONS: B92StructurePresetDefinition[] = [
  {
    id: "1x2-grid",
    label: "1x2",
    fieldCount: 2,
    orientation: "grid",
    rows: 1,
    columns: 2,
    mappedProofFamilyId: "b92-2-field-fixed-fixed",
    unsupportedReason: null,
  },
  {
    id: "2x1-grid",
    label: "2x1",
    fieldCount: 2,
    orientation: "grid",
    rows: 2,
    columns: 1,
    mappedProofFamilyId: "b92-2-field-fixed-bottom-fixed-top",
    unsupportedReason: null,
  },
  {
    id: "2x2-grid",
    label: "2x2",
    fieldCount: 4,
    orientation: "grid",
    rows: 2,
    columns: 2,
    mappedProofFamilyId: null,
    unsupportedReason: "No promoted 2x2 Grid B92 proof family exists yet.",
  },
  {
    id: "2x3-grid",
    label: "2x3",
    fieldCount: 6,
    orientation: "grid",
    rows: 2,
    columns: 3,
    mappedProofFamilyId: null,
    unsupportedReason: "No promoted 2x3 Grid B92 proof family exists yet.",
  },
  {
    id: "3x2-grid",
    label: "3x2",
    fieldCount: 6,
    orientation: "grid",
    rows: 3,
    columns: 2,
    mappedProofFamilyId: null,
    unsupportedReason: "No promoted 3x2 Grid B92 proof family exists yet.",
  },
  {
    id: "3x3-grid",
    label: "3x3",
    fieldCount: 9,
    orientation: "grid",
    rows: 3,
    columns: 3,
    mappedProofFamilyId: null,
    unsupportedReason: "No promoted 3x3 Grid B92 proof family exists yet.",
  },
  {
    id: "3x4-grid",
    label: "3x4",
    fieldCount: 12,
    orientation: "grid",
    rows: 3,
    columns: 4,
    mappedProofFamilyId: null,
    unsupportedReason: "No promoted 3x4 Grid B92 proof family exists yet.",
  },
  {
    id: "4x3-grid",
    label: "4x3",
    fieldCount: 12,
    orientation: "grid",
    rows: 4,
    columns: 3,
    mappedProofFamilyId: null,
    unsupportedReason: "No promoted 4x3 Grid B92 proof family exists yet.",
  },
  {
    id: "4x4-grid",
    label: "4x4",
    fieldCount: 16,
    orientation: "grid",
    rows: 4,
    columns: 4,
    mappedProofFamilyId: null,
    unsupportedReason: "No promoted 4x4 Grid B92 proof family exists yet.",
  },
  {
    id: "5x4-grid",
    label: "5x4",
    fieldCount: 20,
    orientation: "grid",
    rows: 5,
    columns: 4,
    mappedProofFamilyId: null,
    unsupportedReason: "No promoted 5x4 Grid B92 proof family exists yet.",
  },
  {
    id: "4x5-grid",
    label: "4x5",
    fieldCount: 20,
    orientation: "grid",
    rows: 4,
    columns: 5,
    mappedProofFamilyId: null,
    unsupportedReason: "No promoted 4x5 Grid B92 proof family exists yet.",
  },
  {
    id: "5x5-grid",
    label: "5x5",
    fieldCount: 25,
    orientation: "grid",
    rows: 5,
    columns: 5,
    mappedProofFamilyId: null,
    unsupportedReason: "No promoted 5x5 Grid B92 proof family exists yet.",
  },
  {
    id: "5x6-grid",
    label: "5x6",
    fieldCount: 30,
    orientation: "grid",
    rows: 5,
    columns: 6,
    mappedProofFamilyId: null,
    unsupportedReason: "No promoted 5x6 Grid B92 proof family exists yet.",
  },
  {
    id: "6x5-grid",
    label: "6x5",
    fieldCount: 30,
    orientation: "grid",
    rows: 6,
    columns: 5,
    mappedProofFamilyId: null,
    unsupportedReason: "No promoted 6x5 Grid B92 proof family exists yet.",
  },
  {
    id: "6x6-grid",
    label: "6x6",
    fieldCount: 36,
    orientation: "grid",
    rows: 6,
    columns: 6,
    mappedProofFamilyId: null,
    unsupportedReason: "No promoted 6x6 Grid B92 proof family exists yet.",
  },
];

export const B92_STRUCTURE_PRESETS: B92StructurePresetDefinition[] = [
  {
    id: "1-field",
    label: "1 Field",
    fieldCount: 1,
    orientation: "horizontal",
    rows: 1,
    columns: 1,
    mappedProofFamilyId: "b92-1-field-fixed",
    unsupportedReason: null,
  },
  {
    id: "2-field-horizontal",
    label: "2 Field Horizontal",
    fieldCount: 2,
    orientation: "horizontal",
    rows: 1,
    columns: 2,
    mappedProofFamilyId: "b92-2-field-fixed-fixed",
    unsupportedReason: null,
  },
  {
    id: "2-field-vertical",
    label: "2 Field Vertical",
    fieldCount: 2,
    orientation: "vertical",
    rows: 2,
    columns: 1,
    mappedProofFamilyId: "b92-2-field-fixed-bottom-fixed-top",
    unsupportedReason: null,
  },
  {
    id: "3-field-horizontal",
    label: "3 Field Horizontal",
    fieldCount: 3,
    orientation: "horizontal",
    rows: 1,
    columns: 3,
    mappedProofFamilyId: "b92-3-field-fixed-fixed-fixed",
    unsupportedReason: null,
  },
  {
    id: "3-field-vertical",
    label: "3 Field Vertical",
    fieldCount: 3,
    orientation: "vertical",
    rows: 3,
    columns: 1,
    mappedProofFamilyId: null,
    unsupportedReason: "No promoted 3 Field Vertical B92 proof family exists yet.",
  },
  {
    id: "4-field-horizontal",
    label: "4 Field Horizontal",
    fieldCount: 4,
    orientation: "horizontal",
    rows: 1,
    columns: 4,
    mappedProofFamilyId: null,
    unsupportedReason: "No promoted 4 Field Horizontal B92 proof family exists yet.",
  },
  {
    id: "4-field-vertical",
    label: "4 Field Vertical",
    fieldCount: 4,
    orientation: "vertical",
    rows: 4,
    columns: 1,
    mappedProofFamilyId: null,
    unsupportedReason: "No promoted 4 Field Vertical B92 proof family exists yet.",
  },
  {
    id: "5-field-horizontal",
    label: "5 Field Horizontal",
    fieldCount: 5,
    orientation: "horizontal",
    rows: 1,
    columns: 5,
    mappedProofFamilyId: null,
    unsupportedReason: "No promoted 5 Field Horizontal B92 proof family exists yet.",
  },
  {
    id: "5-field-vertical",
    label: "5 Field Vertical",
    fieldCount: 5,
    orientation: "vertical",
    rows: 5,
    columns: 1,
    mappedProofFamilyId: null,
    unsupportedReason: "No promoted 5 Field Vertical B92 proof family exists yet.",
  },
  {
    id: "6-field-horizontal",
    label: "6 Field Horizontal",
    fieldCount: 6,
    orientation: "horizontal",
    rows: 1,
    columns: 6,
    mappedProofFamilyId: null,
    unsupportedReason: "No promoted 6 Field Horizontal B92 proof family exists yet.",
  },
  {
    id: "6-field-vertical",
    label: "6 Field Vertical",
    fieldCount: 6,
    orientation: "vertical",
    rows: 6,
    columns: 1,
    mappedProofFamilyId: null,
    unsupportedReason: "No promoted 6 Field Vertical B92 proof family exists yet.",
  },
  ...B92_GRID_PRESET_OPTIONS,
];

export function getB92StructurePresetDefinition(preset: B92ConfiguratorLayoutPreset) {
  return B92_STRUCTURE_PRESETS.find((candidate) => candidate.id === preset) ?? B92_STRUCTURE_PRESETS[0];
}
