import { useEffect, useMemo, useState } from "react";
import type { Client } from "../../models/types";
import { apiFetch } from "../../services/api/apiClient";
import ClientPortalPreview from "./ClientPortalPreview";
import type { CustomerSafeCommercial } from "./customerSafePortalProjection";
import "./clientPortalPreview.css";

type DirectoryRow={clientId:string;clientReference:string;clientName:string;projectId:string;projectName:string;projectStatus:string;portalAccessStatus:string;activeContacts:number;releasedResources:number};
type Preview={access:{tenantId:string;clientId:string;projectId:string;displayName:string;mode:string};features:Array<{featureKey:string;enabled:boolean}>;project:{id:string;name:string;status:string};estimates:Array<{estimateId:string;commercial:{supplyOnly:number|null;installation:number|null;vatGbp:number|null;totalIncVatGbp:number|null;currency:string}}> ;documents:Array<{id:string}>};

export default function ClientPortalStaffWorkspace({clients,initialClientId=null,initialProjectId=null,onContextConsumed}:{clients:Client[];initialClientId?:string|null;initialProjectId?:string|null;onContextConsumed?:()=>void}){
  const [search,setSearch]=useState(""),[rows,setRows]=useState<DirectoryRow[]>([]),[context,setContext]=useState<{clientId:string;projectId:string}|null>(initialClientId&&initialProjectId?{clientId:initialClientId,projectId:initialProjectId}:null),[preview,setPreview]=useState<Preview|null>(null),[error,setError]=useState("");
  useEffect(()=>{if(initialClientId&&initialProjectId){setContext({clientId:initialClientId,projectId:initialProjectId});onContextConsumed?.()}},[initialClientId,initialProjectId,onContextConsumed]);
  useEffect(()=>{let active=true;apiFetch(`/api/client-portal/internal/directory?search=${encodeURIComponent(search)}`).then(value=>{if(active)setRows(value as DirectoryRow[])}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"Client Portal directory could not be loaded.")});return()=>{active=false}},[search]);
  useEffect(()=>{if(!context){setPreview(null);return}let active=true;apiFetch(`/api/client-portal/internal/clients/${encodeURIComponent(context.clientId)}/projects/${encodeURIComponent(context.projectId)}/preview`).then(value=>{if(active){setPreview(value as Preview);setError("")}}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"Authorised internal portal preview could not be loaded.")});return()=>{active=false}},[context]);
  const client=useMemo(()=>context?clients.find(item=>String(item.id)===context.clientId)||null:null,[clients,context]);
  if(context&&client&&preview){const commercialByEstimateId=Object.fromEntries(preview.estimates.map(item=>[item.estimateId,{supplyOnly:item.commercial.supplyOnly,installation:item.commercial.installation,vat:item.commercial.vatGbp,total:item.commercial.totalIncVatGbp,currency:item.commercial.currency} satisfies Partial<CustomerSafeCommercial>]));return <div className="client-portal-staff-workspace"><div className="client-portal-staff-workspace__bar ui-card"><div><span className="ui-eyebrow">Internal staff access · not customer authentication</span><h2>{client.clientName} · {preview.project.name}</h2><p>You are viewing the exact enabled-and-released customer projection. Internal commercial fields remain excluded.</p></div><button className="ui-button" type="button" onClick={()=>{setContext(null);setPreview(null)}}>Back to Portal Directory</button></div><ClientPortalPreview client={client} commercialByEstimateId={commercialByEstimateId} releasedEstimateIds={preview.estimates.map(item=>item.estimateId)} releasedDocumentIds={preview.documents.map(item=>item.id)} enabledFeatures={preview.features.filter(item=>item.enabled).map(item=>item.featureKey)} accessContext={{tenantLabel:preview.access.tenantId,contactName:"Authorised QuoteSuite staff",contactEmail:"Internal preview — not impersonating customer",projectScope:preview.project.name,mode:"internal_preview"}} /></div>}
  return <section className="client-portal-directory" aria-labelledby="portal-directory-title"><header className="ui-card"><div><span className="ui-eyebrow">QuoteSuite internal workspace</span><h2 id="portal-directory-title">Client Portal Directory</h2><p>Search Clients and Projects, inspect access/release status, then open the governed customer presentation.</p></div></header><label>Client or Project search<input className="ui-input" value={search} onChange={event=>setSearch(event.currentTarget.value)} placeholder="Client, EF-CL reference or Project" /></label>{error?<div className="ui-status ui-status--error" role="alert">{error}</div>:null}<div className="client-portal-directory__list">{rows.map(row=><article className="ui-card" key={`${row.clientId}:${row.projectId}`}><div><strong>{row.clientName}</strong><small>{row.clientReference} · {row.projectName}</small></div><div><span className="ui-status ui-status--muted">{row.portalAccessStatus.replaceAll("_"," ")}</span><small>{row.activeContacts} authorised contact(s) · {row.releasedResources} released resource(s)</small></div><button className="ui-button ui-button--primary" type="button" onClick={()=>setContext({clientId:row.clientId,projectId:row.projectId})}>Open Client Portal</button></article>)}</div></section>;
}
