import { useEffect, useMemo, useState } from "react";
import InstallationDocumentsPanel from '../installationSafety/InstallationDocumentsPanel';
import type { Client } from "../../models/types";
import { apiFetch } from "../../services/api/apiClient";
import ClientPortalPreview from "./ClientPortalPreview";
import SupplierReviewHistory, { type SavedSupplierCheck } from "./SupplierReviewHistory";
import FactoryDraftReview from "./FactoryDraftReview";
import SupplierResponseReviews from "./SupplierResponseReviews";
import type { CustomerSafeCommercial } from "./customerSafePortalProjection";
import "./clientPortalPreview.css";

type DirectoryRow={clientId:string;clientReference:string;clientName:string;projectId:string;projectName:string;projectStatus:string;portalAccessStatus:string;activeContacts:number;releasedResources:number};
type SourceDocument={id:string;file_name:string;document_type:string;revision:string|null;modified_at:string|null};
type Preview={access:{tenantId:string;clientId:string;projectId:string;displayName:string;mode:string};features:Array<{featureKey:string;enabled:boolean}>;project:{id:string;name:string;status:string};estimates:Array<{estimateId:string;status:"issued"|"superseded"|"withdrawn";commercial:{supplyOnly:number|null;installation:number|null;vatGbp:number|null;totalIncVatGbp:number|null;currency:string}}> ;orders:Array<{id:string;orderRef:string;status:string}>;documents:Array<{id:string}>};
type ChangeRequest={review_submission_id:string;client_name:string;client_ref:string;project_name:string;amendment_count:number;submitted_at:string;supplier_revision_request_id:string|null;supplier_revision_status:string|null};
type ChangeEntry={estimatePositionId:string;reference:string;response:string;comment:string};
type SupplierRevision={id:string;status:string;recipient:string;subject:string;bodyText:string;successorEstimateId:string;successorEstimateRef?:string;returnedDocumentId:string|null;returnedSourceKind?:"supplier_quote_attachment"|"canonical_document";returnedRevision:string|null;verifiedAt:string|null;supplierDocuments?:Array<{id:string;file_name:string;revision:string|null}>;returnedReviewDocuments?:Array<{id:string;file_name:string;provider_revision:string|null}>};
type ChangeDetail={reviewSubmissionId:string;estimateRevision:number;clientId:string;clientReference:string;clientName:string;projectId:string;projectName:string;generalComment:string;generalResponse:string;submittedAt:string;positions:ChangeEntry[];supplierRevision:SupplierRevision|null;documents:SourceDocument[];checks?:SavedSupplierCheck[]};
type ChangeCheck={estimatePositionId:string|null;fieldKey:string;requestedChange:string;beforeValue:string;expectedValue:string;afterValue:string;beforeSourceReference:string;afterSourceReference:string;resolutionNote:string;approvedDifference:boolean;changeKind:"requested"|"unrelated_material_change";sourceDocumentId?:string};
type ConfirmationCheck={estimatePositionId:string;fieldKey:string;approvedValue:string;confirmedValue:string;approvedSourceReference:string;confirmationSourceReference:string;resolutionNote:string;approvedDifference:boolean};
type OrderJourney={id:string;orderRef:string;status:string;sourceEstimateId:string;sourceEstimateRevision:number;customerProjection:{positions:Array<{id:string;customerReference?:string;reference:string;description?:string;configurationDescription?:string}>};acceptance:{acceptedAt:string;positions:Array<{estimatePositionId:string;reference:string}>};staffApproval:null|{approvedAt:string};factoryOrder:null|{id:string;status:string};documents:SourceDocument[];confirmations:Array<{id:string;revision:string;status:string;releaseId:string|null;signedPdfDocumentId:string|null;checks:Array<Record<string,unknown>>}>};
type Delivery={deliveryMode:string;customerConfigured:boolean;factoryConfigured:boolean};

const postJson=(path:string,body:unknown,method="POST")=>apiFetch(path,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}) as Promise<Record<string,unknown>>;
const label=(value:string)=>value.replaceAll("_"," ");
const emptyCheck=(entry?:ChangeEntry):ChangeCheck=>({estimatePositionId:entry?.estimatePositionId??null,fieldKey:entry?"requested_change":"general_request",requestedChange:entry?.comment??"",beforeValue:"",expectedValue:entry?.comment??"",afterValue:"",beforeSourceReference:"",afterSourceReference:"",resolutionNote:"",approvedDifference:false,changeKind:"requested"});

export function ChangeReview(props:Parameters<typeof ChangeReviewForm>[0]) {
  return <ChangeReviewForm key={props.detail.reviewSubmissionId} {...props}/>;
}

function ChangeReviewForm({detail,reload,onOpenEstimate}:{detail:ChangeDetail;reload:()=>Promise<void>;delivery?:Delivery|null;onOpenEstimate?:(clientId:string,estimateId:string)=>void}){
  const revision=detail.supplierRevision,requested=detail.positions.filter(item=>item.response==="amendment_requested");
  const [sourceKind,setSourceKind]=useState<"supplier_quote_attachment"|"canonical_document">(revision?.returnedSourceKind||"supplier_quote_attachment"),[returnedId,setReturnedId]=useState(revision?.returnedDocumentId||""),[returnedRevision,setReturnedRevision]=useState(revision?.returnedRevision||""),[checks,setChecks]=useState<ChangeCheck[]>(()=>{
    const saved=(detail.checks||[]).map(check=>({estimatePositionId:check.estimate_position_id,fieldKey:check.field_key,requestedChange:check.requested_change,beforeValue:check.before_value||"",expectedValue:check.expected_value||"",afterValue:check.after_value||"",beforeSourceReference:check.before_source_reference||"",afterSourceReference:check.after_source_reference||"",resolutionNote:check.resolution_note||"",approvedDifference:check.status==="approved_difference",changeKind:check.change_kind,sourceDocumentId:check.source_document_id||""}));
    const missing=requested.filter(entry=>!saved.some(check=>check.changeKind==="requested"&&check.estimatePositionId===entry.estimatePositionId)).map(emptyCheck);
    if(detail.generalResponse==="amendment_requested"&&!saved.some(check=>check.changeKind==="requested"&&check.estimatePositionId===null))missing.push({...emptyCheck(),requestedChange:detail.generalComment,expectedValue:detail.generalComment});
    return [...saved,...missing];
  }),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState("");
  const act=async(task:()=>Promise<unknown>,message:string)=>{setBusy(true);setError("");setNotice("Saving and checking the review…");try{const result=await task();if(result&&typeof result==='object'&&'issueAllowed' in result){const review=result as {issueAllowed:boolean;unresolved:number;outstandingSuppliers?:Array<{supplier_name:string}>};const waiting=review.outstandingSuppliers?.map(item=>item.supplier_name).join(', ');setNotice(review.issueAllowed?'Review saved. The working Estimate is ready for customer-document review.':`Review saved. ${review.unresolved} item(s) still need attention before customer issue.${waiting?` Revised documents are outstanding from ${waiting}.`:''}`);}else setNotice(message);await reload()}catch(reason){setNotice("");setError(reason instanceof Error?reason.message:"The action could not be recorded.")}finally{setBusy(false)}};
  const options=sourceKind==="supplier_quote_attachment"?(revision?.supplierDocuments||[]):detail.documents;
  const openWorking=async()=>{
    if(!revision||!onOpenEstimate||busy)return;
    setBusy(true);setError("");setNotice("Opening working Estimate…");
    try{await onOpenEstimate(detail.clientId,revision.successorEstimateId);setNotice("Working Estimate opened.")}
    catch(reason){setNotice("");setError(reason instanceof Error?reason.message:"The working Estimate could not be opened. Your revision is retained; try again.")}
    finally{setBusy(false)}
  };
  const update=(index:number,patch:Partial<ChangeCheck>)=>setChecks(current=>current.map((item,i)=>i===index?{...item,...patch}:item));
  return <section className="portal-operation-detail ui-card"><header><div><span className="ui-eyebrow">Immutable customer review · staff action required</span><h3>{detail.clientName} · {detail.projectName}</h3><p>{detail.clientReference} · issued revision {detail.estimateRevision} · {new Date(detail.submittedAt).toLocaleString("en-GB")}</p></div></header>
    {detail.generalComment?<p className="ui-status ui-status--warning"><strong>{detail.generalResponse==="amendment_requested"?"General change":"General comment"}</strong> · {detail.generalComment}</p>:null}
    <div className="portal-operation-detail__requests">{detail.positions.map(item=><article key={item.estimatePositionId}><strong>{item.reference}</strong><span className={`ui-status ${item.response==="amendment_requested"?"ui-status--warning":"ui-status--muted"}`}>{label(item.response)}</span><p>{item.comment||"No comment supplied."}</p></article>)}</div>
    {!revision?<button className="ui-button ui-button--primary" disabled={busy} onClick={()=>void act(()=>postJson(`/api/lifecycle/changes-requested/${detail.reviewSubmissionId}/supplier-revision`,{}),"Working revision created. The issued Estimate remains unchanged.")}>{busy?"Creating working revision…":"Create working revision"}</button>:<>
      <div className="portal-operation-detail__stage"><div><span className="ui-eyebrow">Working Estimate</span><h4>{revision.successorEstimateRef||"Working revision"}</h4><p>The issued Position and Project Costing snapshot were carried forward.</p></div>{onOpenEstimate?<button className="ui-button" disabled={busy} onClick={()=>void openWorking()}>Open working Estimate · import supplier revision</button>:null}</div>
      <p className="ui-status">Open the working Estimate and use <strong>Request supplier estimate / revision</strong> to prepare, reopen or send the single tracked supplier request. Creating this working Estimate did not send an Email.</p>
      <SupplierResponseReviews requestId={revision.id} positions={detail.positions} onSaved={reload}/>
      <fieldset><legend>Returned manufacturer revision</legend><div className="portal-operation-detail__fields"><label>Source<select className="ui-select" value={sourceKind} onChange={event=>{setSourceKind(event.currentTarget.value as typeof sourceKind);setReturnedId("")}}><option value="supplier_quote_attachment">Imported manufacturer quotation</option><option value="canonical_document">Canonical Project file</option></select></label><label>Reviewed document<select className="ui-select" value={returnedId} onChange={event=>{setReturnedId(event.currentTarget.value);setReturnedRevision(options.find(item=>item.id===event.currentTarget.value)?.revision||"")}}><option value="">Choose source evidence</option>{options.map(item=><option key={item.id} value={item.id}>{item.file_name} · {item.revision||"current"}</option>)}</select></label><label>Revision<input className="ui-input" value={returnedRevision} onChange={event=>setReturnedRevision(event.currentTarget.value)}/></label></div><button className="ui-button" disabled={busy||!returnedId} onClick={()=>void act(()=>postJson(`/api/lifecycle/supplier-revisions/${revision.id}/returned-document`,sourceKind==="supplier_quote_attachment"?{sourceKind,supplierQuoteAttachmentId:returnedId,revision:returnedRevision}:{sourceKind,canonicalDocumentId:returnedId,revision:returnedRevision}),"Returned supplier revision linked.")}>Link returned revision</button>{revision.returnedDocumentId?<span className="ui-status">Linked · {revision.returnedRevision}</span>:null}</fieldset>
      {revision.returnedDocumentId ? <fieldset>
        <legend>Requested-change verification</legend>
        <p>Use exact before/after source references. Unrelated material changes must be added and resolved before reissue.</p>
        {(revision.returnedReviewDocuments?.length||0)>1||checks.some(check=>check.sourceDocumentId)?<div className="portal-operation-detail__fields"><p>Choose the returned document supporting each field; selecting a document does not confirm the change.</p>{checks.map((check,index)=><label key={`source:${index}`}>{check.estimatePositionId?requested.find(item=>item.estimatePositionId===check.estimatePositionId)?.reference||"Position":"General"} · {check.fieldKey} · returned document<select className="ui-select" disabled={busy} value={check.sourceDocumentId||""} onChange={event=>update(index,{sourceDocumentId:event.currentTarget.value})}><option value="">Choose this field's source</option>{check.sourceDocumentId&&!revision.returnedReviewDocuments?.some(document=>document.id===check.sourceDocumentId)?<option value={check.sourceDocumentId}>Previous source unavailable — choose a retained document</option>:null}{revision.returnedReviewDocuments?.map(document=><option key={document.id} value={document.id}>{document.file_name} · {document.provider_revision||"version not recorded"}</option>)}</select></label>)}</div>:null}
        {!revision.verifiedAt&&detail.checks?.length?<p className="ui-status ui-status--warning">Saved checks are shown for reference. Review every field against the linked supplier document before verifying again.</p>:null}
        {checks.map((check,index)=><article className="portal-operation-detail__check" key={`${check.changeKind}:${index}`}><div className="portal-operation-detail__fields"><label>Position<input className="ui-input" value={check.estimatePositionId?requested.find(item=>item.estimatePositionId===check.estimatePositionId)?.reference||check.estimatePositionId:"General"} readOnly/></label><label>Field<input className="ui-input" value={check.fieldKey} onChange={event=>update(index,{fieldKey:event.currentTarget.value})}/></label><label>Before<input className="ui-input" value={check.beforeValue} onChange={event=>update(index,{beforeValue:event.currentTarget.value})}/></label><label>Requested<input className="ui-input" value={check.expectedValue} onChange={event=>update(index,{expectedValue:event.currentTarget.value})}/></label><label>After<input className="ui-input" value={check.afterValue} onChange={event=>update(index,{afterValue:event.currentTarget.value})}/></label><label>Before source<input className="ui-input" value={check.beforeSourceReference} onChange={event=>update(index,{beforeSourceReference:event.currentTarget.value})}/></label><label>After source<input className="ui-input" value={check.afterSourceReference} onChange={event=>update(index,{afterSourceReference:event.currentTarget.value})}/></label><label>Resolution note<input className="ui-input" value={check.resolutionNote} onChange={event=>update(index,{resolutionNote:event.currentTarget.value})}/></label></div><label><input type="checkbox" checked={check.approvedDifference} onChange={event=>update(index,{approvedDifference:event.currentTarget.checked})}/> Approve this evidenced difference with the resolution note.</label>{check.changeKind==="unrelated_material_change"?<button className="ui-button ui-button--ghost" onClick={()=>setChecks(current=>current.filter((_,i)=>i!==index))}>Remove</button>:null}</article>)}
        <div className="ui-action-row"><button className="ui-button" onClick={()=>setChecks(current=>[...current,{...emptyCheck(),requestedChange:"Unrelated material change",changeKind:"unrelated_material_change"}])}>Add unrelated material change</button><button className="ui-button ui-button--primary" disabled={busy||checks.some(check=>!check.fieldKey||!check.afterValue||!check.afterSourceReference)} onClick={()=>void act(()=>postJson(`/api/lifecycle/supplier-revisions/${revision.id}/verification`,{checks:checks.filter(item=>item.changeKind==="requested"),unrelatedChanges:checks.filter(item=>item.changeKind==="unrelated_material_change")},"PUT"),"Revision verified; unresolved evidence remains fail-closed.")}>Verify changes</button></div>
        {revision.verifiedAt?<span className="ui-status">Verified · successor Estimate can be reviewed and issued</span>:null}
      </fieldset>:null}
      <SupplierReviewHistory key={revision.id} requestId={revision.id}/>
    </>}{notice?<p className="ui-status" role="status">{notice}</p>:null}{error?<p className="ui-status ui-status--error" role="alert">{error}</p>:null}
  </section>;
}

export function OrderJourneyPanel({orderId,reloadPortal,delivery}:{orderId:string;reloadPortal:()=>Promise<void>;delivery:Delivery|null}){
  const [journey,setJourney]=useState<OrderJourney|null>(null),[factoryEmail,setFactoryEmail]=useState(""),[documentId,setDocumentId]=useState(""),[revision,setRevision]=useState(""),[checks,setChecks]=useState<ConfirmationCheck[]>([]),[signedDocumentId,setSignedDocumentId]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState("");
  const load=async()=>{const next=await apiFetch(`/api/lifecycle/orders/${orderId}`) as OrderJourney;setJourney(next);setChecks(current=>current.length?current:next.acceptance.positions.map(position=>{const source=next.customerProjection.positions.find(item=>item.id===position.estimatePositionId||item.customerReference===position.reference||item.reference===position.reference);return{estimatePositionId:position.estimatePositionId,fieldKey:"complete_position",approvedValue:[source?.description,source?.configurationDescription].filter(Boolean).join(" · "),confirmedValue:"",approvedSourceReference:`Issued Estimate · ${position.reference}`,confirmationSourceReference:"",resolutionNote:"",approvedDifference:false}}))};
  useEffect(()=>{void load().catch(reason=>setError(reason instanceof Error?reason.message:"Order could not be loaded."))},[orderId]); // eslint-disable-line react-hooks/exhaustive-deps
  const act=async(task:()=>Promise<unknown>,message:string)=>{setBusy(true);setError("");try{await task();setNotice(message);await load();await reloadPortal()}catch(reason){setError(reason instanceof Error?reason.message:"The Order action failed.")}finally{setBusy(false)}};
  if(!journey)return <div className="ui-empty-state">{error?<><p role="alert">{error}</p><button className="ui-button" onClick={()=>{setError('');void load().catch(reason=>setError(reason instanceof Error?reason.message:'Order could not be loaded.'));}}>Retry loading Order</button></>:'Loading Order journey…'}</div>;const current=journey.confirmations[0]||null,positionIds=journey.acceptance.positions.map(item=>item.estimatePositionId);
  return <section className="portal-operation-detail ui-card"><header><div><span className="ui-eyebrow">Governed Order journey</span><h3>{journey.orderRef}</h3><p>Accepted Estimate revision {journey.sourceEstimateRevision} · {label(journey.status)}</p></div></header><div className="portal-operation-detail__milestones"><span className="ui-status">Customer accepted</span><span className={`ui-status ${journey.staffApproval?"":"ui-status--warning"}`}>Staff approval · {journey.staffApproval?"complete":"required"}</span><span className={`ui-status ${journey.factoryOrder?"":"ui-status--warning"}`}>Factory Order · {journey.factoryOrder?(journey.factoryOrder.status==="sent"?"sent":"prepared, not sent"):"not prepared"}</span><span className={`ui-status ${current?"":"ui-status--warning"}`}>Confirmation · {current?label(current.status):"not received"}</span></div>
    <InstallationDocumentsPanel key={journey.id} estimateId={journey.sourceEstimateId} selectedOrderId={journey.id}/>
    {!journey.staffApproval?<button className="ui-button ui-button--primary" disabled={busy} onClick={()=>void act(()=>postJson(`/api/lifecycle/orders/${journey.id}/staff-approval`,{note:"Accepted Estimate and Position evidence reviewed."}),"Order approved and immutable staff-approved Order PDF created.")}>{busy?"Approving Order…":"Approve Order for factory"}</button>:null}
    {journey.staffApproval&&!journey.factoryOrder?<fieldset><legend>Factory Order</legend><label>Factory test address<input className="ui-input" type="email" value={factoryEmail} onChange={event=>setFactoryEmail(event.currentTarget.value)}/></label><p>Prepare first, then review the saved message and files before sending.</p><button className="ui-button ui-button--primary" disabled={busy||!factoryEmail} onClick={()=>void act(()=>postJson(`/api/lifecycle/orders/${journey.id}/factory-order`,{recipient:factoryEmail,subject:`TEST Factory Order ${journey.orderRef}`,bodyText:"Please review the attached staff-approved Order and return your confirmation.",send:false}),"Factory Order email and PDF prepared. Nothing was sent.")}>{busy?"Preparing factory Order…":"Prepare factory Order preview"}</button></fieldset>:null}
    {journey.factoryOrder?<FactoryDraftReview orderId={journey.id} onChanged={async()=>{await load();await reloadPortal()}}/>:null}
    {journey.factoryOrder?<fieldset>
      <legend>Returned factory confirmation</legend>
      <div className="portal-operation-detail__fields"><label>Canonical returned file<select className="ui-select" value={documentId} onChange={event=>setDocumentId(event.currentTarget.value)}><option value="">Choose Project file</option>{journey.documents.map(document=><option key={document.id} value={document.id}>{document.file_name}</option>)}</select></label><label>Revision<input className="ui-input" value={revision} onChange={event=>setRevision(event.currentTarget.value)}/></label></div>
      {checks.map((check,index)=><article className="portal-operation-detail__check" key={check.estimatePositionId}>
        <strong>{journey.acceptance.positions.find(item=>item.estimatePositionId===check.estimatePositionId)?.reference}</strong>
        <div className="portal-operation-detail__fields"><label>Approved<textarea className="ui-textarea" rows={2} value={check.approvedValue} readOnly/></label><label>Confirmed<textarea className="ui-textarea" rows={2} value={check.confirmedValue} onChange={event=>setChecks(currentChecks=>currentChecks.map((item,i)=>i===index?{...item,confirmedValue:event.currentTarget.value}:item))}/></label><label>Source reference<input className="ui-input" value={check.confirmationSourceReference} onChange={event=>setChecks(currentChecks=>currentChecks.map((item,i)=>i===index?{...item,confirmationSourceReference:event.currentTarget.value}:item))}/></label><label>Resolution note<input className="ui-input" value={check.resolutionNote} onChange={event=>setChecks(currentChecks=>currentChecks.map((item,i)=>i===index?{...item,resolutionNote:event.currentTarget.value}:item))}/></label></div>
        <label><input type="checkbox" checked={check.approvedDifference} onChange={event=>setChecks(currentChecks=>currentChecks.map((item,i)=>i===index?{...item,approvedDifference:event.currentTarget.checked}:item))}/> Accept this evidenced factory difference after staff review.</label>
      </article>)}
      <button className="ui-button ui-button--primary" disabled={busy||!documentId||!revision||checks.some(check=>!check.confirmedValue||!check.confirmationSourceReference||(check.confirmedValue!==check.approvedValue&&(!check.approvedDifference||!check.resolutionNote)))} onClick={()=>void act(()=>postJson(`/api/lifecycle/orders/${journey.id}/factory-confirmations`,{canonicalDocumentId:documentId,revision,checks}),"Factory confirmation compared against every accepted Position.")}>{busy?"Checking confirmation…":"Record and compare confirmation"}</button>
      {current?.checks?.length?<div className="portal-operation-detail__results">{current.checks.map((check,index)=><p className={`ui-status ${String(check.status).includes("review")||String(check.status).includes("change_detected")?"ui-status--warning":""}`} key={index}>{String(check.field_key||"Position")} · {label(String(check.status))}</p>)}</div>:null}
    </fieldset>:null}
    {current?.status==="review_resolved"&&!current.releaseId?<button className="ui-button ui-button--primary" disabled={busy} onClick={()=>void act(()=>postJson(`/api/lifecycle/factory-confirmations/${current.id}/release`,{}),"Reviewed confirmation and final-confirmation PDF released to customer.")}>{busy?"Releasing final confirmation…":"Release final confirmation"}</button>:null}
    {current?.releaseId&&!current.signedPdfDocumentId?<fieldset><legend>Reviewed signed-PDF return</legend><p>Upload the signed PDF to Project Files first. Upload alone is not approval.</p><label>Signed PDF<select className="ui-select" value={signedDocumentId} onChange={event=>setSignedDocumentId(event.currentTarget.value)}><option value="">Choose signed PDF</option>{journey.documents.filter(item=>/pdf/i.test(item.file_name)).map(item=><option key={item.id} value={item.id}>{item.file_name}</option>)}</select></label><button className="ui-button ui-button--primary" disabled={busy||!signedDocumentId} onClick={()=>void act(()=>postJson(`/api/lifecycle/factory-confirmation-releases/${current.releaseId}/signed-approval`,{signedPdfDocumentId:signedDocumentId,reviewed:true,overallApproved:true,positionIds}),"Signed PDF reviewed against all Positions and recorded.")}>{busy?"Recording signed approval…":"Record reviewed signed approval"}</button></fieldset>:null}
    {notice?<p className="ui-status">{notice}</p>:null}{error?<p className="ui-status ui-status--error">{error}</p>:null}</section>;
}

export default function ClientPortalStaffWorkspace({clients,initialClientId=null,initialProjectId=null,onContextConsumed,onOpenEstimate}:{clients:Client[];initialClientId?:string|null;initialProjectId?:string|null;onContextConsumed?:()=>void;onOpenEstimate?:(clientId:string,estimateId:string)=>void}){
  const [search,setSearch]=useState(""),[rows,setRows]=useState<DirectoryRow[]>([]),[context,setContext]=useState<{clientId:string;projectId:string}|null>(initialClientId&&initialProjectId?{clientId:initialClientId,projectId:initialProjectId}:null),[preview,setPreview]=useState<Preview|null>(null),[changes,setChanges]=useState<ChangeRequest[]>([]),[changeId,setChangeId]=useState(""),[detail,setDetail]=useState<ChangeDetail|null>(null),[orderId,setOrderId]=useState(""),[inviteEmail,setInviteEmail]=useState(""),[delivery,setDelivery]=useState<Delivery|null>(null),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const loadPreview=async()=>{if(context)setPreview(await apiFetch(`/api/client-portal/internal/clients/${context.clientId}/projects/${context.projectId}/preview`) as Preview)};const loadChanges=async()=>setChanges(await apiFetch("/api/lifecycle/changes-requested") as ChangeRequest[]);const loadDetail=async()=>{if(changeId)setDetail(await apiFetch(`/api/lifecycle/changes-requested/${changeId}`) as ChangeDetail)};
  useEffect(()=>{if(initialClientId&&initialProjectId){setContext({clientId:initialClientId,projectId:initialProjectId});onContextConsumed?.()}},[initialClientId,initialProjectId,onContextConsumed]);
  useEffect(()=>{void apiFetch(`/api/client-portal/internal/directory?search=${encodeURIComponent(search)}`).then(value=>setRows(value as DirectoryRow[])).catch(reason=>setError(reason instanceof Error?reason.message:"Directory unavailable."))},[search]);
  useEffect(()=>{void loadPreview().catch(reason=>setError(reason instanceof Error?reason.message:"Portal preview unavailable."))},[context]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{void loadChanges();void apiFetch("/api/lifecycle/test-delivery").then(value=>setDelivery(value as Delivery))},[notice]);
  useEffect(()=>{const open=(event:Event)=>{const id=String((event as CustomEvent<{id?:string}>).detail?.id||"");if(id)setChangeId(id)};window.addEventListener("quotesuite:open-revision-request",open);return()=>window.removeEventListener("quotesuite:open-revision-request",open)},[]);
  useEffect(()=>{void loadDetail()},[changeId]); // eslint-disable-line react-hooks/exhaustive-deps
  const client=useMemo(()=>context?clients.find(item=>String(item.id)===context.clientId)||null:null,[clients,context]);
  const invite=async()=>{setBusy(true);try{const value=await postJson("/api/client-portal/internal/invitations",{clientId:context?.clientId,projectId:context?.projectId,email:inviteEmail});setNotice(`Customer-session link: ${location.origin}/#/client-portal?token=${encodeURIComponent(String(value.token))}`)}catch(reason){setError(reason instanceof Error?reason.message:"Invitation failed.")}finally{setBusy(false)}};
  if(context&&client&&preview){const commercial=Object.fromEntries(preview.estimates.map(item=>[item.estimateId,{supplyOnly:item.commercial.supplyOnly,installation:item.commercial.installation,vat:item.commercial.vatGbp,total:item.commercial.totalIncVatGbp,currency:item.commercial.currency} satisfies Partial<CustomerSafeCommercial>])),estimateLifecycle=Object.fromEntries(preview.estimates.map(item=>[item.estimateId,item.status]));return <div className="client-portal-staff-workspace"><div className="client-portal-staff-workspace__bar ui-card"><div><span className="ui-eyebrow">Internal staff access · not customer authentication</span><h2>{client.clientName} · {preview.project.name}</h2><p>Exact enabled-and-released customer projection; internal fields stay excluded.</p></div><button className="ui-button" onClick={()=>{setContext(null);setPreview(null)}}>Back to directory</button></div>{delivery?<p className={`ui-status ${delivery.deliveryMode==="preview_only"?"ui-status--warning":""}`}>Test delivery {label(delivery.deliveryMode)} · customer {delivery.customerConfigured?"configured":"address required"} · factory {delivery.factoryConfigured?"configured":"address required"}</p>:null}<section className="ui-card"><h3>Portal invitation</h3><div className="ui-action-row"><input className="ui-input" type="email" value={inviteEmail} onChange={event=>setInviteEmail(event.currentTarget.value)} placeholder="Configured test customer email"/><button className="ui-button ui-button--primary" disabled={busy||!inviteEmail} onClick={()=>void invite()}>Create customer-session invitation</button></div></section>{notice?<p className="ui-status">{notice}</p>:null}{preview.orders.map(order=><article className="ui-card" key={order.id}><h3>{order.orderRef}</h3><p>{label(order.status)}</p><button className="ui-button ui-button--primary" onClick={()=>setOrderId(order.id)}>Open Order journey</button></article>)}{orderId?<OrderJourneyPanel orderId={orderId} reloadPortal={loadPreview} delivery={delivery}/>:null}<ClientPortalPreview client={client} commercialByEstimateId={commercial} releasedEstimateIds={preview.estimates.map(item=>item.estimateId)} estimateLifecycleById={estimateLifecycle} releasedDocumentIds={preview.documents.map(item=>item.id)} enabledFeatures={preview.features.filter(item=>item.enabled).map(item=>item.featureKey)} accessContext={{tenantLabel:preview.access.tenantId,contactName:"Authorised QuoteSuite staff",contactEmail:"Internal preview — not impersonating customer",projectScope:preview.project.name,mode:"internal_preview"}} /></div>}
  return <section className="client-portal-directory"><header className="ui-card"><span className="ui-eyebrow">QuoteSuite internal workspace</span><h2>Client Portal Directory</h2><p>Open customer context or work the Changes Requested queue.</p></header><label>Client or Project search<input className="ui-input" value={search} onChange={event=>setSearch(event.currentTarget.value)}/></label>{error?<p className="ui-status ui-status--error">{error}</p>:null}{changes.length?<section className="client-portal-directory__changes ui-card"><h3>Changes Requested</h3>{changes.map(item=><article key={item.review_submission_id}><div><strong>{item.client_name} · {item.project_name}</strong><small>{item.client_ref} · {item.amendment_count} Position change(s)</small></div><span className="ui-status ui-status--warning">{item.supplier_revision_status||"staff review required"}</span><button className="ui-button ui-button--primary" onClick={()=>setChangeId(item.review_submission_id)}>Review changes</button></article>)}</section>:null}{detail?<ChangeReview detail={detail} reload={async()=>{await loadDetail();await loadChanges()}} delivery={delivery} onOpenEstimate={onOpenEstimate}/>:null}<div className="client-portal-directory__list">{rows.map(row=><article className="ui-card" key={`${row.clientId}:${row.projectId}`}><div><strong>{row.clientName}</strong><small>{row.clientReference} · {row.projectName}</small></div><span className="ui-status ui-status--muted">{label(row.portalAccessStatus)}</span><button className="ui-button ui-button--primary" onClick={()=>setContext({clientId:row.clientId,projectId:row.projectId})}>Open Client Portal</button></article>)}</div></section>;
}
