import { useEffect, useMemo, useState } from "react";
import type { Client } from "../../models/types";
import { documentRecordsApi, type CanonicalDocumentRecord } from "../../services/documents/documentRecordsApi";
import { buildCustomerSafePortalProjection, type CustomerSafeCommercial } from "./customerSafePortalProjection";
import "./clientPortalPreview.css";

type PortalTab="dashboard"|"estimates"|"orders"|"rejected"|"documents";
type PreviewCommand="review"|"decline"|"proceed"|null;
export type PortalPreviewAccessContext={tenantLabel:string;contactName:string;contactEmail:string;projectScope:string;mode:"internal_preview"|"deterministic_test_adapter"};

const tabs:Array<{id:PortalTab;label:string}>=[{id:"dashboard",label:"Dashboard"},{id:"estimates",label:"Estimates"},{id:"orders",label:"Orders"},{id:"rejected",label:"Rejected"},{id:"documents",label:"Documents"}];
const money=(value:number|null,currency:string)=>value==null?"Not available":new Intl.NumberFormat("en-GB",{style:"currency",currency}).format(value);

export default function ClientPortalPreview({client,commercialByEstimateId={},releasedEstimateIds=[],orderEstimateIds=[],rejectedEstimateIds=[],releasedDocumentIds=[],enabledFeatures,accessContext}:{client:Client;commercialByEstimateId?:Record<string,Partial<CustomerSafeCommercial>>;releasedEstimateIds?:string[];orderEstimateIds?:string[];rejectedEstimateIds?:string[];releasedDocumentIds?:string[];enabledFeatures?:string[];accessContext?:PortalPreviewAccessContext}){
  const [tab,setTab]=useState<PortalTab>("dashboard"),[documents,setDocuments]=useState<CanonicalDocumentRecord[]>([]),[error,setError]=useState(""),[command,setCommand]=useState<PreviewCommand>(null);
  useEffect(()=>{let active=true;documentRecordsApi.listClient(String(client.id)).then((result)=>{if(active)setDocuments(result.documents)}).catch((reason)=>{if(active)setError(reason instanceof Error?reason.message:"Customer-safe documents could not be loaded.")});return()=>{active=false}},[client.id]);
  const projection=useMemo(()=>buildCustomerSafePortalProjection({client,documents,commercialByEstimateId,releasedEstimateIds,orderEstimateIds,rejectedEstimateIds,releasedDocumentIds}),[client,commercialByEstimateId,documents,releasedEstimateIds,orderEstimateIds,rejectedEstimateIds,releasedDocumentIds]);
  const featureEnabled=(feature:string)=>enabledFeatures===undefined||enabledFeatures.includes(feature);
  const visibleTabs=tabs.filter((item)=>featureEnabled(item.id));
  useEffect(()=>{if(!visibleTabs.some((item)=>item.id===tab))setTab(visibleTabs[0]?.id??"dashboard")},[enabledFeatures,tab,visibleTabs]);
  const context=accessContext||{tenantLabel:"Authorised tenant context pending",contactName:client.contactPerson||client.clientName,contactEmail:client.email,projectScope:client.projectName||"Project scope pending",mode:"internal_preview" as const};
  const estimateList=(items:typeof projection.estimates,empty:string)=><div className="client-portal-preview__list">{items.length?items.map((estimate)=><article className="ui-card" key={estimate.id}><div><strong>{estimate.estimateRef}</strong><small>Revision {estimate.revisionNo} · {estimate.status.replaceAll("_"," ")}</small></div><strong>{money(estimate.commercial.total,estimate.commercial.currency)}</strong><button type="button" className="ui-button ui-button--ghost" onClick={()=>setCommand("review")}>Review Estimate</button></article>):<div className="ui-empty-state">{empty}</div>}</div>;
  return <section className="client-portal-preview" aria-labelledby="portal-preview-title">
    <header className="client-portal-preview__notice ui-status ui-status--warning"><strong>Internal portal preview</strong><span>External access is blocked. This view demonstrates released-resource and command contracts; it is not production authentication.</span></header>
    <section className="client-portal-preview__identity ui-card" aria-label="Portal access context"><header><span className="ui-eyebrow">{context.mode==="deterministic_test_adapter"?"Deterministic security adapter":"Authorised context preview"}</span><span className="ui-status ui-status--muted">Project-scoped</span></header><div className="client-portal-preview__identity-grid"><div><span>Tenant / company</span><strong>{context.tenantLabel}</strong></div><div><span>Authenticated contact</span><strong>{context.contactName}</strong><small>{context.contactEmail}</small></div><div><span>Resource scope</span><strong>{context.projectScope}</strong><small>No Client-wide implicit access</small></div></div></section>
    <div className="client-portal-preview__shell">
      <header><div><span className="ui-eyebrow">Customer view · {projection.client.reference}</span><h2 id="portal-preview-title">{projection.client.projectName||projection.client.displayName}</h2></div><span className="ui-status ui-status--muted">{projection.currentStatus}</span></header>
      <nav className="client-portal-preview__tabs" aria-label="Portal areas">{visibleTabs.map((item)=><button key={item.id} type="button" className={tab===item.id?"ui-button ui-button--primary":"ui-button ui-button--ghost"} aria-current={tab===item.id?"page":undefined} onClick={()=>setTab(item.id)}>{item.label}</button>)}</nav>
      {error?<div className="ui-status ui-status--error" role="alert">{error}</div>:null}
      {tab==="dashboard"?<div className="client-portal-preview__dashboard"><section className="client-portal-preview__hero ui-card"><span>Current next step</span><h3>{projection.nextAction||"Your project is being prepared"}</h3><p>The latest released information remains prominent. Internal supplier evidence and commercial diagnostics are excluded by the server projection contract.</p></section>{projection.latestEstimate?<section className="client-portal-preview__latest"><div><span className="ui-eyebrow">Latest issued Estimate</span><h3>{projection.latestEstimate.estimateRef} · Revision {projection.latestEstimate.revisionNo}</h3><small>Immutable customer offer · changes require a new revision</small></div><div className="client-portal-preview__costs">{[["Supply Only",projection.latestEstimate.commercial.supplyOnly],["Installation",projection.latestEstimate.commercial.installation],["VAT",projection.latestEstimate.commercial.vat],["Total",projection.latestEstimate.commercial.total]].map(([label,value])=><article className="ui-card" key={String(label)}><span>{label}</span><strong>{money(value as number|null,projection.latestEstimate!.commercial.currency)}</strong></article>)}</div><div className="ui-action-row">{featureEnabled("review_estimate")?<button className="ui-button ui-button--primary" type="button" onClick={()=>setCommand("review")}>Review Estimate</button>:null}{featureEnabled("intent_to_proceed")?<button className="ui-button ui-button--ghost" type="button" onClick={()=>setCommand("proceed")}>Raise Order / Proceed</button>:null}{featureEnabled("decline_estimate")?<button className="ui-button ui-button--danger" type="button" onClick={()=>setCommand("decline")}>Decline Estimate</button>:null}</div></section>:<div className="ui-empty-state">No customer Estimate has been released yet.</div>}</div>:null}
      {tab==="estimates"?estimateList(projection.estimates,"No released Estimates are available."):null}
      {tab==="orders"?estimateList(projection.orders,"No accepted Orders yet."):null}
      {tab==="rejected"?estimateList(projection.rejected,"No rejected Estimates."):null}
      {tab==="documents"?<div className="client-portal-preview__list">{projection.documents.length?projection.documents.map((document)=><article className="ui-card" key={document.id}><div><strong>{document.fileName}</strong><small>{document.documentType.replaceAll("_"," ")} · {document.revision}</small></div><span>{new Date(document.modifiedAt).toLocaleDateString("en-GB")}</span>{document.openUrl?<a className="ui-button ui-button--ghost" href={document.openUrl}>Open</a>:<span className="ui-status ui-status--muted">Evidence retained</span>}</article>):<div className="ui-empty-state">No approved Project documents are available.</div>}</div>:null}
      {command?<section className="client-portal-preview__command ui-card" aria-live="polite" data-portal-command={command}><header><div><span className="ui-eyebrow">Customer command foundation</span><h3>{command==="review"?"Review issued Estimate":command==="decline"?"Decline issued Estimate":"Intent to proceed"}</h3></div><button className="ui-button ui-button--ghost" type="button" onClick={()=>setCommand(null)}>Close</button></header>{command==="review"?<><p>Position responses and comments are recorded against this immutable issued revision. They never edit the offered Position data.</p><label>Review note<textarea className="ui-textarea" rows={3} placeholder="Demonstration only — submitted evidence requires an authenticated, authorised command." /></label></>:command==="decline"?<><p>Decline preserves the issued Estimate and its history.</p><label>Reason<select className="ui-select" defaultValue=""><option value="" disabled>Please select</option><option>Cost</option><option>Confidence</option><option>Chose Another Supplier</option><option>Other</option></select></label></>:<p>Raise Order records “I wish to proceed”. It does not create or send an irreversible supplier purchase order.</p>}<div className="ui-action-row"><button className="ui-button ui-button--primary" type="button" disabled>Submit through authenticated command</button><span className="ui-status ui-status--warning">Disabled in internal preview</span></div></section>:null}
    </div>
  </section>;
}
