import { useEffect, useMemo, useState } from "react";
import type { Client } from "../../models/types";
import { apiFetch } from "../../services/api/apiClient";
import ClientPortalPreview from "./ClientPortalPreview";
import type { CustomerSafeCommercial } from "./customerSafePortalProjection";
import "./clientPortalPreview.css";

type DirectoryRow={clientId:string;clientReference:string;clientName:string;projectId:string;projectName:string;projectStatus:string;portalAccessStatus:string;activeContacts:number;releasedResources:number};
type Preview={access:{tenantId:string;clientId:string;projectId:string;displayName:string;mode:string};features:Array<{featureKey:string;enabled:boolean}>;project:{id:string;name:string;status:string};estimates:Array<{estimateId:string;commercial:{supplyOnly:number|null;installation:number|null;vatGbp:number|null;totalIncVatGbp:number|null;currency:string}}> ;orders:Array<{id:string;orderRef:string;status:string}>;documents:Array<{id:string}>};
type ChangeRequest={review_submission_id:string;client_name:string;client_ref:string;project_name:string;amendment_count:number;submitted_at:string;supplier_revision_request_id:string|null;supplier_revision_status:string|null};

export default function ClientPortalStaffWorkspace({clients,initialClientId=null,initialProjectId=null,onContextConsumed}:{clients:Client[];initialClientId?:string|null;initialProjectId?:string|null;onContextConsumed?:()=>void}){
  const [search,setSearch]=useState(""),[rows,setRows]=useState<DirectoryRow[]>([]),[context,setContext]=useState<{clientId:string;projectId:string}|null>(initialClientId&&initialProjectId?{clientId:initialClientId,projectId:initialProjectId}:null),[preview,setPreview]=useState<Preview|null>(null),[changes,setChanges]=useState<ChangeRequest[]>([]),[inviteEmail,setInviteEmail]=useState(""),[factoryEmail,setFactoryEmail]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{if(initialClientId&&initialProjectId){setContext({clientId:initialClientId,projectId:initialProjectId});onContextConsumed?.()}},[initialClientId,initialProjectId,onContextConsumed]);
  useEffect(()=>{let active=true;apiFetch(`/api/client-portal/internal/directory?search=${encodeURIComponent(search)}`).then(value=>{if(active)setRows(value as DirectoryRow[])}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"Client Portal directory could not be loaded.")});return()=>{active=false}},[search]);
  useEffect(()=>{if(!context){setPreview(null);return}let active=true;apiFetch(`/api/client-portal/internal/clients/${encodeURIComponent(context.clientId)}/projects/${encodeURIComponent(context.projectId)}/preview`).then(value=>{if(active){setPreview(value as Preview);setError("")}}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"Authorised internal portal preview could not be loaded.")});return()=>{active=false}},[context]);
  useEffect(()=>{let active=true;apiFetch("/api/lifecycle/changes-requested").then(value=>{if(active)setChanges(value as ChangeRequest[])}).catch(()=>{});return()=>{active=false}},[notice]);
  const client=useMemo(()=>context?clients.find(item=>String(item.id)===context.clientId)||null:null,[clients,context]);
  const mutate=async(path:string,body:unknown)=>{setBusy(true);setError("");try{const value=await apiFetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}) as Record<string,unknown>;setNotice(String(value.message||value.status||"Recorded safely."));if(context)setPreview(await apiFetch(`/api/client-portal/internal/clients/${encodeURIComponent(context.clientId)}/projects/${encodeURIComponent(context.projectId)}/preview`) as Preview);return value}catch(reason){setError(reason instanceof Error?reason.message:"The governed action could not be recorded.");return null}finally{setBusy(false)}};

  if(context&&client&&preview){
    const commercialByEstimateId=Object.fromEntries(preview.estimates.map(item=>[item.estimateId,{supplyOnly:item.commercial.supplyOnly,installation:item.commercial.installation,vat:item.commercial.vatGbp,total:item.commercial.totalIncVatGbp,currency:item.commercial.currency} satisfies Partial<CustomerSafeCommercial>]));
    return <div className="client-portal-staff-workspace">
      <div className="client-portal-staff-workspace__bar ui-card"><div><span className="ui-eyebrow">Internal staff access · not customer authentication</span><h2>{client.clientName} · {preview.project.name}</h2><p>You are viewing the exact enabled-and-released customer projection. Internal commercial fields remain excluded.</p></div><button className="ui-button" type="button" onClick={()=>{setContext(null);setPreview(null)}}>Back to Portal Directory</button></div>
      {notice?<div className="ui-status" role="status">{notice}</div>:null}{error?<div className="ui-status ui-status--error" role="alert">{error}</div>:null}
      <section className="client-portal-staff-workspace__operations ui-card"><header><div><span className="ui-eyebrow">Controlled customer access</span><h3>Portal invitation</h3><p>Creates a hashed, expiring invitation for this exact Client and Project. Test mode restricts the address to the configured customer allowlist.</p></div></header><div className="ui-action-row"><input className="ui-input" type="email" value={inviteEmail} onChange={event=>setInviteEmail(event.currentTarget.value)} placeholder="Configured test customer email"/><button className="ui-button ui-button--primary" disabled={busy||!inviteEmail} onClick={()=>void mutate("/api/client-portal/internal/invitations",{clientId:context.clientId,projectId:context.projectId,email:inviteEmail}).then(value=>{if(value?.token)setNotice(`Test invitation ready: ${location.origin}/#/client-portal?token=${encodeURIComponent(String(value.token))}`)})}>Create test invitation</button></div></section>
      {preview.orders.map(order=><section className="client-portal-staff-workspace__operations ui-card" key={order.id}><header><div><span className="ui-eyebrow">Customer-accepted Order</span><h3>{order.orderRef}</h3><p>{order.status.replaceAll("_"," ")}. Staff approval and factory preparation remain distinct.</p></div></header>{order.status==="customer_accepted_pending_staff_approval"?<button className="ui-button ui-button--primary" disabled={busy} onClick={()=>void mutate(`/api/lifecycle/orders/${encodeURIComponent(order.id)}/staff-approval`,{note:"Reviewed from Client Portal operations"})}>Approve Order for factory preparation</button>:null}{order.status==="staff_approved"?<div className="ui-action-row"><input className="ui-input" type="email" value={factoryEmail} onChange={event=>setFactoryEmail(event.currentTarget.value)} placeholder="Configured test factory email"/><button className="ui-button ui-button--primary" disabled={busy||!factoryEmail} onClick={()=>void mutate(`/api/lifecycle/orders/${encodeURIComponent(order.id)}/factory-order`,{recipient:factoryEmail,subject:`TEST Factory Order ${order.orderRef}`,bodyText:"Please review the selected approved Order documents.",documentIds:[],send:false})}>Prepare factory Order preview</button></div>:null}</section>)}
      <ClientPortalPreview client={client} commercialByEstimateId={commercialByEstimateId} releasedEstimateIds={preview.estimates.map(item=>item.estimateId)} releasedDocumentIds={preview.documents.map(item=>item.id)} enabledFeatures={preview.features.filter(item=>item.enabled).map(item=>item.featureKey)} accessContext={{tenantLabel:preview.access.tenantId,contactName:"Authorised QuoteSuite staff",contactEmail:"Internal preview — not impersonating customer",projectScope:preview.project.name,mode:"internal_preview"}} />
    </div>;
  }
  return <section className="client-portal-directory" aria-labelledby="portal-directory-title"><header className="ui-card"><div><span className="ui-eyebrow">QuoteSuite internal workspace</span><h2 id="portal-directory-title">Client Portal Directory</h2><p>Search Clients and Projects, inspect access/release status, then open the governed customer presentation.</p></div></header><label>Client or Project search<input className="ui-input" value={search} onChange={event=>setSearch(event.currentTarget.value)} placeholder="Client, EF-CL reference or Project" /></label>{error?<div className="ui-status ui-status--error" role="alert">{error}</div>:null}{changes.length?<section className="client-portal-directory__changes ui-card"><header><div><span className="ui-eyebrow">Staff queue</span><h3>Changes Requested</h3></div><span className="ui-status ui-status--warning">{changes.length} awaiting review</span></header>{changes.map(item=><article key={item.review_submission_id}><div><strong>{item.client_name} · {item.project_name}</strong><small>{item.client_ref} · {item.amendment_count} Position change{item.amendment_count===1?"":"s"}</small></div>{item.supplier_revision_request_id?<span className="ui-status">{item.supplier_revision_status}</span>:<button className="ui-button ui-button--primary" disabled={busy} onClick={()=>void mutate(`/api/lifecycle/changes-requested/${encodeURIComponent(item.review_submission_id)}/supplier-revision`,{})}>Review and create working revision</button>}</article>)}</section>:null}<div className="client-portal-directory__list">{rows.map(row=><article className="ui-card" key={`${row.clientId}:${row.projectId}`}><div><strong>{row.clientName}</strong><small>{row.clientReference} · {row.projectName}</small></div><div><span className="ui-status ui-status--muted">{row.portalAccessStatus.replaceAll("_"," ")}</span><small>{row.activeContacts} authorised contact(s) · {row.releasedResources} released resource(s)</small></div><button className="ui-button ui-button--primary" type="button" onClick={()=>setContext({clientId:row.clientId,projectId:row.projectId})}>Open Client Portal</button></article>)}</div></section>;
}
