import { useEffect, useState } from "react";
import { apiUrl, extractApiErrorMessage } from "../../services/api/apiClient";
import type { ServiceCase } from "../service/serviceApi";

const idempotency=()=>crypto.randomUUID();
const readable=(value:string)=>value.replaceAll("_"," ").replace(/^./,letter=>letter.toUpperCase());
const base64=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error);reader.onload=()=>resolve(String(reader.result||"").split(",")[1]||"");reader.readAsDataURL(file)});

export default function PortalServicePanel({projectId,csrf,orders}:{projectId:string;csrf:string;orders:Array<{id:string;orderRef:string}>}){
  const[cases,setCases]=useState<ServiceCase[]>([]),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[comment,setComment]=useState<Record<string,string>>({});
  const[draft,setDraft]=useState({orderId:"",caseType:"service",issueSummary:"",description:"",firstNoticedAt:"",priority:"normal"});
  const request=async(path:string,options:RequestInit={})=>{const response=await fetch(apiUrl(path),{...options,credentials:"include",headers:{"Content-Type":"application/json","X-Portal-CSRF":csrf,...(options.headers||{})}});if(!response.ok)throw new Error(extractApiErrorMessage(response.status,await response.text()));return response.json()};
  const root=`/api/client-portal/external/projects/${encodeURIComponent(projectId)}/service-cases`;
  const load=async()=>setCases(await request(root));
  useEffect(()=>{void load().catch(error=>setMessage(error instanceof Error?error.message:"Service cases could not be loaded."))},[projectId]);
  const run=async(action:()=>Promise<unknown>,progress:string,success:string)=>{setBusy(true);setMessage(progress);try{await action();await load();setMessage(success);return true}catch(error){setMessage(`${error instanceof Error?error.message:"The request could not be saved."} Your information is retained; try again safely.`);return false}finally{setBusy(false)}};
  const submit=async()=>{const saved=await run(()=>request(root,{method:"POST",body:JSON.stringify({...draft,idempotencyKey:idempotency()})}),"Submitting your issue…","Issue submitted. Your Service reference is shown below. Next: the Service team reviews the information and records the next update.");if(saved){setOpen(false);setDraft({orderId:"",caseType:"service",issueSummary:"",description:"",firstNoticedAt:"",priority:"normal"})}};
  return <section className="portal-external__command ui-card"><header><div><span className="ui-eyebrow">Service</span><h2>Report and track an issue</h2><p>You do not need an Order reference. Tell us what happened and add useful photos or documents.</p></div><button className="ui-button ui-button--primary" onClick={()=>setOpen(current=>!current)}>{open?"Close form":"Report an issue"}</button></header>
    {message?<p className="ui-status" role={/could not|failed|try again/i.test(message)?"alert":"status"}>{message}</p>:null}
    {open?<div className="portal-external__positions"><label>Project / Order, if known<select className="ui-select" value={draft.orderId} onChange={event=>setDraft(current=>({...current,orderId:event.currentTarget.value}))}><option value="">This Project · Order not known</option>{orders.map(order=><option value={order.id} key={order.id}>{order.orderRef}</option>)}</select></label><label>What is the issue?<input className="ui-input" value={draft.issueSummary} onChange={event=>setDraft(current=>({...current,issueSummary:event.currentTarget.value}))}/></label><label>Please explain<textarea className="ui-textarea" rows={5} value={draft.description} onChange={event=>setDraft(current=>({...current,description:event.currentTarget.value}))}/></label><details><summary>Add optional details</summary><label>Issue type<input className="ui-input" value={draft.caseType} onChange={event=>setDraft(current=>({...current,caseType:event.currentTarget.value}))}/></label><label>First noticed<input className="ui-input" type="date" value={draft.firstNoticedAt} onChange={event=>setDraft(current=>({...current,firstNoticedAt:event.currentTarget.value}))}/></label></details><div className="ui-action-row"><button className="ui-button" disabled={busy} onClick={()=>setOpen(false)}>Cancel</button><button className="ui-button ui-button--primary" disabled={busy||!draft.issueSummary.trim()||!draft.description.trim()} onClick={()=>void submit()}>{busy?"Submitting issue…":"Review and submit"}</button></div></div>:null}
    <div className="portal-external__positions">{cases.map(item=><article className="ui-card" key={item.id}><div className="ui-action-row"><strong>{item.reference} · {item.issueSummary}</strong><span className="ui-status">{readable(item.status)}</span></div><p>{item.description}</p><p><strong>Next step:</strong> {item.nextAction||"The Service team is reviewing your report."}{item.nextActionDueAt?` · ${new Date(item.nextActionDueAt).toLocaleDateString("en-GB")}`:""}</p>{item.customerExpectation?<p>{item.customerExpectation}</p>:null}<details><summary>View case history</summary>{item.events.map(event=><p key={event.id}><strong>{readable(event.eventType)}</strong> · {event.body}<br/><small>{new Date(event.occurredAt).toLocaleString("en-GB")}</small></p>)}{item.attachments.map(file=><p key={file.id}><a className="ui-button ui-button--ghost" href={apiUrl(`${root}/${item.id}/attachments/${file.id}`)} target="_blank" rel="noreferrer">Open {file.fileName}</a></p>)}</details><label>Add information<textarea className="ui-textarea" rows={3} value={comment[item.id]||""} onChange={event=>setComment(current=>({...current,[item.id]:event.currentTarget.value}))}/></label><button className="ui-button" disabled={busy||!comment[item.id]?.trim()} onClick={async()=>{const saved=await run(()=>request(`${root}/${item.id}/comments`,{method:"POST",body:JSON.stringify({body:comment[item.id],idempotencyKey:idempotency()})}),"Adding your information…",`Information added to ${item.reference}. The original report remains unchanged.`);if(saved)setComment(current=>({...current,[item.id]:""}))}}>Add information</button><label>Add photos or documents<input className="ui-input" type="file" multiple onChange={async event=>{const files=[...(event.currentTarget.files||[])];if(!files.length)return;const saved=await run(async()=>{for(const file of files)await request(`${root}/${item.id}/attachments`,{method:"POST",body:JSON.stringify({fileName:file.name,mediaType:file.type,contentBase64:await base64(file),idempotencyKey:idempotency()})})},`Uploading ${files.length} file${files.length===1?"":"s"}…`,`${files.length} file${files.length===1?"":"s"} added to ${item.reference}.`);if(saved)event.currentTarget.value=""}}/></label></article>)}{!cases.length?<p className="ui-empty-state">No Service cases have been reported for this Project.</p>:null}</div>
  </section>;
}
