import {useEffect,useRef,useState} from 'react';
import {apiFetch,apiUrl} from '../../services/api/apiClient';
import './installationDocuments.css';
import OrderInstallationPlanReview from './OrderInstallationPlanReview';

type Saved={id:string;fileName:string;audience:string;revision:number;createdAt:string};
type CalculationReview={ready:boolean;message:string;nextAction:string;rows:Array<{id:string;reference:string;status:string;differences:Array<{field:string;scheduled:number|null;calculated:number|null}>}>;extra:Array<{reference:string;status:string}>};
type Context={clientId:string;estimateReference:string;revision:number;scenarios:Array<{id:string;name:string;revision:number}>;orders:Array<{id:string;reference:string;revision:number}>;plans:Array<{id:string;orderId:string;version:number;reviewReason:string}>;documents:Saved[];total:number;offset:number;limit:number};
export default function InstallationDocumentsPanel({estimateId,selectedScenarioId,selectedOrderId}:{estimateId:string;selectedScenarioId?:string;selectedOrderId?:string}){
  const [open,setOpen]=useState(false),[context,setContext]=useState<Context|null>(null),[audience,setAudience]=useState('installer'),[orderId,setOrderId]=useState(selectedOrderId||''),[scenarioId,setScenarioId]=useState(selectedScenarioId||''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false),[saved,setSaved]=useState<Saved|null>(null);
  const running=useRef(false),loadSequence=useRef(0),request=useRef<{choices:string;key:string}|null>(null),base=`/api/installation-documents/estimates/${encodeURIComponent(estimateId)}`;
  const [review,setReview]=useState<CalculationReview|null>(null);
  const [orderPlanId,setOrderPlanId]=useState('');
  useEffect(()=>setOrderPlanId(''),[orderId]);
  useEffect(()=>setReview(null),[audience,orderId,scenarioId,context?.revision,context?.scenarios]);
  const load=async(offset=0)=>{const sequence=++loadSequence.current,query=new URLSearchParams({offset:String(offset)});if(selectedOrderId||orderId)query.set('orderId',selectedOrderId||orderId);if(scenarioId||selectedScenarioId)query.set('scenarioId',scenarioId||selectedScenarioId||'');const value=await apiFetch(`${base}?${query}`) as Context;if(sequence===loadSequence.current)setContext(value);return value;};
  useEffect(()=>{if(!selectedScenarioId)return;setScenarioId(current=>current||selectedScenarioId);if(open){setMessage('Refreshing the saved calculation choices…');void load().then(()=>setMessage('Saved calculation choices refreshed. Nothing has been sent.')).catch(()=>{setError(true);setMessage('Saved calculation choices could not refresh. Retry loading to continue.');});}},[selectedScenarioId]);
  const show=async()=>{if(running.current)return;setOpen(true);setBusy(true);setError(false);setMessage('Loading saved document choices…');try{await load();setMessage('Choose the document and source revision. Nothing will be sent.');}catch(reason){setError(true);setMessage(`${reason instanceof Error?reason.message:'Document choices could not be loaded.'} Retry loading to continue.`);}finally{setBusy(false)}};
  const prepare=async()=>{
    if(running.current||!context)return;
    const order=context.orders.find(item=>item.id===orderId),scenario=context.scenarios.find(item=>item.id===scenarioId);
    if(orderId&&!order){setError(true);setMessage('The selected Order is unavailable in these choices. Reopen that Order; its accepted revision has not been replaced with the working Estimate.');return;}
    const body={clientId:context.clientId,audience,revision:order?.revision??context.revision,orderId:order?.id||null,scenarioId:audience==='installer'?scenario?.id:null,scenarioRevision:audience==='installer'?scenario?.revision:null};
    const reviewedBody={...body,...(audience==='installer'&&orderPlanId?{orderPlanId}:{})};
    const choices=JSON.stringify(reviewedBody);if(request.current?.choices!==choices)request.current={choices,key:crypto.randomUUID()};
    running.current=true;setBusy(true);setError(false);setSaved(null);setMessage('Preparing document…');
    try{
      const result=await apiFetch(base,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...reviewedBody,requestKey:request.current.key})}) as Saved&{reused:boolean};setSaved(result);setMessage(`${result.reused?'Reopened':'Prepared'} ${result.fileName} in this Estimate’s installation documents. Not sent. Open the PDF and review its missing information.`);
      try{await load();}catch{setMessage(`${result.fileName} was prepared and is available below. The history list could not refresh; reload it when ready. Nothing was sent.`);}
    }catch(reason){setError(true);setMessage(`${reason instanceof Error?reason.message:'Document preparation failed.'} Your selected choices are retained.`);}finally{running.current=false;setBusy(false)}
  };
  const link=(id:string)=>apiUrl(`${base}/documents/${encodeURIComponent(id)}`);
  const reviewCalculation=async()=>{if(running.current||!context)return;const scenario=context.scenarios.find(item=>item.id===scenarioId),order=context.orders.find(item=>item.id===orderId);if(!scenario||orderId&&!order)return;running.current=true;setBusy(true);setError(false);setReview(null);setMessage('Checking the saved calculation against this schedule…');try{const value=await apiFetch(`${base}/calculation-review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId:context.clientId,revision:order?.revision??context.revision,orderId:order?.id||null,scenarioId:scenario.id,scenarioRevision:scenario.revision})}) as CalculationReview;setReview(value);setMessage(value.ready?'Schedule coverage checked. No documents or costings were changed.':'Calculation differences need review. No documents or costings were changed.');}catch(reason){setError(true);setMessage(`${reason instanceof Error?reason.message:'Calculation review failed.'} Your choices are retained; check again to retry.`);}finally{running.current=false;setBusy(false)}};
  const page=async(offset:number)=>{if(running.current)return;running.current=true;setBusy(true);setError(false);setMessage('Loading document history…');try{await load(offset);setMessage('Document history loaded. Select a filename to open its saved PDF.');}catch{setError(true);setMessage('Document history could not load. The previous page and saved documents are unchanged; try the page again.');}finally{running.current=false;setBusy(false)}};
  return <section className="installation-documents"><button className="ui-button" type="button" onClick={()=>open?setOpen(false):void show()} disabled={busy}>Prepare / review installation documents</button>{open?<div className="ui-card">
    <h3>Installation documents</h3><p>Prepare a draft from the selected revision. Drawings, remaining operational details and reviewed delivery are not yet available here; nothing is sent.</p>
    {message?<p role={error?'alert':'status'} className="ui-status">{message}</p>:null}
    {!context?<button type="button" className="ui-button" disabled={busy} onClick={()=>void show()}>Retry loading</button>:<>
      <label>Document<select className="ui-input" value={audience} disabled={busy} onChange={event=>setAudience(event.currentTarget.value)}><option value="installer">Installer pack — draft</option><option value="client">Client schedule without prices — draft</option></select></label>
      <label>Source revision<select className="ui-input" value={orderId} disabled={busy||!!selectedOrderId} onChange={event=>setOrderId(event.currentTarget.value)}><option value="">{context.estimateReference} · Revision {context.revision}</option>{context.orders.map(item=><option key={item.id} value={item.id}>{item.reference} · accepted Estimate revision {item.revision}</option>)}</select></label>
      {audience==='installer'?<label>Saved installation calculation<select className="ui-input" value={scenarioId} disabled={busy} onChange={event=>setScenarioId(event.currentTarget.value)}><option value="">Choose the saved calculation</option>{context.scenarios.map(item=><option key={item.id} value={item.id}>{item.name} · Revision {item.revision}</option>)}</select></label>:null}
      {audience==='installer'&&!context.scenarios.length?<p>No saved calculation is available yet. <button type="button" className="ui-button" disabled={busy} onClick={()=>void show()}>Refresh choices</button></p>:null}
      {audience==='installer'&&orderId&&context.orders.some(item=>item.id===orderId)&&context.scenarios.some(item=>item.id===scenarioId)?<OrderInstallationPlanReview key={`${orderId}:${scenarioId}:${context.scenarios.find(item=>item.id===scenarioId)?.revision}`} base={base} selection={{clientId:context.clientId,orderId,revision:context.orders.find(item=>item.id===orderId)!.revision,scenarioId,scenarioRevision:context.scenarios.find(item=>item.id===scenarioId)!.revision}} onSaved={async id=>{await load();setOrderPlanId(id);}}/>:null}
      {audience==='installer'&&orderId&&(context.plans||[]).some(item=>item.orderId===orderId)?<label>Reviewed Order calculation<select className="ui-input" value={orderPlanId} disabled={busy} onChange={event=>setOrderPlanId(event.currentTarget.value)}><option value="">Use selected Estimate calculation</option>{context.plans.filter(item=>item.orderId===orderId).map(item=><option key={item.id} value={item.id}>Plan {item.version} · {item.reviewReason}</option>)}</select></label>:null}
      {audience==='installer'&&scenarioId?<button type="button" className="ui-button" disabled={busy} onClick={()=>void reviewCalculation()}>Check calculation against schedule</button>:null}
      {review?<div className="ui-card"><p>{review.message}</p><p>{review.nextAction}</p><details><summary>View Position details</summary>{review.rows.map(row=><p key={row.id}>{row.reference}: {({matches:'Matches',missing:'Missing from calculation',repeated:'Repeated in calculation',different:'Quantity or dimensions differ'} as Record<string,string>)[row.status]||row.status}{row.differences.map(item=><span key={item.field}> · {({quantity:'Quantity',widthMm:'Width (mm)',heightMm:'Height (mm)'} as Record<string,string>)[item.field]}: schedule {item.scheduled??'Not confirmed'}, calculation {item.calculated??'Not confirmed'}</span>)}</p>)}{review.extra.map((item,index)=><p key={index}>{item.reference}: {item.status==='unlinked'?'Not linked to a schedule Position':'In calculation but not in selected schedule'}</p>)}</details></div>:null}
      <button type="button" className="ui-button ui-button--primary" disabled={busy||(audience==='installer'&&!orderPlanId&&!context.scenarios.some(item=>item.id===scenarioId))} onClick={()=>void prepare()}>{busy?'Preparing…':'Prepare draft PDF'}</button>
      {saved?<p><a className="ui-button" href={link(saved.id)} target="_blank" rel="noreferrer">Open prepared PDF</a></p>:null}
      <details><summary>Prepared documents — not sent ({context.total})</summary>{context.documents.map(item=><p key={item.id}><a href={link(item.id)} target="_blank" rel="noreferrer">{item.fileName}</a> · Revision {item.revision}</p>)}<p>Showing {context.total?context.offset+1:0}–{context.offset+context.documents.length} of {context.total}</p><button className="ui-button" disabled={busy||context.offset===0} onClick={()=>void page(Math.max(0,context.offset-10))}>Previous</button><button className="ui-button" disabled={busy||context.offset+10>=context.total} onClick={()=>void page(context.offset+10)}>Next</button></details>
    </>}
  </div>:null}</section>;
}
