import { useCallback, useEffect, useState } from "react";
import { communicationsApi, type CommunicationAttachmentView, type CommunicationMessageView, type GoogleWorkspaceStatus } from "../../services/communications/communicationsApi";
import "./emailWorkspace.css";

type ComposeMode="compose"|"reply"|"forward";
type Composer={mode:ComposeMode;providerMessageId?:string;to:string;subject:string;bodyHtml:string;attachments:CommunicationAttachmentView[]};
const emptyComposer=():Composer=>({mode:"compose",to:"",subject:"",bodyHtml:"",attachments:[]});
const fileAttachment=(file:File)=>new Promise<CommunicationAttachmentView>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error??new Error("Attachment could not be read."));reader.onload=()=>resolve({fileName:file.name,mediaType:file.type||"application/octet-stream",sizeBytes:file.size,contentBase64:String(reader.result||"").split(",",2)[1]||""});reader.readAsDataURL(file)});

export default function EmailWorkspace({onOpenIntegrations}:{onOpenIntegrations:()=>void}){
  const [status,setStatus]=useState<GoogleWorkspaceStatus|null>(null),[folder,setFolder]=useState("inbox"),[query,setQuery]=useState(""),[messages,setMessages]=useState<CommunicationMessageView[]>([]),[selected,setSelected]=useState<CommunicationMessageView|null>(null),[composer,setComposer]=useState<Composer|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const refreshStatus=useCallback(()=>communicationsApi.status().then(setStatus).catch(reason=>setError(reason instanceof Error?reason.message:"Email status could not be loaded.")),[]);
  const load=useCallback(async(nextFolder:string,nextQuery:string)=>{setBusy(true);setError("");try{const result=await communicationsApi.list(nextFolder,nextQuery);setMessages(result.messages);setSelected(current=>result.messages.find(item=>item.id===current?.id)??result.messages[0]??null)}catch(reason){setError(reason instanceof Error?reason.message:"Mailbox could not be loaded.")}finally{setBusy(false)}},[]);
  useEffect(()=>{void refreshStatus()},[refreshStatus]);
  useEffect(()=>{if(status?.connected)void load(folder,"")},[folder,status?.connected,load]);
  const submit=async(kind:"draft"|"send")=>{if(!composer)return;setBusy(true);setError("");try{const payload={providerMessageId:composer.providerMessageId,to:composer.to.split(/[;,]/).map(item=>item.trim()).filter(Boolean),subject:composer.subject,bodyHtml:composer.bodyHtml,attachments:composer.attachments};if(kind==="draft")await communicationsApi.draft(payload);else if(composer.mode==="reply")await communicationsApi.reply(payload);else if(composer.mode==="forward")await communicationsApi.forward(payload);else await communicationsApi.send(payload);setComposer(null);setFolder(kind==="draft"?"drafts":"sent");await load(kind==="draft"?"drafts":"sent","")}catch(reason){setError(reason instanceof Error?reason.message:"Email could not be saved.")}finally{setBusy(false)}};
  if(!status)return <section className="email-workspace ui-card"><p>{error||"Loading Email connection…"}</p></section>;
  if(!status.connected)return <section className="email-workspace email-workspace--disconnected ui-card"><div><h2>Email</h2><p>Connect Gmail / Google Workspace to use Inbox, Sent, Drafts, search, compose, reply, forward and attachments. QuoteSuite does not show sample or fake mailbox data.</p>{status.error?<p role="alert">{status.error}</p>:null}</div><button type="button" className="ui-button ui-button--primary" onClick={onOpenIntegrations}>Administration → Integrations</button></section>;
  return <section className="email-workspace" aria-label="Email workspace">
    <header className="email-workspace__header"><div><h2>Email</h2><small>{status.account?.name||status.account?.email} · Gmail / Google Workspace</small></div><button className="ui-button ui-button--primary" onClick={()=>setComposer(emptyComposer())}>Compose</button></header>
    <div className="email-workspace__toolbar"><div role="tablist">{["inbox","sent","drafts"].map(item=><button type="button" role="tab" aria-selected={folder===item} className={`ui-button${folder===item?" ui-button--selected":""}`} key={item} onClick={()=>setFolder(item)}>{item[0].toUpperCase()+item.slice(1)}</button>)}</div><form onSubmit={event=>{event.preventDefault();void load(folder,query)}}><input className="ui-input" aria-label="Search email" value={query} onChange={event=>setQuery(event.currentTarget.value)} placeholder="Search mail"/><button className="ui-button" disabled={busy}>Search</button></form></div>
    {error?<p className="ui-status ui-status--error" role="alert">{error}</p>:null}
    <div className="email-workspace__body"><div className="email-workspace__list" aria-label={`${folder} messages`}>{busy&&!messages.length?<p>Loading…</p>:messages.length?messages.map(message=><button type="button" key={message.id} className={`email-workspace__message${selected?.id===message.id?" is-selected":""}`} onClick={()=>setSelected(message)}><strong>{message.subject||"(No subject)"}</strong><span>{(folder==="inbox"?message.from:message.to).join(", ")}</span><small>{message.sentAt?new Date(message.sentAt).toLocaleString():message.status}</small></button>):<p>No {folder} messages returned by the connected mailbox.</p>}</div>
      <article className="email-workspace__reader">{selected?<><header><h3>{selected.subject||"(No subject)"}</h3><p>From: {selected.from.join(", ")||"—"}<br/>To: {selected.to.join(", ")||"—"}</p></header><div className="email-workspace__message-body">{selected.bodyText||"No plain-text body was returned."}</div>{selected.attachments.length?<ul>{selected.attachments.map(attachment=><li key={attachment.id||attachment.providerAttachmentId}>{selected.providerMessageId&&attachment.providerAttachmentId?<a href={communicationsApi.attachmentUrl(selected.providerMessageId,attachment.providerAttachmentId)}>{attachment.fileName}</a>:attachment.fileName}</li>)}</ul>:null}<footer><button className="ui-button" onClick={()=>setComposer({mode:"reply",providerMessageId:selected.providerMessageId||undefined,to:selected.from.join(", "),subject:selected.subject,bodyHtml:"",attachments:[]})}>Reply</button><button className="ui-button" onClick={()=>setComposer({mode:"forward",providerMessageId:selected.providerMessageId||undefined,to:"",subject:selected.subject,bodyHtml:"",attachments:[]})}>Forward</button></footer></>:<p>Select a message.</p>}</article></div>
    {composer?<div className="ui-modal-backdrop" role="presentation"><section className="ui-modal email-composer" role="dialog" aria-modal="true" aria-label="Email composer"><header><div><h3>{composer.mode==="compose"?"Compose Email":composer.mode==="reply"?"Reply":"Forward"}</h3><small>Provider: Gmail / Google Workspace</small></div><button className="ui-button" onClick={()=>setComposer(null)}>Close</button></header><label>To<input className="ui-input" value={composer.to} onChange={event=>setComposer(current=>current?{...current,to:event.currentTarget.value}:current)}/></label><label>Subject<input className="ui-input" value={composer.subject} onChange={event=>setComposer(current=>current?{...current,subject:event.currentTarget.value}:current)}/></label><label>Message<textarea className="ui-input" rows={10} value={composer.bodyHtml} onChange={event=>setComposer(current=>current?{...current,bodyHtml:event.currentTarget.value}:current)}/></label><label>Attachments<input type="file" multiple onChange={event=>{const files=[...(event.currentTarget.files||[])];void Promise.all(files.map(fileAttachment)).then(attachments=>setComposer(current=>current?{...current,attachments:[...current.attachments,...attachments]}:current))}}/></label>{composer.attachments.map((item,index)=><div className="email-composer__attachment" key={`${item.fileName}-${index}`}><span>{item.fileName}</span><button className="ui-button" onClick={()=>setComposer(current=>current?{...current,attachments:current.attachments.filter((_,at)=>at!==index)}:current)}>Remove</button></div>)}<footer><button className="ui-button" disabled={busy} onClick={()=>void submit("draft")}>Save Draft</button><button className="ui-button ui-button--primary" disabled={busy||!composer.to.trim()||!composer.subject.trim()} onClick={()=>void submit("send")}>Review complete · Send</button></footer></section></div>:null}
  </section>;
}
