// Auto-generated by Phase 4 extraction patch.
// Source of truth for Supplier/Product defaults (moved out of App.tsx).
import * as Models from "../../models/types";
export const PRODUCT_TYPES: Models.ProductType[] = ["uPVC", "uPVC Alu Clad", "Timber", "Timber Aluminium Clad", "Aluminium", "Steel"];

export type SupplierCatalog = {
  name: string;
  productsByType: Partial<Record<Models.ProductType, string[]>>;
};

export const SUPPLIERS: SupplierCatalog[] = [
  {
    name: "Internorm",
    productsByType: {
      uPVC: ["KF520", "KF410", "KF320", "KF310"],
      "uPVC Alu Clad": ["KV440", "KV350", "KF520", "KF310", "KF320"],
      "Timber Aluminium Clad": ["HV450", "HF410", "HF510", "HT410", "HT400", "HT310", "HS330"],
      Aluminium: ["AT500", "AT510", "AT520", "AT530", "AT540"],
    },
  },
  {
    name: "Eko Okna",
    productsByType: {
      uPVC: ["Synego", "Ideal 4000", "Ideal 70", "BluEvolution 82", "Ideal 8000", "Nordline", "S9000"],
      Timber: ["Naturo 68", "Naturo 80", "Naturo 92"],
      "Timber Aluminium Clad": ["Naturo 68 Alu", "Naturo 80 Alu"],
      Aluminium: ["MB-79N", "MB-86 Casement", "MB-104 Passive", "Genesis", "Imperial"],
      Steel: ["Unico XS", "Presto", "Unico"],
    },
  },
];

export function getSupplier(name: string) {
  return SUPPLIERS.find((s) => s.name === name) ?? null;
}

export function allProductsForSupplier(name: string) {
  const s = getSupplier(name);
  if (!s) return [];
  const all = Object.values(s.productsByType).flat().filter(Boolean) as string[];
  return Array.from(new Set(all)).sort((a, b) => a.localeCompare(b));
}

export function firstProductForSupplier(name: string) {
  return allProductsForSupplier(name)[0] ?? "";
}

export const WOOD_TYPES = ["Finger Jointed Pine", "Pine", "Spruce", "Larch", "Oak", "Accoya", "Meranti", "Mahogany"] as const;

export function isTimberProductType(t: Models.ProductType) {
  return t === "Timber" || t === "Timber Aluminium Clad";
}

/* --- finishes: typeahead dropdown via datalist --- */
export const FINISHES_BY_TYPE: Record<Models.ProductType, { external: string[]; internal: string[] }> = {
  uPVC: { external: ["Ext Type 1", "Ext Type 2"], internal: ["Int Type 1", "Int Type 2"] },
  "uPVC Alu Clad": { external: ["Ext Type 1", "Ext Type 2"], internal: ["Int Type 1", "Int Type 2"] },
  Timber: { external: ["Ext Type 1", "Ext Type 2"], internal: ["Int Type 1", "Int Type 2"] },
  "Timber Aluminium Clad": { external: ["Ext Type 1", "Ext Type 2"], internal: ["Int Type 1", "Int Type 2"] },
  Aluminium: { external: ["Ext Type 1", "Ext Type 2"], internal: ["Int Type 1", "Int Type 2"] },
  Steel: { external: ["Ext Type 1", "Ext Type 2"], internal: ["Int Type 1", "Int Type 2"] },
};

