// Auto-generated by QuoteSync Phase 4A extraction patch.
// Source of truth for estimate-level defaults (data + builders).
import * as Models from "../../models/types";
import type { EstimateDefaults } from "../../models/types";
import { SUPPLIERS, WOOD_TYPES, firstProductForSupplier } from "../catalog/defaultCatalog";
export const HINGE_TYPES: EstimateDefaults["hingeType"][] = ["Concealed", "Exposed 130Kg", "Exposed 180Kg"];

export const UG_DOUBLE = ["1.1", "1.2"];
export const UG_TRIPLE = ["0.4", "0.5", "0.6", "0.7", "0.8"];

export const HANDLE_TYPES: EstimateDefaults["windowHandleType"][] = ["Type 1", "Type 2", "Type 3", "Type 4", "Type 5"];

export const SUN_PROTECTION: EstimateDefaults["sunProtectionType"][] = ["Shutters", "Roller blinds", "Venetian blinds (external)", "Venetian blinds (internal)"];

function buildCillDepthOptions(): number[] {
  const out: number[] = [];
  for (let v = 50; v <= 110; v += 20) out.push(v);
  for (let v = 130; v <= 210; v += 15) out.push(v);
  for (let v = 230; v <= 400; v += 20) out.push(v);
  return out;
}

export const CILL_DEPTHS = buildCillDepthOptions();
export const FRAME_EXTS = [0, 25, 50, 75, 100];

export function makeDefaultEstimateDefaults(): EstimateDefaults {
  const supplier = SUPPLIERS[0]?.name ?? "";
    const productType: Models.ProductType = "uPVC";
  const product = supplier ? firstProductForSupplier(supplier) : "";
  return {
    supplier,
    productType,
    product,

    woodType: WOOD_TYPES[0],

    externalFinish: "",
    internalFinish: "",

    hingeType: "Concealed",

    glassType: "Double",
    ugValue: "1.1",
    gValue: "0.53",

    windowHandleType: "Type 1",

    doorMultipointLocking: false,
    electricalOperation: false,
    dayLatch: false,

    internalCillRequired: false,
    externalSillRequired: false,
    cillDepthMm: 50,
    cillEndCapType: "Cladding/Render End Cap",

    frameExtLeftMm: 0,
    frameExtRightMm: 0,
    frameExtTopMm: 0,
    frameExtBottomMm: 0,

    sunProtectionRequired: false,
    sunProtectionType: "Shutters",
  };
}


