import type {
  B92ProfileRuleRegister,
  B92ProfileDefinition,
  B92RuleProfileId,
} from "./b92ProfileRuleModel.types";

const profile = (
  id: B92RuleProfileId,
  definition: Omit<B92ProfileDefinition, "id">
): B92ProfileDefinition => ({
  id,
  ...definition,
});

export const B92_PROFILE_RULE_REGISTER = {
  profiles: {
    "B92-1": profile("B92-1", {
      label: "Fixed head/top",
      kinds: ["outer_frame"],
      orientations: ["top"],
      dimensions: { widthMm: 92, depthMm: 93 },
      status: "confirmed",
      notes: ["Standard fixed top/head profile."],
    }),
    "B92-1/78V": profile("B92-1/78V", {
      label: "Fixed head/top trickle vent alternative",
      kinds: ["outer_frame"],
      orientations: ["top"],
      dimensions: { widthMm: 92, depthMm: 78 },
      status: "candidate",
      notes: ["Alternative trickle vent profile. Exact selection conditions are not yet modelled."],
    }),
    "B92-2": profile("B92-2", {
      label: "Fixed jamb",
      kinds: ["outer_frame"],
      orientations: ["left", "right"],
      dimensions: { widthMm: 92, depthMm: 93 },
      status: "confirmed",
      notes: ["Standard fixed side jamb profile."],
    }),
    "B92-3": profile("B92-3", {
      label: "Fixed sill standard",
      kinds: ["sill", "outer_frame"],
      orientations: ["bottom"],
      dimensions: { widthMm: 92, depthMm: 93 },
      status: "confirmed",
      notes: ["Locked fixed bottom segment sill."],
    }),
    "B92-3a": profile("B92-3a", {
      label: "Fixed sill alternative a",
      kinds: ["sill"],
      orientations: ["bottom"],
      status: "candidate",
      notes: ["Alternative fixed sill. Selection condition requires catalog/PDF confirmation."],
    }),
    "B92-3b": profile("B92-3b", {
      label: "Fixed sill alternative b",
      kinds: ["sill"],
      orientations: ["bottom"],
      status: "candidate",
      notes: ["Alternative fixed sill. Selection condition requires catalog/PDF confirmation."],
    }),
    "B92-3c": profile("B92-3c", {
      label: "Fixed sill alternative c",
      kinds: ["sill"],
      orientations: ["bottom"],
      status: "candidate",
      notes: ["Alternative fixed sill. Selection condition requires catalog/PDF confirmation."],
    }),
    "B92-3d": profile("B92-3d", {
      label: "Fixed sill alternative d",
      kinds: ["sill"],
      orientations: ["bottom"],
      status: "candidate",
      notes: ["Alternative fixed sill. Selection condition requires catalog/PDF confirmation."],
    }),
    "B92-3e": profile("B92-3e", {
      label: "Fixed sill alternative e",
      kinds: ["sill"],
      orientations: ["bottom"],
      status: "candidate",
      notes: ["Alternative fixed sill. Selection condition requires catalog/PDF confirmation."],
    }),
    "B92-3f": profile("B92-3f", {
      label: "Fixed sill alternative f",
      kinds: ["sill"],
      orientations: ["bottom"],
      status: "candidate",
      notes: ["Alternative fixed sill. Selection condition requires catalog/PDF confirmation."],
    }),
    "B92-3g": profile("B92-3g", {
      label: "Fixed sill alternative g",
      kinds: ["sill"],
      orientations: ["bottom"],
      status: "candidate",
      notes: ["Alternative fixed sill. Selection condition requires catalog/PDF confirmation."],
    }),
    "B92-4": profile("B92-4", {
      label: "Fixed head special 2-field case",
      kinds: ["outer_frame"],
      orientations: ["top"],
      dimensions: { widthMm: 92, depthMm: 78 },
      status: "candidate",
      notes: ["Special 2-field fixed head case. Segment conditions are not yet confirmed."],
    }),
    "B92-5": profile("B92-5", {
      label: "Fixed sill field-height equalising profile",
      kinds: ["sill", "outer_frame"],
      orientations: ["bottom"],
      dimensions: { widthMm: 92, depthMm: 78 },
      status: "candidate",
      notes: ["Field-height equalising use. Exact segment rule is not yet confirmed."],
    }),
    "B92-6": profile("B92-6", {
      label: "Fixed jamb/internal interface",
      kinds: ["outer_frame"],
      orientations: ["left", "right"],
      dimensions: { widthMm: 92, depthMm: 78 },
      status: "confirmed",
      notes: ["Fixed internal/interface side profile when explicitly required."],
    }),
    "B92-7": profile("B92-7", {
      label: "Tilt & Turn head/top frame",
      kinds: ["sash_frame", "outer_frame"],
      orientations: ["top"],
      dimensions: { widthMm: 92, depthMm: 78 },
      status: "confirmed",
      notes: ["Standard Tilt & Turn / sash-based top profile."],
    }),
    "B92-7/100": profile("B92-7/100", {
      label: "Tilt & Turn head/top 100 alternative",
      kinds: ["sash_frame", "outer_frame"],
      orientations: ["top"],
      status: "candidate",
      notes: ["Alternative head extension. Selection condition not yet modelled."],
    }),
    "B92-7/120": profile("B92-7/120", {
      label: "Tilt & Turn head/top 120 alternative",
      kinds: ["sash_frame", "outer_frame"],
      orientations: ["top"],
      status: "candidate",
      notes: ["Alternative head extension. Selection condition not yet modelled."],
    }),
    "B92-7/100V": profile("B92-7/100V", {
      label: "Tilt & Turn head/top 100 trickle vent alternative",
      kinds: ["sash_frame", "outer_frame"],
      orientations: ["top"],
      status: "candidate",
      notes: ["Alternative trickle vent/head extension. Selection condition not yet modelled."],
    }),
    "B92-7/120V": profile("B92-7/120V", {
      label: "Tilt & Turn head/top 120 trickle vent alternative",
      kinds: ["sash_frame", "outer_frame"],
      orientations: ["top"],
      status: "candidate",
      notes: ["Alternative trickle vent/head extension. Selection condition not yet modelled."],
    }),
    "B92-8": profile("B92-8", {
      label: "Tilt & Turn sill",
      kinds: ["sill", "sash_frame"],
      orientations: ["bottom"],
      dimensions: { widthMm: 92, depthMm: 78 },
      status: "confirmed",
      notes: ["Locked T&T / Turn / Tilt bottom segment sill."],
    }),
    "B92-8a": profile("B92-8a", {
      label: "Tilt & Turn sill alternative a",
      kinds: ["sill"],
      orientations: ["bottom"],
      status: "candidate",
      notes: ["Alternative T&T sill. Selection condition requires catalog/PDF confirmation."],
    }),
    "B92-8b": profile("B92-8b", {
      label: "Tilt & Turn sill alternative b",
      kinds: ["sill"],
      orientations: ["bottom"],
      status: "candidate",
      notes: ["Alternative T&T sill. Selection condition requires catalog/PDF confirmation."],
    }),
    "B92-8c": profile("B92-8c", {
      label: "Tilt & Turn sill alternative c",
      kinds: ["sill"],
      orientations: ["bottom"],
      status: "candidate",
      notes: ["Alternative T&T sill. Selection condition requires catalog/PDF confirmation."],
    }),
    "B92-8d": profile("B92-8d", {
      label: "Tilt & Turn sill alternative d",
      kinds: ["sill"],
      orientations: ["bottom"],
      status: "candidate",
      notes: ["Alternative T&T sill. Selection condition requires catalog/PDF confirmation."],
    }),
    "B92-8e": profile("B92-8e", {
      label: "Tilt & Turn sill alternative e",
      kinds: ["sill"],
      orientations: ["bottom"],
      status: "candidate",
      notes: ["Alternative T&T sill. Selection condition requires catalog/PDF confirmation."],
    }),
    "B92-8f": profile("B92-8f", {
      label: "Tilt & Turn sill alternative f",
      kinds: ["sill"],
      orientations: ["bottom"],
      status: "candidate",
      notes: ["Alternative T&T sill. Selection condition requires catalog/PDF confirmation."],
    }),
    "B92-9": profile("B92-9", {
      label: "Tilt & Turn jamb handle side",
      kinds: ["sash_frame", "outer_frame"],
      orientations: ["left", "right"],
      dimensions: { widthMm: 92, depthMm: 78 },
      status: "confirmed",
      notes: ["Handle-side side profile."],
    }),
    "B92-10": profile("B92-10", {
      label: "Tilt & Turn jamb hinge side",
      kinds: ["sash_frame", "outer_frame"],
      orientations: ["left", "right"],
      dimensions: { widthMm: 92, depthMm: 78 },
      status: "confirmed",
      notes: ["Hinge-side side profile."],
    }),
    "B92-11": profile("B92-11", {
      label: "Fixed mullion / glass divider",
      kinds: ["vertical_mullion"],
      orientations: ["vertical"],
      dimensions: { widthMm: 92, depthMm: 78 },
      status: "candidate",
      notes: ["Fixed glass divider. Exact use relative to B92-14 requires confirmation."],
    }),
    "B92-12": profile("B92-12", {
      label: "Fixed/T&T mullion",
      kinds: ["vertical_mullion"],
      orientations: ["vertical"],
      dimensions: { widthMm: 92, depthMm: 78 },
      status: "confirmed",
      notes: ["Locked fixed/T&T vertical mullion."],
    }),
    "B92-13": profile("B92-13", {
      label: "Fixed/T&T hinge accommodation mullion",
      kinds: ["vertical_mullion"],
      orientations: ["vertical"],
      dimensions: { widthMm: 92, depthMm: 100 },
      status: "candidate",
      notes: ["Hinge-accommodation variant. Exact override condition requires confirmation."],
    }),
    "B92-14": profile("B92-14", {
      label: "Fixed/fixed mullion",
      kinds: ["vertical_mullion", "sash_bar"],
      orientations: ["vertical"],
      dimensions: { widthMm: 92, depthMm: 78 },
      status: "confirmed",
      notes: ["Locked fixed/fixed vertical mullion."],
    }),
    "B92-15": profile("B92-15", {
      label: "T&T/T&T mullion",
      kinds: ["vertical_mullion"],
      orientations: ["vertical"],
      dimensions: { widthMm: 92, depthMm: 78 },
      status: "confirmed",
      notes: ["Locked default T&T/T&T vertical mullion unless hinge/meeting override applies."],
    }),
    "B92-16": profile("B92-16", {
      label: "T&T/T&T mullion, both hinges at centre",
      kinds: ["vertical_mullion"],
      orientations: ["vertical"],
      dimensions: { widthMm: 92, depthMm: 78 },
      status: "candidate",
      notes: ["Variant based on both hinges at centre. Resolver condition not yet implemented."],
    }),
    "B92-17": profile("B92-17", {
      label: "T&T/T&T mullion, same sash direction",
      kinds: ["vertical_mullion"],
      orientations: ["vertical"],
      dimensions: { widthMm: 92, depthMm: 78 },
      status: "candidate",
      notes: ["Variant when both sashes are T&T right or both T&T left. Resolver condition not yet implemented."],
    }),
    "B92-18": profile("B92-18", {
      label: "Turn/Tilt and Turn flying mullion",
      kinds: ["flying_mullion", "vertical_mullion"],
      orientations: ["vertical"],
      dimensions: { widthMm: 92, depthMm: 78 },
      status: "confirmed",
      notes: ["Locked flying mullion classification."],
    }),
    "B92-19": profile("B92-19", {
      label: "Fixed/fixed transom",
      kinds: ["horizontal_transom"],
      orientations: ["horizontal"],
      dimensions: { widthMm: 92, depthMm: 78 },
      status: "confirmed",
      notes: ["Horizontal transom only; must not be substituted with vertical mullion logic."],
    }),
    "B92-20": profile("B92-20", {
      label: "Fixed bottom / T&T top transom",
      kinds: ["horizontal_transom"],
      orientations: ["horizontal"],
      dimensions: { widthMm: 92, depthMm: 78 },
      status: "confirmed",
      notes: ["Horizontal transom only; used for T&T over fixed adjacency."],
    }),
    "B92-21": profile("B92-21", {
      label: "Fixed top / T&T bottom transom",
      kinds: ["horizontal_transom"],
      orientations: ["horizontal"],
      dimensions: { widthMm: 92, depthMm: 78 },
      status: "confirmed",
      notes: ["Horizontal transom only; used for fixed over T&T adjacency."],
    }),
    "B92-22": profile("B92-22", {
      label: "T&T/T&T transom",
      kinds: ["horizontal_transom"],
      orientations: ["horizontal"],
      dimensions: { widthMm: 92, depthMm: 78 },
      status: "confirmed",
      notes: ["Horizontal transom only; used for T&T over T&T adjacency."],
    }),
    "B92-23": profile("B92-23", {
      label: "Fixed/fixed transom row-aware variant",
      kinds: ["horizontal_transom"],
      orientations: ["horizontal"],
      status: "candidate",
      notes: ["2-field bottom/fixed top or 1-field fixed top contexts require exact rule confirmation."],
    }),
    "B92-24": profile("B92-24", {
      label: "T&T/fixed transom mixed-case variant",
      kinds: ["horizontal_transom"],
      orientations: ["horizontal"],
      status: "candidate",
      notes: ["3-field/mixed case transom. Exact row-composition condition requires confirmation."],
    }),
    "B92-25": profile("B92-25", {
      label: "T&T threshold",
      kinds: ["threshold"],
      orientations: ["bottom"],
      dimensions: { widthMm: 90, depthMm: 88 },
      status: "candidate",
      notes: ["Alternative threshold. Selection conditions not yet modelled."],
    }),
    "B92-26": profile("B92-26", {
      label: "Fixed threshold",
      kinds: ["threshold"],
      orientations: ["bottom"],
      dimensions: { widthMm: 92, depthMm: 67 },
      status: "candidate",
      notes: ["Alternative threshold. Selection conditions not yet modelled."],
    }),
    "B92-C01": profile("B92-C01", {
      label: "Coupling profile C01",
      kinds: ["coupling"],
      orientations: ["coupling"],
      status: "candidate",
      notes: ["Coupling profile. Selection option must be explicit."],
    }),
    "B92-C02": profile("B92-C02", {
      label: "Coupling profile C02",
      kinds: ["coupling"],
      orientations: ["coupling"],
      status: "candidate",
      notes: ["Coupling profile. Selection option must be explicit."],
    }),
    "B92-C03": profile("B92-C03", {
      label: "Coupling profile C03",
      kinds: ["coupling"],
      orientations: ["coupling"],
      status: "candidate",
      notes: ["Coupling profile. Selection option must be explicit."],
    }),
    "B92-C04": profile("B92-C04", {
      label: "Coupling profile C04",
      kinds: ["coupling"],
      orientations: ["coupling"],
      status: "candidate",
      notes: ["Coupling profile. Selection option must be explicit."],
    }),
    "B92-C05": profile("B92-C05", {
      label: "Coupling profile C05",
      kinds: ["coupling"],
      orientations: ["coupling"],
      status: "candidate",
      notes: ["Coupling profile. Selection option must be explicit."],
    }),
    "B92-C06": profile("B92-C06", {
      label: "Coupling profile C06",
      kinds: ["coupling"],
      orientations: ["coupling"],
      status: "candidate",
      notes: ["Coupling profile. Selection option must be explicit."],
    }),
    "B92-C07": profile("B92-C07", {
      label: "Corner/coupling post C07",
      kinds: ["corner"],
      orientations: ["corner"],
      status: "candidate",
      notes: ["Corner/coupling post profile. Selection option must be explicit."],
    }),
    "B92-C08": profile("B92-C08", {
      label: "Corner/coupling post C08",
      kinds: ["corner"],
      orientations: ["corner"],
      status: "candidate",
      notes: ["Corner/coupling post profile. Selection option must be explicit."],
    }),
    "B92-C09": profile("B92-C09", {
      label: "Corner/coupling post C09",
      kinds: ["corner"],
      orientations: ["corner"],
      status: "candidate",
      notes: ["Corner/coupling post profile. Selection option must be explicit."],
    }),
    "B92-C10": profile("B92-C10", {
      label: "Corner/coupling post C10",
      kinds: ["corner"],
      orientations: ["corner"],
      status: "candidate",
      notes: ["Corner/coupling post profile. Selection option must be explicit."],
    }),
    "B92-C11": profile("B92-C11", {
      label: "Corner/coupling post C11",
      kinds: ["corner"],
      orientations: ["corner"],
      status: "candidate",
      notes: ["Corner/coupling post profile. Selection option must be explicit."],
    }),
    "B92-C12": profile("B92-C12", {
      label: "Corner/coupling post C12",
      kinds: ["corner"],
      orientations: ["corner"],
      status: "candidate",
      notes: ["Corner/coupling post profile. Selection option must be explicit."],
    }),
    "B92-C13": profile("B92-C13", {
      label: "Corner/coupling post C13",
      kinds: ["corner", "coupling"],
      orientations: ["corner"],
      status: "candidate",
      notes: ["Angled/corner post. Existing pilot uses 91-140 degree fixed/passive context."],
    }),
    "B92-C14": profile("B92-C14", {
      label: "Corner/coupling post C14",
      kinds: ["corner", "coupling"],
      orientations: ["corner"],
      status: "candidate",
      notes: ["Angled/corner post. Existing pilot uses 141-179 degree fixed/passive context."],
    }),
    "B92-C15": profile("B92-C15", {
      label: "Corner/coupling post C15",
      kinds: ["corner", "coupling"],
      orientations: ["corner"],
      status: "candidate",
      notes: ["Angled/corner post for T&T-present context. Single-tilt constraints not yet modelled here."],
    }),
    "B92-C16": profile("B92-C16", {
      label: "Corner/coupling post C16",
      kinds: ["corner", "coupling"],
      orientations: ["corner"],
      status: "candidate",
      notes: ["Angled/corner post for T&T-present context. Single-tilt constraints not yet modelled here."],
    }),
    "B92-C17": profile("B92-C17", {
      label: "Glass corner",
      kinds: ["glass_corner"],
      orientations: ["corner"],
      status: "confirmed",
      notes: ["Glass-corner profile. Must be explicitly represented where selected."],
    }),
    played_glazing_bar: profile("played_glazing_bar", {
      label: "Played glazing bar",
      kinds: ["glazing_bar"],
      dimensions: { visibleFaceMm: { top: 25, bottom: 25, left: 25, right: 25 } },
      status: "candidate",
      notes: ["Glazing bar, 25mm. Placement rules are not yet modelled."],
    }),
    ovolo_glazing_bar: profile("ovolo_glazing_bar", {
      label: "Ovolo glazing bar",
      kinds: ["glazing_bar"],
      dimensions: { visibleFaceMm: { top: 25, bottom: 25, left: 25, right: 25 } },
      status: "candidate",
      notes: ["Glazing bar, 25mm. Placement rules are not yet modelled."],
    }),
    solid_sash_bars: profile("solid_sash_bars", {
      label: "Solid Sash Bars",
      kinds: ["sash_bar"],
      dimensions: { widthMm: 92, depthMm: 78 },
      status: "candidate",
      notes: ["Solid sash bars. Relationship to B92-14 must be resolved before use in fieldRules."],
    }),
  },
  outerEdgeRules: [
    {
      id: "fixed-top-standard",
      edge: "top",
      fieldOperations: ["fixed"],
      profileId: "B92-1",
      status: "confirmed",
    },
    {
      id: "fixed-side-standard",
      edge: "left",
      fieldOperations: ["fixed"],
      profileId: "B92-2",
      status: "confirmed",
      notes: ["Applies to left/right side segments; resolver must mirror segment side explicitly."],
    },
    {
      id: "sash-top-standard",
      edge: "top",
      fieldOperations: ["fixed_sash", "tilt_turn", "turn_only", "tilt_only"],
      profileId: "B92-7",
      status: "confirmed",
    },
    {
      id: "sash-handle-side-standard",
      edge: "left",
      fieldOperations: ["fixed_sash", "tilt_turn", "turn_only", "tilt_only"],
      profileId: "B92-9",
      status: "confirmed",
      notes: ["Side assignment depends on operation/handing; resolver must not apply globally."],
    },
    {
      id: "sash-hinge-side-standard",
      edge: "right",
      fieldOperations: ["fixed_sash", "tilt_turn", "turn_only", "tilt_only"],
      profileId: "B92-10",
      status: "confirmed",
      notes: ["Side assignment depends on operation/handing; resolver must not apply globally."],
    },
  ],
  sillRules: [
    {
      id: "fixed-bottom-segment-sill",
      bottomFieldOperations: ["fixed"],
      profileId: "B92-3",
      status: "confirmed",
      notes: ["Locked per bottom segment, not global per window type."],
    },
    {
      id: "sash-bottom-segment-sill",
      bottomFieldOperations: ["fixed_sash", "tilt_turn", "turn_only", "tilt_only"],
      profileId: "B92-8",
      status: "confirmed",
      notes: ["Locked per bottom segment for T&T / Turn / Tilt sash-based operations."],
    },
  ],
  verticalMullionRules: [
    {
      id: "fixed-to-tilt-turn",
      leftOperation: "fixed",
      rightOperation: "tilt_turn",
      profileId: "B92-12",
      status: "confirmed",
      notes: ["Locked fixed/T&T vertical mullion. Segment resolver must handle mirrored adjacency."],
    },
    {
      id: "fixed-to-fixed",
      leftOperation: "fixed",
      rightOperation: "fixed",
      profileId: "B92-14",
      status: "confirmed",
      notes: ["Locked fixed/fixed vertical mullion."],
    },
    {
      id: "tilt-turn-to-tilt-turn",
      leftOperation: "tilt_turn",
      rightOperation: "tilt_turn",
      profileId: "B92-15",
      status: "confirmed",
      notes: ["Default T&T/T&T vertical mullion unless overridden by hinge/meeting rules."],
    },
    {
      id: "tilt-turn-to-tilt-turn-both-hinges-centre",
      leftOperation: "tilt_turn",
      rightOperation: "tilt_turn",
      profileId: "B92-16",
      overrideCondition: "hinges_at_meeting",
      status: "candidate",
      notes: ["Override condition is known conceptually but not yet implemented."],
    },
    {
      id: "tilt-turn-to-tilt-turn-same-handing",
      leftOperation: "tilt_turn",
      rightOperation: "tilt_turn",
      profileId: "B92-17",
      overrideCondition: "same_handing",
      status: "candidate",
      notes: ["Used when both sashes are T&T right or both T&T left. Exact meeting condition must be implemented later."],
    },
    {
      id: "flying-mullion",
      leftOperation: "tilt_turn",
      rightOperation: "tilt_turn",
      profileId: "B92-18",
      overrideCondition: "flying_mullion",
      status: "confirmed",
      notes: ["Flying mullion override. Owner/master selection is required by future resolver."],
    },
  ],
  horizontalTransomRules: [
    {
      id: "fixed-over-fixed",
      upperOperation: "fixed",
      lowerOperation: "fixed",
      profileId: "B92-19",
      context: "standard",
      status: "confirmed",
      notes: ["Horizontal transom only; not vertical mullion logic."],
    },
    {
      id: "tilt-turn-over-fixed",
      upperOperation: "tilt_turn",
      lowerOperation: "fixed",
      profileId: "B92-20",
      context: "standard",
      status: "confirmed",
      notes: ["Horizontal transom only."],
    },
    {
      id: "fixed-over-tilt-turn",
      upperOperation: "fixed",
      lowerOperation: "tilt_turn",
      profileId: "B92-21",
      context: "standard",
      status: "confirmed",
      notes: ["Horizontal transom only."],
    },
    {
      id: "tilt-turn-over-tilt-turn",
      upperOperation: "tilt_turn",
      lowerOperation: "tilt_turn",
      profileId: "B92-22",
      context: "standard",
      status: "confirmed",
      notes: ["Horizontal transom only."],
    },
    {
      id: "fixed-fixed-row-aware-special",
      upperOperation: "fixed",
      lowerOperation: "fixed",
      profileId: "B92-23",
      context: "row_composition",
      status: "candidate",
      notes: ["2-field bottom/fixed top or 1-field fixed top context requires exact resolver condition."],
    },
    {
      id: "tilt-turn-fixed-mixed-special",
      upperOperation: "tilt_turn",
      lowerOperation: "fixed",
      profileId: "B92-24",
      context: "special_mixed_case",
      status: "candidate",
      notes: ["3-field/mixed cases require exact resolver condition."],
    },
  ],
  couplingRules: [
    ...(["B92-C01", "B92-C02", "B92-C03", "B92-C04", "B92-C05", "B92-C06"] as const).map((profileId) => ({
      id: `${profileId}-straight-coupling`,
      profileId,
      role: "straight_coupling" as const,
      status: "candidate" as const,
      notes: ["Straight coupling option. Selection must be explicit."],
    })),
    ...(["B92-C07", "B92-C08", "B92-C09", "B92-C10", "B92-C11", "B92-C12"] as const).map((profileId) => ({
      id: `${profileId}-corner-post`,
      profileId,
      role: "corner_post" as const,
      status: "candidate" as const,
      notes: ["Corner/coupling post option. Selection must be explicit."],
    })),
    {
      id: "B92-C13-angled-bay-91-140",
      profileId: "B92-C13",
      role: "angled_bay",
      angleRangeDegrees: [91, 140],
      status: "candidate",
      notes: ["Known existing range, but not yet connected to Admin source model."],
    },
    {
      id: "B92-C14-angled-bay-141-179",
      profileId: "B92-C14",
      role: "angled_bay",
      angleRangeDegrees: [141, 179],
      status: "candidate",
      notes: ["Known existing range, but not yet connected to Admin source model."],
    },
    {
      id: "B92-C15-tilt-angled-bay-91-140",
      profileId: "B92-C15",
      role: "angled_bay",
      angleRangeDegrees: [91, 140],
      status: "candidate",
      notes: ["T&T-present angled bay option. Single-tilt constraint must be represented before use."],
    },
    {
      id: "B92-C16-tilt-angled-bay-141-179",
      profileId: "B92-C16",
      role: "angled_bay",
      angleRangeDegrees: [141, 179],
      status: "candidate",
      notes: ["T&T-present angled bay option. Single-tilt constraint must be represented before use."],
    },
    {
      id: "B92-C17-glass-corner",
      profileId: "B92-C17",
      role: "glass_corner",
      status: "confirmed",
      notes: ["Glass corner must be represented explicitly; it is not optional fallback geometry."],
    },
  ],
  thresholdRules: [
    {
      id: "tilt-turn-threshold",
      fieldOperations: ["fixed_sash", "tilt_turn", "turn_only", "tilt_only"],
      profileId: "B92-25",
      replacesBottomSill: true,
      status: "candidate",
      notes: ["Alternative threshold. Selection condition not yet represented."],
    },
    {
      id: "fixed-threshold",
      fieldOperations: ["fixed"],
      profileId: "B92-26",
      replacesBottomSill: true,
      status: "candidate",
      notes: ["Alternative threshold. Selection condition not yet represented."],
    },
  ],
} as const satisfies B92ProfileRuleRegister;

export const B92_PROFILE_RULE_PROFILE_IDS = Object.keys(
  B92_PROFILE_RULE_REGISTER.profiles
) as B92RuleProfileId[];
