// Auto-generated by QuoteSync Phase 4B extraction patch.
// Moved from src/App.tsx (no UI/layout/logic changes).
import React, { useEffect, useState } from "react";
import Toggle from "../../components/Toggle";
import * as Models from "../../models/types";
import type { EstimateDefaults } from "../../models/types";
import { PRODUCT_TYPES, SUPPLIERS, WOOD_TYPES, FINISHES_BY_TYPE, allProductsForSupplier, firstProductForSupplier, isTimberProductType } from "../catalog/defaultCatalog";
import { HINGE_TYPES, UG_DOUBLE, UG_TRIPLE, HANDLE_TYPES, SUN_PROTECTION, CILL_DEPTHS, FRAME_EXTS } from "./defaultEstimateDefaults";
import "./DefaultsEditor.css";

function H3({ children }: { children: React.ReactNode }) {
  return <h3 className="defaults-editor-heading">{children}</h3>;
}
function Small({ children }: { children: React.ReactNode }) {
  return <div className="defaults-editor-small">{children}</div>;
}
function Input({
  value,
  onChange,
  placeholder,
  type = "text",
  list,
  disabled,
  readOnly,
}: {
  value: string;
  onChange: (v: string) => void;
  placeholder?: string;
  type?: string;
  list?: string;
  disabled?: boolean;
  readOnly?: boolean;
}) {
  return (
    <input
      type={type}
      value={value}
      placeholder={placeholder}
      list={list}
      disabled={disabled}
      readOnly={readOnly}
      onChange={(e) => onChange(e.target.value)}
      className="defaults-editor-input"
    />
  );
}

function CollapsibleSection({
  title,
  open,
  onToggle,
  children,
}: {
  title: string;
  open: boolean;
  onToggle: () => void;
  children: React.ReactNode;
}) {
  return (
    <div className="defaults-editor-section">
      <button
        type="button"
        onClick={onToggle}
        className="defaults-editor-accordion"
      >
        <H3>{open ? "▼" : "▶"} {title}</H3>
      </button>

      {open ? <div className="defaults-editor-section-body">{children}</div> : null}
    </div>
  );
}

/* =========================
   Defaults Editor (Estimate-level + Position "Use estimate defaults")
========================= */

export default function DefaultsEditor({
  title,
  productType,
  value,
  onChange,
  showDoorOptions,
}: {
  title: string;
  productType: Models.ProductType;
  value: EstimateDefaults;
  onChange: (next: EstimateDefaults) => void;
  showDoorOptions: boolean;
}) {
  const finishes = FINISHES_BY_TYPE[productType];
  const [defaultsOpen, setDefaultsOpen] = useState(true);
  const [finishesOpen, setFinishesOpen] = useState(false);
  const [hardwareOpen, setHardwareOpen] = useState(false);
  const [glazingOpen, setGlazingOpen] = useState(false);
  const [windowHandleOpen, setWindowHandleOpen] = useState(false);
  const [doorOptionsOpen, setDoorOptionsOpen] = useState(false);
  const [accessoriesOpen, setAccessoriesOpen] = useState(false);
  const [frameExtensionsOpen, setFrameExtensionsOpen] = useState(false);
  const [sunProtectionOpen, setSunProtectionOpen] = useState(false);

  const lockableHandle = Boolean((value as any).lockableHandle);

  useEffect(() => {
    if (value.gValue !== "0.53") onChange({ ...value, gValue: "0.53" });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [value.ugValue, value.glassType]);

  const ugOptions = value.glassType === "Double" ? UG_DOUBLE : UG_TRIPLE;

  return (
    <div className="defaults-editor-root">
      <button
        type="button"
        onClick={() => setDefaultsOpen((prev) => !prev)}
        className="defaults-editor-accordion"
      >
        <H3>{defaultsOpen ? "▼" : "▶"} {title}</H3>
      </button>

      {defaultsOpen ? (
        <div className="defaults-editor-grid">
          <div className="defaults-editor-card">
            <H3>Supplier & Product</H3>

            <div className="defaults-editor-card-body">
              <div>
                <div className="defaults-editor-label">Supplier</div>
                <select
                  value={value.supplier}
                  onChange={(e) => {
                    const supplier = e.target.value;
                    const nextProd = supplier ? firstProductForSupplier(supplier) : "";
                    onChange({ ...value, supplier, product: nextProd });
                  }}
                  className="defaults-editor-select"
                >
                  <option value="">Select supplier…</option>
                  {SUPPLIERS.map((s) => (
                    <option key={s.name} value={s.name}>
                      {s.name}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <div className="defaults-editor-label">Product type</div>
                <select
                  value={value.productType}
                  onChange={(e) => onChange({ ...value, productType: e.target.value as Models.ProductType })}
                  className="defaults-editor-select"
                >
                  {PRODUCT_TYPES.map((t) => (
                    <option key={t} value={t}>
                      {t}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <div className="defaults-editor-label">Product</div>
                <select
                  value={value.product}
                  onChange={(e) => onChange({ ...value, product: e.target.value })}
                  disabled={!value.supplier}
                  className="defaults-editor-select"
                >
                  <option value="">{value.supplier ? "Select product…" : "Select supplier first…"}</option>
                  {allProductsForSupplier(value.supplier).map((p) => (
                    <option key={p} value={p}>
                      {p}
                    </option>
                  ))}
                </select>
              </div>
            </div>
          </div>

          <CollapsibleSection title="Finishes" open={finishesOpen} onToggle={() => setFinishesOpen((prev) => !prev)}>
            <datalist id={"ext-finish-" + title}>
              {finishes.external.map((x) => (
                <option key={x} value={x} />
              ))}
            </datalist>
            <datalist id={"int-finish-" + title}>
              {finishes.internal.map((x) => (
                <option key={x} value={x} />
              ))}
            </datalist>

            <div className="defaults-editor-two-col">
              <div>
                <div className="defaults-editor-label">External finish</div>
                <Input value={value.externalFinish} onChange={(v) => onChange({ ...value, externalFinish: v })} list={"ext-finish-" + title} placeholder="Select or type…" />
              </div>
              <div>
                <div className="defaults-editor-label">Internal finish</div>
                <Input value={value.internalFinish} onChange={(v) => onChange({ ...value, internalFinish: v })} list={"int-finish-" + title} placeholder="Select or type…" />
              </div>
            </div>
          </CollapsibleSection>

          <CollapsibleSection title="Hardware" open={hardwareOpen} onToggle={() => setHardwareOpen((prev) => !prev)}>
            <div className="defaults-editor-two-col">
              <div>
                <div className="defaults-editor-label">Hinges</div>
                <select
                  value={value.hingeType}
                  onChange={(e) => onChange({ ...value, hingeType: e.target.value as any })}
                  className="defaults-editor-select"
                >
                  {HINGE_TYPES.map((t) => (
                    <option key={t} value={t}>
                      {t}
                    </option>
                  ))}
                </select>
              </div>

              {isTimberProductType(value.productType) ? (
                <div>
                  <div className="defaults-editor-label">Wood type</div>
                  <select
                    value={value.woodType}
                    onChange={(e) => onChange({ ...value, woodType: e.target.value })}
                    className="defaults-editor-select"
                  >
                    {WOOD_TYPES.map((w) => (
                      <option key={w} value={w}>
                        {w}
                      </option>
                    ))}
                  </select>
                </div>
              ) : (
                <div />
              )}
            </div>
          </CollapsibleSection>

          <CollapsibleSection title="Glazing" open={glazingOpen} onToggle={() => setGlazingOpen((prev) => !prev)}>
            <div className="defaults-editor-three-col">
              <div>
                <div className="defaults-editor-label">Glass</div>
                <select
                  value={value.glassType}
                  onChange={(e) => {
                    const glassType = e.target.value as "Double" | "Triple";
                    const nextUg = glassType === "Double" ? "1.1" : "0.4";
                    onChange({ ...value, glassType, ugValue: nextUg, gValue: "0.53" });
                  }}
                  className="defaults-editor-select"
                >
                  <option value="Double">Double</option>
                  <option value="Triple">Triple</option>
                </select>
              </div>

              <div>
                <div className="defaults-editor-label">Ug value required</div>
                <select
                  value={value.ugValue}
                  onChange={(e) => onChange({ ...value, ugValue: e.target.value, gValue: "0.53" })}
                  className="defaults-editor-select"
                >
                  {ugOptions.map((u) => (
                    <option key={u} value={u}>
                      {u}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <div className="defaults-editor-label">G value</div>
                <Input value={value.gValue} onChange={(v) => onChange({ ...value, gValue: v })} />
                <Small>Placeholder: fixed at 0.53 for now</Small>
              </div>
            </div>
          </CollapsibleSection>

          <CollapsibleSection title="Window Handle" open={windowHandleOpen} onToggle={() => setWindowHandleOpen((prev) => !prev)}>
            <div className="defaults-editor-window-handle-grid">
              <div>
                <div className="defaults-editor-label">Handle type</div>
                <select
                  value={value.windowHandleType}
                  onChange={(e) => onChange({ ...value, windowHandleType: e.target.value as any })}
                  className="defaults-editor-select"
                >
                  {HANDLE_TYPES.map((t) => (
                    <option key={t} value={t}>
                      {t}
                    </option>
                  ))}
                </select>
              </div>

              <div className="defaults-editor-handle-preview">
                Handle image
              </div>
            </div>

            <div className="defaults-editor-card-body defaults-editor-card-body-compact">
              <div className="defaults-editor-toggle-row">
                <Toggle
                  value={lockableHandle}
                  onChange={(checked) => onChange({ ...(value as any), lockableHandle: checked } as any)}
                />
                <span className="defaults-editor-toggle-label">Lockable handle</span>
              </div>
              <Small>This is now separate from window cill requirements.</Small>
            </div>
          </CollapsibleSection>

          {showDoorOptions && (
            <CollapsibleSection title="Door options" open={doorOptionsOpen} onToggle={() => setDoorOptionsOpen((prev) => !prev)}>
              <div className="defaults-editor-stack">
                <div className="defaults-editor-toggle-row">
                  <Toggle
                    value={value.doorMultipointLocking}
                    onChange={(checked) => onChange({ ...value, doorMultipointLocking: checked })}
                  />
                  <span className="defaults-editor-toggle-label">Multipoint locking</span>
                </div>

                <div className="defaults-editor-toggle-row">
                  <Toggle
                    value={value.electricalOperation}
                    onChange={(checked) => onChange({ ...value, electricalOperation: checked })}
                  />
                  <span className="defaults-editor-toggle-label">Electrical operation</span>
                </div>

                <div className="defaults-editor-toggle-row">
                  <Toggle
                    value={value.dayLatch}
                    onChange={(checked) => onChange({ ...value, dayLatch: checked })}
                  />
                  <span className="defaults-editor-toggle-label">Day latch</span>
                </div>
              </div>
            </CollapsibleSection>
          )}

          <CollapsibleSection title="Accessories" open={accessoriesOpen} onToggle={() => setAccessoriesOpen((prev) => !prev)}>
            <div className="defaults-editor-grid defaults-editor-grid-compact">
              <div className="defaults-editor-two-col">
                <div className="defaults-editor-toggle-row">
                  <Toggle
                    value={value.internalCillRequired}
                    onChange={(checked) => onChange({ ...value, internalCillRequired: checked })}
                  />
                  <span className="defaults-editor-toggle-label">Window cill internally required</span>
                </div>

                <div className="defaults-editor-toggle-row">
                  <Toggle
                    value={value.externalSillRequired}
                    onChange={(checked) => onChange({ ...value, externalSillRequired: checked })}
                  />
                  <span className="defaults-editor-toggle-label">Window sill externally required</span>
                </div>
              </div>

              <div className="defaults-editor-two-col">
                <div>
                  <div className="defaults-editor-label">Window cill depth</div>
                  <select
                    value={String(value.cillDepthMm)}
                    onChange={(e) => onChange({ ...value, cillDepthMm: Number(e.target.value) })}
                    className="defaults-editor-select"
                  >
                    {CILL_DEPTHS.map((d) => (
                      <option key={d} value={d}>
                        {d} mm
                      </option>
                    ))}
                  </select>
                </div>

                <div>
                  <div className="defaults-editor-label">Cill end cap type</div>
                  <select
                    value={value.cillEndCapType}
                    onChange={(e) => onChange({ ...value, cillEndCapType: e.target.value as any })}
                    className="defaults-editor-select"
                  >
                    <option value="Cladding/Render End Cap">Cladding/Render End Cap</option>
                    <option value="Brick Type End Cap">Brick Type End Cap</option>
                  </select>
                </div>
              </div>
            </div>
          </CollapsibleSection>

          <CollapsibleSection title="Frame extensions" open={frameExtensionsOpen} onToggle={() => setFrameExtensionsOpen((prev) => !prev)}>
            <Small>Set each side independently.</Small>

            <div className="defaults-editor-four-col defaults-editor-section-offset">
              {[
                ["Left", "frameExtLeftMm"],
                ["Right", "frameExtRightMm"],
                ["Top", "frameExtTopMm"],
                ["Bottom", "frameExtBottomMm"],
              ].map(([label, key]) => (
                <div key={key}>
                  <div className="defaults-editor-label">{label}</div>
                  <select
                    value={String((value as any)[key])}
                    onChange={(e) => onChange({ ...value, [key]: Number(e.target.value) } as any)}
                    className="defaults-editor-select"
                  >
                    {FRAME_EXTS.map((mm) => (
                      <option key={mm} value={mm}>
                        {mm} mm
                      </option>
                    ))}
                  </select>
                </div>
              ))}
            </div>
          </CollapsibleSection>

          <CollapsibleSection title="Sun protection required" open={sunProtectionOpen} onToggle={() => setSunProtectionOpen((prev) => !prev)}>
            <div className="defaults-editor-stack">
              <div className="defaults-editor-toggle-row">
                <Toggle
                  value={value.sunProtectionRequired}
                  onChange={(checked) => onChange({ ...value, sunProtectionRequired: checked })}
                />
                <span className="defaults-editor-toggle-label">Sun protection required</span>
              </div>

              {value.sunProtectionRequired ? (
                <div>
                  <div className="defaults-editor-label">Type</div>
                  <select
                    value={value.sunProtectionType}
                    onChange={(e) => onChange({ ...value, sunProtectionType: e.target.value as any })}
                    className="defaults-editor-select"
                  >
                    {SUN_PROTECTION.map((t) => (
                      <option key={t} value={t}>
                        {t}
                      </option>
                    ))}
                  </select>
                </div>
              ) : null}
            </div>
          </CollapsibleSection>
        </div>
      ) : null}
    </div>
  );
}
