import type { PlatformReadiness, RoadmapChronologyEntry, RoadmapItem, RoadmapSection } from "./roadmap.types";

export const ROADMAP_CHECKPOINT_SHA = "ed6537b99f0930357e19ea1f505958e088385ce0";

export const ROADMAP_SECTIONS: RoadmapSection[] = [
  { id: "overview", label: "Overview", description: "Checkpoint, focus, blockers and readiness." },
  { id: "foundation", label: "Foundation & Recovery", description: "Recovery, safeguards and regression foundations." },
  { id: "configurator", label: "Configurator", description: "Canonical foundation and the major product-capability programme." },
  { id: "supplier-import", label: "Supplier Quote Import", description: "Evidence, extraction, review and matching." },
  { id: "estimate-positions", label: "Estimate Positions", description: "Canonical position ownership and bridges." },
  { id: "project-costing", label: "Project Costing", description: "Cost sources, categories and revisions." },
  { id: "commercial-engine", label: "Commercial Engine", description: "Pricing, profitability and governance." },
  { id: "project-map", label: "Project Map & Integrations", description: "Maps, routing, location and provider boundaries." },
  { id: "quotations", label: "Estimate & Quotations", description: "Approved commercial output and customer issue." },
  { id: "crm", label: "CRM & Sales Pipeline", description: "Contacts, enquiries, opportunities and lifecycle." },
  { id: "orders", label: "Orders & Procurement", description: "Accepted work and manufacturer ordering." },
  { id: "documents", label: "Documents & Communications", description: "Mailboxes, files, templates and timelines." },
  { id: "survey-installation", label: "Survey & Installation", description: "Survey, delivery and installation workflow." },
  { id: "workforce", label: "Workforce", description: "People, teams, competence and availability." },
  { id: "field-operations", label: "Field Operations", description: "Assignments, forms, evidence, time and travel." },
  { id: "service-warranty", label: "Service & Warranty", description: "Cases, coverage, claims and completion." },
  { id: "reporting", label: "Reporting & Intelligence", description: "Actual-versus-estimated and operational insight." },
  { id: "automation", label: "Automation & AI", description: "Auditable assistance with human review." },
  { id: "platform-clients", label: "Platform Clients", description: "Web, Windows, mobile, tablet and offline field mode." },
  { id: "saas", label: "SaaS / Multi-Tenancy", description: "Tenant isolation and commercial platform foundations." },
  { id: "cleanup", label: "System Cleanup", description: "Immediate, continuous and freeze-phase debt." },
  { id: "documentation", label: "Documentation", description: "System handbook, contracts and error catalogue." },
  { id: "professional-review", label: "Professional Review", description: "Security, accessibility and architecture review." },
  { id: "external-pilot", label: "Zyle Demo / External Pilot", description: "Controlled external validation." },
  { id: "commercialisation", label: "Commercialisation", description: "Product operations, billing and support." },
];

export const ROADMAP_CHRONOLOGY: RoadmapChronologyEntry[] = [
  "Recovery and protected Client safeguards",
  "Canonical B92 proof/configurator foundation",
  "ConfiguredPositionContract",
  "Legacy configurator containment",
  "Regression/E2E infrastructure",
  "Supplier document/evidence/import foundation",
  "Canonical Estimate Position bridge",
  "Estimate-owned Project Costing",
  "Products / Extras / commercial categories",
  "FX / discounts / markups / fixed selling price",
  "Commercial Margin and revision hardening",
  "Google Maps / Routes integration",
  "Site Visit costing",
  "Project Map consolidation",
  "Phase 6 disposable fixture hardening",
  "Manual/supplier Extra inclusion repair",
  "Aviary alternative/inclusion regression repair",
  "Checkpoint stabilization",
].map((title, index) => ({ sequence: index + 1, title, ...(index === 17 ? { checkpointSha: ROADMAP_CHECKPOINT_SHA } : {}) }));
ROADMAP_CHRONOLOGY.push({ sequence: 19, date: "2026-08-17", title: "Internal Ecofenster MVP · Customer GBP Quotation slice", objective: "Produce a customer-safe GBP quotation preview from saved Project Costing.", validation: "Focused quotation, Project Costing and static validation.", limitations: ["Preview lifecycle only", "Browser print/save PDF", "True DOCX and server PDF remain future work", "VAT policy is isolated but not yet tenant-admin configurable"], resultingStatus: "in_progress" });
ROADMAP_CHRONOLOGY.push({ sequence: 20, date: "2026-08-17", title: "Quotation output · bounded technical layout contract", objective: "Capture approved section and thermal display modes without inventing unavailable technical data.", validation: "Focused quotation contract, TypeScript and build validation.", limitations: ["Position-card renderer remains future work", "No trusted canonical Uf/Ug/Psi/Uw or section-image source yet", "Two-position adaptive pagination remains future work"], resultingStatus: "in_progress" });
ROADMAP_CHRONOLOGY.push({ sequence: 21, date: "2026-08-20", title: "Manufacturer quotation to customer-document foundation", objective: "Preserve position-specific manufacturer evidence and establish generic drawing, branding and customer-safe document projections without assuming Configurator coverage.", validation: "Focused supplier extraction and customer quotation tests plus TypeScript validation.", limitations: ["DOCX EMF elevations are not yet mapped to positions", "B92 document-safe DrawingModel adapter remains unavailable", "Final position cards and pagination remain future work"], resultingStatus: "in_progress" });
ROADMAP_CHRONOLOGY.push({ sequence: 22, date: "2026-08-20", title: "Supplier pricing simplification", objective: "Replace ambiguous supplier buying-price terminology with Factory Price, 1 to 1 Pricing and sequential Staged Discount policies.", validation: "Focused supplier commercial, package, ownership, customer non-leakage and static validation.", limitations: ["Legacy saved policy identifiers remain available only through explicit compatibility", "Order-value bands use saved GBP pre-discount order value and require FX evidence for non-GBP quotations"], resultingStatus: "complete" });
ROADMAP_CHRONOLOGY.push({ sequence: 23, date: "2026-08-20", title: "Manufacturer position visuals · Zyle DOCX/EMF", objective: "Retain embedded manufacturer elevations, map them by Word structure to the correct position and provide print-grade PNG derivatives to Project Costing and Customer Quotation.", validation: "Real 21-position Zyle DOCX mapping/render test, ambiguity regression, customer-safe fallback test and visual inspection.", limitations: ["Direct EMF rendering currently requires Windows System.Drawing", "PDF page-region extraction remains future work", "Image-to-Configurator recognition remains future work"], resultingStatus: "complete" });
ROADMAP_CHRONOLOGY.push({ sequence: 24, date: "2026-08-20", title: "Operational manufacturer import review workflow", objective: "Make Client-owned Estimate creation and explicit manufacturer quotation review operational through the canonical Project Costing browser path.", validation: "Focused service/projection tests, production build and disposable fresh-Zyle browser acceptance: canonical ZF supplier, 21 reviewed positions, 21 mapped PNG previews, same-scenario load and Customer Quotation continuity.", limitations: ["Position match decisions continue through the existing post-load Link to Existing Position / Create New Position review", "No scenario selector or issued quotation lifecycle", "PDF region extraction and image-to-Configurator recognition remain future work"], resultingStatus: "complete" });
ROADMAP_CHRONOLOGY.push({ sequence: 25, date: "2026-08-20", title: "Operational Customer Quotation A4 renderer", objective: "Render the saved Project Costing revision through the canonical customer-safe document model with tenant branding, reviewed manufacturer elevations and adaptive A4 position cards.", validation: "Focused quotation and extraction tests, production build, and disposable fresh-Zyle Chromium acceptance: 21 ordered visuals, two standard positions per A4 page, dedicated wide-position layout and a 13-page A4 PDF without clipping.", limitations: ["Inside/outside pairs remain unavailable where the manufacturer supplied only one unlabelled elevation", "Section details collapse until trusted section assets exist", "Issued quotation snapshots and DOCX output remain future work"], resultingStatus: "complete" });
ROADMAP_CHRONOLOGY.push({ sequence: 26, date: "2026-08-20", title: "Dual Customer Quotation document templates", objective: "Preserve the compact Technical Schedule and add a premium Customer Quotation presentation over the same canonical document model, while making manufacturer previews reliable throughout the browser workflow.", validation: "Fresh disposable Zyle import in isolated Chromium: 21 decoded review/product/document images, both selectable templates, 12-page A4 PDFs, preserved order and no internal commercial leakage.", limitations: ["Legacy visual evidence backfill remains a separate controlled stage", "Only one manufacturer view is available for the current Zyle source", "Issued quotation lifecycle and server archival PDF remain future work"], resultingStatus: "complete" });
ROADMAP_CHRONOLOGY.push({ sequence: 27, date: "2026-08-20", title: "Estimate commercial UX and quotation control correction", objective: "Make quotation thermal/section controls reactive and expose one shared Standard/Advanced Project Costing presentation in Estimate and Admin workspaces.", validation: "Focused quotation tests, TypeScript/build/design-system validation and disposable fresh-Zyle browser/print acceptance across Standard, Advanced, Full, Compact, Hide and both document templates.", limitations: ["Full and Compact contain the same Ug/Uw rows where no trusted Uf/Psi data exists", "Section Show collapses when no trusted section assets exist", "Advanced access is a presentation mode, not yet an RBAC implementation"], resultingStatus: "complete" });
ROADMAP_CHRONOLOGY.push({ sequence: 28, date: "2026-08-20", title: "Dedicated Estimate commercial workspace", objective: "Replace inline Estimate expansion with a compact index and make the dedicated Estimate page the primary Internal/Customer commercial workspace, including snapshotted Admin markup defaults and canonical shared position actions.", validation: "Fresh 21-position Zyle browser import; Internal/Customer same-scenario Duplicate, Alternative, reorder and reload proof; 50-position 1920×1080 and 1366×768 workspace screenshots; quotation print regression; dedicated supported-position quick Configurator save/duplicate/edit/Alternative browser proof; Admin 40%/45% Estimate A/B markup isolation browser proof; dependency-ordered disposable import/costing/evidence purge test; focused Project Costing defaults, TypeScript, build, lint, design-system and Roadmap checks.", limitations: ["Formal access control remains future RBAC work", "Updated timestamps remain unavailable on the legacy Estimate projection"], resultingStatus: "complete" });
ROADMAP_CHRONOLOGY.push({ sequence: 29, date: "2026-08-21", title: "Supplier confirmation lifecycle defect correction", objective: "Correct Confirm & Load when selected evidence spans a current and superseded supplier quotation revision, while preserving revision history, scenario ownership and idempotent costing rows.", validation: "Read-only diagnosis from persisted failed import-run evidence; focused two-revision Manufacturer Import Review → Confirm & Load → Products regression with idempotent retry, supplier-policy snapshots and one unchanged Estimate costing scenario; no manufacturer document re-import or document/PDF acceptance.", limitations: ["The protected Estimate that revealed the defect was not mutated during diagnosis; its existing review can be retried by the user after the corrected server is running"], resultingStatus: "complete" });
ROADMAP_CHRONOLOGY.push({ sequence: 30, date: "2026-08-21", title: "Same-revision manufacturer document accumulation correction", objective: "Separate manufacturer quotation-revision identity from source-document identity so companion documents accumulate idempotently in one Estimate costing scenario, while restoring 1-to-1 Pricing as the explicit GBP row-cost basis.", validation: "Live controlled EF-EST-2026-034 proof: retained Luke document reviewed/loaded 21 positions, retained BI-Fold companion reconciled in place, 22 unique source rows and 22 canonical positions persisted in scenario dcc1de8c-0252-4ab2-adf3-eb63f16877cc, retry added zero, and browser reload retained both documents and all rows. BI-Fold remained EUR 4,242.72 evidence → GBP 4,242.72 parity purchase → GBP 6,151.94 sale at 45%; W1, W5, W17 and Patio door were spot-checked. A targeted browser regression then confirmed the same 22-row scenario visibly retained £20,501.47 Products purchase and £29,777.89 Products sale totals after reload, with explicit 1-to-1 row provenance. Focused supplier/UI tests, Roadmap tests, TypeScript, ESLint, production build and diff checks passed.", limitations: ["Legacy failed import-run audit records remain retained as provenance", "No PDF, print or broad manufacturer-visual acceptance was rerun"], resultingStatus: "complete" });

const base = (item: Omit<RoadmapItem, "dependencies" | "blockers" | "canonicalModules" | "nextAction" | "technicalDebt" | "notes"> & Partial<Pick<RoadmapItem, "dependencies" | "blockers" | "canonicalModules" | "nextAction" | "technicalDebt" | "notes">>): RoadmapItem => ({
  dependencies: [], blockers: [], canonicalModules: [], nextAction: "Define and schedule the next bounded work item.", technicalDebt: [], notes: [], ...item,
});

const backlogChildren = (parentId: string, phase: number, category: RoadmapItem["category"], titles: string[], start = 1): RoadmapItem[] =>
  titles.map((title, index) => base({ id: `${parentId}-${index + start}`, parentId, phase, sequence: index + start, category, title, status: "not_started", platform: ["shared", "web", "tablet"], summary: "Expandable capability group; detailed product rules will be specified progressively.", risk: "medium" }));

const configuratorBacklog = [
  "Window systems", "Door systems", "Sliding systems", "Lift-and-slide systems", "Entrance doors", "French doors",
  "Bi-folding / folding systems", "Fixed glazing", "Combination elements", "Coupled frames", "Complex multi-field structures",
  "Transoms and mullions", "Sash and opening combinations", "Opening directions", "Tilt/turn logic", "Hardware", "Handles",
  "Hinge options", "Locking and security", "Glazing", "Glass build-ups", "Obscure and decorative glass", "Georgian bars and grids",
  "Panels and infill", "Colours and finishes", "Dual colour", "RAL / Teknos / manufacturer finishes", "Cills",
  "Extensions and add-ons", "Frame and sash options", "Ventilation and trickle vents", "Thresholds", "Accessories",
  "Technical constraints", "Dimensional validation", "Manufacturer and product-system rules", "Pricing rules",
  "U-values and thermal data", "Weights", "Drawing accuracy", "Section and profile rendering", "Internal and external views",
  "DIN and UK presentation", "Document drawing output", "Supplier-document to configurator suggestions",
  "Human review of inferred configurations", "Admin catalogue authoring", "Reusable product-system definitions", "Proof and validation expansion",
];

export const ROADMAP_ITEMS: RoadmapItem[] = [
  base({ id: "recovery", phase: 0, sequence: 1, category: "foundation", title: "Recovery and protected Client safeguards", status: "complete", platform: ["all"], summary: "Protected EF-CL-001 through EF-CL-008, disposable acceptance fixtures and checkpoint discipline are established.", checkpointSha: ROADMAP_CHECKPOINT_SHA, validationStatus: "Phase 6 and protected-client integrity passed", evidence: ["Eight protected Client records", "Runtime-owned E2E fixtures", "217/217 focused checkpoint matrix"], nextAction: "Preserve safeguards and add production backup/restore runbooks.", risk: "low" }),
  base({ id: "test-foundation", phase: 0, sequence: 2, category: "foundation", title: "Regression and E2E infrastructure", status: "complete", platform: ["shared", "web"], summary: "Focused domain/service tests and full Phase 6 browser acceptance protect the current milestone.", validationStatus: "217/217 focused; Phase 6 passed", risk: "low" }),

  base({ id: "configurator-foundation", phase: 1, sequence: 1, category: "configurator", title: "Configurator Foundation", status: "complete", platform: ["shared", "web"], summary: "Canonical direction and tested contracts are established; completion here does not mean the configurator product is complete.", canonicalModules: ["ConfiguredPositionContract", "B92 compiler", "Estimate Position bridge", "drawing model pipeline"], evidence: ["Add / Edit / Save / Cancel workflow", "Persistence and hydration", "Approved proof views and regression coverage"], nextAction: "Keep the foundation stable while expanding product capability.", risk: "medium", children: [
    base({ id: "cfg-b92-direction", parentId: "configurator-foundation", phase: 1, sequence: 1, category: "configurator", title: "Generic Configurator with B92 provider", status: "in_progress", platform: ["shared"], summary: "Configurator is the generic architecture; B92 remains the first proven product/system subset behind provider boundaries.", nextAction: "Extract a dimension-safe, non-interactive B92 document DrawingModel adapter without broadening product coverage." }),
    base({ id: "cfg-contract", parentId: "configurator-foundation", phase: 1, sequence: 2, category: "configurator", title: "ConfiguredPositionContract and compiler", status: "complete", platform: ["shared"], summary: "Versioned contract, compiler, validation and compatibility projection exist." }),
    base({ id: "cfg-position-bridge", parentId: "configurator-foundation", phase: 1, sequence: 3, category: "configurator", title: "Estimate Position bridge and persistence", status: "complete", platform: ["shared", "web"], summary: "B92 positions add, edit, save, cancel, persist and hydrate through the canonical bridge." }),
    base({ id: "cfg-proof", parentId: "configurator-foundation", phase: 1, sequence: 4, category: "configurator", title: "Proof and rendering infrastructure", status: "in_progress", platform: ["shared", "web"], summary: "Approved proof families, drawing pipeline and adapters exist, but coverage is intentionally limited.", blockers: ["Production B92 imports Admin/Window Types proof geometry and registries"], nextAction: "Expand proof coverage without weakening approved geometry authority." }),
    base({ id: "cfg-legacy-containment", parentId: "configurator-foundation", phase: 1, sequence: 5, category: "configurator", title: "Legacy configurator containment", status: "complete", platform: ["web"], summary: "Legacy projections and flows are contained behind compatibility boundaries." }),
  ] }),
  base({ id: "configurator-product", phase: 1, sequence: 2, category: "configurator", title: "Configurator Product Capability", status: "in_progress", platform: ["shared", "web", "tablet"], summary: "The canonical configurator architecture is established, but the complete QuoteSuite window and door configuration capability remains a major active development programme.", blockers: ["Large unbounded product-system backlog", "Proof coverage", "Manufacturer rules and pricing not fully specified"], nextAction: "Define and deliver bounded product-system capabilities while preserving canonical contracts.", technicalDebt: ["B92 production depends on Admin/Window Types proof geometry and registries"], notes: ["This programme progresses in parallel with commercial and operational lifecycle work.", "Backlog groups are placeholders, not claims of specified product rules."], risk: "high", children: backlogChildren("configurator-product", 1, "configurator", configuratorBacklog) }),
  base({ id: "configurator-neutral-authority", phase: 19, sequence: 3, category: "configurator", title: "Neutral configurator authority packages", status: "not_started", platform: ["shared"], summary: "Move canonical authority into neutral configurator/domain packages without breaking approved rendering and proof behaviour.", dependencies: ["Proof registry inventory", "Contract and renderer regression protection"], blockers: ["Direct Admin/Window Types dependency"], risk: "high", deferredReason: "Migration must follow evidence-backed extraction; it is not part of the Roadmap UI implementation." }),

  base({ id: "supplier-foundation", phase: 2, sequence: 1, category: "supplier-import", title: "Estimate-owned supplier evidence and import", status: "complete", platform: ["shared", "web", "windows"], summary: "Attachments, revisions, evidence, extraction traces and Estimate ownership are established.", canonicalModules: ["SupplierQuote", "SupplierQuoteRevision", "Supplier evidence"], nextAction: "Expand supported document patterns and review intelligence.", risk: "medium" }),
  base({ id: "supplier-intelligence", phase: 16, sequence: 2, category: "supplier-import", title: "Supplier evidence to configurator suggestions", status: "not_started", platform: ["shared", "web", "tablet"], summary: "Infer likely configurations with explicit confidence and mandatory human review.", dependencies: ["Configurator product metadata", "Normalized technical vocabulary"], risk: "high" }),
  base({ id: "estimate-position-bridge", phase: 3, sequence: 1, category: "estimate-positions", title: "Canonical Estimate Position bridges", status: "complete", platform: ["shared", "web"], summary: "B92 and supplier evidence connect to canonical Estimate-owned positions and Project Costing.", technicalDebt: ["Positions remain persisted in Estimate JSON", "Compatibility projections remain required"], nextAction: "Design normalized position persistence before multi-client/offline work.", risk: "medium" }),

  base({ id: "costing-core", phase: 4, sequence: 1, category: "project-costing", title: "Project Costing foundation", status: "complete", platform: ["shared", "web", "windows"], summary: "Products, supplier/manual Extras, Transport, allocation, FX snapshots, supplier-specific Factory/Parity/Staged Discount policies, markups, customer discounts, fixed selling price, GP, gross margin, effective markup and revisions are proven.", canonicalModules: ["Project Costing scenario", "Supplier commercial policy snapshot", "Supplier costs", "Manual costs", "Commercial revision"], validationStatus: "Focused supplier pricing, costing matrix and Phase 6 validation", technicalDebt: ["Canonical behaviour remains under ProjectCalculatorLab naming/routes", "Legacy supplier policy identifiers remain for historical compatibility"], risk: "medium" }),
  base({ id: "costing-operational-categories", phase: 5, sequence: 2, category: "project-costing", title: "Operational costing categories", status: "in_progress", platform: ["shared", "web"], summary: "Storage, HIAB, Site Visit, installation, equipment hire, installation materials and duties/import fees require further operational depth.", nextAction: "Define each category against procurement and actual-cost ownership.", risk: "medium" }),
  base({ id: "profitability-overhead", phase: 6, sequence: 1, category: "commercial-engine", title: "Profitability / Overhead Recovery", status: "not_started", platform: ["shared", "web"], summary: "Govern minimum profitable work and contribution beyond gross-margin presentation.", children: backlogChildren("profitability-overhead", 6, "commercial-engine", ["Annual overhead budget", "Project overhead recovery", "Contribution", "Contingency allocation", "Minimum profitable selling price", "Approval thresholds", "Role-based discount authority", "Fixed-price override authority", "Margin override authority", "Immutable approval history", "Forecast vs accepted vs actual"]), blockers: ["Authority/RBAC model", "Canonical approval workflow"], risk: "high" }),
  base({ id: "maps", phase: 5, sequence: 1, category: "project-map", title: "Project Map, Geocoding and Routes", status: "complete", platform: ["shared", "web"], summary: "Server-side business geocoding/routing, location provenance, Site Visit integration and unified map are established.", technicalDebt: ["Browser location service uses localStorage", "Legacy installer-distance path remains"], nextAction: "Extract provider-neutral client contracts before native maps.", risk: "medium" }),

  base({ id: "internal-ecofenster-mvp", phase: 7, sequence: 1, category: "quotations", title: "Internal Ecofenster MVP", status: "in_progress", platform: ["web"], summary: "MVP-critical path: Client → Estimate → Supplier Import → Project Costing → GBP Customer Quotation → Print / Save PDF.", milestone: "Target 31 December 2026", notes: ["First Live Customer Quotation target: October/November 2026 or earlier when safely achieved."], nextAction: "Review this quotation slice, then harden the minimal quotation lifecycle.", risk: "high", children: [
    base({ id: "mvp-costing-pricing-authority", parentId: "internal-ecofenster-mvp", phase: 7, sequence: 1, category: "quotations", title: "Saved Project Costing pricing authority", status: "complete", platform: ["shared", "web"], summary: "Worksheet and quotation use one deterministic Project Costing commercial projection.", validationStatus: "Focused commercial projection tests" }),
    base({ id: "mvp-gbp-output", parentId: "internal-ecofenster-mvp", phase: 7, sequence: 2, category: "quotations", title: "GBP customer quotation preview", status: "complete", platform: ["web"], summary: "Customer-facing positions and charges expose GBP selling prices only." }),
    base({ id: "mvp-vat", parentId: "internal-ecofenster-mvp", phase: 7, sequence: 3, category: "quotations", title: "Isolated MVP VAT policy", status: "complete", platform: ["shared", "web"], summary: "One canonical quotation policy applies UK VAT and reconciles ex-VAT, VAT and inc-VAT totals.", technicalDebt: ["VAT is not yet tenant/admin configurable or snapshotted into an issued quotation"] }),
    base({ id: "mvp-print", parentId: "internal-ecofenster-mvp", phase: 7, sequence: 4, category: "quotations", title: "A4 preview and browser Print / Save PDF", status: "complete", platform: ["web"], summary: "A customer-safe preview provides print invocation and A4 print CSS without application chrome." }),
    base({ id: "mvp-imported-position", parentId: "internal-ecofenster-mvp", phase: 7, sequence: 5, category: "quotations", title: "Imported unconfigured position support", status: "complete", platform: ["shared", "web"], summary: "Reviewed imported rows can appear truthfully without fabricated configuration or drawings." }),
    base({ id: "mvp-configured-drawing", parentId: "internal-ecofenster-mvp", phase: 7, sequence: 6, category: "quotations", title: "Generic document-drawing provider boundary", status: "in_progress", platform: ["shared", "web"], summary: "Customer documents request inside/outside drawings through a product/system provider registry with explicit unavailable fallback.", technicalDebt: ["B92 proof geometry is not yet exposed as a dimension-safe non-interactive DrawingModel"] }),
    base({ id: "mvp-fixed-price", parentId: "internal-ecofenster-mvp", phase: 7, sequence: 7, category: "quotations", title: "Fixed Selling Price reconciliation", status: "complete", platform: ["shared", "web"], summary: "A customer-facing project fixed-price adjustment reconciles exactly without invented position allocation." }),
    base({ id: "mvp-reproducibility", parentId: "internal-ecofenster-mvp", phase: 7, sequence: 8, category: "quotations", title: "Saved-state quotation reproducibility", status: "complete", platform: ["shared", "web"], summary: "Quotation projection consumes persisted FX, markups, discounts and fixed price without refreshing providers." }),
    base({ id: "mvp-minimal-lifecycle", parentId: "internal-ecofenster-mvp", phase: 7, sequence: 9, category: "quotations", title: "Minimal quotation lifecycle", status: "not_started", platform: ["shared", "web"], summary: "Record generated/issued state and delivery without overbuilding the final aggregate." }),
    base({ id: "mvp-live-hardening", parentId: "internal-ecofenster-mvp", phase: 7, sequence: 10, category: "quotations", title: "First live quotation acceptance and hardening", status: "in_progress", platform: ["web"], summary: "Complete visual review and controlled real Ecofenster use before treating the output as operationally proven." }),
    base({ id: "mvp-output-display-contract", parentId: "internal-ecofenster-mvp", phase: 7, sequence: 11, category: "quotations", title: "Quotation output display contract", status: "complete", platform: ["shared", "web"], summary: "Typed Show/Hide section details and Full/Compact/Hide position thermal modes are wired through live preview and print with adaptive empty-state collapse.", validationStatus: "Focused quotation contract tests and disposable Chromium/print acceptance", technicalDebt: ["Full and Compact are intentionally identical when only trusted manufacturer Ug/Uw evidence exists"] }),
    base({ id: "mvp-position-card-renderer", parentId: "internal-ecofenster-mvp", phase: 7, sequence: 12, category: "quotations", title: "Detailed adaptive position-card renderer", status: "complete", platform: ["web"], summary: "Sequential customer-safe position cards render two standard positions per A4 page, with reviewed manufacturer PNG fallback and dedicated readable pages for wide products.", validationStatus: "Disposable fresh-Zyle Chromium/print acceptance: 21 ordered elevations, 12 position pages plus summary, 13-page A4 PDF", technicalDebt: ["Native Configurator inside/outside pairs remain limited to proven providers", "Section details collapse until trusted assets exist", "Final issued-document lifecycle remains outstanding"], nextAction: "Establish the minimal immutable generated/issued quotation snapshot and server PDF boundary.", risk: "medium" }),
    base({ id: "mvp-manufacturer-position-visuals", parentId: "internal-ecofenster-mvp", phase: 7, sequence: 13, category: "supplier-import", title: "Manufacturer position visual extraction", status: "complete", platform: ["shared", "web", "windows"], summary: "Zyle DOCX elevations are mapped by exact same-table-cell references, original EMFs are retained and 300 DPI PNG derivatives flow to Project Costing and customer-safe quotation fallback.", validationStatus: "Real 21-position Zyle quotation regression and visual inspection", technicalDebt: ["PDF page-region extraction is not implemented", "Cross-platform EMF renderer adapter remains future work", "Image-to-Configurator recognition remains future work"] }),
    base({ id: "mvp-manufacturer-import-review", parentId: "internal-ecofenster-mvp", phase: 7, sequence: 14, category: "supplier-import", title: "Operational manufacturer import review", status: "complete", platform: ["shared", "web", "windows"], summary: "Client/global Estimate creation, fresh document upload, canonical supplier correction, non-committing position review and explicit idempotent load now form one Estimate-owned Project Costing path.", validationStatus: "Disposable browser acceptance: ZF, 21 reviewed/loaded rows, 21 Product previews and 21 Customer Quotation fallback images", technicalDebt: ["Existing-position match decisions remain a post-load review step", "Manufacturer import revisions do not yet have a dedicated scenario selector"] }),
  ] }),
  base({ id: "quotation", phase: 7, sequence: 2, category: "quotations", title: "Canonical Customer Quotation", status: "in_progress", platform: ["shared", "web", "windows"], summary: "Approved Project Costing Revision → Quotation Revision → Document Generation → Issue → Delivery Record → Acceptance/Rejection → Canonical Order.", children: backlogChildren("quotation", 7, "quotations", ["Quotation numbering", "Quotation revisions", "VAT administration and snapshot", "Terms", "Exclusions", "Validity", "Optional items", "Document-grade drawings", "Proper server PDF", "Proper DOCX", "Email/send", "Issued / superseded / withdrawn states", "Acceptance evidence", "Immutable commercial snapshot"]), blockers: ["Approved commercial snapshot contract", "Document generation boundary"], technicalDebt: ["Current Word output is not true DOCX", "Legacy independently priced estimate document service remains as compatibility code but its misleading output actions are no longer exposed", "Current document/email behaviour is transitional", "Customer pricing is reproducible from saved costing but not yet locked into an issued snapshot"], nextAction: "Review the MVP preview, then design the minimal generated/issued quotation boundary.", risk: "high" }),
  base({ id: "crm-lifecycle", phase: 9, sequence: 1, category: "crm", title: "Contact / Client / Enquiry lifecycle model", status: "not_started", platform: ["shared", "web", "ios", "android", "tablet"], summary: "Define shared Contact/Person and Company identity linked to Enquiry, Prospect/Lead, Opportunity, Client/Customer, Estimate/Quotation, Order/Sold Project and Lost Opportunity records.", notes: ["Do not create duplicated customer databases.", "Future views: Enquiries, Prospects, Active Estimates, Quotations, Customers, Orders / Sold, Completed, Lost and All.", "Exact naming and conversion rules require a design phase."], nextAction: "Run a focused CRM domain-design phase.", risk: "high" }),
  base({ id: "crm-add-client-cleanup", phase: 19, sequence: 2, category: "crm", title: "Rationalise duplicate Add Client actions", status: "not_started", platform: ["web"], summary: "General Create should become the primary creation mechanism; Client Database may retain contextual creation; Follow Ups needs none; redundant Quick Action Add Client should be removed in UI cleanup.", deferredReason: "Recorded only; controls remain unchanged in this task.", nextAction: "Audit navigation usage before removing any entry point.", risk: "low" }),
  base({ id: "crm-pipeline", phase: 9, sequence: 3, category: "crm", title: "CRM and Sales Pipeline", status: "in_progress", platform: ["shared", "web", "ios", "android", "tablet"], summary: "Clients, notes, follow-ups and Estimate outcomes exist; enquiries, opportunities, activities, tasks and conversion history remain.", risk: "high" }),

  base({ id: "canonical-order", phase: 8, sequence: 1, category: "orders", title: "Canonical Order", status: "not_started", platform: ["shared", "web"], summary: "Create an immutable Order from an accepted Quotation revision, including deposit and specification lineage.", dependencies: ["Canonical Customer Quotation", "Acceptance evidence"], risk: "high" }),
  base({ id: "procurement", phase: 11, sequence: 2, category: "orders", title: "Procurement / Manufacturer Ordering", status: "not_started", platform: ["shared", "web", "windows"], summary: "Order → deposit → survey/final specification → manufacturer RFQ/order → acknowledgement → revision comparison → production → dispatch → delivery → installation → completion.", children: backlogChildren("procurement", 11, "orders", ["Common manufacturer integration boundary", "WinPro adapter", "Klaes adapter", "Cantor adapter", "Stolcad adapter", "3E adapter", "Other ERP adapters"]), dependencies: ["Canonical Order", "Final specification ownership"], risk: "high" }),
  base({ id: "communications", phase: 10, sequence: 1, category: "documents", title: "Connected Communications", status: "not_started", platform: ["shared", "web", "windows", "ios", "android", "tablet"], summary: "Gmail/Google Workspace, Microsoft 365/Outlook and a unified linked communication timeline.", children: backlogChildren("communications", 10, "documents", ["Gmail / Google Workspace", "Microsoft 365 / Outlook", "Inbox / Sent / Drafts / Search", "Compose / reply / forward", "Attachments", "Client/project linking", "Supplier quote ingestion from email", "Send quotations through connected mailbox", "Communication timeline", "Templates", "Delivery/open/read tracking where lawful and supported"]), risk: "high" }),
  base({ id: "document-storage", phase: 10, sequence: 2, category: "documents", title: "Document Storage and Versioning", status: "not_started", platform: ["shared", "web", "windows", "ios", "android", "tablet"], summary: "Google Drive, OneDrive, automatic project folders, managed versions and client-neutral file APIs.", children: backlogChildren("document-storage", 10, "documents", ["Google Drive", "OneDrive", "Project folder provisioning", "Document versioning"]), risk: "high" }),

  base({ id: "survey-delivery-installation", phase: 12, sequence: 1, category: "survey-installation", title: "Survey, Delivery and Installation", status: "not_started", platform: ["shared", "web", "ios", "android", "tablet", "offline"], summary: "Canonical Survey, Survey Revision, delivery and Installation Visit workflows.", dependencies: ["Canonical Order", "Field synchronization model"], risk: "high" }),
  base({ id: "workforce-domain", phase: 13, sequence: 1, category: "workforce", title: "Workforce Domain", status: "not_started", platform: ["shared", "web", "ios", "android", "tablet"], summary: "Person, Employee, Worker, Subcontractor, SubcontractCompany, Team, Role, Skill, Availability and Rate.", children: backlogChildren("workforce-domain", 13, "workforce", ["CSCS", "PASMA", "IPAF", "First Aid", "Licences", "Training", "Insurance"]), risk: "high" }),
  base({ id: "field-domain", phase: 13, sequence: 1, category: "field-operations", title: "Field Operations", status: "not_started", platform: ["shared", "ios", "android", "tablet", "offline"], summary: "Appointment, Work Assignment, Field Form, Photo/Evidence, Signature, Time Entry and Travel Event.", dependencies: ["Workforce Domain", "Limited offline synchronization"], risk: "high" }),
  base({ id: "service-warranty-domain", phase: 14, sequence: 1, category: "service-warranty", title: "Service and Warranty", status: "not_started", platform: ["shared", "web", "ios", "android", "tablet", "offline"], summary: "Service Case, Warranty Policy and Warranty Claim linked to Project, Position and component evidence.", dependencies: ["Canonical Order/Project", "Workforce and field evidence"], risk: "high" }),
  base({ id: "actuals", phase: 15, sequence: 1, category: "reporting", title: "Actual-versus-Estimated Intelligence", status: "not_started", platform: ["shared", "web"], summary: "Compare estimated and actual labour, transport, procurement, installation, service and warranty costs.", dependencies: ["Canonical operational event/cost model"], risk: "high" }),
  base({ id: "automation-ai", phase: 16, sequence: 1, category: "automation", title: "Automation and AI Assistance", status: "not_started", platform: ["shared", "web", "ios", "android", "tablet"], summary: "Auditable automation across enquiry, estimating, procurement and field operations with human review.", dependencies: ["Canonical lifecycle events", "Permissions", "Reliable source evidence"], risk: "high" }),

  base({ id: "platform-programme", phase: 17, sequence: 1, category: "platform-clients", title: "Shared Multi-Platform Client Architecture", status: "not_started", platform: ["all"], summary: "Shared TypeScript domain/API packages, primary Web app, potential thin Tauri Windows shell, focused React Native field app and tablet-adaptive field experience.", blockers: ["App.tsx decomposition", "Shared domain/API contracts", "API versioning", "Authentication and RBAC", "Standard errors and observability", "Offline conflict/version semantics", "Client-neutral file APIs"], notes: ["No separate fourth tablet codebase.", "Tauri remains a candidate subject to validation."], risk: "high" }),
  base({ id: "platform-web", parentId: "platform-programme", phase: 17, sequence: 2, category: "platform-clients", title: "Web", status: "in_progress", platform: ["web"], summary: "Primary operational client; strong internal foundation but production security and delivery work remains." }),
  base({ id: "platform-windows", parentId: "platform-programme", phase: 17, sequence: 3, category: "platform-clients", title: "Windows Desktop", status: "not_started", platform: ["windows"], summary: "Potential thin shell around remote QuoteSuite services with native file, print and update adapters." }),
  base({ id: "platform-ios", parentId: "platform-programme", phase: 17, sequence: 4, category: "platform-clients", title: "iOS", status: "not_started", platform: ["ios"], summary: "Focused React Native field client after field APIs and security exist." }),
  base({ id: "platform-android", parentId: "platform-programme", phase: 17, sequence: 5, category: "platform-clients", title: "Android", status: "not_started", platform: ["android"], summary: "Focused React Native field client sharing iOS domain and UI foundations." }),
  base({ id: "platform-tablet", parentId: "platform-programme", phase: 17, sequence: 6, category: "platform-clients", title: "Tablet", status: "not_started", platform: ["tablet"], summary: "Tablet-adaptive field experience for survey, documents, drawings and installation." }),
  base({ id: "platform-offline", parentId: "platform-programme", phase: 17, sequence: 7, category: "platform-clients", title: "Offline Field Mode", status: "not_started", platform: ["offline"], summary: "Limited project snapshots, forms, photos, measurements, signatures and queued updates.", blockers: ["Conflict/version semantics", "Durable outbox", "Media synchronization"] }),

  base({ id: "saas", phase: 18, sequence: 1, category: "saas", title: "SaaS / Multi-Tenant Architecture", status: "not_started", platform: ["shared"], summary: "Tenant isolation, permissions, audit, secrets, billing, GDPR, backup and disaster recovery.", blockers: ["Authentication/RBAC", "Tenant-aware persistence"], risk: "critical" }),
  base({ id: "cleanup-immediate", phase: 19, sequence: 1, category: "cleanup", title: "Immediate architectural stabilization", status: "in_progress", platform: ["shared", "web"], summary: "Bounded extraction before platform expansion.", children: backlogChildren("cleanup-immediate", 19, "cleanup", ["App.tsx decomposition", "Client/Estimate API mapping extraction", "Commercial selector extraction", "Estimate workspace orchestration extraction", "Client Database orchestration extraction", "Project Map extraction", "Document/email adapter extraction", "Top-level navigation extraction", "server/db.js decomposition", "Provider-neutral location contracts", "Customer document price-source audit"]), risk: "high" }),
  base({ id: "cleanup-freeze", phase: 19, sequence: 2, category: "cleanup", title: "Freeze-phase legacy cleanup", status: "legacy", platform: ["shared", "web"], summary: "Remove only after canonical replacements and regression coverage exist.", children: backlogChildren("cleanup-freeze", 19, "cleanup", ["Old Estimate wizard/configurator", "Standalone Supplier Import Lab", "Old calculator", "Old installer-distance path", "Window Types proof dependency migration", "ProjectCalculatorLab naming/routes/tables", "Compatibility projections", "Eventual apps/packages structure", "Obsolete proof/reference/generated assets"]), deferredReason: "Scheduled for controlled freeze phases; nothing is deleted by this roadmap task.", risk: "high" }),
  base({ id: "handbook", phase: 20, sequence: 1, category: "documentation", title: "Technical System Handbook and Error Catalogue", status: "not_started", platform: ["all"], summary: "Canonical ownership, APIs, clients, offline, security, errors and operations documentation.", risk: "medium" }),
  base({ id: "review", phase: 21, sequence: 1, category: "professional-review", title: "Professional Review", status: "not_started", platform: ["all"], summary: "Architecture, security, accessibility, deployment, desktop/mobile and penetration review.", dependencies: ["Production authentication", "Documented architecture"], risk: "critical" }),
  base({ id: "pilot", phase: 22, sequence: 1, category: "external-pilot", title: "Zyle Demo / External Pilot", status: "not_started", platform: ["web", "windows"], summary: "Controlled demonstration after canonical quotation/order boundaries and security prerequisites.", risk: "high" }),
  base({ id: "commercialisation", phase: 23, sequence: 1, category: "commercialisation", title: "Commercialisation", status: "not_started", platform: ["all"], summary: "Product operations, support, billing, deployment and legal/privacy readiness.", dependencies: ["External pilot", "SaaS hardening", "Professional review"], risk: "critical" }),
];

export const PLATFORM_READINESS: PlatformReadiness[] = [
  { platform: "Web", status: "in_progress", summary: "Primary internal client with a strong estimating foundation.", blockers: ["Authentication/RBAC", "Production deployment", "Quotation lifecycle"], nextPrerequisite: "Stabilize App boundaries and deliver production authentication." },
  { platform: "Windows Desktop", status: "not_started", summary: "Feasible thin shell; Tauri is the current candidate subject to validation.", blockers: ["Stable/versioned APIs", "Native authentication", "App decomposition"], nextPrerequisite: "Define shared API client and secure session model." },
  { platform: "iOS", status: "not_started", summary: "Focused field app, not full desktop feature parity.", blockers: ["Field domain", "Offline sync", "PKCE/token storage"], nextPrerequisite: "Design Survey/Field APIs and limited offline model." },
  { platform: "Android", status: "not_started", summary: "Shared React Native field application direction.", blockers: ["Field domain", "Offline sync", "PKCE/token storage"], nextPrerequisite: "Design Survey/Field APIs and limited offline model." },
  { platform: "Tablet", status: "not_started", summary: "Adaptive field experience rather than an independent fourth codebase.", blockers: ["Tablet UX", "Field domain", "Drawing/document APIs"], nextPrerequisite: "Define tablet survey and installation workflows." },
  { platform: "Offline Field Mode", status: "not_started", summary: "Limited offline project snapshots, forms and evidence.", blockers: ["Conflict semantics", "Durable outbox", "Media sync"], nextPrerequisite: "Add server versioning and idempotent operation contracts." },
];

export const DEVELOPMENT_ORDER = [
  "Continuous bounded architectural stabilization",
  "Configurator development continues as a major parallel programme",
  "Review and harden the GBP Customer Quotation preview",
  "Minimal quotation generation / issue lifecycle",
  "Minimal CRM lifecycle categorisation",
  "Controlled Ecofenster internal usage and hardening",
  "Commercial profitability / overhead governance",
  "Acceptance and Canonical Order",
  "Broader CRM lifecycle completion",
  "Communications and Documents",
  "Procurement / Manufacturer workflow",
  "Survey / Installation field model",
  "Workforce / Field Operations",
  "Service / Warranty",
  "Actual-vs-Estimated Reporting",
  "Automation / AI",
  "Platform-client expansion",
  "SaaS / Multi-Tenant hardening",
  "Professional review",
  "External pilot",
  "Commercialisation",
] as const;
