import { useMemo, useState } from "react";
import { buildQuoteComparisonReport } from "../../../shared/quoteComparisonReportModel.js";
import { comparisonStatusLabels, type ComparisonDifferenceStatus, type ComparisonPositionMapping, type QuoteComparison } from "./quoteComparison.types";

type Props = {
  comparison: QuoteComparison;
  busy: boolean;
  onApprove: () => void;
  onCorrectMapping: (mappingId:string,positionId:string|null,status:ComparisonDifferenceStatus,relationship:ComparisonPositionMapping["relationshipKind"],differences?:ComparisonPositionMapping["differences"]) => void;
  onUpdate: (name:string,description:string) => void;
  onCopy: () => void;
  onArchive: () => void;
  onRestore: () => void;
  onDelete: () => void;
};

const statusTone = (value:string) => value === "exact_match" || value === "approved" ? "success" : value.includes("mismatch") || value === "missing" ? "error" : "warning";
const scopeLabel = (value:string) => value === "supply_only" ? "Supply Only" : value === "supply_and_install" ? "Supply + Install" : value === "supply_install_support" ? "Supply + Installation Support" : "Scope review required";
const money = (value:number|null,currency:string|null) => value == null ? "Not supplied" : `${currency || ""} ${value.toLocaleString("en-GB",{minimumFractionDigits:2,maximumFractionDigits:2})}`.trim();
const evidenceLabel = (metric:{basis:string|null;standard:string|null;precision:number|null}) => [metric.basis?.replaceAll("_"," "),metric.standard,metric.precision == null ? null : `${metric.precision} decimal place${metric.precision===1?"":"s"} supplied`].filter(Boolean).join(" · ");
const scopeAmount = (label:string,value:number|null,currency:string|null) => <span><b>{label}</b>{money(value,currency)}</span>;

function RecommendationList({recommendations,message}:{recommendations:Array<{rank:number;label:string;supplierName:string;reason:string}>;message?:string|null}) {
  if (!recommendations.length) return <p className="compare-quotes__muted">{message||"Not enough mapped evidence to produce a reliable ranking."}</p>;
  return <ol className="compare-quotes__recommendations">{recommendations.map(item=><li key={`${item.rank}-${item.supplierName}`}><span>{item.label}</span><strong>{item.supplierName}</strong><p>{item.reason}</p></li>)}</ol>;
}

export default function ComparisonResults({comparison,busy,onApprove,onCorrectMapping,onUpdate,onCopy,onArchive,onRestore,onDelete}:Props) {
  const [view,setView] = useState<"report"|"exceptions"|"advanced">("report");
  const [editingDetails,setEditingDetails] = useState(false);
  const [name,setName] = useState(comparison.name || `${comparison.baselineSnapshot.estimateRef} supplier comparison`);
  const [description,setDescription] = useState(comparison.description || "");
  const report = useMemo(()=>buildQuoteComparisonReport(comparison),[comparison]);
  const exceptionGroups = comparison.proposals.map(proposal=>({proposal,mappings:proposal.positionMappings.filter(mapping=>["review_required","unmapped","information_not_supplied"].includes(mapping.differenceStatus))})).filter(group=>group.mappings.length);

  return <>
    <section className="compare-quotes__baseline ui-card">
      <div><span className="ui-eyebrow">Baseline / reference specification</span><h3>{comparison.baselineSnapshot.estimateRef} · Revision {comparison.baselineSnapshot.revisionNo}</h3><p>{comparison.baselineSnapshot.positions.length} canonical Positions define what was requested. They receive no ranking preference.</p><small><b>Customer commercial source:</b> {comparison.baselineSnapshot.customerCommercial?.kind === "issued_customer_quotation" ? "Issued Customer Quotation PDF" : "Current QuoteSuite Estimate / Project Costing selling values"}.</small></div>
      <div className="compare-quotes__approval"><span className={`ui-status ui-status--${comparison.status === "approved" ? "success" : "warning"}`}>{comparison.status === "approved" ? "Approved comparison" : "Draft · review required"}</span>{comparison.status === "draft_review_required" ? <button className="ui-button ui-button--primary" disabled={busy} onClick={onApprove}>Approve comparison</button> : null}</div>
    </section>

    <section className="compare-quotes__record-tools ui-card">
      {editingDetails ? <div className="compare-quotes__record-edit"><label>Name<input className="ui-input" value={name} maxLength={160} onChange={event=>setName(event.currentTarget.value)} /></label><label>Description<input className="ui-input" value={description} maxLength={1000} onChange={event=>setDescription(event.currentTarget.value)} /></label><div className="ui-action-row"><button className="ui-button" type="button" onClick={()=>setEditingDetails(false)}>Cancel</button><button className="ui-button ui-button--primary" type="button" disabled={busy || !name.trim()} onClick={()=>{onUpdate(name,description);setEditingDetails(false)}}>Save details</button></div></div> : <><div><span className="ui-eyebrow">Comparison record</span><h3>{comparison.name || `${comparison.baselineSnapshot.estimateRef} supplier comparison`}</h3>{comparison.description ? <p>{comparison.description}</p> : null}</div><div className="ui-action-row"><button className="ui-button ui-button--ghost" type="button" onClick={()=>setEditingDetails(true)}>Name / description</button><button className="ui-button ui-button--ghost" type="button" disabled={busy} onClick={onCopy}>Copy</button>{comparison.archivedAt ? <button className="ui-button" type="button" disabled={busy} onClick={onRestore}>Restore</button> : <button className="ui-button" type="button" disabled={busy} onClick={onArchive}>Archive</button>}{comparison.status === "draft_review_required" && !comparison.archivedAt ? <button className="ui-button ui-button--danger" type="button" disabled={busy} onClick={onDelete}>Delete draft</button> : null}</div></>}
    </section>

    <nav className="compare-quotes__view-tabs ui-card" aria-label="Comparison result views">
      <button type="button" className={view === "report" ? "ui-button ui-button--primary" : "ui-button"} onClick={()=>setView("report")}>Comparison Report</button>
      <button type="button" className={view === "exceptions" ? "ui-button ui-button--primary" : "ui-button"} onClick={()=>setView("exceptions")}>Review Exceptions <span>{exceptionGroups.length}</span></button>
      <button type="button" className={view === "advanced" ? "ui-button ui-button--primary" : "ui-button"} onClick={()=>setView("advanced")}>Advanced Mapping</button>
    </nav>

    {view === "report" ? <section className="compare-quotes__report">
      <header className="compare-quotes__report-intro ui-card"><div><span className="ui-eyebrow">Evidence-qualified internal comparison</span><h2>Comparison Report</h2><p>{report.positions.length} Position comparisons · 1 reference Estimate + {comparison.proposals.length} competitor proposal{comparison.proposals.length===1?"":"s"}</p></div><p className="compare-quotes__disclaimer">{report.disclaimer}</p></header>

      <section className="compare-quotes__project-report ui-card"><div><span className="ui-eyebrow">Whole project</span><h3>Overall Comparison Report</h3><p>Specification and dimensional compliance gate value ranking. Net Products / Supply is compared only where it is isolated from extras, delivery and installation.</p></div><div className="compare-quotes__table-wrap"><table><thead><tr><th>Supplier</th><th>Matched</th><th>Compliant</th><th>Qualified</th><th>Mismatch</th><th>Missing</th><th>Review</th><th>Commercial scope</th><th>Headline</th></tr></thead><tbody>{report.suppliers.map(supplier=><tr key={supplier.proposalId}><th>{supplier.supplierName}<small>{supplier.manufacturerName || "Manufacturer not confirmed"}</small></th><td>{supplier.matched}/{report.positions.length}</td><td>{supplier.correct}</td><td>{supplier.acceptable}</td><td>{supplier.materialMismatch}</td><td>{supplier.missing}</td><td>{supplier.unresolved}</td><td><strong>{scopeLabel(supplier.scopeKind)}</strong><small>{supplier.commercial.normalizationReason}</small><div className="compare-quotes__commercial-breakdown">{scopeAmount("Supply net",supplier.commercial.netSupply,supplier.currency)}{supplier.commercial.discountPercentage!=null?<span><b>Discount</b>{supplier.commercial.discountPercentage}% · {money(supplier.commercial.discountAmount,supplier.currency)}</span>:null}{scopeAmount("Extras",supplier.commercial.extras,supplier.currency)}{scopeAmount("Delivery",supplier.commercial.delivery,supplier.currency)}{scopeAmount("Installation",supplier.commercial.installation,supplier.currency)}<span><b>VAT</b>{supplier.commercial.vatStatus.replaceAll("_"," ")}</span></div></td><td>{money(supplier.total,supplier.currency)}</td></tr>)}</tbody></table></div><div><h4>Overall Recommendations</h4><RecommendationList recommendations={report.recommendations} message={report.recommendationMessage}/></div><section className="compare-quotes__clarifications"><h4>Supplier Clarifications</h4>{report.clarifications.map(group=><article key={group.proposalId}><strong>{group.supplierName}</strong><ul>{group.items.map((item,index)=><li key={`${item.category}-${index}`}><b>{item.category.replaceAll("_"," ")}</b> — {item.message}{item.positionReferences.length?` Positions ${item.positionReferences.join(", ")}.`:""}</li>)}</ul></article>)}</section></section>

      <section className="compare-quotes__positions" aria-label="Canonical Position comparisons">{report.positions.map(position=>{
        const hideHardware = /\bfixed\b/i.test(position.configuration) && !/door/i.test(position.configuration);
        return <article className="compare-quotes__position ui-card" key={position.id}>
          <header><div><span className="ui-eyebrow">Position / Type {position.reference}</span><h3>{position.configuration}</h3><p>{position.measurements} · Quantity {position.quantity}{position.roomName ? ` · ${position.roomName}` : ""}</p></div><span className="ui-status ui-status--muted">Reference + {Math.max(0,position.offers.length-1)} competitor offer{position.offers.length===2?"":"s"}</span></header>
          <div className="compare-quotes__table-wrap"><table className="compare-quotes__position-table"><thead><tr><th>Supplier / compliance</th><th>Reference</th><th>Measurements</th><th>System / configuration</th><th>Material / finishes</th><th>Glass</th><th>Ug / Uw evidence</th><th>G / LT</th><th>Security</th>{hideHardware ? null : <th>Hardware</th>}<th>Net supply cost</th></tr></thead><tbody>{position.offers.map(offer=><tr key={`${position.id}-${offer.offerKey||offer.proposalId}`} className={offer.isBaselineReference?"is-reference":""}><th><strong>{offer.supplierName}</strong>{offer.isBaselineReference?<small>Baseline / requested specification</small>:null}{offer.isAlternative ? <small>Alternative / option</small> : null}<span className={`compare-quotes__assessment compare-quotes__assessment--${offer.assessment.tone}`}>{offer.compliance.label}</span><small>{offer.compliance.materialFailures[0]||offer.compliance.compromises[0]||offer.compliance.reviewItems[0]||offer.explanation}</small></th><td>{offer.reference}</td><td>{offer.attributes.measurements}<small>Qty {offer.quantity ?? "not supplied"}</small></td><td>{offer.attributes.productSystem}<small>{offer.attributes.configuration}</small>{offer.attributes.division!=="Not supplied"?<small>Division: {offer.attributes.division}</small>:null}</td><td><b>Material:</b> {offer.attributes.material}<br/><b>In:</b> {offer.attributes.internalFinish}<br/><b>Out:</b> {offer.attributes.externalFinish}{offer.attributes.aluminiumCladding!=="Not supplied"?<><br/><b>Cladding:</b> {offer.attributes.aluminiumCladding}</>:null}{offer.attributes.interfaces!=="Not supplied"?<small>{offer.attributes.interfaces}</small>:null}</td><td>{offer.attributes.glass}</td><td><b>Ug:</b> {offer.attributes.ug}{offer.attributes.thermalEvidence.ug.raw?<small>{evidenceLabel(offer.attributes.thermalEvidence.ug)}</small>:null}<br/><b>Uw:</b> {offer.attributes.uw}{offer.attributes.thermalEvidence.uw.raw?<small>{evidenceLabel(offer.attributes.thermalEvidence.uw)}</small>:null}</td><td><b>G:</b> {offer.attributes.g}<br/><b>LT:</b> {offer.attributes.lt}</td><td>{offer.attributes.security.label}<small>{offer.attributes.security.status.replaceAll("_"," ")}</small></td>{hideHardware ? null : <td>{offer.attributes.hardware}</td>}<td>{money(offer.commercial.netItemCost,offer.currency)}<small>{money(offer.commercial.netQuantityCost,offer.currency)} quantity total</small>{offer.commercial.discountPercentage!=null?<small>List {money(offer.commercial.grossQuantityCost,offer.currency)} · {offer.commercial.discountPercentage}% discount</small>:null}<small>{offer.commercial.comparabilityStatus==="comparable_supply"?"Comparable Products / Supply":"Not comparable — scope/compliance review"}</small></td></tr>)}</tbody></table></div>
          <section className="compare-quotes__position-report"><div><h4>Report</h4><p>{position.report}</p><div className="compare-quotes__findings"><span><b>Best Uw</b>{position.findings.bestUw ? `${position.findings.bestUw.supplierName} · ${position.findings.bestUw.value}` : "Insufficient evidence"}</span><span><b>Best Ug</b>{position.findings.bestUg ? `${position.findings.bestUg.supplierName} · ${position.findings.bestUg.value}` : "Insufficient evidence"}</span><span><b>Best G</b>{position.findings.bestG ? `${position.findings.bestG.supplierName} · ${position.findings.bestG.value}` : "Insufficient evidence"}</span><span><b>Best LT</b>{position.findings.bestLt ? `${position.findings.bestLt.supplierName} · ${position.findings.bestLt.value}` : "Insufficient evidence"}</span>{position.findings.lowestComparablePrice ? <span><b>Lowest comparable price</b>{position.findings.lowestComparablePrice.supplierName} · {money(position.findings.lowestComparablePrice.value,position.findings.lowestComparablePrice.currency)}</span> : <span><b>Lowest comparable price</b>Insufficient evidence</span>}</div></div><div><h4>Recommendations</h4><RecommendationList recommendations={position.recommendations} message={position.recommendationMessage}/></div></section>
        </article>})}</section>
    </section> : null}

    {view === "exceptions" ? <section className="compare-quotes__exceptions ui-card"><header><span className="ui-eyebrow">Review only unresolved evidence</span><h3>Review Exceptions</h3><p>{exceptionGroups.length ? `${exceptionGroups.length} proposal${exceptionGroups.length === 1 ? "" : "s"} contain unresolved evidence. Extracted row counts remain secondary.` : "No unresolved mapping exceptions remain. You can review the Comparison Report."}</p></header>{exceptionGroups.map(({proposal,mappings})=><article key={proposal.id}><div><strong>{proposal.supplierName}</strong><small>{mappings.length} extracted mapping item{mappings.length===1?"":"s"} need review · {mappings.slice(0,3).map(mapping=>mapping.supplierItemReference).join(" · ")}{mappings.length>3?" · …":""}</small></div><span className="ui-status ui-status--warning">{proposal.positionMappings.some(mapping=>mapping.differenceStatus==="unmapped")?"Position mapping unresolved":"Evidence not confirmed"}</span><button type="button" className="ui-button" onClick={()=>setView("advanced")}>Review Mapping Details</button></article>)}</section> : null}

    {view === "advanced" ? <section className="compare-quotes__drilldown ui-card"><header><span className="ui-eyebrow">Engineering / evidence review</span><h3>Advanced Mapping Details</h3><p>Detailed extracted rows, mappings, corrections and provenance remain available here. They are not the normal report.</p></header>{comparison.proposals.map(proposal=><details key={proposal.id}><summary>{proposal.supplierName} · {proposal.positionMappings.length} extracted findings</summary><div className="compare-quotes__mapping-list">{proposal.positionMappings.map(mapping=><div className="compare-quotes__mapping" key={mapping.id}><strong>{mapping.supplierItemReference}</strong><label>Canonical Position<select className="ui-select" value={mapping.canonicalEstimatePositionId || ""} disabled={comparison.status !== "draft_review_required" || busy} onChange={event=>onCorrectMapping(mapping.id,event.currentTarget.value || null,mapping.differenceStatus,event.currentTarget.value ? mapping.relationshipKind : "unmapped",mapping.differences)}><option value="">Unmapped / additional</option>{comparison.baselineSnapshot.positions.map(position=><option key={position.id} value={position.id}>{position.positionRef || position.id}</option>)}</select></label><label>Relationship<select className="ui-select" value={mapping.relationshipKind} disabled={comparison.status !== "draft_review_required" || busy} onChange={event=>onCorrectMapping(mapping.id,mapping.canonicalEstimatePositionId,mapping.differenceStatus,event.currentTarget.value as ComparisonPositionMapping["relationshipKind"],mapping.differences)}>{["exact","grouped","split","missing","additional","alternative","unmapped"].map(value=><option key={value}>{value}</option>)}</select></label><label>Assessment<select className="ui-select" value={mapping.differenceStatus} disabled={comparison.status !== "draft_review_required" || busy} onChange={event=>onCorrectMapping(mapping.id,mapping.canonicalEstimatePositionId,event.currentTarget.value as ComparisonDifferenceStatus,mapping.relationshipKind,mapping.differences)}>{Object.entries(comparisonStatusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><span className={`ui-status ui-status--${statusTone(mapping.differenceStatus)}`}>{mapping.correctedAt ? "Staff corrected" : mapping.provenance.mappingAuthority ? "Auto-mapped" : "Review"}</span></div>)}</div></details>)}</section> : null}
  </>;
}
