import { useState } from "react";
import { createPortal } from "react-dom";
import type { QuoteComparisonReport, QuoteComparisonReportOffer } from "../../../shared/quoteComparisonReportModel.js";
import { resolveManufacturerVisualAssetUrl } from "../manufacturerVisuals/manufacturerVisualAssetUrl";
import { saveQuoteComparisonPdf, saveQuoteComparisonPositionPdf } from "./comparisonPdfExport";

type PrintContext = { clientName:string; clientRef:string; projectName:string };
type Props = { report:QuoteComparisonReport; context:PrintContext; positionReference?:string; onClose:()=>void };
type Position = QuoteComparisonReport["positions"][number];

const money=(value:number|null,currency:string|null)=>value==null?"Not established":`${currency==="GBP"?"£":currency==="EUR"?"€":currency?`${currency} `:""}${value.toLocaleString("en-GB",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const statusLabel=(status:string)=>status==="approved"?"Approved":status==="draft_review_required"?"Draft · review required":status.replaceAll("_"," ");
const scopeLabel=(value:string)=>value==="supply_only"?"Supply Only":value==="supply_and_install"?"Supply + Install":value==="supply_install_support"?"Supply + Installation Support":"Scope not established";
const fieldState:Record<string,string>={reference:"●",match:"✓",difference:"✕",unknown:"?",not_applicable:"—"};

function Footer({page,total,estimateRef}:{page:number;total:number;estimateRef:string}) { return <footer className="comparison-print__footer"><span>QuoteSuite Compare Quotes</span><span>{estimateRef}</span><span>Page {page} of {total}</span></footer>; }

function Drawings({offer,position}:{offer:QuoteComparisonReportOffer;position:string}) {
  return <div className="comparison-print__schedule-drawings">{offer.drawings.map((drawing,index)=><figure className={`comparison-print__schedule-drawing${drawing.status==="available"?"":" is-unavailable"}`} key={`${drawing.mappingId}-${index}`}>{drawing.status==="available"&&drawing.url?<img src={resolveManufacturerVisualAssetUrl(drawing.url)} alt={`${offer.supplierName} source drawing for Position ${position}, source item ${drawing.sourceReference}`}/>:<div><strong>Image unavailable</strong></div>}<figcaption>{drawing.sourceReference}{drawing.sourcePage?` · p${drawing.sourcePage}`:""}</figcaption></figure>)}</div>;
}

function OfferSummary({offer}:{offer:QuoteComparisonReportOffer}) {
  const systems=offer.attributes.systemEvidence ?? [];
  return <><dl className="comparison-print__field-list">{offer.presentationFields.map(field=><div className={`comparison-print__field comparison-print__field--${field.status}`} key={field.key}><dt><i aria-hidden="true">{fieldState[field.status]}</i>{field.label}</dt><dd>{field.value}</dd></div>)}</dl>{offer.annualHeatLoss.status!=="reference"?<small><b>Annual heat-loss comparison:</b> {offer.annualHeatLoss.display}</small>:null}{systems.length?<small>System evidence: {systems.map(source=>`${source.system}${source.systemThermal?` · Uw ${source.systemThermal.raw} for ${source.systemThermal.standardSizeMm?`${source.systemThermal.standardSizeMm.width} × ${source.systemThermal.standardSizeMm.height} mm standard window`:"standard-size window"}`:""}${source.systemSourcePage?` · p${source.systemSourcePage}`:""}`).join("; ")}. Position-specific evidence takes precedence.</small>:null}</>;
}

function Finding({offer}:{offer:QuoteComparisonReportOffer}) {
  return <><b>{offer.isBaselineReference?"Selected supplier":offer.compliance.label}</b><span>{offer.customerFinding.summary}</span>{offer.customerFinding.matches?<span className="is-match"><b>✓</b> {offer.customerFinding.matches}</span>:null}{offer.customerFinding.differs?<span className="is-difference"><b>✕</b> {offer.customerFinding.differs}</span>:null}{offer.customerFinding.confirm?<span className="is-unknown"><b>?</b> {offer.customerFinding.confirm}</span>:null}{offer.customerFinding.confirmation?<span className="is-unknown"><b>Confirm:</b> {offer.customerFinding.confirmation}</span>:null}{offer.customerFinding.disclosure?<span>{offer.customerFinding.disclosure}</span>:null}<span><strong>Recommendation:</strong> {offer.customerFinding.recommendation}</span></>;
}

function PositionBlock({position}:{position:Position}) {
  return <section className="comparison-print__position-block" data-print-position={position.reference}><header><div><span>Position / Type {position.reference}</span><h2>{position.configuration}</h2></div><p>{position.measurements} · Quantity {position.quantity}{position.roomName?` · ${position.roomName}`:""}</p></header><table className="comparison-print__schedule-table"><thead><tr><th>Drawing</th><th>Supplier / item</th><th>What is offered</th><th>Price</th><th>Finding</th></tr></thead><tbody>{position.offers.map(offer=><tr key={offer.offerKey} className={`${offer.isBaselineReference?"is-reference ":""}${offer.isAlternative?"is-alternative":""}`}><td><Drawings offer={offer} position={position.reference}/></td><th><b>{offer.supplierName}</b><span>{offer.reference}</span><small>{offer.isBaselineReference?"Selected supplier / reference":offer.isAlternative?"Alternative / option":offer.relationship==="grouped"?"Grouped supplier solution":"Supplier offer"}</small></th><td><OfferSummary offer={offer}/></td><td><b>{offer.completePositionPriceEligible===false?"No complete Position price":money(offer.commercial.netQuantityCost,offer.currency)}</b>{offer.commercial.netItemCost!=null?<span>Unit: {money(offer.commercial.netItemCost,offer.currency)}</span>:null}<span>Quantity total: {money(offer.commercial.netQuantityCost,offer.currency)}</span>{offer.commercial.discountPercentage!=null?<span>List {money(offer.commercial.grossQuantityCost,offer.currency)} · discount {offer.commercial.discountPercentage}% ({money(offer.commercial.discountAmount,offer.currency)})</span>:null}{offer.commercial.components.length>1?offer.commercial.components.map(component=><span key={component.reference}>{component.reference}: {component.quantity??"?"} × {money(component.netUnitPrice,offer.currency)} = {money(component.netQuantityTotal,offer.currency)}</span>):null}{offer.commercial.supportingComponentCost!=null?<span>Supporting component: {money(offer.commercial.supportingComponentCost,offer.currency)}</span>:null}{offer.priceComparison.amountDifference!=null?<strong>{offer.priceComparison.amountDifference<0?"−":"+"}{money(Math.abs(offer.priceComparison.amountDifference),offer.currency)}{offer.priceComparison.percentageDifference==null?"":` (${offer.priceComparison.percentageDifference>0?"+":""}${offer.priceComparison.percentageDifference.toFixed(1)}%)`} vs selected supplier</strong>:null}<small>{offer.priceComparison.basis}</small></td><td><Finding offer={offer}/></td></tr>)}</tbody></table><footer><b>Position conclusion</b><p>{position.conclusion}</p></footer></section>;
}

function packPositions(positions:Position[]) {
  return positions;
}

export default function ComparisonPrintDocument({report,context,positionReference,onClose}:Props) {
  const [saving,setSaving]=useState(false),[saveMessage,setSaveMessage]=useState("");
  const schedulePages=packPositions(report.positions), total=3+schedulePages.length, status=statusLabel(report.context.status), presentation=report.customerPresentation, projectName=report.context.projectName||context.projectName||"Project not named";
  const questionGroups=presentation.questions.reduce<Record<string,typeof presentation.questions>>((groups,item)=>{(groups[item.supplierName]??=[]).push(item);return groups;},{});
  const focusedPosition=positionReference?report.positions.find((position)=>position.reference===positionReference):null;
  const save=async()=>{setSaving(true);setSaveMessage("");try{const result=focusedPosition?await saveQuoteComparisonPositionPdf(report,context,focusedPosition.reference):await saveQuoteComparisonPdf(report,context);setSaveMessage(`${result.filename} saved as a searchable A4 landscape PDF.`)}catch(error){setSaveMessage(error instanceof Error?error.message:"The PDF could not be saved.")}finally{setSaving(false)}};
  if(focusedPosition)return createPortal(<div className="comparison-print__scrim" role="presentation"><section className="comparison-print__dialog" role="dialog" aria-modal="true" aria-labelledby="comparison-print-title"><div className="comparison-print__controls no-print"><div><strong id="comparison-print-title">Position {focusedPosition.reference} View / Print</strong><small>{status} · one Position · approval is not required · searchable A4 landscape PDF</small>{saveMessage?<span role="status">{saveMessage}</span>:null}</div><div><button type="button" className="ui-button" onClick={onClose}>Close</button><button type="button" className="ui-button" onClick={()=>window.print()}>Print</button><button type="button" className="ui-button ui-button--primary" disabled={saving} onClick={()=>void save()}>{saving?"Preparing PDF…":"Save Position PDF"}</button></div></div><article className="comparison-print__document"><section className="comparison-print-page comparison-print-page--schedule comparison-print-page--focused" data-print-focused-position={focusedPosition.reference}><header className="comparison-print__page-header"><div><span>Supplier comparison</span><h2>Position {focusedPosition.reference}</h2><p>{context.clientName} · {projectName} · {report.context.baselineEstimateRef} Revision {report.context.baselineRevision}</p></div><strong>{status}</strong></header><main><PositionBlock position={focusedPosition}/></main><Footer page={1} total={1} estimateRef={report.context.baselineEstimateRef}/></section></article></section></div>,document.body);
  return createPortal(<div className="comparison-print__scrim" role="presentation"><section className="comparison-print__dialog" role="dialog" aria-modal="true" aria-labelledby="comparison-print-title"><div className="comparison-print__controls no-print"><div><strong id="comparison-print-title">Compare Quotes View / Print</strong><small>{status} · approval is not required to print or save · PDF export preserves searchable text and A4 landscape layout</small>{saveMessage?<span role="status">{saveMessage}</span>:null}</div><div><button type="button" className="ui-button" onClick={onClose}>Close</button><button type="button" className="ui-button" onClick={()=>window.print()}>Print</button><button type="button" className="ui-button ui-button--primary" disabled={saving} onClick={()=>void save()}>{saving?"Preparing PDF…":"Save searchable PDF"}</button></div></div><article className="comparison-print__document">
    <section className="comparison-print-page comparison-print-page--overview" data-print-overview="1"><header className="comparison-print__cover"><span>QuoteSuite</span><h1>Supplier Comparison</h1><p>{report.context.name}</p>{report.context.description?<p>{report.context.description}</p>:null}<strong>{status}</strong></header><main><section className="comparison-print__identity"><div><b>Client</b><span>{context.clientName}</span><small>{context.clientRef}</small></div><div><b>Project</b><span>{projectName}</span><small>{report.context.projectId||"No Project identity supplied"}</small></div><div><b>Reference Estimate</b><span>{report.context.baselineEstimateRef}</span><small>Revision {report.context.baselineRevision} · {report.positions.length} Positions</small></div><div><b>Comparison</b><span>{status}</span><small>Record revision {report.generatedFromRecordRevision}</small></div></section><section className="comparison-print__overview-columns"><article><h2>Reference and scope</h2><p>{presentation.reference}</p><p>{presentation.scope}</p></article><article><h2>How offers are assessed</h2><ol>{presentation.assessmentPriorities.map(item=><li key={item}>{item}</li>)}</ol></article><article><h2>Explained recommendation</h2><p>{presentation.conclusion}</p></article></section><aside className="comparison-print__qualification">{report.disclaimer}</aside></main><Footer page={1} total={total} estimateRef={report.context.baselineEstimateRef}/></section>
    <section className="comparison-print-page comparison-print-page--overview" data-print-overview="2"><header className="comparison-print__page-header"><div><span>Project overview</span><h2>Main differences, thermal evidence and prices</h2><p>Thermal performance and price are reported separately.</p></div><strong>{status}</strong></header><main><section className="comparison-print__supplier-grid">{presentation.suppliers.map(supplier=><article key={supplier.proposalId}><header><h3>{supplier.supplierName}</h3><small>{supplier.manufacturerName||"Manufacturer not confirmed"}</small></header><p>{supplier.coverage}</p><ul>{supplier.mainPoints.length?supplier.mainPoints.map(point=><li key={point}>{point}</li>):<li>No material difference is recorded in the retained evidence.</li>}</ul><dl><div><dt>Thermal evidence</dt><dd>Uw {supplier.thermal.uw?.display||"not confirmed"} · Ug {supplier.thermal.ug?.display||"not confirmed"}<br/>G {supplier.thermal.g?.display||"not confirmed"} · LT {supplier.thermal.lt?.display||"not confirmed"}</dd></div><div><dt>Headline price</dt><dd>{money(supplier.commercial.headlineTotal,supplier.commercial.currency)} · {scopeLabel(supplier.commercial.scopeKind)}</dd></div><div><dt>List / discount / net supply</dt><dd>{money(supplier.commercial.grossSupply,supplier.commercial.currency)} · {supplier.commercial.discountPercentage==null?"discount not established":`${supplier.commercial.discountPercentage}% (${money(supplier.commercial.discountAmount,supplier.commercial.currency)})`} · {money(supplier.commercial.netSupply,supplier.commercial.currency)}</dd></div><div><dt>Extras / delivery / installation</dt><dd>{supplier.commercial.extrasLabels.length?supplier.commercial.extrasLabels.join(", "):"Breakdown not established"} · Delivery {money(supplier.commercial.delivery,supplier.commercial.currency)} · Installation {money(supplier.commercial.installation,supplier.commercial.currency)}</dd></div><div><dt>Comparable supply</dt><dd>{supplier.commercial.established?money(supplier.commercial.netSupply,supplier.commercial.currency):supplier.commercial.explanation}</dd></div></dl></article>)}</section><aside className="comparison-print__qualification"><b>Annual thermal comparison:</b> {report.thermalMethodology.label} {report.thermalMethodology.qualification}</aside></main><Footer page={2} total={total} estimateRef={report.context.baselineEstimateRef}/></section>
    <section className="comparison-print-page comparison-print-page--overview" data-print-overview="3"><header className="comparison-print__page-header"><div><span>Evidence review</span><h2>Outstanding questions and source notes</h2><p>Questions to resolve before a final decision.</p></div><strong>{status}</strong></header><main className="comparison-print__questions-page"><section className="comparison-print__question-grid">{Object.entries(questionGroups).map(([supplier,items])=><article key={supplier}><h3>{supplier}</h3><ul>{items.map((item,index)=><li key={`${supplier}-${index}`}>{item.question}{item.positionReferences.length?` Positions ${item.positionReferences.join(", ")}.`:""}</li>)}</ul></article>)}</section><section className="comparison-print__source-notes"><article><h3>Source register</h3><ul>{report.sourceReferences.map((source,index)=><li key={`${source.sourceId}-${index}`}><b>{source.supplierName}:</b> {source.fileName} · {source.quotationNumber||"reference not supplied"}{source.quotationRevision?` · revision ${source.quotationRevision}`:""}</li>)}</ul></article><article><h3>Interpretation notes</h3><ul>{presentation.interpretationNotes.map(note=><li key={note}>{note}</li>)}</ul></article></section></main><Footer page={3} total={total} estimateRef={report.context.baselineEstimateRef}/></section>
    {schedulePages.map((position,index)=><section className="comparison-print-page comparison-print-page--schedule" data-print-schedule-page={index+1} key={`schedule-${position.id}`}><header className="comparison-print__page-header"><div><span>Position schedule</span><h2>Position {position.reference}</h2><p>Supplier-owned source drawings, offer details, prices and findings.</p></div><strong>{status}</strong></header><main><PositionBlock position={position}/></main><Footer page={4+index} total={total} estimateRef={report.context.baselineEstimateRef}/></section>)}
  </article></section></div>,document.body);
}
