import { useMemo, useState } from "react";
import { buildQuoteComparisonReport } from "../../../shared/quoteComparisonReportModel.js";
import type { Client } from "../../models/types";
import { resolveManufacturerVisualAssetUrl } from "../manufacturerVisuals/manufacturerVisualAssetUrl";
import { comparisonStatusLabels, type ComparisonDifferenceStatus, type ComparisonPositionMapping, type QuoteComparison } from "./quoteComparison.types";
import ComparisonPrintDocument from "./ComparisonPrintDocument";
import "./comparisonPrint.css";

type Props = {
  comparison: QuoteComparison; client: Pick<Client,"clientName"|"clientRef"|"projectName">; busy: boolean;
  onApprove: () => void;
  onCorrectMapping: (mappingId:string,positionId:string|null,status:ComparisonDifferenceStatus,relationship:ComparisonPositionMapping["relationshipKind"],differences?:ComparisonPositionMapping["differences"]) => void;
  onUpdate: (name:string,description:string) => void; onCopy: () => void; onArchive: () => void; onRestore: () => void; onDelete: () => void;
};
type Report = ReturnType<typeof buildQuoteComparisonReport>;
type Offer = Report["positions"][number]["offers"][number];

const statusTone = (value:string) => value === "exact_match" || value === "approved" ? "success" : value.includes("mismatch") || value === "missing" ? "error" : "warning";
const scopeLabel = (value:string) => value === "supply_only" ? "Supply Only" : value === "supply_and_install" ? "Supply + Install" : value === "supply_install_support" ? "Supply + Installation Support" : "Scope not established";
const money = (value:number|null,currency:string|null) => value == null ? "Not established" : `${currency === "GBP" ? "£" : currency === "EUR" ? "€" : currency ? `${currency} ` : ""}${value.toLocaleString("en-GB",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const thermal = (label:string,metric:Offer["attributes"]["thermalEvidence"]["uw"]) => {
  void label;
  if (metric.status === "not_applicable") return "Not applicable";
  if (metric.value == null) return metric.status === "invalid_value" ? `Invalid source value ${metric.raw}` : "Not confirmed";
  if (metric.meaning === "whole_door_ud") return `${metric.raw} (supplier label; whole-door Ud meaning)`;
  if (metric.valueKind === "system_standard") {
    const size=metric.standardSizeMm?`${metric.standardSizeMm.width} × ${metric.standardSizeMm.height} mm`:"standard size";
    return `${metric.raw} (${size}; not actual-Position)`;
  }
  return metric.raw;
};
const fieldState = {reference:"●",match:"✓",difference:"✕",unknown:"?",not_applicable:"—"} as const;
const differenceText=(offer:Offer)=>offer.isBaselineReference||offer.priceComparison.amountDifference==null?null:`${offer.priceComparison.amountDifference<0?"−":"+"}${money(Math.abs(offer.priceComparison.amountDifference),offer.currency)} (${offer.priceComparison.percentageDifference==null?"percentage unavailable":`${offer.priceComparison.percentageDifference>0?"+":""}${offer.priceComparison.percentageDifference.toFixed(1)}%`}) vs selected supplier`;

function OfferDrawings({offer,positionReference}:{offer:Offer;positionReference:string}) {
  return <div className="compare-quotes__schedule-drawings" data-supplier={offer.supplierName} data-alternative={offer.isAlternative?"true":"false"}>{offer.drawings.map((drawing,index)=><figure className={`compare-quotes__schedule-drawing${drawing.status === "available" ? "" : " is-unavailable"}`} key={`${drawing.mappingId}-${drawing.role||"source"}-${index}`} title={drawing.reason||undefined} data-source-reference={drawing.sourceReference} data-image-status={drawing.status}>{drawing.status === "available" && drawing.url ? <img src={resolveManufacturerVisualAssetUrl(drawing.url)} alt={`${offer.supplierName} source drawing for Position ${positionReference}, source item ${drawing.sourceReference}`} loading="lazy"/> : <div role="img" aria-label={`${offer.supplierName}, ${drawing.sourceReference}: Image unavailable`}><strong>Image unavailable</strong></div>}<figcaption>{drawing.sourceReference}{drawing.sourcePage ? ` · page ${drawing.sourcePage}` : ""}</figcaption></figure>)}</div>;
}

function OfferedDetails({offer}:{offer:Offer}) {
  const sources=offer.attributes.systemEvidence ?? [];
  return <div className="compare-quotes__offered-details compare-quotes__field-list">{offer.presentationFields.map(field=><span className={`compare-quotes__field compare-quotes__field--${field.status}`} key={field.key}><i aria-hidden="true">{fieldState[field.status]}</i><b>{field.label}</b><em>{field.thermal?thermal(field.label,field.thermal):field.value}</em></span>)}{offer.annualHeatLoss.status!=="reference"?<small><b>Annual heat-loss comparison:</b> {offer.annualHeatLoss.display}</small>:null}{sources.length?<small>System evidence: {sources.map(source=>`${source.system}${source.systemThermal?` · Uw ${source.systemThermal.raw} for ${source.systemThermal.standardSizeMm?`${source.systemThermal.standardSizeMm.width} × ${source.systemThermal.standardSizeMm.height} mm standard window`:"standard-size window"}`:""}${source.systemSourcePage?` · page ${source.systemSourcePage}`:""}`).join("; ")}. Position-specific evidence takes precedence.</small>:null}</div>;
}

function PriceDetails({offer}:{offer:Offer}) {
  return <div className="compare-quotes__price-details"><strong>{offer.completePositionPriceEligible===false?"No complete Position price":money(offer.commercial.netQuantityCost,offer.currency)}</strong>{offer.commercial.netItemCost != null ? <span>Unit: {money(offer.commercial.netItemCost,offer.currency)}</span> : null}<span>Quantity total: {offer.commercial.netQuantityCost==null?"Not established":money(offer.commercial.netQuantityCost,offer.currency)}</span>{offer.commercial.discountPercentage != null ? <span>List {money(offer.commercial.grossQuantityCost,offer.currency)} · discount {offer.commercial.discountPercentage}% ({money(offer.commercial.discountAmount,offer.currency)})</span> : null}{offer.commercial.components.length>1?offer.commercial.components.map(component=><span key={component.reference}>{component.reference}: {component.quantity??"?"} × {money(component.netUnitPrice,offer.currency)} = {money(component.netQuantityTotal,offer.currency)}</span>):null}{offer.commercial.supportingComponentCost!=null?<span>Supporting component: {money(offer.commercial.supportingComponentCost,offer.currency)}</span>:null}{differenceText(offer)?<b>{differenceText(offer)}</b>:null}<small>{offer.priceComparison.basis}</small></div>;
}

function FindingDetails({offer}:{offer:Offer}) {
  const evidence=offer.referenceAssessment;
  return <div className="compare-quotes__finding-details"><span className={`compare-quotes__assessment compare-quotes__assessment--${offer.assessment.tone}`}>{offer.isBaselineReference ? "Selected reference" : offer.compliance.label}</span>{evidence.verificationNotes.map(note=><p key={note}><b>Reference note:</b> {note}</p>)}<p>{offer.customerFinding.summary}</p>{offer.customerFinding.matches?<p className="is-match"><b>✓</b> {offer.customerFinding.matches}</p>:null}{offer.customerFinding.differs?<p className="is-difference"><b>✕</b> {offer.customerFinding.differs}</p>:null}{offer.customerFinding.confirm?<p className="is-unknown"><b>?</b> {offer.customerFinding.confirm}</p>:null}{offer.customerFinding.confirmation?<p className="is-unknown"><b>Confirm:</b> {offer.customerFinding.confirmation}</p>:null}{offer.customerFinding.disclosure?<p>{offer.customerFinding.disclosure}</p>:null}<p><b>Recommendation:</b> {offer.customerFinding.recommendation}</p></div>;
}

export default function ComparisonResults({comparison,client,busy,onApprove,onCorrectMapping,onUpdate,onCopy,onArchive,onRestore,onDelete}:Props) {
  const [view,setView] = useState<"report"|"exceptions"|"advanced">("report");
  const [printTarget,setPrintTarget] = useState<string|null>(null), [editingDetails,setEditingDetails] = useState(false);
  const [name,setName] = useState(comparison.name || `${comparison.baselineSnapshot.estimateRef} supplier comparison`), [description,setDescription] = useState(comparison.description || "");
  const report = useMemo(()=>buildQuoteComparisonReport(comparison),[comparison]), presentation=report.customerPresentation;
  const questionGroups=presentation.questions.reduce<Record<string,typeof presentation.questions>>((groups,item)=>{(groups[item.supplierName]??=[]).push(item);return groups;},{});
  const exceptionGroups = comparison.proposals.map(proposal=>({proposal,mappings:proposal.positionMappings.filter(mapping=>["review_required","unmapped","information_not_supplied"].includes(mapping.differenceStatus))})).filter(group=>group.mappings.length);
  return <>
    <section className="compare-quotes__baseline ui-card"><div><span className="ui-eyebrow">Baseline / reference specification</span><h3>{comparison.baselineSnapshot.estimateRef} · Revision {comparison.baselineSnapshot.revisionNo}</h3><p>{comparison.baselineSnapshot.positions.length} canonical Positions define what was requested. They receive no ranking preference.</p><small><b>Customer commercial source:</b> {comparison.baselineSnapshot.customerCommercial?.kind === "issued_customer_quotation" ? "Issued Customer Quotation PDF" : "Current QuoteSuite Estimate / Project Costing selling values"}.</small></div><div className="compare-quotes__approval"><span className={`ui-status ui-status--${comparison.status === "approved" ? "success" : "warning"}`}>{comparison.status === "approved" ? "Approved comparison" : "Draft · review required"}</span>{comparison.status === "draft_review_required" ? <button className="ui-button ui-button--primary" disabled={busy} onClick={onApprove}>Approve comparison</button> : null}</div></section>
    <section className="compare-quotes__record-tools ui-card">{editingDetails ? <div className="compare-quotes__record-edit"><label>Name<input className="ui-input" value={name} maxLength={160} onChange={event=>setName(event.currentTarget.value)} /></label><label>Description<input className="ui-input" value={description} maxLength={1000} onChange={event=>setDescription(event.currentTarget.value)} /></label><div className="ui-action-row"><button className="ui-button" type="button" onClick={()=>setEditingDetails(false)}>Cancel</button><button className="ui-button ui-button--primary" type="button" disabled={busy || !name.trim()} onClick={()=>{onUpdate(name,description);setEditingDetails(false)}}>Save details</button></div></div> : <><div><span className="ui-eyebrow">Comparison record</span><h3>{comparison.name || `${comparison.baselineSnapshot.estimateRef} supplier comparison`}</h3>{comparison.description ? <p>{comparison.description}</p> : null}</div><div className="ui-action-row"><button className="ui-button ui-button--primary" type="button" onClick={()=>setPrintTarget("all")}>Print / Save PDF</button><button className="ui-button ui-button--ghost" type="button" onClick={()=>setEditingDetails(true)}>Name / description</button><button className="ui-button ui-button--ghost" type="button" disabled={busy} onClick={onCopy}>Copy</button>{comparison.archivedAt ? <button className="ui-button" type="button" disabled={busy} onClick={onRestore}>Restore</button> : <button className="ui-button" type="button" disabled={busy} onClick={onArchive}>Archive</button>}{comparison.status === "draft_review_required" && !comparison.archivedAt ? <button className="ui-button ui-button--danger" type="button" disabled={busy} onClick={onDelete}>Delete draft</button> : null}</div></>}</section>
    <nav className="compare-quotes__view-tabs ui-card" aria-label="Comparison result views"><button type="button" className={view === "report" ? "ui-button ui-button--primary" : "ui-button"} onClick={()=>setView("report")}>Comparison Report</button><button type="button" className={view === "exceptions" ? "ui-button ui-button--primary" : "ui-button"} onClick={()=>setView("exceptions")}>Review Exceptions <span>{exceptionGroups.length}</span></button><button type="button" className={view === "advanced" ? "ui-button ui-button--primary" : "ui-button"} onClick={()=>setView("advanced")}>Advanced Mapping</button></nav>
    {view === "report" ? <section className="compare-quotes__report">
      <header className="compare-quotes__report-intro ui-card"><div><span className="ui-eyebrow">Plain-language, evidence-qualified comparison</span><h2>Supplier Comparison</h2><p>{report.positions.length} Positions · {report.suppliers.length} supplier offer{report.suppliers.length===1?"":"s"}</p></div><p className="compare-quotes__disclaimer">{report.disclaimer}</p></header>
      <section className="compare-quotes__customer-overview ui-card"><header><div><span className="ui-eyebrow">Reference and scope</span><h3>Project overview</h3></div><span className={`ui-status ui-status--${comparison.status === "approved" ? "success" : "warning"}`}>{comparison.status === "approved" ? "Approved" : "Draft · review required"}</span></header><div className="compare-quotes__overview-grid"><article><h4>Reference</h4><p>{presentation.reference}</p><p>{presentation.scope}</p></article><article><h4>How offers are assessed</h4><ol>{presentation.assessmentPriorities.map(item=><li key={item}>{item}</li>)}</ol></article><article><h4>Conclusion</h4><p>{presentation.conclusion}</p></article></div>
        <div className="compare-quotes__supplier-overview">{presentation.suppliers.map(supplier=><article key={supplier.proposalId}><header><strong>{supplier.supplierName}</strong><small>{supplier.manufacturerName || "Manufacturer not confirmed"}</small></header><p>{supplier.coverage}</p>{supplier.mainPoints.length?<ul>{supplier.mainPoints.map(point=><li key={point}>{point}</li>)}</ul>:<p>No material difference is recorded in the retained evidence.</p>}<div className="compare-quotes__thermal-line"><b>Thermal evidence</b><span>Uw {supplier.thermal.uw?.display || "not confirmed"} · Ug {supplier.thermal.ug?.display || "not confirmed"} · G {supplier.thermal.g?.display || "not confirmed"} · LT {supplier.thermal.lt?.display || "not confirmed"}</span></div><div className="compare-quotes__commercial-line"><b>Headline {money(supplier.commercial.headlineTotal,supplier.commercial.currency)}</b><span>List {money(supplier.commercial.grossSupply,supplier.commercial.currency)} · Discount {supplier.commercial.discountPercentage==null?"not established":`${supplier.commercial.discountPercentage}%`} · Net {money(supplier.commercial.netSupply,supplier.commercial.currency)}</span>{supplier.commercial.extrasLabels.length?<span>Extras: {supplier.commercial.extrasLabels.join(", ")} {money(supplier.commercial.extras,supplier.commercial.currency)}</span>:null}<small>{scopeLabel(supplier.commercial.scopeKind)} · {supplier.commercial.explanation}</small></div></article>)}</div><p className="compare-quotes__thermal-method"><b>Annual thermal comparison:</b> {report.thermalMethodology.label} {report.thermalMethodology.qualification}</p>
        <section className="compare-quotes__questions"><h4>Outstanding questions</h4>{presentation.questions.length?<div>{Object.entries(questionGroups).map(([supplier,questions])=><article key={supplier}><strong>{supplier}</strong><ul>{questions.map((item,index)=><li key={`${supplier}-${index}`}>{item.question}{item.positionReferences.length?` Positions ${item.positionReferences.join(", ")}.`:""}</li>)}</ul></article>)}</div>:<p>No outstanding questions are generated from the retained evidence.</p>}</section>
        <details className="compare-quotes__interpretation"><summary>Sources and interpretation notes</summary><div><section><h4>Source references</h4><ul>{report.sourceReferences.map((source,index)=><li key={`${source.sourceId}-${index}`}><b>{source.supplierName}:</b> {source.fileName} · {source.quotationNumber || "reference not supplied"}{source.quotationRevision?` · revision ${source.quotationRevision}`:""}</li>)}</ul></section><section><h4>How terms are interpreted</h4><ul>{presentation.interpretationNotes.map(note=><li key={note}>{note}</li>)}</ul></section></div></details>
      </section>
      <section className="compare-quotes__positions" aria-label="Canonical Position comparisons">{report.positions.map(position=><article className="compare-quotes__position compare-quotes__position--schedule ui-card" key={position.id} data-position-reference={position.reference}><header><div><span className="ui-eyebrow">Position / Type {position.reference}</span><h3>{position.configuration}</h3><p>{position.measurements} · Quantity {position.quantity}{position.roomName ? ` · ${position.roomName}` : ""}</p></div><div className="compare-quotes__position-actions"><span className="ui-status ui-status--muted">{position.offers.length} assessed offer{position.offers.length===1?"":"s"}</span><button type="button" className="ui-button ui-button--ghost" onClick={()=>setPrintTarget(position.reference)}>View / Save Position</button></div></header><div className="compare-quotes__table-wrap"><table className="compare-quotes__schedule-table"><thead><tr><th>Drawing</th><th>Supplier / item</th><th>What is offered</th><th>Price</th><th>Finding</th></tr></thead><tbody>{position.offers.map(offer=><tr key={`${position.id}-${offer.offerKey}`} className={`${offer.isBaselineReference?"is-reference ":""}${offer.isAlternative?"is-alternative":""}`}><td><OfferDrawings offer={offer} positionReference={position.reference}/></td><th><strong>{offer.supplierName}</strong><span>{offer.reference}</span><small>{offer.isBaselineReference?"Reference specification":offer.isAlternative?"Alternative / option":offer.relationship==="grouped"?"Grouped supplier solution":"Supplier offer"}</small></th><td><OfferedDetails offer={offer}/></td><td><PriceDetails offer={offer}/></td><td><FindingDetails offer={offer}/></td></tr>)}</tbody></table></div><footer className="compare-quotes__position-conclusion"><strong>Position conclusion</strong><p>{position.conclusion}</p></footer></article>)}</section>
    </section> : null}
    {view === "exceptions" ? <section className="compare-quotes__exceptions ui-card"><header><span className="ui-eyebrow">Review only unresolved evidence</span><h3>Review Exceptions</h3><p>{exceptionGroups.length ? `${exceptionGroups.length} proposal${exceptionGroups.length === 1 ? "" : "s"} contain unresolved evidence. Extracted row counts remain secondary.` : "No unresolved mapping exceptions remain. You can review the Comparison Report."}</p></header>{exceptionGroups.map(({proposal,mappings})=><article key={proposal.id}><div><strong>{proposal.supplierName}</strong><small>{mappings.length} extracted mapping item{mappings.length===1?"":"s"} need review · {mappings.slice(0,3).map(mapping=>mapping.supplierItemReference).join(" · ")}{mappings.length>3?" · …":""}</small></div><span className="ui-status ui-status--warning">{proposal.positionMappings.some(mapping=>mapping.differenceStatus==="unmapped")?"Position mapping unresolved":"Evidence not confirmed"}</span><button type="button" className="ui-button" onClick={()=>setView("advanced")}>Review Mapping Details</button></article>)}</section> : null}
    {view === "advanced" ? <section className="compare-quotes__drilldown ui-card"><header><span className="ui-eyebrow">Engineering / evidence review</span><h3>Advanced Mapping Details</h3><p>Detailed extracted rows, mappings, corrections and provenance remain available here. They are not the normal report.</p></header>{comparison.proposals.map(proposal=><details key={proposal.id}><summary>{proposal.supplierName} · {proposal.positionMappings.length} extracted findings</summary><div className="compare-quotes__mapping-list">{proposal.positionMappings.map(mapping=><div className="compare-quotes__mapping" key={mapping.id}><strong>{mapping.supplierItemReference}</strong><label>Canonical Position<select className="ui-select" value={mapping.canonicalEstimatePositionId || ""} disabled={comparison.status !== "draft_review_required" || busy} onChange={event=>onCorrectMapping(mapping.id,event.currentTarget.value || null,mapping.differenceStatus,event.currentTarget.value ? mapping.relationshipKind : "unmapped",mapping.differences)}><option value="">Unmapped / additional</option>{comparison.baselineSnapshot.positions.map(position=><option key={position.id} value={position.id}>{position.positionRef || position.id}</option>)}</select></label><label>Relationship<select className="ui-select" value={mapping.relationshipKind} disabled={comparison.status !== "draft_review_required" || busy} onChange={event=>onCorrectMapping(mapping.id,mapping.canonicalEstimatePositionId,mapping.differenceStatus,event.currentTarget.value as ComparisonPositionMapping["relationshipKind"],mapping.differences)}>{["exact","grouped","split","missing","additional","alternative","unmapped"].map(value=><option key={value}>{value}</option>)}</select></label><label>Assessment<select className="ui-select" value={mapping.differenceStatus} disabled={comparison.status !== "draft_review_required" || busy} onChange={event=>onCorrectMapping(mapping.id,mapping.canonicalEstimatePositionId,event.currentTarget.value as ComparisonDifferenceStatus,mapping.relationshipKind,mapping.differences)}>{Object.entries(comparisonStatusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><span className={`ui-status ui-status--${statusTone(mapping.differenceStatus)}`}>{mapping.correctedAt ? "Staff corrected" : mapping.provenance.mappingAuthority ? "Auto-mapped" : "Review"}</span></div>)}</div></details>)}</section> : null}
    {printTarget ? <ComparisonPrintDocument report={report} context={{clientName:client.clientName,clientRef:client.clientRef,projectName:comparison.projectName || client.projectName}} positionReference={printTarget==="all"?undefined:printTarget} onClose={()=>setPrintTarget(null)}/> : null}
  </>;
}
