import assert from "node:assert/strict";
import test from "node:test";
import os from "node:os";
import path from "node:path";
import { mkdtemp, rm } from "node:fs/promises";
import sqlite3 from "sqlite3";
import { open } from "sqlite";
import { classifyNotification, decodeGmailNotification, resolveNotificationConfiguration, resolveWatchLifecycle } from "../server/features/communications/communicationLiveSync.js";
import { createCommunicationsService } from "../server/features/communications/communicationsService.js";
import { createGmailProvider } from "../server/features/communications/gmailProvider.js";

const baseMessage=(overrides={})=>({provider:"google_workspace",providerMessageId:"message-1",threadId:"thread-1",direction:"inbound",folder:"inbox",status:"received",from:["Sender <sender@example.test>"],to:["mailbox@example.test"],cc:[],bcc:[],subject:"Provider change",snippet:"Changed",bodyHtml:"<p>Changed</p>",bodyText:"Changed",attachments:[],sentAt:"2026-08-27T12:00:00.000Z",unread:true,starred:false,important:false,labels:[{id:"INBOX",name:"Inbox",system:true}],threadCount:1,links:[],...overrides});
const thread=(item)=>({...item,threadMessages:[item],threadCount:1});
const envelope=(messageId,historyId)=>({message:{messageId,publishTime:"2026-08-27T12:01:00.000Z",data:Buffer.from(JSON.stringify({emailAddress:"mailbox@example.test",historyId})).toString("base64url")}});

async function fixture(t){
  const root=await mkdtemp(path.join(os.tmpdir(),"qs-mail-live-")),db=await open({filename:path.join(root,"test.db"),driver:sqlite3.Database});
  await db.exec(`CREATE TABLE communication_messages(id TEXT PRIMARY KEY,provider TEXT NOT NULL,provider_message_id TEXT UNIQUE,provider_thread_id TEXT,mailbox_id TEXT,direction TEXT NOT NULL,folder TEXT NOT NULL,status TEXT NOT NULL,from_json TEXT NOT NULL,to_json TEXT NOT NULL,cc_json TEXT NOT NULL,bcc_json TEXT NOT NULL,subject TEXT NOT NULL,body_html TEXT NOT NULL,body_text TEXT NOT NULL,in_reply_to_provider_message_id TEXT,links_json TEXT NOT NULL,error_message TEXT,sent_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,provider_state_json TEXT NOT NULL DEFAULT '{}');CREATE TABLE communication_attachments(id TEXT PRIMARY KEY,communication_message_id TEXT NOT NULL,file_name TEXT NOT NULL,media_type TEXT NOT NULL,size_bytes INTEGER NOT NULL,storage_key TEXT,provider_attachment_id TEXT,drive_file_id TEXT,sha256 TEXT,created_at TEXT NOT NULL,content_id TEXT,is_inline INTEGER NOT NULL DEFAULT 0);CREATE TABLE communication_provider_sync_states(provider TEXT NOT NULL,provider_account_id TEXT NOT NULL,mailbox_view TEXT NOT NULL,provider_cursor TEXT,status TEXT NOT NULL,last_attempt_at TEXT,last_success_at TEXT,error_message TEXT,updated_at TEXT NOT NULL,PRIMARY KEY(provider,provider_account_id,mailbox_view));CREATE TABLE communication_provider_watch_states(provider TEXT NOT NULL,provider_account_id TEXT NOT NULL,mode TEXT NOT NULL,status TEXT NOT NULL,watch_history_id TEXT,watch_registered_at TEXT,watch_expiration_at TEXT,last_reconciled_history_id TEXT,last_notification_at TEXT,last_reconciled_at TEXT,projection_version INTEGER NOT NULL DEFAULT 0,error_message TEXT,updated_at TEXT NOT NULL,PRIMARY KEY(provider,provider_account_id));CREATE TABLE communication_provider_notifications(provider TEXT NOT NULL,provider_account_id TEXT NOT NULL,notification_id TEXT NOT NULL,provider_cursor TEXT NOT NULL,received_at TEXT NOT NULL,processed_at TEXT,outcome TEXT NOT NULL,PRIMARY KEY(provider,provider_account_id,notification_id));`);
  t.after(async()=>{await db.close();await rm(root,{recursive:true,force:true})});return db;
}
const workspace={async status(){return{connected:true,state:"connected",account:{id:"account-1",email:"mailbox@example.test"},scopes:[],capabilities:{gmail:{available:true}}}}};

test("Gmail Pub/Sub payloads are signals and duplicate/out-of-order positions are deterministic",()=>{
  assert.deepEqual(decodeGmailNotification(envelope("notice-1","101")),{notificationId:"notice-1",emailAddress:"mailbox@example.test",historyId:"101",publishedAt:"2026-08-27T12:01:00.000Z"});
  assert.equal(classifyNotification({notificationIdSeen:true,incomingHistoryId:"102",reconciledHistoryId:"100"}),"duplicate");
  assert.equal(classifyNotification({incomingHistoryId:"99",reconciledHistoryId:"100"}),"out_of_order");
  assert.equal(classifyNotification({incomingHistoryId:"101",reconciledHistoryId:"100"}),"reconcile");
});

test("notification signal reconciles external messages, mailbox state, Sent, Drafts and labels without duplicates",async t=>{
  const db=await fixture(t),items={"thread-new":baseMessage({providerMessageId:"message-new",threadId:"thread-new",subject:"New incoming"}),"thread-state":baseMessage({providerMessageId:"message-state",threadId:"thread-state",folder:"trash",unread:false,starred:true,labels:[{id:"TRASH",name:"Bin",system:true},{id:"Label_customer",name:"Customers/Renamed",system:false}]}),"thread-archive":baseMessage({providerMessageId:"message-archive",threadId:"thread-archive",folder:"other",labels:[]}),"thread-sent":baseMessage({providerMessageId:"message-sent",threadId:"thread-sent",folder:"sent",direction:"outbound",status:"sent",labels:[{id:"SENT",name:"Sent",system:true}]}),"thread-draft":baseMessage({providerMessageId:"message-draft",threadId:"thread-draft",folder:"drafts",direction:"outbound",status:"draft",labels:[{id:"DRAFT",name:"Drafts",system:true}]})};let historyCalls=0;
  const gmail={async listHistory(){historyCalls+=1;return{historyId:"101",changedThreadIds:Object.keys(items),deletedMessageIds:[]}},async readThread(id){return thread(items[id])},async currentHistoryId(){return"101"}};
  const service=createCommunicationsService(db,{workspace,gmail,notificationConfig:{mode:"push",configured:true,topicName:"projects/example/topics/gmail"},verifyNotification:async()=>true});
  await service.repository.saveWatchState("google_workspace","account-1",{mode:"push",status:"active",watchHistoryId:"100",lastReconciledHistoryId:"100",projectionVersion:0});
  const result=await service.receiveNotification(envelope("notice-101","101"));assert.equal(result.outcome,"processed");assert.equal(result.changedThreadCount,5);assert.equal(historyCalls,1);
  const state=await service.repository.findByProviderId("google_workspace","message-state");assert.equal(state.folder,"trash");assert.equal(state.unread,false);assert.equal(state.starred,true);assert.equal((await service.repository.findByProviderId("google_workspace","message-sent")).folder,"sent");assert.equal((await service.repository.findByProviderId("google_workspace","message-draft")).folder,"drafts");assert.equal((await db.get("SELECT COUNT(*) count FROM communication_messages")).count,5);
  assert.equal((await service.receiveNotification(envelope("notice-101","101"))).outcome,"duplicate");assert.equal((await service.receiveNotification(envelope("notice-099","99"))).outcome,"out_of_order");assert.equal(historyCalls,1);
});

test("watch lifecycle registers, renews before expiry and reports local fallback without pretending push exists",async t=>{
  assert.equal(resolveNotificationConfiguration({}).mode,"bounded_reconciliation");assert.equal(resolveWatchLifecycle({watch_expiration_at:"2026-08-27T12:00:00.000Z"},{now:Date.parse("2026-08-27T12:00:01.000Z")}).state,"expired");assert.equal(resolveWatchLifecycle({watch_expiration_at:"2026-09-02T08:00:00.000Z",watch_registered_at:"2026-08-26T08:00:00.000Z"},{now:Date.parse("2026-08-27T12:00:00.000Z")}).state,"renewal_due");
  const db=await fixture(t);let registrations=0;const service=createCommunicationsService(db,{workspace,gmail:{async watch({topicName}){registrations+=1;assert.equal(topicName,"projects/example/topics/gmail");return{historyId:"500",expirationAt:"2026-09-01T00:00:00.000Z"}}},notificationConfig:{mode:"push",configured:true,topicName:"projects/example/topics/gmail"}});const state=await service.maintainWatch();assert.equal(registrations,1);assert.equal(state.status,"active");assert.equal(state.watch_history_id,"500");
  const publicState=await service.changeState();assert.equal(publicState.pushConfigured,true);assert.equal(publicState.watchStatus,"active");assert.doesNotMatch(JSON.stringify(publicState),/projects\/example|service.account|token/i);
});

test("Gmail watch adapter sends only the configured Pub/Sub topic and persists safe response evidence",async()=>{let request;const provider=createGmailProvider({async googleFetch(url,init){request={url:String(url),init};return new Response(JSON.stringify({historyId:"700",expiration:"1788134400000"}),{status:200,headers:{"Content-Type":"application/json"}})}}),result=await provider.watch({topicName:"projects/example/topics/gmail"});assert.match(request.url,/\/users\/me\/watch$/);assert.deepEqual(JSON.parse(request.init.body),{topicName:"projects/example/topics/gmail"});assert.equal(result.historyId,"700");assert.ok(result.expirationAt)});

test("disconnect stops an active watch and reconnect state registers a fresh watch",async t=>{const db=await fixture(t);let stopped=0;const service=createCommunicationsService(db,{workspace,gmail:{async stopWatch(){stopped+=1;return{ok:true}}},notificationConfig:{mode:"push",configured:true,topicName:"projects/example/topics/gmail"}});await service.repository.saveWatchState("google_workspace","account-1",{mode:"push",status:"active",watchHistoryId:"800",watchRegisteredAt:"2026-08-27T10:00:00.000Z",watchExpirationAt:"2026-09-02T10:00:00.000Z",projectionVersion:2});const state=await service.stopWatch();assert.equal(stopped,1);assert.equal(state.status,"stopped");assert.equal(resolveWatchLifecycle(state).action,"register")});

test("mailbox metadata is re-read so provider label create, rename and delete changes reach navigation",async t=>{const db=await fixture(t),snapshots=[[{id:"Label_old",name:"Old",type:"user"}],[{id:"Label_old",name:"Renamed",type:"user"},{id:"Label_new",name:"New",type:"user"}],[{id:"Label_new",name:"New",type:"user"}]],gmail={async labels(){return snapshots.shift()}};const service=createCommunicationsService(db,{workspace,gmail});assert.equal((await service.mailbox()).labels[0].name,"Old");assert.deepEqual((await service.mailbox()).labels.map(label=>label.name),["Renamed","New"]);assert.deepEqual((await service.mailbox()).labels.map(label=>label.name),["New"])});

test("push endpoint contract fails closed when authenticated deployment verification is unavailable",async t=>{const db=await fixture(t),service=createCommunicationsService(db,{workspace,gmail:{},notificationConfig:{mode:"bounded_reconciliation",configured:false,topicName:null}});await assert.rejects(()=>service.receiveNotification(envelope("notice-1","101")),error=>error.status===503&&error.code==="gmail_push_not_configured")});

test("expired notification history performs one controlled multi-mailbox recovery without clearing cache",async t=>{
  const db=await fixture(t),views=[];let current=0;const gmail={async listHistory(){const error=new Error("Expired");error.historyExpired=true;throw error},async list({folder}){views.push(folder);current+=1;return{messages:[thread(baseMessage({providerMessageId:`recovered-${folder}`,threadId:`thread-${folder}`,folder:folder==="trash"||folder==="spam"||folder==="sent"||folder==="drafts"?folder:"inbox"}))],nextPageToken:null}},async currentHistoryId(){return"302"}};
  const service=createCommunicationsService(db,{workspace,gmail,notificationConfig:{mode:"push",configured:true,topicName:"projects/example/topics/gmail"},verifyNotification:async()=>true});await service.repository.save(baseMessage({id:"cached",providerMessageId:"cached",subject:"Visible cached mail"}));await service.repository.saveWatchState("google_workspace","account-1",{mode:"push",status:"active",watchHistoryId:"300",lastReconciledHistoryId:"300",projectionVersion:0});const result=await service.receiveNotification(envelope("notice-302","302"));assert.equal(result.strategy,"expired_history_full_sync");assert.deepEqual(views,["inbox","sent","drafts","trash","spam"]);assert.ok(await service.repository.findByProviderId("google_workspace","cached"));assert.equal(current,5);
});

test("confirmed QuoteSuite mutation is immediate and matching history remains idempotent",async t=>{
  const db=await fixture(t),changed=baseMessage({providerMessageId:"message-command",threadId:"thread-command",unread:false,labels:[{id:"INBOX",name:"Inbox",system:true}]});let commands=0;const modifyingWorkspace={async status(){return{connected:true,state:"connected",account:{id:"account-1",email:"mailbox@example.test"},scopes:["https://www.googleapis.com/auth/gmail.modify"],capabilities:{gmail:{available:true}}}}};const gmail={async command(){commands+=1;return{ok:true}},async readThread(){return thread(changed)},async listHistory(){return{historyId:"201",changedThreadIds:["thread-command"],deletedMessageIds:[]}},async currentHistoryId(){return"201"}};
  const service=createCommunicationsService(db,{workspace:modifyingWorkspace,gmail,notificationConfig:{mode:"push",configured:true,topicName:"projects/example/topics/gmail"},verifyNotification:async()=>true});await service.command({threadIds:["thread-command"],command:"mark_read"});assert.equal(commands,1);assert.equal((await service.repository.findByProviderId("google_workspace","message-command")).unread,false);await service.repository.saveWatchState("google_workspace","account-1",{mode:"push",status:"active",watchHistoryId:"200",lastReconciledHistoryId:"200",projectionVersion:0});await service.receiveNotification(envelope("notice-201","201"));assert.equal((await db.get("SELECT COUNT(*) count FROM communication_messages WHERE provider_message_id='message-command'")).count,1);
});
