import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {calculateCustomerDiscount,calculateSupplierCommercialPolicy} from '../server/features/projectCalculatorLab/supplierCommercialPricing.js';

test('standard policy, project supplier discount, and client discount retain separate ownership',()=>{const supplier=calculateSupplierCommercialPolicy({pricingBasis:'manufacturer_list',manufacturerListAmount:'40000',quotedAmount:'40000',quotedCurrency:'GBP',paidInQuotedCurrency:true,settlementCurrency:'GBP',discountPolicy:{type:'compound',stages:[{percentage:'25',sequence:1},{percentage:'10',sequence:2},{percentage:'5',sequence:3}]},projectDiscount:{mode:'percentage',percentage:'5'},settlementFxSnapshot:{quotedToSettlementRate:'1',settlementToGbpRate:'1'}}),client=calculateCustomerDiscount('40000',{mode:'percentage',percentage:'5'});assert.equal(supplier.standardNetBuyingAmount,'25650.00');assert.equal(supplier.projectDiscountAmount,'1282.50');assert.equal(supplier.discountedSupplierPurchaseAmount,'24367.50');assert.equal(client.amount,'2000.00');assert.equal(client.finalSellingPrice,'38000.00');assert.equal(supplier.discountedSupplierPurchaseAmount,'24367.50');});

test('fixed supplier and client reductions expose equivalent percentages without changing their bases',()=>{const supplier=calculateSupplierCommercialPolicy({pricingBasis:'net_buying_price',quotedAmount:'20000',quotedCurrency:'GBP',paidInQuotedCurrency:true,settlementCurrency:'GBP',projectDiscount:{mode:'fixed',amount:'1000'},settlementFxSnapshot:{quotedToSettlementRate:'1',settlementToGbpRate:'1'}}),client=calculateCustomerDiscount('30000',{mode:'fixed',amount:'1500'});assert.equal(supplier.projectDiscountPercentage,'5.00');assert.equal(supplier.discountedSupplierPurchaseAmount,'19000.00');assert.equal(client.percentage,'5.00');assert.equal(client.finalSellingPrice,'28500.00');});

test('client editor is owned by Commercial Summary and follows Products immediately',async()=>{const review=await readFile('src/features/projectCalculatorLab/SupplierCommercialReview.tsx','utf8'),worksheet=await readFile('src/features/projectCalculatorLab/ScenarioCostingWorksheet.tsx','utf8'),product=worksheet.indexOf('<span>Products / Supply Only</span>'),discount=worksheet.indexOf('<strong>Customer / Client Discount</strong>'),net=worksheet.indexOf('Products after Client Discount'),extras=worksheet.indexOf('[["Extras",extrasSale]');assert.doesNotMatch(review,/Customer \/ retailer discount|Customer \/ Client Discount/);assert.ok(product<discount&&discount<net&&net<extras);assert.match(worksheet,/−\{money\(customerDiscountAmount\)\}/);assert.doesNotMatch(worksheet,/Original supplier purchase total/i);});

test('supplier review exposes only the additional project discount while standard stages remain Admin-owned',async()=>{const review=await readFile('src/features/projectCalculatorLab/SupplierCommercialReview.tsx','utf8'),admin=await readFile('src/features/admin/AdminSupplierCommercialDefaults.tsx','utf8');assert.match(review,/Additional project supplier discount/);assert.doesNotMatch(review,/compound discount stage|order-value threshold/i);assert.match(admin,/discount|threshold|supplier/i);});
