import test from "node:test";
import assert from "node:assert/strict";
import os from "node:os";
import path from "node:path";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import sqlite3 from "sqlite3";
import { open } from "sqlite";
import { calculateFrameFixingPositions, calculateInstallationMaterials, calculatePackerRequirement, roundToPurchasablePack } from "../server/features/projectCalculatorLab/installationMaterials.js";
import { initializeSupplierCommercialSchema } from "../server/schema/supplierCommercialSchema.js";
import { createCalculatorAdminService, snapshotCalculatorAdminConfiguration } from "../server/features/projectCalculatorLab/calculatorAdminService.js";
import { createProjectCalculatorLabService } from "../server/features/projectCalculatorLab/projectCalculatorLabService.js";
import { deriveProjectCostingCommercialResult } from "../src/features/projectCalculatorLab/domain/projectCostingCommercialResult.js";

const source=(page:number)=>({file:"ggf-installation-guide.pdf",printedPage:page});
const timber={key:"ggf_timber",source:"GGF/default",cornerOffsetMinMm:150,cornerOffsetMaxMm:250,maxIntermediateSpacingMm:600,allFourSides:false,centralHeadSillAboveWidthMm:1800,provenance:source(24)};
const aluminium={key:"ggf_aluminium",source:"GGF/default",cornerOffsetMinMm:100,cornerOffsetMaxMm:150,maxIntermediateSpacingMm:600,allFourSides:true,provenance:source(25)};

test("GGF frame rules calculate each side per individual frame and multiply physical quantity",()=>{const normal=calculateFrameFixingPositions({widthMm:1200,heightMm:1400,quantity:2,frameMaterial:"Timber",rule:timber});assert.equal(normal.leftJambFixingCount,3);assert.equal(normal.rightJambFixingCount,3);assert.equal(normal.headFixingCount,0);assert.equal(normal.sillFixingCount,0);assert.equal(normal.totalFixingPositionsPerFrame,6);assert.equal(normal.totalFixingPositions,12);for(const side of [normal.positionsMm.leftJamb,normal.positionsMm.rightJamb]){assert.ok(side[0]>=150&&side[0]<=250);for(let i=1;i<side.length;i++)assert.ok(side[i]-side[i-1]<=600)}const wide=calculateFrameFixingPositions({widthMm:1801,heightMm:1400,quantity:1,frameMaterial:"Timber",rule:timber});assert.equal(wide.headFixingCount,1);assert.equal(wide.sillFixingCount,1);const alu=calculateFrameFixingPositions({widthMm:2000,heightMm:1400,quantity:1,frameMaterial:"Aluminium",rule:aluminium});assert.equal(alu.headFixingCount,4);assert.equal(alu.sillFixingCount,4);assert.equal(alu.source.printedPage,25)});

test("brackets drive separate frame and substrate fixing quantities",()=>{const rules={defaultContingencyPercent:0,defaultBracketLengthMm:200,frameScrewsPerBracket:3,packerCalculationMode:"manual",packersPerFixingPosition:null,packersPerFrame:null,buildingTypes:{concrete:{fixingsPerBracket:2},brick_block:{fixingsPerBracket:1}},frameFixingRules:{Timber:timber}};const position={displayReference:"W1",widthMm:1200,heightMm:1400,quantity:2,framePerimeterMetres:"10.4",frameMaterial:"Timber",includedInCurrentEstimate:true,classification:"standard",sourceSnapshot:{}};const concrete=calculateInstallationMaterials({positions:[position],rules,options:{fixingMethod:"brackets",buildingType:"concrete",bracketLengthMm:200,packerCalculationMode:"manual"},catalogue:[]});assert.equal(concrete.totals.brackets,12);assert.equal(concrete.totals.frameScrews,36);assert.equal(concrete.totals.substrateFixings,24);const brick=calculateInstallationMaterials({positions:[position],rules,options:{fixingMethod:"brackets",buildingType:"brick_block",bracketLengthMm:150,packerCalculationMode:"manual"},catalogue:[]});assert.equal(brick.totals.substrateFixings,12);assert.equal(brick.bracketLengthMm,150)});

test("missing frame and substrate specifications remain explicit",()=>{assert.equal(calculateFrameFixingPositions({widthMm:1000,heightMm:1000,quantity:1,frameMaterial:"Unknown",rule:null}).status,"unavailable");const rules={defaultContingencyPercent:0,defaultBracketLengthMm:200,frameScrewsPerBracket:3,packerCalculationMode:"manual",buildingTypes:{icf:{fixingsPerBracket:null}},frameFixingRules:{Timber:timber}},position={displayReference:"W1",widthMm:1200,heightMm:1400,quantity:1,framePerimeterMetres:"5.2",frameMaterial:"Timber",sourceSnapshot:{}};const result=calculateInstallationMaterials({positions:[position],rules,options:{fixingMethod:"brackets",buildingType:"icf",packerCalculationMode:"manual"},catalogue:[]});assert.equal(result.positionCalculations[0].substrateFixingStatus,"Pending product specification");assert.equal(result.purchasing.substrateFixings.purchaseCost,null)});

test("contingency precedes one pack rounding operation and exposes surplus",()=>{assert.deepEqual(roundToPurchasablePack(73,100,"12.50"),{requiredQuantity:73,packsRequired:1,purchaseQuantity:100,unusedAllowance:27,purchaseCost:"12.50",status:"priced"});assert.equal(roundToPurchasablePack(73,null).status,"Pending product specification")});

test("configured catalogue products are selected automatically and roll requirements round after contingency",()=>{const rules={defaultContingencyPercent:10,defaultBracketLengthMm:200,frameScrewsPerBracket:3,packerCalculationMode:"per_fixing_position",packersPerFixingPosition:1,buildingTypes:{brick_block:{fixingsPerBracket:1}},frameFixingRules:{Timber:timber}},position={id:"p1",displayReference:"W1",widthMm:1200,heightMm:1400,quantity:2,framePerimeterMetres:"30",frameMaterial:"Timber",includedInCurrentEstimate:true,classification:"standard",sourceSnapshot:{}},catalogue=[{id:"me508",category:"illbruck_me508",label:"ME508 20m",rateType:"roll",priceAmount:"30",active:true,variant:{rollLengthM:20}},{id:"bracket",category:"bracket",label:"200 bracket",rateType:"pack",priceAmount:"50",active:true,variant:{bracketLengthMm:200,packQuantity:10}},{id:"frame",category:"frame_screw",label:"Frame screw",rateType:"pack",priceAmount:"10",active:true,variant:{packQuantity:100}},{id:"masonry",category:"masonry_fixing",label:"Masonry",rateType:"pack",priceAmount:"12",active:true,variant:{packQuantity:50}},{id:"packer",category:"packer",label:"Packer",rateType:"pack",priceAmount:"8",active:true,variant:{packQuantity:25}}],result=calculateInstallationMaterials({positions:[position],rules,options:{fixingMethod:"brackets",buildingType:"brick_block",defaultFrameMaterial:"Timber",contingencyPercent:10,bracketLengthMm:200,packerCalculationMode:"per_fixing_position",me508ProductId:"me508",packerProductId:"packer"},catalogue});assert.equal(result.totalPerimeterM,30);assert.equal(result.sealingPurchasing.ME508.requiredLengthM,33);assert.equal(result.sealingPurchasing.ME508.rollsRequired,2);assert.equal(result.sealingPurchasing.ME508.purchaseCost,"60.00");assert.equal(result.purchasing.brackets.packsRequired,2);assert.equal(result.purchasing.frameScrews.packsRequired,1);assert.equal(result.purchasing.substrateFixings.packsRequired,1);assert.equal(result.packers.finalRequiredQuantity,result.totals.fixingPositions);assert.equal(result.packers.purchaseCost,"8.00")});

test("packer calculation supports adjustment and mixed-size pack allocation without invented defaults",()=>{const missing=calculatePackerRequirement({fixingPositions:10,mode:"per_fixing_position",packersPerFixingPosition:null,frameQuantity:1,manualAdjustment:0,mix:[]});assert.equal(missing.status,"unavailable");const result=calculatePackerRequirement({fixingPositions:10,mode:"per_fixing_position",packersPerFixingPosition:1,frameQuantity:1,manualAdjustment:2,mix:[{productId:"test-only-2mm",requiredQuantity:7,packQuantity:10,packPrice:"12.50"},{productId:"test-only-5mm",requiredQuantity:5,packQuantity:10,packPrice:null}]});assert.equal(result.finalRequiredQuantity,12);assert.equal(result.allocatedQuantity,12);assert.equal(result.unallocatedQuantity,0);assert.equal(result.mix[0].purchasing.purchaseCost,"12.50");assert.equal(result.mix[1].purchasing.purchaseQuantity,10)});

test("Estimate catalogue/rule snapshots remain immutable after Administration changes",async t=>{const root=await mkdtemp(path.join(os.tmpdir(),"qs-install-materials-")),db=await open({filename:path.join(root,"test.db"),driver:sqlite3.Database});t.after(async()=>{await db.close();await rm(root,{recursive:true,force:true})});await db.exec("CREATE TABLE estimates(id TEXT PRIMARY KEY);CREATE TABLE clients(id TEXT PRIMARY KEY);");await initializeSupplierCommercialSchema(db);await db.run("INSERT INTO project_calculator_lab_scenarios(id,name,currency,package_code,origin,revision_number,installation_opening_count,created_at,updated_at) VALUES('scenario','Test','GBP','full_installation','manual',1,0,'now','now')");const before=await snapshotCalculatorAdminConfiguration(db,"scenario",1,"before"),admin=createCalculatorAdminService(db),next={...(before.rules.installation_materials_v1.value as Record<string,unknown>),frameScrewsPerBracket:4};await admin.updateRule("installation_materials_v1",next);const persisted=JSON.parse((await db.get("SELECT rules_json FROM project_calculator_lab_catalogue_snapshots WHERE scenario_id='scenario'")).rules_json);assert.equal(persisted.installation_materials_v1.value.frameScrewsPerBracket,3);assert.equal((await admin.getConfiguration()).rules.installation_materials_v1.value.frameScrewsPerBracket,4)});

test("Estimate assumption override creates costing history without rewriting Administration",async t=>{const root=await mkdtemp(path.join(os.tmpdir(),"qs-install-override-")),db=await open({filename:path.join(root,"test.db"),driver:sqlite3.Database});t.after(async()=>{await db.close();await rm(root,{recursive:true,force:true})});await db.exec("CREATE TABLE estimates(id TEXT PRIMARY KEY,positions_json TEXT DEFAULT '[]',project_address_json TEXT DEFAULT '{}',client_project_address_json TEXT DEFAULT '{}',client_customer_address_json TEXT DEFAULT '{}',postcode TEXT);CREATE TABLE clients(id TEXT PRIMARY KEY);");await initializeSupplierCommercialSchema(db);await db.run("INSERT INTO project_calculator_lab_scenarios(id,name,currency,package_code,origin,revision_number,installation_opening_count,created_at,updated_at) VALUES('scenario','Test','GBP','full_installation','manual',1,0,'now','now')");await db.run("INSERT INTO project_calculator_lab_markup_rules VALUES('scenario','0','0','0','0','0','0','0','0','now')");await db.run("INSERT INTO project_calculator_lab_options(scenario_id,options_json,updated_at) VALUES('scenario','{}','now')");const captured=await snapshotCalculatorAdminConfiguration(db,"scenario",1,"before"),adminBefore=(captured.rules.installation_materials_v1.value as any).defaultBracketLengthMm,service=createProjectCalculatorLabService(db,{exchangeRateProvider:async()=>({rawRate:"1",provider:"test",quotedAt:"now"})}),updated=await service.updateInstallationMaterials("scenario",{fixingMethod:"brackets",buildingType:"concrete",bracketLengthMm:250,contingencyPercent:"12",packerCalculationMode:"manual",packerMix:[]});assert.equal((updated.options?.installationMaterials as any).bracketLengthMm,250);assert.equal(updated.revisionNumber,2);assert.equal(((await createCalculatorAdminService(db).getConfiguration()).rules.installation_materials_v1.value as any).defaultBracketLengthMm,adminBefore);assert.equal((await db.get("SELECT reason FROM project_calculator_lab_revisions WHERE scenario_id='scenario' ORDER BY version_number DESC LIMIT 1")).reason,"installation_materials_assumptions_changed")});

test("legacy Estimate snapshots gain Installation Materials only on explicit Estimate action",async t=>{const root=await mkdtemp(path.join(os.tmpdir(),"qs-install-legacy-")),db=await open({filename:path.join(root,"test.db"),driver:sqlite3.Database});t.after(async()=>{await db.close();await rm(root,{recursive:true,force:true})});await db.exec("CREATE TABLE estimates(id TEXT PRIMARY KEY,positions_json TEXT DEFAULT '[]',project_address_json TEXT DEFAULT '{}',client_project_address_json TEXT DEFAULT '{}',client_customer_address_json TEXT DEFAULT '{}',postcode TEXT);CREATE TABLE clients(id TEXT PRIMARY KEY);");await initializeSupplierCommercialSchema(db);await db.run("INSERT INTO project_calculator_lab_scenarios(id,name,currency,package_code,origin,revision_number,installation_opening_count,created_at,updated_at) VALUES('legacy','Legacy','GBP','supply_only','manual',1,0,'now','now')");await db.run("INSERT INTO project_calculator_lab_markup_rules VALUES('legacy','0','0','0','0','0','0','0','0','now')");await db.run("INSERT INTO project_calculator_lab_options(scenario_id,options_json,updated_at) VALUES('legacy','{}','now')");await snapshotCalculatorAdminConfiguration(db,"legacy",1,"before");const snapshot=await db.get("SELECT rules_json FROM project_calculator_lab_catalogue_snapshots WHERE scenario_id='legacy'"),rules=JSON.parse(snapshot.rules_json);delete rules.installation_materials_v1;await db.run("UPDATE project_calculator_lab_catalogue_snapshots SET rules_json=? WHERE scenario_id='legacy'",JSON.stringify(rules));const service=createProjectCalculatorLabService(db,{exchangeRateProvider:async()=>({rawRate:"1",provider:"test",quotedAt:"now"})});assert.equal((await service.getScenario("legacy")).installationMaterials,null);const updated=await service.updateInstallationMaterials("legacy",{enabled:true,fixingMethod:"brackets",buildingType:"concrete",defaultFrameMaterial:"Timber",contingencyPercent:"15",packerCalculationMode:"manual"});assert.ok(updated.catalogueSnapshot?.rules.installation_materials_v1);assert.equal((updated.options?.installationMaterials as any).enabled,true);assert.equal(updated.revisionNumber,2)});

test("Installation Materials purchase cost uses the established category markup and overall totals",()=>{const scenario:any={id:"test",currency:"GBP",products:[],supplierCosts:[],packageItems:[],unpricedSupplierTotals:[],supplierPackageUplifts:[],installationMaterials:{purchaseCost:"100.00"},markups:{product:"0",extras:"0",transport:"0",siteVisit:"0",equipment:"0",installation:"0",materials:"25",duties:"0"},options:null,customerPricing:{discount:{mode:"percentage",percentage:"0",amount:"0"},fixedSellingPrice:{enabled:false,amount:"0",currency:"GBP",basis:"ex_vat"}}};const result=deriveProjectCostingCommercialResult(scenario);assert.equal(result.materialsCost,"100.00");assert.equal(result.materialsSale,"125.00");assert.equal(result.projectCost,"100.00");assert.equal(result.actualSale,"125.00")});

test("worksheet keeps the six costing stages and Estimate-only commercial choices in compact modal actions",async()=>{const worksheet=await readFile("src/features/projectCalculatorLab/ScenarioCostingWorksheet.tsx","utf8"),supplier=await readFile("src/features/projectCalculatorLab/SupplierCommercialReview.tsx","utf8"),assumptions=await readFile("src/features/projectCalculatorLab/InstallationMaterialsAssumptions.tsx","utf8"),catalogue=await readFile("server/features/projectCalculatorLab/calculatorCatalogueDefaults.js","utf8");for(const [index,heading] of [[1,"Products / Supply Only"],[2,"Extras"],[3,"Transport"],[4,"Site Visit / Travel"],[5,"Installation Materials"],[6,"Installation"]] as const)assert.match(worksheet,new RegExp(`index=\\{${index}\\}[\\s\\S]{0,180}title="${heading}"`));assert.match(worksheet,/commercialView === "internal" \|\|[\s\S]{0,120}scenario\.packageCode/);assert.match(worksheet,/Installation Materials Included\?/);assert.match(worksheet,/Installation Included\?/);assert.match(supplier,/Amend Commercial Choices/);assert.match(supplier,/role="dialog"/);assert.match(supplier,/Estimate-only/);assert.match(assumptions,/Advanced Installation Material Overrides/);assert.match(assumptions,/Administration defaults remain unchanged/);assert.match(catalogue,/AB005 Membrane Shears/);assert.doesNotMatch(worksheet,/title="Equipment Hire"/)});

test("Stage 5 and 6 controls use compact canonical editors and omit obsolete placeholder rows",async()=>{const [worksheet,configure,assumptions,admin]=await Promise.all([readFile("src/features/projectCalculatorLab/ScenarioCostingWorksheet.tsx","utf8"),readFile("src/features/projectCalculatorLab/ConfigureInstallation.tsx","utf8"),readFile("src/features/projectCalculatorLab/InstallationMaterialsAssumptions.tsx","utf8"),readFile("src/features/projectCalculatorLab/CalculatorAdminCatalogue.tsx","utf8")]);for(const group of ["Sealing &amp; Airtightness","Mechanical Fixings","Tools","Team / Programme","Labour","Travel / Vehicles","Food / Accommodation","Survey / Support / Cills","Skip / Lifting Review"])assert.match(worksheet,new RegExp(group.replace("/","\\/")));for(const legacy of ["Labour — Not configured","Travel — Not configured","Accommodation — Not configured","Food allowance — Not configured","Staying-away allowance — Not configured"])assert.doesNotMatch(worksheet,new RegExp(legacy));assert.match(configure,/ui-modal-backdrop/);assert.match(configure,/Project postcode required/);assert.match(configure,/No capable installation company available/);assert.match(configure,/Insufficient available crew configuration/);assert.match(configure,/Company\/team base postcode required/);assert.match(configure,/Google routing unavailable\/not configured/);assert.match(configure,/Recommended Installation Company/);for(const control of ["Default frame material","Fixing method","Bracket length","Contingency","Packer calculation","ME508 variant","TP600 variant","Packer product"])assert.match(assumptions,new RegExp(control,"i"));assert.match(admin,/Edit Installation Catalogue Item/);assert.match(admin,/Pack ex-VAT purchase price/);assert.match(admin,/Pending specification/);assert.doesNotMatch(worksheet,/Project Cost \(Ex VAT\)/)});


test("Installation Materials No excludes automatic material costs while retaining override evidence",()=>{const scenario:any={id:"test",currency:"GBP",products:[],supplierCosts:[],packageItems:[],unpricedSupplierTotals:[],supplierPackageUplifts:[],installationMaterials:{purchaseCost:"100.00"},markups:{product:"0",extras:"0",transport:"0",siteVisit:"0",equipment:"0",installation:"0",materials:"25",duties:"0"},options:{installationMaterials:{enabled:false}},customerPricing:{discount:{mode:"percentage",percentage:"0",amount:"0"},fixedSellingPrice:{enabled:false,amount:"0",currency:"GBP",basis:"ex_vat"}}};const result=deriveProjectCostingCommercialResult(scenario);assert.equal(result.materialsCost,"0.00");assert.equal(result.materialsSale,"0.00");assert.equal((scenario.options.installationMaterials as any).enabled,false)});
