import test from "node:test";
import assert from "node:assert/strict";
import os from "node:os";
import path from "node:path";
import { mkdtemp, rm } from "node:fs/promises";
import sqlite3 from "sqlite3";
import { open } from "sqlite";
import { calculateApplicableCillQuantity, calculateInstallationProgramme, rankInstallationTeams } from "../server/features/projectCalculatorLab/installationProgramme.js";
import { createInstallationWorkforceService } from "../server/features/projectCalculatorLab/installationWorkforceService.js";
import { initializeSupplierCommercialSchema } from "../server/schema/supplierCommercialSchema.js";
import { CALCULATION_RULE_DEFAULTS } from "../server/features/projectCalculatorLab/calculatorCatalogueDefaults.js";
import { deriveProjectCostingCommercialResult } from "../src/features/projectCalculatorLab/domain/projectCostingCommercialResult.js";
import { createProjectCalculatorLabService } from "../server/features/projectCalculatorLab/projectCalculatorLabService.js";

const rules=CALCULATION_RULE_DEFAULTS.installation_programme_v1;
const standard=(reference:string,quantity:number)=>({id:reference,displayReference:reference,productClass:"Window",quantity,widthMm:1200,heightMm:1400,includedInCurrentEstimate:true,classification:"standard",sourceSnapshot:{}});
const profile=(overrides:Record<string,unknown>={})=>({enabled:true,selectedTeamId:"team",crewSize:2,travelMode:"auto",vehicleCount:1,mileageRate:"0.55",installerDayRate:"350",foodPerPersonDay:"30",accommodationPerPersonNight:"125",mobilisationSetOutHours:0,skipDecision:"not_required",liftingDecision:"not_required",route:{oneWayMiles:10,oneWayDurationMinutes:30},positionRequirements:{},...overrides});

test("two-person standard programme completes 28 units within the working week with travel-aware day one",()=>{const result=calculateInstallationProgramme({positions:[standard("W",28)],rules,profile:profile()});assert.equal(result.programmeDays,5);assert.equal(result.standardUnitsPerDay,7);assert.equal(result.recommendFourPersonTeam,false);assert.equal(result.costs.labour,"3500.00");assert.equal(result.costs.food,"300.00");assert.equal(result.travel.chargeableMiles,"100.00");assert.equal(result.costs.mileage,"55.00");assert.equal(result.costs.cillInstallation,"700.00");assert.equal(result.costs.purchaseCost,"4555.00")});

test("four-person programme uses conservative twelve-unit capacity and recommends four people above 28",()=>{const result=calculateInstallationProgramme({positions:[standard("W",29)],rules,profile:profile({crewSize:4})});assert.equal(result.standardUnitsPerDay,12);assert.equal(result.recommendFourPersonTeam,true);assert.equal(result.programmeDays,3);assert.equal(result.costs.labour,"4200.00")});

test("specialist task rules preserve concurrent crew and productive duration",()=>{const positions=[{...standard("LS",1),productClass:"Lift-and-slide",widthMm:2400},{...standard("BF",1),productClass:"Bifold",widthMm:2500}];const result=calculateInstallationProgramme({positions,rules,profile:profile({crewSize:4})});assert.deepEqual(result.tasks.map(item=>[item.minimumCrew,item.durationHours]).sort((a,b)=>Number(a[0])-Number(b[0])),[[3,3],[4,4]]);assert.equal(result.programmeDays,1)});

test("kit specialist duration is position-owned and missing duration remains Review Required",()=>{const item={...standard("KIT",1),productClass:"Sliding/gliding door",widthMm:3000};const missing=calculateInstallationProgramme({positions:[item],rules,profile:profile({crewSize:4,positionRequirements:{KIT:{kitFormat:true}}})});assert.match(missing.reviewRequired.join(" "),/kit-format duration/i);const selected=calculateInstallationProgramme({positions:[item],rules,profile:profile({crewSize:4,positionRequirements:{KIT:{kitFormat:true,durationHours:12}}})});assert.equal(selected.tasks.reduce((sum,task)=>sum+task.durationHours,0),12);assert.equal(selected.tasks.every(task=>task.minimumCrew===3),true)});

test("stay-away recommendation, vehicles, mileage, food and accommodation are deterministic",()=>{const result=calculateInstallationProgramme({positions:[standard("W",14)],rules,profile:profile({route:{oneWayMiles:100,oneWayDurationMinutes:120},vehicleCount:2})});assert.equal(result.travel.mode,"stay_away");assert.equal(result.travel.chargeableMiles,"200.00");assert.equal(result.costs.mileage,"220.00");assert.equal(result.allowances.nights,result.programmeDays-1);assert.equal(result.costs.accommodation,(result.allowances.nights*2*125).toFixed(2));assert.equal(result.costs.food,(result.programmeDays*2*30).toFixed(2))});

test("cill installation derives physical qualifying-window quantity and excludes door families",()=>{const positions=[standard("W1",1),standard("W2",2),{...standard("D1",3),productClass:"Entrance door"},{...standard("LS1",2),productClass:"Lift-and-slide door"},{...standard("BF1",2),productClass:"Bifold"},{...standard("W-NO-CILL",4),sourceSnapshot:{canonicalPosition:{positionType:"Window",cillRequired:false}}},{...standard("ALT",7),classification:"alternative",includedInCurrentEstimate:false}];assert.equal(calculateApplicableCillQuantity(positions),3);const result=calculateInstallationProgramme({positions,rules,profile:profile({cillApplicableQuantity:999})});assert.equal(result.allowances.cillApplicableQuantity,3);assert.equal(result.allowances.cillInstallationRate,"25.00");assert.equal(result.costs.cillInstallation,"75.00");assert.equal(Number(result.costs.purchaseCost),Number(result.costs.labour)+Number(result.costs.mileage)+Number(result.costs.food)+Number(result.costs.accommodation)+Number(result.costs.support)+Number(result.costs.survey)+75)});

test("team ranking filters capability and crew before route",()=>{const teams:any[]=[{id:"near",active:true,normalCrewSize:2,capabilities:["standard_windows"]},{id:"capable",active:true,normalCrewSize:4,capabilities:["standard_windows","bifolds"]},{id:"far",active:true,normalCrewSize:4,capabilities:["standard_windows","bifolds"]}];const ranked=rankInstallationTeams({teams,requiredCapabilities:["bifolds"],minimumCrew:4,routesByTeamId:{capable:{durationMinutes:50,distanceMiles:40},far:{durationMinutes:80,distanceMiles:30}}});assert.deepEqual(ranked.map(item=>item.id),["capable","far"])});

test("Installation workforce persists companies, installer rates, team membership and capabilities",async t=>{const root=await mkdtemp(path.join(os.tmpdir(),"qs-install-workforce-")),db=await open({filename:path.join(root,"test.db"),driver:sqlite3.Database});t.after(async()=>{await db.close();await rm(root,{recursive:true,force:true})});await initializeSupplierCommercialSchema(db);const service=createInstallationWorkforceService(db);let state=await service.saveCompany({name:"Test Installations",postcode:"AB1 2CD",active:true});const company=state.companies[0];state=await service.saveInstaller({companyId:company.id,name:"Installer One",dayRate:"375.00",capabilities:["standard_windows"],active:true});const installer=state.installers[0];state=await service.saveTeam({companyId:company.id,name:"Team A",normalCrewSize:4,basePostcode:"AB1 2CD",capabilities:["standard_windows","bifolds"],installerIds:[installer.id],active:true});assert.equal(state.teams[0].installerIds[0],installer.id);assert.equal(state.installers[0].dayRate,"375.00");assert.deepEqual(state.teams[0].capabilities,["standard_windows","bifolds"])});

test("calculated Installation purchase cost uses the canonical Installation markup",()=>{const scenario:any={id:"scenario",currency:"GBP",products:[],supplierCosts:[],packageItems:[],unpricedSupplierTotals:[],supplierPackageUplifts:[],installationProgramme:{costs:{purchaseCost:"1000.00"}},markups:{product:"0",extras:"0",transport:"0",siteVisit:"0",equipment:"0",installation:"30",materials:"0",duties:"0"},options:{installationRequired:true,installationProfile:{enabled:true}},customerPricing:{discount:{mode:"percentage",percentage:"0",amount:"0"},fixedSellingPrice:{enabled:false,amount:"0",currency:"GBP",basis:"ex_vat"}}};const result=deriveProjectCostingCommercialResult(scenario);assert.equal(result.installationGbp,"1000.00");assert.equal(result.installationSale,"1300.00");assert.equal(result.projectCost,"1000.00");assert.equal(result.actualSale,"1300.00")});

test("Estimate explicitly snapshots Installation configuration without rewriting Administration",async t=>{const root=await mkdtemp(path.join(os.tmpdir(),"qs-install-profile-")),db=await open({filename:path.join(root,"test.db"),driver:sqlite3.Database});t.after(async()=>{await db.close();await rm(root,{recursive:true,force:true})});await db.exec("CREATE TABLE estimates(id TEXT PRIMARY KEY);CREATE TABLE clients(id TEXT PRIMARY KEY);");await initializeSupplierCommercialSchema(db);const workforce=createInstallationWorkforceService(db);let state=await workforce.saveCompany({name:"Install Co",postcode:"AA1 1AA"});const company=state.companies[0];state=await workforce.saveTeam({companyId:company.id,name:"Four",normalCrewSize:4,basePostcode:"AA1 1AA",capabilities:["standard_windows"],installerIds:[]});const service=createProjectCalculatorLabService(db,{exchangeRateProvider:async()=>({rawRate:"1",provider:"test",quotedAt:"2026-08-21"})});let scenario=await service.createScenario({origin:"manual",name:"Estimate Installation",currency:"GBP",packageType:"full_installation"});scenario=await service.addManualProduct(scenario.id,{reference:"W1",productClass:"Window",widthMm:1200,heightMm:1400,quantity:12,installationOpeningCount:12,unitSupplyCost:"0",totalSupplyCost:"0"});scenario=await service.updateOptions(scenario.id,{installationRequired:true});scenario=await service.updateInstallationProfile(scenario.id,{enabled:true,selectedTeamId:state.teams[0].id,crewSize:4,travelMode:"daily_travel",vehicleCount:1,mobilisationSetOutHours:0,route:{oneWayMiles:10,oneWayDurationMinutes:30},skipDecision:"not_required",liftingDecision:"not_required"});assert.equal(scenario.selectedInstallationTeam?.id,state.teams[0].id);assert.equal(scenario.installationProgramme?.standardUnitsPerDay,12);assert.equal(scenario.installationProgramme?.costs.labour,"2800.00");assert.equal(scenario.revisionNumber,4);const snapshot=await db.get("SELECT options_json FROM project_calculator_lab_options WHERE scenario_id=?",scenario.id),saved=JSON.parse(snapshot.options_json).installationProfile;assert.equal(saved.selectedTeamId,state.teams[0].id);assert.equal(saved.installerDayRate,"350.00");const admin=JSON.parse((await db.get("SELECT rule_value_json FROM project_calculator_admin_rules WHERE rule_key='installation_programme_v1'")).rule_value_json);assert.equal(admin.installerDayRate,"350.00")});
