import assert from "node:assert/strict";
import test from "node:test";
import os from "node:os";
import path from "node:path";
import { mkdtemp, rm } from "node:fs/promises";
import sqlite3 from "sqlite3";
import { open } from "sqlite";
import { calculateCommercialMargin, DEFAULT_COMMERCIAL_MARGIN_POLICY, resolveMarginStatus } from "../src/features/projectCalculatorLab/domain/commercialMargin.js";
import { initializeSupplierCommercialSchema } from "../server/schema/supplierCommercialSchema.js";
import { createProjectCalculatorLabService } from "../server/features/projectCalculatorLab/projectCalculatorLabService.js";

test("commercial formulas use full precision and distinguish markup from margin",()=>{const result=calculateCommercialMargin("16718.66","24544.18","35")!;assert.equal(result.grossProfit,"7825.52");assert.equal(result.grossMarginPercent,"31.88");assert.equal(result.overallMarkupPercent,"46.81");assert.equal(result.targetSellingPrice,"25721.02");assert.equal(result.varianceAmount,"1176.84");assert.equal(result.varianceDirection,"below");assert.equal(result.requiredOverallMarkupPercent,"53.85")});
test("variance direction and configurable status bands are explicit",()=>{assert.equal(calculateCommercialMargin("100","200","35")?.varianceDirection,"above");for(const[value,status]of [["24.99","low"],["25","caution"],["30","healthy"],["35","strong"],["40","high"]] as const)assert.equal(resolveMarginStatus(value,DEFAULT_COMMERCIAL_MARGIN_POLICY.bands),status)});
test("complete GBP direct costs and mixed-currency converted totals reconcile",()=>{const categories=["13934.48","1000","500","250","900","300","120"],direct=categories.reduce((sum,value)=>sum+Number(value),0).toFixed(2),result=calculateCommercialMargin(direct,"24544.18","35")!;assert.equal(direct,"17004.48");assert.equal(result.grossProfit,"7539.70");const mixed=(13934.48+4850+6185.43).toFixed(2);assert.equal(mixed,"24969.91");assert.equal(calculateCommercialMargin(mixed,"35000","35")?.grossProfit,"10030.09")});

test("company defaults snapshot, project override, reload and revision remain historical",async t=>{const root=await mkdtemp(path.join(os.tmpdir(),"qs-margin-")),db=await open({filename:path.join(root,"test.db"),driver:sqlite3.Database});t.after(async()=>{await db.close();await rm(root,{recursive:true,force:true})});await db.exec(`CREATE TABLE estimates(id TEXT PRIMARY KEY);CREATE TABLE clients(id TEXT PRIMARY KEY);CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT,group_name TEXT,updated_at TEXT);INSERT INTO settings VALUES('commercial.marginPolicy','{"targetGrossMarginPercent":"35","minimumAcceptableGrossMarginPercent":"25","bands":[{"status":"low","minimumPercent":"0"},{"status":"caution","minimumPercent":"25"},{"status":"healthy","minimumPercent":"30"},{"status":"strong","minimumPercent":"35"},{"status":"high","minimumPercent":"40"}]}','projectPreferences','2026-08-10');`);await initializeSupplierCommercialSchema(db);const service=createProjectCalculatorLabService(db,{exchangeRateProvider:async()=>({rawRate:"1",provider:"identity",quotedAt:"2026-08-10"})});let scenario=await service.createScenario({origin:"manual",name:"Margin",currency:"GBP",packageType:"supply_only"});assert.equal(scenario.targetGrossMarginPercent,"35");assert.equal(scenario.commercialMarginPolicy.minimumAcceptableGrossMarginPercent,"25");await db.run(`UPDATE settings SET value='{"targetGrossMarginPercent":"38","minimumAcceptableGrossMarginPercent":"27"}' WHERE key='commercial.marginPolicy'`);scenario=await service.updateMarkups(scenario.id,{targetGrossMarginPercent:"32"});assert.equal(scenario.targetGrossMarginPercent,"32");assert.equal(scenario.commercialMarginPolicy.targetGrossMarginPercent,"35");scenario=await service.getScenario(scenario.id);assert.equal(scenario.targetGrossMarginPercent,"32");scenario=await service.createRevision(scenario.id);assert.equal(scenario.targetGrossMarginPercent,"32");const snapshot=JSON.parse((await db.get("SELECT snapshot_json FROM project_calculator_lab_revisions WHERE scenario_id=? ORDER BY version_number DESC LIMIT 1",scenario.id)).snapshot_json);assert.equal(snapshot.scenario.target_gross_margin_percent,"32");assert.match(snapshot.scenario.commercial_margin_policy_json,/"targetGrossMarginPercent":"35"/);const newer=await service.createScenario({origin:"manual",name:"New policy",currency:"GBP",packageType:"supply_only"});assert.equal(newer.targetGrossMarginPercent,"38");assert.equal(newer.commercialMarginPolicy.minimumAcceptableGrossMarginPercent,"27")});

test("legacy costings without a policy read with compatibility defaults without database mutation",async t=>{const root=await mkdtemp(path.join(os.tmpdir(),"qs-margin-legacy-")),db=await open({filename:path.join(root,"test.db"),driver:sqlite3.Database});t.after(async()=>{await db.close();await rm(root,{recursive:true,force:true})});await db.exec("CREATE TABLE estimates(id TEXT PRIMARY KEY);CREATE TABLE clients(id TEXT PRIMARY KEY);");await initializeSupplierCommercialSchema(db);const service=createProjectCalculatorLabService(db,{exchangeRateProvider:async()=>({rawRate:"1",provider:"identity",quotedAt:"now"})});const scenario=await service.createScenario({origin:"manual",name:"Legacy",currency:"GBP",packageType:"supply_only"});await db.run("UPDATE project_calculator_lab_scenarios SET target_gross_margin_percent=NULL,commercial_margin_policy_json=NULL WHERE id=?",scenario.id);const loaded=await service.getScenario(scenario.id);assert.equal(loaded.targetGrossMarginPercent,"35");assert.equal(loaded.commercialMarginPolicy.minimumAcceptableGrossMarginPercent,"25");const raw=await db.get("SELECT target_gross_margin_percent,commercial_margin_policy_json FROM project_calculator_lab_scenarios WHERE id=?",scenario.id);assert.equal(raw.target_gross_margin_percent,null);assert.equal(raw.commercial_margin_policy_json,null)});
