import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { COMMUNICATION_PROVIDER_CONTRACTS } from "../src/features/communications/domain/communications.ts";
import { buildEcofensterEstimateFolderTemplate, ESTIMATE_TO_ORDER_DOCUMENT_STRATEGY, PROJECT_FOLDER_PROVISIONING_TRIGGER } from "../src/features/documents/domain/projectDocumentArchitecture.ts";
import { deriveNextAction, prepareQuotationIssue, recordIssuedQuotation, workflowEffects } from "../src/features/workflow/workflowFoundation.ts";

test("contextual Next Action follows canonical state without blocking expert navigation",()=>{const base={manufacturerQuoteImported:false,costingReady:false,quotationReviewed:false,quotationIssued:false,followUpDue:false,followUpCompleted:false,customerAccepted:false,orderCreated:false};assert.equal(deriveNextAction(base)?.id,"import_manufacturer_quote");assert.equal(deriveNextAction({...base,manufacturerQuoteImported:true})?.id,"review_costing");assert.equal(deriveNextAction({...base,manufacturerQuoteImported:true,costingReady:true})?.id,"review_customer_quotation");assert.equal(deriveNextAction({...base,manufacturerQuoteImported:true,costingReady:true,quotationReviewed:true})?.id,"send_to_client");assert.equal(deriveNextAction({...base,manufacturerQuoteImported:true,costingReady:true,quotationReviewed:true,quotationIssued:true,followUpDue:true})?.id,"complete_follow_up");assert.equal(deriveNextAction({...base,manufacturerQuoteImported:true,costingReady:true,quotationReviewed:true,quotationIssued:true,followUpCompleted:true})?.id,"schedule_next_follow_up");assert.equal(deriveNextAction({...base,manufacturerQuoteImported:true,costingReady:true,quotationReviewed:true,quotationIssued:true,customerAccepted:true})?.id,"prepare_order")});

test("quotation preparation cannot be mistaken for issue and issue requires immutable evidence",()=>{const prepared=prepareQuotationIssue({estimateId:"estimate-1",estimateRevision:4,quotationRevision:7,estimateReference:"EF-EST-1",clientId:"client-1",clientName:"Example Client",recipient:"client@example.test",subtotalExVatGbp:"1000.00",vatRatePercent:"20",vatGbp:"200.00",totalIncVatGbp:"1200.00",preparedAt:"2026-08-25T12:00:00.000Z"});assert.equal(prepared.status,"prepared_not_sent");assert.equal(prepared.document.status,"pdf_required");assert.equal(prepared.communication.provider,null);assert.throws(()=>recordIssuedQuotation({...prepared,documentId:"",communicationMessageId:"",issuedAt:"",termsSnapshot:""}),/requires document/);const issued=recordIssuedQuotation({...prepared,documentId:"drive-file-1",communicationMessageId:"gmail-message-1",issuedAt:"2026-08-25T12:05:00.000Z",termsSnapshot:"Terms revision 2"});assert.equal(Object.isFrozen(issued),true);assert.equal(Object.hasOwn(issued,"totalIncVatGbp"),false);assert.equal(issued.commercialSnapshot.totalIncVatGbp,"1200.00")});

test("workflow effects create linked recommendations rather than UI-owned side effects",()=>{const links=[{kind:"client",id:"client-1"},{kind:"estimate",id:"estimate-1"}] as const;assert.deepEqual(workflowEffects({name:"quotation.issued",occurredAt:"now",links:[...links]})[0],{kind:"create_follow_up",dueInDays:3,purpose:"Call / email customer regarding issued quotation",links:[...links]});assert.equal(workflowEffects({name:"followup.completed",occurredAt:"now",links:[...links]})[0].defaultDueInDays,7)});

test("communications are provider-neutral and Drive folders use canonical IDs plus dynamic suppliers",()=>{assert.deepEqual(COMMUNICATION_PROVIDER_CONTRACTS.map(item=>item.id),["google_workspace","microsoft_365"]);const tree=buildEcofensterEstimateFolderTemplate({year:2026,clientProjectLabel:"Client / Project",supplierNames:["Zyle Fenster","Other Supplier","Zyle Fenster"]});const serialized=JSON.stringify(tree);for(const folder of ["Drawings (Client)","PDF Auto Take Offs","Drawings (Ecofenster)","Invoices","Pictures","Videos","Zyle Fenster","Other Supplier"])assert.match(serialized,new RegExp(folder.replace(/[()]/g,"\\$&")));assert.equal((serialized.match(/Zyle Fenster/g)??[]).length,1);assert.equal(PROJECT_FOLDER_PROVISIONING_TRIGGER,"enquiry_qualified_to_estimate");assert.match(ESTIMATE_TO_ORDER_DOCUMENT_STRATEGY.rule,/one canonical project folder/i)});

test("UI exposes foundations without claiming live providers",async()=>{const [app,admin,preview]=await Promise.all([readFile("src/App.tsx","utf8"),readFile("src/features/admin/AdminIntegrationsPanel.tsx","utf8"),readFile("src/features/customerQuotation/CustomerQuotationPreview.tsx","utf8")]);assert.match(app,/SidebarItem label="Email"/);assert.match(app,/No live mailbox is connected/);assert.match(admin,/Planned · OAuth required/);assert.match(admin,/Google Drive project documents/);assert.match(preview,/prepared_not_sent|PDF generation and provider delivery are required/);assert.doesNotMatch(admin,/client_secret|refresh_token|access_token/)});
