import test from 'node:test';
import assert from 'node:assert/strict';
import sqlite3 from 'sqlite3';
import {open} from 'sqlite';
import {mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {initializeSupplierCommercialSchema} from '../server/schema/supplierCommercialSchema.js';
import {persistRouteSnapshot} from '../server/features/projectCalculatorLab/routeSnapshotPersistence.js';
import {createProjectCalculatorLabService} from '../server/features/projectCalculatorLab/projectCalculatorLabService.js';
import {createRouteSnapshotSaver} from '../shared/routeSnapshotClient.js';
test('actual-schema route retries preserve endpoint fields and identity across connections',async t=>{
  const root=await mkdtemp(path.join(os.tmpdir(),'qs-route-retry-')),filename=path.join(root,'test.db'),db=await open({filename,driver:sqlite3.Database});
  let second;t.after(async()=>{await second?.close();await db.close();await rm(root,{recursive:true,force:true});});
  await db.exec('CREATE TABLE estimates(id TEXT PRIMARY KEY);CREATE TABLE clients(id TEXT PRIMARY KEY);');await initializeSupplierCommercialSchema(db);
  const service=createProjectCalculatorLabService(db,{exchangeRateProvider:async()=>({rawRate:'1',provider:'disposable',quotedAt:'2026-09-13'})});
  const scenario=await service.createScenario({origin:'manual',name:'Disposable routes',currency:'GBP',packageType:'full_installation'}),otherScenario=await service.createScenario({origin:'manual',name:'Other disposable routes',currency:'GBP',packageType:'full_installation'});
  const input={requestKey:'reviewed-outward',direction:'office_to_site',origin:{label:'Installer base',lat:51,lng:-1},destination:{label:'Site',lat:52,lng:-2},distanceKm:'100',durationMinutes:90,integration:'test_route'};
  const first=await persistRouteSnapshot(db,scenario.id,input);assert.equal(first.reused,false);
  assert.deepEqual(await db.get('SELECT origin_label,destination_label,origin_lat,origin_lng,destination_lat,destination_lng FROM project_calculator_lab_route_snapshots WHERE id=?',first.id),{origin_label:'Installer base',destination_label:'Site',origin_lat:'51',origin_lng:'-1',destination_lat:'52',destination_lng:'-2'});
  second=await open({filename,driver:sqlite3.Database});const replay=await persistRouteSnapshot(second,scenario.id,input);assert.equal(replay.id,first.id);assert.equal(replay.reused,true);
  const serviceReplay=await service.appendRouteSnapshot(scenario.id,input);assert.equal(serviceReplay.savedRouteSnapshotId,first.id);assert.equal(serviceReplay.routeSnapshotReused,true);assert.equal(serviceReplay.routeSnapshots.find(item=>item.id===first.id).destination.label,'Site');
  await assert.rejects(()=>persistRouteSnapshot(second,scenario.id,{...input,durationMinutes:95}),/different route/);
  assert.equal((await db.get('SELECT COUNT(*) count FROM project_calculator_lab_route_snapshots')).count,1);assert.equal((await db.get('SELECT duration_minutes FROM project_calculator_lab_route_snapshots WHERE id=?',first.id)).duration_minutes,90);
  const other=await persistRouteSnapshot(db,otherScenario.id,input);assert.notEqual(other.id,first.id);
  const back=await persistRouteSnapshot(db,scenario.id,{...input,requestKey:'reviewed-return',direction:'site_to_office',origin:input.destination,destination:input.origin,durationMinutes:110});assert.notEqual(back.id,first.id);
  const concurrent=await Promise.all([persistRouteSnapshot(db,scenario.id,{...input,requestKey:'concurrent'}),persistRouteSnapshot(second,scenario.id,{...input,requestKey:'concurrent'})]);assert.equal(concurrent[0].id,concurrent[1].id);assert.equal(concurrent.filter(item=>!item.reused).length,1);
  let loseResponse=true;
  const clientSave=createRouteSnapshotSaver(async(id,value)=>{const result=await service.appendRouteSnapshot(id,value);if(loseResponse){loseResponse=false;throw new Error('Response lost after persistence');}return result;},()=> 'client-retry');
  const clientDraft={...input,requestKey:undefined};
  const countBefore=(await db.get('SELECT COUNT(*) count FROM project_calculator_lab_route_snapshots')).count;
  await assert.rejects(clientSave(scenario.id,clientDraft),/Response lost/);
  const confirmed=await clientSave(scenario.id,clientDraft);
  assert.equal(confirmed.routeSnapshotReused,true);
  assert.equal((await db.get('SELECT COUNT(*) count FROM project_calculator_lab_route_snapshots')).count,countBefore+1);
  assert.equal((await clientSave(scenario.id,clientDraft)).savedRouteSnapshotId,confirmed.savedRouteSnapshotId);
  await db.run("INSERT INTO installation_companies(id,name,created_at,updated_at) VALUES('company','Disposable installer','2026-09-13','2026-09-13')");
  await db.run("INSERT INTO installation_teams(id,company_id,name,normal_crew_size,base_postcode,created_at,updated_at) VALUES('team','company','Disposable team',3,'Installer base','2026-09-13','2026-09-13')");
  const outPair=await persistRouteSnapshot(db,scenario.id,{...input,requestKey:'pair-out',integration:'google_routes_installation_team'});
  const returnPair=await persistRouteSnapshot(db,scenario.id,{...input,requestKey:'pair-return',integration:'google_routes_installation_team',direction:'site_to_office',origin:input.destination,destination:input.origin,distanceKm:120,durationMinutes:110});
  const choice={selectedTeamId:'team',selectedInstallationCompanyId:'company',sitePostcode:'Site',route:{snapshotId:outPair.id,returnSnapshotId:returnPair.id,oneWayMiles:999,returnMiles:999,oneWayDurationMinutes:999,returnDurationMinutes:999}};
  const beforeChoice=await service.getScenario(scenario.id);
  await assert.rejects(service.updateInstallationProfile(scenario.id,{...choice,sitePostcode:'Different site'}),/do not form a return journey/);
  const afterRejection=await service.getScenario(scenario.id);assert.deepEqual(afterRejection.options,beforeChoice.options);assert.equal(afterRejection.revisionNumber,beforeChoice.revisionNumber);
  const adopted=await service.updateInstallationProfile(scenario.id,choice);
  assert.equal(adopted.options.installationProfile.route.oneWayDurationMinutes,90);assert.equal(adopted.options.installationProfile.route.returnDurationMinutes,110);assert.equal(adopted.options.installationProfile.route.returnMiles,'74.56');
  const retained=await second.get('SELECT options_json FROM project_calculator_lab_options WHERE scenario_id=?',scenario.id);assert.equal(JSON.parse(retained.options_json).installationProfile.route.returnSnapshotId,returnPair.id);
  const reviewedChoice={...choice,travelMode:'daily_travel',mileageRate:'0.50',vehicleCount:2,route:{...choice.route,distanceBasis:'retained_directions_v1'},travelReviewKey:'reviewed-pair',expectedRevisionNumber:adopted.revisionNumber};
  await assert.rejects(service.updateInstallationProfile(scenario.id,{...reviewedChoice,expectedRevisionNumber:0}),/costing changed/);
  const reviewed=await service.updateInstallationProfile(scenario.id,reviewedChoice);
  const repeatedReview=await service.updateInstallationProfile(scenario.id,reviewedChoice);assert.equal(repeatedReview.revisionNumber,reviewed.revisionNumber);assert.equal(repeatedReview.options.installationProfile.route.returnDurationMinutes,110);
  await assert.rejects(service.updateInstallationProfile(scenario.id,{...reviewedChoice,travelMode:'stay_away'}),/already saved with different choices/);
  const concurrentChoice={...reviewedChoice,travelReviewKey:'concurrent-reviewed-pair',expectedRevisionNumber:reviewed.revisionNumber};
  const simultaneous=await Promise.all([service.updateInstallationProfile(scenario.id,concurrentChoice),service.updateInstallationProfile(scenario.id,concurrentChoice)]);
  assert.equal(simultaneous[0].revisionNumber,simultaneous[1].revisionNumber);assert.equal(simultaneous[0].revisionNumber,reviewed.revisionNumber+1);
  await db.exec("CREATE TRIGGER disposable_reject_travel_revision BEFORE INSERT ON project_calculator_lab_revisions BEGIN SELECT RAISE(ABORT,'Disposable revision failure'); END;");
  const beforeFailure=await service.getScenario(scenario.id);
  await assert.rejects(service.updateInstallationProfile(scenario.id,{...reviewedChoice,travelReviewKey:'rollback-pair',travelMode:'stay_away',expectedRevisionNumber:beforeFailure.revisionNumber}),/Disposable revision failure/);
  const rolledBack=await service.getScenario(scenario.id);assert.deepEqual(rolledBack.options,beforeFailure.options);assert.equal(rolledBack.revisionNumber,beforeFailure.revisionNumber);
});
