import assert from 'node:assert/strict';
import test from 'node:test';
import os from 'node:os';
import path from 'node:path';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import sqlite3 from 'sqlite3';
import { open } from 'sqlite';
import { initializeSupplierCommercialSchema } from '../server/schema/supplierCommercialSchema.js';
import { createProjectCalculatorLabService } from '../server/features/projectCalculatorLab/projectCalculatorLabService.js';
import { addDecimalAmounts, applyMarkupPercentage, validateMarkupPercentage } from '../src/features/projectCalculatorLab/domain/projectCostingMarkup.js';

const rates={product:'35',extras:'30',transport:'14',siteVisit:'11',equipment:'12.5',installation:'20',materials:'18.75',duties:'5'};
async function fixture(t:test.TestContext){const root=await mkdtemp(path.join(os.tmpdir(),'qs-costing-markups-'));const db=await open({filename:path.join(root,'test.db'),driver:sqlite3.Database});t.after(async()=>{await db.close();await rm(root,{recursive:true,force:true})});await db.exec('CREATE TABLE estimates(id TEXT PRIMARY KEY);CREATE TABLE clients(id TEXT PRIMARY KEY);');await initializeSupplierCommercialSchema(db);const service=createProjectCalculatorLabService(db,{exchangeRateProvider:async()=>({rawRate:'0.875',provider:'test',quotedAt:'2026-08-06T00:00:00.000Z'})});const scenario=await service.createScenario({origin:'manual',name:'Markup test',currency:'EUR',packageType:'full_installation'});return{db,service,scenario};}

test('percentage validation and live calculation use decimal-safe arithmetic',()=>{for(const valid of ['0','35','30.5','999.99'])assert.equal(validateMarkupPercentage(valid),null);for(const invalid of ['-1','NaN','Infinity','1e2','text','1000','999.999'])assert.ok(validateMarkupPercentage(invalid));assert.deepEqual(applyMarkupPercentage('14470.32','35'),{markupValue:'5064.61',sellingPrice:'19534.93'});assert.deepEqual(applyMarkupPercentage('920.98','30'),{markupValue:'276.29',sellingPrice:'1197.27'});assert.equal(addDecimalAmounts(['19534.93','1197.27','2232.12']),'22964.32');});

test('eight independent markups save atomically, reload and copy into a new revision',async t=>{const{db,service,scenario}=await fixture(t);const rawRate=scenario.exchangeRate.rawRate;let saved=await service.updateMarkups(scenario.id,rates);assert.deepEqual(saved.markups,rates);assert.equal(saved.exchangeRate.rawRate,rawRate);const previousRevision=saved.revisionNumber;saved=await service.createRevision(saved.id);assert.equal(saved.revisionNumber,previousRevision+1);assert.deepEqual(saved.markups,rates);const historical=await db.get('SELECT snapshot_json FROM project_calculator_lab_revisions WHERE scenario_id=? AND version_number=?',saved.id,previousRevision);assert.equal(JSON.parse(historical.snapshot_json).markups.product_percent,'35');});

test('populated Zyle commercial values recalculate independently without changing source costs',async t=>{const{service,scenario}=await fixture(t);let populated=await service.addManualProduct(scenario.id,{reference:'Zyle positions',productClass:'Window',widthMm:1000,heightMm:1200,quantity:21,installationOpeningCount:19,unitSupplyCost:'774.226190',totalSupplyCost:'16258.75'});populated=await service.addManualCost(scenario.id,{category:'extras',label:'Zyle extras',amount:'1034.84'});populated=await service.addManualCost(scenario.id,{category:'delivery',label:'Original supplier transport',amount:'2200.00'});const sourceProduct=populated.products[0].originalAmount,sourceProductGbp=populated.products[0].gbpAmount,sourceCosts=populated.supplierCosts.map(row=>row.originalAmount);const saved=await service.updateMarkups(scenario.id,{product:'35',extras:'30',transport:'14',installation:'20'});assert.equal(saved.markups.product,'35');assert.equal(saved.markups.extras,'30');assert.equal(saved.markups.transport,'14');assert.equal(saved.markups.installation,'20');assert.equal(saved.products[0].originalAmount,sourceProduct);assert.equal(saved.products[0].gbpAmount,sourceProductGbp);assert.deepEqual(saved.supplierCosts.map(row=>row.originalAmount),sourceCosts);assert.equal(saved.products[0].gbpAmount,'14226.41');assert.equal(saved.products[0].commercialGbpAmount,'14470.29');assert.equal(applyMarkupPercentage(saved.products[0].commercialGbpAmount,'35')?.sellingPrice,'19534.89');});

test('invalid or failed markup update leaves every persisted category unchanged',async t=>{const{db,service,scenario}=await fixture(t);await assert.rejects(()=>service.updateMarkups(scenario.id,{...rates,transport:'1e2'}),/0 to 999\.99/);assert.equal((await service.getScenario(scenario.id)).markups.transport,'0');await db.exec("CREATE TRIGGER fail_markup_save BEFORE UPDATE ON project_calculator_lab_markup_rules BEGIN SELECT RAISE(ABORT,'simulated'); END;");await assert.rejects(()=>service.updateMarkups(scenario.id,rates),/simulated/);assert.deepEqual((await service.getScenario(scenario.id)).markups,{product:'0',extras:'0',transport:'0',siteVisit:'0',equipment:'0',installation:'0',materials:'0',duties:'0'});});

test('worksheet exposes editable controls, Escape restore, dirty state and visible save failure',async()=>{const source=await readFile('src/features/projectCalculatorLab/ScenarioCostingWorksheet.tsx','utf8');assert.match(source,/inputMode="decimal"/);assert.match(source,/event\.key==="Escape"/);assert.match(source,/Unsaved markup changes/);assert.match(source,/persistedMarkups/);assert.match(source,/onSaveMarkups/);assert.match(source,/role="alert"/);for(const category of ['product','extras','transport','siteVisit','equipment','installation','materials','duties'])assert.match(source,new RegExp(`editMarkup\\("${category}"`));});
