import assert from 'node:assert/strict';
import test from 'node:test';
import os from 'node:os';
import path from 'node:path';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import sqlite3 from 'sqlite3';
import {open} from 'sqlite';
import express from 'express';
import {initializeSupplierCommercialSchema} from '../server/schema/supplierCommercialSchema.js';
import {createProjectCalculatorLabService} from '../server/features/projectCalculatorLab/projectCalculatorLabService.js';
import {createProjectCalculatorLabRouter} from '../server/routes/projectCalculatorLab.js';
import {calculateAdjustedRate,convertSupplierAmountToGbp,createProjectCostingFx,multiplyDecimal} from '../server/features/projectCalculatorLab/exchangeRateModel.js';
import {fetchCentralExchangeRate} from '../server/features/projectCalculatorLab/exchangeRateProvider.js';
import {toScenarioCreationInput} from '../src/features/projectCalculatorLab/domain/scenarioCreation.js';

async function emptyDb(t:Parameters<typeof test>[1] extends (arg:infer T)=>unknown?T:never){const root=await mkdtemp(path.join(os.tmpdir(),'qs-calculator-version-'));const db=await open({filename:path.join(root,'test.db'),driver:sqlite3.Database});t.after(async()=>{await db.close();await rm(root,{recursive:true,force:true});});await db.exec('PRAGMA foreign_keys=ON;CREATE TABLE estimates(id TEXT PRIMARY KEY);CREATE TABLE clients(id TEXT PRIMARY KEY);');await initializeSupplierCommercialSchema(db);return db;}

test('manual HTTP contract omits source ids and creates once with zero Import Lab sessions',async t=>{const db=await emptyDb(t);const rates=['0.875'];let rateCalls=0;const provider=async()=>({rawRate:rates[Math.min(rateCalls++,rates.length-1)],provider:'test-fx',quotedAt:'2026-08-05T10:00:00.000Z'});const app=express();app.use(express.json());app.use('/api/admin/project-calculator-lab',await createProjectCalculatorLabRouter({dbPromise:Promise.resolve(db),exchangeRateProvider:provider}));const server=app.listen(0,'127.0.0.1');t.after(()=>new Promise<void>(resolve=>server.close(()=>resolve())));await new Promise<void>(resolve=>server.once('listening',resolve));const address=server.address();assert.ok(address&&typeof address==='object');const payload=toScenarioCreationInput({origin:'manual',name:'Live manual',sourceRunId:'stale-run',currency:'EUR',packageCode:'support',installationOpeningCount:'99'});assert.deepEqual(payload,{origin:'manual',name:'Live manual',currency:'EUR',packageType:'support'});const response=await fetch(`http://127.0.0.1:${address.port}/api/admin/project-calculator-lab/scenarios`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});assert.equal(response.status,201);const scenario=await response.json();assert.equal(scenario.origin,'manual');assert.equal(scenario.importLabSessionId,null);assert.equal(scenario.exchangeRate.rawRate,'0.875');assert.equal(scenario.exchangeRate.adjustedRate,'0.89');assert.equal(scenario.exchangeRate.gbpToSupplierDisplayRate,undefined);assert.equal(rateCalls,1);assert.equal((await db.get('SELECT count(*) count FROM project_calculator_lab_scenarios')).count,1);assert.equal((await db.get('SELECT count(*) count FROM supplier_import_lab_sessions')).count,0);});

test('exchange snapshots and category markups are versioned without changing source evidence',async t=>{const db=await emptyDb(t);const rates=['0.875','0.91'];let index=0;const service=createProjectCalculatorLabService(db,{exchangeRateProvider:async()=>({rawRate:rates[index++],provider:'test-fx',quotedAt:`2026-08-05T1${index}:00:00.000Z`})});let scenario=await service.createScenario({origin:'manual',name:'Versioned',currency:'EUR',packageType:'supply_only'});scenario=await service.addManualProduct(scenario.id,{reference:'W7, W8',productClass:'Window',widthMm:610,heightMm:1200,quantity:2,installationOpeningCount:1,unitSupplyCost:'537.12',totalSupplyCost:'1074.24'});const firstRate=scenario.exchangeRate.rawRate;scenario=await service.updateMarkups(scenario.id,{product:'10',extras:'5',transport:'20',installation:'15'});assert.deepEqual(scenario.markups,{product:'10',extras:'5',transport:'20',siteVisit:'0',equipment:'0',installation:'15',materials:'0',duties:'0'});assert.equal(scenario.products[0].originalAmount,'1074.24');assert.equal(scenario.products[0].originalCurrency,'EUR');assert.notEqual(scenario.products[0].gbpAmount,scenario.products[0].markedUpAmount);assert.equal(scenario.exchangeRate.rawRate,firstRate);scenario=await service.updateExchangeRate(scenario.id,{adjustmentEnabled:false});assert.equal(scenario.exchangeRate.usedRate,'0.875');await assert.rejects(()=>service.updateExchangeRate(scenario.id,{adjustmentEnabled:true,adjustedRate:'0.95'}),/require a reason/i);scenario=await service.updateExchangeRate(scenario.id,{adjustmentEnabled:true,adjustedRate:'0.95',overrideReason:'Approved hedge'});assert.equal(scenario.exchangeRate.calculatedAdjustedRate,'0.89');assert.equal(scenario.exchangeRate.adjustedRate,'0.95');scenario=await service.refreshExchangeRate(scenario.id);assert.equal(scenario.exchangeRate.rawRate,'0.91');assert.ok(scenario.revisions.length>=5);assert.equal((await db.get('SELECT count(*) count FROM project_calculator_lab_exchange_rate_snapshots WHERE scenario_id=?',scenario.id)).count,4);});

test('rate adjustment rounds upward then adds 0.01',()=>assert.deepEqual(calculateAdjustedRate('0.875'),{rawRate:'0.875',roundedUpRate:'0.88',upliftAmount:'0.01',adjustedRate:'0.89'}));

test('new costings snapshot the dedicated Site Visit markup while historical revisions remain stable',async t=>{const db=await emptyDb(t);await db.exec('CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT,group_name TEXT,updated_at TEXT)');await db.run('INSERT INTO settings VALUES(?,?,?,?)','projectCalculator.siteVisitTravelDefaults',JSON.stringify({siteVisitMarkup:'12.5'}),'projectPreferences','2026-08-12');const service=createProjectCalculatorLabService(db,{exchangeRateProvider:async()=>({rawRate:'1',provider:'identity',quotedAt:'2026-08-12'})});let first=await service.createScenario({origin:'manual',name:'Historical travel markup',currency:'GBP',packageType:'supply_only'});assert.equal(first.markups.siteVisit,'12.5');await db.run('UPDATE settings SET value=? WHERE key=?',JSON.stringify({siteVisitMarkup:'20'}),'projectCalculator.siteVisitTravelDefaults');first=await service.createRevision(first.id);assert.equal(first.markups.siteVisit,'12.5');const snapshot=JSON.parse((await db.get('SELECT snapshot_json FROM project_calculator_lab_revisions WHERE scenario_id=? ORDER BY version_number DESC LIMIT 1',first.id)).snapshot_json);assert.equal(snapshot.markups.site_visit_percent,'12.5');const second=await service.createScenario({origin:'manual',name:'Current travel markup',currency:'GBP',packageType:'supply_only'});assert.equal(second.markups.siteVisit,'20');});

test('new costings snapshot Admin markup defaults without rewriting existing scenarios',async t=>{const db=await emptyDb(t);await db.exec('CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT,group_name TEXT,updated_at TEXT)');await db.run('INSERT INTO settings VALUES(?,?,?,?)','projectCalculator.markupDefaults',JSON.stringify({product:'40',extras:'15',transport:'10',installation:'25'}),'projectPreferences','2026-08-20');const service=createProjectCalculatorLabService(db,{exchangeRateProvider:async()=>({rawRate:'1',provider:'identity',quotedAt:'2026-08-20'})});let first=await service.createScenario({origin:'manual',name:'Estimate A',currency:'GBP',packageType:'supply_only'});assert.equal(first.markups.product,'40');assert.equal(first.markups.installation,'25');assert.equal(first.markups.materials,'25');await db.run('UPDATE settings SET value=? WHERE key=?',JSON.stringify({product:'45',extras:'20',transport:'12',installation:'30',materials:'35'}),'projectCalculator.markupDefaults');first=await service.createRevision(first.id);assert.equal(first.markups.product,'40');assert.equal(first.markups.materials,'25');const second=await service.createScenario({origin:'manual',name:'Estimate B',currency:'GBP',packageType:'supply_only'});assert.equal(second.markups.product,'45');assert.equal(second.markups.installation,'30');assert.equal(second.markups.materials,'35');});

test('canonical Project Costing FX exposes only purchase and selling rates',()=>{const fx=createProjectCostingFx({supplierToGbpLiveRate:'0.857045'});assert.deepEqual(fx,{supplierToGbpLiveRate:'0.857045',supplierToGbpSellingRate:'0.87',roundedUpRate:'0.86',upliftAmount:'0.01',calculatedSellingRate:'0.87',adjustmentEnabled:true});assert.deepEqual(convertSupplierAmountToGbp('3090.12',fx),{purchaseGbpAmount:'2648.37',sellingGbpAmount:'2688.40'});assert.deepEqual(convertSupplierAmountToGbp('16258.75',fx),{purchaseGbpAmount:'13934.48',sellingGbpAmount:'14145.11'});assert.equal('gbpToSupplierDisplayRate' in fx,false);});

test('selling FX is adjusted from the supplier-to-GBP live rate and quantity remains authoritative',async t=>{const db=await emptyDb(t);const service=createProjectCalculatorLabService(db,{exchangeRateProvider:async()=>({rawRate:'0.857045',provider:'test-fx',quotedAt:'2026-08-07T09:00:00.000Z'})});let scenario=await service.createScenario({origin:'manual',name:'Directional rate',currency:'EUR',packageType:'supply_only'});scenario=await service.addManualProduct(scenario.id,{reference:'Back door',productClass:'Single door',widthMm:940,heightMm:2065,quantity:1,installationOpeningCount:1,unitSupplyCost:'3090.12',totalSupplyCost:'3090.12'});scenario=await service.addManualProduct(scenario.id,{reference:'W7, W8',productClass:'Window',widthMm:610,heightMm:1200,quantity:2,installationOpeningCount:2,unitSupplyCost:'537.12',totalSupplyCost:'1074.24'});assert.deepEqual(calculateAdjustedRate('0.857045'),{rawRate:'0.857045',roundedUpRate:'0.86',upliftAmount:'0.01',adjustedRate:'0.87'});const door=scenario.products.find(row=>row.displayReference==='Back door')!;const grouped=scenario.products.find(row=>row.displayReference==='W7, W8')!;assert.equal(door.gbpAmount,'2648.37');assert.equal(door.commercialGbpAmount,'2688.40');assert.equal(door.markedUpAmount,'2688.40');assert.equal(grouped.quantity,2);assert.equal(grouped.commercialGbpAmount,'934.59');assert.equal(grouped.markedUpAmount,'934.59');scenario=await service.updateExchangeRate(scenario.id,{adjustmentEnabled:false});assert.equal(scenario.products.find(row=>row.displayReference==='Back door')!.commercialGbpAmount,'2648.37');});

test('central provider requests supplier-currency-to-pounds direction',async t=>{const testGlobal=globalThis as typeof globalThis&{__quoteSyncExchangeRateTestProvider?:unknown};const previousProvider=testGlobal.__quoteSyncExchangeRateTestProvider;delete testGlobal.__quoteSyncExchangeRateTestProvider;const previous=globalThis.fetch;let requested='';globalThis.fetch=async(input)=>{requested=String(input);return new Response(JSON.stringify({date:'2026-08-07',rates:{GBP:0.857554}}),{status:200,headers:{'Content-Type':'application/json'}})};t.after(()=>{globalThis.fetch=previous;if(previousProvider!==undefined)testGlobal.__quoteSyncExchangeRateTestProvider=previousProvider});const quote=await fetchCentralExchangeRate('EUR');assert.match(requested,/from=EUR&to=GBP/);assert.equal(quote.rawRate,'0.857554');});

test('explicit refresh replaces an obsolete GBP identity snapshot with imported EUR evidence currency',async t=>{const db=await emptyDb(t);const requested:string[]=[];const service=createProjectCalculatorLabService(db,{exchangeRateProvider:async(currency)=>{requested.push(currency);return currency==='GBP'?{rawRate:'1',provider:'identity-test',quotedAt:'2026-08-06T00:00:00.000Z'}:{rawRate:'0.857554',provider:'test-fx',quotedAt:'2026-08-07T00:00:00.000Z'}}});let scenario=await service.createScenario({origin:'manual',name:'Obsolete identity rate',currency:'GBP',packageType:'supply_only'});scenario=await service.addManualProduct(scenario.id,{reference:'EUR product',productClass:'Window',widthMm:1000,heightMm:1000,quantity:1,installationOpeningCount:1,unitSupplyCost:'1000.00',totalSupplyCost:'1000.00'});await db.run("UPDATE project_calculator_lab_manual_product_rows SET currency='EUR' WHERE scenario_id=?",scenario.id);assert.equal((await service.getScenario(scenario.id)).exchangeRate.rawRate,'1');scenario=await service.refreshExchangeRate(scenario.id);assert.deepEqual(requested,['GBP','EUR']);assert.equal(scenario.currency,'EUR');assert.equal(scenario.exchangeRate.rawRate,'0.857554');assert.equal(scenario.exchangeRate.gbpToSupplierDisplayRate,undefined);assert.equal(scenario.exchangeRate.adjustedRate,'0.87');assert.equal(scenario.products[0].gbpAmount,'857.55');assert.equal(scenario.products[0].originalAmount,'1000.00');});

test('refresh persists the provider EUR-to-GBP value unchanged as the latest raw_rate',async t=>{const db=await emptyDb(t);const service=createProjectCalculatorLabService(db,{exchangeRateProvider:async()=>({rawRate:'0.857045',provider:'test-fx',quotedAt:'2026-08-07T00:00:00.000Z'})});const scenario=await service.createScenario({origin:'manual',name:'Persisted FX',currency:'EUR',packageType:'supply_only'});await db.run("UPDATE project_calculator_lab_exchange_rate_snapshots SET raw_rate='1.1668',adjusted_rate='1.18' WHERE scenario_id=?",scenario.id);const refreshed=await service.refreshExchangeRate(scenario.id);const persisted=await db.get('SELECT raw_rate,adjusted_rate FROM project_calculator_lab_exchange_rate_snapshots WHERE scenario_id=? ORDER BY created_at DESC LIMIT 1',scenario.id);assert.deepEqual(persisted,{raw_rate:'0.857045',adjusted_rate:'0.87'});assert.equal(refreshed.exchangeRate.supplierToGbpLiveRate,'0.857045');assert.ok(Number(persisted.raw_rate)<1);});

test('worksheet exposes explicit refresh and approved purchase-cost terminology',async()=>{const source=await readFile('src/features/projectCalculatorLab/ScenarioCostingWorksheet.tsx','utf8');assert.match(source,/Refresh Rate/);assert.match(source,/Base Supply Only Cost/);assert.match(source,/Actual GBP Purchase Cost/);assert.match(source,/supplier subtotal/);assert.doesNotMatch(source,/Original supplier purchase total/);});

test('Commercial Summary delegates the single Site Visit and customer-discount calculation to the canonical result',async()=>{const [worksheet,result]=await Promise.all([readFile('src/features/projectCalculatorLab/ScenarioCostingWorksheet.tsx','utf8'),readFile('src/features/projectCalculatorLab/domain/projectCostingCommercialResult.ts','utf8')]);assert.match(worksheet,/deriveProjectCostingCommercialResult/);assert.match(result,/projectCost = addDecimalAmounts/);assert.match(result,/siteVisitCost/);assert.match(result,/discountedProductSale = subtractDecimalAmounts/);assert.match(result,/siteVisitAllocatedToProducts \? null : siteVisitSale/);assert.match(result,/profit = subtractDecimalAmounts\(actualSale, projectCost\)/);assert.match(worksheet,/supplierToGbpLiveRate/);assert.match(worksheet,/supplierToGbpSellingRate/);});
