import assert from "node:assert/strict";
import { createServer, type Server } from "node:http";
import { mkdtemp, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import express from "express";
import sqlite3 from "sqlite3";
import { open, type Database } from "sqlite";
import { initializeSupplierCommercialSchema } from "../server/schema/supplierCommercialSchema.js";
import { createSupplierQuotesRouter } from "../server/routes/supplierQuotes.js";
import { resolveManagedPath } from "../server/features/supplierQuotes/managedAttachmentStorage.js";
import { clientValidateSupplierFiles } from "../src/features/supplierQuotes/supplierFileValidation";

function crc32(buffer: Buffer) { let crc=0xffffffff; for(const byte of buffer){crc^=byte;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);} return (crc^0xffffffff)>>>0; }
function minimalZip(entries: Record<string,string>) { const locals:Buffer[]=[];const centrals:Buffer[]=[];let offset=0;for(const [name,value] of Object.entries(entries)){const n=Buffer.from(name);const data=Buffer.from(value);const crc=crc32(data);const local=Buffer.alloc(30+n.length);local.writeUInt32LE(0x04034b50,0);local.writeUInt16LE(20,4);local.writeUInt32LE(crc,14);local.writeUInt32LE(data.length,18);local.writeUInt32LE(data.length,22);local.writeUInt16LE(n.length,26);n.copy(local,30);locals.push(local,data);const central=Buffer.alloc(46+n.length);central.writeUInt32LE(0x02014b50,0);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt32LE(crc,16);central.writeUInt32LE(data.length,20);central.writeUInt32LE(data.length,24);central.writeUInt16LE(n.length,28);central.writeUInt32LE(offset,42);n.copy(central,46);centrals.push(central);offset+=local.length+data.length;}const central=Buffer.concat(centrals);const end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(centrals.length,8);end.writeUInt16LE(centrals.length,10);end.writeUInt32LE(central.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...locals,central,end]); }
const pdf=Buffer.from("%PDF-1.7\n1 0 obj\n<<>>\nendobj\n%%EOF\n");
const docx=minimalZip({"[Content_Types].xml":"<Types/>","word/document.xml":"<w:document/>"});

type Context={db:Database;root:string;base:string;server:Server};
async function setup(t:test.TestContext):Promise<Context>{const root=await mkdtemp(path.join(os.tmpdir(),"quotesync-stage1d-"));const db=await open({filename:path.join(root,"test.db"),driver:sqlite3.Database});await db.exec("PRAGMA foreign_keys=ON; CREATE TABLE clients(id TEXT PRIMARY KEY); CREATE TABLE estimates(id TEXT PRIMARY KEY,client_id TEXT NOT NULL,positions_json TEXT NOT NULL DEFAULT '[]',deleted_at TEXT,FOREIGN KEY(client_id) REFERENCES clients(id) ON DELETE CASCADE); INSERT INTO clients VALUES('c1'),('c2'); INSERT INTO estimates VALUES('e1','c1','[{\"id\":\"existing\"}]',NULL),('e2','c2','[]',NULL);");await initializeSupplierCommercialSchema(db);const app=express();app.use(express.json());app.use("/api/estimates",await createSupplierQuotesRouter({dbPromise:Promise.resolve(db),attachmentRoot:path.join(root,"attachments")}));const server=createServer(app);await new Promise<void>((resolve)=>server.listen(0,"127.0.0.1",resolve));const address=server.address();const base=`http://127.0.0.1:${typeof address==="object"&&address?address.port:0}`;t.after(async()=>{await new Promise<void>((resolve)=>server.close(()=>resolve()));await db.close();await rm(root,{recursive:true,force:true});});return{db,root,base,server};}
async function json(base:string,pathName:string,init?:RequestInit){const response=await fetch(base+pathName,init);const body=await response.text();return{response,data:body?JSON.parse(body):null};}
async function createQuoteRevision(context:Context,estimateId="e1",supplierName="Zyle Fenster"){const q=await json(context.base,`/api/estimates/${estimateId}/supplier-quotes`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({supplierCode:"ZYLE",supplierName})});const r=await json(context.base,`/api/estimates/${estimateId}/supplier-quotes/${q.data.id}/revisions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({supplierQuotationNumber:"343117",supplierRevision:"3",currency:"EUR"})});return{quote:q.data,revision:r.data};}
function uploadBody(items:Array<{name:string;type:string;bytes:Buffer}>) { const body=new FormData();for(const item of items)body.append("files",new Blob([item.bytes],{type:item.type}),item.name);body.append("role","original_quote");return body; }

test("quote and revision APIs enforce estimate scope and preserve multiple suppliers/revisions",async(t)=>{const c=await setup(t);const a=await createQuoteRevision(c);await createQuoteRevision(c,"e1","Supplier B");const second=await json(c.base,`/api/estimates/e1/supplier-quotes/${a.quote.id}/revisions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({supplierQuotationNumber:"343117",supplierRevision:"4",currency:"GBP"})});assert.equal(second.response.status,201);const list=await json(c.base,"/api/estimates/e1/supplier-quotes");assert.equal(list.data.length,2);const cross=await json(c.base,`/api/estimates/e2/supplier-quotes/${a.quote.id}`);assert.equal(cross.response.status,404);assert.equal((await c.db.get("SELECT positions_json FROM estimates WHERE id='e1'")).positions_json,'[{"id":"existing"}]');});

test("two files upload atomically, retain independent metadata, and download safely",async(t)=>{const c=await setup(t);const {quote,revision}=await createQuoteRevision(c);const body=uploadBody([{name:"343117-3.pdf",type:"application/pdf",bytes:pdf},{name:"343117-3.docx",type:"application/vnd.openxmlformats-officedocument.wordprocessingml.document",bytes:docx}]);const uploaded=await json(c.base,`/api/estimates/e1/supplier-quotes/${quote.id}/revisions/${revision.id}/attachments`,{method:"POST",body});assert.equal(uploaded.response.status,201);assert.equal(uploaded.data.attachments.length,2);assert.equal((await c.db.get("SELECT COUNT(*) count FROM supplier_quote_attachments")).count,2);for(const item of uploaded.data.attachments){assert.equal(item.sha256.length,64);assert.equal("storageKey" in item,false);const row=await c.db.get("SELECT storage_key FROM supplier_quote_attachments WHERE id=?",item.id);assert.equal((await stat(resolveManagedPath(row.storage_key,path.join(c.root,"attachments")))).isFile(),true);}const download=await fetch(`${c.base}/api/estimates/e1/supplier-quotes/${quote.id}/revisions/${revision.id}/attachments/${uploaded.data.attachments[0].id}/download`);assert.equal(download.status,200);assert.match(download.headers.get("content-disposition")||"",/^attachment;/);assert.deepEqual(Buffer.from(await download.arrayBuffer()),pdf);const cross=await fetch(`${c.base}/api/estimates/e2/supplier-quotes/${quote.id}/revisions/${revision.id}/attachments/${uploaded.data.attachments[0].id}/download`);assert.equal(cross.status,404);});

test("invalid signature or generic ZIP rejects the whole request without metadata or files",async(t)=>{const c=await setup(t);const {quote,revision}=await createQuoteRevision(c);for(const items of [[{name:"valid.pdf",type:"application/pdf",bytes:pdf},{name:"renamed.pdf",type:"application/pdf",bytes:Buffer.from("not pdf")}],[{name:"fake.docx",type:"application/vnd.openxmlformats-officedocument.wordprocessingml.document",bytes:minimalZip({"readme.txt":"not docx"})}]]){const result=await json(c.base,`/api/estimates/e1/supplier-quotes/${quote.id}/revisions/${revision.id}/attachments`,{method:"POST",body:uploadBody(items)});assert.equal(result.response.status,400);assert.equal((await c.db.get("SELECT COUNT(*) count FROM supplier_quote_attachments")).count,0);}const files=await readdir(path.join(c.root,"attachments"),{recursive:true});assert.equal(files.some((name)=>String(name).match(/^[0-9a-f-]{36}$/)),false);});

test("empty, MIME mismatch, excessive count and client-invalid extensions are rejected",async(t)=>{const c=await setup(t);const {quote,revision}=await createQuoteRevision(c);const endpoint=`/api/estimates/e1/supplier-quotes/${quote.id}/revisions/${revision.id}/attachments`;const empty=await json(c.base,endpoint,{method:"POST",body:uploadBody([{name:"empty.pdf",type:"application/pdf",bytes:Buffer.alloc(0)}])});assert.equal(empty.response.status,400);const mismatch=await json(c.base,endpoint,{method:"POST",body:uploadBody([{name:"quote.pdf",type:"text/plain",bytes:pdf}])});assert.equal(mismatch.response.status,400);const tooMany=await json(c.base,endpoint,{method:"POST",body:uploadBody(Array.from({length:11},(_,i)=>({name:`${i}.pdf`,type:"application/pdf",bytes:pdf})))});assert.equal(tooMany.response.status,413);assert.ok(clientValidateSupplierFiles([{name:"malware.exe",size:10}]).length);assert.ok(clientValidateSupplierFiles([{name:"empty.docx",size:0}]).length);});

test("unreferenced removal deletes bytes; referenced evidence is retained; integrity mismatch is blocked",async(t)=>{const c=await setup(t);const {quote,revision}=await createQuoteRevision(c);async function one(){return(await json(c.base,`/api/estimates/e1/supplier-quotes/${quote.id}/revisions/${revision.id}/attachments`,{method:"POST",body:uploadBody([{name:"quote.pdf",type:"application/pdf",bytes:pdf}])})).data.attachments[0];}const removable=await one();const removed=await fetch(`${c.base}/api/estimates/e1/supplier-quotes/${quote.id}/revisions/${revision.id}/attachments/${removable.id}`,{method:"DELETE"});assert.equal(removed.status,204);assert.equal((await c.db.get("SELECT COUNT(*) count FROM supplier_quote_attachments WHERE id=?",removable.id)).count,0);const protectedItem=await one();await c.db.run("INSERT INTO supplier_quote_import_runs(id,estimate_id,revision_id,extractor_name,extractor_version,adapter_code,adapter_version,recognition_version,started_at,completed_at,status,warnings_json) VALUES('run','e1',?,'none','1','none','1','1','now','now','completed','[]')",revision.id);await c.db.run("INSERT INTO supplier_quote_import_run_attachments(import_run_id,attachment_id,ordinal,role) VALUES('run',?,0,'source')",protectedItem.id);const protectedDelete=await fetch(`${c.base}/api/estimates/e1/supplier-quotes/${quote.id}/revisions/${revision.id}/attachments/${protectedItem.id}`,{method:"DELETE"});assert.equal(protectedDelete.status,409);const row=await c.db.get("SELECT storage_key FROM supplier_quote_attachments WHERE id=?",protectedItem.id);await writeFile(resolveManagedPath(row.storage_key,path.join(c.root,"attachments")),"tampered");const download=await fetch(`${c.base}/api/estimates/e1/supplier-quotes/${quote.id}/revisions/${revision.id}/attachments/${protectedItem.id}/download`);assert.equal(download.status,409);});

test("production upload workspace remains Estimate-scoped and separate from Admin Feature Controls",async()=>{const source=await readFile(new URL("../src/features/supplierQuotes/SupplierQuotesWorkspace.tsx",import.meta.url),"utf8");const controls=await readFile(new URL("../src/features/admin/AdminFeatureControls.tsx",import.meta.url),"utf8");const app=await readFile(new URL("../src/App.tsx",import.meta.url),"utf8");assert.match(source,/estimateId/);assert.doesNotMatch(controls,/EstimateCommercialWorkspace|SupplierQuotesWorkspace|SupplierImportLabWorkspace/);assert.doesNotMatch(app,/SupplierQuotesWorkspace|SupplierImportLabWorkspace/);assert.doesNotMatch(source,/ConfiguredPositionContract|OCR|Recognit|Parse document/);});
