import assert from 'node:assert/strict';
import test from 'node:test';
import os from 'node:os';
import path from 'node:path';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import sqlite3 from 'sqlite3';
import { open } from 'sqlite';
import { initializeSupplierCommercialSchema } from '../server/schema/supplierCommercialSchema.js';
import { createProjectCalculatorLabService } from '../server/features/projectCalculatorLab/projectCalculatorLabService.js';
import { addDecimalAmounts, calculateProductSelling } from '../src/features/projectCalculatorLab/domain/projectCostingMarkup.js';

async function fixture(t:test.TestContext){const root=await mkdtemp(path.join(os.tmpdir(),'qs-stage3a-'));const db=await open({filename:path.join(root,'test.db'),driver:sqlite3.Database});t.after(async()=>{await db.close();await rm(root,{recursive:true,force:true})});await db.exec('CREATE TABLE estimates(id TEXT PRIMARY KEY);CREATE TABLE clients(id TEXT PRIMARY KEY);');await initializeSupplierCommercialSchema(db);const service=createProjectCalculatorLabService(db,{exchangeRateProvider:async()=>({rawRate:'1',provider:'test',quotedAt:'2026-08-06T00:00:00.000Z'})});let scenario=await service.createScenario({origin:'manual',name:'Stage 3A',currency:'GBP',packageType:'supply_only'});scenario=await service.updateExchangeRate(scenario.id,{adjustmentEnabled:false});scenario=await service.addManualProduct(scenario.id,{reference:'W7, W8',productClass:'Window',widthMm:610,heightMm:1200,quantity:2,installationOpeningCount:1,unitSupplyCost:'100.00',totalSupplyCost:'200.00'});scenario=await service.addManualProduct(scenario.id,{reference:'W9',productClass:'Window',widthMm:800,heightMm:1200,quantity:1,installationOpeningCount:1,unitSupplyCost:'100.00',totalSupplyCost:'100.00'});return{db,service,scenario};}

test('rows inherit category markup and quantity-safe selling prices',async t=>{const{service,scenario}=await fixture(t);const saved=await service.updateMarkups(scenario.id,{product:'35'});const grouped=saved.products.find(row=>row.displayReference==='W7, W8')!;assert.equal(grouped.markupOverridePercent,null);assert.equal(grouped.markupPercent,'35');assert.equal(grouped.gbpAmount,'200.00');assert.equal(grouped.markedUpAmount,'270.00');assert.deepEqual(calculateProductSelling(grouped.gbpAmount,grouped.quantity,'35',null),{effectiveMarkup:'35',inherited:true,gbpUnitCost:'100.00',unitSellingPrice:'135.00',totalSellingPrice:'270.00',grossProfit:'70.00',grossMargin:'25.9'});assert.equal(addDecimalAmounts(saved.products.map(row=>row.markedUpAmount)),'405.00');});

test('manual override wins, survives category edits and reset restores inheritance',async t=>{const{service,scenario}=await fixture(t);const grouped=scenario.products.find(row=>row.displayReference==='W7, W8')!;let saved=await service.updateMarkups(scenario.id,{product:'35',productOverrides:[{rowId:grouped.id,markupOverridePercent:'20'}]});let row=saved.products.find(item=>item.id===grouped.id)!;assert.equal(row.markupPercent,'20');assert.equal(row.markedUpAmount,'240.00');saved=await service.updateMarkups(scenario.id,{product:'40'});row=saved.products.find(item=>item.id===grouped.id)!;assert.equal(row.markupOverridePercent,'20');assert.equal(row.markedUpAmount,'240.00');saved=await service.updateMarkups(scenario.id,{product:'40',productOverrides:[{rowId:grouped.id,markupOverridePercent:null}]});row=saved.products.find(item=>item.id===grouped.id)!;assert.equal(row.markupOverridePercent,null);assert.equal(row.markupPercent,'40');assert.equal(row.markedUpAmount,'280.00');});

test('save, reload and revision preserve configuration without changing evidence',async t=>{const{db,service,scenario}=await fixture(t);const row=scenario.products[0],source=row.originalAmount,gbp=row.gbpAmount;let saved=await service.updateMarkups(scenario.id,{product:'35',productOverrides:[{rowId:row.id,markupOverridePercent:'17.5'}]});saved=await service.getScenario(saved.id);assert.equal(saved.markups.product,'35');assert.equal(saved.products[0].markupOverridePercent,'17.5');assert.equal(saved.products[0].originalAmount,source);assert.equal(saved.products[0].gbpAmount,gbp);saved=await service.createRevision(saved.id);const snapshot=JSON.parse((await db.get('SELECT snapshot_json FROM project_calculator_lab_revisions WHERE scenario_id=? AND version_number=?',saved.id,saved.revisionNumber)).snapshot_json);assert.equal(snapshot.productMarkupOverrides.find((item:{id:string})=>item.id===row.id).markup_override_percent,'17.5');});

test('worksheet derives row and summary selling values from effective markup',async()=>{const source=await readFile('src/features/projectCalculatorLab/ScenarioCostingWorksheet.tsx','utf8');assert.match(source,/calculateProductSelling\(row\.commercialGbpAmount,row\.quantity,categoryMarkup/);assert.match(source,/override===""\?null:override/);assert.match(source,/productSale=addDecimalAmounts\(\[\.\.\.productPricing\.map/);assert.match(source,/Inherited/);assert.match(source,/Override/);assert.doesNotMatch(source,/number\(row\.markedUpAmount\)\/row\.quantity/);});
