import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import sqlite3 from "sqlite3";
import { open } from "sqlite";
import { initializeSupplierCommercialSchema } from "../server/schema/supplierCommercialSchema.js";
import { createSupplierImportLabExtractionService } from "../server/features/supplierImportLab/supplierImportLabExtractionService.js";
import { createSupplierImportLabService } from "../server/features/supplierImportLab/supplierImportLabService.js";
import { changedFields, exactTotalMatches, friendlyRunStatus, rowToDraft, validateRowDraft } from "../src/features/supplierImportLab/domain/supplierImportLabReview";
import type { SupplierImportLabExtractedRow } from "../src/features/supplierImportLab/domain/supplierImportLab.types";

async function setup(t:test.TestContext){const root=await mkdtemp(path.join(os.tmpdir(),"qs-stage1g-"));const db=await open({filename:path.join(root,"test.db"),driver:sqlite3.Database});await db.exec("PRAGMA foreign_keys=ON;CREATE TABLE estimates(id TEXT PRIMARY KEY,positions_json TEXT);CREATE TABLE clients(id TEXT PRIMARY KEY);");await initializeSupplierCommercialSchema(db);t.after(async()=>{await db.close();await rm(root,{recursive:true,force:true});});return db;}
const snapshot=JSON.stringify({displayReference:"W7, W8",quantity:2,widthMm:610,heightMm:1200,unitPrice:"537.12",totalPrice:"1074.24"});
async function seed(db:Awaited<ReturnType<typeof open>>){await db.run("INSERT INTO supplier_import_lab_sessions(id,supplier_name,currency,status,created_at,updated_at) VALUES('s','Zyle Fenster','EUR','extracted','now','now')");await db.run("INSERT INTO supplier_import_lab_attachments(id,session_id,role,original_file_name,media_type,size_bytes,sha256,storage_key,parser_eligible,created_at) VALUES('a','s','original_quote','quote.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document',1,?,'lab/s/a/file',1,'now')",'a'.repeat(64));for(const run of ['r1','r2'])await db.run("INSERT INTO supplier_import_lab_extraction_runs(id,session_id,attachment_id,extractor_name,extractor_version,field_parser_name,field_parser_version,status,started_at,completed_at,warnings_json,quotation_warnings_json,selected,created_at) VALUES(?,?,?,?,?,?,?,'completed','now','now','[]','[]',?,'now')",run,'s','a','mammoth','1','core','1',run==='r2'?1:0);const insert="INSERT INTO supplier_import_lab_extracted_rows(id,session_id,extraction_run_id,attachment_id,ordinal,display_reference,original_reference_text,supplier_reference_tokens_json,quantity,width_mm,height_mm,unit_price_amount,total_price_amount,currency,warnings_json,status,created_at,original_extracted_snapshot_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,'[]','extracted','now',?)";await db.run(insert,'one','s','r2','a',0,'W7, W8','W7, W8','["W7","W8"]',2,610,1200,'537.12','1074.24','EUR',snapshot);await db.run(insert,'two','s','r2','a',1,'Back door','Back door','[]',1,940,2065,'3090.12','3090.12','EUR',JSON.stringify({displayReference:'Back door'}));await db.run(insert,'old','s','r1','a',0,'W7, W8','W7, W8','["W7","W8"]',2,610,1200,'537.12','1074.24','EUR',snapshot);}

test("review validation accepts grouped and text references while rejecting unsafe commercial values",()=>{const row={id:'one',displayReference:'W7, W8',widthMm:610,heightMm:1200,quantity:2,unitPrice:'537.12',totalPrice:'1074.24',selectedForFutureUse:true,status:'extracted'} as SupplierImportLabExtractedRow;const draft=rowToDraft(row);assert.deepEqual(validateRowDraft(draft),[]);assert.equal(exactTotalMatches(draft),true);assert.deepEqual(validateRowDraft({...draft,displayReference:'Back door'}),[]);assert.deepEqual(validateRowDraft({...draft,displayReference:'Single reference',quantity:'3'}),[]);for(const changed of [{displayReference:''},{widthMm:'0'},{heightMm:'-1'},{quantity:'0'},{unitPrice:'5e2'},{totalPrice:'NaN'}])assert.ok(validateRowDraft({...draft,...changed}).length>0);assert.ok(validateRowDraft(draft,'rejected').some((issue)=>issue.field==='selectedForFutureUse'));assert.equal(exactTotalMatches({...draft,totalPrice:'1074.25'}),false);assert.equal(changedFields(row,{...draft,quantity:'3'}).includes('quantity'),true);});

test("bulk save is all-or-nothing, scoped, preserves snapshots, and persists run-specific selection",async(t)=>{const db=await setup(t);await seed(db);const service=createSupplierImportLabExtractionService(db);const original=(await db.get("SELECT original_extracted_snapshot_json FROM supplier_import_lab_extracted_rows WHERE id='one'")).original_extracted_snapshot_json;await assert.rejects(()=>service.bulkCorrectRows('s',[{rowId:'one',displayReference:'Changed',widthMm:'610',heightMm:'1200',quantity:'2',unitPrice:'537.12',totalPrice:'1074.24',selectedForFutureUse:false},{rowId:'two',displayReference:'Back door',widthMm:'0',heightMm:'2065',quantity:'1',unitPrice:'3090.12',totalPrice:'3090.12',selectedForFutureUse:true}]),/invalid/i);assert.equal((await db.get("SELECT display_reference FROM supplier_import_lab_extracted_rows WHERE id='one'")).display_reference,'W7, W8');const updated=await service.bulkCorrectRows('s',[{rowId:'one',displayReference:'W7, W8 revised',widthMm:'610',heightMm:'1200',quantity:'2',unitPrice:'537.12',totalPrice:'1074.25',selectedForFutureUse:false},{rowId:'two',displayReference:'Back door',widthMm:'940',heightMm:'2065',quantity:'1',unitPrice:'3090.12',totalPrice:'3090.12',selectedForFutureUse:true}]);assert.equal(updated.length,2);assert.equal(updated[0].reviewWarnings.length,1);assert.equal(updated[0].selectedForFutureUse,false);assert.equal((await db.get("SELECT original_extracted_snapshot_json FROM supplier_import_lab_extracted_rows WHERE id='one'")).original_extracted_snapshot_json,original);assert.equal((await db.get("SELECT selected_for_future_use FROM supplier_import_lab_extracted_rows WHERE id='old'")).selected_for_future_use,1);assert.equal(await service.bulkCorrectRows('other',[{rowId:'one',displayReference:'x',widthMm:'1',heightMm:'1',quantity:'1',unitPrice:'1',totalPrice:'1',selectedForFutureUse:true}]),null);for(const table of ['estimates','clients','supplier_quotes','project_calculators'])assert.equal((await db.get(`SELECT COUNT(*) count FROM ${table}`)).count,0);});

test("history and session summaries expose friendly status, counts, filenames and current run",async(t)=>{const db=await setup(t);await seed(db);const runs=await createSupplierImportLabExtractionService(db).listRuns('s');assert.equal(runs.length,2);assert.equal(runs.find((run)=>run.selected)?.rowCount,2);assert.equal(runs[0].attachmentFileName,'quote.docx');assert.equal(friendlyRunStatus('completed_with_warnings'),'Completed with warnings');assert.equal(friendlyRunStatus('unsupported'),'OCR required');const session=await createSupplierImportLabService(db).getSession('s');assert.equal(session.extractedRowCount,2);assert.equal(session.selectedRowCount,2);assert.equal(session.latestExtractionStatus,'completed');});

test("review UI provides one bulk workflow, selection, warning details and unsaved protection",async()=>{const source=await readFile(new URL('../src/features/supplierImportLab/SupplierImportLabWorkspace.tsx',import.meta.url),'utf8');assert.equal((source.match(/Save All Corrections/g)||[]).length,1);assert.doesNotMatch(source,/Save corrections/);for(const text of ['Discard Unsaved Changes','Select All','Clear All','rows changed','Technical extraction details','Some document formatting and embedded images were ignored','beforeunload','window.confirm','Current run'])assert.match(source,new RegExp(text));assert.match(source,/selectedForFutureUse/);assert.match(source,/dirtyRowIds/);});
