import assert from "node:assert/strict";
import { createServer, type Server } from "node:http";
import { mkdtemp, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import express from "express";
import sqlite3 from "sqlite3";
import { open, type Database } from "sqlite";
import { initializeSupplierCommercialSchema } from "../server/schema/supplierCommercialSchema.js";
import { createSupplierImportLabRouter } from "../server/routes/supplierImportLab.js";
import { resolveManagedPath } from "../server/features/supplierQuotes/managedAttachmentStorage.js";

function crc32(buffer:Buffer){let crc=0xffffffff;for(const byte of buffer){crc^=byte;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return(crc^0xffffffff)>>>0;}
function zip(entries:Record<string,string>){const locals:Buffer[]=[];const centrals:Buffer[]=[];let offset=0;for(const[name,value]of Object.entries(entries)){const n=Buffer.from(name);const data=Buffer.from(value);const crc=crc32(data);const local=Buffer.alloc(30+n.length);local.writeUInt32LE(0x04034b50,0);local.writeUInt16LE(20,4);local.writeUInt32LE(crc,14);local.writeUInt32LE(data.length,18);local.writeUInt32LE(data.length,22);local.writeUInt16LE(n.length,26);n.copy(local,30);locals.push(local,data);const central=Buffer.alloc(46+n.length);central.writeUInt32LE(0x02014b50,0);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt32LE(crc,16);central.writeUInt32LE(data.length,20);central.writeUInt32LE(data.length,24);central.writeUInt16LE(n.length,28);central.writeUInt32LE(offset,42);n.copy(central,46);centrals.push(central);offset+=local.length+data.length;}const c=Buffer.concat(centrals);const end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(centrals.length,8);end.writeUInt16LE(centrals.length,10);end.writeUInt32LE(c.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...locals,c,end]);}
const pdf=Buffer.from("%PDF-1.7\n%%EOF\n");const docx=zip({"[Content_Types].xml":"<Types/>","word/document.xml":"<w:document/>"});
type Context={db:Database;root:string;base:string;server:Server};
async function setup(t:test.TestContext):Promise<Context>{const root=await mkdtemp(path.join(os.tmpdir(),"quotesync-stage1d1-"));const db=await open({filename:path.join(root,"test.db"),driver:sqlite3.Database});await db.exec(`PRAGMA foreign_keys=ON;CREATE TABLE clients(id TEXT PRIMARY KEY,client_ref TEXT);CREATE TABLE estimates(id TEXT PRIMARY KEY,client_id TEXT,positions_json TEXT);${Array.from({length:8},(_,i)=>`INSERT INTO clients VALUES('c${i+1}','EF-CL-00${i+1}');`).join("")}`);await initializeSupplierCommercialSchema(db);const app=express();app.use(express.json());app.use("/api/admin/supplier-import-lab",await createSupplierImportLabRouter({dbPromise:Promise.resolve(db),attachmentRoot:path.join(root,"attachments")}));const server=createServer(app);await new Promise<void>((resolve)=>server.listen(0,"127.0.0.1",resolve));const address=server.address();const base=`http://127.0.0.1:${typeof address==="object"&&address?address.port:0}`;t.after(async()=>{await new Promise<void>((resolve)=>server.close(()=>resolve()));await db.close();await rm(root,{recursive:true,force:true});});return{db,root,base,server};}
async function json(c:Context,url:string,init?:RequestInit){const response=await fetch(c.base+url,init);const text=await response.text();return{response,data:text?JSON.parse(text):null};}
async function session(c:Context,name="Zyle Fenster"){return(await json(c,"/api/admin/supplier-import-lab/sessions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({supplierName:name,supplierCode:"ZYLE",supplierQuotationNumber:"343117",supplierRevision:"3",fullQuotationReference:"343117-3",currency:"EUR"})})).data;}
function upload(items:Array<{name:string;type:string;bytes:Buffer}>){const body=new FormData();for(const item of items)body.append("files",new Blob([item.bytes],{type:item.type}),item.name);body.append("role","original_quote");return body;}

test("standalone sessions need no client or estimate and preserve production tables",async(t)=>{const c=await setup(t);const first=await session(c);await session(c,"Supplier B");await session(c);assert.ok(first.id);assert.equal((await c.db.get("SELECT COUNT(*) count FROM supplier_import_lab_sessions")).count,3);for(const table of ["estimates","supplier_quotes","supplier_quote_revisions","project_calculators"])assert.equal((await c.db.get(`SELECT COUNT(*) count FROM ${table}`)).count,0);assert.equal((await c.db.get("SELECT COUNT(*) count FROM clients")).count,8);const refs=(await c.db.all("SELECT client_ref FROM clients ORDER BY client_ref")).map((row)=>row.client_ref);assert.deepEqual(refs,Array.from({length:8},(_,i)=>`EF-CL-00${i+1}`));});

test("session metadata, archive visibility and read-only lifecycle round-trip",async(t)=>{const c=await setup(t);const created=await session(c);const changed=await json(c,`/api/admin/supplier-import-lab/sessions/${created.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({supplierRevision:"4",currency:"GBP"})});assert.equal(changed.data.supplierRevision,"4");assert.equal(changed.data.currency,"GBP");const archived=await json(c,`/api/admin/supplier-import-lab/sessions/${created.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:'{"archive":true}'});assert.equal(archived.data.status,"archived");assert.ok(archived.data.archivedAt);assert.equal((await json(c,"/api/admin/supplier-import-lab/sessions")).data.length,0);assert.equal((await json(c,"/api/admin/supplier-import-lab/sessions?include_archived=true")).data.length,1);assert.equal((await json(c,`/api/admin/supplier-import-lab/sessions/${created.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:'{"supplierName":"Changed"}'})).response.status,409);});

test("multi-file upload is atomic, managed and isolated by session",async(t)=>{const c=await setup(t);const a=await session(c);const b=await session(c,"Supplier B");const result=await json(c,`/api/admin/supplier-import-lab/sessions/${a.id}/attachments`,{method:"POST",body:upload([{name:"343117.pdf",type:"application/pdf",bytes:pdf},{name:"343117.docx",type:"application/vnd.openxmlformats-officedocument.wordprocessingml.document",bytes:docx}])});assert.equal(result.response.status,201);assert.equal(result.data.attachments.length,2);assert.equal(result.data.attachments.some((item:Record<string,unknown>)=>"storageKey"in item),false);for(const item of result.data.attachments){const row=await c.db.get("SELECT storage_key FROM supplier_import_lab_attachments WHERE id=?",item.id);assert.match(row.storage_key,new RegExp(`^lab/${a.id}/`));assert.equal((await stat(resolveManagedPath(row.storage_key,path.join(c.root,"attachments")))).isFile(),true);}assert.equal((await json(c,`/api/admin/supplier-import-lab/sessions/${b.id}/attachments/${result.data.attachments[0].id}`)).response.status,404);const invalid=await json(c,`/api/admin/supplier-import-lab/sessions/${b.id}/attachments`,{method:"POST",body:upload([{name:"ok.pdf",type:"application/pdf",bytes:pdf},{name:"bad.pdf",type:"application/pdf",bytes:Buffer.from("bad")}])});assert.equal(invalid.response.status,400);assert.equal((await c.db.get("SELECT COUNT(*) count FROM supplier_import_lab_attachments WHERE session_id=?",b.id)).count,0);});

test("download integrity, attachment removal and session deletion preserve isolation",async(t)=>{const c=await setup(t);const a=await session(c);const b=await session(c,"Supplier B");async function one(id:string){return(await json(c,`/api/admin/supplier-import-lab/sessions/${id}/attachments`,{method:"POST",body:upload([{name:"quote.pdf",type:"application/pdf",bytes:pdf}])})).data.attachments[0];}const aa=await one(a.id);const bb=await one(b.id);const download=await fetch(`${c.base}/api/admin/supplier-import-lab/sessions/${a.id}/attachments/${aa.id}/download`);assert.equal(download.status,200);assert.match(download.headers.get("content-disposition")||"",/^attachment;/);assert.deepEqual(Buffer.from(await download.arrayBuffer()),pdf);assert.equal(await fetch(`${c.base}/api/admin/supplier-import-lab/sessions/${b.id}/attachments/${aa.id}/download`).then((r)=>r.status),404);const row=await c.db.get("SELECT storage_key FROM supplier_import_lab_attachments WHERE id=?",aa.id);await writeFile(resolveManagedPath(row.storage_key,path.join(c.root,"attachments")),"tampered");assert.equal(await fetch(`${c.base}/api/admin/supplier-import-lab/sessions/${a.id}/attachments/${aa.id}/download`).then((r)=>r.status),409);assert.equal(await fetch(`${c.base}/api/admin/supplier-import-lab/sessions/${a.id}/attachments/${aa.id}`,{method:"DELETE"}).then((r)=>r.status),204);assert.equal(await fetch(`${c.base}/api/admin/supplier-import-lab/sessions/${b.id}`,{method:"DELETE"}).then((r)=>r.status),204);assert.equal((await c.db.get("SELECT COUNT(*) count FROM supplier_import_lab_sessions WHERE id=?",a.id)).count,1);assert.equal((await c.db.get("SELECT COUNT(*) count FROM supplier_import_lab_attachments WHERE id=?",bb.id)).count,0);});

test("Admin UI is Estimate-owned and preserves the six-column supplier-evidence boundary",async()=>{const source=await readFile(new URL("../src/features/supplierImportLab/SupplierImportLabWorkspace.tsx",import.meta.url),"utf8");const launcher=await readFile(new URL("../src/features/admin/AdminSupplierQuoteImportBeta.tsx",import.meta.url),"utf8");assert.match(source,/New Import Session/);assert.match(source,/multiple/);assert.match(source,/No extracted positions/);for(const heading of ["Reference","Width","Height","Quantity","Unit Price","Total Price"])assert.match(source,new RegExp(`>${heading}<`));assert.match(source,/"Processing…"\s*:\s*"Extract"/);assert.match(source,/Some document formatting and embedded images were ignored/);assert.match(source,/Technical extraction details/);assert.match(source,/listSessions\(includeArchived,estimateId\)/);assert.match(source,/createScenario\(\{estimateId,origin:"supplier_import"/);assert.doesNotMatch(source,/clientId|ConfiguredPositionContract|Recognit/);assert.match(launcher,/EstimateCommercialWorkspace[^]*estimateId=\{selected\.id\}/);});
