import assert from 'node:assert/strict';
import test from 'node:test';
import os from 'node:os';
import path from 'node:path';
import { mkdtemp,readFile,rm } from 'node:fs/promises';
import sqlite3 from 'sqlite3';
import { open } from 'sqlite';
import { initializeSupplierCommercialSchema } from '../server/schema/supplierCommercialSchema.js';
import { calculateProductGeometry,createProjectCalculatorLabService,COST_CATALOGUE } from '../server/features/projectCalculatorLab/projectCalculatorLabService.js';

async function fixture(t:Parameters<typeof test>[1] extends (arg:infer T)=>unknown?T:never){const root=await mkdtemp(path.join(os.tmpdir(),'qs-stage2a-'));const db=await open({filename:path.join(root,'test.db'),driver:sqlite3.Database});t.after(async()=>{await db.close();await rm(root,{recursive:true,force:true});});await db.exec('PRAGMA foreign_keys=ON;CREATE TABLE estimates(id TEXT PRIMARY KEY);CREATE TABLE clients(id TEXT PRIMARY KEY);');await initializeSupplierCommercialSchema(db);const now=new Date().toISOString();await db.run("INSERT INTO supplier_import_lab_sessions(id,supplier_name,currency,status,created_at,updated_at) VALUES('s','Zyle Fenster','EUR','extracted',?,?)",now,now);await db.run("INSERT INTO supplier_import_lab_attachments(id,session_id,role,original_file_name,media_type,size_bytes,sha256,storage_key,parser_eligible,created_at) VALUES('a','s','original_quote','synthetic.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document',1,?,'lab/s/a/file',1,?)",'a'.repeat(64),now);await db.run("INSERT INTO supplier_import_lab_extraction_runs(id,session_id,attachment_id,extractor_name,extractor_version,field_parser_name,field_parser_version,status,started_at,completed_at,warnings_json,created_at,selected) VALUES('r','s','a','test','1','test','1','completed',?,?, '[]',?,1)",now,now,now);const snapshot=JSON.stringify({displayReference:'W7, W8',supplierReferenceTokens:['W7','W8'],quantity:2,totalPrice:'1074.24'});await db.run("INSERT INTO supplier_import_lab_extracted_rows(id,session_id,extraction_run_id,attachment_id,ordinal,display_reference,original_reference_text,supplier_reference_tokens_json,quantity,width_mm,height_mm,original_dimensions_text,unit_price_amount,total_price_amount,currency,source_pages_json,source_trace_json,warnings_json,confidence,status,created_at,original_extracted_snapshot_json,selected_for_future_use,review_warnings_json) VALUES('row','s','r','a',1,'W7, W8','W7, W8','[\"W7\",\"W8\"]',2,610,1200,'610x1200','537.12','1074.24','EUR','[1]','[]','[]',0.99,'extracted',?,?,1,'[]')",now,snapshot);await db.run("INSERT INTO supplier_import_lab_commercial_summaries(id,session_id,extraction_run_id,attachment_id,currency,product_subtotal_amount,delivery_total_amount,final_supplier_total_amount,source_trace_json,warnings_json,status,original_extracted_snapshot_json,created_at) VALUES('sum','s','r','a','EUR','1074.24','2200.00','3274.24','[]','[]','extracted','{}',?)",now);await db.run("INSERT INTO supplier_import_lab_additional_cost_items(id,summary_id,session_id,extraction_run_id,ordinal,category,original_description,total_price_amount,currency,source_trace_json,warnings_json,status,selected_for_future_use,original_extracted_snapshot_json,created_at) VALUES('cost','sum','s','r',1,'delivery','Delivery','2200.00','EUR','[]','[]','extracted',1,'{}',?)",now);return {db,service:createProjectCalculatorLabService(db)};}

test('exact geometry uses physical quantity while grouped reference remains one row',()=>{assert.deepEqual(calculateProductGeometry(610,1200,2),{areaSquareMetres:'1.464',framePerimeterMetres:'7.24'});assert.deepEqual(calculateProductGeometry(1000,1200,3),{areaSquareMetres:'3.6',framePerimeterMetres:'13.2'});});

test('scenario imports immutable selected evidence and package catalogue without estimate side effects',async(t)=>{const {db,service}=await fixture(t);const scenario=await service.createScenario({name:'Zyle test',packageCode:'support',importLabSessionId:'s',extractionRunId:'r',sourceAttachmentId:'a',installationOpeningCount:1});assert.equal(scenario.products.length,1);assert.equal(scenario.products[0].displayReference,'W7, W8');assert.equal(scenario.products[0].quantity,2);assert.equal(scenario.products[0].productClass,'Needs review');assert.equal(scenario.products[0].currency,'EUR');assert.equal(scenario.supplierCosts[0].amount,'2200.00');assert.equal(scenario.packageItems.length,COST_CATALOGUE.length);assert.equal(scenario.supplierSummary.deliveryTotal,'2200.00');await service.updateProduct(scenario.id,scenario.products[0].id,{productClass:'Window'});const source=await db.get("SELECT display_reference,quantity,total_price_amount,original_extracted_snapshot_json FROM supplier_import_lab_extracted_rows WHERE id='row'");assert.equal(source.display_reference,'W7, W8');assert.equal(source.quantity,2);assert.equal(source.total_price_amount,'1074.24');assert.match(source.original_extracted_snapshot_json,/W7, W8/);for(const table of ['estimates','clients','project_calculators','project_cost_items'])assert.equal((await db.get(`SELECT COUNT(*) count FROM ${table}`)).count,0);});

test('outbound and return route snapshots remain distinct and preserve override evidence',async(t)=>{const {service}=await fixture(t);let scenario=await service.createScenario({name:'Routes',packageCode:'supply_only',importLabSessionId:'s',extractionRunId:'r',sourceAttachmentId:'a',installationOpeningCount:0});scenario=await service.appendRouteSnapshot(scenario.id,{direction:'office_to_site',origin:{label:'Office',lat:'51',lng:'-1'},destination:{label:'Site',lat:'52',lng:'0'},distanceKm:'100.2',durationMinutes:90,trafficDurationMinutes:null,integration:'google_distance_matrix',manuallyOverridden:false});scenario=await service.appendRouteSnapshot(scenario.id,{direction:'site_to_office',origin:{label:'Site',lat:'52',lng:'0'},destination:{label:'Office',lat:'51',lng:'-1'},distanceKm:'104.8',durationMinutes:97,trafficDurationMinutes:110,integration:'manual',manuallyOverridden:true,overrideReason:'Road closure'});assert.equal(scenario.routeSnapshots.length,2);assert.notEqual(scenario.routeSnapshots[0].direction,scenario.routeSnapshots[1].direction);assert.equal(scenario.routeSnapshots.some(r=>r.manuallyOverridden&&r.overrideReason==='Road closure'),true);});

test('feature tabs and central integrations reuse existing providers without customer workflow coupling',async()=>{const [admin,ui,adapter,google,location]=await Promise.all(['src/features/admin/AdminSupplierQuoteImportBeta.tsx','src/features/projectCalculatorLab/ProjectCalculatorLabWorkspace.tsx','src/features/projectCalculatorLab/integrations/routeIntegration.ts','src/services/distance/providers/google.ts','src/services/locationService.ts'].map(file=>readFile(file,'utf8')));assert.match(admin,/Supplier Quote Import/);assert.match(admin,/Project Calculator/);assert.match(ui,/Project Calculator \(Beta\)/);assert.match(ui,/Supply Only|Full Installation/);assert.match(adapter,/googleDistanceProvider/);assert.match(adapter,/resolveWhat3WordsCoordinates/);assert.match(google,/distancematrix/);assert.match(location,/convert-to-coordinates/);assert.doesNotMatch(ui,/ConfiguredPositionContract|customer quotation|estimateId/);});
