import assert from 'node:assert/strict';
import { mkdtemp, rm as removeTree, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import sqlite3 from 'sqlite3';
import { open } from 'sqlite';
import { extractSupplierDocument } from '../server/features/supplierImportLab/documentExtraction.js';
import { normalizeDecimal, parseCommercialFields, parseQuotationReference } from '../server/features/supplierImportLab/commercialFieldParser.js';
import { createSupplierImportLabExtractionService } from '../server/features/supplierImportLab/supplierImportLabExtractionService.js';
import { initializeSupplierCommercialSchema } from '../server/schema/supplierCommercialSchema.js';

async function rm(target:string,options:{recursive:boolean;force:boolean}){try{await removeTree(target,options);}catch(error){if((error as NodeJS.ErrnoException).code!=='EBUSY')throw error;setTimeout(()=>void removeTree(target,options),200);}}

const block = (text:string, readingOrder:number, pageNumber:number|null=1) => ({ id:`b${readingOrder}`, text, pageNumber, boundingBox:pageNumber?{x:10,y:700-readingOrder*10,width:100,height:10}:null, readingOrder, sourceType:pageNumber?'positioned_text':'paragraph' });
function document(lines:string[],mediaType='application/pdf'){return{attachmentId:'attachment',sessionId:'session',mediaType,extractorName:'synthetic',extractorVersion:'1',createdAt:new Date().toISOString(),pages:[{pageNumber:mediaType==='application/pdf'?1:null,pageLabel:'1',width:600,height:800,text:lines.join('\n'),blocks:lines.map((line,index)=>block(line,index,mediaType==='application/pdf'?1:null)),tables:[]}],warnings:[],textAvailable:true,extractionStatus:'completed'};}
const quoteLines=['PRICE OFFER No. 343117-3','W7, W8','1. Product: ignored','Price, EUR','Qty','Total, EUR','610x1200mm','0.73m²','537.12','2','1074.24','W14, W15','Price, EUR','Qty','Total, EUR','610x1050mm','0.64m²','408.79','2','817.58','Back door','Price, EUR','Qty','Total, EUR','940x2065mm','1.94m²','3090.12','1','3090.12','Total excl VAT','16258.75'];

test('quotation metadata and grouped references remain exact independent rows',()=>{const result=parseCommercialFields(document(quoteLines),{currency:'GBP'});assert.deepEqual(result.quotation,{supplierQuotationNumber:'343117',supplierRevision:'3',fullQuotationReference:'343117-3',warnings:[]});assert.equal(result.rows.length,3);assert.deepEqual(result.rows[0].supplierReferenceTokens,['W7','W8']);assert.equal(result.rows[0].displayReference,'W7, W8');assert.equal(result.rows[0].quantity,2);assert.equal(result.rows[1].displayReference,'W14, W15');assert.equal(result.rows[2].displayReference,'Back door');assert.equal(result.rows.some((row)=>row.displayReference==='Total excl VAT'),false);});
test('dimensions, pages, raw evidence and exact money reconciliation survive',()=>{const row=parseCommercialFields(document(quoteLines),{currency:'EUR'}).rows[0];assert.equal(row.widthMm,610);assert.equal(row.heightMm,1200);assert.equal(row.originalDimensionsText,'610x1200mm');assert.deepEqual(row.sourcePages,[1]);assert.equal(row.unitPrice,'537.12');assert.equal(row.totalPrice,'1074.24');assert.equal(row.warnings.length,0);assert.ok(row.sourceTrace.every((trace)=>trace.pageNumber===1));});
test('decimal comma normalizes exactly and mismatch warns without replacing supplied total',()=>{assert.equal(normalizeDecimal('1.234,56 EUR'),'1234.56');const lines=['Quote No. AB12-2','Patio door','Price, EUR','Qty','Total, EUR','920x2020mm','1,86m²','408,79','2','817,59'];const row=parseCommercialFields(document(lines),{currency:'EUR'}).rows[0];assert.equal(row.unitPrice,'408.79');assert.equal(row.totalPrice,'817.59');assert.match(row.warnings.join(' '),/does not equal/);});
test('uncertain quotation suffix is preserved by not inventing revision metadata',()=>{assert.deepEqual(parseQuotationReference('Quotation No. ABC-REV-A'),{supplierQuotationNumber:null,supplierRevision:null,fullQuotationReference:null,warnings:[]});});

test('document metadata cannot leak into the first position reference',()=>{const lines=['Customer: Eco Fenster','Reference: The Aviary','Date: 2026 04 08','PRICE OFFER No. 343718','W0.01','1. Product: 92 Europa window','Price, EUR','Qty','Total, EUR','900x1200mm','1.08m²','500.00','1','500.00'];const parsed=parseCommercialFields(document(lines),{currency:'EUR'});assert.equal(parsed.rows[0].displayReference,'W0.01');assert.equal(parsed.quotation.supplierQuotationNumber,'343718');assert.deepEqual(parsed.metadata,{supplierCustomer:'Eco Fenster',projectReference:'The Aviary',quotationDate:'2026 04 08'});});

test('manufacturer position evidence preserves quoted Ug and Uw without inventing item, Uf, Psi or calculated Uw',()=>{const lines=['PRICE OFFER No. 343117-3','W1','1. Product: 92 Europa window','2. Glass unit: Triple glazing (Ug=0.51 W/m²K)','3. Fittings: Tilt and turn','4. View from inside Left opening','5. Weight 87.4 kg','6. Uw = 0.79 W/m²K','Price, EUR','Qty','Total, EUR','1190x1490mm','1.77m²','1000.00','1','1000.00'];const row=parseCommercialFields(document(lines),{currency:'EUR'}).rows[0];assert.equal(row.manufacturerEvidence.customerReference,'W1');assert.equal(row.manufacturerEvidence.manufacturerItemNumber,null);assert.equal(row.manufacturerEvidence.product,'92 Europa window');assert.equal(row.manufacturerEvidence.manufacturerQuotedUg,'0.51');assert.equal(row.manufacturerEvidence.manufacturerQuotedUw,'0.79');assert.equal(row.manufacturerEvidence.configurationDescription,'View from inside Left opening');assert.equal(row.manufacturerEvidence.sourceVisual.status,'unavailable');assert.doesNotMatch(JSON.stringify(row.manufacturerEvidence),/ufLeft|spacerPsi|calculatedUw/);});
test('manufacturer thermal decimals exclude sentence punctuation without changing quoted values',()=>{const lines=['PRICE OFFER No. 343117-3','W1','1. Product: 92 Europa window','2. Glass unit: Triple glazing (Ug=0.53, 33(-2;-5) dB)','3. Uw = 0.89.','Price, EUR','Qty','Total, EUR','893x1320mm','1.18m²','655.47','1','655.47'];const row=parseCommercialFields(document(lines),{currency:'EUR'}).rows[0];assert.equal(row.manufacturerEvidence.manufacturerQuotedUg,'0.53');assert.equal(row.manufacturerEvidence.manufacturerQuotedUw,'0.89');});

test('explicit manufacturer item number remains distinct from the customer position reference',()=>{const lines=['PRICE OFFER No. 343117-4','W2','Item No: 7','1. Product: 92 Europa window','Price, EUR','Qty','Total, EUR','900x1200mm','1.08m²','500.00','1','500.00'];const evidence=parseCommercialFields(document(lines),{currency:'EUR'}).rows[0].manufacturerEvidence;assert.equal(evidence.manufacturerItemNumber,'7');assert.equal(evidence.customerReference,'W2');});

test('explicit alternative remains in source order with price and commercial exclusion evidence',()=>{const lines=['PRICE OFFER No. 343718','W0.04','1. Product: base design','Price, EUR','Qty','Total, EUR','1200x1400mm','1.68m²','2661.39','1','2661.39','W0.04ALT','Alternative position (not included in total sum of the offer)','1. Product: alternative design','Price, EUR','Qty','Total, EUR','1200x1400mm','1.68m²','1188.38','1','1188.38','W0.05','1. Product: next design','Price, EUR','Qty','Total, EUR','800x1000mm','0.8m²','400.00','1','400.00'];const rows=parseCommercialFields(document(lines),{currency:'EUR'}).rows;assert.deepEqual(rows.map(row=>row.displayReference),['W0.04','W0.04ALT','W0.05']);assert.equal(rows[1].classification,'alternative');assert.equal(rows[1].includedInSupplierTotal,false);assert.equal(rows[1].alternativeTo,'W0.04');assert.equal(rows[1].totalPrice,'1188.38');assert.match(rows[1].classificationEvidence,/not included/i);assert.deepEqual(rows.map(row=>row.ordinal),[0,1,2]);});

function pdfWithText(text:string){const escaped=text.replace(/[()\\]/g,'\\$&');const stream=`BT /F1 11 Tf 50 750 Td (${escaped}) Tj ET`;const objects=[`1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj`,`2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj`,`3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj`,`4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj`,`5 0 obj << /Length ${Buffer.byteLength(stream)} >> stream\n${stream}\nendstream endobj`];let result='%PDF-1.4\n';const offsets=[0];for(const object of objects){offsets.push(Buffer.byteLength(result));result+=object+'\n';}const xref=Buffer.byteLength(result);result+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map((offset)=>String(offset).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer << /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(result);}
function pdfWithLines(lines:string[]){
  const commands=lines.map((line,index)=>`${index?'0 -14 Td ':''}(${line.replace(/[()\\]/g,'\\$&')}) Tj`).join(' ');
  const stream=`BT /F1 11 Tf 50 750 Td ${commands} ET`;
  const objects=[`1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj`,`2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj`,`3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj`,`4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj`,`5 0 obj << /Length ${Buffer.byteLength(stream)} >> stream\n${stream}\nendstream endobj`];
  let result='%PDF-1.4\n';const offsets=[0];for(const object of objects){offsets.push(Buffer.byteLength(result));result+=object+'\n';}const xref=Buffer.byteLength(result);result+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map((offset)=>String(offset).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer << /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(result);
}
function crc32(buffer:Buffer){let crc=0xffffffff;for(const byte of buffer){crc^=byte;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return(crc^0xffffffff)>>>0;}
function zip(entries:Record<string,string>){const locals:Buffer[]=[];const centrals:Buffer[]=[];let offset=0;for(const[name,value]of Object.entries(entries)){const n=Buffer.from(name);const data=Buffer.from(value);const crc=crc32(data);const local=Buffer.alloc(30+n.length);local.writeUInt32LE(0x04034b50,0);local.writeUInt16LE(20,4);local.writeUInt32LE(crc,14);local.writeUInt32LE(data.length,18);local.writeUInt32LE(data.length,22);local.writeUInt16LE(n.length,26);n.copy(local,30);locals.push(local,data);const central=Buffer.alloc(46+n.length);central.writeUInt32LE(0x02014b50,0);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt32LE(crc,16);central.writeUInt32LE(data.length,20);central.writeUInt32LE(data.length,24);central.writeUInt16LE(n.length,28);central.writeUInt32LE(offset,42);n.copy(central,46);centrals.push(central);offset+=local.length+data.length;}const c=Buffer.concat(centrals);const end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(centrals.length,8);end.writeUInt16LE(centrals.length,10);end.writeUInt32LE(c.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...locals,c,end]);}
const xmlEscape=(value:string)=>value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function docx(lines:string[]){const paragraphs=lines.map((line)=>`<w:p><w:r><w:t>${xmlEscape(line)}</w:t></w:r></w:p>`).join('');return zip({'[Content_Types].xml':'<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>','_rels/.rels':'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>','word/document.xml':`<?xml version="1.0"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${paragraphs}</w:body></w:document>`});}

test('machine-readable PDF retains page and positioned blocks; no-text PDF requests bounded OCR',async(t)=>{const root=await mkdtemp(path.join(os.tmpdir(),'qs-stage1e-pdf-'));t.after(()=>rm(root,{recursive:true,force:true}));const readable=path.join(root,'readable.pdf');await writeFile(readable,pdfWithText('PRICE OFFER No. 343117-3 W1 1200x1200mm'));const extracted=await extractSupplierDocument(readable,{id:'a',sessionId:'s',mediaType:'application/pdf'});assert.equal(extracted.pages[0].pageNumber,1);assert.ok(extracted.pages[0].blocks[0].boundingBox);const blank=path.join(root,'blank.pdf');await writeFile(blank,pdfWithText(' '));const unsupported=await extractSupplierDocument(blank,{id:'b',sessionId:'s',mediaType:'application/pdf'});assert.equal(unsupported.extractionStatus,'ocr_required');assert.match(unsupported.warnings[0],/OCR.*required/i);});
test('positioned PDF commercial rows parse without turning totals into positions',async(t)=>{const root=await mkdtemp(path.join(os.tmpdir(),'qs-stage1e-pdf-fields-'));t.after(()=>rm(root,{recursive:true,force:true}));const file=path.join(root,'quote.pdf');await writeFile(file,pdfWithLines(quoteLines));const extracted=await extractSupplierDocument(file,{id:'a',sessionId:'s',mediaType:'application/pdf'});const parsed=parseCommercialFields(extracted,{currency:'EUR'});assert.equal(parsed.rows[0].displayReference,'W7, W8');assert.equal(parsed.rows.length,3);});
test('DOCX paragraphs extract in stable order and malformed/unsafe packages fail safely',async(t)=>{const root=await mkdtemp(path.join(os.tmpdir(),'qs-stage1e-docx-'));t.after(()=>rm(root,{recursive:true,force:true}));const file=path.join(root,'quote.docx');await writeFile(file,docx(quoteLines));const extracted=await extractSupplierDocument(file,{id:'a',sessionId:'s',mediaType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});assert.match(extracted.pages[0].text,/W7, W8/);assert.equal(extracted.pages[0].pageNumber,null);const malformed=path.join(root,'bad.docx');await writeFile(malformed,Buffer.from('PK\x03\x04bad'));await assert.rejects(()=>extractSupplierDocument(malformed,{id:'b',sessionId:'s',mediaType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}),/safe extraction limits/);});

test('persistence appends runs, scopes rows, preserves correction snapshot and blocks evidence deletion',async(t)=>{const root=await mkdtemp(path.join(os.tmpdir(),'qs-stage1e-db-'));t.after(()=>rm(root,{recursive:true,force:true}));const db=await open({filename:path.join(root,'test.db'),driver:sqlite3.Database});t.after(()=>db.close());await db.exec('PRAGMA foreign_keys=ON;CREATE TABLE estimates(id TEXT PRIMARY KEY);');await initializeSupplierCommercialSchema(db);const now=new Date().toISOString();await db.run("INSERT INTO supplier_import_lab_sessions(id,supplier_name,currency,status,created_at,updated_at) VALUES('session','Zyle','EUR','uploaded',?,?)",now,now);await db.run("INSERT INTO supplier_import_lab_attachments(id,session_id,role,original_file_name,media_type,size_bytes,sha256,storage_key,parser_eligible,created_at) VALUES('attachment','session','original_quote','quote.pdf','application/pdf',100,?,'lab/session/attachment/file',1,?)",'a'.repeat(64),now);const service=createSupplierImportLabExtractionService(db);const first=await service.createRun('session','attachment');const parsed=parseCommercialFields(document(quoteLines),{currency:'EUR'});await service.completeRun(first!.id,document(quoteLines),parsed);const second=await service.createRun('session','attachment');await service.completeRun(second!.id,document(quoteLines),parsed);assert.equal((await service.listRuns('session')).length,2);const rows=await service.listRows('session',first!.id);assert.deepEqual(rows!.map(row=>row.ordinal),[0,1,2]);const corrected=await service.correctRow('session',rows![0].id,{...rows![0],displayReference:'Customer W7/W8'});assert.equal(corrected!.displayReference,'Customer W7/W8');assert.equal(corrected!.originalExtractedSnapshot.displayReference,'W7, W8');assert.equal(await service.listRows('other',first!.id),null);assert.equal(await service.hasAttachmentEvidence('session','attachment'),true);});
