import assert from 'node:assert/strict';
import test from 'node:test';
import os from 'node:os';
import path from 'node:path';
import { mkdtemp,readFile,rm } from 'node:fs/promises';
import sqlite3 from 'sqlite3';
import { open } from 'sqlite';
import express from 'express';
import { initializeSupplierCommercialSchema } from '../server/schema/supplierCommercialSchema.js';
import { calculateProductGeometry,createProjectCalculatorLabService,COST_CATALOGUE } from '../server/features/projectCalculatorLab/projectCalculatorLabService.js';
import { createScenarioCreationWorkflow,toScenarioCreationInput,validateScenarioCreation } from '../src/features/projectCalculatorLab/domain/scenarioCreation.js';
import type { CalculatorScenario } from '../src/features/projectCalculatorLab/domain/projectCalculatorLab.types.js';
import { createProjectCalculatorLabRouter } from '../server/routes/projectCalculatorLab.js';
import './stage2a-manual-scenarios.test.js';
import './stage2a-calculator-versioning.test.js';

(globalThis as typeof globalThis & {__quoteSyncExchangeRateTestProvider?:(currency:string)=>Promise<{rawRate:string;provider:string;quotedAt:string}>}).__quoteSyncExchangeRateTestProvider=async()=>({rawRate:'0.875',provider:'test',quotedAt:'2026-08-05T00:00:00.000Z'});

async function fixture(t:Parameters<typeof test>[1] extends (arg:infer T)=>unknown?T:never){const root=await mkdtemp(path.join(os.tmpdir(),'qs-stage2a-'));const db=await open({filename:path.join(root,'test.db'),driver:sqlite3.Database});t.after(async()=>{await db.close();await rm(root,{recursive:true,force:true});});await db.exec('PRAGMA foreign_keys=ON;CREATE TABLE estimates(id TEXT PRIMARY KEY);CREATE TABLE clients(id TEXT PRIMARY KEY);');await initializeSupplierCommercialSchema(db);const now=new Date().toISOString();await db.run("INSERT INTO supplier_import_lab_sessions(id,supplier_name,currency,status,created_at,updated_at) VALUES('s','Zyle Fenster','EUR','extracted',?,?)",now,now);await db.run("INSERT INTO supplier_import_lab_attachments(id,session_id,role,original_file_name,media_type,size_bytes,sha256,storage_key,parser_eligible,created_at) VALUES('a','s','original_quote','synthetic.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document',1,?,'lab/s/a/file',1,?)",'a'.repeat(64),now);await db.run("INSERT INTO supplier_import_lab_extraction_runs(id,session_id,attachment_id,extractor_name,extractor_version,field_parser_name,field_parser_version,status,started_at,completed_at,warnings_json,created_at,selected) VALUES('r','s','a','test','1','test','1','completed',?,?, '[]',?,1)",now,now,now);const snapshot=JSON.stringify({displayReference:'W7, W8',supplierReferenceTokens:['W7','W8'],quantity:2,totalPrice:'1074.24'});await db.run("INSERT INTO supplier_import_lab_extracted_rows(id,session_id,extraction_run_id,attachment_id,ordinal,display_reference,original_reference_text,supplier_reference_tokens_json,quantity,width_mm,height_mm,original_dimensions_text,unit_price_amount,total_price_amount,currency,source_pages_json,source_trace_json,warnings_json,confidence,status,created_at,original_extracted_snapshot_json,selected_for_future_use,review_warnings_json) VALUES('row','s','r','a',1,'W7, W8','W7, W8','[\"W7\",\"W8\"]',2,610,1200,'610x1200','537.12','1074.24','EUR','[1]','[]','[]',0.99,'extracted',?,?,1,'[]')",now,snapshot);await db.run("INSERT INTO supplier_import_lab_commercial_summaries(id,session_id,extraction_run_id,attachment_id,currency,product_subtotal_amount,delivery_total_amount,final_supplier_total_amount,source_trace_json,warnings_json,status,original_extracted_snapshot_json,created_at) VALUES('sum','s','r','a','EUR','1074.24','2200.00','3274.24','[]','[]','extracted','{}',?)",now);await db.run("INSERT INTO supplier_import_lab_additional_cost_items(id,summary_id,session_id,extraction_run_id,ordinal,category,original_description,total_price_amount,currency,source_trace_json,warnings_json,status,selected_for_future_use,original_extracted_snapshot_json,created_at) VALUES('cost','sum','s','r',1,'delivery','Delivery','2200.00','EUR','[]','[]','extracted',1,'{}',?)",now);return {db,service:createProjectCalculatorLabService(db)};}

test('exact geometry uses physical quantity while grouped reference remains one row',()=>{assert.deepEqual(calculateProductGeometry(610,1200,2),{areaSquareMetres:'1.464',framePerimeterMetres:'7.24'});assert.deepEqual(calculateProductGeometry(1000,1200,3),{areaSquareMetres:'3.6',framePerimeterMetres:'13.2'});});

test('scenario imports immutable selected evidence and package catalogue without estimate side effects',async(t)=>{const {db,service}=await fixture(t);const scenario=await service.createScenario({name:'Zyle test',packageCode:'support',importLabSessionId:'s',extractionRunId:'r',sourceAttachmentId:'a',installationOpeningCount:1});assert.equal(scenario.products.length,1);assert.equal(scenario.products[0].displayReference,'W7, W8');assert.equal(scenario.products[0].quantity,2);assert.equal(scenario.products[0].productClass,'Needs review');assert.equal(scenario.products[0].currency,'EUR');assert.equal(scenario.supplierCosts[0].amount,'2200.00');assert.equal(scenario.packageItems.length,COST_CATALOGUE.length);assert.equal(scenario.supplierSummary.deliveryTotal,'2200.00');await service.updateProduct(scenario.id,scenario.products[0].id,{productClass:'Window'});const source=await db.get("SELECT display_reference,quantity,total_price_amount,original_extracted_snapshot_json FROM supplier_import_lab_extracted_rows WHERE id='row'");assert.equal(source.display_reference,'W7, W8');assert.equal(source.quantity,2);assert.equal(source.total_price_amount,'1074.24');assert.match(source.original_extracted_snapshot_json,/W7, W8/);for(const table of ['estimates','clients','project_calculators','project_cost_items'])assert.equal((await db.get(`SELECT COUNT(*) count FROM ${table}`)).count,0);});

test('create workflow validates missing and empty sources, posts once, refreshes and opens the result',async()=>{const source={sessionId:'s',supplierName:'Zyle',currency:'EUR',runId:'r',attachmentId:'a',attachmentFileName:'quote.docx',completedAt:'now',selectedRowCount:1,selectedAdditionalCostCount:1};const draft={name:'Scenario',sourceRunId:'r',packageCode:'support' as const,installationOpeningCount:'2'};assert.match(validateScenarioCreation({...draft,sourceRunId:''},[source])||'',/Select a completed/);assert.match(validateScenarioCreation(draft,[])||'',/No eligible/);assert.match(validateScenarioCreation(draft,[{...source,selectedRowCount:0,selectedAdditionalCostCount:0}])||'',/no positions or additional costs/i);const input=toScenarioCreationInput(draft,source);let postCount=0,refreshCount=0;const opened:string[]=[];let release:((value:CalculatorScenario)=>void)|undefined;const workflow=createScenarioCreationWorkflow(async(payload)=>{postCount++;assert.equal(payload.extractionRunId,'r');return await new Promise<CalculatorScenario>(resolve=>{release=resolve;});});const first=workflow.run(input,async()=>{refreshCount++;},scenario=>opened.push(scenario.id));const second=workflow.run(input,async()=>{refreshCount++;},scenario=>opened.push(scenario.id));assert.equal(first,second);assert.equal(postCount,1);release!({id:'created',name:'Scenario'} as CalculatorScenario);await first;assert.equal(refreshCount,1);assert.deepEqual(opened,['created']);});

test('create workflow exposes server failure and does not refresh or open',async()=>{const workflow=createScenarioCreationWorkflow(async()=>{throw new Error('The extraction run has no selected positions or additional costs.');});let refreshed=false,opened=false;await assert.rejects(()=>workflow.run({name:'Scenario',packageCode:'support',importLabSessionId:'s',extractionRunId:'r',sourceAttachmentId:'a',installationOpeningCount:0},async()=>{refreshed=true;},()=>{opened=true;}),/no selected positions/);assert.equal(refreshed,false);assert.equal(opened,false);});

test('service rejects an evidence-empty source without creating a scenario',async(t)=>{const {db,service}=await fixture(t);await db.run("UPDATE supplier_import_lab_extracted_rows SET selected_for_future_use=0 WHERE extraction_run_id='r'");await db.run("UPDATE supplier_import_lab_additional_cost_items SET selected_for_future_use=0 WHERE extraction_run_id='r'");await assert.rejects(()=>service.createScenario({name:'Empty',packageCode:'support',importLabSessionId:'s',extractionRunId:'r',sourceAttachmentId:'a',installationOpeningCount:0}),/no selected positions or additional costs/i);assert.equal((await db.get('SELECT COUNT(*) count FROM project_calculator_lab_scenarios')).count,0);});

test('POST scenario API returns one opened scenario and structured empty-source failure',async(t)=>{const {db}=await fixture(t);const app=express();app.use(express.json());app.use('/api/admin/project-calculator-lab',await createProjectCalculatorLabRouter({dbPromise:Promise.resolve(db)}));const server=app.listen(0,'127.0.0.1');t.after(()=>new Promise<void>(resolve=>server.close(()=>resolve())));await new Promise<void>(resolve=>server.once('listening',()=>resolve()));const address=server.address();assert.ok(address&&typeof address==='object');const url=`http://127.0.0.1:${address.port}/api/admin/project-calculator-lab/scenarios`;const body={name:'HTTP scenario',packageCode:'support',importLabSessionId:'s',extractionRunId:'r',sourceAttachmentId:'a',installationOpeningCount:1};const created=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});assert.equal(created.status,201);assert.equal((await created.json()).name,'HTTP scenario');assert.equal((await db.get('SELECT COUNT(*) count FROM project_calculator_lab_scenarios')).count,1);await db.run("UPDATE supplier_import_lab_extracted_rows SET selected_for_future_use=0 WHERE extraction_run_id='r'");await db.run("UPDATE supplier_import_lab_additional_cost_items SET selected_for_future_use=0 WHERE extraction_run_id='r'");const failed=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,name:'Empty'})});assert.equal(failed.status,409);const error=await failed.json();assert.equal(error.code,'source_has_no_selected_items');assert.match(error.error,/no selected positions or additional costs/i);assert.equal((await db.get('SELECT COUNT(*) count FROM project_calculator_lab_scenarios')).count,1);});

test('outbound and return route snapshots remain distinct and preserve override evidence',async(t)=>{const {service}=await fixture(t);let scenario=await service.createScenario({name:'Routes',packageCode:'supply_only',importLabSessionId:'s',extractionRunId:'r',sourceAttachmentId:'a',installationOpeningCount:0});scenario=await service.appendRouteSnapshot(scenario.id,{direction:'office_to_site',origin:{label:'Office',lat:'51',lng:'-1'},destination:{label:'Site',lat:'52',lng:'0'},distanceKm:'100.2',durationMinutes:90,trafficDurationMinutes:null,integration:'google_distance_matrix',manuallyOverridden:false});scenario=await service.appendRouteSnapshot(scenario.id,{direction:'site_to_office',origin:{label:'Site',lat:'52',lng:'0'},destination:{label:'Office',lat:'51',lng:'-1'},distanceKm:'104.8',durationMinutes:97,trafficDurationMinutes:110,integration:'manual',manuallyOverridden:true,overrideReason:'Road closure'});assert.equal(scenario.routeSnapshots.length,2);assert.notEqual(scenario.routeSnapshots[0].direction,scenario.routeSnapshots[1].direction);assert.equal(scenario.routeSnapshots.some(r=>r.manuallyOverridden&&r.overrideReason==='Road closure'),true);});

test('estimate workflow and central integrations reuse backend capabilities without customer workflow coupling',async()=>{const [admin,ui,workflow,adapter,location]=await Promise.all(['src/features/admin/AdminSupplierQuoteImportBeta.tsx','src/features/projectCalculatorLab/ProjectCalculatorLabWorkspace.tsx','src/features/estimateCommercial/EstimateCommercialWorkspace.tsx','src/features/projectCalculatorLab/integrations/routeIntegration.ts','src/services/locationService.ts'].map(file=>readFile(file,'utf8')));assert.match(admin,/commercial workflow/i);assert.doesNotMatch(admin,/<ProjectCalculatorLabWorkspace|<SupplierImportLabWorkspace/);assert.match(workflow,/Import Supplier Costs/);assert.match(workflow,/Project Costing/);assert.match(ui,/Supply Only|Full Installation/);assert.match(ui,/creationWorkflow\.current\.run/);assert.match(ui,/Project Costing .* created and opened/);assert.match(ui,/role=\{messageKind==="error"\?"alert"/);assert.match(adapter,/\/api\/integrations\/googleMaps\/geocode/);assert.match(adapter,/\/api\/integrations\/googleMaps\/route/);assert.match(adapter,/resolveWhat3WordsCoordinates/);assert.doesNotMatch(adapter,/googleDistanceProvider/);assert.match(location,/\/api\/integrations\/what3words\/coordinates/);assert.doesNotMatch(ui,/ConfiguredPositionContract|customer quotation/);});
