import assert from 'node:assert/strict';import test from 'node:test';
import {applyDiscountStages,calculateCustomerDiscount,calculateSupplierCommercialPolicy,normalizeSupplierCommercialPolicy,resolveDiscountStages} from '../server/features/projectCalculatorLab/supplierCommercialPricing.js';

test('compound discounts retain stages and calculate 35.875 percent exactly',()=>{const result=applyDiscountStages('10000',[{sequence:0,percentage:'25'},{sequence:1,percentage:'10'},{sequence:2,percentage:'5'}]);assert.equal(result.resultingAmount,'6412.50');assert.equal(result.effectiveDiscountPercentage,'35.875');assert.deepEqual(result.stages.map(item=>item.percentage),['25','10','5']);});
test('tier thresholds use manufacturer list value before discounts',()=>{const policy={type:'tiered',thresholdBasis:'manufacturer_list_before_discounts',stages:[{sequence:0,thresholdAmount:'0',percentage:'47.5'},{sequence:1,thresholdAmount:'10000',percentage:'10'},{sequence:2,thresholdAmount:'20000',percentage:'5'}]};assert.equal(resolveDiscountStages(policy,'9999.99').length,1);assert.equal(resolveDiscountStages(policy,'10000').length,2);assert.equal(resolveDiscountStages(policy,'25000').length,3);});
test('Glassworx packages retain evidence, base supply and exact service uplifts',()=>{const common={pricingBasis:'net_buying_price',quotedCurrency:'GBP',quotedAmount:'82786.66',paidInQuotedCurrency:true,settlementCurrency:'GBP',settlementAmountMode:'confirmed',settlementFxSnapshot:{quotedToSettlementRate:'1',settlementToGbpRate:'1'},packages:[{id:'bronze',label:'Bronze',amount:'80258.73',isBase:true},{id:'silver',label:'Silver',amount:'82786.66',upliftCategory:'installation'},{id:'gold',label:'Gold',amount:'96700.99',upliftCategory:'installation'}]};const silver=calculateSupplierCommercialPolicy({...common,selectedPackageId:'silver'}),gold=calculateSupplierCommercialPolicy({...common,selectedPackageId:'gold'});assert.equal(silver.basePackageAmount,'80258.73');assert.equal(silver.packageUplift,'2527.93');assert.equal(gold.packageUplift,'16442.26');assert.equal(silver.actualGbpPurchaseCost,'82786.66');});
test('quoted evidence is immutable while GBP quotation settles in confirmed or estimated EUR',()=>{const quoted={quotedCurrency:'GBP',quotedAmount:'5989.85',paidInQuotedCurrency:false,settlementCurrency:'EUR',pricingBasis:'net_buying_price',settlementFxSnapshot:{quotedToSettlementRate:'1.176470588235',settlementToGbpRate:'0.85'}};const confirmed=calculateSupplierCommercialPolicy({...quoted,settlementAmountMode:'confirmed',confirmedSettlementAmount:'7000'}),estimated=calculateSupplierCommercialPolicy({...quoted,settlementAmountMode:'estimated'});assert.equal(confirmed.policy.quotedCurrency,'GBP');assert.equal(confirmed.settlementAmount,'7000');assert.equal(confirmed.actualGbpPurchaseCost,'5950.00');assert.equal(estimated.settlementAmountEstimated,true);assert.equal(estimated.policy.quotedAmount,'5989.85');});
test('project supplier and customer discounts remain independent',()=>{const supplier=calculateSupplierCommercialPolicy({pricingBasis:'net_buying_price',quotedCurrency:'GBP',quotedAmount:'10000',projectDiscount:{mode:'percentage',percentage:'5'},paidInQuotedCurrency:true,settlementCurrency:'GBP',settlementFxSnapshot:{quotedToSettlementRate:'1',settlementToGbpRate:'1'}}),customer=calculateCustomerDiscount('15000',{mode:'fixed',amount:'1500'});assert.equal(supplier.projectDiscountAmount,'500.00');assert.equal(supplier.discountedSupplierPurchaseAmount,'9500.00');assert.equal(customer.percentage,'10.00');assert.equal(customer.finalSellingPrice,'13500.00');});
test('legacy policy defaults settlement to quoted currency and net pricing',()=>{const policy=normalizeSupplierCommercialPolicy({quotedCurrency:'EUR',quotedAmount:'100'});assert.equal(policy.settlementCurrency,'EUR');assert.equal(policy.paidInQuotedCurrency,true);assert.equal(policy.pricingBasis,'net_buying_price');});
test('single discount and fixed project discount retain their separate values',()=>{const result=calculateSupplierCommercialPolicy({pricingBasis:'manufacturer_list',manufacturerListAmount:'10000',quotedAmount:'10000',discountPolicy:{type:'single',percentage:'25'},projectDiscount:{mode:'fixed',amount:'500'},paidInQuotedCurrency:true,quotedCurrency:'GBP',settlementCurrency:'GBP',settlementFxSnapshot:{quotedToSettlementRate:'1',settlementToGbpRate:'1'}});assert.equal(result.standardNetBuyingAmount,'7500.00');assert.equal(result.projectDiscountAmount,'500');assert.equal(result.projectDiscountPercentage,'6.666667');assert.equal(result.discountedSupplierPurchaseAmount,'7000.00');});
test('package configuration rejects missing or duplicate base packages',()=>{assert.throws(()=>calculateSupplierCommercialPolicy({packagePricingAvailable:true,packages:[],quotedAmount:'1'}),/exactly one/);assert.throws(()=>calculateSupplierCommercialPolicy({packagePricingAvailable:true,packages:[{id:'a',isBase:true,amount:'1'},{id:'b',isBase:true,amount:'2'}],quotedAmount:'1'}),/exactly one/);});
test('discount application basis is explicit for complete package, base, and uplift',()=>{const common={pricingBasis:'manufacturer_list',manufacturerListAmount:'100',discountPolicy:{type:'single',percentage:'10'},projectDiscount:{mode:'percentage',percentage:'0'},quotedCurrency:'GBP',paidInQuotedCurrency:true,settlementCurrency:'GBP',settlementFxSnapshot:{quotedToSettlementRate:'1',settlementToGbpRate:'1'},packagePricingAvailable:true,packages:[{id:'base',amount:'100',isBase:true},{id:'service',amount:'120',upliftCategory:'installation'}],selectedPackageId:'service'};const complete=calculateSupplierCommercialPolicy({...common,manufacturerListAmount:null,discountApplicationBasis:'selected_complete_package'}),base=calculateSupplierCommercialPolicy({...common,manufacturerListAmount:null,discountApplicationBasis:'base_supply_only'}),uplift=calculateSupplierCommercialPolicy({...common,manufacturerListAmount:null,discountApplicationBasis:'package_uplift'});assert.equal(complete.selectedPackageAmount,'108.00');assert.equal(base.selectedPackageAmount,'110.00');assert.equal(uplift.selectedPackageAmount,'118.00');});
test('customer percentage discount is a negative selling adjustment only',()=>{const result=calculateCustomerDiscount('30000',{mode:'percentage',percentage:'5'});assert.equal(result.amount,'1500.00');assert.equal(result.finalSellingPrice,'28500.00');});
test('GBP paid in GBP remains identity while supplier policies stay independent',()=>{const glass=calculateSupplierCommercialPolicy({quotedCurrency:'GBP',quotedAmount:'100',paidInQuotedCurrency:true,settlementCurrency:'GBP',settlementFxSnapshot:{quotedToSettlementRate:'1',settlementToGbpRate:'1'}}),zyle=calculateSupplierCommercialPolicy({quotedCurrency:'EUR',quotedAmount:'100',paidInQuotedCurrency:true,settlementCurrency:'EUR',settlementFxSnapshot:{quotedToSettlementRate:'1',settlementToGbpRate:'0.85'}});assert.equal(glass.actualGbpPurchaseCost,'100.00');assert.equal(zyle.actualGbpPurchaseCost,'85.00');assert.equal(glass.policy.quotedCurrency,'GBP');assert.equal(zyle.policy.quotedCurrency,'EUR');});
test('alternative evidence is excluded before the supplier commercial policy base',()=>{const included=['2661.39','3051.76'],alternatives=['1188.38','2580.29'];const includedTotal=included.reduce((sum,value)=>String(Number(sum)+Number(value)),'0');const result=calculateSupplierCommercialPolicy({quotedCurrency:'EUR',quotedAmount:includedTotal,paidInQuotedCurrency:true,settlementCurrency:'EUR',settlementFxSnapshot:{quotedToSettlementRate:'1',settlementToGbpRate:'0.85'}});assert.equal(result.policy.quotedAmount,'5713.15');assert.equal(alternatives.length,2);});
