// Generated by scripts/extract-europa92-type5-authority-linework.mjs
// Source: _project/Test/Europa 92 Alu Clad/2 Field/Table_Test/2 Field, Type 5.dxf
// Do not edit by hand; regenerate from the approved authority DXF.

export type Europa92Type5AuthorityLine = {
  type: "LINE";
  layer: string;
  handle: string;
  sourceLine: number;
  x1: number;
  y1: number;
  x2: number;
  y2: number;
};

export type Europa92Type5AuthorityCircle = {
  type: "CIRCLE";
  layer: string;
  handle: string;
  sourceLine: number;
  cx: number;
  cy: number;
  r: number;
};

export type Europa92Type5AuthorityText = {
  type: "TEXT";
  layer: string;
  handle: string;
  sourceLine: number;
  x: number;
  y: number;
  height: number;
  value: string;
};

export const EUROPA92_TYPE5_AUTHORITY_LINEWORK_SOURCE = {
  "dxfPath": "_project/Test/Europa 92 Alu Clad/2 Field/Table_Test/2 Field, Type 5.dxf",
  "includedSections": [
    "ENTITIES"
  ],
  "geometryRule": "Render only LINE entities on layer Medis hatch. Other extracted ENTITIES are authority annotations and are excluded from visual preview.",
  "renderedEntityTypes": [
    "LINE"
  ],
  "renderedLayers": [
    "Medis hatch"
  ],
  "excludedAnnotationEntityTypes": [
    "LINE",
    "CIRCLE",
    "TEXT"
  ],
  "ignoredEntityTypes": [
    "MTEXT",
    "ACAD_TABLE",
    "INSERT",
    "LWPOLYLINE",
    "ARC",
    "HATCH"
  ],
  "allExtractedBounds": {
    "minX": 1283.338423560286,
    "maxX": 3312.275667253212,
    "minY": 1508.21013561479,
    "maxY": 2524.531846303668
  },
  "bounds": {
    "minX": 1283.338423560286,
    "maxX": 3283.338423560286,
    "minY": 1508.21013561479,
    "maxY": 2508.210135614791
  },
  "normalizedBounds": {
    "minX": 0,
    "minY": 0,
    "maxX": 720,
    "maxY": 360
  },
  "scale": 0.35999999999999965,
  "renderedEntityCount": 54,
  "excludedAnnotationEntityCount": 20,
  "extractedEntityTypeCounts": {
    "LINE": 58,
    "CIRCLE": 7,
    "TEXT": 9
  },
  "renderedLayerCounts": {
    "Medis hatch": 54
  },
  "excludedAnnotationLayerCounts": {
    "MATMENYS": 20
  },
  "excludedAnnotationLayers": [
    "MATMENYS"
  ]
} as const;

export const EUROPA92_TYPE5_AUTHORITY_GEOMETRY_LINES = [
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3A4",
    "sourceLine": 6957,
    "x1": 1283.338423560286,
    "y1": 1508.21013561479,
    "x2": 2283.338423560286,
    "y2": 1508.21013561479
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3A5",
    "sourceLine": 6983,
    "x1": 3283.338423560286,
    "y1": 1508.21013561479,
    "x2": 3283.338423560286,
    "y2": 2508.210135614791
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3A6",
    "sourceLine": 7009,
    "x1": 1283.338423560286,
    "y1": 2508.210135614791,
    "x2": 1283.338423560286,
    "y2": 1508.21013561479
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3A7",
    "sourceLine": 7035,
    "x1": 2283.338423560286,
    "y1": 1508.21013561479,
    "x2": 3283.338423560286,
    "y2": 1508.21013561479
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3A8",
    "sourceLine": 7061,
    "x1": 1283.338423560286,
    "y1": 2508.210135614791,
    "x2": 2283.338423560286,
    "y2": 2508.210135614791
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3A9",
    "sourceLine": 7087,
    "x1": 2283.338423560286,
    "y1": 2508.210135614791,
    "x2": 3283.338423560286,
    "y2": 2508.210135614791
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3AA",
    "sourceLine": 7113,
    "x1": 3283.338423560286,
    "y1": 1566.21013561479,
    "x2": 3245.838423560286,
    "y2": 1566.21013561479
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3AB",
    "sourceLine": 7139,
    "x1": 1320.838423560286,
    "y1": 2465.210135614805,
    "x2": 1320.838423560286,
    "y2": 1566.21013561479
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3AC",
    "sourceLine": 7165,
    "x1": 3245.838423560286,
    "y1": 1566.21013561479,
    "x2": 3245.838423560286,
    "y2": 2470.710135614791
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3AD",
    "sourceLine": 7191,
    "x1": 3245.838423560286,
    "y1": 1560.71013561479,
    "x2": 3245.838423560286,
    "y2": 2470.710135614791
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3AE",
    "sourceLine": 7217,
    "x1": 3188.838423560286,
    "y1": 1560.71013561479,
    "x2": 3188.838423560286,
    "y2": 2470.710135614791
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3AF",
    "sourceLine": 7243,
    "x1": 1320.838423560286,
    "y1": 2470.710135614805,
    "x2": 1320.838423560228,
    "y2": 1560.71013561479
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3B0",
    "sourceLine": 7269,
    "x1": 1377.838423560286,
    "y1": 2470.710135614805,
    "x2": 1377.838423560286,
    "y2": 1560.71013561479
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3B1",
    "sourceLine": 7295,
    "x1": 1320.838423560286,
    "y1": 2470.710135614805,
    "x2": 2267.338423560286,
    "y2": 2470.710135614805
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3B2",
    "sourceLine": 7321,
    "x1": 1377.838423560286,
    "y1": 2419.210135614791,
    "x2": 2238.838423560286,
    "y2": 2419.210135614791
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3B3",
    "sourceLine": 7347,
    "x1": 2270.838423560286,
    "y1": 2470.710135614805,
    "x2": 3245.838423560286,
    "y2": 2470.710135614791
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3B4",
    "sourceLine": 7373,
    "x1": 2329.338423560286,
    "y1": 2419.210135614791,
    "x2": 3188.838423560286,
    "y2": 2419.210135614791
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3B5",
    "sourceLine": 7399,
    "x1": 2265.838423560228,
    "y1": 1560.71013561479,
    "x2": 2265.838423560286,
    "y2": 2470.710135614805
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3B6",
    "sourceLine": 7425,
    "x1": 2270.838423560286,
    "y1": 1560.71013561479,
    "x2": 2270.838423560286,
    "y2": 2470.710135614791
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3B7",
    "sourceLine": 7451,
    "x1": 2238.838423560228,
    "y1": 1560.71013561479,
    "x2": 2238.838423560286,
    "y2": 2470.710135614805
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3B8",
    "sourceLine": 7477,
    "x1": 2327.838423560286,
    "y1": 1560.71013561479,
    "x2": 2327.838423560286,
    "y2": 2470.710135614791
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3B9",
    "sourceLine": 7503,
    "x1": 2270.838423560286,
    "y1": 1560.71013561479,
    "x2": 3245.838423560286,
    "y2": 1560.71013561479
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3BA",
    "sourceLine": 7529,
    "x1": 2265.838423560228,
    "y1": 1560.71013561479,
    "x2": 1320.838423560228,
    "y2": 1560.71013561479
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3BB",
    "sourceLine": 7555,
    "x1": 2238.838423560228,
    "y1": 1617.710135614833,
    "x2": 1377.838423560228,
    "y2": 1617.71013561479
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3BC",
    "sourceLine": 7581,
    "x1": 2327.838423560315,
    "y1": 1617.710135614819,
    "x2": 3188.838423560286,
    "y2": 1617.710135614717
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3BD",
    "sourceLine": 7607,
    "x1": 2270.838423560286,
    "y1": 2451.210135614805,
    "x2": 2265.838423560286,
    "y2": 2451.210135614805
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3BE",
    "sourceLine": 7635,
    "x1": 1320.838423560286,
    "y1": 1566.21013561479,
    "x2": 1283.338423560286,
    "y2": 1566.21013561479
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3BF",
    "sourceLine": 7661,
    "x1": 1398.838423560286,
    "y1": 2398.210135614791,
    "x2": 1398.838423560228,
    "y2": 1638.71013561479
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3C0",
    "sourceLine": 7687,
    "x1": 1398.838423560286,
    "y1": 2398.210135614791,
    "x2": 2217.838423560286,
    "y2": 2398.210135614791
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3C1",
    "sourceLine": 7713,
    "x1": 2217.838423560286,
    "y1": 2398.210135614791,
    "x2": 2217.838423560228,
    "y2": 1638.71013561479
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3C2",
    "sourceLine": 7739,
    "x1": 1377.838423560286,
    "y1": 2419.210135614791,
    "x2": 1398.838423560286,
    "y2": 2398.210135614791
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3C3",
    "sourceLine": 7765,
    "x1": 2238.838423560286,
    "y1": 2419.210135614791,
    "x2": 2217.838423560286,
    "y2": 2398.210135614791
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3C4",
    "sourceLine": 7791,
    "x1": 1377.838423560286,
    "y1": 1617.71013561479,
    "x2": 1398.838423560286,
    "y2": 1638.71013561479
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3C5",
    "sourceLine": 7817,
    "x1": 1398.838423560228,
    "y1": 1638.71013561479,
    "x2": 2217.838423560228,
    "y2": 1638.71013561479
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3C6",
    "sourceLine": 7843,
    "x1": 2238.838423560228,
    "y1": 1617.710135614833,
    "x2": 2217.838423560228,
    "y2": 1638.71013561479
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3C7",
    "sourceLine": 7869,
    "x1": 3167.838423560315,
    "y1": 1638.710135614834,
    "x2": 3167.838423560315,
    "y2": 2398.210135614907
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3C8",
    "sourceLine": 7895,
    "x1": 2327.838423560286,
    "y1": 2419.210135614907,
    "x2": 3188.838423560316,
    "y2": 2419.210135614907
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3C9",
    "sourceLine": 7921,
    "x1": 2348.838423560286,
    "y1": 2398.210135614907,
    "x2": 3167.838423560315,
    "y2": 2398.210135614907
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3CA",
    "sourceLine": 7947,
    "x1": 2327.838423560286,
    "y1": 2419.210135614907,
    "x2": 2348.838423560286,
    "y2": 2398.210135614907
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3CB",
    "sourceLine": 7973,
    "x1": 2348.838423560286,
    "y1": 2398.210135614907,
    "x2": 2348.838423560286,
    "y2": 1638.710135614951
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3CC",
    "sourceLine": 7999,
    "x1": 2327.838423560315,
    "y1": 1617.710135614819,
    "x2": 2348.838423560286,
    "y2": 1638.710135614951
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3CD",
    "sourceLine": 8025,
    "x1": 3167.838423560315,
    "y1": 1638.710135614834,
    "x2": 3188.838423560286,
    "y2": 1617.710135614717
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3CE",
    "sourceLine": 8051,
    "x1": 3188.838423560316,
    "y1": 2419.210135614907,
    "x2": 3167.838423560315,
    "y2": 2398.210135614907
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3CF",
    "sourceLine": 8077,
    "x1": 1377.838423560228,
    "y1": 1617.71013561479,
    "x2": 2238.838423560228,
    "y2": 1617.710135614833
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3D0",
    "sourceLine": 8103,
    "x1": 2238.838423560286,
    "y1": 1623.210135614834,
    "x2": 2238.838423560286,
    "y2": 2419.210135614791
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3D1",
    "sourceLine": 8129,
    "x1": 2327.838423560286,
    "y1": 2419.210135614907,
    "x2": 2327.838423560315,
    "y2": 1623.21013561495
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3D2",
    "sourceLine": 8155,
    "x1": 3188.838423560316,
    "y1": 2419.210135614907,
    "x2": 3188.838423560316,
    "y2": 1623.210135614834
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3D3",
    "sourceLine": 8181,
    "x1": 1398.838423560286,
    "y1": 2398.210135614791,
    "x2": 2217.838423560286,
    "y2": 2021.21013561479
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3D4",
    "sourceLine": 8209,
    "x1": 2217.838423560286,
    "y1": 2021.21013561479,
    "x2": 1398.838423560228,
    "y2": 1638.710135614732
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3D5",
    "sourceLine": 8237,
    "x1": 3167.838423560315,
    "y1": 2398.210135614907,
    "x2": 2348.838423560286,
    "y2": 2021.210135614936
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3D6",
    "sourceLine": 8265,
    "x1": 2348.838423560286,
    "y1": 2021.210135614936,
    "x2": 3167.838423560315,
    "y2": 1638.710135614834
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3D7",
    "sourceLine": 8293,
    "x1": 3167.838423560315,
    "y1": 1638.710135614834,
    "x2": 2758.338423560315,
    "y2": 2398.210135614907
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3D8",
    "sourceLine": 8321,
    "x1": 2758.338423560315,
    "y1": 2398.210135614907,
    "x2": 2348.838423560286,
    "y2": 1638.710135614951
  },
  {
    "type": "LINE",
    "layer": "Medis hatch",
    "handle": "3D9",
    "sourceLine": 8349,
    "x1": 2348.838423560286,
    "y1": 1638.710135614951,
    "x2": 3167.838423560315,
    "y2": 1638.710135614834
  }
] as const satisfies readonly Europa92Type5AuthorityLine[];

export const EUROPA92_TYPE5_AUTHORITY_ANNOTATION_LINES = [
  {
    "type": "LINE",
    "layer": "MATMENYS",
    "handle": "3DA",
    "sourceLine": 8375,
    "x1": 2270.838423560286,
    "y1": 1565.21013561479,
    "x2": 2265.838423560228,
    "y2": 1565.21013561479
  },
  {
    "type": "LINE",
    "layer": "MATMENYS",
    "handle": "3DB",
    "sourceLine": 8403,
    "x1": 3283.338423560286,
    "y1": 2451.210135614791,
    "x2": 3245.838423560286,
    "y2": 2451.210135614791
  },
  {
    "type": "LINE",
    "layer": "MATMENYS",
    "handle": "3DC",
    "sourceLine": 8431,
    "x1": 1283.338423560286,
    "y1": 2451.210135614791,
    "x2": 1320.838423560286,
    "y2": 2451.210135614791
  },
  {
    "type": "LINE",
    "layer": "MATMENYS",
    "handle": "3DD",
    "sourceLine": 8459,
    "x1": 2265.838423560286,
    "y1": 2470.710135614805,
    "x2": 2270.838423560286,
    "y2": 2470.710135614791
  }
] as const satisfies readonly Europa92Type5AuthorityLine[];

export const EUROPA92_TYPE5_AUTHORITY_ANNOTATION_CIRCLES = [
  {
    "type": "CIRCLE",
    "layer": "MATMENYS",
    "handle": "3DE",
    "sourceLine": 8487,
    "cx": 1353.811946330912,
    "cy": 2021.038011538301,
    "r": 70.473522770626
  },
  {
    "type": "CIRCLE",
    "layer": "MATMENYS",
    "handle": "3E0",
    "sourceLine": 8537,
    "cx": 2281.913265850366,
    "cy": 1578.683658385416,
    "r": 70.473522770626
  },
  {
    "type": "CIRCLE",
    "layer": "MATMENYS",
    "handle": "3E2",
    "sourceLine": 8587,
    "cx": 2280.056109094731,
    "cy": 2454.058323533042,
    "r": 70.473522770626
  },
  {
    "type": "CIRCLE",
    "layer": "MATMENYS",
    "handle": "3E4",
    "sourceLine": 8637,
    "cx": 3241.802144482586,
    "cy": 2014.397367432801,
    "r": 70.473522770626
  },
  {
    "type": "CIRCLE",
    "layer": "MATMENYS",
    "handle": "3E6",
    "sourceLine": 8687,
    "cx": 2285.518796698889,
    "cy": 2016.46058835111,
    "r": 70.473522770626
  },
  {
    "type": "CIRCLE",
    "layer": "MATMENYS",
    "handle": "3E8",
    "sourceLine": 8737,
    "cx": 1781.659335998818,
    "cy": 2014.373339817845,
    "r": 70.473522770626
  },
  {
    "type": "CIRCLE",
    "layer": "MATMENYS",
    "handle": "3EA",
    "sourceLine": 8787,
    "cx": 2761.307219008683,
    "cy": 2013.601616193759,
    "r": 70.473522770626
  }
] as const satisfies readonly Europa92Type5AuthorityCircle[];

export const EUROPA92_TYPE5_AUTHORITY_ANNOTATION_TEXTS = [
  {
    "type": "TEXT",
    "layer": "MATMENYS",
    "handle": "3DF",
    "sourceLine": 8511,
    "x": 1309.167389534181,
    "y": 2013.188415182623,
    "height": 20,
    "value": "B92-10"
  },
  {
    "type": "TEXT",
    "layer": "MATMENYS",
    "handle": "3E1",
    "sourceLine": 8561,
    "x": 2246.409340390266,
    "y": 1567.159802983224,
    "height": 20,
    "value": "B92-8"
  },
  {
    "type": "TEXT",
    "layer": "MATMENYS",
    "handle": "3E3",
    "sourceLine": 8611,
    "x": 2235.411552297999,
    "y": 2446.208727177364,
    "height": 20,
    "value": "B92-7"
  },
  {
    "type": "TEXT",
    "layer": "MATMENYS",
    "handle": "3E5",
    "sourceLine": 8661,
    "x": 3197.157587685855,
    "y": 2006.547771077123,
    "height": 20,
    "value": "B92-7"
  },
  {
    "type": "TEXT",
    "layer": "MATMENYS",
    "handle": "3E7",
    "sourceLine": 8711,
    "x": 2250.014871238789,
    "y": 2004.936732948918,
    "height": 20,
    "value": "B92-18"
  },
  {
    "type": "TEXT",
    "layer": "MATMENYS",
    "handle": "3E9",
    "sourceLine": 8761,
    "x": 1772.807159348216,
    "y": 2010.478379734486,
    "height": 20,
    "value": "1"
  },
  {
    "type": "TEXT",
    "layer": "MATMENYS",
    "handle": "3EB",
    "sourceLine": 8811,
    "x": 2761.95422587177,
    "y": 2008.607580939235,
    "height": 20,
    "value": "2"
  },
  {
    "type": "TEXT",
    "layer": "MATMENYS",
    "handle": "3EC",
    "sourceLine": 8837,
    "x": 1722.174074007489,
    "y": 1917.177834908871,
    "height": 20,
    "value": "Turn Left"
  },
  {
    "type": "TEXT",
    "layer": "MATMENYS",
    "handle": "3ED",
    "sourceLine": 8863,
    "x": 2656.486836199008,
    "y": 1913.415586636562,
    "height": 20,
    "value": "Tilt and Turn Right"
  }
] as const satisfies readonly Europa92Type5AuthorityText[];
