export const QUOTE_COMPARISON_EVIDENCE_DISCLAIMER: string;

export type ComparisonThermalMetric = {raw:string|null;value:number|null;precision:number|null;basis:string|null;standard:string|null;standardSizeMm:{width:number;height:number}|null;qualification:string|null;sourceFieldId:string|null;sourcePage:number|null;inheritedFromSystem:string|null;valueKind:string;label:string|null;meaning:string|null;status:string};
export type ComparisonCommercialBreakdown = {currency:string|null;grossSupply:number|null;discountPercentage:number|null;discountAmount:number|null;netSupply:number|null;extras:number|null;extrasLabels:string[];delivery:number|null;installation:number|null;survey:number|null;vat:number|null;vatStatus:string;headlineTotal:number|null;scopeKind:string;normalizationStatus:string;normalizationReason:string;scopeEvidence:Record<string,unknown>;sourceReconciliation:Record<string,unknown>};
export type ComparisonClarification = {category:string;message:string;positionReferences:string[];severity:string};
export type ComparisonSourceDrawing = {status:"available"|"unavailable";url:string|null;role:string|null;sourcePage:number|null;mappingMethod:string|null;reason:string|null;supplierName:string;proposalId:string;mappingId:string;sourceReference:string;sourceAttachmentId:string|null;sourceRevisionId:string|null;sourceRowKey:string|null;relationship:string;isAlternative:boolean};
export type ComparisonSourceReference = {ownerKind:"baseline"|"competitor";supplierName:string;manufacturerName:string|null;role:string;fileName:string;quotationNumber:string|null;quotationRevision:string|null;quotationDate:string|null;sourceId:string|null};

export type QuoteComparisonReportOffer = {
  offerKey:string;proposalId:string;supplierName:string;manufacturerName:string|null;reference:string;relationship:string;
  assessment:{label:string;tone:"positive"|"warning"|"danger"|"neutral"};assessmentCode:string;explanation:string;
  attributes:{measurements:string;internalFinish:string;externalFinish:string;productSystem:string;productFamily:string;material:string;aluminiumCladding:string;glass:string;ug:string;g:string;lt:string;uw:string;hardware:string;configuration:string;operation:string;division:string;interfaces:string;thermalEvidence:{ug:ComparisonThermalMetric;uw:ComparisonThermalMetric;g:ComparisonThermalMetric;lt:ComparisonThermalMetric};security:{status:string;label:string;standards:string[];certification:string|null};sourceEvidence:{system:string|null;systemSourcePage:number|null;positionSourcePages:number[];inheritanceRule:string|null;systemThermal:ComparisonThermalMetric|null};systemEvidence:Array<{system:string|null;systemSourcePage:number|null;positionSourcePages:number[];inheritanceRule:string|null;systemThermal:ComparisonThermalMetric|null}>};
  compliance:{status:string;label:string;compromises:string[];materialFailures:string[];reviewItems:string[]};commercial:{basis:string;grossItemCost:number|null;grossQuantityCost:number|null;discountPercentage:number|null;discountAmount:number|null;netItemCost:number|null;netQuantityCost:number|null;supportingComponentCost:number|null;completePositionPriceEligible:boolean;components:Array<{reference:string;productSystem:string;productFamily:string;material:string;quantity:number|null;grossUnitPrice:number|null;grossQuantityTotal:number|null;netUnitPrice:number|null;netQuantityTotal:number|null}>;supportingComponents:Array<{role:string;reference:string;description:string;quantity:number|null;amount:number|null}>;sourcePricesPreserved:boolean;comparabilityStatus:string;comparabilityReason:string};
  quantity:number|null;itemCost:number|null;quantityCost:number|null;currency:string|null;scopeKind:string;isAlternative:boolean;completePositionPriceEligible:boolean;evidenceCompleteness:number;mappingIds:string[];drawings:ComparisonSourceDrawing[];isBaselineReference?:boolean;positionReference:string;referenceAssessment:{sourceReference:string;matches:string[];differences:string[];missingEvidence:string[];notAssessable:string[];verificationNotes:string[]};priceComparison:{status:string;comparable:boolean;amountDifference:number|null;percentageDifference:number|null;basis:string};annualHeatLoss:{status:string;display:string;deltaKwh:number|null;minimumKwh:number|null;maximumKwh:number|null;equivalentAreaM2?:number;degreeDaysKDaysPerYear?:number};presentationFields:Array<{key:string;label:string;value:string;status:"reference"|"match"|"difference"|"unknown"|"not_applicable";thermal?:ComparisonThermalMetric}>;customerFinding:{summary:string;matches:string|null;differs:string|null;confirm:string|null;confirmation:string|null;recommendation:string;disclosure:string|null};
};
export type QuoteComparisonReport = {
  version:string;generatedFromRecordRevision:number;disclaimer:string;commonScope:string|null;
  context:{comparisonId:string;name:string;description:string|null;status:string;clientId:string;projectId:string|null;projectName:string|null;baselineEstimateId:string;baselineEstimateRef:string;baselineRevision:number};sourceReferences:ComparisonSourceReference[];
  thermalMethodology:{source:string;degreeDaysKDaysPerYear:number;baseTemperatureC:number|null;location:string|null;label:string;formula:string;qualification:string};
  positions:Array<{id:string;reference:string;roomName:string;quantity:number;measurements:string;configuration:string;widthMm:number|null;heightMm:number|null;offers:QuoteComparisonReportOffer[];report:string;conclusion:string;findings:{bestUw:{supplierName:string;value:string;evidence:ComparisonThermalMetric;likeForLike:boolean;qualification:string}|null;bestUg:{supplierName:string;value:string;evidence:ComparisonThermalMetric;likeForLike:boolean;qualification:string}|null;bestG:null;bestLt:null;gValues:Array<{supplierName:string;value:string;evidence:ComparisonThermalMetric}>;ltValues:Array<{supplierName:string;value:string;evidence:ComparisonThermalMetric}>;lowestComparablePrice:{supplierName:string;value:number;currency:string|null}|null};recommendations:Array<{rank:number;supplierName:string;label:string;reason:string}>;recommendationStatus:"ready"|"review_required";recommendationMessage:string|null}>;
  suppliers:Array<{proposalId:string;supplierName:string;manufacturerName:string|null;currency:string|null;scopeKind:string;total:number|null;commercial:ComparisonCommercialBreakdown;matched:number;correct:number;acceptable:number;materialMismatch:number;missing:number;unresolved:number;completeness:number;clarifications:ComparisonClarification[];isBaselineReference?:boolean}>;
  recommendations:Array<{rank:number;supplierName:string;label:string;reason:string}>;
  recommendationStatus:"ready"|"review_required";recommendationMessage:string|null;orderingRules:string[];overallConclusion:string;
  clarifications:Array<{proposalId:string;supplierName:string;items:ComparisonClarification[]}>;
  customerPresentation:{reference:string;scope:string;assessmentPriorities:string[];conclusion:string;suppliers:Array<{proposalId:string;supplierName:string;manufacturerName:string|null;coverage:string;mainPoints:string[];additionalPointCount:number;thermal:{uw:{count:number;minimum:number;maximum:number;display:string}|null;ug:{count:number;minimum:number;maximum:number;display:string}|null;g:{count:number;minimum:number;maximum:number;display:string}|null;lt:{count:number;minimum:number;maximum:number;display:string}|null};commercial:{headlineTotal:number|null;currency:string|null;scopeKind:string;grossSupply:number|null;discountPercentage:number|null;discountAmount:number|null;netSupply:number|null;extras:number|null;extrasLabels:string[];delivery:number|null;installation:number|null;established:boolean;explanation:string}}>;questions:Array<{supplierName:string;question:string;positionReferences:string[];severity:string}>;interpretationNotes:string[]};
};
export function buildQuoteComparisonReport(comparison:unknown):QuoteComparisonReport;
