import {CALCULATOR_CATALOGUE_DEFAULTS,CALCULATION_RULE_DEFAULTS,PACKAGE_RULE_DEFAULTS} from '../features/projectCalculatorLab/calculatorCatalogueDefaults.js';

const tables = [
  `CREATE TABLE IF NOT EXISTS supplier_import_lab_sessions (
    id TEXT PRIMARY KEY,
    estimate_id TEXT,
    supplier_code TEXT,
    supplier_name TEXT NOT NULL CHECK (length(trim(supplier_name)) > 0),
    supplier_quotation_number TEXT,
    supplier_revision TEXT,
    full_quotation_reference TEXT,
    quotation_date TEXT,
    currency TEXT NOT NULL CHECK (length(currency) = 3 AND currency = upper(currency)),
    status TEXT NOT NULL CHECK (status IN ('draft','uploaded','extraction_pending','extracted','failed','archived')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    archived_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_import_lab_attachments (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('original_quote','supporting_document','supplier_drawing')),
    original_file_name TEXT NOT NULL,
    media_type TEXT NOT NULL,
    size_bytes INTEGER NOT NULL CHECK (size_bytes >= 0),
    sha256 TEXT NOT NULL CHECK (length(sha256) = 64 AND sha256 = lower(sha256)),
    storage_key TEXT NOT NULL UNIQUE,
    parser_eligible INTEGER NOT NULL CHECK (parser_eligible IN (0,1)),
    created_at TEXT NOT NULL,
    upload_order INTEGER NOT NULL DEFAULT 0,
      FOREIGN KEY (session_id) REFERENCES supplier_import_lab_sessions(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS supplier_import_lab_extraction_runs (
      id TEXT PRIMARY KEY,
      session_id TEXT NOT NULL,
      attachment_id TEXT NOT NULL,
      extractor_name TEXT NOT NULL,
      extractor_version TEXT NOT NULL,
      field_parser_name TEXT NOT NULL,
      field_parser_version TEXT NOT NULL,
      status TEXT NOT NULL CHECK (status IN ('queued','running','completed','completed_with_warnings','failed','unsupported')),
      started_at TEXT NOT NULL,
      completed_at TEXT,
      warnings_json TEXT NOT NULL DEFAULT '[]',
      error_code TEXT,
      error_message TEXT,
      quotation_number TEXT,
      supplier_revision TEXT,
      full_quotation_reference TEXT,
      quotation_warnings_json TEXT NOT NULL DEFAULT '[]',
      selected INTEGER NOT NULL DEFAULT 0 CHECK (selected IN (0,1)),
      created_at TEXT NOT NULL,
      FOREIGN KEY (session_id) REFERENCES supplier_import_lab_sessions(id) ON DELETE CASCADE,
      FOREIGN KEY (attachment_id) REFERENCES supplier_import_lab_attachments(id) ON DELETE RESTRICT
    )`,
    `CREATE TABLE IF NOT EXISTS supplier_import_lab_extracted_documents (
      extraction_run_id TEXT PRIMARY KEY,
      document_json TEXT NOT NULL,
      FOREIGN KEY (extraction_run_id) REFERENCES supplier_import_lab_extraction_runs(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS supplier_import_lab_extracted_rows (
      id TEXT PRIMARY KEY,
      session_id TEXT NOT NULL,
      extraction_run_id TEXT NOT NULL,
      attachment_id TEXT NOT NULL,
      ordinal INTEGER NOT NULL CHECK (ordinal >= 0),
      display_reference TEXT,
      original_reference_text TEXT,
      supplier_reference_tokens_json TEXT NOT NULL DEFAULT '[]',
      quantity INTEGER,
      width_mm INTEGER,
      height_mm INTEGER,
      original_dimensions_text TEXT,
      unit_price_amount TEXT,
      total_price_amount TEXT,
      currency TEXT NOT NULL,
      source_pages_json TEXT NOT NULL DEFAULT '[]',
      source_trace_json TEXT NOT NULL DEFAULT '[]',
      confidence TEXT,
      warnings_json TEXT NOT NULL DEFAULT '[]',
      status TEXT NOT NULL CHECK (status IN ('extracted','needs_review','corrected','rejected')),
      created_at TEXT NOT NULL,
      corrected_at TEXT,
      corrected_by TEXT,
      review_warnings_json TEXT NOT NULL DEFAULT '[]',
      selected_for_future_use INTEGER NOT NULL DEFAULT 1 CHECK (selected_for_future_use IN (0,1)),
      original_extracted_snapshot_json TEXT NOT NULL,
      FOREIGN KEY (session_id) REFERENCES supplier_import_lab_sessions(id) ON DELETE CASCADE,
      FOREIGN KEY (extraction_run_id) REFERENCES supplier_import_lab_extraction_runs(id) ON DELETE CASCADE,
      FOREIGN KEY (attachment_id) REFERENCES supplier_import_lab_attachments(id) ON DELETE RESTRICT,
      UNIQUE (extraction_run_id, ordinal)
    )`,
  `CREATE TABLE IF NOT EXISTS supplier_import_lab_commercial_summaries (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    extraction_run_id TEXT NOT NULL UNIQUE,
    attachment_id TEXT NOT NULL,
    currency TEXT,
    total_quantity TEXT,
    total_quantity_unit TEXT,
    total_area_square_metres TEXT,
    product_subtotal_amount TEXT,
    additional_items_subtotal_amount TEXT,
    delivery_total_amount TEXT,
    vat_total_amount TEXT,
    final_supplier_total_amount TEXT,
    average_u_value TEXT,
    total_weight_kg TEXT,
    closing_notes TEXT,
    source_trace_json TEXT NOT NULL DEFAULT '[]',
    warnings_json TEXT NOT NULL DEFAULT '[]',
    reconciliation_json TEXT NOT NULL DEFAULT '{}',
    confidence REAL CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1),
    status TEXT NOT NULL CHECK (status IN ('extracted','needs_review','corrected','rejected')),
    original_extracted_snapshot_json TEXT NOT NULL,
    corrected_at TEXT,
    corrected_by TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (session_id) REFERENCES supplier_import_lab_sessions(id) ON DELETE CASCADE,
    FOREIGN KEY (extraction_run_id) REFERENCES supplier_import_lab_extraction_runs(id) ON DELETE CASCADE,
    FOREIGN KEY (attachment_id) REFERENCES supplier_import_lab_attachments(id) ON DELETE RESTRICT
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_import_lab_additional_cost_items (
    id TEXT PRIMARY KEY,
    summary_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    extraction_run_id TEXT NOT NULL,
    ordinal INTEGER NOT NULL CHECK (ordinal >= 0),
    category TEXT NOT NULL CHECK (category IN ('delivery','sill','flashing','trim','accessory','packaging','surcharge','discount','other')),
    original_description TEXT NOT NULL,
    normalized_label TEXT,
    quantity TEXT,
    quantity_unit TEXT,
    unit_price_amount TEXT,
    total_price_amount TEXT,
    currency TEXT,
    source_trace_json TEXT NOT NULL DEFAULT '[]',
    warnings_json TEXT NOT NULL DEFAULT '[]',
    confidence REAL CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1),
    status TEXT NOT NULL CHECK (status IN ('extracted','needs_review','corrected','rejected')),
    selected_for_future_use INTEGER NOT NULL DEFAULT 1 CHECK (selected_for_future_use IN (0,1)),
    original_extracted_snapshot_json TEXT NOT NULL,
    corrected_at TEXT,
    corrected_by TEXT,
    created_at TEXT NOT NULL,
    UNIQUE (extraction_run_id, ordinal),
    FOREIGN KEY (summary_id) REFERENCES supplier_import_lab_commercial_summaries(id) ON DELETE CASCADE,
    FOREIGN KEY (session_id) REFERENCES supplier_import_lab_sessions(id) ON DELETE CASCADE,
    FOREIGN KEY (extraction_run_id) REFERENCES supplier_import_lab_extraction_runs(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_quotes (
    id TEXT PRIMARY KEY,
    estimate_id TEXT NOT NULL,
    supplier_code TEXT NOT NULL,
    supplier_name TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    archived_at TEXT,
    UNIQUE (id, estimate_id),
    FOREIGN KEY (estimate_id) REFERENCES estimates(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_quote_revisions (
    id TEXT PRIMARY KEY,
    supplier_quote_id TEXT NOT NULL,
    estimate_id TEXT NOT NULL,
    revision_sequence INTEGER NOT NULL CHECK (revision_sequence >= 0),
    supplier_quotation_number TEXT NOT NULL,
    supplier_revision TEXT,
    full_quotation_reference TEXT NOT NULL,
    quotation_date TEXT,
    customer_reference TEXT,
    currency TEXT NOT NULL CHECK (length(currency) = 3 AND currency = upper(currency)),
    vat_status TEXT NOT NULL,
    product_subtotal_amount TEXT,
    extras_total_amount TEXT,
    delivery_total_amount TEXT,
    vat_total_amount TEXT,
    final_supplier_total_amount TEXT,
    lifecycle_status TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    superseded_at TEXT,
    superseded_by_revision_id TEXT,
    UNIQUE (supplier_quote_id, revision_sequence),
    UNIQUE (id, estimate_id),
    CHECK ((lifecycle_status = 'superseded' AND superseded_at IS NOT NULL AND superseded_by_revision_id IS NOT NULL) OR (lifecycle_status <> 'superseded' AND superseded_at IS NULL AND superseded_by_revision_id IS NULL)),
    FOREIGN KEY (supplier_quote_id, estimate_id) REFERENCES supplier_quotes(id, estimate_id) ON DELETE CASCADE,
    FOREIGN KEY (superseded_by_revision_id, estimate_id) REFERENCES supplier_quote_revisions(id, estimate_id)
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_quote_attachments (
    id TEXT PRIMARY KEY,
    estimate_id TEXT NOT NULL,
    revision_id TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('original_quote','supplier_drawing','supporting_document','derived_artifact')),
    original_file_name TEXT NOT NULL,
    media_type TEXT NOT NULL,
    size_bytes INTEGER NOT NULL CHECK (size_bytes >= 0),
    sha256 TEXT NOT NULL CHECK (length(sha256) = 64 AND sha256 = lower(sha256)),
    storage_key TEXT NOT NULL UNIQUE,
    parser_eligible INTEGER NOT NULL CHECK (parser_eligible IN (0,1)),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    derived_from_attachment_id TEXT,
    artifact_type TEXT,
    extractor_version TEXT,
    document_kind TEXT NOT NULL DEFAULT 'complete_quotation',
    uploaded_by TEXT NOT NULL DEFAULT 'local-admin',
    upload_order INTEGER NOT NULL DEFAULT 0,
    UNIQUE (id, estimate_id),
    CHECK ((role = 'derived_artifact' AND derived_from_attachment_id IS NOT NULL AND artifact_type IS NOT NULL) OR (role <> 'derived_artifact' AND artifact_type IS NULL)),
    FOREIGN KEY (revision_id, estimate_id) REFERENCES supplier_quote_revisions(id, estimate_id) ON DELETE CASCADE,
    FOREIGN KEY (derived_from_attachment_id, estimate_id) REFERENCES supplier_quote_attachments(id, estimate_id)
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_quote_import_runs (
    id TEXT PRIMARY KEY,
    estimate_id TEXT NOT NULL,
    revision_id TEXT NOT NULL,
    extractor_name TEXT NOT NULL,
    extractor_version TEXT NOT NULL,
    adapter_code TEXT NOT NULL,
    adapter_version TEXT NOT NULL,
    recognition_version TEXT NOT NULL,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    status TEXT NOT NULL,
    warnings_json TEXT NOT NULL DEFAULT '[]',
    error_code TEXT,
    error_message TEXT,
    raw_result_attachment_id TEXT,
    UNIQUE (id, estimate_id),
    CHECK ((status IN ('completed','completed_with_warnings','failed','cancelled') AND completed_at IS NOT NULL) OR (status IN ('queued','running') AND completed_at IS NULL)),
    CHECK (status <> 'failed' OR error_code IS NOT NULL OR error_message IS NOT NULL),
    FOREIGN KEY (revision_id, estimate_id) REFERENCES supplier_quote_revisions(id, estimate_id) ON DELETE CASCADE,
    FOREIGN KEY (raw_result_attachment_id, estimate_id) REFERENCES supplier_quote_attachments(id, estimate_id)
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_quote_import_run_attachments (
    import_run_id TEXT NOT NULL,
    attachment_id TEXT NOT NULL,
    ordinal INTEGER NOT NULL CHECK (ordinal >= 0),
    role TEXT NOT NULL,
    PRIMARY KEY (import_run_id, attachment_id),
    UNIQUE (import_run_id, ordinal),
    FOREIGN KEY (import_run_id) REFERENCES supplier_quote_import_runs(id) ON DELETE CASCADE,
    FOREIGN KEY (attachment_id) REFERENCES supplier_quote_attachments(id)
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_quote_positions (
    id TEXT PRIMARY KEY,
    estimate_id TEXT NOT NULL,
    revision_id TEXT NOT NULL,
    display_reference TEXT NOT NULL CHECK (length(trim(display_reference)) > 0),
    supplier_reference_tokens_json TEXT NOT NULL DEFAULT '[]',
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    product TEXT,
    product_system TEXT,
    original_specification_text TEXT NOT NULL DEFAULT '',
    width_mm INTEGER,
    height_mm INTEGER,
    supplier_area_square_metres TEXT,
    calculated_area_square_metres TEXT,
    unit_purchase_price_amount TEXT,
    total_purchase_price_amount TEXT,
    currency TEXT,
    supplier_drawing_attachment_id TEXT,
    opening_direction TEXT,
    view_direction TEXT NOT NULL DEFAULT 'unknown',
    proposed_window_type_id TEXT,
    proposed_proof_family_id TEXT,
    recognition_confidence REAL CHECK (recognition_confidence IS NULL OR recognition_confidence BETWEEN 0 AND 1),
    recognition_reasons_json TEXT NOT NULL DEFAULT '[]',
    source_pages_json TEXT NOT NULL DEFAULT '[]',
    trace_json TEXT NOT NULL DEFAULT '[]',
    review_status TEXT NOT NULL DEFAULT 'unreviewed',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (id, estimate_id),
    FOREIGN KEY (revision_id, estimate_id) REFERENCES supplier_quote_revisions(id, estimate_id) ON DELETE CASCADE,
    FOREIGN KEY (supplier_drawing_attachment_id, estimate_id) REFERENCES supplier_quote_attachments(id, estimate_id)
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_specification_items (
    id TEXT PRIMARY KEY,
    supplier_position_id TEXT NOT NULL,
    ordinal INTEGER NOT NULL CHECK (ordinal >= 0),
    supplied_number TEXT,
    original_text TEXT NOT NULL CHECK (length(original_text) > 0),
    normalized_label TEXT,
    normalized_value TEXT,
    trace_json TEXT NOT NULL DEFAULT '[]',
    UNIQUE (supplier_position_id, ordinal),
    FOREIGN KEY (supplier_position_id) REFERENCES supplier_quote_positions(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_quote_extras (
    id TEXT PRIMARY KEY,
    estimate_id TEXT NOT NULL,
    revision_id TEXT NOT NULL,
    category TEXT NOT NULL,
    label TEXT NOT NULL,
    original_text TEXT NOT NULL,
    quantity TEXT,
    unit_price_amount TEXT,
    total_price_amount TEXT,
    currency TEXT NOT NULL,
    trace_json TEXT NOT NULL DEFAULT '[]',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (revision_id, estimate_id) REFERENCES supplier_quote_revisions(id, estimate_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_position_match_proposals (
    proposal_key TEXT PRIMARY KEY,
    estimate_id TEXT NOT NULL,
    supplier_position_id TEXT NOT NULL,
    proposed_window_type_id TEXT,
    proposed_proof_family_id TEXT,
    score REAL NOT NULL,
    confidence REAL NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    reasons_json TEXT NOT NULL DEFAULT '[]',
    normalized_evidence_json TEXT NOT NULL,
    recognition_version TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    supported_by_production_manifest INTEGER NOT NULL CHECK (supported_by_production_manifest IN (0,1)),
    blocking_issues_json TEXT NOT NULL DEFAULT '[]',
    rank INTEGER NOT NULL CHECK (rank >= 0),
    UNIQUE (supplier_position_id, rank),
    FOREIGN KEY (supplier_position_id, estimate_id) REFERENCES supplier_quote_positions(id, estimate_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_quote_review_decisions (
    id TEXT PRIMARY KEY,
    estimate_id TEXT NOT NULL,
    supplier_position_id TEXT NOT NULL,
    import_run_id TEXT NOT NULL,
    review_version TEXT NOT NULL,
    decision TEXT NOT NULL CHECK (decision IN ('accepted','corrected','rejected','deferred')),
    selected_proposal_key TEXT,
    proposed_configuration_snapshot_json TEXT NOT NULL,
    approved_configuration_snapshot_json TEXT,
    resulting_position_id TEXT,
    resulting_contract_schema_version INTEGER,
    reviewer_id TEXT NOT NULL,
    reviewed_at TEXT NOT NULL,
    note TEXT,
    CHECK (decision NOT IN ('rejected','deferred') OR (resulting_position_id IS NULL AND resulting_contract_schema_version IS NULL)),
    FOREIGN KEY (supplier_position_id, estimate_id) REFERENCES supplier_quote_positions(id, estimate_id) ON DELETE CASCADE,
    FOREIGN KEY (import_run_id, estimate_id) REFERENCES supplier_quote_import_runs(id, estimate_id),
    FOREIGN KEY (selected_proposal_key) REFERENCES supplier_position_match_proposals(proposal_key)
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_position_applications (
    id TEXT PRIMARY KEY,
    estimate_id TEXT NOT NULL,
    supplier_quote_id TEXT NOT NULL,
    supplier_quote_revision_id TEXT NOT NULL,
    supplier_quote_position_id TEXT NOT NULL,
    action TEXT NOT NULL CHECK (action IN ('include_as_new_position','map_to_existing_position','replace_existing_position','exclude','comparison_only','deferred')),
    target_estimate_position_id TEXT,
    applied_at TEXT NOT NULL,
    applied_by TEXT NOT NULL,
    active INTEGER NOT NULL CHECK (active IN (0,1)),
    superseded_by_application_id TEXT,
    note TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (id, estimate_id),
    CHECK (action NOT IN ('exclude','comparison_only','deferred') OR target_estimate_position_id IS NULL),
    FOREIGN KEY (supplier_quote_id, estimate_id) REFERENCES supplier_quotes(id, estimate_id) ON DELETE CASCADE,
    FOREIGN KEY (supplier_quote_revision_id, estimate_id) REFERENCES supplier_quote_revisions(id, estimate_id) ON DELETE CASCADE,
    FOREIGN KEY (supplier_quote_position_id, estimate_id) REFERENCES supplier_quote_positions(id, estimate_id) ON DELETE CASCADE,
    FOREIGN KEY (superseded_by_application_id, estimate_id) REFERENCES supplier_position_applications(id, estimate_id)
  )`,
  `CREATE TABLE IF NOT EXISTS project_calculators (
    id TEXT PRIMARY KEY,
    estimate_id TEXT NOT NULL,
    base_currency TEXT NOT NULL,
    active_scenario_id TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    archived_at TEXT,
    UNIQUE (id, estimate_id),
    FOREIGN KEY (estimate_id) REFERENCES estimates(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS project_cost_items (
    id TEXT PRIMARY KEY,
    calculator_id TEXT NOT NULL,
    estimate_id TEXT NOT NULL,
    category TEXT NOT NULL,
    label TEXT NOT NULL,
    quantity TEXT NOT NULL,
    unit_cost_amount TEXT NOT NULL,
    unit_cost_currency TEXT NOT NULL,
    total_cost_amount TEXT NOT NULL,
    total_cost_currency TEXT NOT NULL,
    source TEXT NOT NULL,
    included INTEGER NOT NULL CHECK (included IN (0,1)),
    supplier_quote_revision_id TEXT,
    supplier_position_id TEXT,
    manually_overridden INTEGER NOT NULL CHECK (manually_overridden IN (0,1)),
    source_value_snapshot_json TEXT,
    exchange_rate TEXT,
    exchange_rate_date TEXT,
    exchange_rate_source TEXT,
    converted_total_amount TEXT,
    converted_currency TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (calculator_id, estimate_id) REFERENCES project_calculators(id, estimate_id) ON DELETE CASCADE,
    FOREIGN KEY (supplier_quote_revision_id, estimate_id) REFERENCES supplier_quote_revisions(id, estimate_id),
    FOREIGN KEY (supplier_position_id, estimate_id) REFERENCES supplier_quote_positions(id, estimate_id)
  )`,
  `CREATE TABLE IF NOT EXISTS pricing_scenarios (
    id TEXT PRIMARY KEY,
    calculator_id TEXT NOT NULL,
    estimate_id TEXT NOT NULL,
    name TEXT NOT NULL,
    status TEXT NOT NULL,
    markup_percent TEXT,
    target_margin_percent TEXT,
    net_cost_amount TEXT NOT NULL,
    currency TEXT NOT NULL,
    contingency_amount TEXT NOT NULL,
    gross_profit_amount TEXT NOT NULL,
    margin_percent TEXT NOT NULL,
    vat_status TEXT NOT NULL,
    vat_rate_percent TEXT NOT NULL,
    vat_amount TEXT NOT NULL,
    selling_price_ex_vat TEXT NOT NULL,
    selling_price_inc_vat TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (id, estimate_id),
    FOREIGN KEY (calculator_id, estimate_id) REFERENCES project_calculators(id, estimate_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS calculator_snapshots (
    id TEXT PRIMARY KEY,
    calculator_id TEXT NOT NULL,
    estimate_id TEXT NOT NULL,
    scenario_id TEXT NOT NULL,
    snapshot_version TEXT NOT NULL,
    calculation_inputs_json TEXT NOT NULL,
    calculation_outputs_json TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by TEXT NOT NULL,
    FOREIGN KEY (calculator_id, estimate_id) REFERENCES project_calculators(id, estimate_id) ON DELETE CASCADE,
    FOREIGN KEY (scenario_id, estimate_id) REFERENCES pricing_scenarios(id, estimate_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS project_calculator_lab_scenarios (
    id TEXT PRIMARY KEY,
    estimate_id TEXT,
    name TEXT NOT NULL CHECK (length(trim(name)) > 0),
    currency TEXT NOT NULL CHECK (length(currency) = 3 AND currency = upper(currency)),
    package_code TEXT NOT NULL CHECK (package_code IN ('supply_only','support','full_installation')),
    origin TEXT NOT NULL DEFAULT 'supplier_import' CHECK (origin IN ('supplier_import','estimate','manual','mixed')),
    import_lab_session_id TEXT,
    extraction_run_id TEXT,
    source_attachment_id TEXT,
    source_revision TEXT,
    revision_number INTEGER NOT NULL DEFAULT 1,
    installation_opening_count INTEGER NOT NULL DEFAULT 0 CHECK (installation_opening_count >= 0),
    target_gross_margin_percent TEXT,
    commercial_margin_policy_json TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (import_lab_session_id) REFERENCES supplier_import_lab_sessions(id),
    FOREIGN KEY (extraction_run_id) REFERENCES supplier_import_lab_extraction_runs(id),
    FOREIGN KEY (source_attachment_id) REFERENCES supplier_import_lab_attachments(id)
  )`,
  `CREATE TABLE IF NOT EXISTS estimate_commercial_settings (
    estimate_id TEXT PRIMARY KEY,
    pricing_source TEXT CHECK (pricing_source IN ('quotesync_generated','supplier_quotation_import')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (estimate_id) REFERENCES estimates(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS project_calculator_lab_product_rows (
    id TEXT PRIMARY KEY,
    scenario_id TEXT NOT NULL,
    source_row_id TEXT NOT NULL,
    source_snapshot_json TEXT NOT NULL,
    display_reference TEXT NOT NULL,
    product_class TEXT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    width_mm INTEGER NOT NULL CHECK (width_mm > 0),
    height_mm INTEGER NOT NULL CHECK (height_mm > 0),
    total_price_amount TEXT,
    currency TEXT NOT NULL,
    area_square_metres TEXT NOT NULL,
    frame_perimeter_metres TEXT NOT NULL,
    markup_override_percent TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (scenario_id, source_row_id),
    FOREIGN KEY (scenario_id) REFERENCES project_calculator_lab_scenarios(id) ON DELETE CASCADE,
    FOREIGN KEY (source_row_id) REFERENCES supplier_import_lab_extracted_rows(id)
  )`,
  `CREATE TABLE IF NOT EXISTS project_calculator_lab_supplier_costs (
    id TEXT PRIMARY KEY,
    scenario_id TEXT NOT NULL,
    source_additional_cost_id TEXT NOT NULL,
    source_snapshot_json TEXT NOT NULL,
    category TEXT NOT NULL,
    label TEXT NOT NULL,
    amount TEXT,
    currency TEXT,
    created_at TEXT NOT NULL,
    UNIQUE (scenario_id, source_additional_cost_id),
    FOREIGN KEY (scenario_id) REFERENCES project_calculator_lab_scenarios(id) ON DELETE CASCADE,
    FOREIGN KEY (source_additional_cost_id) REFERENCES supplier_import_lab_additional_cost_items(id)
  )`,
  `CREATE TABLE IF NOT EXISTS project_calculator_estimate_product_rows (
    id TEXT PRIMARY KEY,
    scenario_id TEXT NOT NULL,
    source_position_id TEXT NOT NULL,
    source_attachment_id TEXT NOT NULL,
    source_revision_id TEXT NOT NULL,
    source_snapshot_json TEXT NOT NULL,
    display_reference TEXT NOT NULL,
    product_class TEXT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    width_mm INTEGER NOT NULL CHECK (width_mm > 0),
    height_mm INTEGER NOT NULL CHECK (height_mm > 0),
    total_price_amount TEXT,
    currency TEXT NOT NULL,
    area_square_metres TEXT NOT NULL,
    frame_perimeter_metres TEXT NOT NULL,
    markup_override_percent TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (scenario_id, source_position_id),
    FOREIGN KEY (scenario_id) REFERENCES project_calculator_lab_scenarios(id) ON DELETE CASCADE,
    FOREIGN KEY (source_position_id) REFERENCES supplier_quote_positions(id),
    FOREIGN KEY (source_attachment_id) REFERENCES supplier_quote_attachments(id),
    FOREIGN KEY (source_revision_id) REFERENCES supplier_quote_revisions(id)
  )`,
  `CREATE TABLE IF NOT EXISTS project_calculator_estimate_supplier_costs (
    id TEXT PRIMARY KEY,
    scenario_id TEXT NOT NULL,
    source_extra_id TEXT NOT NULL,
    source_attachment_id TEXT NOT NULL,
    source_revision_id TEXT NOT NULL,
    source_snapshot_json TEXT NOT NULL,
    category TEXT NOT NULL,
    label TEXT NOT NULL,
    amount TEXT,
    currency TEXT,
    created_at TEXT NOT NULL,
    UNIQUE (scenario_id, source_extra_id),
    FOREIGN KEY (scenario_id) REFERENCES project_calculator_lab_scenarios(id) ON DELETE CASCADE,
    FOREIGN KEY (source_extra_id) REFERENCES supplier_quote_extras(id),
    FOREIGN KEY (source_attachment_id) REFERENCES supplier_quote_attachments(id),
    FOREIGN KEY (source_revision_id) REFERENCES supplier_quote_revisions(id)
  )`,
  `CREATE TABLE IF NOT EXISTS project_calculator_supplier_quote_revisions (
    scenario_id TEXT NOT NULL,
    supplier_quote_id TEXT NOT NULL,
    revision_id TEXT NOT NULL,
    import_run_id TEXT NOT NULL,
    fx_snapshot_id TEXT,
    currency TEXT NOT NULL,
    linked_at TEXT NOT NULL,
    PRIMARY KEY (scenario_id, revision_id),
    FOREIGN KEY (scenario_id) REFERENCES project_calculator_lab_scenarios(id) ON DELETE CASCADE,
    FOREIGN KEY (supplier_quote_id) REFERENCES supplier_quotes(id),
    FOREIGN KEY (revision_id) REFERENCES supplier_quote_revisions(id),
    FOREIGN KEY (import_run_id) REFERENCES supplier_quote_import_runs(id),
    FOREIGN KEY (fx_snapshot_id) REFERENCES project_calculator_supplier_fx_snapshots(id)
  )`,
  `CREATE TABLE IF NOT EXISTS project_calculator_supplier_fx_snapshots (
    id TEXT PRIMARY KEY,
    scenario_id TEXT NOT NULL,
    supplier_quote_revision_id TEXT NOT NULL,
    import_run_id TEXT NOT NULL,
    scenario_revision INTEGER NOT NULL,
    supplier_currency TEXT NOT NULL,
    target_currency TEXT NOT NULL DEFAULT 'GBP',
    provider TEXT NOT NULL,
    provider_timestamp TEXT NOT NULL,
    supplier_to_gbp_live_rate TEXT NOT NULL,
    rounded_up_rate TEXT NOT NULL,
    uplift_amount TEXT NOT NULL,
    calculated_selling_rate TEXT NOT NULL,
    supplier_to_gbp_selling_rate TEXT NOT NULL,
    adjustment_enabled INTEGER NOT NULL CHECK (adjustment_enabled IN (0,1)),
    manually_overridden INTEGER NOT NULL DEFAULT 0 CHECK (manually_overridden IN (0,1)),
    override_reason TEXT,
    overridden_at TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (scenario_id) REFERENCES project_calculator_lab_scenarios(id) ON DELETE CASCADE,
    FOREIGN KEY (supplier_quote_revision_id) REFERENCES supplier_quote_revisions(id),
    FOREIGN KEY (import_run_id) REFERENCES supplier_quote_import_runs(id)
  )`,
  `CREATE TABLE IF NOT EXISTS project_calculator_lab_package_items (
    id TEXT PRIMARY KEY,
    scenario_id TEXT NOT NULL,
    package_code TEXT NOT NULL,
    catalogue_code TEXT NOT NULL,
    label TEXT NOT NULL,
    included INTEGER NOT NULL CHECK (included IN (0,1)),
    unit_cost_amount TEXT,
    currency TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (scenario_id) REFERENCES project_calculator_lab_scenarios(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS project_calculator_lab_route_snapshots (
    id TEXT PRIMARY KEY,
    scenario_id TEXT NOT NULL,
    direction TEXT NOT NULL CHECK (direction IN ('office_to_site','site_to_office')),
    origin_label TEXT NOT NULL,
    destination_label TEXT NOT NULL,
    origin_lat TEXT NOT NULL,
    origin_lng TEXT NOT NULL,
    destination_lat TEXT NOT NULL,
    destination_lng TEXT NOT NULL,
    distance_km TEXT,
    duration_minutes INTEGER,
    traffic_duration_minutes INTEGER,
    calculated_at TEXT NOT NULL,
    integration TEXT NOT NULL,
    manually_overridden INTEGER NOT NULL CHECK (manually_overridden IN (0,1)),
    override_reason TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (scenario_id) REFERENCES project_calculator_lab_scenarios(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS project_calculator_lab_manual_product_rows (
    id TEXT PRIMARY KEY,
    scenario_id TEXT NOT NULL,
    reference TEXT NOT NULL,
    product_class TEXT NOT NULL,
    width_mm INTEGER NOT NULL CHECK (width_mm > 0),
    height_mm INTEGER NOT NULL CHECK (height_mm > 0),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    installation_opening_count INTEGER NOT NULL CHECK (installation_opening_count >= 0),
    unit_supply_cost_amount TEXT,
    total_supply_cost_amount TEXT,
    currency TEXT NOT NULL,
    evidence_origin TEXT NOT NULL DEFAULT 'manual' CHECK (evidence_origin = 'manual'),
    markup_override_percent TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (scenario_id) REFERENCES project_calculator_lab_scenarios(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS project_calculator_lab_manual_cost_lines (
    id TEXT PRIMARY KEY,
    scenario_id TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('discount','extras','delivery','survey','materials','labour','plant','travel','accommodation','admin','other')),
    label TEXT NOT NULL,
    amount TEXT NOT NULL,
    currency TEXT NOT NULL,
    evidence_origin TEXT NOT NULL DEFAULT 'manual' CHECK (evidence_origin = 'manual'),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (scenario_id) REFERENCES project_calculator_lab_scenarios(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS project_calculator_lab_exchange_rate_snapshots (
    id TEXT PRIMARY KEY,
    scenario_id TEXT NOT NULL,
    scenario_revision INTEGER NOT NULL,
    from_currency TEXT NOT NULL,
    to_currency TEXT NOT NULL DEFAULT 'GBP',
    provider TEXT NOT NULL,
    provider_timestamp TEXT NOT NULL,
    raw_rate TEXT NOT NULL,
    inverse_rate TEXT,
    rounded_up_rate TEXT NOT NULL,
    uplift_amount TEXT NOT NULL,
    calculated_adjusted_rate TEXT NOT NULL,
    adjusted_rate TEXT NOT NULL,
    adjustment_enabled INTEGER NOT NULL CHECK (adjustment_enabled IN (0,1)),
    manually_overridden INTEGER NOT NULL DEFAULT 0 CHECK (manually_overridden IN (0,1)),
    override_reason TEXT,
    overridden_at TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (scenario_id) REFERENCES project_calculator_lab_scenarios(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS project_calculator_lab_markup_rules (
    scenario_id TEXT PRIMARY KEY,
    product_percent TEXT NOT NULL DEFAULT '0',
    extras_percent TEXT NOT NULL DEFAULT '0',
    transport_percent TEXT NOT NULL DEFAULT '0',
    equipment_percent TEXT NOT NULL DEFAULT '0',
    installation_percent TEXT NOT NULL DEFAULT '0',
    materials_percent TEXT NOT NULL DEFAULT '0',
    duties_percent TEXT NOT NULL DEFAULT '0',
    updated_at TEXT NOT NULL,
    FOREIGN KEY (scenario_id) REFERENCES project_calculator_lab_scenarios(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS project_calculator_lab_revisions (
    id TEXT PRIMARY KEY,
    scenario_id TEXT NOT NULL,
    version_number INTEGER NOT NULL,
    reason TEXT NOT NULL,
    snapshot_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    UNIQUE (scenario_id, version_number),
    FOREIGN KEY (scenario_id) REFERENCES project_calculator_lab_scenarios(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS project_calculator_admin_catalogue_items (
    id TEXT PRIMARY KEY, category TEXT NOT NULL, label TEXT NOT NULL, rate_type TEXT NOT NULL,
    price_amount TEXT, currency TEXT NOT NULL DEFAULT 'GBP', variant_json TEXT NOT NULL DEFAULT '{}',
    supplier TEXT, notes TEXT, active INTEGER NOT NULL DEFAULT 1 CHECK(active IN(0,1)), version INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL, updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS project_calculator_admin_rules (
    rule_key TEXT PRIMARY KEY, rule_value_json TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1, updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS project_calculator_admin_package_rules (
    package_code TEXT PRIMARY KEY CHECK(package_code IN('supply_only','support','full_installation')),
    inclusions_json TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1, updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS project_calculator_lab_catalogue_snapshots (
    id TEXT PRIMARY KEY, scenario_id TEXT NOT NULL, scenario_revision INTEGER NOT NULL,
    catalogue_json TEXT NOT NULL, rules_json TEXT NOT NULL, package_rules_json TEXT NOT NULL, created_at TEXT NOT NULL,
    FOREIGN KEY(scenario_id) REFERENCES project_calculator_lab_scenarios(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS project_calculator_lab_options (
    scenario_id TEXT PRIMARY KEY, project_type TEXT NOT NULL DEFAULT 'new_build', crew_size INTEGER NOT NULL DEFAULT 2,
    use_illbruck INTEGER NOT NULL DEFAULT 0, brackets_required INTEGER NOT NULL DEFAULT 0, stay_away INTEGER NOT NULL DEFAULT 0,
    transport_customer_amount TEXT, transport_allocate_difference INTEGER NOT NULL DEFAULT 0,
    transport_allocation_method TEXT NOT NULL DEFAULT 'proportional_value', options_json TEXT NOT NULL DEFAULT '{}', updated_at TEXT NOT NULL,
    FOREIGN KEY(scenario_id) REFERENCES project_calculator_lab_scenarios(id) ON DELETE CASCADE
  )`,
];

const indexes = [
  'CREATE INDEX IF NOT EXISTS idx_supplier_import_lab_sessions_status ON supplier_import_lab_sessions(status)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_import_lab_sessions_created ON supplier_import_lab_sessions(created_at)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_import_lab_sessions_archive ON supplier_import_lab_sessions(archived_at)',
    'CREATE INDEX IF NOT EXISTS idx_supplier_import_lab_attachments_session ON supplier_import_lab_attachments(session_id, created_at)',
    'CREATE INDEX IF NOT EXISTS idx_supplier_import_lab_runs_session ON supplier_import_lab_extraction_runs(session_id, created_at)',
    'CREATE INDEX IF NOT EXISTS idx_supplier_import_lab_runs_attachment ON supplier_import_lab_extraction_runs(session_id, attachment_id, status)',
    'CREATE UNIQUE INDEX IF NOT EXISTS idx_supplier_import_lab_one_selected_run ON supplier_import_lab_extraction_runs(session_id) WHERE selected = 1',
    'CREATE INDEX IF NOT EXISTS idx_supplier_import_lab_rows_run ON supplier_import_lab_extracted_rows(session_id, extraction_run_id, ordinal)',
    'CREATE INDEX IF NOT EXISTS idx_supplier_import_lab_summary_session ON supplier_import_lab_commercial_summaries(session_id, extraction_run_id)',
    'CREATE INDEX IF NOT EXISTS idx_supplier_import_lab_costs_summary ON supplier_import_lab_additional_cost_items(summary_id, ordinal)',
    'CREATE INDEX IF NOT EXISTS idx_supplier_import_lab_costs_run ON supplier_import_lab_additional_cost_items(session_id, extraction_run_id, ordinal)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_quotes_estimate ON supplier_quotes(estimate_id, archived_at)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_revisions_quote ON supplier_quote_revisions(estimate_id, supplier_quote_id, revision_sequence)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_revisions_lifecycle ON supplier_quote_revisions(estimate_id, lifecycle_status)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_attachments_revision ON supplier_quote_attachments(estimate_id, revision_id)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_import_runs_revision ON supplier_quote_import_runs(estimate_id, revision_id, started_at)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_positions_revision ON supplier_quote_positions(estimate_id, revision_id)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_extras_revision ON supplier_quote_extras(estimate_id, revision_id)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_proposals_position ON supplier_position_match_proposals(estimate_id, supplier_position_id, rank)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_reviews_position ON supplier_quote_review_decisions(estimate_id, supplier_position_id, reviewed_at)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_applications_position ON supplier_position_applications(estimate_id, supplier_quote_position_id, created_at)',
  'CREATE UNIQUE INDEX IF NOT EXISTS idx_supplier_applications_one_active ON supplier_position_applications(estimate_id, supplier_quote_position_id) WHERE active = 1',
  'CREATE INDEX IF NOT EXISTS idx_project_calculators_estimate ON project_calculators(estimate_id, archived_at)',
  'CREATE UNIQUE INDEX IF NOT EXISTS idx_project_calculators_one_active ON project_calculators(estimate_id) WHERE archived_at IS NULL',
  'CREATE INDEX IF NOT EXISTS idx_project_cost_items_calculator ON project_cost_items(estimate_id, calculator_id)',
  'CREATE INDEX IF NOT EXISTS idx_project_cost_items_supplier_source ON project_cost_items(estimate_id, supplier_quote_revision_id, supplier_position_id)',
  'CREATE INDEX IF NOT EXISTS idx_pricing_scenarios_calculator ON pricing_scenarios(estimate_id, calculator_id, status)',
  'CREATE INDEX IF NOT EXISTS idx_calculator_snapshots_scenario ON calculator_snapshots(estimate_id, scenario_id, created_at)',
  'CREATE INDEX IF NOT EXISTS idx_calculator_lab_scenarios_run ON project_calculator_lab_scenarios(import_lab_session_id, extraction_run_id)',
  'CREATE INDEX IF NOT EXISTS idx_calculator_lab_rows_scenario ON project_calculator_lab_product_rows(scenario_id)',
  'CREATE INDEX IF NOT EXISTS idx_calculator_lab_costs_scenario ON project_calculator_lab_supplier_costs(scenario_id)',
  'CREATE INDEX IF NOT EXISTS idx_calculator_estimate_rows_scenario ON project_calculator_estimate_product_rows(scenario_id, source_attachment_id)',
  'CREATE INDEX IF NOT EXISTS idx_calculator_estimate_costs_scenario ON project_calculator_estimate_supplier_costs(scenario_id, source_attachment_id)',
  'CREATE INDEX IF NOT EXISTS idx_calculator_quote_revisions_scenario ON project_calculator_supplier_quote_revisions(scenario_id, linked_at)',
  'CREATE INDEX IF NOT EXISTS idx_calculator_supplier_fx_scenario ON project_calculator_supplier_fx_snapshots(scenario_id, supplier_quote_revision_id, created_at)',
  'CREATE INDEX IF NOT EXISTS idx_calculator_lab_package_scenario ON project_calculator_lab_package_items(scenario_id, package_code)',
  'CREATE INDEX IF NOT EXISTS idx_calculator_lab_routes_scenario ON project_calculator_lab_route_snapshots(scenario_id, direction, calculated_at)',
  'CREATE INDEX IF NOT EXISTS idx_calculator_lab_manual_rows_scenario ON project_calculator_lab_manual_product_rows(scenario_id, created_at)',
  'CREATE INDEX IF NOT EXISTS idx_calculator_lab_manual_costs_scenario ON project_calculator_lab_manual_cost_lines(scenario_id, created_at)',
  'CREATE INDEX IF NOT EXISTS idx_calculator_lab_fx_scenario ON project_calculator_lab_exchange_rate_snapshots(scenario_id, created_at)',
  'CREATE INDEX IF NOT EXISTS idx_calculator_lab_revisions_scenario ON project_calculator_lab_revisions(scenario_id, version_number)',
  'CREATE INDEX IF NOT EXISTS idx_calculator_admin_catalogue_category ON project_calculator_admin_catalogue_items(category, active)',
  'CREATE INDEX IF NOT EXISTS idx_calculator_lab_catalogue_snapshot ON project_calculator_lab_catalogue_snapshots(scenario_id, scenario_revision)',
];

export async function initializeSupplierCommercialSchema(db) {
  await db.exec('PRAGMA foreign_keys = ON');
  for (const statement of tables) await db.exec(statement);
  const calculatorScenarioColumns = await db.all('PRAGMA table_info(project_calculator_lab_scenarios)');
  const legacyRequiredSource = calculatorScenarioColumns.some((column) => column.name === 'import_lab_session_id' && column.notnull === 1);
  if (legacyRequiredSource) {
    await db.exec('PRAGMA foreign_keys = OFF');
    try {
      await db.exec(`BEGIN IMMEDIATE;
        CREATE TABLE project_calculator_lab_scenarios_new (
          id TEXT PRIMARY KEY,
          name TEXT NOT NULL CHECK (length(trim(name)) > 0),
          currency TEXT NOT NULL CHECK (length(currency) = 3 AND currency = upper(currency)),
          package_code TEXT NOT NULL CHECK (package_code IN ('supply_only','support','full_installation')),
          origin TEXT NOT NULL DEFAULT 'supplier_import' CHECK (origin IN ('supplier_import','estimate','manual','mixed')),
          import_lab_session_id TEXT,
          extraction_run_id TEXT,
          source_attachment_id TEXT,
          source_revision TEXT,
          revision_number INTEGER NOT NULL DEFAULT 1,
          installation_opening_count INTEGER NOT NULL DEFAULT 0 CHECK (installation_opening_count >= 0),
          created_at TEXT NOT NULL,
          updated_at TEXT NOT NULL,
          FOREIGN KEY (import_lab_session_id) REFERENCES supplier_import_lab_sessions(id),
          FOREIGN KEY (extraction_run_id) REFERENCES supplier_import_lab_extraction_runs(id),
          FOREIGN KEY (source_attachment_id) REFERENCES supplier_import_lab_attachments(id)
        );
        INSERT INTO project_calculator_lab_scenarios_new(id,name,currency,package_code,origin,import_lab_session_id,extraction_run_id,source_attachment_id,source_revision,revision_number,installation_opening_count,created_at,updated_at)
          SELECT id,name,currency,package_code,'supplier_import',import_lab_session_id,extraction_run_id,source_attachment_id,NULL,1,installation_opening_count,created_at,updated_at FROM project_calculator_lab_scenarios;
        DROP TABLE project_calculator_lab_scenarios;
        ALTER TABLE project_calculator_lab_scenarios_new RENAME TO project_calculator_lab_scenarios;
        COMMIT;`);
    } catch (error) {
      await db.exec('ROLLBACK').catch(() => {});
      throw error;
    } finally {
      await db.exec('PRAGMA foreign_keys = ON');
    }
  }
  if (!legacyRequiredSource && !calculatorScenarioColumns.some((column) => column.name === 'source_revision')) await db.exec('ALTER TABLE project_calculator_lab_scenarios ADD COLUMN source_revision TEXT');
  if (!legacyRequiredSource && !calculatorScenarioColumns.some((column) => column.name === 'revision_number')) await db.exec('ALTER TABLE project_calculator_lab_scenarios ADD COLUMN revision_number INTEGER NOT NULL DEFAULT 1');
  const calculatorMarkupColumns = await db.all('PRAGMA table_info(project_calculator_lab_markup_rules)');
  for (const column of ['equipment_percent','materials_percent','duties_percent']) if (!calculatorMarkupColumns.some((item) => item.name === column)) await db.exec(`ALTER TABLE project_calculator_lab_markup_rules ADD COLUMN ${column} TEXT NOT NULL DEFAULT '0'`);
  for (const table of ['project_calculator_lab_product_rows','project_calculator_lab_manual_product_rows']) {
    const columns = await db.all(`PRAGMA table_info(${table})`);
    if (!columns.some((column) => column.name === 'markup_override_percent')) await db.exec(`ALTER TABLE ${table} ADD COLUMN markup_override_percent TEXT`);
  }
  const calculatorRateColumns=await db.all('PRAGMA table_info(project_calculator_lab_exchange_rate_snapshots)');
  if(!calculatorRateColumns.some(column=>column.name==='inverse_rate'))await db.exec('ALTER TABLE project_calculator_lab_exchange_rate_snapshots ADD COLUMN inverse_rate TEXT');
  const importSessionColumns=await db.all('PRAGMA table_info(supplier_import_lab_sessions)');
  if(!importSessionColumns.some(column=>column.name==='estimate_id'))await db.exec('ALTER TABLE supplier_import_lab_sessions ADD COLUMN estimate_id TEXT');
  const importAttachmentColumns=await db.all('PRAGMA table_info(supplier_import_lab_attachments)');
  if(!importAttachmentColumns.some(column=>column.name==='upload_order'))await db.exec('ALTER TABLE supplier_import_lab_attachments ADD COLUMN upload_order INTEGER NOT NULL DEFAULT 0');
  const supplierQuoteAttachmentColumns=await db.all('PRAGMA table_info(supplier_quote_attachments)');
  if(!supplierQuoteAttachmentColumns.some(column=>column.name==='document_kind'))await db.exec("ALTER TABLE supplier_quote_attachments ADD COLUMN document_kind TEXT NOT NULL DEFAULT 'complete_quotation'");
  if(!supplierQuoteAttachmentColumns.some(column=>column.name==='uploaded_by'))await db.exec("ALTER TABLE supplier_quote_attachments ADD COLUMN uploaded_by TEXT NOT NULL DEFAULT 'local-admin'");
  if(!supplierQuoteAttachmentColumns.some(column=>column.name==='upload_order'))await db.exec('ALTER TABLE supplier_quote_attachments ADD COLUMN upload_order INTEGER NOT NULL DEFAULT 0');
  const calculatorQuoteRevisionColumns=await db.all('PRAGMA table_info(project_calculator_supplier_quote_revisions)');
  if(!calculatorQuoteRevisionColumns.some(column=>column.name==='fx_snapshot_id'))await db.exec('ALTER TABLE project_calculator_supplier_quote_revisions ADD COLUMN fx_snapshot_id TEXT');
  const estimateProductFxColumns=await db.all('PRAGMA table_info(project_calculator_estimate_product_rows)');
  if(!estimateProductFxColumns.some(column=>column.name==='fx_snapshot_id'))await db.exec('ALTER TABLE project_calculator_estimate_product_rows ADD COLUMN fx_snapshot_id TEXT');
  if(!estimateProductFxColumns.some(column=>column.name==='purchase_amount_gbp'))await db.exec('ALTER TABLE project_calculator_estimate_product_rows ADD COLUMN purchase_amount_gbp TEXT');
  if(!estimateProductFxColumns.some(column=>column.name==='selling_amount_gbp'))await db.exec('ALTER TABLE project_calculator_estimate_product_rows ADD COLUMN selling_amount_gbp TEXT');
  const estimateCostFxColumns=await db.all('PRAGMA table_info(project_calculator_estimate_supplier_costs)');
  if(!estimateCostFxColumns.some(column=>column.name==='fx_snapshot_id'))await db.exec('ALTER TABLE project_calculator_estimate_supplier_costs ADD COLUMN fx_snapshot_id TEXT');
  if(!estimateCostFxColumns.some(column=>column.name==='purchase_amount_gbp'))await db.exec('ALTER TABLE project_calculator_estimate_supplier_costs ADD COLUMN purchase_amount_gbp TEXT');
  if(!estimateCostFxColumns.some(column=>column.name==='selling_amount_gbp'))await db.exec('ALTER TABLE project_calculator_estimate_supplier_costs ADD COLUMN selling_amount_gbp TEXT');
  const calculatorScenarioOwnershipColumns=await db.all('PRAGMA table_info(project_calculator_lab_scenarios)');
  if(!calculatorScenarioOwnershipColumns.some(column=>column.name==='estimate_id'))await db.exec('ALTER TABLE project_calculator_lab_scenarios ADD COLUMN estimate_id TEXT');
  if(!calculatorScenarioOwnershipColumns.some(column=>column.name==='target_gross_margin_percent'))await db.exec('ALTER TABLE project_calculator_lab_scenarios ADD COLUMN target_gross_margin_percent TEXT');
  if(!calculatorScenarioOwnershipColumns.some(column=>column.name==='commercial_margin_policy_json'))await db.exec('ALTER TABLE project_calculator_lab_scenarios ADD COLUMN commercial_margin_policy_json TEXT');
  const labRowColumns = await db.all('PRAGMA table_info(supplier_import_lab_extracted_rows)');
  if (!labRowColumns.some((column) => column.name === 'review_warnings_json')) await db.exec("ALTER TABLE supplier_import_lab_extracted_rows ADD COLUMN review_warnings_json TEXT NOT NULL DEFAULT '[]'");
  if (!labRowColumns.some((column) => column.name === 'selected_for_future_use')) await db.exec('ALTER TABLE supplier_import_lab_extracted_rows ADD COLUMN selected_for_future_use INTEGER NOT NULL DEFAULT 1 CHECK (selected_for_future_use IN (0,1))');
  const now=new Date().toISOString();
  for(const [id,category,label,rateType,price,variant] of CALCULATOR_CATALOGUE_DEFAULTS)await db.run('INSERT OR IGNORE INTO project_calculator_admin_catalogue_items(id,category,label,rate_type,price_amount,currency,variant_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)',id,category,label,rateType,price,'GBP',JSON.stringify(variant||{}),now,now);
  await db.run("UPDATE project_calculator_admin_catalogue_items SET active=0,updated_at=? WHERE id='me508_unconfigured' AND price_amount IS NULL",now);
  for(const [key,value] of Object.entries(CALCULATION_RULE_DEFAULTS))await db.run('INSERT OR IGNORE INTO project_calculator_admin_rules(rule_key,rule_value_json,updated_at) VALUES(?,?,?)',key,JSON.stringify(value),now);
  for(const [code,inclusions] of Object.entries(PACKAGE_RULE_DEFAULTS))await db.run('INSERT OR IGNORE INTO project_calculator_admin_package_rules(package_code,inclusions_json,updated_at) VALUES(?,?,?)',code,JSON.stringify(inclusions),now);
  for (const statement of indexes) await db.exec(statement);
}

export const supplierCommercialTableNames = Object.freeze([
  'supplier_import_lab_sessions', 'supplier_import_lab_attachments', 'supplier_import_lab_extraction_runs',
  'supplier_import_lab_extracted_documents', 'supplier_import_lab_extracted_rows',
  'supplier_import_lab_commercial_summaries', 'supplier_import_lab_additional_cost_items',
  'supplier_quotes', 'supplier_quote_revisions', 'supplier_quote_attachments',
  'supplier_quote_import_runs', 'supplier_quote_import_run_attachments',
  'supplier_quote_positions', 'supplier_specification_items', 'supplier_quote_extras',
  'supplier_position_match_proposals', 'supplier_quote_review_decisions',
  'supplier_position_applications', 'project_calculators', 'project_cost_items',
  'pricing_scenarios', 'calculator_snapshots',
  'project_calculator_lab_scenarios', 'project_calculator_lab_product_rows',
  'project_calculator_estimate_product_rows', 'project_calculator_estimate_supplier_costs',
  'project_calculator_supplier_quote_revisions',
  'project_calculator_supplier_fx_snapshots',
  'project_calculator_lab_supplier_costs', 'project_calculator_lab_package_items',
  'project_calculator_lab_route_snapshots',
  'project_calculator_lab_manual_product_rows', 'project_calculator_lab_manual_cost_lines',
  'project_calculator_lab_exchange_rate_snapshots', 'project_calculator_lab_markup_rules',
  'project_calculator_lab_revisions',
  'project_calculator_admin_catalogue_items','project_calculator_admin_rules','project_calculator_admin_package_rules',
  'project_calculator_lab_catalogue_snapshots','project_calculator_lab_options',
]);
