const tables = [
  `CREATE TABLE IF NOT EXISTS supplier_import_lab_sessions (
    id TEXT PRIMARY KEY,
    supplier_code TEXT,
    supplier_name TEXT NOT NULL CHECK (length(trim(supplier_name)) > 0),
    supplier_quotation_number TEXT,
    supplier_revision TEXT,
    full_quotation_reference TEXT,
    quotation_date TEXT,
    currency TEXT NOT NULL CHECK (length(currency) = 3 AND currency = upper(currency)),
    status TEXT NOT NULL CHECK (status IN ('draft','uploaded','extraction_pending','extracted','failed','archived')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    archived_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_import_lab_attachments (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('original_quote','supporting_document','supplier_drawing')),
    original_file_name TEXT NOT NULL,
    media_type TEXT NOT NULL,
    size_bytes INTEGER NOT NULL CHECK (size_bytes >= 0),
    sha256 TEXT NOT NULL CHECK (length(sha256) = 64 AND sha256 = lower(sha256)),
    storage_key TEXT NOT NULL UNIQUE,
    parser_eligible INTEGER NOT NULL CHECK (parser_eligible IN (0,1)),
    created_at TEXT NOT NULL,
    FOREIGN KEY (session_id) REFERENCES supplier_import_lab_sessions(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_quotes (
    id TEXT PRIMARY KEY,
    estimate_id TEXT NOT NULL,
    supplier_code TEXT NOT NULL,
    supplier_name TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    archived_at TEXT,
    UNIQUE (id, estimate_id),
    FOREIGN KEY (estimate_id) REFERENCES estimates(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_quote_revisions (
    id TEXT PRIMARY KEY,
    supplier_quote_id TEXT NOT NULL,
    estimate_id TEXT NOT NULL,
    revision_sequence INTEGER NOT NULL CHECK (revision_sequence >= 0),
    supplier_quotation_number TEXT NOT NULL,
    supplier_revision TEXT,
    full_quotation_reference TEXT NOT NULL,
    quotation_date TEXT,
    customer_reference TEXT,
    currency TEXT NOT NULL CHECK (length(currency) = 3 AND currency = upper(currency)),
    vat_status TEXT NOT NULL,
    product_subtotal_amount TEXT,
    extras_total_amount TEXT,
    delivery_total_amount TEXT,
    vat_total_amount TEXT,
    final_supplier_total_amount TEXT,
    lifecycle_status TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    superseded_at TEXT,
    superseded_by_revision_id TEXT,
    UNIQUE (supplier_quote_id, revision_sequence),
    UNIQUE (id, estimate_id),
    CHECK ((lifecycle_status = 'superseded' AND superseded_at IS NOT NULL AND superseded_by_revision_id IS NOT NULL) OR (lifecycle_status <> 'superseded' AND superseded_at IS NULL AND superseded_by_revision_id IS NULL)),
    FOREIGN KEY (supplier_quote_id, estimate_id) REFERENCES supplier_quotes(id, estimate_id) ON DELETE CASCADE,
    FOREIGN KEY (superseded_by_revision_id, estimate_id) REFERENCES supplier_quote_revisions(id, estimate_id)
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_quote_attachments (
    id TEXT PRIMARY KEY,
    estimate_id TEXT NOT NULL,
    revision_id TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('original_quote','supplier_drawing','supporting_document','derived_artifact')),
    original_file_name TEXT NOT NULL,
    media_type TEXT NOT NULL,
    size_bytes INTEGER NOT NULL CHECK (size_bytes >= 0),
    sha256 TEXT NOT NULL CHECK (length(sha256) = 64 AND sha256 = lower(sha256)),
    storage_key TEXT NOT NULL UNIQUE,
    parser_eligible INTEGER NOT NULL CHECK (parser_eligible IN (0,1)),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    derived_from_attachment_id TEXT,
    artifact_type TEXT,
    extractor_version TEXT,
    UNIQUE (id, estimate_id),
    CHECK ((role = 'derived_artifact' AND derived_from_attachment_id IS NOT NULL AND artifact_type IS NOT NULL) OR (role <> 'derived_artifact' AND artifact_type IS NULL)),
    FOREIGN KEY (revision_id, estimate_id) REFERENCES supplier_quote_revisions(id, estimate_id) ON DELETE CASCADE,
    FOREIGN KEY (derived_from_attachment_id, estimate_id) REFERENCES supplier_quote_attachments(id, estimate_id)
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_quote_import_runs (
    id TEXT PRIMARY KEY,
    estimate_id TEXT NOT NULL,
    revision_id TEXT NOT NULL,
    extractor_name TEXT NOT NULL,
    extractor_version TEXT NOT NULL,
    adapter_code TEXT NOT NULL,
    adapter_version TEXT NOT NULL,
    recognition_version TEXT NOT NULL,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    status TEXT NOT NULL,
    warnings_json TEXT NOT NULL DEFAULT '[]',
    error_code TEXT,
    error_message TEXT,
    raw_result_attachment_id TEXT,
    UNIQUE (id, estimate_id),
    CHECK ((status IN ('completed','completed_with_warnings','failed','cancelled') AND completed_at IS NOT NULL) OR (status IN ('queued','running') AND completed_at IS NULL)),
    CHECK (status <> 'failed' OR error_code IS NOT NULL OR error_message IS NOT NULL),
    FOREIGN KEY (revision_id, estimate_id) REFERENCES supplier_quote_revisions(id, estimate_id) ON DELETE CASCADE,
    FOREIGN KEY (raw_result_attachment_id, estimate_id) REFERENCES supplier_quote_attachments(id, estimate_id)
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_quote_import_run_attachments (
    import_run_id TEXT NOT NULL,
    attachment_id TEXT NOT NULL,
    ordinal INTEGER NOT NULL CHECK (ordinal >= 0),
    role TEXT NOT NULL,
    PRIMARY KEY (import_run_id, attachment_id),
    UNIQUE (import_run_id, ordinal),
    FOREIGN KEY (import_run_id) REFERENCES supplier_quote_import_runs(id) ON DELETE CASCADE,
    FOREIGN KEY (attachment_id) REFERENCES supplier_quote_attachments(id)
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_quote_positions (
    id TEXT PRIMARY KEY,
    estimate_id TEXT NOT NULL,
    revision_id TEXT NOT NULL,
    display_reference TEXT NOT NULL CHECK (length(trim(display_reference)) > 0),
    supplier_reference_tokens_json TEXT NOT NULL DEFAULT '[]',
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    product TEXT,
    product_system TEXT,
    original_specification_text TEXT NOT NULL DEFAULT '',
    width_mm INTEGER,
    height_mm INTEGER,
    supplier_area_square_metres TEXT,
    calculated_area_square_metres TEXT,
    unit_purchase_price_amount TEXT,
    total_purchase_price_amount TEXT,
    currency TEXT,
    supplier_drawing_attachment_id TEXT,
    opening_direction TEXT,
    view_direction TEXT NOT NULL DEFAULT 'unknown',
    proposed_window_type_id TEXT,
    proposed_proof_family_id TEXT,
    recognition_confidence REAL CHECK (recognition_confidence IS NULL OR recognition_confidence BETWEEN 0 AND 1),
    recognition_reasons_json TEXT NOT NULL DEFAULT '[]',
    source_pages_json TEXT NOT NULL DEFAULT '[]',
    trace_json TEXT NOT NULL DEFAULT '[]',
    review_status TEXT NOT NULL DEFAULT 'unreviewed',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (id, estimate_id),
    FOREIGN KEY (revision_id, estimate_id) REFERENCES supplier_quote_revisions(id, estimate_id) ON DELETE CASCADE,
    FOREIGN KEY (supplier_drawing_attachment_id, estimate_id) REFERENCES supplier_quote_attachments(id, estimate_id)
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_specification_items (
    id TEXT PRIMARY KEY,
    supplier_position_id TEXT NOT NULL,
    ordinal INTEGER NOT NULL CHECK (ordinal >= 0),
    supplied_number TEXT,
    original_text TEXT NOT NULL CHECK (length(original_text) > 0),
    normalized_label TEXT,
    normalized_value TEXT,
    trace_json TEXT NOT NULL DEFAULT '[]',
    UNIQUE (supplier_position_id, ordinal),
    FOREIGN KEY (supplier_position_id) REFERENCES supplier_quote_positions(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_quote_extras (
    id TEXT PRIMARY KEY,
    estimate_id TEXT NOT NULL,
    revision_id TEXT NOT NULL,
    category TEXT NOT NULL,
    label TEXT NOT NULL,
    original_text TEXT NOT NULL,
    quantity TEXT,
    unit_price_amount TEXT,
    total_price_amount TEXT,
    currency TEXT NOT NULL,
    trace_json TEXT NOT NULL DEFAULT '[]',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (revision_id, estimate_id) REFERENCES supplier_quote_revisions(id, estimate_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_position_match_proposals (
    proposal_key TEXT PRIMARY KEY,
    estimate_id TEXT NOT NULL,
    supplier_position_id TEXT NOT NULL,
    proposed_window_type_id TEXT,
    proposed_proof_family_id TEXT,
    score REAL NOT NULL,
    confidence REAL NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    reasons_json TEXT NOT NULL DEFAULT '[]',
    normalized_evidence_json TEXT NOT NULL,
    recognition_version TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    supported_by_production_manifest INTEGER NOT NULL CHECK (supported_by_production_manifest IN (0,1)),
    blocking_issues_json TEXT NOT NULL DEFAULT '[]',
    rank INTEGER NOT NULL CHECK (rank >= 0),
    UNIQUE (supplier_position_id, rank),
    FOREIGN KEY (supplier_position_id, estimate_id) REFERENCES supplier_quote_positions(id, estimate_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_quote_review_decisions (
    id TEXT PRIMARY KEY,
    estimate_id TEXT NOT NULL,
    supplier_position_id TEXT NOT NULL,
    import_run_id TEXT NOT NULL,
    review_version TEXT NOT NULL,
    decision TEXT NOT NULL CHECK (decision IN ('accepted','corrected','rejected','deferred')),
    selected_proposal_key TEXT,
    proposed_configuration_snapshot_json TEXT NOT NULL,
    approved_configuration_snapshot_json TEXT,
    resulting_position_id TEXT,
    resulting_contract_schema_version INTEGER,
    reviewer_id TEXT NOT NULL,
    reviewed_at TEXT NOT NULL,
    note TEXT,
    CHECK (decision NOT IN ('rejected','deferred') OR (resulting_position_id IS NULL AND resulting_contract_schema_version IS NULL)),
    FOREIGN KEY (supplier_position_id, estimate_id) REFERENCES supplier_quote_positions(id, estimate_id) ON DELETE CASCADE,
    FOREIGN KEY (import_run_id, estimate_id) REFERENCES supplier_quote_import_runs(id, estimate_id),
    FOREIGN KEY (selected_proposal_key) REFERENCES supplier_position_match_proposals(proposal_key)
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_position_applications (
    id TEXT PRIMARY KEY,
    estimate_id TEXT NOT NULL,
    supplier_quote_id TEXT NOT NULL,
    supplier_quote_revision_id TEXT NOT NULL,
    supplier_quote_position_id TEXT NOT NULL,
    action TEXT NOT NULL CHECK (action IN ('include_as_new_position','map_to_existing_position','replace_existing_position','exclude','comparison_only','deferred')),
    target_estimate_position_id TEXT,
    applied_at TEXT NOT NULL,
    applied_by TEXT NOT NULL,
    active INTEGER NOT NULL CHECK (active IN (0,1)),
    superseded_by_application_id TEXT,
    note TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (id, estimate_id),
    CHECK (action NOT IN ('exclude','comparison_only','deferred') OR target_estimate_position_id IS NULL),
    FOREIGN KEY (supplier_quote_id, estimate_id) REFERENCES supplier_quotes(id, estimate_id) ON DELETE CASCADE,
    FOREIGN KEY (supplier_quote_revision_id, estimate_id) REFERENCES supplier_quote_revisions(id, estimate_id) ON DELETE CASCADE,
    FOREIGN KEY (supplier_quote_position_id, estimate_id) REFERENCES supplier_quote_positions(id, estimate_id) ON DELETE CASCADE,
    FOREIGN KEY (superseded_by_application_id, estimate_id) REFERENCES supplier_position_applications(id, estimate_id)
  )`,
  `CREATE TABLE IF NOT EXISTS project_calculators (
    id TEXT PRIMARY KEY,
    estimate_id TEXT NOT NULL,
    base_currency TEXT NOT NULL,
    active_scenario_id TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    archived_at TEXT,
    UNIQUE (id, estimate_id),
    FOREIGN KEY (estimate_id) REFERENCES estimates(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS project_cost_items (
    id TEXT PRIMARY KEY,
    calculator_id TEXT NOT NULL,
    estimate_id TEXT NOT NULL,
    category TEXT NOT NULL,
    label TEXT NOT NULL,
    quantity TEXT NOT NULL,
    unit_cost_amount TEXT NOT NULL,
    unit_cost_currency TEXT NOT NULL,
    total_cost_amount TEXT NOT NULL,
    total_cost_currency TEXT NOT NULL,
    source TEXT NOT NULL,
    included INTEGER NOT NULL CHECK (included IN (0,1)),
    supplier_quote_revision_id TEXT,
    supplier_position_id TEXT,
    manually_overridden INTEGER NOT NULL CHECK (manually_overridden IN (0,1)),
    source_value_snapshot_json TEXT,
    exchange_rate TEXT,
    exchange_rate_date TEXT,
    exchange_rate_source TEXT,
    converted_total_amount TEXT,
    converted_currency TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (calculator_id, estimate_id) REFERENCES project_calculators(id, estimate_id) ON DELETE CASCADE,
    FOREIGN KEY (supplier_quote_revision_id, estimate_id) REFERENCES supplier_quote_revisions(id, estimate_id),
    FOREIGN KEY (supplier_position_id, estimate_id) REFERENCES supplier_quote_positions(id, estimate_id)
  )`,
  `CREATE TABLE IF NOT EXISTS pricing_scenarios (
    id TEXT PRIMARY KEY,
    calculator_id TEXT NOT NULL,
    estimate_id TEXT NOT NULL,
    name TEXT NOT NULL,
    status TEXT NOT NULL,
    markup_percent TEXT,
    target_margin_percent TEXT,
    net_cost_amount TEXT NOT NULL,
    currency TEXT NOT NULL,
    contingency_amount TEXT NOT NULL,
    gross_profit_amount TEXT NOT NULL,
    margin_percent TEXT NOT NULL,
    vat_status TEXT NOT NULL,
    vat_rate_percent TEXT NOT NULL,
    vat_amount TEXT NOT NULL,
    selling_price_ex_vat TEXT NOT NULL,
    selling_price_inc_vat TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (id, estimate_id),
    FOREIGN KEY (calculator_id, estimate_id) REFERENCES project_calculators(id, estimate_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS calculator_snapshots (
    id TEXT PRIMARY KEY,
    calculator_id TEXT NOT NULL,
    estimate_id TEXT NOT NULL,
    scenario_id TEXT NOT NULL,
    snapshot_version TEXT NOT NULL,
    calculation_inputs_json TEXT NOT NULL,
    calculation_outputs_json TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by TEXT NOT NULL,
    FOREIGN KEY (calculator_id, estimate_id) REFERENCES project_calculators(id, estimate_id) ON DELETE CASCADE,
    FOREIGN KEY (scenario_id, estimate_id) REFERENCES pricing_scenarios(id, estimate_id) ON DELETE CASCADE
  )`,
];

const indexes = [
  'CREATE INDEX IF NOT EXISTS idx_supplier_import_lab_sessions_status ON supplier_import_lab_sessions(status)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_import_lab_sessions_created ON supplier_import_lab_sessions(created_at)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_import_lab_sessions_archive ON supplier_import_lab_sessions(archived_at)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_import_lab_attachments_session ON supplier_import_lab_attachments(session_id, created_at)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_quotes_estimate ON supplier_quotes(estimate_id, archived_at)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_revisions_quote ON supplier_quote_revisions(estimate_id, supplier_quote_id, revision_sequence)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_revisions_lifecycle ON supplier_quote_revisions(estimate_id, lifecycle_status)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_attachments_revision ON supplier_quote_attachments(estimate_id, revision_id)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_import_runs_revision ON supplier_quote_import_runs(estimate_id, revision_id, started_at)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_positions_revision ON supplier_quote_positions(estimate_id, revision_id)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_extras_revision ON supplier_quote_extras(estimate_id, revision_id)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_proposals_position ON supplier_position_match_proposals(estimate_id, supplier_position_id, rank)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_reviews_position ON supplier_quote_review_decisions(estimate_id, supplier_position_id, reviewed_at)',
  'CREATE INDEX IF NOT EXISTS idx_supplier_applications_position ON supplier_position_applications(estimate_id, supplier_quote_position_id, created_at)',
  'CREATE UNIQUE INDEX IF NOT EXISTS idx_supplier_applications_one_active ON supplier_position_applications(estimate_id, supplier_quote_position_id) WHERE active = 1',
  'CREATE INDEX IF NOT EXISTS idx_project_calculators_estimate ON project_calculators(estimate_id, archived_at)',
  'CREATE UNIQUE INDEX IF NOT EXISTS idx_project_calculators_one_active ON project_calculators(estimate_id) WHERE archived_at IS NULL',
  'CREATE INDEX IF NOT EXISTS idx_project_cost_items_calculator ON project_cost_items(estimate_id, calculator_id)',
  'CREATE INDEX IF NOT EXISTS idx_project_cost_items_supplier_source ON project_cost_items(estimate_id, supplier_quote_revision_id, supplier_position_id)',
  'CREATE INDEX IF NOT EXISTS idx_pricing_scenarios_calculator ON pricing_scenarios(estimate_id, calculator_id, status)',
  'CREATE INDEX IF NOT EXISTS idx_calculator_snapshots_scenario ON calculator_snapshots(estimate_id, scenario_id, created_at)',
];

export async function initializeSupplierCommercialSchema(db) {
  await db.exec('PRAGMA foreign_keys = ON');
  for (const statement of tables) await db.exec(statement);
  for (const statement of indexes) await db.exec(statement);
}

export const supplierCommercialTableNames = Object.freeze([
  'supplier_import_lab_sessions', 'supplier_import_lab_attachments',
  'supplier_quotes', 'supplier_quote_revisions', 'supplier_quote_attachments',
  'supplier_quote_import_runs', 'supplier_quote_import_run_attachments',
  'supplier_quote_positions', 'supplier_specification_items', 'supplier_quote_extras',
  'supplier_position_match_proposals', 'supplier_quote_review_decisions',
  'supplier_position_applications', 'project_calculators', 'project_cost_items',
  'pricing_scenarios', 'calculator_snapshots',
]);
