import { Component, useCallback, useEffect, useMemo, useState, type ErrorInfo, type ReactNode } from "react";
import { documentRecordsApi, type DocumentRecordsResult } from "../../services/documents/documentRecordsApi";
import HierarchicalFileExplorer from "./HierarchicalFileExplorer";
import "./canonicalDocuments.css";

const label = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (character) => character.toUpperCase());
const providerLabel = (value: string) => ({ google_drive: "Google Drive", microsoft_onedrive: "OneDrive", microsoft_sharepoint: "SharePoint", quotesuite_managed: "QuoteSuite managed" }[value] || label(value));

type Props = { enquiryId?: string; clientId?: string; projectId?: string; estimateId?: string };

class FilesExplorerBoundary extends Component<{children:ReactNode;resetKey:string;onUseAllDocuments:()=>void},{failed:boolean}> {
  state={failed:false};
  static getDerivedStateFromError(){return {failed:true}}
  componentDidCatch(error:Error,info:ErrorInfo){console.error("Files folder explorer could not render",{message:error.message,componentStack:info.componentStack})}
  componentDidUpdate(previous:{resetKey:string}){if(this.state.failed&&previous.resetKey!==this.props.resetKey)this.setState({failed:false})}
  render(){if(!this.state.failed)return this.props.children;return <div className="canonical-documents__explorer-error ui-status ui-status--error" role="alert"><div><strong>Folder explorer could not be displayed.</strong><span>Cached documents remain available in All Documents.</span></div><div className="ui-action-row"><button type="button" className="ui-button ui-button--ghost" onClick={()=>this.setState({failed:false})}>Retry folders</button><button type="button" className="ui-button ui-button--primary" onClick={this.props.onUseAllDocuments}>Open All Documents</button></div></div>}
}

export default function CanonicalDocumentsPanel({ enquiryId, clientId, projectId, estimateId }: Props) {
  const [result, setResult] = useState<DocumentRecordsResult | null>(null);
  const [loadError, setLoadError] = useState(""), [syncError, setSyncError] = useState(""), [view, setView] = useState<"folders"|"documents">("folders"), [filter, setFilter] = useState("all"), [supplierFilter, setSupplierFilter] = useState("all"), [projectFilter, setProjectFilter] = useState("all"), [estimateFilter, setEstimateFilter] = useState("all"), [providerFilter, setProviderFilter] = useState("all"), [search, setSearch] = useState(""), [syncing, setSyncing] = useState(false);
  const listCached = useCallback(() => estimateId ? documentRecordsApi.listEstimate(estimateId) : projectId ? documentRecordsApi.listProject(projectId) : clientId ? documentRecordsApi.listClient(clientId) : enquiryId ? documentRecordsApi.listEnquiry(enquiryId) : Promise.reject(new Error("Document context is unavailable.")), [clientId, enquiryId, estimateId, projectId]);
  const syncDrive = useCallback(() => estimateId ? documentRecordsApi.syncEstimate(estimateId) : projectId ? documentRecordsApi.syncProject(projectId) : clientId ? documentRecordsApi.syncClient(clientId) : enquiryId ? documentRecordsApi.syncEnquiry(enquiryId) : Promise.resolve(), [clientId, enquiryId, estimateId, projectId]);
  const refresh = useCallback(async () => { setSyncing(true); setSyncError(""); try { await syncDrive(); setResult(await listCached()); } catch (reason) { setSyncError(reason instanceof Error ? reason.message : "Drive sync failed — showing cached files."); } finally { setSyncing(false); } }, [listCached, syncDrive]);
  useEffect(() => { let active = true; (async () => { setLoadError(""); setSyncError(""); try { const cached=await listCached(); if (!active) return; setResult(cached); setSyncing(true); try { await syncDrive(); if (active) setResult(await listCached()); } catch (reason) { if (active) setSyncError(`${reason instanceof Error ? reason.message : "Drive sync failed."} — showing cached files`); } finally { if (active) setSyncing(false); } } catch (reason) { if (active) setLoadError(reason instanceof Error ? reason.message : "Documents could not be loaded."); } })(); return () => { active = false; }; }, [listCached, syncDrive]);
  const types = useMemo(() => [...new Set((result?.documents || []).map((item) => item.documentType))].sort(), [result]);
  const suppliers = useMemo(() => [...new Set((result?.documents || []).map((item) => item.supplierName).filter((value):value is string => Boolean(value)))].sort(), [result]);
  const projects = useMemo(() => [...new Set((result?.documents || []).map((item) => item.projectName).filter(Boolean))].sort(), [result]);
  const estimates = useMemo(() => [...new Set((result?.documents || []).map((item) => item.estimateRef).filter(Boolean))].sort(), [result]);
  const providers = useMemo(() => [...new Set((result?.documents || []).map((item) => item.provider))].sort(), [result]);
  const documents = useMemo(() => { const term = search.trim().toLowerCase(); return (result?.documents || []).filter((item) => (filter === "all" || item.documentType === filter) && (supplierFilter === "all" || item.supplierName === supplierFilter) && (projectFilter === "all" || item.projectName === projectFilter) && (estimateFilter === "all" || item.estimateRef === estimateFilter) && (providerFilter === "all" || item.provider === providerFilter) && (!term || [item.fileName, item.reference, item.estimateRef, item.projectName, item.supplierName, item.folder].some((value) => String(value || "").toLowerCase().includes(term)))); }, [result, filter, supplierFilter, projectFilter, estimateFilter, providerFilter, search]);
  if (loadError) return <div className="ui-status ui-status--error" role="alert">{loadError}</div>;
  if (!result) return <div className="ui-empty-state ui-loading">Loading canonical documents…</div>;
  const syncLabels = { idle: "Drive not synced yet", syncing: "Syncing…", synced: result.sync.lastSuccessAt ? `Synced ${new Date(result.sync.lastSuccessAt).toLocaleString("en-GB")}` : "Synced", synced_no_files: "Synced — no files found", client_folder_not_matched: "Client folder not matched", project_assignment_pending: "Project assignment pending — Client files cached", failed: "Sync failed — showing cached files" } as const;
  const effectiveSyncState = syncing ? "syncing" : syncError ? "failed" : result.sync.state;
  const syncLabel = syncLabels[effectiveSyncState];
  const title = estimateId ? "Estimate Files / Documents" : projectId ? "Project Files" : enquiryId ? "Enquiry Files" : "Client Files";
  return <section className="canonical-documents" aria-label="Canonical commercial documents" data-document-scope={estimateId ? "estimate" : projectId ? "project" : enquiryId ? "enquiry" : "client"}>
    <header><div><h3>{title}</h3><p>Browse cached provider folders or switch to the complete canonical document register. Provider IDs remain authoritative if folders or files are renamed.</p></div><div className="canonical-documents__header-actions"><div className="canonical-documents__summary"><span className="ui-status ui-status--muted">{result.documents.length} document{result.documents.length === 1 ? "" : "s"}</span><span className="ui-status ui-status--muted">{result.folders.length} linked folder{result.folders.length === 1 ? "" : "s"}</span><span className={`ui-status ${syncError || effectiveSyncState === "client_folder_not_matched" ? "ui-status--warning" : "ui-status--muted"}`} role="status" data-sync-state={effectiveSyncState}>{syncLabel}</span></div><button type="button" className="ui-button ui-button--ghost" disabled={syncing} onClick={() => void refresh()}>↻ Sync Drive</button></div></header>
    {syncError ? <p className="canonical-documents__sync-error" role="alert">{syncError}</p> : null}
    <div className="canonical-documents__view-tabs" role="tablist" aria-label="Files view"><button type="button" role="tab" aria-selected={view === "folders"} className={`ui-button ${view === "folders" ? "ui-button--primary" : "ui-button--ghost"}`} onClick={() => setView("folders")}>Folders</button><button type="button" role="tab" aria-selected={view === "documents"} className={`ui-button ${view === "documents" ? "ui-button--primary" : "ui-button--ghost"}`} onClick={() => setView("documents")}>All Documents</button></div>
    {view === "folders" ? <FilesExplorerBoundary resetKey={`${JSON.stringify(result.scope)}:${result.folders.length}:${result.documents.length}`} onUseAllDocuments={()=>setView("documents")}><HierarchicalFileExplorer key={JSON.stringify(result.scope)} result={result} rootLabel={title} search={search} onSearchChange={setSearch} onRecordsUpdated={setResult}/></FilesExplorerBoundary> : <>
      <div className="canonical-documents__filters"><label>Document type<select className="ui-input" value={filter} onChange={(event) => setFilter(event.currentTarget.value)}><option value="all">All types</option>{types.map((type) => <option key={type} value={type}>{label(type)}</option>)}</select></label><label>Supplier<select className="ui-input" value={supplierFilter} onChange={(event) => setSupplierFilter(event.currentTarget.value)}><option value="all">All suppliers</option>{suppliers.map((value) => <option key={value}>{value}</option>)}</select></label><label>Project<select className="ui-input" value={projectFilter} onChange={(event) => setProjectFilter(event.currentTarget.value)}><option value="all">All projects</option>{projects.map((value) => <option key={value}>{value}</option>)}</select></label><label>Estimate<select className="ui-input" value={estimateFilter} onChange={(event) => setEstimateFilter(event.currentTarget.value)}><option value="all">All estimates</option>{estimates.map((value) => <option key={value}>{value}</option>)}</select></label><label>Provider<select className="ui-input" value={providerFilter} onChange={(event) => setProviderFilter(event.currentTarget.value)}><option value="all">All providers</option>{providers.map((value) => <option key={value} value={value}>{providerLabel(value)}</option>)}</select></label><label>Search<input className="ui-input" type="search" value={search} onChange={(event) => setSearch(event.currentTarget.value)} placeholder="File, project, estimate or supplier"/></label></div>
      {documents.length ? <div className="canonical-documents__table-wrap"><table><thead><tr><th>File</th><th>Project / Estimate</th><th>Type / Supplier</th><th>Revision</th><th>Provider / Folder</th><th>Modified</th><th>Actions</th></tr></thead><tbody>{documents.map((item) => <tr key={item.id} className={item.removedAt ? "canonical-documents__row--removed" : undefined}><td data-label="File"><strong>{item.fileName}</strong><small>{item.reference}</small></td><td data-label="Project / Estimate">{item.projectName || "—"}<small>{item.estimateRef}</small></td><td data-label="Type / Supplier">{label(item.documentType)}<small>{item.supplierName || "—"}</small></td><td data-label="Revision">{item.revision}<small>{label(item.status)}</small></td><td data-label="Provider / Folder">{providerLabel(item.provider)}<small>{item.folder}{item.providerFileId ? " · Provider file linked" : ""}</small></td><td data-label="Modified">{new Date(item.modifiedAt).toLocaleDateString("en-GB")}</td><td data-label="Actions"><div className="ui-action-row">{item.downloadUrl ? <a className="ui-button ui-button--ghost" href={documentRecordsApi.downloadUrl(item.downloadUrl)}>Open document</a> : item.openUrl ? <a className="ui-button ui-button--ghost" href={item.openUrl} target="_blank" rel="noreferrer">Open in Drive</a> : <span className="ui-status ui-status--muted">Evidence only</span>}</div></td></tr>)}</tbody></table></div> : <div className="ui-empty-state">No cached documents match these filters. Clear a filter or return to Folders.</div>}
    </>}
  </section>;
}
