import { useCallback, useEffect, useMemo, useState } from "react";
import { documentRecordsApi, type DocumentRecordsResult } from "../../services/documents/documentRecordsApi";
import "./canonicalDocuments.css";

const label=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,character=>character.toUpperCase());
const providerLabel=(value:string)=>({google_drive:"Google Drive",microsoft_onedrive:"OneDrive",microsoft_sharepoint:"SharePoint",quotesuite_managed:"QuoteSuite managed"}[value]||label(value));

export default function CanonicalDocumentsPanel({clientId,estimateId}:{clientId?:string;estimateId?:string}){
  const [result,setResult]=useState<DocumentRecordsResult|null>(null),[error,setError]=useState(""),[filter,setFilter]=useState("all"),[search,setSearch]=useState(""),[refreshing,setRefreshing]=useState(false);
  const load=useCallback(async()=>{setRefreshing(true);setError("");try{setResult(estimateId?await documentRecordsApi.listEstimate(estimateId):clientId?await documentRecordsApi.listClient(clientId):await Promise.reject(new Error("Document context is unavailable.")))}catch(reason){setError(reason instanceof Error?reason.message:"Documents could not be loaded.")}finally{setRefreshing(false)}},[clientId,estimateId]);
  useEffect(()=>{void load()},[load]);
  const types=useMemo(()=>[...new Set((result?.documents||[]).map(item=>item.documentType))].sort(),[result]);
  const documents=useMemo(()=>{const term=search.trim().toLowerCase();return (result?.documents||[]).filter(item=>(filter==="all"||item.documentType===filter)&&(!term||[item.fileName,item.reference,item.estimateRef,item.projectName,item.supplierName,item.folder].some(value=>String(value||"").toLowerCase().includes(term))))},[result,filter,search]);
  if(error)return <div className="ui-status ui-status--error" role="alert">{error}</div>;
  if(!result)return <div className="ui-empty-state ui-loading">Loading canonical documents…</div>;
  return <section className="canonical-documents" aria-label="Canonical client and project documents">
    <header><div><h3>{estimateId?"Estimate Files / Documents":"Client Files"}</h3><p>One provider-neutral view of QuoteSuite evidence and linked cloud files. Provider IDs remain authoritative if folders or files are renamed.</p></div><div className="canonical-documents__header-actions"><div className="canonical-documents__summary"><span className="ui-status ui-status--muted">{documents.length} document{documents.length===1?"":"s"}</span><span className="ui-status ui-status--muted">{result.folders.length} linked folder{result.folders.length===1?"":"s"}</span></div><button type="button" className="ui-button ui-button--ghost" disabled={refreshing} onClick={()=>void load()}>↻ Refresh</button></div></header>
    <div className="canonical-documents__filters"><label>Document type<select className="ui-input" value={filter} onChange={event=>setFilter(event.currentTarget.value)}><option value="all">All documents</option>{types.map(type=><option key={type} value={type}>{label(type)}</option>)}</select></label><label>Search<input className="ui-input" value={search} onChange={event=>setSearch(event.currentTarget.value)} placeholder="File, project, estimate or supplier"/></label></div>
    {documents.length?<div className="canonical-documents__table-wrap"><table><thead><tr><th>File</th><th>Project / Estimate</th><th>Type / Supplier</th><th>Revision</th><th>Provider / Folder</th><th>Modified</th><th>Actions</th></tr></thead><tbody>{documents.map(item=><tr key={item.id}><td data-label="File"><strong>{item.fileName}</strong><small>{item.reference}</small></td><td data-label="Project / Estimate">{item.projectName||"—"}<small>{item.estimateRef}</small></td><td data-label="Type / Supplier">{label(item.documentType)}<small>{item.supplierName||"—"}</small></td><td data-label="Revision">{item.revision}<small>{label(item.status)}</small></td><td data-label="Provider / Folder">{providerLabel(item.provider)}<small>{item.folder}{item.providerFileId?` · Provider file linked`:""}</small></td><td data-label="Modified">{new Date(item.modifiedAt).toLocaleDateString("en-GB")}</td><td data-label="Actions"><div className="ui-action-row">{item.downloadUrl?<a className="ui-button ui-button--ghost" href={documentRecordsApi.downloadUrl(item.downloadUrl)}>Open document</a>:<span className="ui-status ui-status--muted">Evidence only</span>}</div></td></tr>)}</tbody></table></div>:<div className="ui-empty-state">No documents match this context. Supplier evidence and issued quotation documents will appear here automatically.</div>}
    {result.folders.length?<details><summary>Provisioned project folders ({result.folders.length})</summary><div className="canonical-documents__folders">{result.folders.map(folder=><span className="ui-chip" title={`Provider folder ID: ${folder.providerFolderId}`} key={folder.id}>{folder.estimateRef} · {folder.name}</span>)}</div></details>:null}
  </section>;
}
