import { useCallback, useEffect, useMemo, useState } from "react";
import { documentRecordsApi, type DocumentRecordsResult } from "../../services/documents/documentRecordsApi";
import "./canonicalDocuments.css";

const label = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (character) => character.toUpperCase());
const providerLabel = (value: string) => ({ google_drive: "Google Drive", microsoft_onedrive: "OneDrive", microsoft_sharepoint: "SharePoint", quotesuite_managed: "QuoteSuite managed" }[value] || label(value));

type Props = { enquiryId?: string; clientId?: string; projectId?: string; estimateId?: string };

export default function CanonicalDocumentsPanel({ enquiryId, clientId, projectId, estimateId }: Props) {
  const [result, setResult] = useState<DocumentRecordsResult | null>(null);
  const [loadError, setLoadError] = useState(""), [syncError, setSyncError] = useState(""), [filter, setFilter] = useState("all"), [search, setSearch] = useState(""), [syncing, setSyncing] = useState(false);
  const listCached = useCallback(() => estimateId ? documentRecordsApi.listEstimate(estimateId) : projectId ? documentRecordsApi.listProject(projectId) : clientId ? documentRecordsApi.listClient(clientId) : enquiryId ? documentRecordsApi.listEnquiry(enquiryId) : Promise.reject(new Error("Document context is unavailable.")), [clientId, enquiryId, estimateId, projectId]);
  const syncDrive = useCallback(() => estimateId ? documentRecordsApi.syncEstimate(estimateId) : projectId ? documentRecordsApi.syncProject(projectId) : clientId ? documentRecordsApi.syncClient(clientId) : enquiryId ? documentRecordsApi.syncEnquiry(enquiryId) : Promise.resolve(), [clientId, enquiryId, estimateId, projectId]);
  const refresh = useCallback(async () => { setSyncing(true); setSyncError(""); try { await syncDrive(); setResult(await listCached()); } catch (reason) { setSyncError(reason instanceof Error ? reason.message : "Drive sync failed — showing cached files."); } finally { setSyncing(false); } }, [listCached, syncDrive]);
  useEffect(() => { let active = true; (async () => { setLoadError(""); try { const cached=await listCached(); if (!active) return; setResult(cached); setSyncing(true); try { await syncDrive(); if (active) setResult(await listCached()); } catch (reason) { if (active) setSyncError(`${reason instanceof Error ? reason.message : "Drive sync failed."} — showing cached files`); } finally { if (active) setSyncing(false); } } catch (reason) { if (active) setLoadError(reason instanceof Error ? reason.message : "Documents could not be loaded."); } })(); return () => { active = false; }; }, [listCached, syncDrive]);
  const types = useMemo(() => [...new Set((result?.documents || []).map((item) => item.documentType))].sort(), [result]);
  const documents = useMemo(() => { const term = search.trim().toLowerCase(); return (result?.documents || []).filter((item) => (filter === "all" || item.documentType === filter) && (!term || [item.fileName, item.reference, item.estimateRef, item.projectName, item.supplierName, item.folder].some((value) => String(value || "").toLowerCase().includes(term)))); }, [result, filter, search]);
  if (loadError) return <div className="ui-status ui-status--error" role="alert">{loadError}</div>;
  if (!result) return <div className="ui-empty-state ui-loading">Loading canonical documents…</div>;
  const syncLabel = syncing ? "Syncing…" : syncError ? "Sync failed — showing cached files" : result.sync.lastSuccessAt ? `Synced ${new Date(result.sync.lastSuccessAt).toLocaleString("en-GB")}` : "Drive not synced yet";
  const title = estimateId ? "Estimate Files / Documents" : projectId ? "Project Files" : enquiryId ? "Enquiry Files" : "Client Files";
  return <section className="canonical-documents" aria-label="Canonical commercial documents" data-document-scope={estimateId ? "estimate" : projectId ? "project" : enquiryId ? "enquiry" : "client"}>
    <header><div><h3>{title}</h3><p>One provider-neutral view of cached QuoteSuite evidence and discovered cloud files. Provider IDs remain authoritative if folders or files are renamed.</p></div><div className="canonical-documents__header-actions"><div className="canonical-documents__summary"><span className="ui-status ui-status--muted">{documents.length} document{documents.length === 1 ? "" : "s"}</span><span className="ui-status ui-status--muted">{result.folders.length} linked folder{result.folders.length === 1 ? "" : "s"}</span><span className={`ui-status ${syncError ? "ui-status--warning" : "ui-status--muted"}`} role="status" data-sync-state={syncing ? "syncing" : syncError ? "failed" : "ready"}>{syncLabel}</span></div><button type="button" className="ui-button ui-button--ghost" disabled={syncing} onClick={() => void refresh()}>↻ Sync Drive</button></div></header>
    {syncError ? <p className="canonical-documents__sync-error" role="alert">{syncError}</p> : null}
    <div className="canonical-documents__filters"><label>Document type<select className="ui-input" value={filter} onChange={(event) => setFilter(event.currentTarget.value)}><option value="all">All documents</option>{types.map((type) => <option key={type} value={type}>{label(type)}</option>)}</select></label><label>Search<input className="ui-input" value={search} onChange={(event) => setSearch(event.currentTarget.value)} placeholder="File, project, estimate or supplier"/></label></div>
    {documents.length ? <div className="canonical-documents__table-wrap"><table><thead><tr><th>File</th><th>Project / Estimate</th><th>Type / Supplier</th><th>Revision</th><th>Provider / Folder</th><th>Modified</th><th>Actions</th></tr></thead><tbody>{documents.map((item) => <tr key={item.id} className={item.removedAt ? "canonical-documents__row--removed" : undefined}><td data-label="File"><strong>{item.fileName}</strong><small>{item.reference}</small></td><td data-label="Project / Estimate">{item.projectName || "—"}<small>{item.estimateRef}</small></td><td data-label="Type / Supplier">{label(item.documentType)}<small>{item.supplierName || "—"}</small></td><td data-label="Revision">{item.revision}<small>{label(item.status)}</small></td><td data-label="Provider / Folder">{providerLabel(item.provider)}<small>{item.folder}{item.providerFileId ? " · Provider file linked" : ""}</small></td><td data-label="Modified">{new Date(item.modifiedAt).toLocaleDateString("en-GB")}</td><td data-label="Actions"><div className="ui-action-row">{item.downloadUrl ? <a className="ui-button ui-button--ghost" href={documentRecordsApi.downloadUrl(item.downloadUrl)}>Open document</a> : item.openUrl ? <a className="ui-button ui-button--ghost" href={item.openUrl} target="_blank" rel="noreferrer">Open in Drive</a> : <span className="ui-status ui-status--muted">Evidence only</span>}</div></td></tr>)}</tbody></table></div> : <div className="ui-empty-state">No cached documents match this context. QuoteSuite will keep this view available while Drive refreshes.</div>}
    {result.folders.length ? <details><summary>Discovered project folders ({result.folders.length})</summary><div className="canonical-documents__folders">{result.folders.map((folder) => <span className="ui-chip" title={`Provider folder ID: ${folder.providerFolderId}`} key={folder.id}>{folder.estimateRef} · {folder.folderPath || folder.name}{folder.removedAt ? " · no longer present" : ""}</span>)}</div></details> : null}
  </section>;
}
