// Auto-generated by QuoteSync Phase 4C extraction patch.
// Seed/demo clients moved out of src/App.tsx (no logic changes).
import * as Models from "../../models/types";
import type { Client } from "../../models/types";
export const DEFAULT_CUSTOMER_ADDRESS = ["4 Glebe Road", "Cowdenbeath", "Fife", "KY4 9FA"].join("\n");

export function makeDefaultClients(opts: { uid: () => string; nextClientRef: (n: number) => string }): Client[]  {
  return [
    {
      id: Models.asClientId(opts.uid()),
      type: "Business",
      clientRef: opts.nextClientRef(1),
      clientName: "Ecofenster Ltd",
      businessName: "Ecofenster Ltd",
      contactPerson: "",
      email: "",
      mobile: "07882 809 453",
      home: "",
      projectName: "",
      projectAddress: DEFAULT_CUSTOMER_ADDRESS,
      invoiceAddress: DEFAULT_CUSTOMER_ADDRESS,
      estimates: [],
    },
    {
      id: Models.asClientId(opts.uid()),
      type: "Individual",
      clientRef: opts.nextClientRef(2),
      clientName: "Craig Ferguson",
      businessName: "",
      contactPerson: "",
      email: "",
      mobile: "07882 809 453",
      home: "",
      projectName: "",
      projectAddress: DEFAULT_CUSTOMER_ADDRESS,
      invoiceAddress: DEFAULT_CUSTOMER_ADDRESS,
      estimates: [],
    },
  ];
}

/* QS_DEFAULT_ESTIMATE_SEED_v1_1 */
// Auto-inject a demo estimate (with 5 positions) for seeded clients that have no estimates.
// Seed/demo only — does not affect new clients created later.
function qsSeedUid() {
  return Math.random().toString(16).slice(2) + Date.now().toString(16);
}
function qsSeedEstimateRef(n: number) {
  const y = new Date().getFullYear();
  return `${y}-90${String(n).padStart(2, "0")}`;
}
function qsMakeDemoEstimate(n: number) {
  const nowIso = new Date().toISOString();
  const positions = Array.from({ length: 5 }).map((_, i) => ({
    id: qsSeedUid(),
    ref: `W-${String(i + 1).padStart(3, "0")}`,
    name: `Demo item ${i + 1}`,
    quantity: 1,
    notes: "",
    createdAt: nowIso,
    updatedAt: nowIso,
  }));
  return {
    id: qsSeedUid(),
    estimateRef: qsSeedEstimateRef(n),
    status: "Open",
    createdAt: nowIso,
    updatedAt: nowIso,
    positions,
  };
}

// Try to locate the exported seeded array by common names.
try {
  // @ts-ignore
  if (typeof DEFAULT_CLIENTS !== "undefined" && Array.isArray(DEFAULT_CLIENTS)) {
    // @ts-ignore
    DEFAULT_CLIENTS.forEach((c: any, idx: number) => {
      if (!c.estimates || c.estimates.length === 0) c.estimates = [qsMakeDemoEstimate(idx + 1)];
    });
  }
} catch {}
try {
  // @ts-ignore
  if (typeof defaultClients !== "undefined" && Array.isArray(defaultClients)) {
    // @ts-ignore
    defaultClients.forEach((c: any, idx: number) => {
      if (!c.estimates || c.estimates.length === 0) c.estimates = [qsMakeDemoEstimate(idx + 1)];
    });
  }
} catch {}

