import { useEffect, useMemo, useState } from "react";
import { clientValidateSupplierFiles } from "../supplierQuotes/SupplierQuotesWorkspace";
import { supplierImportLabApi, type CreateLabSessionInput } from "./api/supplierImportLabApi";
import type { SupplierImportLabAttachment, SupplierImportLabAttachmentRole, SupplierImportLabSession } from "./domain/supplierImportLab.types";
import "../supplierQuotes/supplierQuotes.css";

const blank: CreateLabSessionInput = { supplierName: "", supplierCode: "", supplierQuotationNumber: "", supplierRevision: "", fullQuotationReference: "", quotationDate: "", currency: "EUR" };
const sizeLabel = (bytes: number) => `${(bytes / 1024 / 1024).toFixed(2)} MB`;

export default function SupplierImportLabWorkspace() {
  const [sessions, setSessions] = useState<SupplierImportLabSession[]>([]); const [selectedId, setSelectedId] = useState(""); const [attachments, setAttachments] = useState<SupplierImportLabAttachment[]>([]); const [draft, setDraft] = useState<CreateLabSessionInput>(blank); const [files, setFiles] = useState<File[]>([]); const [role, setRole] = useState<SupplierImportLabAttachmentRole>("original_quote"); const [includeArchived, setIncludeArchived] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const selected = sessions.find((session) => session.id === selectedId) ?? null; const fileIssues = useMemo(() => clientValidateSupplierFiles(files), [files]);
  async function act(operation: () => Promise<void>) { setBusy(true); setMessage(""); try { await operation(); } catch (error) { setMessage(error instanceof Error ? error.message : "Import Lab operation failed."); } finally { setBusy(false); } }
  async function refreshSessions(nextSelectedId = selectedId) { const rows = await supplierImportLabApi.listSessions(includeArchived); setSessions(rows); if (nextSelectedId && rows.some((row) => row.id === nextSelectedId)) setSelectedId(nextSelectedId); else if (nextSelectedId) { setSelectedId(""); setAttachments([]); } }
  async function openSession(sessionId: string) { setSelectedId(sessionId); setAttachments(await supplierImportLabApi.listAttachments(sessionId)); }
  useEffect(() => { supplierImportLabApi.listSessions(includeArchived).then(setSessions).catch((error) => setMessage(error.message)); }, [includeArchived]);
  const field = (key: keyof CreateLabSessionInput, label: string, type = "text") => <label>{label}<input type={type} value={draft[key] || ""} onChange={(event) => setDraft((current) => ({ ...current, [key]: event.currentTarget.value }))} /></label>;
  return <section className="supplier-quotes-workspace" data-testid="supplier-import-lab-workspace"><div><h3>Supplier Quote Import (Beta)</h3><p>Standalone Admin development tool. Sessions are not linked to an estimate, and promotion is not yet available.</p></div>
    <form className="supplier-import-lab-form" onSubmit={(event) => { event.preventDefault(); void act(async () => { const created = await supplierImportLabApi.createSession(draft); setDraft(blank); await refreshSessions(created.id); await openSession(created.id); setMessage("Import Lab session created."); }); }}><h4>New Import Session</h4>{field("supplierName", "Supplier name")}{field("supplierCode", "Supplier code (optional)")}{field("supplierQuotationNumber", "Quotation number (optional)")}{field("supplierRevision", "Revision (optional)")}{field("fullQuotationReference", "Full quotation reference (optional)")}{field("quotationDate", "Quotation date (optional)", "date")}{field("currency", "Currency")}<button disabled={busy || !draft.supplierName.trim() || !/^[A-Za-z]{3}$/.test(draft.currency)}>Save session</button></form>
    <div><div className="supplier-import-lab-heading"><h4>Import Lab sessions</h4><label><input type="checkbox" checked={includeArchived} onChange={(event) => setIncludeArchived(event.currentTarget.checked)} /> Show archived</label></div>{sessions.length === 0 ? <p>No Import Lab sessions.</p> : <table><thead><tr><th>Supplier</th><th>Quotation / reference</th><th>Revision</th><th>Currency</th><th>Status</th><th>Attachments</th><th>Created</th><th>Updated</th><th>Action</th></tr></thead><tbody>{sessions.map((session) => <tr key={session.id}><td>{session.supplierName}</td><td>{session.fullQuotationReference || session.supplierQuotationNumber || "—"}</td><td>{session.supplierRevision || "—"}</td><td>{session.currency}</td><td>{session.status}</td><td>{session.attachmentCount}</td><td>{new Date(session.createdAt).toLocaleDateString()}</td><td>{new Date(session.updatedAt).toLocaleDateString()}</td><td><button onClick={() => void act(() => openSession(session.id))}>Open</button></td></tr>)}</tbody></table>}</div>
    {selected && <div className="supplier-upload-panel"><div className="supplier-import-lab-heading"><div><h4>{selected.supplierName}</h4><p>{selected.fullQuotationReference || selected.supplierQuotationNumber || "No quotation reference"} · {selected.currency} · {selected.status}</p></div><div><button disabled={busy || !!selected.archivedAt} onClick={() => void act(async () => { await supplierImportLabApi.archiveSession(selected.id); await refreshSessions(); setMessage("Session archived."); })}>Archive</button><button disabled={busy || !!selected.archivedAt} onClick={() => void act(async () => { await supplierImportLabApi.deleteSession(selected.id); await refreshSessions(""); setAttachments([]); setMessage("Session deleted."); })}>Delete session</button></div></div><select aria-label="Attachment role" value={role} disabled={!!selected.archivedAt} onChange={(event) => setRole(event.currentTarget.value as SupplierImportLabAttachmentRole)}><option value="original_quote">Original quotation</option><option value="supporting_document">Supporting document</option><option value="supplier_drawing">Supplier drawing</option></select><input aria-label="Supplier documents" type="file" multiple accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" disabled={!!selected.archivedAt} onChange={(event) => setFiles(Array.from(event.currentTarget.files || []))} />{files.map((file) => <div key={`${file.name}-${file.size}`}>{file.name} — {sizeLabel(file.size)}</div>)}{fileIssues.map((issue) => <div className="supplier-upload-error" key={issue}>{issue}</div>)}<button disabled={busy || !!selected.archivedAt || fileIssues.length > 0} onClick={() => void act(async () => { await supplierImportLabApi.uploadAttachments(selected.id, files, role); setFiles([]); await openSession(selected.id); await refreshSessions(selected.id); setMessage("Documents uploaded."); })}>Upload selected files</button><h4>Stored attachments</h4>{attachments.length === 0 ? <p>No stored documents.</p> : <table><thead><tr><th>File</th><th>Role</th><th>Type</th><th>Size</th><th>Uploaded</th><th>Actions</th></tr></thead><tbody>{attachments.map((attachment) => <tr key={attachment.id}><td>{attachment.originalFileName}</td><td>{attachment.role}</td><td>{attachment.mediaType}</td><td>{sizeLabel(attachment.sizeBytes)}</td><td>{new Date(attachment.createdAt).toLocaleString()}</td><td><button onClick={() => void act(() => supplierImportLabApi.downloadAttachment(selected.id, attachment))}>Download</button><button disabled={!!selected.archivedAt} onClick={() => void act(async () => { await supplierImportLabApi.removeAttachment(selected.id, attachment.id); await openSession(selected.id); await refreshSessions(selected.id); })}>Remove</button></td></tr>)}</tbody></table>}</div>}
    {message && <div role="status" className="supplier-upload-status">{message}</div>}<div className="supplier-extraction-panel"><div><h4>Extraction results</h4><p>Extraction will be enabled in Stage 1E.</p></div><button disabled>Extract</button><table><thead><tr><th>Reference</th><th>Width</th><th>Height</th><th>Quantity</th><th>Unit Price</th><th>Total Price</th></tr></thead><tbody><tr><td colSpan={6}>No extracted positions.</td></tr></tbody></table></div>
    <div className="admin-warning-box">Future promotion will require explicit user review and a real estimate. It will copy evidence without mutating or deleting this lab session.</div></section>;
}
