import { useEffect, useMemo, useState } from "react";
import { clientValidateSupplierFiles } from "../supplierQuotes/SupplierQuotesWorkspace";
import { supplierImportLabApi, type CreateLabSessionInput } from "./api/supplierImportLabApi";
import type { SupplierImportLabAttachment, SupplierImportLabAttachmentRole, SupplierImportLabExtractedRow, SupplierImportLabExtractionRun, SupplierImportLabSession } from "./domain/supplierImportLab.types";
import "../supplierQuotes/supplierQuotes.css";

const blank: CreateLabSessionInput = { supplierName: "", supplierCode: "", supplierQuotationNumber: "", supplierRevision: "", fullQuotationReference: "", quotationDate: "", currency: "EUR" };
const sizeLabel = (bytes: number) => `${(bytes / 1024).toFixed(1)} KB`;
const isDocumentFormattingWarning = (warning: string) => /w:tblPrEx|image\/x-emf/i.test(warning);

export default function SupplierImportLabWorkspace() {
  const [sessions, setSessions] = useState<SupplierImportLabSession[]>([]); const [selectedId, setSelectedId] = useState(""); const [attachments, setAttachments] = useState<SupplierImportLabAttachment[]>([]); const [runs, setRuns] = useState<SupplierImportLabExtractionRun[]>([]); const [rows, setRows] = useState<SupplierImportLabExtractedRow[]>([]); const [draft, setDraft] = useState<CreateLabSessionInput>(blank); const [files, setFiles] = useState<File[]>([]); const [role, setRole] = useState<SupplierImportLabAttachmentRole>("original_quote"); const [includeArchived, setIncludeArchived] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const selected = sessions.find((session) => session.id === selectedId) ?? null; const selectedRun = runs.find((run) => run.selected) ?? null; const fileIssues = useMemo(() => clientValidateSupplierFiles(files), [files]);
  const technicalFormattingWarnings = selectedRun?.warnings.filter(isDocumentFormattingWarning) ?? [];
  const commercialWarnings = selectedRun?.warnings.filter((warning) => !isDocumentFormattingWarning(warning)) ?? [];
  async function act(operation: () => Promise<void>) { setBusy(true); setMessage(""); try { await operation(); } catch (error) { setMessage(error instanceof Error ? error.message : "Import Lab operation failed."); } finally { setBusy(false); } }
  async function refreshSessions(nextSelectedId = selectedId) { const values = await supplierImportLabApi.listSessions(includeArchived); setSessions(values); if (nextSelectedId && values.some((item) => item.id === nextSelectedId)) setSelectedId(nextSelectedId); }
  async function openSession(sessionId: string) { setSelectedId(sessionId); const [stored, history] = await Promise.all([supplierImportLabApi.listAttachments(sessionId), supplierImportLabApi.listExtractionRuns(sessionId)]); setAttachments(stored); setRuns(history); const active = history.find((run) => run.selected); setRows(active ? await supplierImportLabApi.listExtractedRows(sessionId, active.id) : []); }
  useEffect(() => { supplierImportLabApi.listSessions(includeArchived).then(setSessions).catch((error) => setMessage(error.message)); }, [includeArchived]);
  const field = (key: keyof CreateLabSessionInput, label: string, type = "text") => <label>{label}<input type={type} value={draft[key] || ""} onChange={(event) => setDraft((current) => ({ ...current, [key]: event.currentTarget.value }))} /></label>;
  async function extract(attachment: SupplierImportLabAttachment) { await supplierImportLabApi.extractAttachment(selectedId, attachment.id); await openSession(selectedId); await refreshSessions(selectedId); setMessage("Commercial extraction completed. Review warnings and values before use."); }
  async function selectRun(run: SupplierImportLabExtractionRun) { await supplierImportLabApi.selectExtractionRun(selectedId, run.id); await openSession(selectedId); }
  async function acceptQuotationProposal() { if (!selected || !selectedRun) return; const proposal = selectedRun.quotationProposal; await supplierImportLabApi.updateSession(selected.id, { supplierQuotationNumber: selected.supplierQuotationNumber || proposal.supplierQuotationNumber || undefined, supplierRevision: selected.supplierRevision || proposal.supplierRevision || undefined, fullQuotationReference: selected.fullQuotationReference || proposal.fullQuotationReference || undefined }); await refreshSessions(selected.id); setMessage("Blank quotation metadata fields were filled from extraction; existing values were preserved."); }
  async function saveRow(row: SupplierImportLabExtractedRow, form: HTMLFormElement) { const data = new FormData(form); await supplierImportLabApi.correctExtractedRow(selectedId, row.id, { displayReference: String(data.get("displayReference") || ""), widthMm: Number(data.get("widthMm")), heightMm: Number(data.get("heightMm")), quantity: Number(data.get("quantity")), unitPrice: String(data.get("unitPrice") || ""), totalPrice: String(data.get("totalPrice") || "") }); await openSession(selectedId); setMessage("Correction saved; original extracted evidence was retained."); }
  return <section className="supplier-quotes-workspace" data-testid="supplier-import-lab-workspace"><div><h3>Supplier Quote Import (Beta)</h3><p>Standalone Admin development tool. It is not linked to an estimate. Extracted commercial fields require review; promotion is unavailable.</p></div>
    <form className="supplier-import-lab-form" onSubmit={(event) => { event.preventDefault(); void act(async () => { const created = await supplierImportLabApi.createSession(draft); setDraft(blank); await refreshSessions(created.id); await openSession(created.id); }); }}><h4>New Import Session</h4>{field("supplierName", "Supplier name")}{field("supplierCode", "Supplier code (optional)")}{field("supplierQuotationNumber", "Quotation number (optional)")}{field("supplierRevision", "Revision (optional)")}{field("fullQuotationReference", "Full quotation reference (optional)")}{field("quotationDate", "Quotation date (optional)", "date")}{field("currency", "Currency")}<button disabled={busy || !draft.supplierName.trim() || !/^[A-Za-z]{3}$/.test(draft.currency)}>Save session</button></form>
    <div><div className="supplier-import-lab-heading"><h4>Import Lab sessions</h4><label><input type="checkbox" checked={includeArchived} onChange={(event) => setIncludeArchived(event.currentTarget.checked)} /> Show archived</label></div>{sessions.length === 0 ? <p>No Import Lab sessions.</p> : <table><thead><tr><th>Supplier</th><th>Quotation / reference</th><th>Revision</th><th>Currency</th><th>Status</th><th>Attachments</th><th>Created</th><th>Updated</th><th>Action</th></tr></thead><tbody>{sessions.map((session) => <tr key={session.id}><td>{session.supplierName}</td><td>{session.fullQuotationReference || session.supplierQuotationNumber || "—"}</td><td>{session.supplierRevision || "—"}</td><td>{session.currency}</td><td>{session.status}</td><td>{session.attachmentCount}</td><td>{new Date(session.createdAt).toLocaleDateString()}</td><td>{new Date(session.updatedAt).toLocaleDateString()}</td><td><button onClick={() => void act(() => openSession(session.id))}>Open</button></td></tr>)}</tbody></table>}</div>
    {selected && <div className="supplier-upload-panel"><div className="supplier-import-lab-heading"><div><h4>{selected.supplierName}</h4><p>Quotation number: <strong>{selected.supplierQuotationNumber || "—"}</strong> · Revision: <strong>{selected.supplierRevision || "—"}</strong> · Full reference: <strong>{selected.fullQuotationReference || "—"}</strong> · {selected.currency} · {selected.status}</p></div><div><button disabled={busy || !!selected.archivedAt} onClick={() => void act(async () => { await supplierImportLabApi.archiveSession(selected.id); await refreshSessions(selected.id); })}>Archive</button><button disabled={busy || !!selected.archivedAt || runs.length > 0} onClick={() => void act(async () => { await supplierImportLabApi.deleteSession(selected.id); setSelectedId(""); await refreshSessions(""); })}>Delete session</button></div></div>
      <select aria-label="Attachment role" value={role} disabled={!!selected.archivedAt} onChange={(event) => setRole(event.currentTarget.value as SupplierImportLabAttachmentRole)}><option value="original_quote">Original quotation</option><option value="supporting_document">Supporting document</option><option value="supplier_drawing">Supplier drawing</option></select><input aria-label="Supplier documents" type="file" multiple accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" disabled={!!selected.archivedAt} onChange={(event) => setFiles(Array.from(event.currentTarget.files || []))} />{files.map((file) => <div key={`${file.name}-${file.size}`}>{file.name} — {sizeLabel(file.size)}</div>)}{fileIssues.map((issue) => <div className="supplier-upload-error" key={issue}>{issue}</div>)}<button disabled={busy || !!selected.archivedAt || !files.length || fileIssues.length > 0} onClick={() => void act(async () => { await supplierImportLabApi.uploadAttachments(selected.id, files, role); setFiles([]); await openSession(selected.id); await refreshSessions(selected.id); })}>Upload selected files</button>
      <h4>Stored attachments</h4>{attachments.length === 0 ? <p>No stored documents.</p> : <table><thead><tr><th>File</th><th>Role</th><th>Type</th><th>Size</th><th>Uploaded</th><th>Actions</th></tr></thead><tbody>{attachments.map((attachment) => <tr key={attachment.id}><td>{attachment.originalFileName}</td><td>{attachment.role}</td><td>{attachment.mediaType}</td><td>{sizeLabel(attachment.sizeBytes)}</td><td>{new Date(attachment.createdAt).toLocaleString()}</td><td><button onClick={() => void act(() => supplierImportLabApi.downloadAttachment(selected.id, attachment))}>Download</button><button disabled={busy || !attachment.parserEligible || !!selected.archivedAt} onClick={() => void act(() => extract(attachment))}>{busy ? "Processing…" : "Extract"}</button><button disabled={!!selected.archivedAt || runs.some((run) => run.attachmentId === attachment.id)} onClick={() => void act(async () => { await supplierImportLabApi.removeAttachment(selected.id, attachment.id); await openSession(selected.id); })}>Remove</button></td></tr>)}</tbody></table>}
      {runs.length > 0 && <div><h4>Extraction history</h4>{runs.map((run) => <button key={run.id} disabled={!run.status.startsWith("completed") || run.selected} onClick={() => void act(() => selectRun(run))}>{run.status} · {new Date(run.createdAt).toLocaleString()} {run.selected ? "(selected)" : ""}</button>)}</div>}
    </div>}
    {message && <div role="status" className="supplier-upload-status">{message}</div>}
    <div className="supplier-extraction-panel"><div><h4>Extraction results</h4>{selectedRun?.quotationProposal.fullQuotationReference && <p>Extracted quotation proposal: <strong>{selectedRun.quotationProposal.fullQuotationReference}</strong>. Existing session metadata was not overwritten. <button onClick={() => void act(acceptQuotationProposal)}>Fill blank metadata</button></p>}{technicalFormattingWarnings.length > 0 && <><p>Some document formatting and embedded images were ignored. Commercial data extraction completed.</p><details><summary>Technical extraction details</summary>{technicalFormattingWarnings.map((warning) => <p key={warning}>{warning}</p>)}</details></>}{commercialWarnings.map((warning) => <p key={warning} className="supplier-upload-error">{warning}</p>)}</div><table><thead><tr><th>Reference</th><th>Width</th><th>Height</th><th>Quantity</th><th>Unit Price</th><th>Total Price</th></tr></thead><tbody>{rows.length === 0 ? <tr><td colSpan={6}>No extracted positions.</td></tr> : rows.map((row) => <tr key={row.id}><td colSpan={6}><form className="supplier-extracted-row" onSubmit={(event) => { event.preventDefault(); void act(() => saveRow(row, event.currentTarget)); }}><input aria-label="Reference" name="displayReference" defaultValue={row.displayReference || ""} /><input aria-label="Width" name="widthMm" type="number" defaultValue={row.widthMm || ""} /><input aria-label="Height" name="heightMm" type="number" defaultValue={row.heightMm || ""} /><input aria-label="Quantity" name="quantity" type="number" defaultValue={row.quantity || ""} /><input aria-label="Unit Price" name="unitPrice" defaultValue={row.unitPrice || ""} /><input aria-label="Total Price" name="totalPrice" defaultValue={row.totalPrice || ""} /><button>Save corrections</button>{row.status === "corrected" && <small>Corrected</small>}{row.warnings.map((warning) => <small key={warning}>{warning}</small>)}</form></td></tr>)}</tbody></table></div>
    <div className="admin-warning-box">Grouped references remain one extracted row. Extraction does not create estimates, canonical positions, calculator entries, descriptions, specifications, or recognition results.</div></section>;
}
