import { useEffect, useMemo, useState } from "react";
import { clientValidateSupplierFiles } from "../supplierQuotes/SupplierQuotesWorkspace";
import { supplierImportLabApi, type CreateLabSessionInput } from "./api/supplierImportLabApi";
import { changedFields, exactTotalMatches, friendlyRunStatus, rowToDraft, validateRowDraft, type ReviewField, type ReviewIssue } from "./domain/supplierImportLabReview";
import type { SupplierImportLabAdditionalCostItem, SupplierImportLabAttachment, SupplierImportLabAttachmentRole, SupplierImportLabCommercialSummary, SupplierImportLabExtractedRow, SupplierImportLabExtractionRun, SupplierImportLabRowDraft, SupplierImportLabSession } from "./domain/supplierImportLab.types";
import "../supplierQuotes/supplierQuotes.css";

const blank: CreateLabSessionInput = { supplierName: "", supplierCode: "", supplierQuotationNumber: "", supplierRevision: "", fullQuotationReference: "", quotationDate: "", currency: "EUR" };
const sizeLabel = (bytes: number) => `${(bytes / 1024).toFixed(1)} KB`;
const isDocumentFormattingWarning = (warning: string) => /w:tblPrEx|image\/x-emf/i.test(warning);
const dateTime = (value: string | null) => value ? new Date(value).toLocaleString() : "—";

export default function SupplierImportLabWorkspace() {
  const [sessions, setSessions] = useState<SupplierImportLabSession[]>([]);
  const [selectedId, setSelectedId] = useState("");
  const [attachments, setAttachments] = useState<SupplierImportLabAttachment[]>([]);
  const [runs, setRuns] = useState<SupplierImportLabExtractionRun[]>([]);
  const [rows, setRows] = useState<SupplierImportLabExtractedRow[]>([]);
  const [rowDrafts, setRowDrafts] = useState<Record<string, SupplierImportLabRowDraft>>({});
  const [rowIssues, setRowIssues] = useState<Record<string, ReviewIssue[]>>({});
  const [commercialSummary, setCommercialSummary] = useState<SupplierImportLabCommercialSummary | null>(null);
  const [additionalCosts, setAdditionalCosts] = useState<SupplierImportLabAdditionalCostItem[]>([]);
  const [summaryDraft, setSummaryDraft] = useState<Record<string, string>>({});
  const [costDrafts, setCostDrafts] = useState<Record<string, SupplierImportLabAdditionalCostItem>>({});
  const [draft, setDraft] = useState<CreateLabSessionInput>(blank);
  const [files, setFiles] = useState<File[]>([]);
  const [role, setRole] = useState<SupplierImportLabAttachmentRole>("original_quote");
  const [includeArchived, setIncludeArchived] = useState(false);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const selected = sessions.find((session) => session.id === selectedId) ?? null;
  const selectedRun = runs.find((run) => run.selected) ?? null;
  const fileIssues = useMemo(() => clientValidateSupplierFiles(files), [files]);
  const dirtyRowIds = useMemo(() => rows.filter((row) => rowDrafts[row.id] && changedFields(row, rowDrafts[row.id]).length > 0).map((row) => row.id), [rowDrafts, rows]);
  const summaryDirty = Boolean(commercialSummary && ["totalQuantity","totalAreaSquareMetres","productSubtotal","additionalItemsSubtotal","deliveryTotal","vatTotal","finalSupplierTotal","averageUValue","totalWeightKg","closingNotes"].some((field) => summaryDraft[field] !== String(commercialSummary[field as keyof SupplierImportLabCommercialSummary] ?? "")));
  const costDirtyIds = additionalCosts.filter((item) => JSON.stringify(costDrafts[item.id]) !== JSON.stringify(item)).map((item) => item.id);
  const dirty = dirtyRowIds.length > 0 || summaryDirty || costDirtyIds.length > 0;
  const selectedRowCount = rows.filter((row) => rowDrafts[row.id]?.selectedForFutureUse && row.status !== "rejected").length;
  const technicalFormattingWarnings = selectedRun?.warnings.filter(isDocumentFormattingWarning) ?? [];
  const commercialWarnings = selectedRun?.warnings.filter((warning) => !isDocumentFormattingWarning(warning)) ?? [];

  useEffect(() => { supplierImportLabApi.listSessions(includeArchived).then(setSessions).catch((error) => setMessage(error.message)); }, [includeArchived]);
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = ""; } }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty]);

  async function act(operation: () => Promise<void>) { setBusy(true); setMessage(""); try { await operation(); } catch (error) { setMessage(error instanceof Error ? error.message : "Import Lab operation failed."); } finally { setBusy(false); } }
  async function refreshSessions(nextSelectedId = selectedId) { const values = await supplierImportLabApi.listSessions(includeArchived); setSessions(values); if (nextSelectedId && values.some((item) => item.id === nextSelectedId)) setSelectedId(nextSelectedId); }
  function installSummary(summary: SupplierImportLabCommercialSummary | null, costs: SupplierImportLabAdditionalCostItem[]) { setCommercialSummary(summary); setAdditionalCosts(costs); setSummaryDraft(summary ? Object.fromEntries(["totalQuantity","totalAreaSquareMetres","productSubtotal","additionalItemsSubtotal","deliveryTotal","vatTotal","finalSupplierTotal","averageUValue","totalWeightKg","closingNotes"].map((field) => [field, String(summary[field as keyof SupplierImportLabCommercialSummary] ?? "")])) : {}); setCostDrafts(Object.fromEntries(costs.map((item) => [item.id, item]))); }
  function installRows(nextRows: SupplierImportLabExtractedRow[]) { setRows(nextRows); setRowDrafts(Object.fromEntries(nextRows.map((row) => [row.id, rowToDraft(row)]))); setRowIssues({}); }
  async function loadSession(sessionId: string) { setSelectedId(sessionId); const [stored, history] = await Promise.all([supplierImportLabApi.listAttachments(sessionId), supplierImportLabApi.listExtractionRuns(sessionId)]); setAttachments(stored); setRuns(history); const active = history.find((run) => run.selected); if (active) { const [nextRows, summaryResult] = await Promise.all([supplierImportLabApi.listExtractedRows(sessionId, active.id), supplierImportLabApi.getCommercialSummary(sessionId, active.id)]); installRows(nextRows); installSummary(summaryResult.summary, summaryResult.additionalItems); } else { installRows([]); installSummary(null, []); } }
  function permitDiscard(action: string) { return !dirty || window.confirm(`You have unsaved commercial review changes. Discard those edits and ${action}?`); }
  function discardChanges() { installRows(rows); setMessage("Unsaved changes discarded."); }
  function updateDraft(rowId: string, field: ReviewField, value: string | boolean) { setRowDrafts((current) => ({ ...current, [rowId]: { ...current[rowId], [field]: value } })); setRowIssues((current) => ({ ...current, [rowId]: (current[rowId] ?? []).filter((issue) => issue.field !== field) })); }
  async function saveAll() { const dirtyDrafts = dirtyRowIds.map((id) => rowDrafts[id]); const issues = Object.fromEntries(dirtyDrafts.map((item) => [item.rowId, validateRowDraft(item, rows.find((row) => row.id === item.rowId)?.status)]).filter(([, value]) => value.length > 0)); setRowIssues(issues); if (Object.keys(issues).length) { setMessage("Correct the highlighted fields before saving. No rows were updated."); return; } const result = await supplierImportLabApi.bulkCorrectExtractedRows(selectedId, dirtyDrafts); const updated = new Map(result.rows.map((row) => [row.id, row])); installRows(rows.map((row) => updated.get(row.id) ?? row)); await refreshSessions(selectedId); setMessage(`${dirtyDrafts.length} corrected row${dirtyDrafts.length === 1 ? "" : "s"} saved. Original extraction evidence was retained.`); }
  async function extract(attachment: SupplierImportLabAttachment) { if (!permitDiscard("rerun extraction")) return; await supplierImportLabApi.extractAttachment(selectedId, attachment.id); await loadSession(selectedId); await refreshSessions(selectedId); setMessage("Commercial extraction completed. Review warnings and values before use."); }
  async function selectRun(run: SupplierImportLabExtractionRun) { if (!permitDiscard("switch extraction runs")) return; await supplierImportLabApi.selectExtractionRun(selectedId, run.id); await loadSession(selectedId); }
  async function acceptQuotationProposal() { if (!selected || !selectedRun) return; const proposal = selectedRun.quotationProposal; await supplierImportLabApi.updateSession(selected.id, { supplierQuotationNumber: selected.supplierQuotationNumber || proposal.supplierQuotationNumber || undefined, supplierRevision: selected.supplierRevision || proposal.supplierRevision || undefined, fullQuotationReference: selected.fullQuotationReference || proposal.fullQuotationReference || undefined }); await refreshSessions(selected.id); setMessage("Blank quotation metadata fields were filled from extraction; existing values were preserved."); }
  const field = (key: keyof CreateLabSessionInput, label: string, type = "text") => <label>{label}<input type={type} value={draft[key] || ""} onChange={(event) => setDraft((current) => ({ ...current, [key]: event.currentTarget.value }))} /></label>;
  const setAllSelected = (value: boolean) => setRowDrafts((current) => Object.fromEntries(rows.map((row) => [row.id, { ...current[row.id], selectedForFutureUse: row.status === "rejected" ? false : value }])));
  const setAllCostsSelected = (value: boolean) => setCostDrafts((current) => Object.fromEntries(additionalCosts.map((item) => [item.id, { ...current[item.id], selectedForFutureUse: item.status === "rejected" ? false : value }])));
  async function saveSummary() { if (!commercialSummary) return; const decimal = /^(?:0|[1-9]\d*)(?:\.\d+)?$/; const invalid = Object.entries(summaryDraft).filter(([field,value]) => field !== "closingNotes" && value && !decimal.test(value)); if (invalid.length) { setMessage("Summary values must be plain non-negative decimals or blank. No values were saved."); return; } const saved = await supplierImportLabApi.correctCommercialSummary(selectedId, commercialSummary.id, summaryDraft); installSummary(saved, additionalCosts); await refreshSessions(selectedId); setMessage("Supplier summary corrections saved. Original supplier evidence remains unchanged."); }
  async function saveAdditionalCosts() { const changed = costDirtyIds.map((id) => costDrafts[id]); const result = await supplierImportLabApi.bulkCorrectAdditionalCosts(selectedId, changed.map((item) => ({ itemId: item.id, category: item.category, normalizedLabel: item.normalizedLabel, quantity: item.quantity, quantityUnit: item.quantityUnit, unitPrice: item.unitPrice, totalPrice: item.totalPrice, selectedForFutureUse: item.selectedForFutureUse }))); installSummary(commercialSummary, additionalCosts.map((item) => result.items.find((updated) => updated.id === item.id) ?? item)); await refreshSessions(selectedId); setMessage("Additional supplier costs saved atomically. Original supplier evidence remains unchanged."); }

  return <section className="supplier-quotes-workspace" data-testid="supplier-import-lab-workspace">
    <div><h3>Supplier Quote Import (Beta)</h3><p>Standalone Admin development tool. It is not linked to an estimate. Selection marks rows for possible future use only; it is not approval or promotion.</p></div>
    <form className="supplier-import-lab-form" onSubmit={(event) => { event.preventDefault(); void act(async () => { const created = await supplierImportLabApi.createSession(draft); setDraft(blank); await refreshSessions(created.id); await loadSession(created.id); }); }}><h4>New Import Session</h4>{field("supplierName", "Supplier name")}{field("supplierCode", "Supplier code (optional)")}{field("supplierQuotationNumber", "Quotation number (optional)")}{field("supplierRevision", "Revision (optional)")}{field("fullQuotationReference", "Full quotation reference (optional)")}{field("quotationDate", "Quotation date (optional)", "date")}{field("currency", "Currency")}<button disabled={busy || !draft.supplierName.trim() || !/^[A-Za-z]{3}$/.test(draft.currency)}>Save session</button></form>
    <div className="supplier-review-scroll"><div className="supplier-import-lab-heading"><h4>Import Lab sessions</h4><label><input type="checkbox" checked={includeArchived} onChange={(event) => setIncludeArchived(event.currentTarget.checked)} /> Show archived</label></div>{sessions.length === 0 ? <p>No Import Lab sessions.</p> : <table><thead><tr><th>Supplier</th><th>Quotation / reference</th><th>Revision</th><th>Currency</th><th>Status</th><th>Attachments</th><th>Rows selected</th><th>Latest extraction</th><th>Updated</th><th>Action</th></tr></thead><tbody>{sessions.map((session) => <tr key={session.id}><td>{session.supplierName}</td><td>{session.fullQuotationReference || session.supplierQuotationNumber || "—"}</td><td>{session.supplierRevision || "—"}</td><td>{session.currency}</td><td>{session.status}</td><td>{session.attachmentCount}</td><td>{session.selectedRowCount} / {session.extractedRowCount}</td><td>{session.latestExtractionStatus ? friendlyRunStatus(session.latestExtractionStatus) : "—"}<br/><small>{dateTime(session.lastExtractionAt)}</small></td><td>{new Date(session.updatedAt).toLocaleDateString()}</td><td><button onClick={() => { if (permitDiscard("open another session")) void act(() => loadSession(session.id)); }}>Open</button></td></tr>)}</tbody></table>}</div>
    {selected && <div className="supplier-upload-panel"><div className="supplier-import-lab-heading"><div><h4>{selected.supplierName}</h4><p>Quotation <strong>{selected.supplierQuotationNumber || "—"}</strong> · Revision <strong>{selected.supplierRevision || "—"}</strong> · Full reference <strong>{selected.fullQuotationReference || "—"}</strong> · {selected.currency}</p><p>Status: <strong>{selected.status}</strong> · Attachments: <strong>{attachments.length}</strong> · Active rows: <strong>{rows.length}</strong> · Selected: <strong>{selectedRowCount}</strong> · Last extraction: <strong>{dateTime(selectedRun?.completedAt ?? null)}</strong></p></div><div><button disabled={busy || !!selected.archivedAt} onClick={() => { if (permitDiscard("archive this session")) void act(async () => { await supplierImportLabApi.archiveSession(selected.id); await refreshSessions(selected.id); }); }}>Archive</button><button disabled={busy || !!selected.archivedAt || runs.length > 0} onClick={() => { if (permitDiscard("delete this session")) void act(async () => { await supplierImportLabApi.deleteSession(selected.id); setSelectedId(""); await refreshSessions(""); }); }}>Delete session</button></div></div>
      <select aria-label="Attachment role" value={role} disabled={!!selected.archivedAt} onChange={(event) => setRole(event.currentTarget.value as SupplierImportLabAttachmentRole)}><option value="original_quote">Original quotation</option><option value="supporting_document">Supporting document</option><option value="supplier_drawing">Supplier drawing</option></select><input aria-label="Supplier documents" type="file" multiple accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" disabled={!!selected.archivedAt} onChange={(event) => setFiles(Array.from(event.currentTarget.files || []))} />{files.map((file) => <div key={`${file.name}-${file.size}`}>{file.name} — {sizeLabel(file.size)}</div>)}{fileIssues.map((issue) => <div className="supplier-upload-error" key={issue}>{issue}</div>)}<button disabled={busy || !!selected.archivedAt || !files.length || fileIssues.length > 0} onClick={() => void act(async () => { await supplierImportLabApi.uploadAttachments(selected.id, files, role); setFiles([]); await loadSession(selected.id); await refreshSessions(selected.id); })}>Upload selected files</button>
      <h4>Stored attachments</h4>{attachments.length === 0 ? <p>No stored documents.</p> : <table><thead><tr><th>File</th><th>Role</th><th>Type</th><th>Size</th><th>Uploaded</th><th>Actions</th></tr></thead><tbody>{attachments.map((attachment) => <tr key={attachment.id}><td>{attachment.originalFileName}</td><td>{attachment.role}</td><td>{attachment.mediaType}</td><td>{sizeLabel(attachment.sizeBytes)}</td><td>{new Date(attachment.createdAt).toLocaleString()}</td><td><button onClick={() => void act(() => supplierImportLabApi.downloadAttachment(selected.id, attachment))}>Download</button><button disabled={busy || !attachment.parserEligible || !!selected.archivedAt} onClick={() => void act(() => extract(attachment))}>{busy ? "Processing…" : "Extract"}</button><button disabled={!!selected.archivedAt || runs.some((run) => run.attachmentId === attachment.id)} onClick={() => void act(async () => { await supplierImportLabApi.removeAttachment(selected.id, attachment.id); await loadSession(selected.id); })}>Remove</button></td></tr>)}</tbody></table>}
      {runs.length > 0 && <div><h4>Extraction history</h4><div className="supplier-extraction-history">{runs.map((run) => <article className={run.selected ? "is-current" : ""} key={run.id}><strong>{friendlyRunStatus(run.status)}</strong><span>{run.attachmentFileName || "Attachment"}</span><span>{dateTime(run.completedAt || run.startedAt)}</span><span>{run.rowCount} positions · {run.additionalCostCount} additional costs · {run.warningCount} warnings</span><span>Product {run.productSubtotal ?? "—"} · Delivery {run.deliveryTotal ?? "—"} · Final {run.finalSupplierTotal ?? "—"}</span><span>Summary: {run.summaryStatus ?? "not found"} · Reconciliation: {run.reconciliationStatus ?? "—"}</span><small>{run.extractorName} {run.extractorVersion} · parser {run.fieldParserVersion}</small><button disabled={!run.status.startsWith("completed") || run.selected} onClick={() => void act(() => selectRun(run))}>{run.selected ? "Current run" : "View run"}</button></article>)}</div></div>}
    </div>}
    {message && <div role="status" className="supplier-upload-status">{message}</div>}
    <div className="supplier-extraction-panel"><div><div className="supplier-import-lab-heading"><h4>Extraction results — {rows.length} rows</h4>{rows.length > 0 && <div className="supplier-review-actions"><button onClick={() => setAllSelected(true)}>Select All</button><button onClick={() => setAllSelected(false)}>Clear All</button><button disabled={busy || dirtyRowIds.length === 0} onClick={() => void act(saveAll)}>Save All Corrections</button><button disabled={busy || dirtyRowIds.length === 0} onClick={discardChanges}>Discard Unsaved Changes</button><strong>{dirtyRowIds.length} rows changed</strong></div>}</div>{selectedRun?.quotationProposal.fullQuotationReference && <p>Extracted quotation proposal: <strong>{selectedRun.quotationProposal.fullQuotationReference}</strong>. Existing session metadata was not overwritten. <button onClick={() => void act(acceptQuotationProposal)}>Fill blank metadata</button></p>}{technicalFormattingWarnings.length > 0 && <><p className="supplier-warning-info">Some document formatting and embedded images were ignored. Commercial data extraction completed.</p><details><summary>Technical extraction details</summary>{technicalFormattingWarnings.map((warning) => <p key={warning}>{warning}</p>)}</details></>}{commercialWarnings.map((warning) => <p key={warning} className="supplier-upload-error">{warning}</p>)}</div>
      <div className="supplier-review-scroll"><table className="supplier-review-table"><thead><tr><th>Select</th><th>Reference</th><th>Width</th><th>Height</th><th>Quantity</th><th>Unit Price</th><th>Total Price</th><th>Review</th></tr></thead><tbody>{rows.length === 0 ? <tr><td colSpan={8}>No extracted positions.</td></tr> : rows.map((row) => { const rowDraft = rowDrafts[row.id] ?? rowToDraft(row); const changed = new Set(changedFields(row, rowDraft)); const issues = rowIssues[row.id] ?? []; const issueFor = (field: ReviewField) => issues.find((issue) => issue.field === field); const input = (field: Exclude<ReviewField,"selectedForFutureUse">, label: string, type = "text") => <div><input aria-label={`${label} ${row.ordinal + 1}`} className={`${changed.has(field) ? "is-dirty" : ""} ${issueFor(field) ? "is-invalid" : ""}`} type={type} value={rowDraft[field]} onChange={(event) => updateDraft(row.id, field, event.currentTarget.value)} />{issueFor(field) && <small className="supplier-upload-error">{issueFor(field)?.message}</small>}</div>; const liveMismatch = !exactTotalMatches(rowDraft); return <tr className={`${changed.size ? "is-dirty" : ""} ${issues.length ? "is-invalid" : ""}`} key={row.id}><td><input aria-label={`Select ${row.displayReference || `row ${row.ordinal + 1}`}`} type="checkbox" checked={rowDraft.selectedForFutureUse} disabled={row.status === "rejected"} onChange={(event) => updateDraft(row.id,"selectedForFutureUse",event.currentTarget.checked)} /></td><td>{input("displayReference","Reference")}</td><td>{input("widthMm","Width","number")}</td><td>{input("heightMm","Height","number")}</td><td>{input("quantity","Quantity","number")}</td><td>{input("unitPrice","Unit Price")}</td><td>{input("totalPrice","Total Price")}</td><td>{changed.size > 0 && <small>Unsaved</small>}{row.status === "corrected" && <small>Corrected</small>}{[...row.warnings,...row.reviewWarnings].map((warning) => <small className="supplier-review-warning" key={warning}>{warning}</small>)}{liveMismatch && <small className="supplier-review-warning">Supplied total does not equal unit price × quantity.</small>}</td></tr>; })}</tbody></table></div>
    </div>
    <section className="supplier-extraction-panel"><div className="supplier-import-lab-heading"><h4>Supplier Quotation Summary</h4>{commercialSummary && <div className="supplier-review-actions"><button disabled={busy || !summaryDirty} onClick={() => void act(saveSummary)}>Save All Summary Corrections</button><button disabled={!summaryDirty} onClick={() => installSummary(commercialSummary, additionalCosts)}>Discard Unsaved Summary Changes</button></div>}</div>
      {!selectedRun ? <p>Select an extraction run to review its supplier summary.</p> : !commercialSummary ? <p>No end-of-quotation commercial summary was found. Position extraction remains available.</p> : <><div className="supplier-summary-grid">{[["totalQuantity","Total quantity"],["totalAreaSquareMetres","Total area (m²)"],["productSubtotal","Product subtotal"],["additionalItemsSubtotal","Additional items subtotal"],["deliveryTotal","Original supplier delivery"],["vatTotal","VAT"],["finalSupplierTotal","Final supplier total"],["averageUValue","Average U-value"],["totalWeightKg","Total weight (kg)"]].map(([field,label]) => <label key={field}>{label}<input aria-label={label} value={summaryDraft[field] ?? ""} onChange={(event) => setSummaryDraft((current) => ({ ...current, [field]: event.currentTarget.value }))} /></label>)}</div><p>Currency: <strong>{commercialSummary.currency || selected?.currency || "—"}</strong> · Reconciliation: <strong>{commercialSummary.reconciliation.reconciled ? "Reconciled" : "Review required"}</strong></p>{commercialSummary.warnings.map((warning) => <p className="supplier-review-warning" key={warning}>{warning}</p>)}<p className="supplier-warning-info"><strong>Original supplier delivery</strong> remains unchanged. Commercial allocation and customer-facing delivery presentation will be handled later in the Project Calculator.</p></>}
      <div className="supplier-import-lab-heading"><h4>Additional Supplier Costs — {additionalCosts.length}</h4>{additionalCosts.length > 0 && <div className="supplier-review-actions"><button onClick={() => setAllCostsSelected(true)}>Select All Additional Costs</button><button onClick={() => setAllCostsSelected(false)}>Clear All Additional Costs</button><button disabled={busy || costDirtyIds.length === 0} onClick={() => void act(saveAdditionalCosts)}>Save All Additional Cost Corrections</button><button disabled={costDirtyIds.length === 0} onClick={() => installSummary(commercialSummary, additionalCosts)}>Discard Unsaved Cost Changes</button></div>}</div>
      <div className="supplier-review-scroll"><table><thead><tr><th>Include for future use</th><th>Category</th><th>Original description</th><th>Quantity</th><th>Unit</th><th>Unit price</th><th>Total price</th><th>Warning/status</th></tr></thead><tbody>{additionalCosts.length === 0 ? <tr><td colSpan={8}>No additional supplier costs extracted.</td></tr> : additionalCosts.map((item) => { const draftItem = costDrafts[item.id] ?? item; const update = (field: keyof SupplierImportLabAdditionalCostItem, value: string | boolean) => setCostDrafts((current) => ({ ...current, [item.id]: { ...draftItem, [field]: value } })); return <tr className={costDirtyIds.includes(item.id) ? "is-dirty" : ""} key={item.id}><td><input aria-label={`Select cost ${item.ordinal + 1}`} type="checkbox" checked={draftItem.selectedForFutureUse} disabled={item.status === "rejected"} onChange={(event) => update("selectedForFutureUse", event.currentTarget.checked)} /></td><td><select value={draftItem.category} onChange={(event) => update("category", event.currentTarget.value)}>{["delivery","sill","flashing","trim","accessory","packaging","surcharge","discount","other"].map((category) => <option key={category}>{category}</option>)}</select></td><td><span className="supplier-original-evidence">{item.originalDescription}</span></td><td><input aria-label={`Cost quantity ${item.ordinal + 1}`} value={draftItem.quantity ?? ""} onChange={(event) => update("quantity", event.currentTarget.value)} /></td><td><input aria-label={`Cost unit ${item.ordinal + 1}`} value={draftItem.quantityUnit ?? ""} onChange={(event) => update("quantityUnit", event.currentTarget.value)} /></td><td><input aria-label={`Cost unit price ${item.ordinal + 1}`} value={draftItem.unitPrice ?? ""} onChange={(event) => update("unitPrice", event.currentTarget.value)} /></td><td><input aria-label={`Cost total ${item.ordinal + 1}`} value={draftItem.totalPrice ?? ""} onChange={(event) => update("totalPrice", event.currentTarget.value)} /></td><td>{item.status}{item.warnings.map((warning) => <small className="supplier-review-warning" key={warning}>{warning}</small>)}</td></tr>; })}</tbody></table></div>
      {commercialSummary?.closingNotes && <details><summary>Closing supplier notes</summary><pre className="supplier-closing-notes">{commercialSummary.closingNotes}</pre></details>}
    </section>
    <div className="admin-warning-box">Grouped references remain one review row. Selection is run-specific and does not approve, promote, or create estimate positions.</div>
  </section>;
}
