import { apiFetch, apiUrl, extractApiErrorMessage } from "../../../services/api/apiClient";
import type { SupplierImportLabAdditionalCostItem, SupplierImportLabCommercialSummary, SupplierImportLabAttachment, SupplierImportLabAttachmentRole, SupplierImportLabExtractedRow, SupplierImportLabExtractionRun, SupplierImportLabRowDraft, SupplierImportLabSession, SupplierImportLabSummaryResult } from "../domain/supplierImportLab.types";

const base = "/api/admin/supplier-import-lab/sessions";
export type CreateLabSessionInput = { supplierName: string; supplierCode?: string; supplierQuotationNumber?: string; supplierRevision?: string; fullQuotationReference?: string; quotationDate?: string; currency: string };

export const supplierImportLabApi = {
  listSessions: (includeArchived = false) => apiFetch(`${base}?include_archived=${includeArchived}`) as Promise<SupplierImportLabSession[]>,
  createSession: (input: CreateLabSessionInput) => apiFetch(base, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }) as Promise<SupplierImportLabSession>,
  updateSession: (sessionId: string, input: Partial<CreateLabSessionInput>) => apiFetch(`${base}/${encodeURIComponent(sessionId)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }) as Promise<SupplierImportLabSession>,
  archiveSession: (sessionId: string) => apiFetch(`${base}/${encodeURIComponent(sessionId)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ archive: true }) }) as Promise<SupplierImportLabSession>,
  deleteSession: (sessionId: string) => apiFetch(`${base}/${encodeURIComponent(sessionId)}`, { method: "DELETE" }),
  listAttachments: (sessionId: string) => apiFetch(`${base}/${encodeURIComponent(sessionId)}/attachments`) as Promise<SupplierImportLabAttachment[]>,
  uploadAttachments: (sessionId: string, files: readonly File[], role: SupplierImportLabAttachmentRole) => { const body = new FormData(); files.forEach((file) => body.append("files", file)); body.append("role", role); return apiFetch(`${base}/${encodeURIComponent(sessionId)}/attachments`, { method: "POST", body }) as Promise<{ attachments: SupplierImportLabAttachment[] }>; },
  removeAttachment: (sessionId: string, attachmentId: string) => apiFetch(`${base}/${encodeURIComponent(sessionId)}/attachments/${encodeURIComponent(attachmentId)}`, { method: "DELETE" }),
  downloadAttachment: async (sessionId: string, attachment: SupplierImportLabAttachment) => { const response = await fetch(apiUrl(`${base}/${encodeURIComponent(sessionId)}/attachments/${encodeURIComponent(attachment.id)}/download`)); if (!response.ok) { const body = await response.text().catch(() => ""); throw new Error(extractApiErrorMessage(response.status, body)); } const blob = await response.blob(); const url = URL.createObjectURL(blob); try { const anchor = document.createElement("a"); anchor.href = url; anchor.download = attachment.originalFileName; anchor.click(); } finally { URL.revokeObjectURL(url); } },
  extractAttachment: (sessionId: string, attachmentId: string) => apiFetch(`${base}/${encodeURIComponent(sessionId)}/attachments/${encodeURIComponent(attachmentId)}/extract`, { method: "POST" }) as Promise<SupplierImportLabExtractionRun>,
  listExtractionRuns: (sessionId: string) => apiFetch(`${base}/${encodeURIComponent(sessionId)}/extraction-runs`) as Promise<SupplierImportLabExtractionRun[]>,
  listExtractedRows: (sessionId: string, runId: string) => apiFetch(`${base}/${encodeURIComponent(sessionId)}/extraction-runs/${encodeURIComponent(runId)}/rows`) as Promise<SupplierImportLabExtractedRow[]>,
  getCommercialSummary: (sessionId: string, runId: string) => apiFetch(`${base}/${encodeURIComponent(sessionId)}/extraction-runs/${encodeURIComponent(runId)}/summary`) as Promise<SupplierImportLabSummaryResult>,
  correctCommercialSummary: (sessionId: string, summaryId: string, input: Partial<SupplierImportLabCommercialSummary>) => apiFetch(`${base}/${encodeURIComponent(sessionId)}/commercial-summary/${encodeURIComponent(summaryId)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }) as Promise<SupplierImportLabCommercialSummary>,
  bulkCorrectAdditionalCosts: (sessionId: string, items: Array<Partial<SupplierImportLabAdditionalCostItem> & { itemId: string }>) => apiFetch(`${base}/${encodeURIComponent(sessionId)}/additional-cost-items`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ items }) }) as Promise<{ items: SupplierImportLabAdditionalCostItem[] }>,
  selectExtractionRun: (sessionId: string, runId: string) => apiFetch(`${base}/${encodeURIComponent(sessionId)}/extraction-runs/${encodeURIComponent(runId)}/select`, { method: "POST" }) as Promise<SupplierImportLabExtractionRun>,
  correctExtractedRow: (sessionId: string, rowId: string, input: Pick<SupplierImportLabExtractedRow, "displayReference" | "widthMm" | "heightMm" | "quantity" | "unitPrice" | "totalPrice">) => apiFetch(`${base}/${encodeURIComponent(sessionId)}/extracted-rows/${encodeURIComponent(rowId)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }) as Promise<SupplierImportLabExtractedRow>,
  bulkCorrectExtractedRows: (sessionId: string, rows: SupplierImportLabRowDraft[]) => apiFetch(`${base}/${encodeURIComponent(sessionId)}/extracted-rows`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rows }) }) as Promise<{ rows: SupplierImportLabExtractedRow[] }>,
};
