import { useEffect, useMemo, useState } from "react";
import type { SupplierQuote, SupplierQuoteAttachment, SupplierQuoteRevision } from "../supplierQuoteImport/domain/supplierQuote.types";
import { supplierQuotesApi } from "./api/supplierQuotesApi";
import "./supplierQuotes.css";

export type SupplierQuotesWorkspaceProps = { estimateId: string | null; estimateReference: string };
export function clientValidateSupplierFiles(files: readonly Pick<File, "name" | "size">[]) {
  const issues: string[] = []; if (!files.length) issues.push("Select at least one PDF or DOCX file."); if (files.length > 10) issues.push("Select no more than 10 files.");
  let total = 0; for (const file of files) { total += file.size; if (!/\.(pdf|docx)$/i.test(file.name)) issues.push(`${file.name}: only PDF and DOCX are allowed.`); if (!file.size) issues.push(`${file.name}: empty files are not allowed.`); if (file.size > 50 * 1024 * 1024) issues.push(`${file.name}: exceeds 50 MB.`); }
  if (total > 150 * 1024 * 1024) issues.push("Combined file size exceeds 150 MB."); return issues;
}
const sizeLabel = (bytes: number) => `${(bytes / 1024 / 1024).toFixed(2)} MB`;
export default function SupplierQuotesWorkspace({ estimateId, estimateReference }: SupplierQuotesWorkspaceProps) {
  const [quotes, setQuotes] = useState<SupplierQuote[]>([]); const [quoteId, setQuoteId] = useState(""); const [revisions, setRevisions] = useState<SupplierQuoteRevision[]>([]); const [revisionId, setRevisionId] = useState(""); const [attachments, setAttachments] = useState<SupplierQuoteAttachment[]>([]); const [supplierName, setSupplierName] = useState(""); const [supplierCode, setSupplierCode] = useState(""); const [quotationNumber, setQuotationNumber] = useState(""); const [supplierRevision, setSupplierRevision] = useState(""); const [currency, setCurrency] = useState("GBP"); const [files, setFiles] = useState<File[]>([]); const [role, setRole] = useState("original_quote"); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const selectedQuote = quotes.find((quote) => quote.id === quoteId) ?? null; const selectedRevision = revisions.find((revision) => revision.id === revisionId) ?? null; const fileIssues = useMemo(() => clientValidateSupplierFiles(files), [files]);
  async function loadQuotes() { if (!estimateId) return; const rows = await supplierQuotesApi.listQuotes(estimateId); setQuotes(rows); if (quoteId && !rows.some((row) => row.id === quoteId)) setQuoteId(""); }
  async function loadRevisions(nextQuoteId = quoteId) { if (!estimateId || !nextQuoteId) { setRevisions([]); return; } const rows = await supplierQuotesApi.listRevisions(estimateId, nextQuoteId); setRevisions(rows); if (revisionId && !rows.some((row) => row.id === revisionId)) setRevisionId(""); }
  async function loadAttachments(nextRevisionId = revisionId) { if (!estimateId || !quoteId || !nextRevisionId) { setAttachments([]); return; } setAttachments(await supplierQuotesApi.listAttachments(estimateId, quoteId, nextRevisionId)); }
  useEffect(() => { setQuotes([]); setQuoteId(""); setRevisions([]); setRevisionId(""); setAttachments([]); if (estimateId) supplierQuotesApi.listQuotes(estimateId).then(setQuotes).catch((error) => setMessage(error.message)); }, [estimateId]);
  if (!estimateId) return <section className="supplier-quotes-workspace"><h3>Supplier Quote Import (Beta)</h3><p>Select a persisted estimate to manage internal supplier documents.</p></section>;
  async function act(operation: () => Promise<void>) { setBusy(true); setMessage(""); try { await operation(); } catch (error) { setMessage(error instanceof Error ? error.message : "Supplier quote operation failed."); } finally { setBusy(false); } }
  return <section className="supplier-quotes-workspace" data-testid="supplier-quotes-workspace"><div className="supplier-quotes-workspace__header"><div><h3>Supplier Quote Import (Beta)</h3><p>Development tool for internal supplier evidence owned by estimate <strong>{estimateReference}</strong>. Uploading does not add estimate positions.</p></div></div>
    <div className="supplier-quotes-grid"><form onSubmit={(event) => { event.preventDefault(); act(async () => { const created = await supplierQuotesApi.createQuote(estimateId, { supplierCode, supplierName }); setSupplierCode(""); setSupplierName(""); await loadQuotes(); setQuoteId(created.id); await loadRevisions(created.id); setMessage("Supplier quote added."); }); }}><h4>Add supplier quote</h4><label>Supplier name<input value={supplierName} onChange={(e) => setSupplierName(e.target.value)} required /></label><label>Supplier code<input value={supplierCode} onChange={(e) => setSupplierCode(e.target.value)} required /></label><button disabled={busy}>Add supplier</button></form>
      <div><h4>Supplier</h4><select aria-label="Supplier quote" value={quoteId} onChange={(e) => { const id=e.target.value; setQuoteId(id); setRevisionId(""); setAttachments([]); loadRevisions(id).catch((error)=>setMessage(error.message)); }}><option value="">Select supplier quote</option>{quotes.map((quote)=><option key={quote.id} value={quote.id}>{quote.supplierName} ({quote.supplierCode})</option>)}</select>{selectedQuote&&<p>{selectedQuote.supplierName}</p>}</div>
      <form onSubmit={(event)=>{event.preventDefault(); if(!quoteId)return; act(async()=>{const created=await supplierQuotesApi.createRevision(estimateId,quoteId,{supplierQuotationNumber:quotationNumber,supplierRevision,fullQuotationReference:[quotationNumber,supplierRevision].filter(Boolean).join("-"),currency,vatStatus:"unknown"});await loadRevisions();setRevisionId(created.id);setQuotationNumber("");setSupplierRevision("");setMessage("Revision created.");});}}><h4>Create revision</h4><label>Quotation number<input value={quotationNumber} onChange={(e)=>setQuotationNumber(e.target.value)} /></label><label>Supplier revision<input value={supplierRevision} onChange={(e)=>setSupplierRevision(e.target.value)} /></label><label>Currency<input value={currency} maxLength={3} onChange={(e)=>setCurrency(e.target.value.toUpperCase())} /></label><button disabled={busy||!quoteId}>Create revision</button></form>
      <div><h4>Revision</h4><select aria-label="Supplier revision" value={revisionId} onChange={(e)=>{const id=e.target.value;setRevisionId(id);loadAttachments(id).catch((error)=>setMessage(error.message));}}><option value="">Select revision</option>{revisions.map((revision)=><option key={revision.id} value={revision.id}>{revision.fullQuotationReference||`Revision ${revision.revisionSequence+1}`}</option>)}</select>{selectedRevision&&<p>Status: {selectedRevision.lifecycleStatus}</p>}</div></div>
    <div className="supplier-upload-panel"><h4>Upload PDF/DOCX documents</h4><select aria-label="Attachment role" value={role} onChange={(e)=>setRole(e.target.value)}><option value="original_quote">Original quotation</option><option value="supporting_document">Supporting document</option><option value="supplier_drawing">Supplier drawing</option></select><input aria-label="Supplier documents" type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" multiple onChange={(e)=>setFiles(Array.from(e.target.files||[]))} />{files.map((file)=><div key={`${file.name}-${file.size}`}>{file.name} — {sizeLabel(file.size)}</div>)}{fileIssues.map((issue)=><div className="supplier-upload-error" key={issue}>{issue}</div>)}<button disabled={busy||!revisionId||fileIssues.length>0} onClick={()=>act(async()=>{if(!revisionId)return;await supplierQuotesApi.uploadAttachments(estimateId,quoteId,revisionId,files,role);setFiles([]);await loadAttachments();setMessage("Documents uploaded successfully.");})}>{busy?"Working…":"Upload selected files"}</button></div>
    {message&&<div role="status" className="supplier-upload-status">{message}</div>}<div><h4>Stored attachments</h4>{attachments.length===0?<p>No stored documents for this revision.</p>:<table><thead><tr><th>File</th><th>Role</th><th>Type</th><th>Size</th><th>Uploaded</th><th>Actions</th></tr></thead><tbody>{attachments.map((attachment)=><tr key={attachment.id}><td>{attachment.originalFileName}</td><td>{attachment.role}</td><td>{attachment.mediaType}</td><td>{sizeLabel(attachment.sizeBytes)}</td><td>{new Date(attachment.createdAt).toLocaleString()}</td><td><button onClick={()=>act(()=>supplierQuotesApi.downloadAttachment(estimateId,quoteId,revisionId,attachment))}>Download</button><button onClick={()=>act(async()=>{await supplierQuotesApi.removeAttachment(estimateId,quoteId,revisionId,attachment.id);await loadAttachments();setMessage("Attachment removed.");})}>Remove</button></td></tr>)}</tbody></table>}</div>
    <div className="supplier-extraction-panel"><div><h4>Extraction results</h4><p>Extraction is deferred to Stage 1E. No document content is parsed by this Beta upload foundation.</p></div><button type="button" disabled title="Document extraction is not implemented in Stage 1D.">Extract</button><table><thead><tr><th>Reference</th><th>Width</th><th>Height</th><th>Quantity</th><th>Unit Price</th><th>Total Price</th></tr></thead><tbody><tr><td colSpan={6}>No extracted positions.</td></tr></tbody></table></div></section>;
}
