import { randomUUID } from 'node:crypto';
import { pdfReadingOrderBlocks } from './pdfLayout.js';
import { extractEkoOknaSourceSpecification } from './ekoOknaSourceSpecification.js';
import { buildManufacturerInternalSpecification } from './manufacturerInternalSpecification.js';
import { detectEkoOknaDrawingPanels, EKO_INSIDE_DRAWING_PANEL_GEOMETRY_VERSION } from './ekoOknaDrawingPanelGeometry.js';

const flatten = (document) => document.pages.flatMap((page) => page.blocks.map((block) => ({ ...block, text: String(block.text).trim(), pageNumber: page.pageNumber }))).filter((block) => block.text);
const lines = (document) => pdfReadingOrderBlocks(document).map((block) => ({ ...block, text: String(block.text).trim() })).filter((block) => block.text);
const textOf = (document) => flatten(document).map((block) => block.text).join('\n');
const decimal = (raw) => { const compact=String(raw??'').replace(/[\s\u00a0£€$]/g,''); if(!/^[\d.,]+$/.test(compact))return null; const comma=compact.lastIndexOf(','),dot=compact.lastIndexOf('.'); return comma>=0&&dot>=0?(comma>dot?compact.replaceAll('.','').replace(',','.'):compact.replaceAll(',','')):comma>=0?compact.replace(',','.'):compact; };
const integerQuantity = (raw) => { const value=decimal(raw); return value!=null&&Number.isInteger(Number(value))&&Number(value)>0?Number(value):null; };
const sourceTrace = (document, blocks) => blocks.map((block) => ({ attachmentId:document.attachmentId,pageNumber:block.pageNumber,blockId:block.id,boundingBox:block.boundingBox,coordinateSpace:block.boundingBox?'pdf_points':null,extractedText:block.text }));
const cleanMetadataValue = (value) => String(value??'').trim().replace(/\s+([,:;])$/,'').replace(/([,:;])$/,'').trim() || null;
const dateIso = (value) => { const match=String(value??'').match(/^(\d{2})[./](\d{2})[./](\d{4})$/); return match?`${match[3]}-${match[2]}-${match[1]}`:cleanMetadataValue(value); };

export function detectPdfDocumentCurrency(document) {
  const text = textOf(document);
  const evidence = {
    GBP: (text.match(/(?:£\s*[\d.,]+|[\d.,]+\s*£|\bGBP\b)/gi) || []).length,
    EUR: (text.match(/(?:€\s*[\d.,]+|[\d.,]+\s*€|\bEUR\b|\bEURO\b)/gi) || []).length,
  };
  const explicit = Object.entries(evidence).filter(([, count]) => count > 0);
  return explicit.length === 1 ? { currency: explicit[0][0], evidence } : { currency: null, evidence };
}

function sourceVisual(document, visualRegion, { primary = false } = {}) {
  const sourcePage = visualRegion?.sourcePage ?? null;
  const boundingRegion = visualRegion?.boundingRegion ?? null;
  return {kind:'manufacturer_document_region',role:visualRegion?.role??'combined_source',primary,primaryUse:primary?'products_supply':null,status:'unavailable',sourceFormat:'pdf',sourcePage,boundingRegion,coordinateSpace:'pdf_points',mappingMethod:visualRegion?.mappingMethod??'pdf_position_region_geometry',mappingConfidence:visualRegion?.geometryEvidence?.confidence??(boundingRegion?'strong':'review'),mappingReviewStatus:visualRegion?.geometryEvidence?.reviewState??(boundingRegion?'mapped_automatic':'needs_review'),geometryEvidence:visualRegion?.geometryEvidence??null,originalAsset:{mediaType:'application/pdf',attachmentId:document.attachmentId,sourcePage,boundingRegion,coordinateSpace:'pdf_points'},renderParameters:{targetFormat:'image/png',status:'not_rendered'},reason:'The immutable PDF page region is retained as provenance; a browser preview derivative is not yet available.'};
}

function row(document,{ordinal,reference,manufacturerItemNumber=null,roomLocation=null,product=null,productSystem=null,configurationDescription=null,glassSpecification=null,fittingsSpecification=null,quantity,widthMm=null,heightMm=null,unitPrice=null,totalPrice=null,currency='GBP',classification='standard',alternativeTo=null,classificationEvidence=null,manufacturerQuotedUg=null,manufacturerQuotedUw=null,blocks,warnings=[],visualRegion=null,visualRegions=null,sourceSpecification=null}){
  const requestedVisuals=Array.isArray(visualRegions)&&visualRegions.length?visualRegions:visualRegion?[{...visualRegion,role:'combined_source'}]:[];const primaryRegion=requestedVisuals.find(item=>item.primary)||requestedVisuals[0]||null;const sourcePage=primaryRegion?.sourcePage??blocks.find(block=>Number.isInteger(block.pageNumber))?.pageNumber??null;const pageBoxes=blocks.filter(block=>block.pageNumber===sourcePage&&block.boundingBox).map(block=>block.boundingBox);const fallbackRegion=pageBoxes.length?{sourcePage,boundingRegion:{x:Math.min(...pageBoxes.map(box=>box.x)),y:Math.min(...pageBoxes.map(box=>box.y)),width:Math.max(...pageBoxes.map(box=>box.x+box.width))-Math.min(...pageBoxes.map(box=>box.x)),height:Math.max(...pageBoxes.map(box=>box.y+box.height))-Math.min(...pageBoxes.map(box=>box.y))},role:'combined_source',primary:true}:null;const effectiveVisuals=requestedVisuals.length?requestedVisuals:fallbackRegion?[fallbackRegion]:[];const sourceVisuals=effectiveVisuals.map(item=>sourceVisual(document,item,{primary:Boolean(item.primary)||(!effectiveVisuals.some(candidate=>candidate.primary)&&item===effectiveVisuals[0])}));const primaryVisual=sourceVisuals.find(item=>item.primary)||sourceVisuals[0]||sourceVisual(document,null,{primary:true});
  const canonical=sourceSpecification?.canonical??{};const resolvedConfiguration=configurationDescription??canonical.sashes?.map(item=>`${item.sourceElementReference}: ${item.fitting??item.profile??'unspecified'}`).join('; ')??null;const areaSquareMetres=widthMm&&heightMm?String((widthMm*heightMm/1_000_000).toFixed(4)).replace(/0+$/,'').replace(/\.$/,''):null;const resolvedFittings=fittingsSpecification??canonical.sashes?.map(item=>[item.sourceElementReference,item.fitting,item.hardware].filter(Boolean).join(' · ')).filter(Boolean).join('; ')??null;const internalSpecification=sourceSpecification?buildManufacturerInternalSpecification({product,productSystem,widthMm,heightMm,quantity,areaSquareMetres,configurationDescription:resolvedConfiguration,glassSpecification,fittingsSpecification:resolvedFittings,manufacturerQuotedUg,manufacturerQuotedUw,sourceSpecification}):null;const manufacturerEvidence={manufacturerItemNumber,customerReference:reference,roomLocation,product,productSystem,productType:product?/\bdoor\b/i.test(product)?'Door':/\bwindow|casement|frame\b/i.test(product)?'Window':null:null,configurationDescription:resolvedConfiguration,areaSquareMetres,weightKg:canonical.weightKg?.value??null,glassSpecification,fittingsSpecification:resolvedFittings,manufacturerQuotedUg,manufacturerQuotedUw,customerSafeSpecification:[],sourceSpecification,canonicalSpecification:canonical,...(internalSpecification?{internalSpecification}:{}),sourceVisuals,sourceVisual:primaryVisual};
  const original={displayReference:reference,originalReferenceText:reference,supplierReferenceTokens:[reference,manufacturerItemNumber].filter(Boolean),quantity,widthMm,heightMm,originalDimensionsText:widthMm&&heightMm?`${widthMm}x${heightMm}mm`:null,unitPrice,totalPrice,currency,classification,includedInSupplierTotal:classification==='standard',alternativeTo,classificationEvidence,manufacturerEvidence};
  return{id:randomUUID(),ordinal,...original,...manufacturerEvidence,sourcePages:[...new Set(blocks.map(block=>block.pageNumber).filter(Number.isInteger))],sourceTrace:sourceTrace(document,blocks),confidence:warnings.length?'0.78':'0.96',warnings,status:warnings.length?'needs_review':'extracted',originalExtractedSnapshot:original};
}

function ekoPositionVisualRegions(document, blocks, markerPage) {
  const sourcePages = new Set(blocks.map((block) => block.pageNumber).filter(Number.isInteger));
  const marker = document.pages.find((item) => item.pageNumber === markerPage);
  const page = Number(marker?.contentEvidence?.vectorPathCount || 0) >= 200 ? marker : document.pages
    .filter((item) => sourcePages.has(item.pageNumber) && item.pageNumber > markerPage)
    .sort((left, right) => left.pageNumber - right.pageNumber)
    .find((item) => Number(item.contentEvidence?.vectorPathCount || 0) >= 200);
  if (!page || !Number.isFinite(page.width) || !Number.isFinite(page.height) || !page.contentEvidence?.hasVectorContent) return null;
  const drawingPanels = detectEkoOknaDrawingPanels(page);
  if (drawingPanels) return drawingPanels;
  // Do not revive the superseded tight-crop heuristic when the stronger
  // classifier is uncertain. Retain a bounded combined source region and make
  // the review state explicit instead of silently clipping an Inside panel.
  return [{
    sourcePage: page.pageNumber,
    boundingRegion: { x: page.width * 0.03, y: page.height * 0.38, width: page.width * 0.44, height: page.height * 0.58 },
    role: 'combined_source',
    primary: true,
    mappingMethod: EKO_INSIDE_DRAWING_PANEL_GEOMETRY_VERSION,
    geometryEvidence: {
      version: EKO_INSIDE_DRAWING_PANEL_GEOMETRY_VERSION,
      classifier: 'drawing_owned_text_and_vector_evidence',
      confidence: 'review',
      reviewState: 'review_required',
      reason: 'The complete Inside drawing-panel boundary could not be established without clipping or adjacent-table risk.',
    },
  }];
}

const pageSegments = (document, marker) => {
  const all = lines(document); const starts = all.map((block,index)=>marker.test(block.text)?index:-1).filter(index=>index>=0);
  return starts.map((start,index)=>all.slice(start,starts[index+1]??all.length));
};

function parseFrameQuotation(document){
  const rows=[]; const segments=pageSegments(document,/^Frame No:\s*\d+\s+Qty:/i);
  for(const blocks of segments){const header=blocks[0].text.match(/^Frame No:\s*(\d+)\s+Qty:\s*(\d+)\s+(.+?)\s*Location:\s*(.+?)\s+£\s*([\d,.]+)$/i);if(!header)continue;const dimension=blocks.find(block=>/\b\d{2,5}\s*x\s*\d{2,5}\b/i.test(block.text))?.text.match(/\b(\d{2,5})\s*x\s*(\d{2,5})\b/i);const uw=blocks.map(block=>block.text).join(' ').match(/\bU(?:w|-Value(?:\s*\(element\))?)\s*[:=]?\s*([\d.,]+)/i)?.[1]??null;const location=cleanMetadataValue(header[4]);rows.push(row(document,{ordinal:rows.length,reference:location||`Frame ${header[1]}`,manufacturerItemNumber:header[1],roomLocation:location,product:cleanMetadataValue(header[3]),configurationDescription:cleanMetadataValue(header[3]),quantity:integerQuantity(header[2]),widthMm:dimension?Number(dimension[1]):null,heightMm:dimension?Number(dimension[2]):null,unitPrice:decimal(header[5]),totalPrice:decimal(header[5]),manufacturerQuotedUw:decimal(uw),blocks,warnings:dimension?[]:['Position dimensions were not recognised.']}));}
  const all=flatten(document),quotation=all.find(block=>/^(?:Quotation|Quote)\s+(?:No\.?\s*)?\d+/i.test(block.text))?.text.match(/\d[\d/-]*/)?.[0]??null;
  return{adapter:'frame_schedule_geometry_v1',supplier:/VELFAC/i.test(textOf(document))?'VELFAC':'Rationel',documentType:'complete_quotation',quotation:{supplierQuotationNumber:quotation,supplierRevision:null,fullQuotationReference:quotation,warnings:[]},metadata:{supplierCustomer:null,projectReference:cleanMetadataValue(all[all.findIndex(block=>/^Customer Reference:$/i.test(block.text))+1]?.text),quotationDate:null},rows,warnings:rows.length?[]:['Frame quotation positions were not detected.']};
}

function parseIdealcombi(document){
  const rows=[];
  for(const block of lines(document)){const match=block.text.match(/^(\d+)\s+(\d+)\s+(.+?)\s+(\d{2,5})\s*X\s*(\d{2,5})\s+([\d.,]+)\s+([\d.,]+)$/i);if(!match)continue;rows.push(row(document,{ordinal:rows.length,reference:match[1],manufacturerItemNumber:match[1],roomLocation:cleanMetadataValue(match[3]),quantity:integerQuantity(match[2]),widthMm:Number(match[4]),heightMm:Number(match[5]),unitPrice:decimal(match[6]),totalPrice:decimal(match[7]),blocks:[block]}));}
  const all=flatten(document),quotation=all[all.findIndex(block=>/^Quotation no\.$/i.test(block.text))+1]?.text??null;
  return{adapter:'idealcombi_position_table_v1',supplier:'Idealcombi',documentType:'complete_quotation',quotation:{supplierQuotationNumber:cleanMetadataValue(quotation),supplierRevision:null,fullQuotationReference:cleanMetadataValue(quotation),warnings:[]},metadata:{supplierCustomer:null,projectReference:null,quotationDate:null},rows,warnings:rows.length?[]:['Idealcombi position table was not detected.']};
}

function parseNorrsken(document){
  const rows=[];
  for(const block of lines(document)){const marker=block.text.match(/^(\d+)\s+(Option\s+)?(Type\s+.+?)\s*-\s*(\[?\d+\]?)\s+(.+)$/i);if(!marker||!/£/.test(marker[5]))continue;const beforePrice=marker[5].split('£')[0];const dimensions=[...beforePrice.matchAll(/\b(\d{3,5})\b/g)].map(match=>Number(match[1]));if(dimensions.length<2)continue;const [widthMm,heightMm]=dimensions.slice(-2);const prices=[...marker[5].matchAll(/£\s*\[?([\d,.]+)\]?/g)].map(match=>decimal(match[1]));if(!prices.length)continue;const quantity=integerQuantity(marker[4].replace(/[\[\]]/g,''));const baseReference=cleanMetadataValue(marker[3]);const product=cleanMetadataValue(beforePrice.replace(/\b\d{3,5}\b[\s\S]*$/,'').trim())||null;const values=[...beforePrice.matchAll(/\b(0?\.\d+|1(?:\.0+)?)\b/g)].map(match=>decimal(match[1])).filter(Boolean);const alternative=Boolean(marker[2])||/\[/.test(marker[4]);const reference=alternative?`${baseReference} ALT`:baseReference;rows.push(row(document,{ordinal:rows.length,reference,manufacturerItemNumber:marker[1],product,quantity,widthMm,heightMm,unitPrice:prices[0],totalPrice:prices.at(-1),classification:alternative?'alternative':'standard',alternativeTo:alternative?baseReference:null,classificationEvidence:alternative?'Supplier table labels the position as an option.':null,manufacturerQuotedUw:values.at(-1)??null,blocks:[block]}));}
  const all=flatten(document),quotation=textOf(document).match(/(?:Quotation|Quote)\s*(?:No\.?|number)?\s*[:#]?\s*([A-Z0-9/-]+)/i)?.[1]??null;
  return{adapter:'norrsken_item_table_v1',supplier:'Norrsken',documentType:'complete_quotation',quotation:{supplierQuotationNumber:quotation,supplierRevision:null,fullQuotationReference:quotation,warnings:[]},metadata:{supplierCustomer:null,projectReference:null,quotationDate:null},rows,warnings:rows.length?[]:['Norrsken item table was not detected.']};
}

function parseTwentyOneDegrees(document){
  const rows=[];const segments=pageSegments(document,/^ITEM\s+\d+\s*-/i);
  for(const blocks of segments){const header=blocks[0].text.match(/^ITEM\s+(\d+)\s*-\s*(.+?)\s+Price after discount:\s*£\s*([\d,.]+)/i);if(!header)continue;const text=blocks.map(block=>block.text).join(' ');const product=text.match(/Supply & Deliver a complete new\s+(.+?)(?:\s*\([^)]*\)|\s+in Alu-clad)/i)?.[1]??null;const system=text.match(/\(([^)]*(?:Casement|Lift and Slide|Door)[^)]*)\)/i)?.[1]??null;const uw=text.match(/\bU-Value\s*([\d.,]+)/i)?.[1]??null;rows.push(row(document,{ordinal:rows.length,reference:header[1],manufacturerItemNumber:header[1],roomLocation:cleanMetadataValue(header[2]),product:cleanMetadataValue(product),productSystem:cleanMetadataValue(system),configurationDescription:cleanMetadataValue(product),quantity:1,widthMm:null,heightMm:null,unitPrice:decimal(header[3]),totalPrice:decimal(header[3]),manufacturerQuotedUw:decimal(uw),blocks,warnings:['Position dimensions are not present in the machine-readable text and require review.']}));}
  const quotation=textOf(document).match(/GB Quote Reference\s+([A-Z0-9/-]+)/i)?.[1]??null;
  return{adapter:'twenty_one_degrees_detail_v1',supplier:'21 Degrees',documentType:'complete_quotation',quotation:{supplierQuotationNumber:quotation,supplierRevision:null,fullQuotationReference:quotation,warnings:[]},metadata:{supplierCustomer:null,projectReference:null,quotationDate:null},rows,warnings:rows.length?[]:['21 Degrees detailed positions were not detected.']};
}

function parseWestcoast(document){
  const rows=[];
  for(const block of lines(document)){const match=block.text.match(/^(.+?)\s+\((\d{2,5})x(\d{2,5})\)\s+(\d+)\s+(.+?)\s+(\d+)\s+no$/i);if(!match)continue;const room=cleanMetadataValue(match[5]);const location=room?.match(/\b([A-Z]+\d+[A-Z]?)\b/i)?.[1]??null;const quantity=Number(match[6]);const alternative=/\bopt\b/i.test(room||'')||quantity===0;const baseReference=location||match[4],reference=alternative?`${baseReference} ALT`:baseReference;rows.push(row(document,{ordinal:rows.length,reference,manufacturerItemNumber:match[4],roomLocation:room,product:cleanMetadataValue(match[1]),quantity,widthMm:Number(match[2]),heightMm:Number(match[3]),classification:alternative?'alternative':'standard',alternativeTo:alternative?baseReference:null,classificationEvidence:alternative?'Supplier schedule marks this position as optional or zero quantity.':null,blocks:[block],warnings:quantity>0?[]:['The supplier states zero quantity; review before canonical costing.']}));}
  const quotation=textOf(document).match(/Quotation\s+(\d+)/i)?.[1]??null;
  return{adapter:'westcoast_position_schedule_v1',supplier:'Westcoast Windows',documentType:'complete_quotation',quotation:{supplierQuotationNumber:quotation,supplierRevision:null,fullQuotationReference:quotation,warnings:[]},metadata:{supplierCustomer:null,projectReference:null,quotationDate:null},rows,warnings:rows.length?[]:['Westcoast position schedule was not detected.']};
}

function parseInternormSchedule(document){
  const blocks=flatten(document),rows=[];
  for(let index=0;index<blocks.length-3;index+=1){if(!/^\d{3}$/.test(blocks[index].text)||!/^\d+[.,]\d+$/.test(blocks[index+1]?.text)||!/^Unit$/i.test(blocks[index+2]?.text)||!/^[A-Z]{2}[A-Z0-9-]+/i.test(blocks[index+3]?.text))continue;const next=blocks.findIndex((block,nextIndex)=>nextIndex>index+3&&/^\d{3}$/.test(block.text)&&/^\d+[.,]\d+$/.test(blocks[nextIndex+1]?.text||'')&&/^Unit$/i.test(blocks[nextIndex+2]?.text||'')&&/^[A-Z]{2}[A-Z0-9-]+/i.test(blocks[nextIndex+3]?.text||''));const end=next>=0?next:blocks.length;const segment=blocks.slice(index,end);const widthText=segment.find(block=>/^[, ]*(?:Width|Frame width):?$/i.test(block.text));const heightText=segment.find(block=>/^[, ]*(?:Height|Frame height):?$/i.test(block.text));const inline=segment.map(block=>block.text).join(' ').match(/Element width:\s*(\d+)mm,?\s*Element height:\s*(\d+)mm/i);const width=inline?Number(inline[1]):widthText?Number(segment[segment.indexOf(widthText)+1]?.text.match(/\d+/)?.[0]||0)||null:null;const height=inline?Number(inline[2]):heightText?Number(segment[segment.indexOf(heightText)+1]?.text.match(/\d+/)?.[0]||0)||null:null;const reference=blocks[index+3].text.match(/^[A-Z]{2}[A-Z0-9-]+/i)?.[0]||blocks[index+3].text.replace(/:$/,'');rows.push(row(document,{ordinal:rows.length,reference,quantity:integerQuantity(blocks[index+1].text),widthMm:width,heightMm:height,unitPrice:null,totalPrice:null,currency:'GBP',blocks:segment}));}
  return{adapter:'internorm_schedule_v1',supplier:'Glass Worx / Internorm',documentType:'window_schedule',quotation:{supplierQuotationNumber:blocks.find(block=>/^Offer number:/i.test(block.text))?.text.split(':').slice(1).join(':').trim()||null,supplierRevision:null,fullQuotationReference:blocks.find(block=>/^Offer number:/i.test(block.text))?.text.split(':').slice(1).join(':').trim()||null,warnings:[]},metadata:{supplierCustomer:cleanMetadataValue(blocks.find(block=>/^Mr\s+/i.test(block.text))?.text),projectReference:cleanMetadataValue(blocks.find(block=>/Schedule$/i.test(block.text))?.text.replace(/\s*-\s*Schedule$/i,'')),quotationDate:dateIso(blocks.find(block=>/^\d{2}\.\d{2}\.\d{4}$/.test(block.text))?.text)},rows,warnings:rows.length?[]:['Internorm schedule positions were not detected.']};
}

function parseEkoItemised(document,variant){
  const pages=document.pages,rows=[];const currencyEvidence=detectPdfDocumentCurrency(document);const currencyWarnings=currencyEvidence.currency?[]:['The document currency is absent or ambiguous and requires review.'];
  const segments=variant==='eko'?(()=>{const blocks=flatten(document),markers=blocks.map((block,index)=>/^(?:Window|Door)\s+\d{3}$/i.test(block.text)?index:-1).filter(index=>index>=0);return markers.map((start,index)=>blocks.slice(start,markers[index+1]??blocks.length));})():pages.map(page=>page.blocks.map(block=>({...block,text:String(block.text).trim(),pageNumber:page.pageNumber})).filter(block=>block.text));
  for(const blocks of segments){const markerIndex=blocks.findIndex(block=>/^(?:Window|Door)\s+\d{3}$/i.test(block.text));if(markerIndex<0)continue;const marker=blocks[markerIndex],quantityBlock=blocks.slice(markerIndex+1).find(block=>/^(?:Qty\s*:|Quantity:)/i.test(block.text));const priceLabel=blocks.findIndex(block=>/^Price$|^Window price$/i.test(block.text));const priceBlock=priceLabel>=0?blocks.slice(priceLabel+1).find(block=>decimal(block.text)!=null):null;const dimensions=blocks.find(block=>/^Dimensions\s+\d+\s*mm\s*x\s*\d+\s*mm$/i.test(block.text))?.text.match(/(\d+)\s*mm\s*x\s*(\d+)\s*mm/i);let width=dimensions?Number(dimensions[1]):null,height=dimensions?Number(dimensions[2]):null;if(variant==='gutmann'){const diagram=blocks.slice(0,markerIndex).filter(block=>/^\d{3,4}$/.test(block.text)).map(block=>Number(block.text));if(diagram.length){width=Math.max(...diagram);height=diagram.filter(value=>value!==width).sort((a,b)=>b-a)[0]||null;}}const reference=marker.text.replace(/^(Window|Door)\s+/i,'');const totalPrice=decimal(priceBlock?.text),joined=blocks.map(block=>block.text).join(' ');const system=joined.match(/\bSystem\s*:\s*(.{1,120}?)(?=\s+(?:Page\s+\d|Colour|Window|Door|Price|Dimensions|FIX|Outer frame)\b|$)/i)?.[1]??null;const ug=joined.match(/\bUg\s*=\s*([\d.,]+)/i)?.[1]??null,uw=joined.match(/\bUw\s*=\s*([\d.,]+)/i)?.[1]??null;const glazing=blocks.find(block=>/\bUg\s*=\s*[\d.,]+/i.test(block.text))?.text??null;const visualRegions=variant==='eko'?ekoPositionVisualRegions(document,blocks,marker.pageNumber):null;const sourceSpecification=variant==='eko'?extractEkoOknaSourceSpecification(document,blocks,visualRegions?.[0]?.sourcePage):null;rows.push(row(document,{ordinal:rows.length,reference,manufacturerItemNumber:reference,product:/^Door/i.test(marker.text)?'Door':'Window',productSystem:cleanMetadataValue(system),glassSpecification:cleanMetadataValue(glazing),quantity:integerQuantity(quantityBlock?.text.split(':').slice(1).join(':')),widthMm:width,heightMm:height,unitPrice:totalPrice,totalPrice,currency:currencyEvidence.currency,manufacturerQuotedUg:decimal(ug),manufacturerQuotedUw:decimal(uw),blocks,warnings:currencyWarnings,visualRegions,sourceSpecification}));}
  const all=flatten(document),quotationText=variant==='gutmann'?all.find(block=>/Price details\s+WEB\//i.test(block.text))?.text:all.find(block=>/^Quotation\s+OF\//i.test(block.text))?.text;const full=quotationText?.match(/(?:WEB|OF)\/\d+\/\d+/i)?.[0]||null;const client=variant==='gutmann'?all[all.findIndex(block=>/^Client:$/i.test(block.text))+1]?.text:all.find(block=>/^ECOFENSTER LTD/i.test(block.text))?.text;const project=variant==='gutmann'?all.find(block=>/^Your reference:/i.test(block.text))?.text.split(':').slice(1).join(':'):null;const date=variant==='gutmann'?all.find(block=>/^\d{2}\/\d{2}\/\d{4}$/.test(block.text))?.text:all.find(block=>/^\d{2}\/\d{2}\/\d{4}$/.test(block.text))?.text;
  return{adapter:variant==='gutmann'?'gutmann_web_v1':'eko_okna_winpro_v1',supplier:variant==='gutmann'?'Ecofenster / Gutmann':'EKO-OKNA',documentType:'complete_quotation',quotation:{supplierQuotationNumber:full,supplierRevision:null,fullQuotationReference:full,warnings:currencyWarnings},metadata:{supplierCustomer:cleanMetadataValue(client),projectReference:cleanMetadataValue(project),quotationDate:dateIso(date)},rows,warnings:rows.length?currencyWarnings:['Itemised PDF positions were not detected.']};
}

function parseGlassWorxCover(document){const blocks=flatten(document),reference=blocks.find(block=>/^25\s*-\s*\d+\s*-/i.test(block.text))?.text||null,preparedFor=blocks[blocks.findIndex(block=>/^Prepared for$/i.test(block.text))+1]?.text||null,date=blocks.find(block=>/^\d{2}\.\d{2}\.\d{4}$/.test(block.text))?.text;return{adapter:'glass_worx_cover_v1',supplier:'Glass Worx',documentType:'quotation_letter',quotation:{supplierQuotationNumber:cleanMetadataValue(reference),supplierRevision:null,fullQuotationReference:cleanMetadataValue(reference),warnings:[]},metadata:{supplierCustomer:cleanMetadataValue(preparedFor),projectReference:cleanMetadataValue(reference),quotationDate:dateIso(date)},rows:[],warnings:[]};}

const adapters=[
  {recognizes:text=>/Glass Worx Limited[\s\S]*Offer number:\s*\d+/i.test(text)&&/\bPos\.\s*\nQuantity\b/i.test(text),parse:parseInternormSchedule},
  {recognizes:text=>/Glass Worx Ltd[\s\S]*YOUR PROJECT COSTS/i.test(text),parse:parseGlassWorxCover},
  {recognizes:text=>/EKO-OKNA S\.A\.[\s\S]*Quotation\s+OF\//i.test(text),parse:document=>parseEkoItemised(document,'eko')},
  {recognizes:text=>/Price details\s+WEB\//i.test(text)&&/\[GUTMANN\]/i.test(text),parse:document=>parseEkoItemised(document,'gutmann')},
  {recognizes:text=>/\bFrame No:\s*\d+\b[\s\S]*\bQty:\s*\d+/i.test(text)&&/\b(?:VELFAC|Rationel)\b/i.test(text),parse:parseFrameQuotation},
  {recognizes:text=>/\bIdealcombi\b/i.test(text)&&/\bQuotation no\./i.test(text)&&/\bGBP\/ Unit\b/i.test(text),parse:parseIdealcombi},
  {recognizes:text=>/\bItem\s+Location\s+No\.\s+Type\s+Width Height Glazing\b/i.test(text)&&/\bPrice ea\.\s*\nPrice Total\b/i.test(text),parse:parseNorrsken},
  {recognizes:text=>/\bWestcoast Windows AB\b/i.test(text)&&/\bPowered by CalWin\b/i.test(text),parse:parseWestcoast},
  {recognizes:text=>/\b21 Degrees\b/i.test(text)&&/\bGB Quote Reference\b/i.test(text)&&/\bPrice after discount\b/i.test(text),parse:parseTwentyOneDegrees},
];

export function parsePdfSupplierFields(document){if(document.mediaType!=='application/pdf')return null;const text=textOf(document);const adapter=adapters.find(candidate=>candidate.recognizes(text));return adapter?adapter.parse(document):null;}

function summary(document,{currency,finalSupplierTotal,productSubtotal=null,additionalItemsSubtotal=null,deliveryTotal=null,vatTotal=null}){const blocks=flatten(document),original={currency, totalQuantity:null,totalQuantityUnit:null,totalAreaSquareMetres:null,productSubtotal,additionalItemsSubtotal,deliveryTotal,vatTotal,finalSupplierTotal,averageUValue:null,totalWeightKg:null,closingNotes:null};return{id:randomUUID(),...original,sourceTrace:sourceTrace(document,blocks.filter(block=>/total|net price|cost \(excl/i.test(block.text))),warnings:[],confidence:0.96,status:'extracted',originalExtractedSnapshot:original};}
export function parsePdfSupplierSummary(document,positionRows=[]){
  const parsed=parsePdfSupplierFields(document);if(!parsed)return null;const blocks=flatten(document);
  if(parsed.adapter==='internorm_schedule_v1')return{summary:null,additionalItems:[],warnings:['Line prices and quotation total are supplied separately.']};
  if(parsed.adapter==='glass_worx_cover_v1'){
    const packageValues=blocks.filter(block=>/^\d{1,3},\d{3}\.\d{2}$/.test(block.text)).map(block=>decimal(block.text)).slice(-3);const selected=packageValues[1]??packageValues[0]??null;
    const labels=['Bronze / Supply Only','Silver / Install Support','Gold / Full Installation'];const value=summary(document,{currency:'GBP',finalSupplierTotal:selected});value.comparisonTotals=packageValues.map((amount,index)=>({classification:'package_option',label:labels[index],amount,currency:'GBP',includedInSupplierTotal:index===1,selected:index===1,sourceTrace:sourceTrace(document,blocks.filter(block=>decimal(block.text)===amount))}));value.originalExtractedSnapshot.comparisonTotals=value.comparisonTotals;value.warnings=['Line-level reconciliation is unavailable because the authoritative schedule is unpriced.'];value.status='needs_review';value.reconciliation={positionSubtotal:null,additionalSubtotal:null,deliverySubtotal:null,expectedFinal:null,reconciled:false,warnings:value.warnings};return{summary:value,additionalItems:[],warnings:value.warnings};
  }
  if(parsed.adapter==='norrsken_item_table_v1'){
    const pageLines=lines(document);const amount=(pattern)=>{const match=pageLines.find(block=>pattern.test(block.text))?.text.match(/£\s*([\d,.]+)\s*$/);return decimal(match?.[1]);};const productSubtotal=amount(/^Total Items\b/i),deliveryTotal=amount(/^Delivery\b/i),sills=amount(/^Sills & Trims\b/i),services=amount(/^Services\b/i),finalSupplierTotal=amount(/^Total\s+£/i);const additionalItemsSubtotal=sills&&services?(Number(sills)+Number(services)).toFixed(2):null;const value=summary(document,{currency:'GBP',productSubtotal,additionalItemsSubtotal,deliveryTotal,finalSupplierTotal});value.reconciliation={positionSubtotal:positionRows.filter(item=>item.includedInSupplierTotal!==false).reduce((sum,item)=>sum+Number(item.totalPrice||0),0).toFixed(2),additionalSubtotal:additionalItemsSubtotal,deliverySubtotal:deliveryTotal,expectedFinal:[productSubtotal,additionalItemsSubtotal,deliveryTotal].every(Boolean)?(Number(productSubtotal)+Number(additionalItemsSubtotal)+Number(deliveryTotal)).toFixed(2):null,reconciled:false,warnings:[]};value.reconciliation.reconciled=value.reconciliation.expectedFinal!=null&&Number(value.reconciliation.expectedFinal)===Number(finalSupplierTotal);value.reconciliation.warnings=value.reconciliation.reconciled?[]:['Supplied total does not reconcile with the extracted item and service evidence.'];value.warnings=value.reconciliation.warnings;value.status=value.warnings.length?'needs_review':'extracted';return{summary:value,additionalItems:[],warnings:value.warnings};
  }
  if(parsed.adapter==='twenty_one_degrees_detail_v1'){
    const pageLines=lines(document);const amount=(pattern)=>{const match=pageLines.find(block=>pattern.test(block.text))?.text.match(/£\s*([\d,.]+)\s*$/);return decimal(match?.[1]);};const productSubtotal=amount(/^Sub Total After Discount\b/i),vatTotal=amount(/^VAT\b/i),finalSupplierTotal=amount(/^Total Order Value\b/i);const value=summary(document,{currency:'GBP',productSubtotal,vatTotal,finalSupplierTotal});value.warnings=['Dimensional reconciliation is incomplete because position dimensions are absent from the text layer.'];value.status='needs_review';value.reconciliation={positionSubtotal:positionRows.reduce((sum,item)=>sum+Number(item.totalPrice||0),0).toFixed(2),additionalSubtotal:null,deliverySubtotal:null,expectedFinal:productSubtotal&&vatTotal?(Number(productSubtotal)+Number(vatTotal)).toFixed(2):null,reconciled:Boolean(productSubtotal&&vatTotal&&finalSupplierTotal&&Number(productSubtotal)+Number(vatTotal)===Number(finalSupplierTotal)),warnings:value.warnings};return{summary:value,additionalItems:[],warnings:value.warnings};
  }
  if(['idealcombi_position_table_v1','frame_schedule_geometry_v1','westcoast_position_schedule_v1'].includes(parsed.adapter))return{summary:null,additionalItems:[],warnings:['A trustworthy end-of-quotation commercial summary was not recognised for this layout.']};
  const totalLabel=blocks.findIndex(block=>parsed.adapter==='gutmann_web_v1'?/^Net price$/i.test(block.text):/^Totals$/i.test(block.text));const candidates=blocks.slice(Math.max(0,totalLabel),totalLabel+40).map(block=>decimal(block.text)).filter(Boolean);const final=candidates[0];const productSubtotal=positionRows.every(item=>item.totalPrice!=null)?positionRows.reduce((sum,item)=>sum+Number(item.totalPrice),0).toFixed(2):null;const detectedCurrency=detectPdfDocumentCurrency(document).currency;const rowCurrencies=[...new Set(positionRows.map(item=>item.currency).filter(Boolean))];const currency=rowCurrencies.length===1?rowCurrencies[0]:detectedCurrency;const value=summary(document,{currency,finalSupplierTotal:final,productSubtotal});const reconciled=productSubtotal!=null&&final!=null&&Number(productSubtotal)===Number(final);value.reconciliation={positionSubtotal:productSubtotal,additionalSubtotal:null,deliverySubtotal:null,expectedFinal:productSubtotal,reconciled,warnings:reconciled?[]:['Supplied final total does not reconcile with the extracted commercial evidence.']};if(!currency)value.reconciliation.warnings.push('The document currency is absent or ambiguous and requires review.');value.warnings=value.reconciliation.warnings;value.status=value.warnings.length?'needs_review':'extracted';return{summary:value,additionalItems:[],warnings:value.warnings};
}

export { cleanMetadataValue };
