import { randomUUID } from 'node:crypto';

const flatten = (document) => document.pages.flatMap((page) => page.blocks.map((block) => ({ ...block, text: String(block.text).trim(), pageNumber: page.pageNumber }))).filter((block) => block.text);
const textOf = (document) => flatten(document).map((block) => block.text).join('\n');
const decimal = (raw) => { const compact=String(raw??'').replace(/[\s\u00a0£€$]/g,''); if(!/^[\d.,]+$/.test(compact))return null; const comma=compact.lastIndexOf(','),dot=compact.lastIndexOf('.'); return comma>=0&&dot>=0?(comma>dot?compact.replaceAll('.','').replace(',','.'):compact.replaceAll(',','')):comma>=0?compact.replace(',','.'):compact; };
const integerQuantity = (raw) => { const value=decimal(raw); return value!=null&&Number.isInteger(Number(value))&&Number(value)>0?Number(value):null; };
const sourceTrace = (document, blocks) => blocks.map((block) => ({ attachmentId:document.attachmentId,pageNumber:block.pageNumber,blockId:block.id,boundingBox:block.boundingBox,coordinateSpace:block.boundingBox?'pdf_points':null,extractedText:block.text }));
const cleanMetadataValue = (value) => String(value??'').trim().replace(/\s+([,:;])$/,'').replace(/([,:;])$/,'').trim() || null;
const dateIso = (value) => { const match=String(value??'').match(/^(\d{2})[./](\d{2})[./](\d{4})$/); return match?`${match[3]}-${match[2]}-${match[1]}`:cleanMetadataValue(value); };

function row(document,{ordinal,reference,quantity,widthMm=null,heightMm=null,unitPrice=null,totalPrice=null,currency='GBP',blocks}){
  const original={displayReference:reference,originalReferenceText:reference,supplierReferenceTokens:[reference],quantity,widthMm,heightMm,originalDimensionsText:widthMm&&heightMm?`${widthMm}x${heightMm}mm`:null,unitPrice,totalPrice,currency,classification:'standard',includedInSupplierTotal:true,alternativeTo:null,classificationEvidence:null};
  return{id:randomUUID(),ordinal,...original,sourcePages:[...new Set(blocks.map(block=>block.pageNumber).filter(Number.isInteger))],sourceTrace:sourceTrace(document,blocks),confidence:'0.96',warnings:[],status:'extracted',originalExtractedSnapshot:original};
}

function parseInternormSchedule(document){
  const blocks=flatten(document),rows=[];
  for(let index=0;index<blocks.length-3;index+=1){if(!/^\d{3}$/.test(blocks[index].text)||!/^\d+[.,]\d+$/.test(blocks[index+1]?.text)||!/^Unit$/i.test(blocks[index+2]?.text)||!/^[A-Z]{2}[A-Z0-9-]+/i.test(blocks[index+3]?.text))continue;const next=blocks.findIndex((block,nextIndex)=>nextIndex>index+3&&/^\d{3}$/.test(block.text)&&/^\d+[.,]\d+$/.test(blocks[nextIndex+1]?.text||'')&&/^Unit$/i.test(blocks[nextIndex+2]?.text||'')&&/^[A-Z]{2}[A-Z0-9-]+/i.test(blocks[nextIndex+3]?.text||''));const end=next>=0?next:blocks.length;const segment=blocks.slice(index,end);const widthText=segment.find(block=>/^[, ]*(?:Width|Frame width):?$/i.test(block.text));const heightText=segment.find(block=>/^[, ]*(?:Height|Frame height):?$/i.test(block.text));const inline=segment.map(block=>block.text).join(' ').match(/Element width:\s*(\d+)mm,?\s*Element height:\s*(\d+)mm/i);const width=inline?Number(inline[1]):widthText?Number(segment[segment.indexOf(widthText)+1]?.text.match(/\d+/)?.[0]||0)||null:null;const height=inline?Number(inline[2]):heightText?Number(segment[segment.indexOf(heightText)+1]?.text.match(/\d+/)?.[0]||0)||null:null;const reference=blocks[index+3].text.match(/^[A-Z]{2}[A-Z0-9-]+/i)?.[0]||blocks[index+3].text.replace(/:$/,'');rows.push(row(document,{ordinal:rows.length,reference,quantity:integerQuantity(blocks[index+1].text),widthMm:width,heightMm:height,unitPrice:null,totalPrice:null,currency:'GBP',blocks:segment}));}
  return{adapter:'internorm_schedule_v1',supplier:'Glass Worx / Internorm',documentType:'window_schedule',quotation:{supplierQuotationNumber:blocks.find(block=>/^Offer number:/i.test(block.text))?.text.split(':').slice(1).join(':').trim()||null,supplierRevision:null,fullQuotationReference:blocks.find(block=>/^Offer number:/i.test(block.text))?.text.split(':').slice(1).join(':').trim()||null,warnings:[]},metadata:{supplierCustomer:cleanMetadataValue(blocks.find(block=>/^Mr\s+/i.test(block.text))?.text),projectReference:cleanMetadataValue(blocks.find(block=>/Schedule$/i.test(block.text))?.text.replace(/\s*-\s*Schedule$/i,'')),quotationDate:dateIso(blocks.find(block=>/^\d{2}\.\d{2}\.\d{4}$/.test(block.text))?.text)},rows,warnings:rows.length?[]:['Internorm schedule positions were not detected.']};
}

function parseEkoItemised(document,variant){
  const pages=document.pages,rows=[];
  const segments=variant==='eko'?(()=>{const blocks=flatten(document),markers=blocks.map((block,index)=>/^(?:Window|Door)\s+\d{3}$/i.test(block.text)?index:-1).filter(index=>index>=0);return markers.map((start,index)=>blocks.slice(start,markers[index+1]??blocks.length));})():pages.map(page=>page.blocks.map(block=>({...block,text:String(block.text).trim(),pageNumber:page.pageNumber})).filter(block=>block.text));
  for(const blocks of segments){const markerIndex=blocks.findIndex(block=>/^(?:Window|Door)\s+\d{3}$/i.test(block.text));if(markerIndex<0)continue;const marker=blocks[markerIndex],quantityBlock=blocks.slice(markerIndex+1).find(block=>/^(?:Qty\s*:|Quantity:)/i.test(block.text));const priceLabel=blocks.findIndex(block=>/^Price$|^Window price$/i.test(block.text));const priceBlock=priceLabel>=0?blocks.slice(priceLabel+1).find(block=>decimal(block.text)!=null):null;const dimensions=blocks.find(block=>/^Dimensions\s+\d+\s*mm\s*x\s*\d+\s*mm$/i.test(block.text))?.text.match(/(\d+)\s*mm\s*x\s*(\d+)\s*mm/i);let width=dimensions?Number(dimensions[1]):null,height=dimensions?Number(dimensions[2]):null;if(variant==='gutmann'){const diagram=blocks.slice(0,markerIndex).filter(block=>/^\d{3,4}$/.test(block.text)).map(block=>Number(block.text));if(diagram.length){width=Math.max(...diagram);height=diagram.filter(value=>value!==width).sort((a,b)=>b-a)[0]||null;}}const reference=marker.text.replace(/^(Window|Door)\s+/i,'');const totalPrice=decimal(priceBlock?.text);rows.push(row(document,{ordinal:rows.length,reference,quantity:integerQuantity(quantityBlock?.text.split(':').slice(1).join(':')),widthMm:width,heightMm:height,unitPrice:totalPrice,totalPrice,currency:'GBP',blocks}));}
  const all=flatten(document),quotationText=variant==='gutmann'?all.find(block=>/Price details\s+WEB\//i.test(block.text))?.text:all.find(block=>/^Quotation\s+OF\//i.test(block.text))?.text;const full=quotationText?.match(/(?:WEB|OF)\/\d+\/\d+/i)?.[0]||null;const client=variant==='gutmann'?all[all.findIndex(block=>/^Client:$/i.test(block.text))+1]?.text:all.find(block=>/^ECOFENSTER LTD/i.test(block.text))?.text;const project=variant==='gutmann'?all.find(block=>/^Your reference:/i.test(block.text))?.text.split(':').slice(1).join(':'):null;const date=variant==='gutmann'?all.find(block=>/^\d{2}\/\d{2}\/\d{4}$/.test(block.text))?.text:all.find(block=>/^\d{2}\/\d{2}\/\d{4}$/.test(block.text))?.text;
  return{adapter:variant==='gutmann'?'gutmann_web_v1':'eko_okna_winpro_v1',supplier:variant==='gutmann'?'Ecofenster / Gutmann':'EKO-OKNA',documentType:'complete_quotation',quotation:{supplierQuotationNumber:full,supplierRevision:null,fullQuotationReference:full,warnings:[]},metadata:{supplierCustomer:cleanMetadataValue(client),projectReference:cleanMetadataValue(project),quotationDate:dateIso(date)},rows,warnings:rows.length?[]:['Itemised PDF positions were not detected.']};
}

function parseGlassWorxCover(document){const blocks=flatten(document),reference=blocks.find(block=>/^25\s*-\s*\d+\s*-/i.test(block.text))?.text||null,preparedFor=blocks[blocks.findIndex(block=>/^Prepared for$/i.test(block.text))+1]?.text||null,date=blocks.find(block=>/^\d{2}\.\d{2}\.\d{4}$/.test(block.text))?.text;return{adapter:'glass_worx_cover_v1',supplier:'Glass Worx',documentType:'quotation_letter',quotation:{supplierQuotationNumber:cleanMetadataValue(reference),supplierRevision:null,fullQuotationReference:cleanMetadataValue(reference),warnings:[]},metadata:{supplierCustomer:cleanMetadataValue(preparedFor),projectReference:cleanMetadataValue(reference),quotationDate:dateIso(date)},rows:[],warnings:[]};}

const adapters=[
  {recognizes:text=>/Glass Worx Limited[\s\S]*Offer number:\s*\d+/i.test(text)&&/\bPos\.\s*\nQuantity\b/i.test(text),parse:parseInternormSchedule},
  {recognizes:text=>/Glass Worx Ltd[\s\S]*YOUR PROJECT COSTS/i.test(text),parse:parseGlassWorxCover},
  {recognizes:text=>/EKO-OKNA S\.A\.[\s\S]*Quotation\s+OF\//i.test(text),parse:document=>parseEkoItemised(document,'eko')},
  {recognizes:text=>/Price details\s+WEB\//i.test(text)&&/\[GUTMANN\]/i.test(text),parse:document=>parseEkoItemised(document,'gutmann')},
];

export function parsePdfSupplierFields(document){if(document.mediaType!=='application/pdf')return null;const text=textOf(document);const adapter=adapters.find(candidate=>candidate.recognizes(text));return adapter?adapter.parse(document):null;}

function summary(document,{currency,finalSupplierTotal,productSubtotal=null}){const blocks=flatten(document),original={currency, totalQuantity:null,totalQuantityUnit:null,totalAreaSquareMetres:null,productSubtotal,additionalItemsSubtotal:null,deliveryTotal:null,vatTotal:null,finalSupplierTotal,averageUValue:null,totalWeightKg:null,closingNotes:null};return{id:randomUUID(),...original,sourceTrace:sourceTrace(document,blocks.filter(block=>/total|net price|cost \(excl/i.test(block.text))),warnings:[],confidence:0.96,status:'extracted',originalExtractedSnapshot:original};}
export function parsePdfSupplierSummary(document,positionRows=[]){
  const parsed=parsePdfSupplierFields(document);if(!parsed)return null;const blocks=flatten(document);
  if(parsed.adapter==='internorm_schedule_v1')return{summary:null,additionalItems:[],warnings:['Line prices and quotation total are supplied separately.']};
  if(parsed.adapter==='glass_worx_cover_v1'){
    const packageValues=blocks.filter(block=>/^\d{1,3},\d{3}\.\d{2}$/.test(block.text)).map(block=>decimal(block.text)).slice(-3);const selected=packageValues[1]??packageValues[0]??null;
    const labels=['Bronze / Supply Only','Silver / Install Support','Gold / Full Installation'];const value=summary(document,{currency:'GBP',finalSupplierTotal:selected});value.comparisonTotals=packageValues.map((amount,index)=>({classification:'package_option',label:labels[index],amount,currency:'GBP',includedInSupplierTotal:index===1,selected:index===1,sourceTrace:sourceTrace(document,blocks.filter(block=>decimal(block.text)===amount))}));value.originalExtractedSnapshot.comparisonTotals=value.comparisonTotals;value.warnings=['Line-level reconciliation is unavailable because the authoritative schedule is unpriced.'];value.status='needs_review';value.reconciliation={positionSubtotal:null,additionalSubtotal:null,deliverySubtotal:null,expectedFinal:null,reconciled:false,warnings:value.warnings};return{summary:value,additionalItems:[],warnings:value.warnings};
  }
  const totalLabel=blocks.findIndex(block=>parsed.adapter==='gutmann_web_v1'?/^Net price$/i.test(block.text):/^Totals$/i.test(block.text));const candidates=blocks.slice(Math.max(0,totalLabel),totalLabel+40).map(block=>decimal(block.text)).filter(Boolean);const final=candidates[0];const productSubtotal=positionRows.every(item=>item.totalPrice!=null)?positionRows.reduce((sum,item)=>sum+Number(item.totalPrice),0).toFixed(2):null;const value=summary(document,{currency:'GBP',finalSupplierTotal:final,productSubtotal});const reconciled=productSubtotal!=null&&final!=null&&Number(productSubtotal)===Number(final);value.reconciliation={positionSubtotal:productSubtotal,additionalSubtotal:null,deliverySubtotal:null,expectedFinal:productSubtotal,reconciled,warnings:reconciled?[]:['Supplied final total does not reconcile with the extracted commercial evidence.']};value.warnings=value.reconciliation.warnings;value.status=value.warnings.length?'needs_review':'extracted';return{summary:value,additionalItems:[],warnings:value.warnings};
}

export { cleanMetadataValue };
