import { randomUUID } from 'node:crypto';
import { FIELD_PARSER_VERSION } from './commercialFieldParser.js';
import { EXTRACTOR_VERSION } from './documentExtraction.js';

const parse = (value, fallback) => { try { return JSON.parse(value); } catch { return fallback; } };
const mapRun = (row) => ({ id: row.id, sessionId: row.session_id, attachmentId: row.attachment_id, attachmentFileName: row.attachment_file_name ?? null, rowCount: Number(row.row_count || 0), selectedRowCount: Number(row.selected_row_count || 0), warningCount: Number(row.warning_count ?? parse(row.warnings_json, []).length), extractorName: row.extractor_name, extractorVersion: row.extractor_version, fieldParserName: row.field_parser_name, fieldParserVersion: row.field_parser_version, status: row.status, startedAt: row.started_at, completedAt: row.completed_at, warnings: parse(row.warnings_json, []), errorCode: row.error_code, errorMessage: row.error_message, quotationProposal: { supplierQuotationNumber: row.quotation_number, supplierRevision: row.supplier_revision, fullQuotationReference: row.full_quotation_reference, warnings: parse(row.quotation_warnings_json, []) }, selected: Boolean(row.selected), createdAt: row.created_at });
const mapRow = (row) => ({ id: row.id, sessionId: row.session_id, extractionRunId: row.extraction_run_id, attachmentId: row.attachment_id, ordinal: row.ordinal, displayReference: row.display_reference, originalReferenceText: row.original_reference_text, supplierReferenceTokens: parse(row.supplier_reference_tokens_json, []), quantity: row.quantity, widthMm: row.width_mm, heightMm: row.height_mm, originalDimensionsText: row.original_dimensions_text, unitPrice: row.unit_price_amount, totalPrice: row.total_price_amount, currency: row.currency, sourcePages: parse(row.source_pages_json, []), sourceTrace: parse(row.source_trace_json, []), confidence: row.confidence == null ? null : Number(row.confidence), warnings: parse(row.warnings_json, []), reviewWarnings: parse(row.review_warnings_json, []), selectedForFutureUse: Boolean(row.selected_for_future_use) && row.status !== 'rejected', status: row.status, createdAt: row.created_at, correctedAt: row.corrected_at, correctedBy: row.corrected_by, originalExtractedSnapshot: parse(row.original_extracted_snapshot_json, {}) });
const plainDecimal = /^(?:0|[1-9]\d*)(?:\.\d+)?$/;
function decimalParts(value) { const [whole, fraction = ''] = String(value).split('.'); return { digits: BigInt(`${whole}${fraction}`), scale: fraction.length }; }
function multiplyMatches(unitPrice, quantity, totalPrice) { const unit = decimalParts(unitPrice); const total = decimalParts(totalPrice); const scale = Math.max(unit.scale, total.scale); const left = unit.digits * BigInt(quantity) * (10n ** BigInt(scale - unit.scale)); const right = total.digits * (10n ** BigInt(scale - total.scale)); return left === right; }
function validateReviewValues(input, status = 'extracted') { const issues = []; const reference = String(input.displayReference ?? '').trim(); const positiveInteger = (value) => Number.isInteger(Number(value)) && Number(value) > 0; if (!reference) issues.push({ field: 'displayReference', message: 'Reference is required.' }); for (const [field, label] of [['widthMm','Width'],['heightMm','Height'],['quantity','Quantity']]) if (!positiveInteger(input[field])) issues.push({ field, message: `${label} must be a positive whole number.` }); for (const [field, label] of [['unitPrice','Unit price'],['totalPrice','Total price']]) if (!plainDecimal.test(String(input[field] ?? ''))) issues.push({ field, message: `${label} must be a non-negative decimal without exponent notation.` }); if (status === 'rejected' && input.selectedForFutureUse) issues.push({ field: 'selectedForFutureUse', message: 'Rejected rows cannot be selected for future use.' }); const reviewWarnings = issues.length === 0 && !multiplyMatches(String(input.unitPrice), Number(input.quantity), String(input.totalPrice)) ? ['Supplied total does not equal unit price × quantity.'] : []; return { valid: issues.length === 0, issues, values: { displayReference: reference, widthMm: Number(input.widthMm), heightMm: Number(input.heightMm), quantity: Number(input.quantity), unitPrice: String(input.unitPrice), totalPrice: String(input.totalPrice), selectedForFutureUse: Boolean(input.selectedForFutureUse) }, reviewWarnings }; }

export function createSupplierImportLabExtractionService(db) {
  async function createRun(sessionId, attachmentId) {
    const attachment = await db.get('SELECT * FROM supplier_import_lab_attachments WHERE id=? AND session_id=?', attachmentId, sessionId); if (!attachment) return null;
    if (await db.get("SELECT id FROM supplier_import_lab_extraction_runs WHERE session_id=? AND attachment_id=? AND status IN ('queued','running')", sessionId, attachmentId)) throw Object.assign(new Error('Extraction is already running.'), { code: 'extraction_in_progress' });
    if (!attachment.parser_eligible) throw Object.assign(new Error('Attachment is not eligible for extraction.'), { code: 'attachment_not_eligible' });
    const now = new Date().toISOString(); const id = randomUUID();
    await db.run(`INSERT INTO supplier_import_lab_extraction_runs(id,session_id,attachment_id,extractor_name,extractor_version,field_parser_name,field_parser_version,status,started_at,warnings_json,quotation_warnings_json,selected,created_at) VALUES(?,?,?,?,?,?,?,?,?,'[]','[]',0,?)`, id, sessionId, attachmentId, attachment.media_type === 'application/pdf' ? 'pdfjs-dist' : 'mammoth', EXTRACTOR_VERSION, 'core-commercial-fields', FIELD_PARSER_VERSION, 'running', now, now);
    await db.run("UPDATE supplier_import_lab_sessions SET status='extraction_pending',updated_at=? WHERE id=? AND archived_at IS NULL", now, sessionId);
    return { id, attachment: { id: attachment.id, sessionId, mediaType: attachment.media_type, storageKey: attachment.storage_key } };
  }
  const runSelect = `SELECT r.*,a.original_file_name attachment_file_name,(SELECT COUNT(*) FROM supplier_import_lab_extracted_rows x WHERE x.extraction_run_id=r.id) row_count,(SELECT COUNT(*) FROM supplier_import_lab_extracted_rows x WHERE x.extraction_run_id=r.id AND x.selected_for_future_use=1 AND x.status<>'rejected') selected_row_count,(json_array_length(r.warnings_json)+(SELECT COUNT(*) FROM supplier_import_lab_extracted_rows x WHERE x.extraction_run_id=r.id AND (json_array_length(x.warnings_json)>0 OR json_array_length(x.review_warnings_json)>0))) warning_count FROM supplier_import_lab_extraction_runs r JOIN supplier_import_lab_attachments a ON a.id=r.attachment_id`;
  async function getRun(sessionId, runId) { const row = await db.get(`${runSelect} WHERE r.id=? AND r.session_id=?`, runId, sessionId); return row ? mapRun(row) : null; }
  async function completeRun(runId, document, parsed) {
    const run = await db.get('SELECT * FROM supplier_import_lab_extraction_runs WHERE id=?', runId); if (!run) throw new Error('Extraction run not found.'); const now = new Date().toISOString(); const warnings = [...document.warnings, ...parsed.warnings]; const status = warnings.length || parsed.rows.some((row) => row.warnings.length) ? 'completed_with_warnings' : 'completed';
    await db.exec('BEGIN IMMEDIATE'); try {
      await db.run('INSERT INTO supplier_import_lab_extracted_documents(extraction_run_id,document_json) VALUES(?,?)', runId, JSON.stringify(document));
      for (const row of parsed.rows) await db.run(`INSERT INTO supplier_import_lab_extracted_rows(id,session_id,extraction_run_id,attachment_id,ordinal,display_reference,original_reference_text,supplier_reference_tokens_json,quantity,width_mm,height_mm,original_dimensions_text,unit_price_amount,total_price_amount,currency,source_pages_json,source_trace_json,confidence,warnings_json,status,created_at,original_extracted_snapshot_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`, randomUUID(), run.session_id, runId, run.attachment_id, row.ordinal, row.displayReference, row.originalReferenceText, JSON.stringify(row.supplierReferenceTokens), row.quantity, row.widthMm, row.heightMm, row.originalDimensionsText, row.unitPrice, row.totalPrice, row.currency, JSON.stringify(row.sourcePages), JSON.stringify(row.sourceTrace), row.confidence, JSON.stringify(row.warnings), row.status, now, JSON.stringify(row.originalExtractedSnapshot));
      await db.run('UPDATE supplier_import_lab_extraction_runs SET selected=0 WHERE session_id=?', run.session_id);
      await db.run(`UPDATE supplier_import_lab_extraction_runs SET status=?,completed_at=?,warnings_json=?,quotation_number=?,supplier_revision=?,full_quotation_reference=?,quotation_warnings_json=?,selected=1 WHERE id=?`, status, now, JSON.stringify(warnings), parsed.quotation.supplierQuotationNumber, parsed.quotation.supplierRevision, parsed.quotation.fullQuotationReference, JSON.stringify(parsed.quotation.warnings), runId);
      await db.run("UPDATE supplier_import_lab_sessions SET status='extracted',updated_at=? WHERE id=?", now, run.session_id); await db.exec('COMMIT');
    } catch (error) { await db.exec('ROLLBACK'); throw error; }
    return getRun(run.session_id, runId);
  }
  async function failRun(runId, status, code, message) { const row = await db.get('SELECT session_id FROM supplier_import_lab_extraction_runs WHERE id=?', runId); if (!row) return; const now = new Date().toISOString(); await db.run('UPDATE supplier_import_lab_extraction_runs SET status=?,completed_at=?,error_code=?,error_message=? WHERE id=?', status, now, code, message, runId); await db.run("UPDATE supplier_import_lab_sessions SET status='failed',updated_at=? WHERE id=?", now, row.session_id); }
  async function listRuns(sessionId) { return (await db.all(`${runSelect} WHERE r.session_id=? ORDER BY r.created_at DESC,r.rowid DESC`, sessionId)).map(mapRun); }
  async function listRows(sessionId, runId) { if (!await getRun(sessionId, runId)) return null; return (await db.all('SELECT * FROM supplier_import_lab_extracted_rows WHERE session_id=? AND extraction_run_id=? ORDER BY ordinal', sessionId, runId)).map(mapRow); }
  async function selectRun(sessionId, runId) { if (!await getRun(sessionId, runId)) return null; await db.exec('BEGIN IMMEDIATE'); try { await db.run('UPDATE supplier_import_lab_extraction_runs SET selected=0 WHERE session_id=?', sessionId); await db.run("UPDATE supplier_import_lab_extraction_runs SET selected=1 WHERE id=? AND session_id=? AND status IN ('completed','completed_with_warnings')", runId, sessionId); await db.exec('COMMIT'); } catch (error) { await db.exec('ROLLBACK'); throw error; } return getRun(sessionId, runId); }
  async function bulkCorrectRows(sessionId, inputs, reviewerId = 'admin-beta') { if (!Array.isArray(inputs) || inputs.length === 0) throw Object.assign(new Error('At least one row is required.'), { code: 'invalid_correction', issues: [] }); const ids = inputs.map((item) => String(item.rowId || '')); if (new Set(ids).size !== ids.length) throw Object.assign(new Error('Duplicate row IDs are not allowed.'), { code: 'invalid_correction', issues: [] }); const placeholders = ids.map(() => '?').join(','); const rows = await db.all(`SELECT * FROM supplier_import_lab_extracted_rows WHERE session_id=? AND id IN (${placeholders})`, sessionId, ...ids); if (rows.length !== ids.length) return null; const byId = new Map(rows.map((row) => [row.id, row])); const checked = inputs.map((input) => ({ input, row: byId.get(input.rowId), result: validateReviewValues(input, byId.get(input.rowId).status) })); const issues = checked.flatMap(({ input, result }) => result.issues.map((issue) => ({ rowId: input.rowId, ...issue }))); if (issues.length) throw Object.assign(new Error('One or more corrected rows are invalid.'), { code: 'invalid_correction', issues }); const now = new Date().toISOString(); await db.exec('BEGIN IMMEDIATE'); try { for (const { input, result } of checked) { const v = result.values; await db.run(`UPDATE supplier_import_lab_extracted_rows SET display_reference=?,width_mm=?,height_mm=?,quantity=?,unit_price_amount=?,total_price_amount=?,selected_for_future_use=?,review_warnings_json=?,status=CASE WHEN status='rejected' THEN status ELSE 'corrected' END,corrected_at=?,corrected_by=? WHERE id=? AND session_id=?`, v.displayReference, v.widthMm, v.heightMm, v.quantity, v.unitPrice, v.totalPrice, v.selectedForFutureUse ? 1 : 0, JSON.stringify(result.reviewWarnings), now, reviewerId, input.rowId, sessionId); } await db.exec('COMMIT'); } catch (error) { await db.exec('ROLLBACK'); throw error; } return (await db.all(`SELECT * FROM supplier_import_lab_extracted_rows WHERE session_id=? AND id IN (${placeholders}) ORDER BY ordinal`, sessionId, ...ids)).map(mapRow); }
  async function correctRow(sessionId, rowId, input, reviewerId = 'admin-beta') { const row = await db.get('SELECT * FROM supplier_import_lab_extracted_rows WHERE id=? AND session_id=?', rowId, sessionId); if (!row) return null; const merged = { rowId, displayReference: Object.hasOwn(input,'displayReference') ? input.displayReference : row.display_reference, widthMm: Object.hasOwn(input,'widthMm') ? input.widthMm : row.width_mm, heightMm: Object.hasOwn(input,'heightMm') ? input.heightMm : row.height_mm, quantity: Object.hasOwn(input,'quantity') ? input.quantity : row.quantity, unitPrice: Object.hasOwn(input,'unitPrice') ? input.unitPrice : row.unit_price_amount, totalPrice: Object.hasOwn(input,'totalPrice') ? input.totalPrice : row.total_price_amount, selectedForFutureUse: Object.hasOwn(input,'selectedForFutureUse') ? input.selectedForFutureUse : Boolean(row.selected_for_future_use) }; const updated = await bulkCorrectRows(sessionId, [merged], reviewerId); return updated?.[0] ?? null; }
  const hasAttachmentEvidence = async (sessionId, attachmentId) => Boolean(await db.get('SELECT 1 FROM supplier_import_lab_extraction_runs WHERE session_id=? AND attachment_id=? LIMIT 1', sessionId, attachmentId));
  const hasSessionEvidence = async (sessionId) => Boolean(await db.get('SELECT 1 FROM supplier_import_lab_extraction_runs WHERE session_id=? LIMIT 1', sessionId));
  return { createRun, completeRun, failRun, listRuns, getRun, listRows, selectRun, correctRow, bulkCorrectRows, hasAttachmentEvidence, hasSessionEvidence };
}
