import { randomUUID } from 'node:crypto';

const SESSION_STATUSES = new Set(['draft', 'uploaded', 'extraction_pending', 'extracted', 'failed', 'archived']);
const EDITABLE_STATUSES = new Set(['draft', 'uploaded', 'extraction_pending', 'extracted']);
const ATTACHMENT_ROLES = new Set(['original_quote', 'supporting_document', 'supplier_drawing']);

function optionalText(value) { const text = String(value ?? '').trim(); return text || null; }
function currency(value) { const result = String(value ?? '').trim().toUpperCase(); if (!/^[A-Z]{3}$/.test(result)) throw Object.assign(new Error('Currency must be a three-letter code.'), { code: 'invalid_session' }); return result; }
function mapSession(row, attachmentCount = Number(row.attachment_count || 0)) { return { id: row.id, supplierCode: row.supplier_code, supplierName: row.supplier_name, supplierQuotationNumber: row.supplier_quotation_number, supplierRevision: row.supplier_revision, fullQuotationReference: row.full_quotation_reference, quotationDate: row.quotation_date, currency: row.currency, status: row.status, attachmentCount, createdAt: row.created_at, updatedAt: row.updated_at, archivedAt: row.archived_at }; }
function mapAttachment(row) { return { id: row.id, sessionId: row.session_id, role: row.role, originalFileName: row.original_file_name, mediaType: row.media_type, sizeBytes: row.size_bytes, sha256: row.sha256, parserEligible: Boolean(row.parser_eligible), createdAt: row.created_at }; }

export function createSupplierImportLabService(db) {
  async function sessionRow(sessionId) { return db.get('SELECT * FROM supplier_import_lab_sessions WHERE id=?', sessionId); }
  async function attachmentRow(sessionId, attachmentId) { return db.get('SELECT * FROM supplier_import_lab_attachments WHERE id=? AND session_id=?', attachmentId, sessionId); }
  async function createSession(input) {
    const supplierName = String(input.supplierName ?? '').trim(); if (!supplierName) throw Object.assign(new Error('Supplier name is required.'), { code: 'invalid_session' });
    const now = new Date().toISOString(); const session = { id: randomUUID(), supplierCode: optionalText(input.supplierCode), supplierName, supplierQuotationNumber: optionalText(input.supplierQuotationNumber), supplierRevision: optionalText(input.supplierRevision), fullQuotationReference: optionalText(input.fullQuotationReference), quotationDate: optionalText(input.quotationDate), currency: currency(input.currency), status: 'draft', createdAt: now, updatedAt: now, archivedAt: null };
    await db.run(`INSERT INTO supplier_import_lab_sessions(id,supplier_code,supplier_name,supplier_quotation_number,supplier_revision,full_quotation_reference,quotation_date,currency,status,created_at,updated_at,archived_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,NULL)`, session.id, session.supplierCode, session.supplierName, session.supplierQuotationNumber, session.supplierRevision, session.fullQuotationReference, session.quotationDate, session.currency, session.status, now, now);
    return { ...session, attachmentCount: 0 };
  }
  async function listSessions({ includeArchived = false } = {}) { const rows = await db.all(`SELECT s.*,COUNT(a.id) attachment_count FROM supplier_import_lab_sessions s LEFT JOIN supplier_import_lab_attachments a ON a.session_id=s.id ${includeArchived ? '' : 'WHERE s.archived_at IS NULL'} GROUP BY s.id ORDER BY s.updated_at DESC,s.rowid DESC`); return rows.map((row) => mapSession(row)); }
  async function getSession(sessionId) { const row = await db.get('SELECT s.*,(SELECT COUNT(*) FROM supplier_import_lab_attachments a WHERE a.session_id=s.id) attachment_count FROM supplier_import_lab_sessions s WHERE s.id=?', sessionId); return row ? mapSession(row) : null; }
  async function updateSession(sessionId, input) { const row = await sessionRow(sessionId); if (!row) return null; if (!EDITABLE_STATUSES.has(row.status) || row.archived_at) throw Object.assign(new Error('Session is read-only.'), { code: 'invalid_session_state' }); const nextStatus = input.status == null ? row.status : String(input.status); if (!SESSION_STATUSES.has(nextStatus) || nextStatus === 'archived') throw Object.assign(new Error('Invalid session status.'), { code: 'invalid_session' }); const supplierName = input.supplierName == null ? row.supplier_name : String(input.supplierName).trim(); if (!supplierName) throw Object.assign(new Error('Supplier name is required.'), { code: 'invalid_session' }); const now = new Date().toISOString(); await db.run(`UPDATE supplier_import_lab_sessions SET supplier_code=?,supplier_name=?,supplier_quotation_number=?,supplier_revision=?,full_quotation_reference=?,quotation_date=?,currency=?,status=?,updated_at=? WHERE id=?`, input.supplierCode == null ? row.supplier_code : optionalText(input.supplierCode), supplierName, input.supplierQuotationNumber == null ? row.supplier_quotation_number : optionalText(input.supplierQuotationNumber), input.supplierRevision == null ? row.supplier_revision : optionalText(input.supplierRevision), input.fullQuotationReference == null ? row.full_quotation_reference : optionalText(input.fullQuotationReference), input.quotationDate == null ? row.quotation_date : optionalText(input.quotationDate), input.currency == null ? row.currency : currency(input.currency), nextStatus, now, sessionId); return getSession(sessionId); }
  async function archiveSession(sessionId) { const row = await sessionRow(sessionId); if (!row) return null; if (row.archived_at) return getSession(sessionId); const now = new Date().toISOString(); await db.run(`UPDATE supplier_import_lab_sessions SET status='archived',archived_at=?,updated_at=? WHERE id=?`, now, now, sessionId); return getSession(sessionId); }
  async function listAttachments(sessionId) { if (!(await sessionRow(sessionId))) return null; return (await db.all('SELECT * FROM supplier_import_lab_attachments WHERE session_id=? ORDER BY created_at,rowid', sessionId)).map(mapAttachment); }
  async function getAttachment(sessionId, attachmentId) { const row = await attachmentRow(sessionId, attachmentId); return row ? { metadata: mapAttachment(row), storageKey: row.storage_key } : null; }
  async function insertAttachments(sessionId, records) { const session = await sessionRow(sessionId); if (!session) throw Object.assign(new Error('Session not found.'), { code: 'session_not_found' }); if (session.archived_at) throw Object.assign(new Error('Archived session is read-only.'), { code: 'invalid_session_state' }); await db.exec('BEGIN IMMEDIATE'); try { for (const item of records) { if (!ATTACHMENT_ROLES.has(item.role)) throw Object.assign(new Error('Invalid attachment role.'), { code: 'unsupported_file_type' }); await db.run(`INSERT INTO supplier_import_lab_attachments(id,session_id,role,original_file_name,media_type,size_bytes,sha256,storage_key,parser_eligible,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`, item.id, sessionId, item.role, item.originalFileName, item.mediaType, item.sizeBytes, item.sha256, item.storageKey, item.parserEligible ? 1 : 0, item.createdAt); } const now = new Date().toISOString(); await db.run(`UPDATE supplier_import_lab_sessions SET status='uploaded',updated_at=? WHERE id=?`, now, sessionId); await db.exec('COMMIT'); return records.map(({ storageKey: _storageKey, ...item }) => item); } catch (error) { await db.exec('ROLLBACK'); throw error; } }
  async function deleteAttachmentMetadata(sessionId, attachmentId) { const row = await attachmentRow(sessionId, attachmentId); if (!row) return null; const session = await sessionRow(sessionId); if (session.archived_at) throw Object.assign(new Error('Archived session is read-only.'), { code: 'invalid_session_state' }); if (await db.get('SELECT 1 FROM supplier_import_lab_extraction_runs WHERE session_id=? AND attachment_id=? LIMIT 1', sessionId, attachmentId)) throw Object.assign(new Error('Attachment has extraction evidence and cannot be removed.'), { code: 'attachment_in_use' }); const result = await db.run('DELETE FROM supplier_import_lab_attachments WHERE id=? AND session_id=?', attachmentId, sessionId); return result.changes ? { storageKey: row.storage_key } : null; }
  async function deleteSessionMetadata(sessionId) { const session = await sessionRow(sessionId); if (!session) return null; if (session.archived_at) throw Object.assign(new Error('Archived sessions cannot be deleted.'), { code: 'invalid_session_state' }); if (await db.get('SELECT 1 FROM supplier_import_lab_extraction_runs WHERE session_id=? LIMIT 1', sessionId)) throw Object.assign(new Error('Session has extraction evidence and must be archived.'), { code: 'session_in_use' }); const attachments = await db.all('SELECT * FROM supplier_import_lab_attachments WHERE session_id=?', sessionId); const result = await db.run('DELETE FROM supplier_import_lab_sessions WHERE id=?', sessionId); return result.changes ? { attachments: attachments.map((row) => ({ storageKey: row.storage_key })) } : null; }
  return { createSession, listSessions, getSession, updateSession, archiveSession, listAttachments, getAttachment, insertAttachments, deleteAttachmentMetadata, deleteSessionMetadata };
}
