import { randomUUID } from 'node:crypto';
import { FIELD_PARSER_VERSION } from './commercialFieldParser.js';
import { EXTRACTOR_VERSION } from './documentExtraction.js';

const parse = (value, fallback) => { try { return JSON.parse(value); } catch { return fallback; } };
const mapRun = (row) => ({ id: row.id, sessionId: row.session_id, attachmentId: row.attachment_id, extractorName: row.extractor_name, extractorVersion: row.extractor_version, fieldParserName: row.field_parser_name, fieldParserVersion: row.field_parser_version, status: row.status, startedAt: row.started_at, completedAt: row.completed_at, warnings: parse(row.warnings_json, []), errorCode: row.error_code, errorMessage: row.error_message, quotationProposal: { supplierQuotationNumber: row.quotation_number, supplierRevision: row.supplier_revision, fullQuotationReference: row.full_quotation_reference, warnings: parse(row.quotation_warnings_json, []) }, selected: Boolean(row.selected), createdAt: row.created_at });
const mapRow = (row) => ({ id: row.id, sessionId: row.session_id, extractionRunId: row.extraction_run_id, attachmentId: row.attachment_id, ordinal: row.ordinal, displayReference: row.display_reference, originalReferenceText: row.original_reference_text, supplierReferenceTokens: parse(row.supplier_reference_tokens_json, []), quantity: row.quantity, widthMm: row.width_mm, heightMm: row.height_mm, originalDimensionsText: row.original_dimensions_text, unitPrice: row.unit_price_amount, totalPrice: row.total_price_amount, currency: row.currency, sourcePages: parse(row.source_pages_json, []), sourceTrace: parse(row.source_trace_json, []), confidence: row.confidence == null ? null : Number(row.confidence), warnings: parse(row.warnings_json, []), status: row.status, createdAt: row.created_at, correctedAt: row.corrected_at, correctedBy: row.corrected_by, originalExtractedSnapshot: parse(row.original_extracted_snapshot_json, {}) });

export function createSupplierImportLabExtractionService(db) {
  async function createRun(sessionId, attachmentId) {
    const attachment = await db.get('SELECT * FROM supplier_import_lab_attachments WHERE id=? AND session_id=?', attachmentId, sessionId); if (!attachment) return null;
    if (await db.get("SELECT id FROM supplier_import_lab_extraction_runs WHERE session_id=? AND attachment_id=? AND status IN ('queued','running')", sessionId, attachmentId)) throw Object.assign(new Error('Extraction is already running.'), { code: 'extraction_in_progress' });
    if (!attachment.parser_eligible) throw Object.assign(new Error('Attachment is not eligible for extraction.'), { code: 'attachment_not_eligible' });
    const now = new Date().toISOString(); const id = randomUUID();
    await db.run(`INSERT INTO supplier_import_lab_extraction_runs(id,session_id,attachment_id,extractor_name,extractor_version,field_parser_name,field_parser_version,status,started_at,warnings_json,quotation_warnings_json,selected,created_at) VALUES(?,?,?,?,?,?,?,?,?,'[]','[]',0,?)`, id, sessionId, attachmentId, attachment.media_type === 'application/pdf' ? 'pdfjs-dist' : 'mammoth', EXTRACTOR_VERSION, 'core-commercial-fields', FIELD_PARSER_VERSION, 'running', now, now);
    await db.run("UPDATE supplier_import_lab_sessions SET status='extraction_pending',updated_at=? WHERE id=? AND archived_at IS NULL", now, sessionId);
    return { id, attachment: { id: attachment.id, sessionId, mediaType: attachment.media_type, storageKey: attachment.storage_key } };
  }
  async function getRun(sessionId, runId) { const row = await db.get('SELECT * FROM supplier_import_lab_extraction_runs WHERE id=? AND session_id=?', runId, sessionId); return row ? mapRun(row) : null; }
  async function completeRun(runId, document, parsed) {
    const run = await db.get('SELECT * FROM supplier_import_lab_extraction_runs WHERE id=?', runId); if (!run) throw new Error('Extraction run not found.'); const now = new Date().toISOString(); const warnings = [...document.warnings, ...parsed.warnings]; const status = warnings.length || parsed.rows.some((row) => row.warnings.length) ? 'completed_with_warnings' : 'completed';
    await db.exec('BEGIN IMMEDIATE'); try {
      await db.run('INSERT INTO supplier_import_lab_extracted_documents(extraction_run_id,document_json) VALUES(?,?)', runId, JSON.stringify(document));
      for (const row of parsed.rows) await db.run(`INSERT INTO supplier_import_lab_extracted_rows(id,session_id,extraction_run_id,attachment_id,ordinal,display_reference,original_reference_text,supplier_reference_tokens_json,quantity,width_mm,height_mm,original_dimensions_text,unit_price_amount,total_price_amount,currency,source_pages_json,source_trace_json,confidence,warnings_json,status,created_at,original_extracted_snapshot_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`, randomUUID(), run.session_id, runId, run.attachment_id, row.ordinal, row.displayReference, row.originalReferenceText, JSON.stringify(row.supplierReferenceTokens), row.quantity, row.widthMm, row.heightMm, row.originalDimensionsText, row.unitPrice, row.totalPrice, row.currency, JSON.stringify(row.sourcePages), JSON.stringify(row.sourceTrace), row.confidence, JSON.stringify(row.warnings), row.status, now, JSON.stringify(row.originalExtractedSnapshot));
      await db.run('UPDATE supplier_import_lab_extraction_runs SET selected=0 WHERE session_id=?', run.session_id);
      await db.run(`UPDATE supplier_import_lab_extraction_runs SET status=?,completed_at=?,warnings_json=?,quotation_number=?,supplier_revision=?,full_quotation_reference=?,quotation_warnings_json=?,selected=1 WHERE id=?`, status, now, JSON.stringify(warnings), parsed.quotation.supplierQuotationNumber, parsed.quotation.supplierRevision, parsed.quotation.fullQuotationReference, JSON.stringify(parsed.quotation.warnings), runId);
      await db.run("UPDATE supplier_import_lab_sessions SET status='extracted',updated_at=? WHERE id=?", now, run.session_id); await db.exec('COMMIT');
    } catch (error) { await db.exec('ROLLBACK'); throw error; }
    return getRun(run.session_id, runId);
  }
  async function failRun(runId, status, code, message) { const row = await db.get('SELECT session_id FROM supplier_import_lab_extraction_runs WHERE id=?', runId); if (!row) return; const now = new Date().toISOString(); await db.run('UPDATE supplier_import_lab_extraction_runs SET status=?,completed_at=?,error_code=?,error_message=? WHERE id=?', status, now, code, message, runId); await db.run("UPDATE supplier_import_lab_sessions SET status='failed',updated_at=? WHERE id=?", now, row.session_id); }
  async function listRuns(sessionId) { return (await db.all('SELECT * FROM supplier_import_lab_extraction_runs WHERE session_id=? ORDER BY created_at DESC,rowid DESC', sessionId)).map(mapRun); }
  async function listRows(sessionId, runId) { if (!await getRun(sessionId, runId)) return null; return (await db.all('SELECT * FROM supplier_import_lab_extracted_rows WHERE session_id=? AND extraction_run_id=? ORDER BY ordinal', sessionId, runId)).map(mapRow); }
  async function selectRun(sessionId, runId) { if (!await getRun(sessionId, runId)) return null; await db.exec('BEGIN IMMEDIATE'); try { await db.run('UPDATE supplier_import_lab_extraction_runs SET selected=0 WHERE session_id=?', sessionId); await db.run("UPDATE supplier_import_lab_extraction_runs SET selected=1 WHERE id=? AND session_id=? AND status IN ('completed','completed_with_warnings')", runId, sessionId); await db.exec('COMMIT'); } catch (error) { await db.exec('ROLLBACK'); throw error; } return getRun(sessionId, runId); }
  async function correctRow(sessionId, rowId, input, reviewerId = 'admin-beta') { const row = await db.get('SELECT * FROM supplier_import_lab_extracted_rows WHERE id=? AND session_id=?', rowId, sessionId); if (!row) return null; const values = { displayReference: row.display_reference, quantity: row.quantity, widthMm: row.width_mm, heightMm: row.height_mm, unitPrice: row.unit_price_amount, totalPrice: row.total_price_amount }; for (const key of Object.keys(values)) if (Object.hasOwn(input, key)) values[key] = input[key] === '' ? null : input[key]; if (!String(values.displayReference || '').trim() || !Number.isInteger(Number(values.quantity)) || Number(values.quantity) <= 0 || !Number.isInteger(Number(values.widthMm)) || Number(values.widthMm) <= 0 || !Number.isInteger(Number(values.heightMm)) || Number(values.heightMm) <= 0 || !/^\d+(?:\.\d+)?$/.test(String(values.unitPrice)) || !/^\d+(?:\.\d+)?$/.test(String(values.totalPrice))) throw Object.assign(new Error('Corrected commercial fields are invalid.'), { code: 'invalid_correction' }); const now = new Date().toISOString(); await db.run(`UPDATE supplier_import_lab_extracted_rows SET display_reference=?,quantity=?,width_mm=?,height_mm=?,unit_price_amount=?,total_price_amount=?,status='corrected',corrected_at=?,corrected_by=? WHERE id=? AND session_id=?`, String(values.displayReference).trim(), Number(values.quantity), Number(values.widthMm), Number(values.heightMm), String(values.unitPrice), String(values.totalPrice), now, reviewerId, rowId, sessionId); return mapRow(await db.get('SELECT * FROM supplier_import_lab_extracted_rows WHERE id=?', rowId)); }
  const hasAttachmentEvidence = async (sessionId, attachmentId) => Boolean(await db.get('SELECT 1 FROM supplier_import_lab_extraction_runs WHERE session_id=? AND attachment_id=? LIMIT 1', sessionId, attachmentId));
  const hasSessionEvidence = async (sessionId) => Boolean(await db.get('SELECT 1 FROM supplier_import_lab_extraction_runs WHERE session_id=? LIMIT 1', sessionId));
  return { createRun, completeRun, failRun, listRuns, getRun, listRows, selectRun, correctRow, hasAttachmentEvidence, hasSessionEvidence };
}
