import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { apiFetch } from "../../services/api/apiClient";
import B92ConfiguratorShell from "../b92Configurator/B92ConfiguratorShell";
import { compileB92ConfiguratorStateToConfiguredPositionContract, hydrateB92ConfiguratorStateFromPosition, projectConfiguredPositionContractToLegacyPosition } from "../b92Configurator/b92ConfiguredPositionCompiler";
import type { B92ConfiguratorState } from "../b92Configurator/b92Configurator.types";
import type { EstimatePositionAction } from "./EstimateCommercialActionsContext";

type Position=Record<string,any>;
type Bridge={estimateId:string;clientId:string;positions:Position[];reviewRequired:Array<{position:Position;candidates:Position[]}>};
export type PositionWorkspaceControls={positions:Position[];startAdd:()=>void;startConfigure:(positionId:string)=>void;positionAction:(positionId:string,action:EstimatePositionAction)=>void};

export default function EstimatePositionBridge({estimateId,addRequest,refreshRequest,onChanged,children}:{estimateId:string;addRequest:number;refreshRequest:number;onChanged:()=>void;children:(controls:PositionWorkspaceControls)=>ReactNode}){
  const [bridge,setBridge]=useState<Bridge|null>(null),[editing,setEditing]=useState<Position|null>(null),[adding,setAdding]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");
  const bridgeRef=useRef<Bridge|null>(null);
  const load=useCallback(()=>apiFetch(`/api/estimates/${encodeURIComponent(estimateId)}/position-bridge`).then(value=>{bridgeRef.current=value as Bridge;setBridge(value as Bridge)}),[estimateId]);
  useEffect(()=>{void load().catch(reason=>{console.error("Estimate position bridge load failed",reason);setError("Estimate positions could not be loaded.")})},[load]);
  useEffect(()=>{if(refreshRequest>0)void load().catch(reason=>{console.error("Estimate position bridge refresh failed",reason);setError("Estimate positions could not be refreshed.")})},[load,refreshRequest]);
  useEffect(()=>{if(addRequest>0)setAdding(true)},[addRequest]);
  const persistPositions=useCallback(async(positions:Position[])=>{await apiFetch(`/api/estimates/${encodeURIComponent(estimateId)}/positions`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({positions}),keepalive:true});await load();onChanged()},[estimateId,load,onChanged]);
  useEffect(()=>{const handleAdd=()=>setAdding(true);window.addEventListener("quotesuite:add-position",handleAdd);return()=>window.removeEventListener("quotesuite:add-position",handleAdd)},[]);
  const positionAction=useCallback((positionId:string,action:EstimatePositionAction)=>{const positions=[...(bridgeRef.current?.positions??[])],index=positions.findIndex(item=>item.id===positionId);if(index<0)return;if(action==="up"&&index>0)[positions[index-1],positions[index]]=[positions[index],positions[index-1]];else if(action==="down"&&index<positions.length-1)[positions[index+1],positions[index]]=[positions[index],positions[index+1]];else if(action==="delete")positions.splice(index,1);else if(action==="alternative"){const target=positions[index-1]??null,isAlternative=positions[index].classification==="alternative";positions[index]={...positions[index],classification:isAlternative?"standard":"alternative",alternativeTo:isAlternative?null:target?.positionRef??null,alternativeToPositionId:isAlternative?null:target?.id??null};}else if(action==="duplicate"){const source=positions[index],id=crypto.randomUUID(),contract=source.configuredContract?structuredClone(source.configuredContract):null;if(contract?.identity)contract.identity={...contract.identity,positionId:id,positionRef:`${source.positionRef}-COPY`};positions.splice(index+1,0,{...source,id,positionRef:`${source.positionRef}-COPY`,classification:"standard",alternativeTo:null,alternativeToPositionId:null,supplierEvidenceLinks:[],sourceProvenance:null,configuredContract:contract})}else return;bridgeRef.current=bridgeRef.current?{...bridgeRef.current,positions}:bridgeRef.current;setBridge(current=>current?{...current,positions}:current);void persistPositions(positions).catch(reason=>{void load();setError(reason instanceof Error?reason.message:"Position action could not be saved.")})},[load,persistPositions]);
  const draft=useMemo(()=>editing??(adding?{id:crypto.randomUUID(),positionRef:`W-${String((bridge?.positions.length??0)+1).padStart(3,"0")}`,qty:1,roomName:"",widthMm:1000,heightMm:1000}:null),[editing,adding,bridge?.positions.length]);
  async function save(state:B92ConfiguratorState){if(!bridge||!draft)return;setSaving(true);setError("");try{const compiled=compileB92ConfiguratorStateToConfiguredPositionContract(state,{clientId:bridge.clientId,estimateId,positionId:draft.id,positionRef:draft.positionRef,quantity:draft.qty,roomName:draft.roomName??"",itemPrice:draft.itemPrice??null,createdAt:draft.configuredContract?.identity?.createdAt});if(!compiled.ok)throw new Error(compiled.errors.join(" "));const projection=projectConfiguredPositionContractToLegacyPosition(compiled.contract);if(adding)await apiFetch(`/api/estimates/${encodeURIComponent(estimateId)}/positions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({position:{...draft,...projection,configuredContract:compiled.contract}})});else await apiFetch(`/api/estimates/${encodeURIComponent(estimateId)}/positions/${encodeURIComponent(draft.id)}/configuration`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({configuredContract:compiled.contract,projection})});setAdding(false);setEditing(null);await load();onChanged();}catch(reason){setError(reason instanceof Error?reason.message:"Configuration could not be saved.")}finally{setSaving(false)}}
  async function resolve(sourcePositionId:string,decision:"link_existing"|"create_new",targetEstimatePositionId?:string){setSaving(true);try{await apiFetch(`/api/estimates/${encodeURIComponent(estimateId)}/position-match-reviews/${encodeURIComponent(sourcePositionId)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision,targetEstimatePositionId})});await load();onChanged();}catch(reason){setError(reason instanceof Error?reason.message:"Review could not be saved.")}finally{setSaving(false)}}
  if(draft)return <section className="estimate-position-bridge__editor" aria-label={adding?"Add Position":"Configure Position"}><div className="estimate-position-bridge__editor-heading"><h3>{adding?"Add Position":draft.configuredContract?"Edit Configuration":"Configure Position"}</h3><p>{draft.positionRef} · {draft.widthMm} × {draft.heightMm} mm · Qty {draft.qty}</p></div><B92ConfiguratorShell key={draft.id} initialState={hydrateB92ConfiguratorStateFromPosition(draft)} saving={saving} onSave={state=>void save(state)} onCancel={()=>{setAdding(false);setEditing(null)}}/>{error?<p role="alert">{error}</p>:null}</section>;
  const positions=bridge?.positions??[];
  return <>{error?<p role="alert" className="calculator-lab__message calculator-lab__message--error">{error}</p>:null}{children({positions,startAdd:()=>setAdding(true),startConfigure:positionId=>{const position=positions.find(item=>item.id===positionId);if(position?.configuredContract)setEditing(position)},positionAction})}{bridge?.reviewRequired.length?<section className="estimate-position-reviews" aria-label="Position match review">{bridge.reviewRequired.map(review=><MatchReview key={review.position.id} review={review} saving={saving} onResolve={resolve}/>)}</section>:null}</>;
}

function MatchReview({review,saving,onResolve}:{review:{position:Position;candidates:Position[]};saving:boolean;onResolve:(sourceId:string,decision:"link_existing"|"create_new",target?:string)=>void}){const [target,setTarget]=useState("");const sourceId=review.position.supplierEvidenceLinks?.[0]?.sourcePositionId;return <section className="estimate-position-match-review"><h4>Review Required</h4><p><strong>Supplier row:</strong> {review.position.positionRef} · {review.position.widthMm} × {review.position.heightMm} mm · Qty {review.position.qty} · {review.position.supplier?.name??"Supplier"} · sequence {review.position.sourceSequence}</p><label>Eligible Estimate position<select value={target} onChange={event=>setTarget(event.currentTarget.value)}><option value="">Select position</option>{review.candidates.map(candidate=><option key={candidate.id} value={candidate.id}>{candidate.positionRef} · {candidate.widthMm} × {candidate.heightMm} · Qty {candidate.qty} · {candidate.configuredContract?"Configured":"Unconfigured"}</option>)}</select></label><div><button className="ui-button ui-button--primary" disabled={saving||!target||!sourceId} onClick={()=>onResolve(sourceId,"link_existing",target)}>Link to Existing Position</button><button className="ui-button" disabled={saving||!sourceId} onClick={()=>onResolve(sourceId,"create_new")}>Create New Position</button></div></section>}
