import { useCallback, useEffect, useMemo, useState } from "react";
import type { SupplierQuote, SupplierQuoteAttachment, SupplierQuoteRevision } from "../supplierQuoteImport/domain/supplierQuote.types";
import { supplierQuotesApi, type ManufacturerImportReview } from "../supplierQuotes/api/supplierQuotesApi";
import { resolveManufacturerVisualAssetUrl as apiUrl } from "../manufacturerVisuals/manufacturerVisualAssetUrl";

type StoredDocument = { quote: SupplierQuote; revision: SupplierQuoteRevision; attachment: SupplierQuoteAttachment };
const documentRoleLabel = (attachment: SupplierQuoteAttachment) => attachment.documentKind === "window_schedule" ? "Schedule" : attachment.documentKind === "quotation_letter" ? "Commercial / covering quotation" : attachment.documentKind === "installation_pricing" ? "Installation / additional pricing" : attachment.documentKind.replaceAll("_", " ");
export function updateDocumentSelection(current:Set<string>,attachmentId:string,checked:boolean){
 const next = new Set(current);
 if (checked) next.add(attachmentId);
 else next.delete(attachmentId);
 return next
}

export default function EstimateSupplierCostImportControl({estimateId,scenarioId,onLoaded}:{estimateId:string;scenarioId:string;onLoaded:(message?:string)=>Promise<void>|void}){
 const [documents,setDocuments]=useState<StoredDocument[]>([]),[selected,setSelected]=useState<Set<string>>(()=>new Set()),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[review,setReview]=useState<ManufacturerImportReview|null>(null),[selectedRows,setSelectedRows]=useState<Set<string>>(()=>new Set()),[supplierCode,setSupplierCode]=useState(""),[quotationNumber,setQuotationNumber]=useState(""),[revision,setRevision]=useState(""),[currency,setCurrency]=useState("EUR"),[largeImage,setLargeImage]=useState<{url:string;reference:string}|null>(null);
 const chosen=useMemo(()=>documents.filter(item=>selected.has(item.attachment.id)),[documents,selected]);
 const refresh=useCallback(async()=>setDocuments(await supplierQuotesApi.listStoredDocuments(estimateId)),[estimateId]);
 useEffect(()=>{let current=true;void supplierQuotesApi.listStoredDocuments(estimateId).then(items=>{if(current)setDocuments(items)}).catch(error=>{if(current)setMessage(error instanceof Error?error.message:"Supplier documents could not be loaded.")});return()=>{current=false}},[estimateId]);
 useEffect(()=>{const handle=(event:Event)=>{if((event as CustomEvent<{estimateId?:string}>).detail?.estimateId===estimateId)void refresh()};window.addEventListener("quotesuite:supplier-documents-changed",handle);return()=>window.removeEventListener("quotesuite:supplier-documents-changed",handle)},[estimateId,refresh]);
 async function prepare(){if(!chosen.length||busy)return;setBusy(true);setMessage("Extracting manufacturer quotation for review…");try{const value=await supplierQuotesApi.prepareReview(estimateId,chosen.map(item=>({quoteId:item.quote.id,revisionId:item.revision.id,attachmentId:item.attachment.id})));setReview(value);setSelectedRows(new Set(value.documents.flatMap(item=>item.rows.filter(row=>row.include).map(row=>row.rowKey))));setSupplierCode(value.metadata.supplierCode??"");setQuotationNumber(value.metadata.quotationNumber??"");setRevision(value.metadata.revision??"");setCurrency(value.metadata.currency);const counts=value.documents.reduce((total,item)=>({parsed:total.parsed+item.diagnostics.counts.parsedPositions,ready:total.ready+item.diagnostics.counts.validCanonicalPositions}),{parsed:0,ready:0});setMessage(value.metadata.supplierCode?`Extracted — ready to confirm. ${counts.parsed} parsed · ${counts.ready} ready for Products / Supply.`:`Source supplier recognised: ${value.metadata.recognizedSupplierName}. Canonical supplier required before confirmation. ${counts.parsed} parsed · ${counts.ready} ready.`)}catch(error){setMessage(error instanceof Error?error.message:"Manufacturer review could not be prepared.")}finally{setBusy(false)}}
 async function confirm(){if(!review||!supplierCode||!selectedRows.size||busy)return;setBusy(true);setMessage("Confirming reviewed positions…");try{const result=await supplierQuotesApi.extractAndLoad(estimateId,scenarioId,review.documents.map(item=>({quoteId:item.quoteId,revisionId:item.revisionId,attachmentId:item.attachmentId})),{selectedRowKeys:[...selectedRows],supplierCode,metadata:{quotationNumber,revision,currency}});const {counts}=result,loaded=result.documents.reduce((sum,item)=>sum+item.loadedProducts,0),duplicates=result.documents.reduce((sum,item)=>sum+item.duplicateProducts,0),supplier=review.canonicalSuppliers.find(item=>item.supplierCode===supplierCode)?.supplierName??supplierCode,summary=`${supplier} · ${quotationNumber}${revision?`-${revision}`:""} · ${counts.selectedPositions} selected · ${counts.persistedPositions} canonical · ${counts.productsSupplyRows} Products / Supply · ${counts.projectCostingRows} Project Costing${loaded?` · ${loaded} new`:""}${duplicates?` · ${duplicates} existing`:""}.`;await refresh();await onLoaded(summary);if(result.status==="confirmed"){setReview(null);setSelected(new Set());setMessage(`${counts.persistedPositions} position${counts.persistedPositions===1?"":"s"} confirmed; Products / Supply and Project Costing each contain ${counts.projectCostingRows}.${result.postConfirmationWarnings?.length?` ${result.postConfirmationWarnings.join(" ")}`:""}`)}else if(result.status==="review_required")setMessage(`Review required for ${counts.reviewRequiredPositions} positions. ${counts.validCanonicalPositions} canonical-ready positions were preserved. Original quotation retained.`);else setMessage(`${counts.selectedPositions} positions selected — confirmation incomplete. Costing projection incomplete — recovery required. Original quotation retained.`)}catch(error){setMessage(error instanceof Error?error.message:"Confirmation failed. Original quotation retained; recovery review is required before retrying.")}finally{setBusy(false)}}
 if(review){
  const rows=review.documents.flatMap(item=>item.rows);
  const canonicalSupplier=review.canonicalSuppliers.find(item=>item.supplierCode===supplierCode)??null;
  const confirmationBlocked=!canonicalSupplier;
  return <section className="ui-card manufacturer-import-review" aria-labelledby="manufacturer-import-review-title" aria-busy={busy}>
   <header><div><h3 id="manufacturer-import-review-title">Manufacturer Import Review</h3><p>Confirm canonical supplier, quotation metadata and selected positions before Project Costing is changed.</p></div><button className="ui-button" disabled={busy} onClick={()=>setReview(null)}>Back</button></header>
   <div className="manufacturer-import-review__supplier-status" data-status={confirmationBlocked?"review_required":"ready"} role="status"><span><strong>Source supplier recognised:</strong> {review.metadata.recognizedSupplierName}</span><span><strong>Canonical supplier:</strong> {canonicalSupplier?.supplierName??"not selected"}</span><small>{confirmationBlocked?"Extracted — supplier confirmation required. No commercial rows have been persisted.":"Ready to confirm through the quantitative completion gate."}</small></div>
   <div className="manufacturer-import-review__metadata"><label>Canonical supplier<select className="ui-input" disabled={busy} value={supplierCode} onChange={event=>setSupplierCode(event.currentTarget.value)}><option value="">Select configured supplier</option>{review.canonicalSuppliers.map(item=><option key={item.supplierCode} value={item.supplierCode}>{item.supplierName} · {item.pricingMethod.replaceAll("_"," ")}</option>)}</select></label><label>Quotation / reference<input className="ui-input" disabled={busy} value={quotationNumber} onChange={event=>setQuotationNumber(event.currentTarget.value)}/></label><label>Revision<input className="ui-input" disabled={busy} value={revision} onChange={event=>setRevision(event.currentTarget.value)}/></label><label>Currency<input className="ui-input" disabled={busy} maxLength={3} value={currency} onChange={event=>setCurrency(event.currentTarget.value.toUpperCase())}/></label></div>
   <div className="manufacturer-import-review__table" tabIndex={0} aria-label="Manufacturer positions; scroll horizontally for additional evidence">
    <table>
     <colgroup><col className="review-col-include"/><col className="review-col-preview"/><col className="review-col-item"/><col className="review-col-reference"/><col className="review-col-room"/><col className="review-col-product"/><col className="review-col-configuration"/><col className="review-col-dimensions"/><col className="review-col-quantity"/><col className="review-col-price"/><col className="review-col-status"/></colgroup>
     <thead><tr><th>Include</th><th>Preview</th><th>Manufacturer item</th><th>Customer reference</th><th>Room</th><th>Product / system</th><th>Configuration</th><th>Dimensions / area</th><th>Qty</th><th>Unit / total</th><th>Thermal / status</th></tr></thead>
     <tbody>{rows.map(row=>{const visual=row.sourceVisual,image=visual.status==="available"&&visual.url;const unavailable=visual.originalAsset?"Preview unavailable — source region retained":"No manufacturer image supplied";const product=row.productSystem??row.product??"—",configuration=row.configurationDescription??"—",ready=row.include&&!row.warnings.length;return <tr key={row.rowKey} aria-selected={selectedRows.has(row.rowKey)} data-readiness={ready?"ready":"review_required"}>
      <td data-label="Include"><input aria-label={`Include ${row.customerReference??row.rowKey}`} type="checkbox" disabled={busy} checked={selectedRows.has(row.rowKey)} onChange={event=>{const checked=event.currentTarget.checked;setSelectedRows(current=>updateDocumentSelection(current,row.rowKey,checked))}}/></td>
      <td data-label="Preview">{image?<><button className="manufacturer-import-review__image-button" disabled={busy} onClick={()=>setLargeImage({url:apiUrl(visual.url!),reference:row.customerReference??"position"})}><img src={apiUrl(visual.url!)} alt={`Manufacturer ${visual.role==="inside"?"inside ":""}elevation ${row.customerReference??""}`}/></button><small>{visual.role==="inside"?"Inside elevation · PDF region":visual.sourceFormat==="pdf"?"Preview derived from PDF region":"Source preview"}</small></>:<span title={visual.reason??undefined}>{unavailable}</span>}</td>
      <td data-label="Manufacturer item">{row.manufacturerItemNumber??"—"}</td><td data-label="Customer reference"><strong>{row.customerReference??"—"}</strong></td><td data-label="Room">{row.roomLocation??"—"}</td>
      <td data-label="Product / system" title={product}>{product}</td><td data-label="Configuration" title={configuration}>{configuration}</td>
      <td data-label="Dimensions / area">{row.widthMm??"—"} × {row.heightMm??"—"}<small>{row.areaSquareMetres?`${row.areaSquareMetres} m²`:""}</small></td><td data-label="Qty">{row.quantity??"—"}</td>
      <td data-label="Unit / total">{row.unitPrice??"—"} / {row.totalPrice??"—"} {row.currency??""}</td><td data-label="Thermal / status">Ug {row.manufacturerQuotedUg??"—"} · Uw {row.manufacturerQuotedUw??"—"}<small>{ready?"Ready to confirm":"Review required"} · {visual.status==="available"?(visual.sourceFormat==="pdf"?"PDF region preview":"preview available"):"preview unavailable"}</small></td>
     </tr>})}</tbody>
    </table>
   </div>
   <footer><span>{selectedRows.size} of {rows.length} positions selected.</span><button className="ui-button ui-button--primary" disabled={busy||confirmationBlocked||!selectedRows.size} onClick={()=>void confirm()}>{busy?"Confirming…":confirmationBlocked?"Select canonical supplier to confirm":"Confirm & Load to Project Costing"}</button></footer>
   {message?<p role="status">{message}</p>:null}{largeImage?<div className="manufacturer-import-review__lightbox" role="presentation" onClick={()=>setLargeImage(null)}><section className="ui-card" role="dialog" aria-modal="true" aria-label={`Manufacturer elevation ${largeImage.reference}`} onClick={event=>event.stopPropagation()}><button className="ui-button" onClick={()=>setLargeImage(null)}>Close</button><img src={largeImage.url} alt={`Manufacturer elevation ${largeImage.reference}`}/></section></div>:null}
  </section>
 }
 const grouped=documents.reduce<Map<string,{quote:SupplierQuote;revisions:Map<string,{revision:SupplierQuoteRevision;attachments:SupplierQuoteAttachment[]}>}>>((map,item)=>{if(!map.has(item.quote.id))map.set(item.quote.id,{quote:item.quote,revisions:new Map()});const revisions=map.get(item.quote.id)!.revisions;if(!revisions.has(item.revision.id))revisions.set(item.revision.id,{revision:item.revision,attachments:[]});revisions.get(item.revision.id)!.attachments.push(item.attachment);return map},new Map());
 const operationLabel=(status:SupplierQuoteRevision["confirmationStatus"])=>status==="confirmed"?"Confirmed":status==="partial_recovery_required"||status==="failed_recoverable"?"Recovery required":status==="confirming"?"Confirming":null;
 return <section className="ui-card calculator-lab__supplier-import" aria-labelledby="supplier-cost-import-heading"><div><h3 id="supplier-cost-import-heading">Review and import supplier documents</h3><p>Select uploaded manufacturer documents. Extraction opens a review before any positions are loaded.</p></div>{!documents.length?<p>No supplier documents are stored for this estimate yet.</p>:<div className="calculator-lab__supplier-documents">{[...grouped.values()].map(({quote,revisions})=><section key={quote.id}><h4>{quote.supplierName}</h4>{[...revisions.values()].map(({revision,attachments})=>{const status=operationLabel(revision.confirmationStatus),confirmed=revision.confirmationStatus==="confirmed";return <div key={revision.id} data-confirmation-status={revision.confirmationStatus??"not_confirmed"}><strong>{revision.fullQuotationReference||"No quotation reference"}{revision.supplierRevision?` · revision ${revision.supplierRevision}`:""}{status?<span className="manufacturer-import-operation-status">{status}</span>:null}</strong>{attachments.map(attachment=><label key={attachment.id}><input type="checkbox" disabled={confirmed} checked={selected.has(attachment.id)} onChange={event=>{const checked = event.currentTarget.checked; setSelected((current) => updateDocumentSelection(current, attachment.id, checked))}}/><span><strong>{attachment.originalFileName}</strong><small>{revision.currency} · {documentRoleLabel(attachment)} · uploaded {new Date(attachment.createdAt).toLocaleDateString()}{confirmed?" · canonical import complete":""}</small></span></label>)}</div>})}</section>)}</div>}<button className="ui-button ui-button--primary" disabled={busy||!selected.size} onClick={()=>void prepare()}>{busy?"Extracting…":"Extract & Review Manufacturer Quote"}</button>{message?<p role="status">{message}</p>:null}</section>
}
