import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { apiFetch } from "../../services/api/apiClient";
import B92ConfiguratorShell from "../b92Configurator/B92ConfiguratorShell";
import { compileB92ConfiguratorStateToConfiguredPositionContract, hydrateB92ConfiguratorStateFromPosition, projectConfiguredPositionContractToLegacyPosition } from "../b92Configurator/b92ConfiguredPositionCompiler";
import type { B92ConfiguratorState } from "../b92Configurator/b92Configurator.types";

type Position=Record<string,any>;
type Bridge={estimateId:string;clientId:string;positions:Position[];reviewRequired:Array<{position:Position;candidates:Position[]}>};
export type PositionWorkspaceControls={positions:Position[];startAdd:()=>void;startConfigure:(positionId:string)=>void};

export default function EstimatePositionBridge({estimateId,addRequest,onChanged,children}:{estimateId:string;addRequest:number;onChanged:()=>void;children:(controls:PositionWorkspaceControls)=>ReactNode}){
  const [bridge,setBridge]=useState<Bridge|null>(null),[editing,setEditing]=useState<Position|null>(null),[adding,setAdding]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");
  const load=useCallback(()=>apiFetch(`/api/estimates/${encodeURIComponent(estimateId)}/position-bridge`).then(value=>setBridge(value as Bridge)),[estimateId]);
  useEffect(()=>{void load().catch(reason=>{console.error("Estimate position bridge load failed",reason);setError("Estimate positions could not be loaded.")})},[load]);
  useEffect(()=>{if(addRequest>0)setAdding(true)},[addRequest]);
  useEffect(()=>{const handleAdd=()=>setAdding(true),handleConfigure=(event:Event)=>{const id=(event as CustomEvent<{positionId:string}>).detail?.positionId;const position=bridge?.positions.find(item=>item.id===id);if(position)setEditing(position)};window.addEventListener("quotesuite:add-position",handleAdd);window.addEventListener("quotesuite:configure-position",handleConfigure);return()=>{window.removeEventListener("quotesuite:add-position",handleAdd);window.removeEventListener("quotesuite:configure-position",handleConfigure)}},[bridge?.positions]);
  const draft=useMemo(()=>editing??(adding?{id:crypto.randomUUID(),positionRef:`W-${String((bridge?.positions.length??0)+1).padStart(3,"0")}`,qty:1,roomName:"",widthMm:1000,heightMm:1000}:null),[editing,adding,bridge?.positions.length]);
  async function save(state:B92ConfiguratorState){if(!bridge||!draft)return;setSaving(true);setError("");try{const compiled=compileB92ConfiguratorStateToConfiguredPositionContract(state,{clientId:bridge.clientId,estimateId,positionId:draft.id,positionRef:draft.positionRef,quantity:draft.qty,roomName:draft.roomName??"",itemPrice:draft.itemPrice??null,createdAt:draft.configuredContract?.identity?.createdAt});if(!compiled.ok)throw new Error(compiled.errors.join(" "));const projection=projectConfiguredPositionContractToLegacyPosition(compiled.contract);if(adding)await apiFetch(`/api/estimates/${encodeURIComponent(estimateId)}/positions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({position:{...draft,...projection,configuredContract:compiled.contract}})});else await apiFetch(`/api/estimates/${encodeURIComponent(estimateId)}/positions/${encodeURIComponent(draft.id)}/configuration`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({configuredContract:compiled.contract,projection})});setAdding(false);setEditing(null);await load();onChanged();}catch(reason){setError(reason instanceof Error?reason.message:"Configuration could not be saved.")}finally{setSaving(false)}}
  async function resolve(sourcePositionId:string,decision:"link_existing"|"create_new",targetEstimatePositionId?:string){setSaving(true);try{await apiFetch(`/api/estimates/${encodeURIComponent(estimateId)}/position-match-reviews/${encodeURIComponent(sourcePositionId)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision,targetEstimatePositionId})});await load();onChanged();}catch(reason){setError(reason instanceof Error?reason.message:"Review could not be saved.")}finally{setSaving(false)}}
  if(draft)return <section className="estimate-position-bridge__editor" aria-label={adding?"Add Position":"Configure Position"}><div className="estimate-position-bridge__editor-heading"><h3>{adding?"Add Position":draft.configuredContract?"Edit Configuration":"Configure Position"}</h3><p>{draft.positionRef} · {draft.widthMm} × {draft.heightMm} mm · Qty {draft.qty}</p></div><B92ConfiguratorShell key={draft.id} initialState={hydrateB92ConfiguratorStateFromPosition(draft)} saving={saving} onSave={state=>void save(state)} onCancel={()=>{setAdding(false);setEditing(null)}}/>{error?<p role="alert">{error}</p>:null}</section>;
  const positions=bridge?.positions??[];
  return <>{error?<p role="alert" className="calculator-lab__message calculator-lab__message--error">{error}</p>:null}{children({positions,startAdd:()=>setAdding(true),startConfigure:positionId=>{const position=positions.find(item=>item.id===positionId);if(position)setEditing(position)}})}{bridge?.reviewRequired.length?<section className="estimate-position-reviews" aria-label="Position match review">{bridge.reviewRequired.map(review=><MatchReview key={review.position.id} review={review} saving={saving} onResolve={resolve}/>)}</section>:null}</>;
}

function MatchReview({review,saving,onResolve}:{review:{position:Position;candidates:Position[]};saving:boolean;onResolve:(sourceId:string,decision:"link_existing"|"create_new",target?:string)=>void}){const [target,setTarget]=useState("");const sourceId=review.position.supplierEvidenceLinks?.[0]?.sourcePositionId;return <section className="estimate-position-match-review"><h4>Review Required</h4><p><strong>Supplier row:</strong> {review.position.positionRef} · {review.position.widthMm} × {review.position.heightMm} mm · Qty {review.position.qty} · {review.position.supplier?.name??"Supplier"} · sequence {review.position.sourceSequence}</p><label>Eligible Estimate position<select value={target} onChange={event=>setTarget(event.currentTarget.value)}><option value="">Select position</option>{review.candidates.map(candidate=><option key={candidate.id} value={candidate.id}>{candidate.positionRef} · {candidate.widthMm} × {candidate.heightMm} · Qty {candidate.qty} · {candidate.configuredContract?"Configured":"Unconfigured"}</option>)}</select></label><div><button className="ui-button ui-button--primary" disabled={saving||!target||!sourceId} onClick={()=>onResolve(sourceId,"link_existing",target)}>Link to Existing Position</button><button className="ui-button" disabled={saving||!sourceId} onClick={()=>onResolve(sourceId,"create_new")}>Create New Position</button></div></section>}
