import { useEffect, useMemo, useRef, useState } from "react";
import { apiFetch, apiUrl } from "../../services/api/apiClient";
import "./supplierRfqDialog.css";
import SupplierReplyReview from "./SupplierReplyReview";

type RfqDocument = { id:string; fileName:string; mediaType:string; sizeBytes:number; documentType:string; providerRevision:string|null; folderPath:string|null };
type RfqRecord = { id:string; supplierId?:string; supplierName:string|null; recipient:string; subject:string; bodyText?:string; status:string;deliveryState?:string; revisionNo:number; documentIds?:string[]; documentSnapshot:RfqDocument[]; communicationMessageId:string; idempotencyKey?:string|null;requestKind?:"initial"|"revision";revisionRequestId?:string|null;sentAt?:string|null;responseDueAt?:string|null;responseState?:string;followupSentAt?:string|null;followupFailure?:string;followupDeliveryState?:string;createdAt:string; nextAction?:string; idempotentReplay?:boolean };
type RfqContext = {
  project:{id:string;clientId:string;clientName:string;clientReference:string;name:string};
  selectedEstimateId:string|null;
  estimates:Array<{id:string;estimateRef:string;revisionNo:number;status:string}>;
  suppliers:Array<{id:string;name:string}>;
  documents:RfqDocument[];
  enquiries:RfqRecord[];
  requestMode:"initial"|"revision";
  revisionRequest:null|{id:string;status:string;sourceReleaseId:string;summary:{sourceEstimateRef?:string;sourceRevision?:number;generalComment?:string;positions?:Array<{reference:string;request:string}>};submittedAt:string;responseDueAt:string|null};
  legacyPrepared:Array<{id:string;status:string;supplierName:string|null;request:{requestedChanges?:string;affectedPositionIds?:string[];supportingDocumentIds?:string[]};createdAt:string}>;
  legacyCorrespondence?:Array<{id:string;status:string;subject:string;bodyText:string;recipients:string[];createdAt:string;sentAt:string|null;attachments:Array<{id:string;fileName:string;downloadUrl:string|null}>}>;
  legacyCorrespondenceTotal?:number;
  recommendedDocumentIds:string[];
  delivery:{deliveryMode:string;factoryConfigured:boolean};
};

const json={"Content-Type":"application/json"};
const makeKey=()=>globalThis.crypto?.randomUUID?.()||`rfq-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const reviewedContent=(supplierId:string,recipient:string,subject:string,bodyText:string,documentIds:string[],requestKind:string)=>JSON.stringify({supplierId,recipient,subject,bodyText,documentIds:[...documentIds].sort(),requestKind});
const localDateTime=(value?:string|null)=>{if(!value)return"";const date=new Date(value);if(Number.isNaN(date.getTime()))return"";const offset=date.getTimezoneOffset()*60_000;return new Date(date.getTime()-offset).toISOString().slice(0,16)};

export default function SupplierRfqDialog({projectId,estimateId,estimateRef,onClose}:{projectId:string;estimateId:string;estimateRef:string;onClose:()=>void}){
  const [context,setContext]=useState<RfqContext|null>(null),[requestKind,setRequestKind]=useState<"initial"|"revision">("initial"),[supplierId,setSupplierId]=useState(""),[recipient,setRecipient]=useState(""),[subject,setSubject]=useState(`Request for estimate · ${estimateRef}`),[bodyText,setBodyText]=useState("Please review the selected project documents and provide your estimate."),[documentIds,setDocumentIds]=useState<string[]>([]),[dueDrafts,setDueDrafts]=useState<Record<string,string>>({}),[sendNow,setSendNow]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[result,setResult]=useState<RfqRecord|null>(null);
  const idempotencyKey=useRef<string>(makeKey()),submitting=useRef(false);
  const submittedContent=useRef<string|null>(null);
  const deliveryBlocked=Boolean(context?.enquiries.some(item=>item.idempotencyKey===idempotencyKey.current&&["sending","uncertain"].includes(item.deliveryState||"")));
  const recordedSend=Boolean(context?.enquiries.some(item=>item.idempotencyKey===idempotencyKey.current&&item.deliveryState==="sent"&&item.status!=="sent"));
  const [replyRequest, setReplyRequest] = useState<RfqRecord | null>(null);
  const [legacyOffset,setLegacyOffset]=useState(0);
  const pageLegacy=async(offset:number)=>{if(saving||!context?.revisionRequest)return;setSaving(true);setError("");try{const page=await apiFetch(`/api/lifecycle/supplier-revisions/${encodeURIComponent(context.revisionRequest.id)}/earlier-correspondence?offset=${offset}`) as {items:NonNullable<RfqContext["legacyCorrespondence"]>;total:number;offset:number};setContext(current=>current?{...current,legacyCorrespondence:page.items,legacyCorrespondenceTotal:page.total}:current);setLegacyOffset(page.offset)}catch(reason){setError(reason instanceof Error?reason.message:"Earlier messages could not be loaded. Your current page and entered values are retained.")}finally{setSaving(false)}};
  const selectedSupplier=useMemo(()=>context?.suppliers.find(item=>item.id===supplierId)||null,[context,supplierId]);
  const applyMode=(kind:"initial"|"revision",value:RfqContext)=>{setRequestKind(kind);if(kind==="revision"&&value.revisionRequest){const summary=value.revisionRequest.summary;setSubject(`Requested estimate revision · ${value.project.name} · ${summary.sourceEstimateRef||estimateRef}`);setBodyText([`Please revise your estimate for ${value.project.name}.`,...(summary.positions||[]).map(item=>`${item.reference}: ${item.request}`),...(summary.generalComment?[`General: ${summary.generalComment}`]:[]),"Please return a revised document identifying the changed values."].join("\n"))}else{setSubject(`Request for estimate · ${estimateRef}`);setBodyText("Please review the selected project documents and provide your estimate.")}};
  const load=async()=>{setLoading(true);setError("");try{const value=await apiFetch(`/api/lifecycle/projects/${encodeURIComponent(projectId)}/supplier-enquiries?estimate_id=${encodeURIComponent(estimateId)}`) as RfqContext;setContext(value);applyMode(value.requestMode,value);setDocumentIds(value.recommendedDocumentIds||[]);if(!supplierId&&value.suppliers.length===1)setSupplierId(value.suppliers[0].id)}catch(reason){setError(reason instanceof Error?reason.message:"Supplier request details could not be loaded.")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[projectId,estimateId]); // eslint-disable-line react-hooks/exhaustive-deps
  const toggleDocument=(id:string,checked:boolean)=>setDocumentIds(current=>checked?[...new Set([...current,id])]:current.filter(item=>item!==id));
  const reopen=(item:RfqRecord)=>{const selectedDocuments=item.documentIds||item.documentSnapshot.map(document=>document.id);setResult(null);setSupplierId(item.supplierId||"");setRecipient(item.recipient);setSubject(item.subject);setBodyText(item.bodyText||"");setDocumentIds(selectedDocuments);setRequestKind(item.requestKind||"initial");setSendNow(item.deliveryState==="sent"&&item.status!=="sent");idempotencyKey.current=item.idempotencyKey||makeKey();submittedContent.current=reviewedContent(item.supplierId||"",item.recipient,item.subject,item.bodyText||"",selectedDocuments,item.requestKind||"initial");setError("")};
  const retryFollowup=async(item:RfqRecord)=>{if(saving)return;setSaving(true);setError("");setNotice("");try{await apiFetch(`/api/lifecycle/supplier-enquiries/${encodeURIComponent(item.id)}/followup-retry`,{method:"POST"});await load();setNotice("Follow-up retry queued. QuoteSuite will recheck that a response is still outstanding before sending.")}catch(reason){setError(reason instanceof Error?reason.message:"The follow-up retry could not be queued. No email was sent.")}finally{setSaving(false)}};
const adjustDue=async(item:RfqRecord)=>{const value=dueDrafts[item.id]??localDateTime(item.responseDueAt);const parsed=new Date(value);if(!value||Number.isNaN(parsed.getTime())){setError("Choose a valid supplier response deadline.");return}setSaving(true);setError("");setNotice("");try{const updated=await apiFetch(`/api/lifecycle/supplier-enquiries/${encodeURIComponent(item.id)}/response-due`,{method:"PUT",headers:json,body:JSON.stringify({responseDueAt:parsed.toISOString()})}) as RfqRecord;setContext(current=>current?{...current,enquiries:current.enquiries.map(entry=>entry.id===updated.id?updated:entry)}:current);setNotice(`Supplier response deadline updated to ${parsed.toLocaleString("en-GB")}. ${["sending","uncertain"].includes(updated.followupDeliveryState||"")?"Delivery is still awaiting confirmation; this does not queue another email.":updated.followupDeliveryState==="not_sent"?"Correct the reported issue and explicitly retry the unsent follow-up when ready.":"Any pending follow-up will use this reviewed deadline."}`)}catch(reason){setError(reason instanceof Error?reason.message:"The supplier response deadline could not be updated. The previous deadline remains in place.")}finally{setSaving(false)}};
  const submit=async()=>{if(submitting.current||saving||!supplierId||!recipient.trim()||!subject.trim()||!bodyText.trim())return;const content=reviewedContent(supplierId,recipient,subject,bodyText,documentIds,requestKind);if(submittedContent.current&&submittedContent.current!==content)idempotencyKey.current=makeKey();submittedContent.current=content;submitting.current=true;setSaving(true);setError("");try{const value=await apiFetch(`/api/lifecycle/projects/${encodeURIComponent(projectId)}/supplier-enquiries`,{method:"POST",headers:json,body:JSON.stringify({estimateId,supplierId,recipient,subject,bodyText,documentIds,idempotencyKey:idempotencyKey.current,send:sendNow,requestKind,revisionRequestId:requestKind==="revision"?context?.revisionRequest?.id:null})}) as RfqRecord;setResult(value);setContext(current=>current?{...current,enquiries:[value,...current.enquiries.filter(item=>item.id!==value.id)]}:current)}catch(reason){setError(reason instanceof Error?reason.message:"The supplier request could not be prepared. Your entries are still here; retry safely.");try{const refreshed=await apiFetch(`/api/lifecycle/projects/${encodeURIComponent(projectId)}/supplier-enquiries?estimate_id=${encodeURIComponent(estimateId)}`) as RfqContext;setContext(refreshed)}catch{}}finally{setSaving(false);submitting.current=false}};
  if (replyRequest) return <div className="estimate-commercial__modal-scrim"><section className="estimate-commercial__modal supplier-rfq ui-card" role="dialog" aria-modal="true" aria-label="Supplier reply review"><SupplierReplyReview projectId={projectId} estimateId={estimateId} requestId={replyRequest.id} recipient={replyRequest.recipient} onClose={()=>setReplyRequest(null)} onOpenFiles={()=>{onClose();window.dispatchEvent(new CustomEvent("quotesuite:open-estimate-documents"));}} onImport={documentId=>{onClose();window.dispatchEvent(new CustomEvent("quotesuite:import-manufacturer-quote",{detail:{canonicalDocumentId:documentId}}));}} /></section></div>;
  return <div className="estimate-commercial__modal-scrim" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget&&!saving)onClose()}}>
    <section className="estimate-commercial__modal supplier-rfq ui-card" role="dialog" aria-modal="true" aria-labelledby="supplier-rfq-title" aria-busy={loading||saving}>
      <header><div><span className="ui-eyebrow">Reviewed supplier request</span><h2 id="supplier-rfq-title">Request supplier estimate / revision</h2><p>{context?`${context.project.clientReference} · ${context.project.clientName} · ${context.project.name}`:`${estimateRef} · loading Project context…`}</p></div><button className="ui-button" disabled={saving} onClick={onClose}>Close</button></header>
      {loading?<p className="ui-status" role="status">Loading current Project files and suppliers…</p>:null}
      {deliveryBlocked?<p className="ui-status ui-status--warning" role="status">Supplier delivery is awaiting confirmation. Your request is retained. Do not send another copy; check the connected mailbox and request delivery review.</p>:null}
      {notice?<p className="ui-status ui-status--success" role="status">{notice}</p>:null}
{context?.legacyCorrespondence?.length?<details><summary>Earlier supplier correspondence ({context.legacyCorrespondenceTotal??context.legacyCorrespondence.length})</summary><p>These retained messages predate the current supplier-request workflow. Original messages remain unchanged.</p>{context.legacyCorrespondence.map(item=><article key={item.id}><h3>{item.subject}</h3><p>{item.recipients.join(", ")} · {item.status==="sent"?`Sent ${item.sentAt||item.createdAt}`:item.status==="draft"?"Prepared, not sent":"Delivery outcome requires review — do not resend"}</p><p style={{whiteSpace:"pre-wrap"}}>{item.bodyText}</p><p>Retained attachments: {item.attachments.length?item.attachments.map(file=><span key={file.id}>{file.downloadUrl?<a href={apiUrl(file.downloadUrl)}>Download {file.fileName}</a>:<span>{file.fileName} · version not confirmed; review the current Project file separately.</span>} </span>):"None"}</p>{item.status==="draft"?<button className="ui-button" disabled={saving} onClick={()=>{setResult(null);setRequestKind("revision");setSupplierId("");setRecipient(item.recipients.join(", "));setSubject(item.subject);setBodyText(item.bodyText);setDocumentIds([]);setSendNow(false);idempotencyKey.current=makeKey();submittedContent.current=null;setNotice("Earlier message opened for review. Choose the correct supplier and review current Project files before preparing. Nothing was sent; the original message is retained.")}}>Continue earlier message</button>:null}</article>)}<p>Showing {legacyOffset+1}–{legacyOffset+context.legacyCorrespondence.length} of {context.legacyCorrespondenceTotal??context.legacyCorrespondence.length}</p><button className="ui-button" disabled={saving||legacyOffset===0} onClick={()=>void pageLegacy(Math.max(0,legacyOffset-20))}>Newer messages</button><button className="ui-button" disabled={saving||legacyOffset+context.legacyCorrespondence.length>=(context.legacyCorrespondenceTotal??0)} onClick={()=>void pageLegacy(legacyOffset+20)}>Older messages</button></details>:null}
      {error?<div className="ui-status ui-status--error" role="alert"><strong>{error}</strong><span>No completed work will be repeated. Check the details and retry.</span></div>:null}
      {result?<section className="supplier-rfq__result" aria-live="polite"><span className="ui-status">{result.status==="sent"?"Supplier request sent":"Prepared for review — not sent"}</span><h3>{result.subject}</h3><p>{result.supplierName} · request revision {result.revisionNo}</p>{result.responseDueAt?<p><strong>Response due:</strong> {new Date(result.responseDueAt).toLocaleDateString("en-GB")}</p>:null}<p>{result.nextAction||"Review the saved Email draft before sending."}</p><div className="ui-action-row">{result.status!=="sent"?<button className="ui-button" onClick={()=>reopen(result)}>Continue editing</button>:null}<button className="ui-button ui-button--primary" onClick={onClose}>Done</button></div><details><summary>View details</summary><dl><div><dt>Request type</dt><dd>{result.requestKind==="revision"?"Supplier revision":"Initial supplier estimate"}</dd></div><div><dt>Recipient</dt><dd>{result.recipient}</dd></div><div><dt>Files</dt><dd>{result.documentSnapshot.length?result.documentSnapshot.map(item=>item.fileName).join(", "):"No selected Project files"}</dd></div><div><dt>Saved Email</dt><dd>{result.communicationMessageId}</dd></div></dl></details></section>:context?<>
        <div className="supplier-rfq__step"><span>1</span><div><h3>Choose request type</h3><p>Creating an editable Estimate revision is a separate action. This step prepares or sends supplier correspondence and never changes issued evidence.</p></div></div>
        {context.enquiries.length ? <details><summary>Review an incoming supplier reply</summary><p>Choose the request the supplier is answering.</p><div className="supplier-rfq__history">{context.enquiries.filter(item=>item.status!=="cancelled").map(item=><button className="ui-button" key={item.id} onClick={()=>setReplyRequest(item)}>{item.supplierName || "Supplier"} · {item.subject} · request {item.revisionNo}</button>)}</div></details> : null}
        <div className="supplier-rfq__mode" role="radiogroup" aria-label="Supplier request type"><label><input type="radio" name="supplier-request-kind" checked={requestKind==="initial"} onChange={()=>applyMode("initial",context)}/> Initial supplier estimate</label><label><input type="radio" name="supplier-request-kind" checked={requestKind==="revision"} disabled={!context.revisionRequest} onChange={()=>applyMode("revision",context)}/> Revision to the tracked customer request</label></div>
        {requestKind==="revision"&&context.revisionRequest?<p className="ui-status ui-status--warning">Customer changes retained against issued revision {context.revisionRequest.summary.sourceRevision}. Current state: {context.revisionRequest.status.replaceAll("_"," ")}.</p>:null}
        <div className="supplier-rfq__step"><span>2</span><div><h3>Choose supplier and recipient</h3><p>The request stays linked to this exact working Estimate and supplier.</p></div></div>
        <div className="supplier-rfq__fields"><label>Supplier<select className="ui-select" value={supplierId} onChange={event=>setSupplierId(event.currentTarget.value)}><option value="">Choose supplier</option>{context.suppliers.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Email address<input className="ui-input" type="email" value={recipient} onChange={event=>setRecipient(event.currentTarget.value)} placeholder={selectedSupplier?`${selectedSupplier.name} recipient`:"Supplier recipient"}/></label></div>
        <div className="supplier-rfq__step"><span>3</span><div><h3>Review Project files</h3><p>Current schedules and drawings are suggested when available. Only checked files are attached; the tracked change summary is added automatically for a revision request.</p></div></div>
        <div className="supplier-rfq__documents">{context.documents.length?context.documents.map(document=><label key={document.id}><input type="checkbox" checked={documentIds.includes(document.id)} onChange={event=>toggleDocument(document.id,event.currentTarget.checked)}/><span><strong>{document.fileName}</strong><small>{document.documentType.replaceAll("_"," ")}</small></span></label>):<p className="ui-empty-state">No current Project files are available. You can prepare the message without an attachment or add files first.</p>}</div>
        <div className="supplier-rfq__step"><span>4</span><div><h3>Review the message</h3><p>Nothing is sent until you choose the sending option.</p></div></div>
        <div className="supplier-rfq__fields"><label className="supplier-rfq__wide">Subject<input className="ui-input" value={subject} onChange={event=>setSubject(event.currentTarget.value)}/></label><label className="supplier-rfq__wide">Message<textarea className="ui-textarea" rows={6} value={bodyText} onChange={event=>setBodyText(event.currentTarget.value)}/></label></div>
        {context.delivery.deliveryMode==="test_allowlist"?<label className="supplier-rfq__send"><input type="checkbox" checked={sendNow} onChange={event=>setSendNow(event.currentTarget.checked)}/> Send now to the configured factory test address</label>:<p className="ui-status ui-status--warning">Preview only. QuoteSuite will save an Email draft; sending is not enabled in this workspace.</p>}
{context.enquiries.length?<details open={context.enquiries.some(item=>item.status!=="sent"||Boolean(item.followupFailure)||["sending","uncertain"].includes(item.followupDeliveryState||""))}><summary>View or reopen previous requests ({context.enquiries.length})</summary><div className="supplier-rfq__history">{context.enquiries.map(item=><article key={item.id}><strong>{item.supplierName||"Supplier"} · request revision {item.revisionNo}</strong><span>{item.subject}</span><small>{new Date(item.createdAt).toLocaleString("en-GB")} · {item.status==="sent"?`sent${item.sentAt?` ${new Date(item.sentAt).toLocaleString("en-GB")}`:""}`:["sending","uncertain"].includes(item.deliveryState||"")?"delivery awaiting confirmation":item.deliveryState==="sent"?"sent — local result needs completion":"prepared — not sent"}{item.responseDueAt?` · response due ${new Date(item.responseDueAt).toLocaleString("en-GB")}`:""}</small>{item.requestKind==="revision"&&item.status==="sent"&&!item.followupSentAt?<details><summary>Adjust response deadline</summary><label>Expected supplier response<input className="ui-input" type="datetime-local" value={dueDrafts[item.id]??localDateTime(item.responseDueAt)} onChange={event=>{const value=event.currentTarget.value;setDueDrafts(current=>({...current,[item.id]:value}))}}/></label><button className="ui-button" disabled={saving} onClick={()=>void adjustDue(item)}>Save reviewed deadline</button></details>:null}{["sending","uncertain"].includes(item.followupDeliveryState||"")?<p role="status">Follow-up delivery is awaiting confirmation. Do not resend; check the connected mailbox and request delivery review.</p>:null}{item.followupSentAt?<p>Follow-up sent {new Date(item.followupSentAt).toLocaleString("en-GB")}. {item.responseState==="revised_document_received"?"The revised document is ready for staff review.":"The revised document remains outstanding."}</p>:null}{item.followupFailure?<><span className="ui-status ui-status--error">Follow-up failed: {item.followupFailure}</span>{item.followupDeliveryState==="not_sent"?<button className="ui-button" disabled={saving} onClick={()=>void retryFollowup(item)}>Retry follow-up safely</button>:null}</>:null}<button className="ui-button ui-button--ghost" onClick={()=>reopen(item)}>{item.status==="sent"?"View request":"Reopen prepared request"}</button></article>)}</div></details>:null}
        {context.legacyPrepared.length?<details open><summary>Earlier prepared revision requests ({context.legacyPrepared.length})</summary><p>These earlier actions recorded an internal preparation marker but did not create or send an Email. Continue one here to make the correspondence accessible.</p><div className="supplier-rfq__history">{context.legacyPrepared.map(item=><article key={item.id}><strong>{item.supplierName||"Supplier revision"}</strong><small>{new Date(item.createdAt).toLocaleString("en-GB")} · prepared — not sent</small><button className="ui-button ui-button--ghost" onClick={()=>{setRequestKind(context.revisionRequest?"revision":"initial");setBodyText(item.request.requestedChanges||bodyText);setDocumentIds(item.request.supportingDocumentIds||[]);setResult(null)}}>Continue prepared request</button></article>)}</div></details>:null}
        <footer><button className="ui-button" disabled={saving} onClick={onClose}>Cancel</button><button className="ui-button ui-button--primary" disabled={saving||deliveryBlocked||!supplierId||!recipient.trim()||!subject.trim()||!bodyText.trim()} onClick={()=>void submit()}>{saving?(sendNow?"Sending supplier request…":"Saving reviewed draft…"):(recordedSend?"Finish saved result":sendNow?"Send supplier request":"Prepare for review")}</button></footer>
      </>:null}
    </section>
  </div>;
}
