import { useEffect, useMemo, useRef, useState } from "react";
import { apiFetch } from "../../services/api/apiClient";
import "./supplierRfqDialog.css";

type RfqDocument = { id:string; fileName:string; mediaType:string; sizeBytes:number; documentType:string; providerRevision:string|null; folderPath:string|null };
type RfqRecord = { id:string; supplierId?:string; supplierName:string|null; recipient:string; subject:string; bodyText?:string; status:string; revisionNo:number; documentIds?:string[]; documentSnapshot:RfqDocument[]; communicationMessageId:string; idempotencyKey?:string|null;requestKind?:"initial"|"revision";revisionRequestId?:string|null;sentAt?:string|null;responseDueAt?:string|null;responseState?:string;followupSentAt?:string|null;followupFailure?:string;createdAt:string; nextAction?:string; idempotentReplay?:boolean };
type RfqContext = {
  project:{id:string;clientId:string;clientName:string;clientReference:string;name:string};
  selectedEstimateId:string|null;
  estimates:Array<{id:string;estimateRef:string;revisionNo:number;status:string}>;
  suppliers:Array<{id:string;name:string}>;
  documents:RfqDocument[];
  enquiries:RfqRecord[];
  requestMode:"initial"|"revision";
  revisionRequest:null|{id:string;status:string;sourceReleaseId:string;summary:{sourceEstimateRef?:string;sourceRevision?:number;generalComment?:string;positions?:Array<{reference:string;request:string}>};submittedAt:string;responseDueAt:string|null};
  legacyPrepared:Array<{id:string;status:string;supplierName:string|null;request:{requestedChanges?:string;affectedPositionIds?:string[];supportingDocumentIds?:string[]};createdAt:string}>;
  recommendedDocumentIds:string[];
  delivery:{deliveryMode:string;factoryConfigured:boolean};
};

const json={"Content-Type":"application/json"};
const makeKey=()=>globalThis.crypto?.randomUUID?.()||`rfq-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const localDateTime=(value?:string|null)=>{if(!value)return"";const date=new Date(value);if(Number.isNaN(date.getTime()))return"";const offset=date.getTimezoneOffset()*60_000;return new Date(date.getTime()-offset).toISOString().slice(0,16)};

export default function SupplierRfqDialog({projectId,estimateId,estimateRef,onClose}:{projectId:string;estimateId:string;estimateRef:string;onClose:()=>void}){
  const [context,setContext]=useState<RfqContext|null>(null),[requestKind,setRequestKind]=useState<"initial"|"revision">("initial"),[supplierId,setSupplierId]=useState(""),[recipient,setRecipient]=useState(""),[subject,setSubject]=useState(`Request for estimate · ${estimateRef}`),[bodyText,setBodyText]=useState("Please review the selected project documents and provide your estimate."),[documentIds,setDocumentIds]=useState<string[]>([]),[dueDrafts,setDueDrafts]=useState<Record<string,string>>({}),[sendNow,setSendNow]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[result,setResult]=useState<RfqRecord|null>(null);
  const idempotencyKey=useRef<string>(makeKey()),submitting=useRef(false);
  const selectedSupplier=useMemo(()=>context?.suppliers.find(item=>item.id===supplierId)||null,[context,supplierId]);
  const applyMode=(kind:"initial"|"revision",value:RfqContext)=>{setRequestKind(kind);if(kind==="revision"&&value.revisionRequest){const summary=value.revisionRequest.summary;setSubject(`Requested estimate revision · ${value.project.name} · ${summary.sourceEstimateRef||estimateRef}`);setBodyText([`Please revise your estimate for ${value.project.name}.`,...(summary.positions||[]).map(item=>`${item.reference}: ${item.request}`),...(summary.generalComment?[`General: ${summary.generalComment}`]:[]),"Please return a revised document identifying the changed values."].join("\n"))}else{setSubject(`Request for estimate · ${estimateRef}`);setBodyText("Please review the selected project documents and provide your estimate.")}};
  const load=async()=>{setLoading(true);setError("");try{const value=await apiFetch(`/api/lifecycle/projects/${encodeURIComponent(projectId)}/supplier-enquiries?estimate_id=${encodeURIComponent(estimateId)}`) as RfqContext;setContext(value);applyMode(value.requestMode,value);setDocumentIds(value.recommendedDocumentIds||[]);if(!supplierId&&value.suppliers.length===1)setSupplierId(value.suppliers[0].id)}catch(reason){setError(reason instanceof Error?reason.message:"Supplier request details could not be loaded.")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[projectId,estimateId]); // eslint-disable-line react-hooks/exhaustive-deps
  const toggleDocument=(id:string,checked:boolean)=>setDocumentIds(current=>checked?[...new Set([...current,id])]:current.filter(item=>item!==id));
  const reopen=(item:RfqRecord)=>{setResult(null);setSupplierId(item.supplierId||"");setRecipient(item.recipient);setSubject(item.subject);setBodyText(item.bodyText||"");setDocumentIds(item.documentIds||item.documentSnapshot.map(document=>document.id));setRequestKind(item.requestKind||"initial");setSendNow(false);idempotencyKey.current=item.idempotencyKey||makeKey();setError("")};
  const retryFollowup=async(item:RfqRecord)=>{if(saving)return;setSaving(true);setError("");setNotice("");try{await apiFetch(`/api/lifecycle/supplier-enquiries/${encodeURIComponent(item.id)}/followup-retry`,{method:"POST"});await load();setNotice("Follow-up retry queued. QuoteSuite will recheck that a response is still outstanding before sending.")}catch(reason){setError(reason instanceof Error?reason.message:"The follow-up retry could not be queued. No email was sent.")}finally{setSaving(false)}};
  const adjustDue=async(item:RfqRecord)=>{const value=dueDrafts[item.id]??localDateTime(item.responseDueAt);const parsed=new Date(value);if(!value||Number.isNaN(parsed.getTime())){setError("Choose a valid supplier response deadline.");return}setSaving(true);setError("");setNotice("");try{const updated=await apiFetch(`/api/lifecycle/supplier-enquiries/${encodeURIComponent(item.id)}/response-due`,{method:"PUT",headers:json,body:JSON.stringify({responseDueAt:parsed.toISOString()})}) as RfqRecord;setContext(current=>current?{...current,enquiries:current.enquiries.map(entry=>entry.id===updated.id?updated:entry)}:current);setNotice(`Supplier response deadline updated to ${parsed.toLocaleString("en-GB")}. The pending follow-up will use this reviewed deadline.`)}catch(reason){setError(reason instanceof Error?reason.message:"The supplier response deadline could not be updated. The previous deadline remains in place.")}finally{setSaving(false)}};
  const submit=async()=>{if(submitting.current||saving||!supplierId||!recipient.trim()||!subject.trim()||!bodyText.trim())return;submitting.current=true;setSaving(true);setError("");try{const value=await apiFetch(`/api/lifecycle/projects/${encodeURIComponent(projectId)}/supplier-enquiries`,{method:"POST",headers:json,body:JSON.stringify({estimateId,supplierId,recipient,subject,bodyText,documentIds,idempotencyKey:idempotencyKey.current,send:sendNow,requestKind,revisionRequestId:requestKind==="revision"?context?.revisionRequest?.id:null})}) as RfqRecord;setResult(value);setContext(current=>current?{...current,enquiries:[value,...current.enquiries.filter(item=>item.id!==value.id)]}:current)}catch(reason){setError(reason instanceof Error?reason.message:"The supplier request could not be prepared. Your entries are still here; retry safely.")}finally{setSaving(false);submitting.current=false}};
  return <div className="estimate-commercial__modal-scrim" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget&&!saving)onClose()}}>
    <section className="estimate-commercial__modal supplier-rfq ui-card" role="dialog" aria-modal="true" aria-labelledby="supplier-rfq-title" aria-busy={loading||saving}>
      <header><div><span className="ui-eyebrow">Reviewed supplier request</span><h2 id="supplier-rfq-title">Request supplier estimate / revision</h2><p>{context?`${context.project.clientReference} · ${context.project.clientName} · ${context.project.name}`:`${estimateRef} · loading Project context…`}</p></div><button className="ui-button" disabled={saving} onClick={onClose}>Close</button></header>
      {loading?<p className="ui-status" role="status">Loading current Project files and suppliers…</p>:null}
      {notice?<p className="ui-status ui-status--success" role="status">{notice}</p>:null}
      {error?<div className="ui-status ui-status--error" role="alert"><strong>{error}</strong><span>No completed work will be repeated. Check the details and retry.</span></div>:null}
      {result?<section className="supplier-rfq__result" aria-live="polite"><span className="ui-status">{result.status==="sent"?"Supplier request sent":"Prepared for review — not sent"}</span><h3>{result.subject}</h3><p>{result.supplierName} · request revision {result.revisionNo}</p>{result.responseDueAt?<p><strong>Response due:</strong> {new Date(result.responseDueAt).toLocaleDateString("en-GB")}</p>:null}<p>{result.nextAction||"Review the saved Email draft before sending."}</p><div className="ui-action-row">{result.status!=="sent"?<button className="ui-button" onClick={()=>reopen(result)}>Continue editing</button>:null}<button className="ui-button ui-button--primary" onClick={onClose}>Done</button></div><details><summary>View details</summary><dl><div><dt>Request type</dt><dd>{result.requestKind==="revision"?"Supplier revision":"Initial supplier estimate"}</dd></div><div><dt>Recipient</dt><dd>{result.recipient}</dd></div><div><dt>Files</dt><dd>{result.documentSnapshot.length?result.documentSnapshot.map(item=>item.fileName).join(", "):"No selected Project files"}</dd></div><div><dt>Saved Email</dt><dd>{result.communicationMessageId}</dd></div></dl></details></section>:context?<>
        <div className="supplier-rfq__step"><span>1</span><div><h3>Choose request type</h3><p>Creating an editable Estimate revision is a separate action. This step prepares or sends supplier correspondence and never changes issued evidence.</p></div></div>
        <div className="supplier-rfq__mode" role="radiogroup" aria-label="Supplier request type"><label><input type="radio" name="supplier-request-kind" checked={requestKind==="initial"} onChange={()=>applyMode("initial",context)}/> Initial supplier estimate</label><label><input type="radio" name="supplier-request-kind" checked={requestKind==="revision"} disabled={!context.revisionRequest} onChange={()=>applyMode("revision",context)}/> Revision to the tracked customer request</label></div>
        {requestKind==="revision"&&context.revisionRequest?<p className="ui-status ui-status--warning">Customer changes retained against issued revision {context.revisionRequest.summary.sourceRevision}. Current state: {context.revisionRequest.status.replaceAll("_"," ")}.</p>:null}
        <div className="supplier-rfq__step"><span>2</span><div><h3>Choose supplier and recipient</h3><p>The request stays linked to this exact working Estimate and supplier.</p></div></div>
        <div className="supplier-rfq__fields"><label>Supplier<select className="ui-select" value={supplierId} onChange={event=>setSupplierId(event.currentTarget.value)}><option value="">Choose supplier</option>{context.suppliers.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Email address<input className="ui-input" type="email" value={recipient} onChange={event=>setRecipient(event.currentTarget.value)} placeholder={selectedSupplier?`${selectedSupplier.name} recipient`:"Supplier recipient"}/></label></div>
        <div className="supplier-rfq__step"><span>3</span><div><h3>Review Project files</h3><p>Current schedules and drawings are suggested when available. Only checked files are attached; the tracked change summary is added automatically for a revision request.</p></div></div>
        <div className="supplier-rfq__documents">{context.documents.length?context.documents.map(document=><label key={document.id}><input type="checkbox" checked={documentIds.includes(document.id)} onChange={event=>toggleDocument(document.id,event.currentTarget.checked)}/><span><strong>{document.fileName}</strong><small>{document.documentType.replaceAll("_"," ")}</small></span></label>):<p className="ui-empty-state">No current Project files are available. You can prepare the message without an attachment or add files first.</p>}</div>
        <div className="supplier-rfq__step"><span>4</span><div><h3>Review the message</h3><p>Nothing is sent until you choose the sending option.</p></div></div>
        <div className="supplier-rfq__fields"><label className="supplier-rfq__wide">Subject<input className="ui-input" value={subject} onChange={event=>setSubject(event.currentTarget.value)}/></label><label className="supplier-rfq__wide">Message<textarea className="ui-textarea" rows={6} value={bodyText} onChange={event=>setBodyText(event.currentTarget.value)}/></label></div>
        {context.delivery.deliveryMode==="test_allowlist"?<label className="supplier-rfq__send"><input type="checkbox" checked={sendNow} onChange={event=>setSendNow(event.currentTarget.checked)}/> Send now to the configured factory test address</label>:<p className="ui-status ui-status--warning">Preview only. QuoteSuite will save an Email draft; sending is not enabled in this workspace.</p>}
        {context.enquiries.length?<details open={context.enquiries.some(item=>item.status!=="sent"||Boolean(item.followupFailure))}><summary>View or reopen previous requests ({context.enquiries.length})</summary><div className="supplier-rfq__history">{context.enquiries.map(item=><article key={item.id}><strong>{item.supplierName||"Supplier"} · request revision {item.revisionNo}</strong><span>{item.subject}</span><small>{new Date(item.createdAt).toLocaleString("en-GB")} · {item.status==="sent"?`sent${item.sentAt?` ${new Date(item.sentAt).toLocaleString("en-GB")}`:""}`:"prepared — not sent"}{item.responseDueAt?` · response due ${new Date(item.responseDueAt).toLocaleString("en-GB")}`:""}</small>{item.requestKind==="revision"&&item.status==="sent"&&!item.followupSentAt?<details><summary>Adjust response deadline</summary><label>Expected supplier response<input className="ui-input" type="datetime-local" value={dueDrafts[item.id]??localDateTime(item.responseDueAt)} onChange={event=>setDueDrafts(current=>({...current,[item.id]:event.currentTarget.value}))}/></label><button className="ui-button" disabled={saving} onClick={()=>void adjustDue(item)}>Save reviewed deadline</button></details>:null}{item.followupFailure?<><span className="ui-status ui-status--error">Follow-up failed: {item.followupFailure}</span><button className="ui-button" disabled={saving} onClick={()=>void retryFollowup(item)}>Retry follow-up safely</button></>:null}<button className="ui-button ui-button--ghost" onClick={()=>reopen(item)}>{item.status==="sent"?"View request":"Reopen prepared request"}</button></article>)}</div></details>:null}
        {context.legacyPrepared.length?<details open><summary>Earlier prepared revision requests ({context.legacyPrepared.length})</summary><p>These earlier actions recorded an internal preparation marker but did not create or send an Email. Continue one here to make the correspondence accessible.</p><div className="supplier-rfq__history">{context.legacyPrepared.map(item=><article key={item.id}><strong>{item.supplierName||"Supplier revision"}</strong><small>{new Date(item.createdAt).toLocaleString("en-GB")} · prepared — not sent</small><button className="ui-button ui-button--ghost" onClick={()=>{setRequestKind(context.revisionRequest?"revision":"initial");setBodyText(item.request.requestedChanges||bodyText);setDocumentIds(item.request.supportingDocumentIds||[]);setResult(null)}}>Continue prepared request</button></article>)}</div></details>:null}
        <footer><button className="ui-button" disabled={saving} onClick={onClose}>Cancel</button><button className="ui-button ui-button--primary" disabled={saving||!supplierId||!recipient.trim()||!subject.trim()||!bodyText.trim()} onClick={()=>void submit()}>{saving?(sendNow?"Sending supplier request…":"Saving reviewed draft…"):(sendNow?"Send supplier request":"Prepare for review")}</button></footer>
      </>:null}
    </section>
  </div>;
}
