import {createHash,randomUUID} from "node:crypto";
import {readFile,writeFile} from "node:fs/promises";
import {ensureManagedParent,resolveManagedPath,resolveAttachmentRoot} from "../supplierQuotes/managedAttachmentStorage.js";
import {createInstallationWorkforceService} from "../projectCalculatorLab/installationWorkforceService.js";

const clean=value=>String(value??"").trim(),parse=(value,fallback)=>{try{return JSON.parse(value||"")??fallback}catch{return fallback}},hash=value=>createHash("sha256").update(value).digest("hex");
const fail=(message,status=422,code="installation_rams_invalid")=>Object.assign(new Error(message),{status,code});
const HAZARDS=["Delivery and storage","Removal and making safe","Glass handling","Lifting","Work at height","Fixing and sealing","Public protection","Waste","Emergency arrangements"];
const sourcePosition=position=>({id:clean(position.id),reference:clean(position.reference||position.positionRef||position.name),quantity:Number(position.quantity)||1,widthMm:Number(position.widthMm)||null,heightMm:Number(position.heightMm)||null,product:clean(position.productType||position.productClass||position.system),opening:clean(position.openingType||position.configuration),room:clean(position.roomName||position.room),floor:clean(position.floor)});

export function createInstallationSafetyService(db,{id=randomUUID,clock=()=>new Date(),attachmentRoot=resolveAttachmentRoot()}={}){
  const now=()=>clock().toISOString(),workforce=createInstallationWorkforceService(db);
  async function sourceContext(estimateId){
    const row=await db.get(`SELECT e.*,c.name client_name,c.client_ref,p.name project_name,p.id canonical_project_id,o.id order_id,o.order_ref,o.source_estimate_revision order_revision
      FROM estimates e JOIN clients c ON c.id=e.client_id LEFT JOIN projects p ON p.id=e.project_id
      LEFT JOIN orders o ON o.source_estimate_id=e.id WHERE e.id=? AND e.deleted_at IS NULL AND c.deleted_at IS NULL ORDER BY o.created_at DESC LIMIT 1`,estimateId);
    if(!row)throw fail("Estimate not found.",404,"estimate_not_found");
    const scenario=await db.get(`SELECT s.id,s.revision_number,o.options_json FROM project_calculator_lab_scenarios s LEFT JOIN project_calculator_lab_options o ON o.scenario_id=s.id WHERE s.estimate_id=? ORDER BY s.updated_at DESC LIMIT 1`,estimateId),options=parse(scenario?.options_json,{}),profile=options.installationProfile||{},positions=parse(row.positions_json,[]).map(sourcePosition);
    const selectedTeamId=clean(profile.selectedTeamId),team=selectedTeamId?await db.get("SELECT id,name FROM installation_teams WHERE id=?",selectedTeamId):null;
    const operational={estimateId:row.id,estimateReference:row.estimate_ref,sourceRevision:Number(row.revision_no)||0,orderId:row.order_id||null,orderReference:row.order_ref||null,clientId:row.client_id,clientName:row.client_name,projectId:row.canonical_project_id||null,projectName:row.project_name||"",siteAddress:row.project_address||"",postcode:row.postcode||"",positions,scenarioId:scenario?.id||null,scenarioRevision:Number(scenario?.revision_number)||null,selectedTeamId:team?.id||null,teamName:team?.name||null,attendanceStart:clean(row.order_meta_json&&parse(row.order_meta_json,{}).installationDate)||null,materials:options.installationMaterials||null,equipment:{lifting:profile.liftingEquipment||null,skip:profile.skipHire||null}};
    return{...operational,fingerprint:hash(JSON.stringify(operational))};
  }
  const mapVersion=(row,currentIssuedVersion)=>row&&({id:row.id,version:Number(row.version),state:row.state==="issued"&&Number(row.version)!==Number(currentIssuedVersion)?"superseded":row.state,title:row.title,workSummary:row.work_summary,siteConditions:parse(row.site_conditions_json,{}),hazards:parse(row.hazards_json,[]),methodSteps:parse(row.method_steps_json,[]),emergencyArrangements:row.emergency_arrangements,publicProtection:row.public_protection,wasteArrangements:row.waste_arrangements,specialistAssessment:row.specialist_assessment,supportingDocumentIds:parse(row.supporting_document_ids_json,[]),sourceSnapshot:parse(row.source_snapshot_json,{}),sourceFingerprint:row.source_fingerprint,reviewerName:row.reviewer_name,reviewerRole:row.reviewer_role,reviewedAt:row.reviewed_at,competentPersonConfirmed:!!row.competent_person_confirmed,issuedAt:row.issued_at,pdfFileName:row.pdf_file_name,pdfSha256:row.pdf_sha256,pdfSizeBytes:row.pdf_size_bytes,downloadUrl:row.pdf_storage_key?`/api/installation-safety/rams/${row.rams_id}/versions/${row.version}/pdf`:null,createdAt:row.created_at,updatedAt:row.updated_at});
  async function get(ramsId){
    const record=await db.get("SELECT * FROM installation_rams WHERE id=?",ramsId);if(!record)throw fail("RAMS record not found.",404,"installation_rams_not_found");
    const context=await sourceContext(record.estimate_id),versions=(await db.all("SELECT * FROM installation_rams_versions WHERE rams_id=? ORDER BY version DESC",ramsId)).map(row=>mapVersion(row,record.current_issued_version)),draft=versions.find(item=>item.state==="draft")||null,issued=versions.find(item=>item.state==="issued")||versions.find(item=>item.state==="superseded")||null,briefings=await db.all("SELECT * FROM installation_rams_briefings WHERE rams_id=? ORDER BY acknowledged_at",ramsId);
    const changeReasons=issued&&issued.sourceFingerprint!==context.fingerprint?["The Estimate/Order schedule, team, equipment or site information changed after this RAMS was issued. Review and issue a new revision."]:[];
    return{id:record.id,clientId:record.client_id,projectId:record.project_id,estimateId:record.estimate_id,orderId:record.order_id,status:changeReasons.length?"review_required":record.status,currentDraftVersion:record.current_draft_version,currentIssuedVersion:record.current_issued_version,context,draft,issued,versions,briefings:briefings.map(row=>({id:row.id,version:row.rams_version,installerId:row.installer_id,personName:row.person_name,acknowledgedAt:row.acknowledged_at,acknowledgement:row.acknowledgement,recordedBy:row.recorded_by})),reviewReasons:changeReasons};
  }
  async function listForEstimate(estimateId){const rows=await db.all("SELECT id FROM installation_rams WHERE estimate_id=? ORDER BY updated_at DESC",estimateId);return Promise.all(rows.map(row=>get(row.id)))}
  async function create(estimateId,input={}){
    const context=await sourceContext(estimateId),existing=await db.get("SELECT id FROM installation_rams WHERE estimate_id=? AND source_revision=? AND order_id IS ?",estimateId,context.sourceRevision,context.orderId);if(existing)return get(existing.id);
    const ramsId=id(),versionId=id(),at=now(),hazards=HAZARDS.map(hazard=>({hazard,applies:null,controls:[],notes:"",reviewed:false})),workSummary=clean(input.workSummary)||`${context.positions.length} scheduled position(s) for installation. Confirm scope, removal, access and sequence.`;
    await db.exec("BEGIN IMMEDIATE");try{await db.run("INSERT INTO installation_rams(id,client_id,project_id,estimate_id,order_id,source_revision,status,current_draft_version,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,'draft',1,?,?,?)",ramsId,context.clientId,context.projectId,estimateId,context.orderId,context.sourceRevision,input.actorId||"User",at,at);await db.run(`INSERT INTO installation_rams_versions(id,rams_id,version,state,title,work_summary,hazards_json,method_steps_json,source_snapshot_json,source_fingerprint,created_by,created_at,updated_at)
      VALUES(?,?,1,'draft',?,?,?,?,?,?,?, ?,?)`,versionId,ramsId,clean(input.title)||`Installation RAMS · ${context.orderReference||context.estimateReference}`,workSummary,JSON.stringify(hazards),JSON.stringify([]),JSON.stringify(context),context.fingerprint,input.actorId||"User",at,at);await db.exec("COMMIT")}catch(error){await db.exec("ROLLBACK").catch(()=>{});throw error}return get(ramsId);
  }
  async function validateDocuments(context,ids){const unique=[...new Set((Array.isArray(ids)?ids:[]).map(clean).filter(Boolean))];for(const documentId of unique){const document=await db.get("SELECT id FROM canonical_documents WHERE id=? AND removed_at IS NULL AND trashed=0 AND (estimate_id=? OR project_id=? OR client_id=?)",documentId,context.estimateId,context.projectId,context.clientId);if(!document)throw fail("One selected supporting file is unavailable in this Client, Project or Estimate. Review Files and try again.",409,"rams_document_unavailable")}return unique}
  async function saveDraft(ramsId,input={}){
    const current=await get(ramsId),draft=current.draft;if(!draft)throw fail("Create a new RAMS revision before editing issued evidence.",409,"rams_draft_required");
    const hazards=Array.isArray(input.hazards)?input.hazards.map(item=>({hazard:clean(item.hazard),applies:item.applies===true?true:item.applies===false?false:null,controls:Array.isArray(item.controls)?item.controls.map(clean).filter(Boolean):[],notes:clean(item.notes),reviewed:item.reviewed===true})).filter(item=>item.hazard):draft.hazards,documents=await validateDocuments(current.context,input.supportingDocumentIds??draft.supportingDocumentIds),at=now();
    const competentConfirmed=input.competentPersonConfirmed===undefined?draft.competentPersonConfirmed:input.competentPersonConfirmed===true;
    await db.run(`UPDATE installation_rams_versions SET title=?,work_summary=?,site_conditions_json=?,hazards_json=?,method_steps_json=?,emergency_arrangements=?,public_protection=?,waste_arrangements=?,specialist_assessment=?,supporting_document_ids_json=?,source_snapshot_json=?,source_fingerprint=?,reviewer_name=?,reviewer_role=?,competent_person_confirmed=?,reviewed_at=?,updated_at=? WHERE id=? AND state='draft'`,clean(input.title??draft.title),clean(input.workSummary??draft.workSummary),JSON.stringify(input.siteConditions??draft.siteConditions),JSON.stringify(hazards),JSON.stringify(Array.isArray(input.methodSteps)?input.methodSteps.map(clean).filter(Boolean):draft.methodSteps),clean(input.emergencyArrangements??draft.emergencyArrangements),clean(input.publicProtection??draft.publicProtection),clean(input.wasteArrangements??draft.wasteArrangements),clean(input.specialistAssessment??draft.specialistAssessment),JSON.stringify(documents),JSON.stringify(current.context),current.context.fingerprint,clean(input.reviewerName??draft.reviewerName)||null,clean(input.reviewerRole??draft.reviewerRole)||null,competentConfirmed?1:0,competentConfirmed?(draft.reviewedAt||at):null,at,draft.id);await db.run("UPDATE installation_rams SET updated_at=? WHERE id=?",at,ramsId);return get(ramsId);
  }
  function unknowns(draft){const result=[];if(!clean(draft.workSummary))result.push("Work scope is not confirmed.");if(!clean(draft.siteConditions?.description))result.push("Site conditions are not confirmed.");for(const hazard of draft.hazards){if(hazard.applies===null||!hazard.reviewed)result.push(`${hazard.hazard} has not been reviewed.`);else if(hazard.applies&&!hazard.controls.length)result.push(`${hazard.hazard} requires controls.`)}if(!draft.methodSteps.length)result.push("The installation method is not confirmed.");if(!clean(draft.emergencyArrangements))result.push("Emergency arrangements are not confirmed.");return result}
  async function issue(ramsId,input={}){
    let current=await saveDraft(ramsId,input),draft=current.draft,missing=unknowns(draft);if(!draft.competentPersonConfirmed||!clean(draft.reviewerName)||!clean(draft.reviewerRole))missing.push("A competent responsible person must review and confirm this revision.");if(missing.length)throw fail(`RAMS cannot be issued yet: ${missing.join(" ")}`,409,"rams_review_incomplete");
    let qualificationSummary=[];if(current.context.selectedTeamId&&clean(input.attendanceStart||current.context.attendanceStart)){const check=await workforce.qualificationCheck(current.context.selectedTeamId,{attendanceStart:input.attendanceStart||current.context.attendanceStart,attendanceEnd:input.attendanceEnd||input.attendanceStart||current.context.attendanceStart,requiredTypes:Array.isArray(input.requiredQualificationTypes)?input.requiredQualificationTypes:[]});qualificationSummary=check.members.map(member=>({name:member.name,summary:member.qualifications.length?member.qualifications.map(item=>`${item.typeLabel}: ${item.status}${item.expiryDate?` (${item.expiryDate})`:""}`).join("; "):"No qualifications supplied"}));if(check.gaps.length)missing=[...missing,...check.gaps]}
    if(missing.length)throw fail(`RAMS cannot be issued yet: ${missing.join(" ")}`,409,"rams_qualification_review_required");
    const at=now(),projection={...current.context,...draft,reference:current.context.orderReference||current.context.estimateReference,version:draft.version,issuedAt:at,siteConditions:clean(draft.siteConditions?.description),unknowns:[],qualificationSummary},{renderInstallationRamsPdf}=await import("./installationRamsRenderer.js"),bytes=await renderInstallationRamsPdf(projection),fileName=`${projection.reference.replace(/[^A-Za-z0-9_-]+/g,"-")}-RAMS-R${draft.version}.pdf`,storageKey=`installation-rams/${ramsId}/${draft.id}.pdf`,target=await ensureManagedParent(storageKey,attachmentRoot);await writeFile(target,bytes,{flag:"wx"});
    await db.exec("BEGIN IMMEDIATE");try{await db.run("UPDATE installation_rams_versions SET state='issued',issued_at=?,pdf_storage_key=?,pdf_file_name=?,pdf_sha256=?,pdf_size_bytes=?,updated_at=? WHERE id=? AND state='draft'",at,storageKey,fileName,hash(bytes),bytes.length,at,draft.id);await db.run("UPDATE installation_rams SET status='issued',current_issued_version=?,current_draft_version=?,updated_at=? WHERE id=?",draft.version,draft.version+1,at,ramsId);await db.exec("COMMIT")}catch(error){await db.exec("ROLLBACK").catch(()=>{});throw error}return get(ramsId)
  }
  async function newRevision(ramsId){const current=await get(ramsId);if(current.draft)return current;if(!current.issued)throw fail("There is no issued RAMS to revise.",409);const at=now(),next=current.issued.version+1,versionId=id(),source=await sourceContext(current.estimateId);await db.run(`INSERT INTO installation_rams_versions(id,rams_id,version,state,title,work_summary,site_conditions_json,hazards_json,method_steps_json,emergency_arrangements,public_protection,waste_arrangements,specialist_assessment,supporting_document_ids_json,source_snapshot_json,source_fingerprint,created_by,created_at,updated_at)
    VALUES(?,?,?,'draft',?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,versionId,ramsId,next,current.issued.title,current.issued.workSummary,JSON.stringify(current.issued.siteConditions),JSON.stringify(current.issued.hazards),JSON.stringify(current.issued.methodSteps),current.issued.emergencyArrangements,current.issued.publicProtection,current.issued.wasteArrangements,current.issued.specialistAssessment,JSON.stringify(current.issued.supportingDocumentIds),JSON.stringify(source),source.fingerprint,"User",at,at);await db.run("UPDATE installation_rams SET status='draft',current_draft_version=?,updated_at=? WHERE id=?",next,at,ramsId);return get(ramsId)}
  async function acknowledge(ramsId,input={}){const current=await get(ramsId);if(!current.issued)throw fail("Issue the RAMS before recording a workforce briefing.",409,"rams_issue_required");const person=clean(input.personName),key=clean(input.idempotencyKey);if(!person||!key)throw fail("Choose the person and provide a retry-safe acknowledgement.");const at=clean(input.acknowledgedAt)||now(),existing=await db.get("SELECT id FROM installation_rams_briefings WHERE idempotency_key=?",key);if(!existing)await db.run("INSERT INTO installation_rams_briefings(id,rams_id,rams_version,installer_id,person_name,acknowledged_at,acknowledgement,recorded_by,idempotency_key) VALUES(?,?,?,?,?,?,?,?,?)",id(),ramsId,current.issued.version,clean(input.installerId)||null,person,at,clean(input.acknowledgement)||"Briefed and understood",input.recordedBy||"User",key);return get(ramsId)}
  async function readPdf(ramsId,version){const row=await db.get("SELECT * FROM installation_rams_versions WHERE rams_id=? AND version=? AND state IN('issued','superseded')",ramsId,Number(version));if(!row?.pdf_storage_key)throw fail("Issued RAMS PDF not found.",404);return{fileName:row.pdf_file_name,sha256:row.pdf_sha256,bytes:await readFile(resolveManagedPath(row.pdf_storage_key,attachmentRoot))}}
  return{sourceContext,listForEstimate,get,create,saveDraft,issue,newRevision,acknowledge,readPdf};
}
