# =====================================================================
# QuoteSync — Phase 4B: Extract DefaultsEditor component from App.tsx
# Script: 20260220_17_phase4b_extract_defaults_editor.ps1
# Run from: PS C:\Github\QuoteSync\web\ps1_patches>
#
# Creates:
#   src\features\estimateDefaults\DefaultsEditor.tsx
#
# Updates:
#   src\App.tsx  (removes local DefaultsEditor block; adds import)
#
# Scope:
# - No UI/layout/logic changes. Component moved 1:1.
# - Keeps App.tsx labelStyle/Input/H3/Small untouched (they're used elsewhere).
# - The extracted component file includes local copies of Input/H3/Small + labelStyle
#   to avoid cross-file coupling (matching existing UI output).
#
# Safety:
# - Auto-backup touched files to _backups\<timestamp>\
# - Fail fast if anchors ambiguous or target file exists
# =====================================================================

$ErrorActionPreference = "Stop"

function Ok($m){ Write-Host "OK: $m" -ForegroundColor Green }
function Info($m){ Write-Host "INFO: $m" -ForegroundColor Cyan }
function Fail($m){ Write-Host "ERROR: $m" -ForegroundColor Red; throw $m }

function Get-Text([string]$path){
  if (!(Test-Path $path)) { Fail "Missing file: $path" }
  return [System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8)
}
function Set-Text([string]$path, [string]$text){
  $dir = Split-Path -Parent $path
  if (!(Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
  [System.IO.File]::WriteAllText($path, $text, [System.Text.Encoding]::UTF8)
}
function Ensure-Once([string]$name, [string]$text, [string]$pattern){
  $rx = [regex]::new($pattern, [System.Text.RegularExpressions.RegexOptions]::Multiline)
  $m = $rx.Matches($text)
  if ($m.Count -ne 1) { Fail "Ambiguous (expected 1 match, got $($m.Count)): $name" }
}
function Replace-Once([string]$name, [ref]$textRef, [string]$pattern, [string]$replacement){
  $rx = [regex]::new($pattern, [System.Text.RegularExpressions.RegexOptions]::Multiline)
  $m = $rx.Matches($textRef.Value)
  if ($m.Count -ne 1) { Fail "Ambiguous (expected 1 match, got $($m.Count)): $name" }
  $textRef.Value = $rx.Replace($textRef.Value, $replacement, 1)
}
function Ensure-NotPresent([string]$name, [string]$text, [string]$needle){
  if ($text -match [regex]::Escape($needle)) { Fail "Refusing to re-apply (already present): $name contains '$needle'" }
}
function Backup-File([string]$root, [string]$absPath, [string]$backupRoot){
  if (!(Test-Path $absPath)) { Fail "Cannot backup missing file: $absPath" }
  $rel = (Resolve-Path $absPath).Path.Substring((Resolve-Path $root).Path.Length).TrimStart('\')
  $dest = Join-Path $backupRoot $rel
  $destDir = Split-Path -Parent $dest
  if (!(Test-Path $destDir)) { New-Item -ItemType Directory -Force -Path $destDir | Out-Null }
  Copy-Item -Force $absPath $dest
  Ok "Backed up $rel -> $dest"
}

# --- Resolve project root (web) from ps1_patches ---
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$root = Resolve-Path (Join-Path $scriptDir "..")  # ...\web
Set-Location $root
Info "Run directory: $root"

$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$backupRoot = Join-Path $root "_backups\$timestamp"
New-Item -ItemType Directory -Force -Path $backupRoot | Out-Null
Ok "Backup folder: $backupRoot"

$appPath = Join-Path $root "src\App.tsx"
$targetPath = Join-Path $root "src\features\estimateDefaults\DefaultsEditor.tsx"

Backup-File $root $appPath $backupRoot
if (Test-Path $targetPath) { Fail "Refusing to overwrite existing file: src\features\estimateDefaults\DefaultsEditor.tsx" }

$appTxt = Get-Text $appPath

# Guard: do not re-apply
Ensure-NotPresent "App.tsx" $appTxt './features/estimateDefaults/DefaultsEditor'

# Anchor: DefaultsEditor block must exist exactly once and must end right before Main App comment
$blockPattern = '(?s)\/\* =========================\r?\n   Defaults Editor[\s\S]*?\r?\n\*\/\r?\n\r?\nfunction DefaultsEditor\([\s\S]*?\r?\n\}\r?\n\r?\n(?=\/\* =========================\r?\n   Main App)'
Ensure-Once "App.tsx DefaultsEditor block" $appTxt $blockPattern

# Extract block
$rx = [regex]::new($blockPattern, [System.Text.RegularExpressions.RegexOptions]::Multiline)
$block = $rx.Match($appTxt).Value

# Build new file content: local UI primitives + moved component (1:1)
# Convert `function DefaultsEditor` to `export default function DefaultsEditor`
$blockOut = $block -replace 'function DefaultsEditor\(', 'export default function DefaultsEditor('

$header = @"
// Auto-generated by QuoteSync Phase 4B extraction patch.
// Moved from src/App.tsx (no UI/layout/logic changes).
import React, { useEffect } from "react";
import * as Models from "../../models/types";
import type { EstimateDefaults } from "../../models/types";
import { PRODUCT_TYPES, SUPPLIERS, WOOD_TYPES, FINISHES_BY_TYPE, allProductsForSupplier, firstProductForSupplier, isTimberProductType } from "../catalog/defaultCatalog";
import { HINGE_TYPES, UG_DOUBLE, UG_TRIPLE, HANDLE_TYPES, SUN_PROTECTION, CILL_DEPTHS, FRAME_EXTS } from "./defaultEstimateDefaults";

function H3({ children }: { children: React.ReactNode }) {
  return <h3 style={{ fontSize: 14, margin: 0, fontWeight: 800, color: "#18181b" }}>{children}</h3>;
}
function Small({ children }: { children: React.ReactNode }) {
  return <div style={{ fontSize: 12, color: "#71717a" }}>{children}</div>;
}
function Input({
  value,
  onChange,
  placeholder,
  type = "text",
  list,
  disabled,
  readOnly,
}: {
  value: string;
  onChange: (v: string) => void;
  placeholder?: string;
  type?: string;
  list?: string;
  disabled?: boolean;
  readOnly?: boolean;
}) {
  return (
    <input
      type={type}
      value={value}
      placeholder={placeholder}
      list={list}
      disabled={disabled}
      readOnly={readOnly}
      onChange={(e) => onChange(e.target.value)}
      style={{
        width: "100%",
        borderRadius: 12,
        border: "1px solid #e4e4e7",
        padding: "10px 12px",
        fontSize: 14,
        outline: "none",
      }}
    />
  );
}

const labelStyle: React.CSSProperties = { fontSize: 13, color: "#3f3f46", fontWeight: 700, marginBottom: 6 };

"@

Set-Text $targetPath ($header + $blockOut.TrimStart("`r","`n") + "`r`n")
Ok "Created: src\features\estimateDefaults\DefaultsEditor.tsx"

# Remove the block from App.tsx
Replace-Once "App.tsx remove DefaultsEditor block" ([ref]$appTxt) $blockPattern "`r`n"

# Insert import for DefaultsEditor near other feature imports (after EstimatePickerTabs import)
Ensure-Once "App.tsx EstimatePickerTabs import anchor" $appTxt '^import EstimatePickerTabs from "\./features/estimatePicker/EstimatePickerTabs";\s*$'
$importInsert = 'import DefaultsEditor from "./features/estimateDefaults/DefaultsEditor";' + "`r`n"
Replace-Once "App.tsx insert DefaultsEditor import" ([ref]$appTxt) '(^import EstimatePickerTabs from "\./features/estimatePicker/EstimatePickerTabs";\r?\n)' "`$1$importInsert"

Set-Text $appPath $appTxt
Ok "Patched: src\App.tsx"

Ok "Phase 4B complete: DefaultsEditor extracted."
Info "Next: npm run dev"
