# QuoteSync patch: Add 1 default estimate (with 5 positions) to each seeded default client
# Scope: ONLY the seeded default clients in defaultClients.ts (Option 1).
# Notes:
# - Adds one demo estimate per default client.
# - Adds 5 demo positions (W-001..W-005) to that estimate.
# - Uses local uid() to generate IDs; estimate refs use 2026-9001, 2026-9002 etc (demo range).
#
# Run from: PS C:\Github\QuoteSync\web\ps1_patches>
#   Unblock-File .\THIS_SCRIPT.ps1
#   pwsh -ExecutionPolicy Bypass -File .\THIS_SCRIPT.ps1

$ErrorActionPreference = "Stop"
function Fail($m){ Write-Host "ERROR: $m" -ForegroundColor Red; throw $m }
function Ok($m)  { Write-Host "OK: $m" -ForegroundColor Green }
function Warn($m){ Write-Host "WARN: $m" -ForegroundColor Yellow }

$runDir = (Get-Location).Path
Write-Host ("Run directory: " + $runDir)

$webRoot = Resolve-Path (Join-Path $runDir "..") | Select-Object -ExpandProperty Path
if (-not (Test-Path (Join-Path $webRoot "package.json"))) { Fail "Could not detect web root (package.json not found) at: $webRoot" }
Ok ("Detected web root: " + $webRoot)

# Find defaultClients.ts inside src (we don't assume a fixed folder)
$matches = Get-ChildItem -Path (Join-Path $webRoot "src") -Recurse -File -Filter "defaultClients.ts" -ErrorAction Stop | Select-Object -ExpandProperty FullName
if (-not $matches -or $matches.Count -eq 0) { Fail "Could not find defaultClients.ts under src/." }
if ($matches.Count -gt 1) {
  Write-Host "Found multiple defaultClients.ts files:" -ForegroundColor Yellow
  $matches | ForEach-Object { Write-Host (" - " + $_) -ForegroundColor Yellow }
  Fail "Ambiguous: multiple defaultClients.ts files found. Please remove duplicates or tell me which to patch."
}
$target = $matches[0]
Ok ("Target file: " + $target)

# Backup folder
$backupsRoot = Join-Path $webRoot "_backups"
New-Item -ItemType Directory -Force -Path $backupsRoot | Out-Null
$stamp = Get-Date -Format "yyyyMMdd_HHmmss"
$backupDir = Join-Path $backupsRoot $stamp
New-Item -ItemType Directory -Force -Path $backupDir | Out-Null
Ok ("Backup folder: " + $backupDir)

Copy-Item -Force $target (Join-Path $backupDir "defaultClients.ts")
Ok "Backed up defaultClients.ts"

# Write updated content
$fixed = @'
// Auto-generated by QuoteSync Phase 4C extraction patch.
// Seed/demo clients moved out of src/App.tsx (no logic changes).
import * as Models from "../../models/types";
import type { Client, Estimate, Position } from "../../models/types";
import { makeDefaultEstimateDefaults } from "../estimateDefaults/defaultEstimateDefaults";
export const DEFAULT_CUSTOMER_ADDRESS = ["4 Glebe Road", "Cowdenbeath", "Fife", "KY4 9FA"].join("\n");

function makeDemoPositions(uid: () => string): Position[] {
  return [
    {
      id: Models.asPositionId(uid()),
      positionRef: "W-001",
      qty: 1,
      roomName: "",
      widthMm: 1000,
      heightMm: 1200,
      fieldsX: 1,
      fieldsY: 1,
      insertion: "Fixed",
      cellInsertions: { "0,0": "Fixed" },
      positionType: "Window",
      useEstimateDefaults: true,
      overrides: {},
    },
    {
      id: Models.asPositionId(uid()),
      positionRef: "W-002",
      qty: 1,
      roomName: "",
      widthMm: 900,
      heightMm: 1200,
      fieldsX: 1,
      fieldsY: 1,
      insertion: "Fixed",
      cellInsertions: { "0,0": "Fixed" },
      positionType: "Window",
      useEstimateDefaults: true,
      overrides: {},
    },
    {
      id: Models.asPositionId(uid()),
      positionRef: "W-003",
      qty: 1,
      roomName: "",
      widthMm: 1200,
      heightMm: 1400,
      fieldsX: 1,
      fieldsY: 1,
      insertion: "Fixed",
      cellInsertions: { "0,0": "Fixed" },
      positionType: "Window",
      useEstimateDefaults: true,
      overrides: {},
    },
    {
      id: Models.asPositionId(uid()),
      positionRef: "W-004",
      qty: 1,
      roomName: "",
      widthMm: 1500,
      heightMm: 1200,
      fieldsX: 1,
      fieldsY: 1,
      insertion: "Fixed",
      cellInsertions: { "0,0": "Fixed" },
      positionType: "Window",
      useEstimateDefaults: true,
      overrides: {},
    },
    {
      id: Models.asPositionId(uid()),
      positionRef: "W-005",
      qty: 1,
      roomName: "",
      widthMm: 800,
      heightMm: 1000,
      fieldsX: 1,
      fieldsY: 1,
      insertion: "Fixed",
      cellInsertions: { "0,0": "Fixed" },
      positionType: "Window",
      useEstimateDefaults: true,
      overrides: {},
    },
  ];
}

function makeDemoEstimate(uid: () => string, demoNo: number): Estimate {
  const base = "2026-" + String(9000 + demoNo).padStart(4, "0");
  return {
    id: Models.asEstimateId(uid()),
    estimateRef: base,
    baseEstimateRef: base,
    revisionNo: 0,
    status: "Draft",
    defaults: makeDefaultEstimateDefaults(),
    positions: makeDemoPositions(uid),
  };
}


export function makeDefaultClients(opts: { uid: () => string; nextClientRef: (n: number) => string }): Client[]  {
  return [
    {
      id: Models.asClientId(opts.uid()),
      type: "Business",
      clientRef: opts.nextClientRef(1),
      clientName: "Ecofenster Ltd",
      businessName: "Ecofenster Ltd",
      contactPerson: "",
      email: "",
      mobile: "07882 809 453",
      home: "",
      projectName: "",
      projectAddress: DEFAULT_CUSTOMER_ADDRESS,
      invoiceAddress: DEFAULT_CUSTOMER_ADDRESS,
      estimates: [makeDemoEstimate(opts.uid, 1)],
    },
    {
      id: Models.asClientId(opts.uid()),
      type: "Individual",
      clientRef: opts.nextClientRef(2),
      clientName: "Craig Ferguson",
      businessName: "",
      contactPerson: "",
      email: "",
      mobile: "07882 809 453",
      home: "",
      projectName: "",
      projectAddress: DEFAULT_CUSTOMER_ADDRESS,
      invoiceAddress: DEFAULT_CUSTOMER_ADDRESS,
      estimates: [makeDemoEstimate(opts.uid, 2)],
    },
  ];
}



'@

Set-Content -Path $target -Value $fixed -Encoding UTF8
Ok "Wrote updated defaultClients.ts (seed clients now include a demo estimate + 5 positions)"

Write-Host ""
Write-Host "Starting dev server..." -ForegroundColor Cyan
Push-Location $webRoot
try { npm run dev } finally { Pop-Location }
