# QuoteSync patch (SAFEWRITE): Seed default clients with 1 default estimate containing 5 positions
# Scope: ONLY src\features\clients\defaultClients.ts
# Fix: prior attempt didn't work because defaults are produced by makeDefaultClients() and there is no DEFAULT_CLIENTS constant.
#
# Run from: PS C:\Github\QuoteSync\web\ps1_patches>
#   Unblock-File .\THIS_SCRIPT.ps1
#   pwsh -ExecutionPolicy Bypass -File .\THIS_SCRIPT.ps1

$ErrorActionPreference = "Stop"
function Fail($m){ Write-Host "ERROR: $m" -ForegroundColor Red; throw $m }
function Ok($m)  { Write-Host "OK: $m" -ForegroundColor Green }

$runDir = (Get-Location).Path
Write-Host ("Run directory: " + $runDir)

$webRoot = Resolve-Path (Join-Path $runDir "..") | Select-Object -ExpandProperty Path
if (-not (Test-Path (Join-Path $webRoot "package.json"))) { Fail "Could not detect web root (package.json not found) at: $webRoot" }
Ok ("Detected web root: " + $webRoot)

$rel = "src\features\clients\defaultClients.ts"
$path = Join-Path $webRoot $rel
if (-not (Test-Path $path)) { Fail "Missing file: $path" }

$backupsRoot = Join-Path $webRoot "_backups"
New-Item -ItemType Directory -Force -Path $backupsRoot | Out-Null
$stamp = Get-Date -Format "yyyyMMdd_HHmmss"
$backupDir = Join-Path $backupsRoot $stamp
New-Item -ItemType Directory -Force -Path $backupDir | Out-Null
Ok ("Backup folder: " + $backupDir)

Copy-Item -Force $path (Join-Path $backupDir "defaultClients.ts")
Ok ("Backed up " + $rel)

$fixed = @'
// Auto-generated by QuoteSync Phase 4C extraction patch.
// Seed/demo clients moved out of src/App.tsx (no logic changes).
import * as Models from "../../models/types";
import type { Client, Estimate, Position } from "../../models/types";
import { makeDefaultEstimateDefaults } from "../estimateDefaults/defaultEstimateDefaults";

export const DEFAULT_CUSTOMER_ADDRESS = ["4 Glebe Road", "Cowdenbeath", "Fife", "KY4 9FA"].join("\n");

function makeDemoPositions(opts: { uid: () => string }): Position[] {
  const mk = (n: number, w: number, h: number): Position => ({
    id: Models.asPositionId(opts.uid()),
    positionRef: `W-${String(n).padStart(3, "0")}`,
    qty: 1,
    roomName: "",
    widthMm: w,
    heightMm: h,
    fieldsX: 1,
    fieldsY: 1,
    insertion: "Fixed",
    cellInsertions: { "0,0": "Fixed" },
    positionType: "Window",
    useEstimateDefaults: true,
    overrides: {},
  });

  return [
    mk(1, 1000, 1200),
    mk(2, 900, 900),
    mk(3, 1200, 1050),
    mk(4, 800, 2100),
    mk(5, 1500, 1200),
  ];
}

function makeDemoEstimate(opts: { uid: () => string }, n: number): Estimate {
  const year = new Date().getFullYear();
  const base = `${year}-90${String(n).padStart(2, "0")}`;

  return {
    id: Models.asEstimateId(opts.uid()),
    estimateRef: base,
    baseEstimateRef: base,
    revisionNo: 0,
    status: "Draft",
    defaults: makeDefaultEstimateDefaults(),
    positions: makeDemoPositions(opts),
  };
}

export function makeDefaultClients(opts: { uid: () => string; nextClientRef: (n: number) => string }): Client[] {
  return [
    {
      id: Models.asClientId(opts.uid()),
      type: "Business",
      clientRef: opts.nextClientRef(1),
      clientName: "Ecofenster Ltd",
      businessName: "Ecofenster Ltd",
      contactPerson: "",
      email: "",
      mobile: "07882 809 453",
      home: "",
      projectName: "",
      projectAddress: DEFAULT_CUSTOMER_ADDRESS,
      invoiceAddress: DEFAULT_CUSTOMER_ADDRESS,
      estimates: [makeDemoEstimate(opts, 1)],
    },
    {
      id: Models.asClientId(opts.uid()),
      type: "Individual",
      clientRef: opts.nextClientRef(2),
      clientName: "Craig Ferguson",
      businessName: "",
      contactPerson: "",
      email: "",
      mobile: "07882 809 453",
      home: "",
      projectName: "",
      projectAddress: DEFAULT_CUSTOMER_ADDRESS,
      invoiceAddress: DEFAULT_CUSTOMER_ADDRESS,
      estimates: [makeDemoEstimate(opts, 2)],
    },
  ];
}

'@

Set-Content -Path $path -Value $fixed -Encoding UTF8
Ok ("Wrote " + $rel)

Write-Host ""
Write-Host "Starting dev server..." -ForegroundColor Cyan
Push-Location $webRoot
try { npm run dev } finally { Pop-Location }
